import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

describe('memory workbench settings page', () => {
  it('lives under the modules settings area as Memory with all visible loop tabs', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')

    expect(source).toContain('useAlicizationMemoryWorkbenchStore')
    expect(source).toContain('\'working\'')
    expect(source).toContain('\'long-term\'')
    expect(source).toContain('\'review\'')
    expect(source).toContain('\'probe\'')
    expect(source).toContain('\'persona\'')
    expect(source).toContain('\'health\'')
    expect(source).toContain('settings.pages.memory.workbench.title')
    expect(source).toContain('titleKey: settings.pages.memory.workbench.title')
    expect(source).not.toContain('settingsEntry: true')
  })

  it('keeps the old memory route as a compatibility redirect instead of a settings entry', () => {
    const source = readFileSync(new URL('./index.vue', import.meta.url), 'utf8')

    expect(source).toContain('router.replace(\'/settings/modules/memory\')')
    expect(source).not.toContain('settingsEntry: true')
  })

  it('exposes Memory from the modules list', () => {
    const source = readFileSync(new URL('../../../../../../../packages/stage-ui/src/composables/use-modules-list.ts', import.meta.url), 'utf8')

    expect(source).toContain('id: \'memory\'')
    expect(source).toContain('to: \'/settings/modules/memory\'')
    expect(source).toContain('settings.pages.modules.memory.title')
  })

  it('keeps user-facing memory UI outside performance visualizer', () => {
    const source = readFileSync(new URL('../../devtools/performance-visualizer.vue', import.meta.url), 'utf8')

    expect(source).not.toContain('useAlicizationMemoryWorkbenchStore')
  })

  it('renders productized long-term filters and health sections', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')

    expect(source).toContain('longTermFilters')
    expect(source).toContain('loadMoreLongTerm')
    expect(source).toContain('settings.pages.memory.workbench.fields.semantic_channel')
    expect(source).toContain('recallProbe.semantic')
    expect(source).toContain('settings.pages.memory.workbench.fields.queue_health')
    expect(source).toContain('settings.pages.memory.workbench.fields.embedding_health')
  })

  it('localizes long-term memory search filters instead of rendering raw enum values', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')

    expect(source).toContain('settings.pages.memory.workbench.placeholders.long_term_search')
    expect(source).toContain('settings.pages.memory.workbench.placeholders.long_term_source')
    expect(source).toContain('settings.pages.memory.workbench.filters.kind.')
    expect(source).toContain('settings.pages.memory.workbench.filters.sensitivity.')
    expect(source).toContain('settings.pages.memory.workbench.filters.visibility.')
    expect(source).toContain('settings.pages.memory.workbench.filters.training.')
    expect(source).toContain('formatLongTermFilterLabel(')
    expect(source).not.toContain('{{ option }}')
  })

  it('renders persona candidate panel and embedding reindex action', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')

    expect(source).toContain('personaCandidates')
    expect(source).toContain('applyPersonaCandidateAction')
    expect(source).toContain('reindexEmbeddings')
    expect(source).toContain('settings.pages.memory.workbench.fields.behavior_lesson')
    expect(source).toContain('settings.pages.memory.workbench.actions.reindex_embeddings')
  })

  it('renders the local persona trainer configuration and durable run controls', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')
    const configSource = readFileSync(new URL('../modules/components/persona-training-executor-config.vue', import.meta.url), 'utf8')
    const runsSource = readFileSync(new URL('../modules/components/persona-training-runs.vue', import.meta.url), 'utf8')

    expect(source).toContain('<PersonaTrainingExecutorConfig />')
    expect(source).toContain('<PersonaTrainingRuns')
    expect(configSource).toContain('loadPersonaTrainingExecutorConfig')
    expect(configSource).toContain('savePersonaTrainingExecutorConfig')
    expect(configSource).toContain('testPersonaTrainingExecutor')
    expect(configSource).toContain('persona_training_executor_description')
    expect(configSource).not.toContain('fixedArgumentsText')
    expect(configSource).not.toContain('persona_training_fixed_arguments')
    expect(runsSource).toContain('refreshPersonaTrainingRuns')
    expect(runsSource).toContain('cancelPersonaTraining')
    expect(runsSource).toContain('personaTrainingRun.artifact.activation.status')
    expect(runsSource).toContain('personaTrainingRun.artifact.activation.loaderId')
    expect(runsSource).toContain('personaTrainingRun.artifact.activation.receiptId')
    expect(runsSource).toContain('personaTrainingRun.artifact.activation.activatedAt')
    expect(runsSource).toContain('persona_training_loader_id')
    expect(runsSource).toContain('persona_training_receipt_id')
    expect(runsSource).toContain('persona_training_activated_at')
    expect(runsSource).toContain('persona_training_increment_')
    expect(runsSource).toContain('persona_training_cleanup_pending')
    expect(runsSource).toContain('increment.cleanup.lastError')
    expect(runsSource).toContain('\'terminalizing\'')
    expect(runsSource).toContain('cancelableStatuses')
    expect(runsSource).not.toContain('{{ increment.state }}')
    expect(runsSource).not.toContain('已激活')
    expect(source).toContain('resetPersonaTrainingScope')
  })

  it('keeps polling terminalizing persona runs while disabling late cancellation', () => {
    const storeSource = readFileSync(new URL('../../../../../../../packages/stage-ui/src/stores/alicization-memory-workbench.ts', import.meta.url), 'utf8')
    const zhSource = readFileSync(new URL('../../../../../../../packages/i18n/src/locales/zh-Hans/settings.yaml', import.meta.url), 'utf8')
    const enSource = readFileSync(new URL('../../../../../../../packages/i18n/src/locales/en/settings.yaml', import.meta.url), 'utf8')

    expect(storeSource).toContain('\'terminalizing\'')
    expect(zhSource).toContain('persona_training_terminalizing:')
    expect(enSource).toContain('persona_training_terminalizing:')
  })

  it('renders dataset governance controls and truthful vector index health', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')

    expect(source).toContain('personaTrainingDataset')
    expect(source).toContain('refreshPersonaTrainingDataset')
    expect(source).toContain('stagePersonaTrainingDataset')
    expect(source).toContain('exportPersonaTrainingDataset')
    expect(source).toContain('activatePersonaTrainingDataset')
    expect(source).toContain('rollbackPersonaTrainingDataset')
    expect(source).toContain('revokePersonaTrainingDatasetSource')
    expect(source).toContain('setPersonaTrainingDatasetExamplePolicy')
    expect(source).toContain('settings.pages.memory.workbench.fields.dataset_consent')
    expect(source).toContain('settings.pages.memory.workbench.fields.pii_status')
    expect(source).toContain('settings.pages.memory.workbench.fields.index_mode')
    expect(source).toContain('settings.pages.memory.workbench.fields.native_index')
    expect(source).toContain('settings.pages.memory.workbench.fields.search_ready')
    expect(source).toContain('settings.pages.memory.workbench.fields.canonical_count')
    expect(source).toContain('settings.pages.memory.workbench.fields.indexed_count')
    expect(source).toContain('settings.pages.memory.workbench.fields.missing_count')
    expect(source).toContain('settings.pages.memory.workbench.fields.text_hash_mismatch_count')
    expect(source).toContain('settings.pages.memory.workbench.fields.stale_or_failed_count')
    expect(source).toContain('settings.pages.memory.workbench.fields.orphaned_count')
    expect(source).toContain('settings.pages.memory.workbench.fields.coverage_ratio')
    expect(source).toContain('formatCoverageRatio(')
    expect(source).not.toContain('pending: {{')
    expect(source).not.toContain('deadLettered: {{')
  })

  it('renders durable reindex progress, cancellation, retry, and transparent provider errors', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')

    expect(source).toContain('reindexProgress')
    expect(source).toContain('cancelReindexJob')
    expect(source).toContain('retryDeadLetterReindex')
    expect(source).toContain('reindexDeadLetterItems')
    expect(source).toContain('deadLetterItem.itemId')
    expect(source).toContain('deadLetterItem.sourceId')
    expect(source).toContain('deadLetterItem.attemptCount')
    expect(source).toContain('deadLetterItem.lastError')
    expect(source).toContain('reindexProgress.lastError')
    expect(source).toContain('settings.pages.memory.workbench.actions.cancel_reindex')
    expect(source).toContain('settings.pages.memory.workbench.actions.retry_dead_letter')
  })

  it('renders production embedding configuration controls first with model discovery and connectivity testing', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')
    const embeddingConfigSource = readFileSync(new URL('../modules/components/memory-embedding-config.vue', import.meta.url), 'utf8')
    const embeddingConfigIndex = source.indexOf('<MemoryEmbeddingConfig />')
    const tabIndex = source.indexOf('v-for="tab in tabs"')

    expect(embeddingConfigIndex).toBeGreaterThan(0)
    expect(tabIndex).toBeGreaterThan(embeddingConfigIndex)
    expect(source).toContain('<MemoryEmbeddingConfig />')
    expect(source).not.toContain('const memoryEmbeddingBaseUrl')
    expect(embeddingConfigSource).toContain('memoryEmbeddingBaseUrl')
    expect(embeddingConfigSource).toContain('memoryEmbeddingApiKey')
    expect(embeddingConfigSource).toContain('memoryEmbeddingProviderId')
    expect(embeddingConfigSource).toContain('memoryEmbeddingModel')
    expect(embeddingConfigSource).toContain('memoryEmbeddingModelSearch')
    expect(embeddingConfigSource).toContain('memoryEmbeddingDimensions')
    expect(embeddingConfigSource).toContain('discoverEmbeddingModels')
    expect(embeddingConfigSource).toContain('selectEmbeddingModel')
    expect(embeddingConfigSource).toContain('testEmbeddingConnection')
    expect(embeddingConfigSource).toContain('saveEmbeddingConfig')
    expect(embeddingConfigSource).toContain('onUnmounted')
    expect(embeddingConfigSource).toContain('LEGACY_MEMORY_EMBEDDING_CONFIG_KEY')
    expect(embeddingConfigSource).toContain('store.embeddingConnectionTest = null')
    expect(embeddingConfigSource).toContain('settings.pages.memory.workbench.actions.discover_embedding_models')
    expect(embeddingConfigSource).toContain('settings.pages.memory.workbench.actions.test_embedding_connection')
    expect(embeddingConfigSource).toContain('settings.pages.memory.workbench.actions.save_embedding_config')
  })

  it('uses a card-scoped replay session picker instead of a manual replay pack id', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')
    const pickerSource = readFileSync(new URL('../modules/components/memory-quality-session-picker.vue', import.meta.url), 'utf8')

    expect(source).toContain('<MemoryQualitySessionPicker')
    expect(source).toContain('qualityReplaySessions')
    expect(source).toContain('selectedQualitySessionId')
    expect(source).toContain('qualityTrialMode')
    expect(source).toContain('loadMoreQualityReplaySessions')
    expect(source).toContain('watch(activeCardId')
    expect(source).toContain('resetQualityTrialContext')
    expect(source).toContain('@update:selected-session-id="store.selectQualityTrialSession"')
    expect(source).toContain('@update:mode="store.setQualityTrialMode"')
    expect(source).toContain(':disabled="qualityReplaySessionsLoading || !selectedQualitySessionId"')
    expect(source).not.toContain('qualityReplayPackId')
    expect(source).not.toContain('replay_pack_id')
    expect(pickerSource).toContain('historical-replay')
    expect(pickerSource).toContain('live-provider')
    expect(pickerSource).toContain('settings.pages.memory.workbench.quality.live_provider_notice')
  })

  it('renders durable semantic scale controls, progress, dead-letter retry, and report history', () => {
    const source = readFileSync(new URL('../modules/memory.vue', import.meta.url), 'utf8')
    const zhHans = readFileSync(new URL('../../../../../../../packages/i18n/src/locales/zh-Hans/settings.yaml', import.meta.url), 'utf8')
    const english = readFileSync(new URL('../../../../../../../packages/i18n/src/locales/en/settings.yaml', import.meta.url), 'utf8')

    expect(source).toContain('semanticScaleTier')
    expect(source).toContain('semanticScaleJob')
    expect(source).toContain('semanticScaleJobs')
    expect(source).toContain('startSemanticScaleJob')
    expect(source).toContain('cancelSemanticScaleJob')
    expect(source).toContain('retrySemanticScaleJob')
    expect(source).toContain('resetSemanticScaleJobContext')
    expect(source).toContain('loadSemanticScaleJobs')
    expect(source).toContain('v-for="tier in [\'10k\', \'100k\'] as const"')
    expect(source).toContain(':value="tier"')
    expect(source).toContain('semanticScaleJob.progress.ratio')
    expect(source).toContain('semanticScaleJob?.deadLettered')
    expect(source).toContain('semanticScaleJob.report')
    expect(source).toContain('semanticScaleJob.report.passed')
    expect(source).toContain('v-for="check in semanticScaleJob.report.summary.failingChecks"')
    expect(source).toContain('v-for="action in semanticScaleJob.report.recommendedNextActions"')
    expect(source).toContain('v-for="job in semanticScaleJobs"')
    expect(source).toContain('@click="store.selectSemanticScaleJob(job.jobId)"')
    expect(source).toContain('@click.stop="store.refreshSemanticScaleJob(job.jobId)"')
    expect(source).toContain('@click.stop="store.cancelSemanticScaleJob(job.jobId')
    expect(source).toContain('@click.stop="store.retrySemanticScaleJob(job.jobId)"')
    expect(source).not.toContain(':disabled="Boolean(semanticScaleJob &&')
    expect(source).toContain('watch(activeCardId')
    expect(zhHans).toContain('start_semantic_scale: 开始语义规模压测')
    expect(zhHans).toContain('semantic_scale_history: 历史报告')
    expect(zhHans).toContain('semantic_scale_quality_failed: 质量检查未通过')
    expect(zhHans).toContain('semantic_scale_failing_checks: 未通过检查')
    expect(zhHans).toContain('semantic_scale_recommended_actions: 建议动作')
    expect(english).toContain('start_semantic_scale: Start Semantic Scale Soak')
    expect(english).toContain('semantic_scale_history: Report History')
    expect(english).toContain('semantic_scale_quality_failed: Quality Checks Failed')
    expect(english).toContain('semantic_scale_failing_checks: Failing Checks')
    expect(english).toContain('semantic_scale_recommended_actions: Recommended Actions')
  })
})
