import { describe, expect, it } from 'vitest'

import { buildAlicizationEmbodimentScript } from './director'

describe('director micro-expression timing', () => {
  it('adds pre-utterance and post-utterance cues for gentle chinese guidance turns', () => {
    const script = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-1',
        turnId: 'turn-1',
        replyText: '先看这里，然后点保存。',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-1',
          reply: '先看这里，然后点保存。',
          emotion: 'thinking',
          segments: [],
        },
        digitalLife: null,
        digitalLifeSpine: null,
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    expect(script.facePlan.preUtteranceCue).toBeTruthy()
    expect(script.facePlan.postUtteranceCue).toBeTruthy()
  })

  it('preserves timeline facial hold windows on segment speaking cues', () => {
    const script = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-hold',
        turnId: 'turn-hold',
        replyText: '先看这里，然后点保存。',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-hold',
          reply: '先看这里，然后点保存。',
          emotion: 'thinking',
          segments: [
            {
              id: 'segment-1',
              index: 0,
              startOffset: 0,
              endOffset: 5,
              text: '先看这里，',
              emotion: 'thinking',
              gestureWeight: 0.24,
              facialWeight: 0.38,
              prosodyWeight: 0.76,
              beatWeight: 0.52,
              facialHoldMs: 360,
              actionHoldMs: 140,
              actionCue: 'point_screen',
              facialCue: 'focused',
              actionWindow: 'segment-start',
              interruptMode: 'soft-interrupt',
            },
          ],
        },
        digitalLife: null,
        digitalLifeSpine: null,
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    expect(script.facePlan.speakingCues[0]).toEqual(expect.objectContaining({
      segmentId: 'segment-1',
      facialCue: 'focused',
      holdMs: 360,
    }))
  })

  it('derives segment-level face enter and release cues from chinese prosody timing', () => {
    const script = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-segment-face-timing',
        turnId: 'turn-segment-face-timing',
        replyText: '先看这里，然后确认了吗？',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-segment-face-timing',
          reply: '先看这里，然后确认了吗？',
          emotion: 'thinking',
          segments: [
            {
              id: 'segment-comma',
              index: 0,
              startOffset: 0,
              endOffset: 5,
              text: '先看这里，',
              emotion: 'thinking',
              gestureWeight: 0.24,
              facialWeight: 0.38,
              prosodyWeight: 0.76,
              beatWeight: 0.52,
              facialHoldMs: 360,
              actionHoldMs: 140,
              actionCue: 'point_screen',
              facialCue: 'focused',
              actionWindow: 'segment-start',
              interruptMode: 'soft-interrupt',
            },
            {
              id: 'segment-question',
              index: 1,
              startOffset: 5,
              endOffset: 13,
              text: '然后确认了吗？',
              emotion: 'thinking',
              gestureWeight: 0.32,
              facialWeight: 0.46,
              prosodyWeight: 0.82,
              beatWeight: 0.58,
              facialHoldMs: 420,
              actionHoldMs: 180,
              actionCue: 'idle_gentle_nod',
              facialCue: 'focused',
              actionWindow: 'cadence-peak',
              interruptMode: 'soft-interrupt',
            },
          ],
        },
        digitalLife: null,
        digitalLifeSpine: null,
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    expect(script.facePlan.speakingCues).toEqual([
      expect.objectContaining({
        segmentId: 'segment-comma',
        source: 'prosody-authority',
        confidence: 0.94,
        preUtteranceCue: 'steady-inhale',
        postUtteranceCue: 'soft-release',
      }),
      expect.objectContaining({
        segmentId: 'segment-question',
        source: 'prosody-authority',
        confidence: 0.94,
        preUtteranceCue: 'steady-inhale',
        postUtteranceCue: 'eyes-soften',
      }),
    ])
  })

  it('lets persona observe-first versus direct reconnect bias micro-expression timing when delivery is otherwise equal', () => {
    const observeFirst = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-persona-observe',
        turnId: 'turn-persona-observe',
        replyText: '继续吧。',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-persona-observe',
          reply: '继续吧。',
          emotion: 'thinking',
          segments: [],
        },
        digitalLife: null,
        digitalLifeSpine: {
          version: 'digital-life-spine-digest-v1',
          runtime: {
            watchMode: 'symbiotic-vision',
            sceneScenario: 'coding',
            sceneSummary: 'observe-first opening',
            activeThreadId: 'thread-observe',
            activeThreadTitle: 'observe line',
            dominantMode: 'thinking',
            dominantDrive: 'understand',
            answerIntent: 'guide',
            preferredPresence: 'attentive',
            selectedAction: 'hover',
            updatedAt: 1_000,
          },
          architecture: null,
          continuitySignal: null,
          proactive: {
            selectedAction: 'hover',
            preferredStyle: 'silent-observe',
            confidence: 0.7,
            shouldSpeak: false,
            activeThreadId: 'thread-observe',
            activeThreadTitle: 'observe line',
            dominantConcernKind: null,
            dominantConcernSummary: null,
            leadingGoalId: null,
            leadingGoalSummary: null,
            preferredPresence: 'attentive',
            personaBias: {
              relationshipPosture: 'observer',
              initiativeStyle: 'observant',
              silenceReconnect: 'hold',
              comfortStyle: 'quiet-presence',
              preferredProactiveStyle: 'silent-observe',
              manifestationCadenceSummary: 'persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.',
              openingGuidance: 'Open by observing first and keep the approach lighter.',
              whySummary: 'persona prefers observe-first room before a closer move.',
            },
          },
          embodiment: null,
          memory: null,
        },
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    const directReconnect = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-persona-direct',
        turnId: 'turn-persona-direct',
        replyText: '继续吧。',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-persona-direct',
          reply: '继续吧。',
          emotion: 'thinking',
          segments: [],
        },
        digitalLife: null,
        digitalLifeSpine: {
          version: 'digital-life-spine-digest-v1',
          runtime: {
            watchMode: 'symbiotic-vision',
            sceneScenario: 'coding',
            sceneSummary: 'direct opening',
            activeThreadId: 'thread-direct',
            activeThreadTitle: 'direct line',
            dominantMode: 'thinking',
            dominantDrive: 'guide',
            answerIntent: 'guide',
            preferredPresence: 'attentive',
            selectedAction: 'whisper',
            updatedAt: 1_000,
          },
          architecture: null,
          continuitySignal: null,
          proactive: {
            selectedAction: 'whisper',
            preferredStyle: 'light-nudge',
            confidence: 0.82,
            shouldSpeak: true,
            activeThreadId: 'thread-direct',
            activeThreadTitle: 'direct line',
            dominantConcernKind: null,
            dominantConcernSummary: null,
            leadingGoalId: null,
            leadingGoalSummary: null,
            preferredPresence: 'attentive',
            personaBias: {
              relationshipPosture: 'guardian',
              initiativeStyle: 'high-participation',
              silenceReconnect: 'direct-approach',
              comfortStyle: 'take-charge',
              preferredProactiveStyle: 'light-nudge',
              manifestationCadenceSummary: 'persona leans toward direct reconnect once the opening is real, so the return cadence can loosen earlier.',
              openingGuidance: 'Open directly with the live answer first and keep the approach lighter.',
              whySummary: 'persona prefers a direct reconnect once the opening is real.',
            },
          },
          embodiment: null,
          memory: null,
        },
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    expect(observeFirst.facePlan.preUtteranceCue).toBeTruthy()
    expect(directReconnect.facePlan.preUtteranceCue).toBeTruthy()
    expect(observeFirst.facePlan.postUtteranceCue).not.toBe(directReconnect.facePlan.postUtteranceCue)
  })

  it('lets long-horizon lower-pressure relationship timing slow speaking hold and release cadence even under the same gentle answer', () => {
    const lowerPressure = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-lower-pressure-timing',
        turnId: 'turn-lower-pressure-timing',
        replyText: '先看这里，然后继续。',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-lower-pressure-timing',
          reply: '先看这里，然后继续。',
          emotion: 'thinking',
          segments: [
            {
              id: 'segment-lower-pressure',
              index: 0,
              startOffset: 0,
              endOffset: 10,
              text: '先看这里，然后继续。',
              emotion: 'thinking',
              gestureWeight: 0.24,
              facialWeight: 0.38,
              prosodyWeight: 0.74,
              beatWeight: 0.48,
              facialHoldMs: 320,
              actionHoldMs: 140,
              actionCue: 'idle_gentle_nod',
              facialCue: 'focused',
              actionWindow: 'segment-start',
              interruptMode: 'soft-interrupt',
            },
          ],
        },
        digitalLife: null,
        digitalLifeSpine: {
          version: 'digital-life-spine-digest-v1',
          runtime: {
            watchMode: 'symbiotic-vision',
            sceneScenario: 'coding',
            sceneSummary: 'stay nearby without reopening too fast',
            activeThreadId: 'thread-lower-pressure',
            activeThreadTitle: 'lower-pressure line',
            dominantMode: 'thinking',
            dominantDrive: 'understand',
            answerIntent: 'guide',
            preferredPresence: 'attentive',
            selectedAction: 'hover',
            updatedAt: 1_000,
          },
          architecture: null,
          continuitySignal: null,
          proactive: {
            selectedAction: 'hover',
            preferredStyle: 'silent-observe',
            confidence: 0.72,
            shouldSpeak: true,
            activeThreadId: 'thread-lower-pressure',
            activeThreadTitle: 'lower-pressure line',
            dominantConcernKind: null,
            dominantConcernSummary: null,
            leadingGoalId: null,
            leadingGoalSummary: null,
            preferredPresence: 'attentive',
            personaBias: {
              relationshipPosture: 'observer',
              initiativeStyle: 'observant',
              silenceReconnect: 'hold',
              comfortStyle: 'quiet-presence',
              preferredProactiveStyle: 'silent-observe',
              manifestationCadenceSummary: 'persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.',
              openingGuidance: 'Open by observing first and keep the approach lighter.',
              whySummary: 'presence fits better than a quick close-in move.',
            },
          },
          embodiment: null,
          memory: null,
          outcomeLearning: {
            reflectionTargetScope: 'relationship',
            reflectionSummary: 'The room stayed warmer when pressure stayed low.',
            reflectionLesson: 'Keep more room before widening closeness again.',
            latestInflection: 'The last seam held because pressure stayed low and the return stayed slower.',
            revisionPressure: 0.22,
            autobiographicalStability: 0.86,
            learningReadiness: 0.8,
            contradictionPressure: 0.16,
            dominantTrajectory: 'lower-pressure timing preserves trust',
            activeLearningFocuses: ['relationship timing'],
            evolutionMomentum: 0.84,
            nextLearningAction: 'internalize',
            nextLearningReason: 'The relationship line is stabilizing around slower re-entry.',
            summary: 'Repair should settle before closeness expands, and the opening should keep more room.',
          },
        },
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    const baseline = buildAlicizationEmbodimentScript({
      seed: {
        decisionTraceId: 'trace-baseline-timing',
        turnId: 'turn-baseline-timing',
        replyText: '先看这里，然后继续。',
        performance: {
          baseEmotion: 'thinking',
          emotion: 'thinking',
          facialCue: 'focused',
          actionCue: 'idle_gentle_nod',
          delivery: 'gentle',
          emphasis: 1,
        },
        embodiment: null,
        speechTimeline: {
          version: 'speech-timeline-v1',
          variationToken: 'turn-baseline-timing',
          reply: '先看这里，然后继续。',
          emotion: 'thinking',
          segments: [
            {
              id: 'segment-baseline',
              index: 0,
              startOffset: 0,
              endOffset: 10,
              text: '先看这里，然后继续。',
              emotion: 'thinking',
              gestureWeight: 0.24,
              facialWeight: 0.38,
              prosodyWeight: 0.74,
              beatWeight: 0.48,
              facialHoldMs: 320,
              actionHoldMs: 140,
              actionCue: 'idle_gentle_nod',
              facialCue: 'focused',
              actionWindow: 'segment-start',
              interruptMode: 'soft-interrupt',
            },
          ],
        },
        digitalLife: null,
        digitalLifeSpine: {
          version: 'digital-life-spine-digest-v1',
          runtime: {
            watchMode: 'symbiotic-vision',
            sceneScenario: 'coding',
            sceneSummary: 'direct but still gentle answer',
            activeThreadId: 'thread-baseline',
            activeThreadTitle: 'baseline line',
            dominantMode: 'thinking',
            dominantDrive: 'guide',
            answerIntent: 'guide',
            preferredPresence: 'attentive',
            selectedAction: 'whisper',
            updatedAt: 1_000,
          },
          architecture: null,
          continuitySignal: null,
          proactive: {
            selectedAction: 'whisper',
            preferredStyle: 'light-nudge',
            confidence: 0.82,
            shouldSpeak: true,
            activeThreadId: 'thread-baseline',
            activeThreadTitle: 'baseline line',
            dominantConcernKind: null,
            dominantConcernSummary: null,
            leadingGoalId: null,
            leadingGoalSummary: null,
            preferredPresence: 'attentive',
            personaBias: {
              relationshipPosture: 'guardian',
              initiativeStyle: 'high-participation',
              silenceReconnect: 'direct-approach',
              comfortStyle: 'take-charge',
              preferredProactiveStyle: 'light-nudge',
              manifestationCadenceSummary: 'persona leans toward direct reconnect once the opening is real, so the return cadence can loosen earlier.',
              openingGuidance: 'Open directly with the live answer first and keep the approach lighter.',
              whySummary: 'the opening is real enough for a clearer reconnect.',
            },
          },
          embodiment: null,
          memory: null,
          outcomeLearning: null,
        },
      },
      manifest: {
        renderer: 'live2d',
        supportedBaseEmotions: ['neutral', 'thinking'],
        supportedFacialCues: [],
        supportedActions: [],
        supportsLookAt: true,
        supportsVisemeLipSync: true,
        supportsMicroDynamics: true,
      },
      residentPerformance: null,
      rendererTarget: 'live2d',
    })

    expect(lowerPressure.facePlan.speakingCues[0]?.holdMs).toBeGreaterThan(baseline.facePlan.speakingCues[0]?.holdMs ?? 0)
    expect(lowerPressure.motionPlan.actionBursts[0]?.holdMs).toBeGreaterThan(baseline.motionPlan.actionBursts[0]?.holdMs ?? 0)
    expect(lowerPressure.facePlan.postUtteranceCue).toBe('soft-release')
  })
})
