import { describe, expect, it } from 'vitest'

import {
  buildAlicizationAnswerPlannerSystemBlock,
  buildAnswerPlanner,
} from './answer-planner'

const baseContext = {
  localTime: { hour: 14, minute: 0, isLateNight: false },
  system: {
    cpuUsage: 18,
    battery: { percent: 82, charging: true },
    memory: { usagePercent: 36, freeMB: 4096, totalMB: 8192 },
    idleSeconds: 12,
    inputActivity: 'active' as const,
    fullscreenLikely: false,
    foregroundWindow: {
      appName: 'Cursor',
      processName: 'Cursor',
      title: 'runtime.ts - diff',
      pid: 7,
    },
    degradedSignals: [],
  },
  workload: {
    kind: 'coding' as const,
    confidence: 0.88,
    source: 'foreground-window-heuristic' as const,
    matchedLabels: ['cursor'],
  },
  content: {
    kind: 'diff' as const,
    confidence: 0.84,
    source: 'foreground-window-heuristic' as const,
    matchedLabels: ['diff'],
    summary: 'runtime.ts - diff',
  },
  relationship: {
    hostAttitude: '礼貌而克制，保持观察',
    boredom: 14,
    loneliness: 18,
    fatigue: 20,
    minutesSinceLastUserTurn: 2,
    reminderBacklog: 0,
    lateNightActiveMinutes: 0,
    recentProactiveOutcomes: [],
  },
}

describe('buildAnswerPlanner', () => {
  it('chooses guide when a live diff knot is the governing concern', () => {
    const planner = buildAnswerPlanner({
      now: 30_000,
      context: baseContext,
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'runtime.ts diff',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        target: null,
        beganAt: 0,
        lastSeenAt: 30_000,
      },
      worldModel: {
        activeThread: {
          id: 'thread::runtime-diff',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts diff',
          summary: 'The host is checking where the runtime diff is wrong.',
          confidence: 0.86,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 30_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 30_000,
          attentionAgeMs: 30_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 30_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered', 'imagined'],
        live: {
          kind: 'live',
          summary: 'The diff is live and grounded.',
          confidence: 0.9,
          stability: 0.84,
          focusThreadId: 'thread::runtime-diff',
          evidence: ['grounded-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 30_000,
      },
      concernContinuity: {
        governingEntryId: 'entry::runtime',
        entries: [{
          id: 'entry::runtime',
          sourceConcernId: 'concern-1',
          kind: 'help-fix',
          status: 'active',
          summary: 'She is still holding the runtime diff knot.',
          anchor: 'runtime.ts diff',
          targetThreadId: 'thread::runtime-diff',
          continuityWeight: 0.82,
          freshnessBias: 0.9,
          repairAffinity: 0.12,
          confidence: 0.84,
          createdAt: 0,
          lastUpdatedAt: 30_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.82,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 30_000,
      },
      repairLedger: null,
      commitmentLedger: null,
      inquiryPlanner: null,
      relationshipModel: {
        climate: 'attuned',
        approachVector: 'guide',
        receptivity: 0.62,
        sharedAttentionTrust: 0.68,
        correctionSensitivity: 0.22,
        reciprocityExpectation: 0.4,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 30_000,
      },
      privateThought: {
        stance: 'nudge',
        confidence: 0.78,
        rationaleTags: [],
        thoughtText: 'Stay with the real diff knot.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 90_000,
        afterglowFromScenario: null,
        emotionalTension: 'focused-flow',
      },
      mindKernel: {
        dominantMode: 'tracking',
        worldPressure: 0.72,
        epistemicPressure: 0.34,
        relationalPressure: 0.28,
        carePressure: 0.18,
        continuityPressure: 0.66,
        speakReadiness: 0.54,
        presenceWeight: 0.52,
        narrative: [],
        updatedAt: 30_000,
      },
      inspectionRequested: true,
    })

    expect(planner.act).toBe('guide')
    expect(planner.evidenceMode).toBe('live-grounded')
    expect(planner.governingFocus).toContain('runtime diff')
    expect(buildAlicizationAnswerPlannerSystemBlock(planner)).toContain('[ALICIZATION_ANSWER_PLAN]')
  })

  it('chooses correct-stale-anchor when continuity is outrunning live sight', () => {
    const planner = buildAnswerPlanner({
      now: 40_000,
      context: {
        ...baseContext,
        workload: {
          kind: 'browser',
          confidence: 0.32,
          source: 'foreground-window-heuristic',
          matchedLabels: ['browser'],
        },
        content: {
          kind: 'unknown',
          confidence: 0.22,
          source: 'foreground-window-heuristic',
          matchedLabels: [],
        },
      },
      currentScene: {
        workloadKind: 'browser',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'Desktop browser',
        source: 'foreground-window-heuristic',
        confidence: 0.44,
        target: null,
        beganAt: 32_000,
        lastSeenAt: 40_000,
      },
      worldModel: {
        activeThread: {
          id: 'thread::runtime-diff',
          kind: 'change-review',
          status: 'lingering',
          source: 'continuity',
          title: 'runtime.ts diff',
          summary: 'The old diff knot is still being carried.',
          confidence: 0.68,
          significance: 0.7,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 40_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 8_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 40_000,
      },
      worldOntology: {
        dominantFrame: 'remembered',
        truthPriority: ['live', 'remembered', 'imagined'],
        live: null,
        remembered: {
          kind: 'remembered',
          summary: 'Only remembered continuity is carrying the knot.',
          confidence: 0.66,
          stability: 0.52,
          focusThreadId: 'thread::runtime-diff',
          evidence: ['continuity'],
        },
        imagined: null,
        updatedAt: 40_000,
      },
      concernContinuity: {
        governingEntryId: 'entry::runtime',
        entries: [{
          id: 'entry::runtime',
          sourceConcernId: 'concern-1',
          kind: 'help-fix',
          status: 'carried',
          summary: 'She is still carrying the runtime diff knot.',
          anchor: 'runtime.ts diff',
          targetThreadId: 'thread::runtime-diff',
          continuityWeight: 0.74,
          freshnessBias: 0.24,
          repairAffinity: 0.58,
          confidence: 0.78,
          createdAt: 0,
          lastUpdatedAt: 40_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.74,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 40_000,
      },
      repairLedger: {
        governingRepairId: 'repair::stale',
        entries: [{
          id: 'repair::stale',
          kind: 'stale-scene-anchor',
          status: 'open',
          summary: 'The carried diff anchor may already be stale.',
          rationale: 'Continuity is outrunning fresh sight.',
          targetConcernEntryId: 'entry::runtime',
          urgency: 0.78,
          confidence: 0.74,
          createdAt: 0,
          lastUpdatedAt: 40_000,
          expiresAt: 120_000,
        }],
        repairPressure: 0.78,
        truthRisk: 0.72,
        shouldConstrainPresentTense: true,
        narrative: [],
        updatedAt: 40_000,
      },
      privateThought: {
        stance: 'uncertain',
        confidence: 0.72,
        rationaleTags: [],
        thoughtText: 'I should repair the old anchor before speaking plainly.',
        shouldSpeak: false,
        suggestedStyle: 'silent-observe',
        embodiedPresence: 'hesitant',
        expiresAt: 100_000,
        afterglowFromScenario: 'coding',
        emotionalTension: 'focused-flow',
      },
      inspectionRequested: true,
    })

    expect(planner.act).toBe('correct-stale-anchor')
    expect(planner.evidenceMode).toBe('repair-first')
    expect(planner.shouldAcknowledgeRepair).toBe(true)
  })

  it('chooses care when late-night body concern is governing the answer', () => {
    const planner = buildAnswerPlanner({
      now: 40_000,
      context: {
        ...baseContext,
        localTime: { hour: 1, minute: 20, isLateNight: true },
        workload: {
          kind: 'media',
          confidence: 0.62,
          source: 'foreground-window-heuristic',
          matchedLabels: ['music'],
        },
        content: {
          kind: 'music',
          confidence: 0.7,
          source: 'foreground-window-heuristic',
          matchedLabels: ['music'],
        },
        relationship: {
          ...baseContext.relationship,
          fatigue: 76,
          lateNightActiveMinutes: 120,
        },
      },
      currentScene: null,
      worldModel: {
        activeThread: {
          id: 'thread::late-night',
          kind: 'late-night-endurance',
          status: 'active',
          source: 'observed-scene',
          title: 'Late night session',
          summary: 'The host is still awake deep into the night.',
          confidence: 0.74,
          significance: 0.78,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 40_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 40_000,
          attentionAgeMs: 40_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'heavy',
        },
        updatedAt: 40_000,
      },
      concernContinuity: {
        governingEntryId: 'entry::care',
        entries: [{
          id: 'entry::care',
          sourceConcernId: 'concern-1',
          kind: 'care-body',
          status: 'active',
          summary: 'She is worried the host is dragging deeper into fatigue.',
          anchor: 'late night fatigue',
          continuityWeight: 0.8,
          freshnessBias: 0.66,
          repairAffinity: 0.18,
          confidence: 0.84,
          createdAt: 0,
          lastUpdatedAt: 40_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.8,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 40_000,
      },
      privateThought: {
        stance: 'care',
        confidence: 0.78,
        rationaleTags: [],
        thoughtText: 'The host needs care more than commentary right now.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'concerned',
        expiresAt: 100_000,
        afterglowFromScenario: null,
        emotionalTension: 'late-night-drain',
      },
      inspectionRequested: false,
    })

    expect(planner.act).toBe('care')
    expect(planner.relationshipPosture).toBe('tender')
  })
})
