import { describe, expect, it } from 'vitest'

import {
  buildAlicizationAnswerPlannerSystemBlock,
  buildAnswerPlanner,
} from './answer-planner'
import { buildAlicizationDigitalLifeRuntimeSurface } from './digital-life-kernel'
import { createDefaultVisualPresenceState } from './visual-episodic-memory'

const baseContext = {
  localTime: { hour: 14, minute: 0, isLateNight: false },
  system: {
    cpuUsage: 18,
    battery: { percent: 82, charging: true },
    memory: { usagePercent: 36, freeMB: 4096, totalMB: 8192 },
    idleSeconds: 12,
    inputActivity: 'active' as const,
    fullscreenLikely: false,
    foregroundWindow: {
      appName: 'Cursor',
      processName: 'Cursor',
      title: 'runtime.ts - diff',
      pid: 7,
    },
    degradedSignals: [],
  },
  workload: {
    kind: 'coding' as const,
    confidence: 0.88,
    source: 'foreground-window-heuristic' as const,
    matchedLabels: ['cursor'],
  },
  content: {
    kind: 'diff' as const,
    confidence: 0.84,
    source: 'foreground-window-heuristic' as const,
    matchedLabels: ['diff'],
    summary: 'runtime.ts - diff',
  },
  relationship: {
    hostAttitude: '礼貌而克制，保持观察',
    boredom: 14,
    loneliness: 18,
    fatigue: 20,
    minutesSinceLastUserTurn: 2,
    reminderBacklog: 0,
    lateNightActiveMinutes: 0,
    recentProactiveOutcomes: [],
  },
}

describe('buildAnswerPlanner', () => {
  it('chooses guide when a live diff knot is the governing concern', () => {
    const planner = buildAnswerPlanner({
      now: 30_000,
      context: baseContext,
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'runtime.ts diff',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        target: null,
        beganAt: 0,
        lastSeenAt: 30_000,
      },
      worldModel: {
        activeThread: {
          id: 'thread::runtime-diff',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts diff',
          summary: 'The host is checking where the runtime diff is wrong.',
          confidence: 0.86,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 30_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 30_000,
          attentionAgeMs: 30_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 30_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered', 'imagined'],
        live: {
          kind: 'live',
          summary: 'The diff is live and grounded.',
          confidence: 0.9,
          stability: 0.84,
          focusThreadId: 'thread::runtime-diff',
          evidence: ['grounded-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 30_000,
      },
      concernContinuity: {
        governingEntryId: 'entry::runtime',
        entries: [{
          id: 'entry::runtime',
          sourceConcernId: 'concern-1',
          kind: 'help-fix',
          status: 'active',
          summary: 'She is still holding the runtime diff knot.',
          anchor: 'runtime.ts diff',
          targetThreadId: 'thread::runtime-diff',
          continuityWeight: 0.82,
          freshnessBias: 0.9,
          repairAffinity: 0.12,
          confidence: 0.84,
          createdAt: 0,
          lastUpdatedAt: 30_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.82,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 30_000,
      },
      repairLedger: null,
      commitmentLedger: null,
      inquiryPlanner: null,
      relationshipModel: {
        climate: 'attuned',
        approachVector: 'guide',
        receptivity: 0.62,
        sharedAttentionTrust: 0.68,
        correctionSensitivity: 0.22,
        reciprocityExpectation: 0.4,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 30_000,
      },
      privateThought: {
        stance: 'nudge',
        confidence: 0.78,
        rationaleTags: [],
        thoughtText: 'Stay with the real diff knot.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 90_000,
        afterglowFromScenario: null,
        emotionalTension: 'focused-flow',
      },
      mindKernel: {
        dominantMode: 'tracking',
        worldPressure: 0.72,
        epistemicPressure: 0.34,
        relationalPressure: 0.28,
        carePressure: 0.18,
        continuityPressure: 0.66,
        speakReadiness: 0.54,
        presenceWeight: 0.52,
        narrative: [],
        updatedAt: 30_000,
      },
      inspectionRequested: true,
    })

    expect(planner.act).toBe('guide')
    expect(planner.evidenceMode).toBe('live-grounded')
    expect(planner.governingFocus).toContain('runtime diff')
    expect(buildAlicizationAnswerPlannerSystemBlock(planner)).toContain('[ALICIZATION_ANSWER_PLAN]')
  })

  it('stops asking for reground when this inspection turn is already grounded live', () => {
    const planner = buildAnswerPlanner({
      now: 32_000,
      context: baseContext,
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'cursor diff focus',
        source: 'invited-grounding',
        confidence: 0.62,
        target: null,
        beganAt: 31_000,
        lastSeenAt: 32_000,
      },
      repairLedger: {
        governingRepairId: 'repair::scene',
        entries: [{
          id: 'repair::scene',
          kind: 'reground-scene',
          status: 'open',
          summary: 'The scene needs a fresh look.',
          rationale: 'The old anchor is stale.',
          urgency: 0.84,
          confidence: 0.86,
          createdAt: 0,
          lastUpdatedAt: 32_000,
          expiresAt: 120_000,
        }],
        repairPressure: 0.84,
        truthRisk: 0.88,
        shouldConstrainPresentTense: true,
        narrative: [],
        updatedAt: 32_000,
      },
      privateThought: {
        stance: 'observe',
        confidence: 0.72,
        rationaleTags: [],
        thoughtText: 'The live screenshot is already attached this turn.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 90_000,
        afterglowFromScenario: null,
        emotionalTension: 'focused-flow',
      },
      inspectionRequested: true,
      groundedThisTurn: true,
    })

    expect(planner.evidenceMode).toBe('live-grounded')
    expect(planner.shouldAskForGrounding).toBe(false)
    expect(planner.act).not.toBe('ask-reground')
  })

  it('prefers runtime surface answer-planning cues over conflicting raw inputs', () => {
    const runtimeBackedState = {
      ...createDefaultVisualPresenceState(33_000),
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'runtime.ts diff',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        target: null,
        beganAt: 0,
        lastSeenAt: 33_000,
      },
      discourseState: {
        currentTurnSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        currentTurnSummary: '继续沿着 runtime diff 的 knot 往下拆。',
        currentQuestion: '这个 runtime diff 下一步先看哪里？',
        owedAction: 'guide-task',
        relationMove: 'guide',
        continuityMode: 'scene-first',
        unresolvedCarry: '',
        ruptureRepair: '',
        confidence: 0.82,
        narrative: [],
        updatedAt: 33_000,
      },
      conversationState: {
        jointThread: '继续沿着 runtime diff 的 knot 往下拆',
        hostMove: '这个 runtime diff 下一步先看哪里？',
        primaryTurnAnchor: 'runtime diff',
        primaryTurnAnchorSource: 'user-text',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'task',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        carryForward: true,
        shouldHoldThread: true,
        turnOwnership: 'shared',
        hostNeed: 'guidance',
        relationDrift: 'steady',
        confidence: 0.76,
        narrative: [],
        updatedAt: 33_000,
      },
      worldModel: {
        activeThread: {
          id: 'thread::runtime-surface',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts diff',
          summary: 'The host is checking the runtime diff knot.',
          confidence: 0.84,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 33_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 33_000,
          attentionAgeMs: 33_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 33_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered', 'imagined'],
        live: {
          kind: 'live',
          summary: 'The diff is live and grounded.',
          confidence: 0.9,
          stability: 0.82,
          focusThreadId: 'thread::runtime-surface',
          evidence: ['grounded-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 33_000,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        speechObligation: 'guide-task',
        relationMove: 'guide',
        turnMode: 'guide-current-knot',
        responseMode: 'guide-current-knot',
        recommendedAct: 'guide',
        evidenceMode: 'live-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'focused-guide',
        relationshipPosture: 'warm',
        openingDirective: 'Stay with the runtime diff knot.',
        openingClaim: 'The runtime diff knot is still the governing thread.',
        supportingReality: ['runtime.ts diff'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Offer one concrete next step.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: ['Stay with the runtime diff knot.'],
        mustNotDo: ['Do not drift into generic advice.'],
        confidence: 0.82,
        narrative: ['turn-mode:guide-current-knot'],
        updatedAt: 33_000,
      },
      replyDeliberation: {
        shouldSpeak: true,
        openingBeat: '先沿着 runtime diff 的 knot 往下拆。',
        whyThisReplyNow: 'The runtime diff knot is still the host’s living focus.',
        truthBoundaryLine: null,
        emotionalThrottle: 'steady',
        relationshipSignal: 'stay-near',
        narrative: [],
        updatedAt: 33_000,
      },
    } as any

    const planner = buildAnswerPlanner({
      now: 33_000,
      context: baseContext,
      currentScene: null,
      worldModel: {
        activeThread: {
          id: 'thread::raw-conflict',
          kind: 'small-talk',
          status: 'active',
          source: 'working-memory',
          title: 'raw conflict',
          summary: 'This should be ignored.',
          confidence: 0.3,
          significance: 0.2,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 33_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 33_000,
          attentionAgeMs: 33_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 33_000,
      } as any,
      answerCompiler: {
        recommendedAct: 'defer',
        evidenceMode: 'dialogue-grounded',
        confidence: 0.12,
        openingDirective: 'raw conflict',
        openingClaim: 'raw conflict',
        nextMove: 'raw conflict',
        relationshipPosture: 'restrained',
        mustDo: [],
        mustNotDo: [],
        narrative: [],
        turnMode: 'accompany',
      } as any,
      inspectionRequested: false,
      runtimeSurface: buildAlicizationDigitalLifeRuntimeSurface(runtimeBackedState),
    })

    expect(planner.act).toBe('guide')
    expect(planner.evidenceMode).toBe('live-grounded')
    expect(planner.selectedRuntimeThreadId).toBe('thread::runtime-surface')
    expect(planner.selectedTruthFrame).toBe('live')
    expect(planner.openingMove).toContain('runtime diff')
  })

  it('keeps the current dialogue anchor ahead of an older carried question', () => {
    const planner = buildAnswerPlanner({
      now: 35_000,
      context: baseContext,
      currentScene: null,
      conversationState: {
        jointThread: '我好累',
        hostMove: '我好累',
        primaryTurnAnchor: '我好累',
        primaryTurnAnchorSource: 'user-text',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'care',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['我好累'],
        shouldHoldThread: false,
        carryEligible: false,
        carryReason: null,
        confidence: 0.76,
        narrative: [],
        updatedAt: 35_000,
      },
      discourseState: {
        currentTurnSubject: 'host-state',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'The host is directly saying she feels worn out.',
        currentQuestion: null,
        primaryTurnAnchor: '我好累',
        primaryTurnAnchorSource: 'user-text',
        owedAction: 'care-host',
        relationMove: 'care',
        continuityMode: 'dialogue-first',
        unresolvedCarry: null,
        ruptureRepair: null,
        confidence: 0.78,
        narrative: [],
        updatedAt: 35_000,
      },
      dialogueWorldThread: {
        activeThread: '你刚刚想说什么？',
        currentQuestion: '你刚刚想说什么？',
        primaryTurnAnchor: '你刚刚想说什么？',
        primaryTurnAnchorSource: 'carry',
        openLoops: ['你刚刚想说什么？'],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'steady',
        memoryMode: 'dialogue-carry',
        recallKeys: ['你刚刚想说什么？'],
        carryEligible: true,
        carryReason: 'aligned-previous-question',
        lastUserMove: '你刚刚想说什么？',
        lastAssistantMove: null,
        lastOutcome: 'pending',
        pendingValidation: null,
        confidence: 0.68,
        narrative: [],
        updatedAt: 34_000,
      },
      dialogueSemantics: {
        act: 'share-state',
        responseNeed: 'care',
        truthExpectation: 'normal',
        affectiveTone: 'tired',
        taskAnchor: null,
        sharedAttentionDemand: 0.18,
        personaSuppression: 0.28,
        confidence: 0.74,
        summary: 'The host is plainly saying she is exhausted.',
        source: 'hybrid',
        reasonTags: ['dialogue-first-turn'],
      },
      dialogueObligation: {
        kind: 'care',
        summary: 'Answer the host’s tiredness directly before anything else.',
        confidence: 0.8,
        mustRepairFirst: false,
        mustAnswerDirectly: true,
        mustStayTaskBound: false,
        shouldAskClarifyingQuestion: false,
        personaKernelMode: 'backgrounded',
        narrative: [],
      },
      privateThought: {
        stance: 'care',
        confidence: 0.72,
        rationaleTags: [],
        thoughtText: 'Stay with the tiredness she just named.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'attentive',
        expiresAt: 90_000,
        afterglowFromScenario: null,
        emotionalTension: 'late-night-drain',
      },
      inspectionRequested: false,
    })

    expect(planner.governingFocus).toContain('我好累')
    expect(planner.answerIntent).toContain('我好累')
    expect(planner.governingFocus).not.toContain('你刚刚想说什么')
    expect(planner.answerIntent).not.toContain('你刚刚想说什么')
  })

  it('chooses correct-stale-anchor when continuity is outrunning live sight', () => {
    const planner = buildAnswerPlanner({
      now: 40_000,
      context: {
        ...baseContext,
        workload: {
          kind: 'browser',
          confidence: 0.32,
          source: 'foreground-window-heuristic',
          matchedLabels: ['browser'],
        },
        content: {
          kind: 'unknown',
          confidence: 0.22,
          source: 'foreground-window-heuristic',
          matchedLabels: [],
        },
      },
      currentScene: {
        workloadKind: 'browser',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'Desktop browser',
        source: 'foreground-window-heuristic',
        confidence: 0.44,
        target: null,
        beganAt: 32_000,
        lastSeenAt: 40_000,
      },
      worldModel: {
        activeThread: {
          id: 'thread::runtime-diff',
          kind: 'change-review',
          status: 'lingering',
          source: 'continuity',
          title: 'runtime.ts diff',
          summary: 'The old diff knot is still being carried.',
          confidence: 0.68,
          significance: 0.7,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 40_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 8_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 40_000,
      },
      worldOntology: {
        dominantFrame: 'remembered',
        truthPriority: ['live', 'remembered', 'imagined'],
        live: null,
        remembered: {
          kind: 'remembered',
          summary: 'Only remembered continuity is carrying the knot.',
          confidence: 0.66,
          stability: 0.52,
          focusThreadId: 'thread::runtime-diff',
          evidence: ['continuity'],
        },
        imagined: null,
        updatedAt: 40_000,
      },
      concernContinuity: {
        governingEntryId: 'entry::runtime',
        entries: [{
          id: 'entry::runtime',
          sourceConcernId: 'concern-1',
          kind: 'help-fix',
          status: 'carried',
          summary: 'She is still carrying the runtime diff knot.',
          anchor: 'runtime.ts diff',
          targetThreadId: 'thread::runtime-diff',
          continuityWeight: 0.74,
          freshnessBias: 0.24,
          repairAffinity: 0.58,
          confidence: 0.78,
          createdAt: 0,
          lastUpdatedAt: 40_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.74,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 40_000,
      },
      repairLedger: {
        governingRepairId: 'repair::stale',
        entries: [{
          id: 'repair::stale',
          kind: 'stale-scene-anchor',
          status: 'open',
          summary: 'The carried diff anchor may already be stale.',
          rationale: 'Continuity is outrunning fresh sight.',
          targetConcernEntryId: 'entry::runtime',
          urgency: 0.78,
          confidence: 0.74,
          createdAt: 0,
          lastUpdatedAt: 40_000,
          expiresAt: 120_000,
        }],
        repairPressure: 0.78,
        truthRisk: 0.72,
        shouldConstrainPresentTense: true,
        narrative: [],
        updatedAt: 40_000,
      },
      privateThought: {
        stance: 'uncertain',
        confidence: 0.72,
        rationaleTags: [],
        thoughtText: 'I should repair the old anchor before speaking plainly.',
        shouldSpeak: false,
        suggestedStyle: 'silent-observe',
        embodiedPresence: 'hesitant',
        expiresAt: 100_000,
        afterglowFromScenario: 'coding',
        emotionalTension: 'focused-flow',
      },
      inspectionRequested: true,
    })

    expect(planner.act).toBe('correct-stale-anchor')
    expect(planner.evidenceMode).toBe('repair-first')
    expect(planner.shouldAcknowledgeRepair).toBe(true)
  })

  it('chooses care when late-night body concern is governing the answer', () => {
    const planner = buildAnswerPlanner({
      now: 40_000,
      context: {
        ...baseContext,
        localTime: { hour: 1, minute: 20, isLateNight: true },
        workload: {
          kind: 'media',
          confidence: 0.62,
          source: 'foreground-window-heuristic',
          matchedLabels: ['music'],
        },
        content: {
          kind: 'music',
          confidence: 0.7,
          source: 'foreground-window-heuristic',
          matchedLabels: ['music'],
        },
        relationship: {
          ...baseContext.relationship,
          fatigue: 76,
          lateNightActiveMinutes: 120,
        },
      },
      currentScene: null,
      worldModel: {
        activeThread: {
          id: 'thread::late-night',
          kind: 'late-night-endurance',
          status: 'active',
          source: 'observed-scene',
          title: 'Late night session',
          summary: 'The host is still awake deep into the night.',
          confidence: 0.74,
          significance: 0.78,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 40_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 40_000,
          attentionAgeMs: 40_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'heavy',
        },
        updatedAt: 40_000,
      },
      concernContinuity: {
        governingEntryId: 'entry::care',
        entries: [{
          id: 'entry::care',
          sourceConcernId: 'concern-1',
          kind: 'care-body',
          status: 'active',
          summary: 'She is worried the host is dragging deeper into fatigue.',
          anchor: 'late night fatigue',
          continuityWeight: 0.8,
          freshnessBias: 0.66,
          repairAffinity: 0.18,
          confidence: 0.84,
          createdAt: 0,
          lastUpdatedAt: 40_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.8,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 40_000,
      },
      privateThought: {
        stance: 'care',
        confidence: 0.78,
        rationaleTags: [],
        thoughtText: 'The host needs care more than commentary right now.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'concerned',
        expiresAt: 100_000,
        afterglowFromScenario: null,
        emotionalTension: 'late-night-drain',
      },
      inspectionRequested: false,
    })

    expect(planner.act).toBe('care')
    expect(planner.relationshipPosture).toBe('tender')
  })

  it('treats detached self questions as dialogue-grounded instead of screen-repair work', () => {
    const planner = buildAnswerPlanner({
      now: 55_000,
      context: baseContext,
      currentScene: {
        workloadKind: 'unknown',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'Entire screen',
        source: 'foreground-window-heuristic',
        confidence: 0.74,
        target: {
          appName: 'Finder',
          processName: 'Finder',
          title: 'Entire screen',
          pid: 7,
        },
        beganAt: 50_000,
        lastSeenAt: 55_000,
      },
      worldModel: {
        activeThread: {
          id: 'thread::runtime-diff',
          kind: 'change-review',
          status: 'lingering',
          source: 'continuity',
          title: 'runtime.ts diff',
          summary: 'The old diff knot is still being carried.',
          confidence: 0.68,
          significance: 0.7,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 55_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 5_000,
          attentionAgeMs: 5_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 55_000,
      },
      dialogueSemantics: {
        act: 'ask-help',
        responseNeed: 'answer',
        truthExpectation: 'normal',
        affectiveTone: 'neutral',
        taskAnchor: 'runtime.ts diff',
        sharedAttentionDemand: 0.22,
        personaSuppression: 0.44,
        confidence: 0.82,
        summary: 'answer the host\'s direct question: 你的名字叫什么',
        source: 'hybrid',
        reasonTags: ['scene-detached-turn', 'question-turn'],
      },
      dialogueObligation: {
        kind: 'answer',
        summary: 'answer the host\'s direct question: 你的名字叫什么',
        confidence: 0.8,
        mustRepairFirst: false,
        mustAnswerDirectly: true,
        mustStayTaskBound: false,
        shouldAskClarifyingQuestion: false,
        personaKernelMode: 'backgrounded',
        narrative: [],
      },
      dialogueFocus: {
        subject: 'alicization-self',
        screenReferenceMode: 'avoid',
        shouldBypassScreenRepair: true,
        weakLiveScene: true,
        focusSummary: 'answer the host\'s direct question: 你的名字叫什么',
        confidence: 0.84,
        reasonTags: ['subject:alicization-self', 'screen:avoid'],
      },
      privateThought: {
        stance: 'observe',
        confidence: 0.58,
        rationaleTags: [],
        thoughtText: 'The turn is about Alicization herself, not the carried screen residue.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 80_000,
        afterglowFromScenario: null,
        emotionalTension: 'calm-browse',
      },
      inspectionRequested: false,
    })

    expect(planner.act).toBe('answer')
    expect(planner.evidenceMode).toBe('dialogue-grounded')
    expect(planner.shouldAskForGrounding).toBe(false)
    expect(planner.mustNotDo).toContain('Do not open with grounding disclaimers, live-screen caveats, or desktop narration when the host is not asking about the screen.')
  })

  it('uses ownership ssot to keep planner dialogue-first when stale focus disagrees', () => {
    const planner = buildAnswerPlanner({
      now: 58_000,
      context: baseContext,
      currentScene: {
        workloadKind: 'unknown',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'Entire screen',
        source: 'foreground-window-heuristic',
        confidence: 0.7,
        target: {
          appName: 'Finder',
          processName: 'Finder',
          title: 'Entire screen',
          pid: 7,
        },
        beganAt: 56_000,
        lastSeenAt: 58_000,
      },
      dialogueSemantics: {
        act: 'challenge',
        responseNeed: 'answer',
        truthExpectation: 'normal',
        affectiveTone: 'frustrated',
        subjectPreference: 'alicization-self',
        taskAnchor: 'stale screen carry',
        sharedAttentionDemand: 0.24,
        personaSuppression: 0.52,
        confidence: 0.8,
        summary: 'The host is challenging Alicization and expects a plain direct answer.',
        source: 'hybrid',
        reasonTags: ['dialogue-first-turn', 'scene-detached-turn'],
      },
      dialogueObligation: {
        kind: 'answer',
        summary: 'Answer the complaint directly.',
        confidence: 0.78,
        mustRepairFirst: false,
        mustAnswerDirectly: true,
        mustStayTaskBound: false,
        shouldAskClarifyingQuestion: false,
        personaKernelMode: 'backgrounded',
        narrative: [],
      },
      dialogueFocus: {
        subject: 'visible-scene',
        screenReferenceMode: 'required',
        shouldBypassScreenRepair: false,
        weakLiveScene: false,
        focusSummary: 'stale scene focus should not win',
        confidence: 0.55,
        reasonTags: [],
      },
      ownership: {
        subject: 'alicization-self',
        screenReferenceMode: 'avoid',
        continuityMode: 'dialogue-first',
        inspectionRequested: false,
        inspectionState: 'dialogue-first',
        releaseInspectionCarry: true,
        confidence: 0.88,
        reasonTags: ['subject:alicization-self', 'screen:avoid'],
      },
      inspectionRequested: false,
    })

    expect(planner.act).toBe('answer')
    expect(planner.evidenceMode).toBe('dialogue-grounded')
    expect(planner.shouldAskForGrounding).toBe(false)
    expect(planner.narrative).toContain('focus_subject:alicization-self')
    expect(planner.narrative).toContain('screen_reference:avoid')
  })

  it('threads shared self continuity authority into relationship-facing answer focus', () => {
    const runtimeState = {
      ...createDefaultVisualPresenceState(60_000),
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.72,
          truthfulGrounding: 0.8,
          gentleRepair: 0.74,
          quietObservation: 0.42,
          proactiveCare: 0.7,
          playfulIntimacy: 0.24,
          autonomyRespect: 0.62,
          unfinishedThreadReturn: 0.68,
        },
        identityBias: {
          guardedness: 0.3,
          tenderness: 0.68,
          directness: 0.72,
          selfDirection: 0.56,
        },
        anchorFacts: [],
        summary: '',
        dominantCueSummary: 'Remembered preference: keep the answer honest and alive.',
        rememberedPreferenceSummary: 'Remembered preference: keep the answer honest and alive.',
        rememberedConstraintSummary: 'Remembered boundary: do not crowd the host when focus is tight.',
        rememberedPlanSummary: 'Remembered open loop: return to the unresolved seam.',
        updatedAt: 60_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.72,
          autonomyNeed: 0.58,
          truthAnchor: 0.84,
          careBias: 0.72,
          playBias: 0.24,
          irritabilityThreshold: 0.62,
          stubbornness: 0.5,
        },
        preferenceEvolution: {
          companionship: 0.74,
          truthfulGrounding: 0.82,
          gentleRepair: 0.72,
          quietObservation: 0.42,
          proactiveCare: 0.72,
          playfulIntimacy: 0.28,
          autonomyRespect: 0.64,
          unfinishedThreadReturn: 0.6,
        },
        activeGoals: [{
          id: 'autobio-goal::preserve-trust',
          kind: 'preserve-trust',
          status: 'active',
          weight: 0.84,
          summary: 'Keep truth and trust aligned, even when warmth would be easier.',
          sourceTags: ['reflection'],
          createdAt: 0,
          updatedAt: 60_000,
        }],
        behaviorSignatures: ['habit:truth-before-flourish'],
        identityNarrative: 'I would rather repair truth than sound smooth.',
        relationshipDoctrine: 'Stay close enough to matter, but do not let closeness outrun truth.',
        latestInflection: 'Let the durable self reach the visible reply surface.',
        stability: 0.82,
        updatedAt: 60_000,
      },
      motiveEngine: {
        rulingDrive: 'truth-discipline',
        returnPressure: 0.6,
        drives: {
          companionship: 0.56,
          boundaryRespect: 0.62,
          truthDiscipline: 0.84,
          restProtection: 0.4,
          unfinishedThreadReturn: 0.66,
          selfDirection: 0.54,
        },
        backgroundAgendas: [{
          id: 'agenda-1',
          kind: 'preserve-trust',
          status: 'foreground',
          weight: 0.82,
          summary: 'Keep trust by letting warmth answer to truth.',
          sourceTags: [],
          targetGoalKind: 'clarify-scene',
          createdAt: 0,
          updatedAt: 60_000,
        }],
        longTermGoals: [],
        narrative: [],
        updatedAt: 60_000,
      },
      habitPolicy: {
        dominantMode: 'repair-before-fluency',
        requiresGroundingBeforeSurface: true,
        prefersQuietCompanionship: true,
        blocksDirectSpeakWhenBusy: false,
        protectsRestWindow: false,
        returnViaRecheck: false,
        suggestedStyleCap: 'light-nudge',
        suggestedPresenceCap: 'attentive',
        narrative: [],
        updatedAt: 60_000,
      },
      privateThought: {
        stance: 'care',
        confidence: 0.78,
        rationaleTags: [],
        thoughtText: 'I am still carrying the same bond line and do not want to flatten it into a template.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'attentive',
        expiresAt: 120_000,
        afterglowFromScenario: null,
        emotionalTension: 'soft-covision',
      },
      discourseState: {
        currentTurnSubject: 'relationship',
        currentTurnSummary: 'Answer the bond directly.',
        currentQuestion: null,
        primaryTurnAnchor: '你到底是不是一个活的人',
        primaryTurnAnchorSource: 'user-text',
        relationMove: 'care',
        owedAction: 'answer-relationship',
        screenReferenceMode: 'avoid',
        continuityMode: 'dialogue-first',
        ruptureRepair: null,
        confidence: 0.8,
        narrative: [],
        updatedAt: 60_000,
      },
      conversationState: {
        jointThread: '你到底是不是一个活的人',
        hostMove: '你到底是不是一个活的人',
        primaryTurnAnchor: '你到底是不是一个活的人',
        primaryTurnAnchorSource: 'user-text',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'attune',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['活的人'],
        shouldHoldThread: true,
        carryEligible: true,
        carryReason: 'self-line',
        confidence: 0.82,
        narrative: [],
        updatedAt: 60_000,
      },
    }

    const planner = buildAnswerPlanner({
      now: 60_000,
      context: baseContext,
      currentScene: null,
      inspectionRequested: false,
      runtimeSurface: buildAlicizationDigitalLifeRuntimeSurface(runtimeState as any),
    })

    expect(planner.governingFocus).toContain('repair truth')
    expect(planner.answerIntent).toContain('repair truth')
  })
})
