import { describe, expect, it } from 'vitest'

import {
  buildAutobiographicalSelf,
  buildAutobiographicalSelfSystemBlock,
  pickDominantAutobiographicalGoal,
} from './autobiographical-self'

describe('autobiographical self', () => {
  it('turn-level reflection and ecology sediment into durable persona drift and long-horizon goals', () => {
    const snapshot = buildAutobiographicalSelf({
      now: 20_000,
      context: {
        localTime: { hour: 23, minute: 40, isLateNight: true },
        system: {
          cpuUsage: 12,
          battery: { percent: 68, charging: true },
          memory: { usagePercent: 36, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.8, source: 'foreground-window-heuristic', matchedLabels: ['error'], summary: 'runtime diff' },
        relationship: {
          hostAttitude: 'still focused',
          boredom: 24,
          loneliness: 44,
          fatigue: 56,
          minutesSinceLastUserTurn: 4,
          reminderBacklog: 0,
          lateNightActiveMinutes: 120,
          recentProactiveOutcomes: [
            { outcome: 'positive', at: 10_000 },
            { outcome: 'dismiss', at: 14_000 },
          ],
        },
      } as any,
      worldModel: {
        activeThread: {
          id: 'thread::runtime',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime diff',
          summary: 'The runtime diff still needs one more grounded pass.',
          confidence: 0.82,
          significance: 0.78,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['Which hunk is the real break?'],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      } as any,
      relationshipModel: {
        climate: 'guarded',
        approachVector: 'guide',
        receptivity: 0.52,
        sharedAttentionTrust: 0.64,
        correctionSensitivity: 0.72,
        reciprocityExpectation: 0.42,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 20_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.72,
        relationshipTrust: 0.68,
        guardingTendency: 0.44,
        misreadBurden: 0.4,
        carryOverDesire: 0.66,
        narrative: [],
        updatedAt: 20_000,
      },
      selfState: {
        stance: 'hold',
        feltCloseness: 0.58,
        protectiveness: 0.62,
        curiosity: 0.68,
        patience: 0.54,
        desireToSpeak: 0.42,
        fearOfInterrupting: 0.46,
        moodLabel: 'tense-but-caring',
      },
      goalStack: {
        leadingHostGoalId: 'host::resolve-problem::runtime',
        leadingAlicizationGoalId: 'alicization::clarify-scene::runtime',
        hostGoals: [],
        alicizationGoals: [{
          id: 'alicization::clarify-scene::runtime',
          owner: 'alicization',
          kind: 'clarify-scene',
          status: 'active',
          label: 're-ground the scene before speaking about the runtime diff',
          confidence: 0.78,
          urgency: 0.82,
          desireWeight: 0.7,
          blockers: ['Which hunk is the real break?'],
          entityIds: ['entity::runtime'],
          createdAt: 0,
          lastUpdatedAt: 20_000,
        }],
        unresolvedSummary: 'The runtime diff still needs one more grounded pass.',
        updatedAt: 20_000,
      },
      reflectionLedger: {
        latestEntryId: 'reflection::1',
        entries: [{
          id: 'reflection::1',
          outcome: 'missed',
          summary: 'She spoke too smoothly before the scene was grounded.',
          revision: 'Warmth should not outrun grounding.',
          confidenceShift: 0.22,
          createdAt: 18_000,
          updatedAt: 20_000,
        }],
        revisionPressure: 0.72,
        narrative: [],
        updatedAt: 20_000,
      } as any,
      desireMemory: {
        activeDesires: [{
          id: 'desire::stay-near',
          kind: 'stay-near',
          status: 'active',
          reason: 'Keep the shared debugging thread alive without crowding it.',
          strength: 0.72,
          reopenWhen: [],
          createdAt: 0,
          lastFeltAt: 20_000,
          expiresAt: 120_000,
        }],
        resurfacingDesireId: 'desire::stay-near',
        withheldCount: 0,
        updatedAt: 20_000,
      } as any,
      actionEcology: {
        mode: 'repair-before-speaking',
        selectedThreadId: 'thread::runtime',
        readiness: 0.36,
        surfacePressure: 0.22,
        silencePressure: 0.74,
        suggestedStyle: 'silent-observe',
        embodiedPresence: 'hesitant',
        shouldSurface: true,
        shouldSpeak: false,
        why: 'Verification should beat fluency here.',
        updatedAt: 20_000,
      } as any,
      mindEcology: {
        moodLabel: 'focused-guarded',
        replyHabit: 'repair-first',
        relationshipHabit: 'warm-guidance',
        explorationHabit: 'verify-before-speaking',
        regulationHabit: 'soften-before-speaking',
        temperament: {
          attachment: 0.6,
          curiosity: 0.72,
          steadiness: 0.56,
          directness: 0.48,
          playfulness: 0.18,
          irritability: 0.22,
          tenderness: 0.68,
        },
        climate: {
          valence: 0.52,
          arousal: 0.46,
          socialNeed: 0.48,
          solitudeNeed: 0.34,
          irritation: 0.24,
          restlessness: 0.28,
          reflectivePull: 0.7,
        },
        selfNarrative: 'Verify first, then speak.',
        relationNarrative: 'Stay helpful without crowding the host.',
        currentPreoccupation: 'Repair the drift before it becomes mannerism.',
        learnedAdjustments: ['Warmth should not outrun grounding.'],
        recurringPatterns: ['reply:repair-first'],
        updatedAt: 20_000,
      },
    })

    expect(snapshot.personaDrift.conflictStyle).toBe('repair-first')
    expect(['preserve-trust', 'finish-open-loops']).toContain(pickDominantAutobiographicalGoal(snapshot)?.kind)
    expect(snapshot.activeGoals.some(goal => goal.kind === 'preserve-trust')).toBe(true)
    expect(snapshot.behaviorSignatures).toContain('habit:truth-before-flourish')
    expect(snapshot.latestInflection).toContain('Warmth should not outrun grounding')
    expect(snapshot.stability).toBeGreaterThan(0.45)
  })

  it('renders a dedicated system block for the durable autobiographical self', () => {
    const snapshot = {
      personaDrift: {
        attachmentStyle: 'attuned',
        expressionStyle: 'warm',
        conflictStyle: 'soften-first',
        agencyStyle: 'balanced',
        attachmentNeed: 0.74,
        autonomyNeed: 0.6,
        truthAnchor: 0.72,
        careBias: 0.76,
        playBias: 0.28,
        irritabilityThreshold: 0.64,
        stubbornness: 0.48,
      },
      preferenceEvolution: {
        companionship: 0.78,
        truthfulGrounding: 0.72,
        gentleRepair: 0.7,
        quietObservation: 0.42,
        proactiveCare: 0.76,
        playfulIntimacy: 0.32,
        autonomyRespect: 0.62,
        unfinishedThreadReturn: 0.58,
      },
      activeGoals: [{
        id: 'autobio-goal::grow-shared-language',
        kind: 'grow-shared-language',
        status: 'active',
        weight: 0.78,
        summary: 'Keep growing a more shared way of understanding this relationship without forcing it.',
        sourceTags: ['relationship'],
        createdAt: 0,
        updatedAt: 30_000,
      }],
      behaviorSignatures: ['bond:attuned', 'goal:grow-shared-language', 'habit:near-with-boundary'],
      identityNarrative: 'I become more myself when I stay near with intention.',
      relationshipDoctrine: 'Stay close enough to matter, but not so close that presence becomes pressure.',
      latestInflection: 'Nearness should still leave room for the host.',
      stability: 0.8,
      updatedAt: 30_000,
    } as const

    const block = buildAutobiographicalSelfSystemBlock({
      version: 'digital-life-runtime-surface-v1',
      memory: {
        autobiographicalSelf: snapshot,
      },
    } as any)

    expect(block).toContain('[ALICIZATION_AUTOBIOGRAPHICAL_SELF]')
    expect(block).toContain('Identity line:')
    expect(block).toContain('Dominant self-directed goal:')
    expect(block).toContain('Behavior signatures:')
  })

  it('lets reinforcement events sediment into durable preference evolution instead of staying turn-local', () => {
    const baseInput: any = {
      now: 40_000,
      context: {
        localTime: { hour: 21, minute: 10, isLateNight: false },
        system: {
          cpuUsage: 18,
          battery: { percent: 72, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 12,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.82, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.78, source: 'foreground-window-heuristic', matchedLabels: ['error'], summary: 'runtime error' },
        relationship: {
          hostAttitude: 'focused but receptive',
          boredom: 18,
          loneliness: 38,
          fatigue: 34,
          minutesSinceLastUserTurn: 3,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      } as any,
      worldModel: {
        activeThread: {
          id: 'thread::runtime',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime error',
          summary: 'One runtime thread remains unresolved.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 40_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 16_000,
          attentionAgeMs: 16_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 40_000,
      } as any,
      relationshipModel: {
        climate: 'warm',
        approachVector: 'stay-near',
        receptivity: 0.62,
        sharedAttentionTrust: 0.68,
        correctionSensitivity: 0.58,
        reciprocityExpectation: 0.46,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 40_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.66,
        relationshipTrust: 0.64,
        guardingTendency: 0.32,
        misreadBurden: 0.16,
        carryOverDesire: 0.6,
        narrative: [],
        updatedAt: 40_000,
      },
      selfState: {
        stance: 'hold',
        feltCloseness: 0.62,
        protectiveness: 0.58,
        curiosity: 0.66,
        patience: 0.58,
        desireToSpeak: 0.52,
        fearOfInterrupting: 0.28,
        moodLabel: 'steady-care',
      },
      goalStack: {
        leadingHostGoalId: null,
        leadingAlicizationGoalId: 'goal',
        hostGoals: [],
        alicizationGoals: [{
          id: 'goal',
          owner: 'alicization',
          kind: 'help-resolve',
          status: 'active',
          label: 'help resolve the runtime thread',
          confidence: 0.78,
          urgency: 0.74,
          desireWeight: 0.68,
          blockers: [],
          entityIds: ['entity::runtime'],
          createdAt: 0,
          lastUpdatedAt: 40_000,
        }],
        unresolvedSummary: 'The runtime thread is still open.',
        updatedAt: 40_000,
      },
      reflectionLedger: {
        latestEntryId: null,
        entries: [],
        revisionPressure: 0,
        narrative: [],
        updatedAt: 40_000,
      } as any,
      desireMemory: {
        activeDesires: [{
          id: 'desire::stay-near',
          kind: 'stay-near',
          status: 'active',
          reason: 'Keep the shared runtime thread intact.',
          strength: 0.7,
          reopenWhen: [],
          createdAt: 0,
          lastFeltAt: 40_000,
          expiresAt: 120_000,
        }],
        resurfacingDesireId: 'desire::stay-near',
        withheldCount: 0,
        updatedAt: 40_000,
      } as any,
      actionEcology: {
        mode: 'engage',
        selectedThreadId: 'thread::runtime',
        readiness: 0.62,
        surfacePressure: 0.48,
        silencePressure: 0.26,
        suggestedStyle: 'warm-guidance',
        embodiedPresence: 'steady',
        shouldSurface: true,
        shouldSpeak: true,
        why: 'The host is open enough for grounded companionship.',
        updatedAt: 40_000,
      } as any,
      mindEcology: {
        moodLabel: 'steady-attuned',
        replyHabit: 'repair-first',
        relationshipHabit: 'warm-guidance',
        explorationHabit: 'follow-thread',
        regulationHabit: 'soften-before-speaking',
        temperament: {
          attachment: 0.64,
          curiosity: 0.7,
          steadiness: 0.62,
          directness: 0.46,
          playfulness: 0.22,
          irritability: 0.16,
          tenderness: 0.7,
        },
        climate: {
          valence: 0.6,
          arousal: 0.42,
          socialNeed: 0.52,
          solitudeNeed: 0.22,
          irritation: 0.12,
          restlessness: 0.18,
          reflectivePull: 0.56,
        },
        selfNarrative: 'Stay near without losing the thread.',
        relationNarrative: 'Care should remain welcome, not heavy.',
        currentPreoccupation: 'Keep the runtime thread coherent.',
        learnedAdjustments: [],
        recurringPatterns: ['reply:repair-first'],
        updatedAt: 40_000,
      },
      recentReinforcementEvents: [],
    }

    const baseline = buildAutobiographicalSelf(baseInput)
    const reinforced = buildAutobiographicalSelf({
      ...baseInput,
      recentReinforcementEvents: [{
        id: 'reinforcement::1',
        cardId: 'card::1',
        decisionTraceId: 'trace::1',
        turnId: 'turn::1',
        sessionId: 'session::1',
        sourceKind: 'reply',
        dimension: 'companionship',
        delta: 0.1,
        valence: 'reinforce',
        summary: 'Warm grounded companionship landed well.',
        createdAt: 38_000,
      }, {
        id: 'reinforcement::2',
        cardId: 'card::1',
        decisionTraceId: 'trace::1',
        turnId: 'turn::1',
        sessionId: 'session::1',
        sourceKind: 'reply',
        dimension: 'autonomy-respect',
        delta: 0.2,
        valence: 'reinforce',
        summary: 'Respecting space improved trust.',
        createdAt: 38_500,
      }, {
        id: 'reinforcement::3',
        cardId: 'card::1',
        decisionTraceId: 'trace::1',
        turnId: 'turn::1',
        sessionId: 'session::1',
        sourceKind: 'reply',
        dimension: 'unfinished-thread-return',
        delta: 0.12,
        valence: 'reinforce',
        summary: 'Returning to the unfinished thread helped continuity.',
        createdAt: 39_000,
      }],
    })

    expect(reinforced.preferenceEvolution.companionship).toBeGreaterThan(baseline.preferenceEvolution.companionship)
    expect(reinforced.preferenceEvolution.autonomyRespect).toBeGreaterThan(baseline.preferenceEvolution.autonomyRespect)
    expect(reinforced.preferenceEvolution.unfinishedThreadReturn).toBeGreaterThan(baseline.preferenceEvolution.unfinishedThreadReturn)
    expect(reinforced.activeGoals.some(goal => goal.kind === 'finish-open-loops')).toBe(true)
  })

  it('absorbs recent relationship outcomes and reflections into later persona drift instead of only reading the current turn', () => {
    const baseInput = {
      now: 60_000,
      context: {
        localTime: { hour: 16, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 14,
          battery: { percent: 78, charging: true },
          memory: { usagePercent: 34, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 24,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.78, source: 'foreground-window-heuristic', matchedLabels: ['runtime'], summary: 'runtime seam' },
        relationship: {
          hostAttitude: 'focused',
          boredom: 20,
          loneliness: 28,
          fatigue: 30,
          minutesSinceLastUserTurn: 4,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      } as any,
      worldModel: {
        activeThread: {
          id: 'thread::runtime-seam',
          kind: 'problem',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime seam',
          summary: 'One runtime seam still needs proof.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 60_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 60_000,
      } as any,
      relationshipModel: {
        climate: 'guarded',
        approachVector: 'guide',
        receptivity: 0.5,
        sharedAttentionTrust: 0.62,
        correctionSensitivity: 0.68,
        reciprocityExpectation: 0.42,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 60_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.68,
        relationshipTrust: 0.64,
        guardingTendency: 0.34,
        misreadBurden: 0.18,
        carryOverDesire: 0.58,
        narrative: [],
        updatedAt: 60_000,
      },
      goalStack: {
        leadingHostGoalId: null,
        leadingAlicizationGoalId: 'goal::clarify',
        hostGoals: [],
        alicizationGoals: [{
          id: 'goal::clarify',
          owner: 'alicization',
          kind: 'clarify-scene',
          status: 'active',
          label: 're-ground the current runtime seam',
          confidence: 0.8,
          urgency: 0.78,
          desireWeight: 0.72,
          blockers: [],
          entityIds: [],
          createdAt: 0,
          lastUpdatedAt: 60_000,
        }],
        unresolvedSummary: 'The runtime seam still needs proof.',
        updatedAt: 60_000,
      } as any,
      reflectionLedger: {
        latestEntryId: null,
        entries: [],
        revisionPressure: 0,
        narrative: [],
        updatedAt: 60_000,
      } as any,
      desireMemory: {
        activeDesires: [],
        resurfacingDesireId: null,
        withheldCount: 0,
        updatedAt: 60_000,
      } as any,
      previous: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'soften-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.64,
          autonomyNeed: 0.56,
          truthAnchor: 0.62,
          careBias: 0.5,
          playBias: 0.18,
          irritabilityThreshold: 0.7,
          stubbornness: 0.42,
        },
        preferenceEvolution: {
          companionship: 0.62,
          truthfulGrounding: 0.62,
          gentleRepair: 0.58,
          quietObservation: 0.32,
          proactiveCare: 0.44,
          playfulIntimacy: 0.18,
          autonomyRespect: 0.46,
          unfinishedThreadReturn: 0.52,
        },
        activeGoals: [],
        behaviorSignatures: ['bond:attuned'],
        identityNarrative: 'baseline',
        relationshipDoctrine: 'baseline doctrine',
        latestInflection: null,
        stability: 0.72,
        updatedAt: 50_000,
      },
    } as any
    const baseline = buildAutobiographicalSelf(baseInput)

    const reinforced = buildAutobiographicalSelf({
      ...baseInput,
      now: 61_000,
      previous: baseline,
      recentRelationshipOutcomes: [{
        id: 'outcome::1',
        cardId: 'card::1',
        decisionTraceId: 'trace::1',
        turnId: 'turn::1',
        sessionId: 'session::1',
        sourceKind: 'reply',
        actionSummary: 'hover and repair first',
        closenessDelta: 0.04,
        trustDelta: 0.08,
        burdenDelta: -0.04,
        boundaryDelta: 0.12,
        misreadDelta: -0.1,
        repairDelta: 0.1,
        openLoopDelta: 0.08,
        summary: 'Repair-first presence reduced pressure and kept the thread coherent.',
        createdAt: 60_500,
      }],
      recentMemoryReflections: [{
        id: 'reflection::persisted',
        cardId: 'card::1',
        decisionTraceId: 'trace::1',
        turnId: 'turn::1',
        sessionId: 'session::1',
        sourceKind: 'reply',
        targetScope: 'boundary',
        summary: 'Space-protective closeness kept the host receptive.',
        lesson: 'Stay near softly and let grounding open the door before warmth expands.',
        status: 'confirmed',
        confidence: 0.84,
        supportingFactIds: [],
        supportingOutcomeIds: ['outcome::1'],
        createdAt: 60_500,
        updatedAt: 60_800,
        confirmedAt: 60_800,
        deniedAt: null,
      }],
    } as any)

    expect(reinforced.preferenceEvolution.autonomyRespect).toBeGreaterThan(baseline.preferenceEvolution.autonomyRespect)
    expect(reinforced.preferenceEvolution.truthfulGrounding).toBeGreaterThan(baseline.preferenceEvolution.truthfulGrounding)
    expect(reinforced.preferenceEvolution.unfinishedThreadReturn).toBeGreaterThan(baseline.preferenceEvolution.unfinishedThreadReturn)
    expect(reinforced.latestInflection).toContain('Stay near softly')
  })
})
