import { describe, expect, it } from 'vitest'

import {
  buildClaimEvidenceLedger,
  buildClaimEvidenceLedgerSystemBlock,
  extractTechnicalSpecificityClaims,
} from './claim-evidence-ledger'
import { buildAlicizationDigitalLifeRuntimeSurface } from './digital-life-kernel'
import { createDefaultVisualPresenceState } from './visual-episodic-memory'

describe('claim-evidence-ledger', () => {
  it('keeps screen-guess turns on a coarse specificity budget until concrete artifacts are truly grounded', () => {
    const ledger = buildClaimEvidenceLedger({
      now: 40_000,
      discourseState: {
        currentTurnSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        currentTurnSummary: 'Guess what the host is doing from the visible workspace.',
        currentQuestion: '猜猜我在干嘛',
        primaryTurnAnchor: '猜猜我在干嘛',
        primaryTurnAnchorSource: 'user-text',
        owedAction: 'guide-task',
        relationMove: 'witness',
        continuityMode: 'scene-first',
        unresolvedCarry: null,
        ruptureRepair: null,
        confidence: 0.84,
        narrative: [],
        updatedAt: 40_000,
      },
      conversationState: {
        jointThread: 'The host wants a best-effort guess from the current workspace.',
        hostMove: '猜猜我在干嘛',
        primaryTurnAnchor: '猜猜我在干嘛',
        primaryTurnAnchorSource: 'user-text',
        activeProject: null,
        unansweredQuestion: '猜猜我在干嘛',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'witness',
        continuityPolicy: 'scene-before-memory',
        memoryMode: 'scene-anchored',
        memoryQueryHints: ['猜猜我在干嘛'],
        shouldHoldThread: true,
        confidence: 0.8,
        narrative: [],
        updatedAt: 40_000,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        speechObligation: 'guide-task',
        relationMove: 'witness',
        turnMode: 'guide-current-knot',
        responseMode: 'guide-current-knot',
        recommendedAct: 'guide',
        evidenceMode: 'coarse-held',
        openingStyle: 'direct-answer',
        personaKernelMode: 'backgrounded',
        relationshipPosture: 'warm',
        openingDirective: 'Stay with the visible knot before naming a larger story.',
        openingClaim: 'Git commit diff in Java code editor',
        supportingReality: ['Git commit diff in Java code editor'],
        uncertaintyBoundary: 'The exact file or class is not yet safe to claim.',
        careVector: null,
        nextMove: 'Describe the visible knot first, then keep the guess soft.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.84,
        narrative: [],
        updatedAt: 40_000,
      },
      currentConsciousFrame: {
        subject: 'task-knot',
        centerOfGravity: 'witness',
        truthDiscipline: 'observe-then-hypothesize',
        consciousNeed: 'Start from what is visible before naming the task.',
        consciousTension: 'The scene is still too coarse for class-level certainty.',
        speakingIntention: 'Separate observation from guess and keep the guess soft.',
        focusAnchor: 'Git commit diff in Java code editor',
        withheldImpulse: 'Do not collapse coarse visual evidence into file, class, or field certainty.',
        shouldWithholdSpecificity: true,
        shouldSelfRevise: false,
        confidence: 0.8,
        reasonTags: ['discipline:observe-then-hypothesize'],
        updatedAt: 40_000,
      },
      currentScene: {
        scenario: 'coding',
        workloadKind: 'coding',
        contentKind: 'diff',
        summary: 'Git commit diff in Java code editor',
        source: 'screen-semantic-summary',
        confidence: 0.76,
        target: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'IDE with Java diff',
          pid: 42,
        },
        beganAt: 38_000,
        lastSeenAt: 40_000,
      },
    })

    expect(ledger).toEqual(expect.objectContaining({
      specificityBudget: 'coarse-scene',
      shouldLabelHypothesis: true,
      forbidUnsupportedSpecificity: true,
    }))
    expect(ledger?.allowedSpecificCues).toEqual([])
    expect(buildClaimEvidenceLedgerSystemBlock(ledger)).toContain('[ALICIZATION_CLAIM_EVIDENCE_LEDGER]')
  })

  it('admits concrete artifact cues only when they are grounded or explicitly named by the host', () => {
    const ledger = buildClaimEvidenceLedger({
      now: 55_000,
      discourseState: {
        currentTurnSubject: 'visible-scene',
        screenReferenceMode: 'required',
        currentTurnSummary: 'Recheck the current grounded file and answer plainly.',
        currentQuestion: '你是不是在改 AppArbitorController.java？',
        primaryTurnAnchor: 'AppArbitorController.java',
        primaryTurnAnchorSource: 'user-text',
        owedAction: 'inspect-scene',
        relationMove: 'guide',
        continuityMode: 'scene-first',
        unresolvedCarry: null,
        ruptureRepair: null,
        confidence: 0.88,
        narrative: [],
        updatedAt: 55_000,
      },
      conversationState: {
        jointThread: 'The host is asking about AppArbitorController.java directly.',
        hostMove: '你是不是在改 AppArbitorController.java？',
        primaryTurnAnchor: 'AppArbitorController.java',
        primaryTurnAnchorSource: 'user-text',
        activeProject: null,
        unansweredQuestion: '你是不是在改 AppArbitorController.java？',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'guide',
        continuityPolicy: 'scene-before-memory',
        memoryMode: 'scene-anchored',
        memoryQueryHints: ['AppArbitorController.java'],
        shouldHoldThread: true,
        confidence: 0.82,
        narrative: [],
        updatedAt: 55_000,
      },
      answerCompiler: {
        answerSubject: 'visible-scene',
        screenReferenceMode: 'required',
        speechObligation: 'inspect-scene',
        relationMove: 'guide',
        turnMode: 'grounded-inspection',
        responseMode: 'answer-naturally',
        recommendedAct: 'answer',
        evidenceMode: 'live-grounded',
        openingStyle: 'direct-observation',
        personaKernelMode: 'backgrounded',
        relationshipPosture: 'warm',
        openingDirective: 'Answer from the grounded scene itself.',
        openingClaim: 'AppArbitorController.java diff in the IDE',
        supportingReality: ['AppArbitorController.java diff in the IDE'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Stay with the grounded file before widening the story.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.9,
        narrative: [],
        updatedAt: 55_000,
      },
      currentScene: {
        scenario: 'coding',
        workloadKind: 'coding',
        contentKind: 'diff',
        summary: 'AppArbitorController.java diff in the IDE',
        source: 'invited-grounding',
        confidence: 0.92,
        target: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'AppArbitorController.java',
          pid: 42,
        },
        beganAt: 54_000,
        lastSeenAt: 55_000,
      },
    })

    expect(ledger).toEqual(expect.objectContaining({
      specificityBudget: 'grounded-artifacts',
      shouldLabelHypothesis: false,
    }))
    expect(ledger?.allowedSpecificCues).toContain('AppArbitorController.java')
    expect(extractTechnicalSpecificityClaims('你在改 AppArbitorController.java 和 CaseApplyTypeEnum')).toEqual(expect.arrayContaining([
      'AppArbitorController.java',
      'AppArbitorController',
      'CaseApplyTypeEnum',
    ]))
  })

  it('prefers runtime surface evidence cues over conflicting raw inputs', () => {
    const runtimeBackedState = {
      ...createDefaultVisualPresenceState(60_000),
      discourseState: {
        currentTurnSubject: 'visible-scene',
        screenReferenceMode: 'required',
        currentTurnSummary: 'Recheck the current grounded file and answer plainly.',
        currentQuestion: '你是不是在改 AppArbitorController.java？',
        primaryTurnAnchor: 'AppArbitorController.java',
        primaryTurnAnchorSource: 'user-text',
        owedAction: 'inspect-scene',
        relationMove: 'guide',
        continuityMode: 'scene-first',
        unresolvedCarry: null,
        ruptureRepair: null,
        confidence: 0.88,
        narrative: [],
        updatedAt: 60_000,
      },
      conversationState: {
        jointThread: 'The host is asking about AppArbitorController.java directly.',
        hostMove: '你是不是在改 AppArbitorController.java？',
        primaryTurnAnchor: 'AppArbitorController.java',
        primaryTurnAnchorSource: 'user-text',
        activeProject: null,
        unansweredQuestion: '你是不是在改 AppArbitorController.java？',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'guide',
        continuityPolicy: 'scene-before-memory',
        memoryMode: 'scene-anchored',
        memoryQueryHints: ['AppArbitorController.java'],
        shouldHoldThread: true,
        confidence: 0.82,
        narrative: [],
        updatedAt: 60_000,
      },
      answerCompiler: {
        answerSubject: 'visible-scene',
        screenReferenceMode: 'required',
        speechObligation: 'inspect-scene',
        relationMove: 'guide',
        turnMode: 'grounded-inspection',
        responseMode: 'answer-naturally',
        recommendedAct: 'answer',
        evidenceMode: 'live-grounded',
        openingStyle: 'direct-observation',
        personaKernelMode: 'backgrounded',
        relationshipPosture: 'warm',
        openingDirective: 'Answer from the grounded scene itself.',
        openingClaim: 'AppArbitorController.java diff in the IDE',
        supportingReality: ['AppArbitorController.java diff in the IDE'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Stay with the grounded file before widening the story.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.9,
        narrative: [],
        updatedAt: 60_000,
      },
      currentConsciousFrame: {
        subject: 'visible-scene',
        centerOfGravity: 'witness',
        truthDiscipline: 'observe-first',
        consciousNeed: 'Start from the grounded file.',
        consciousTension: 'Keep the answer attached to the grounded file.',
        speakingIntention: 'Answer from the grounded artifact itself.',
        focusAnchor: 'AppArbitorController.java',
        withheldImpulse: null,
        shouldWithholdSpecificity: false,
        shouldSelfRevise: false,
        confidence: 0.84,
        reasonTags: ['grounded-artifact'],
        updatedAt: 60_000,
      },
      currentScene: {
        scenario: 'coding',
        workloadKind: 'coding',
        contentKind: 'diff',
        summary: 'AppArbitorController.java diff in the IDE',
        source: 'invited-grounding',
        confidence: 0.92,
        target: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'AppArbitorController.java',
          pid: 42,
        },
        beganAt: 59_000,
        lastSeenAt: 60_000,
      },
    } as any

    const ledger = buildClaimEvidenceLedger({
      now: 60_000,
      discourseState: {
        currentTurnSubject: 'relationship',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'raw conflict',
        currentQuestion: 'raw conflict',
        primaryTurnAnchor: 'raw conflict',
        primaryTurnAnchorSource: 'user-text',
        owedAction: 'answer-relationship',
        relationMove: 'attune',
        continuityMode: 'dialogue-first',
        unresolvedCarry: null,
        ruptureRepair: null,
        confidence: 0.2,
        narrative: [],
        updatedAt: 60_000,
      } as any,
      answerCompiler: {
        answerSubject: 'relationship',
        screenReferenceMode: 'avoid',
        speechObligation: 'answer-relationship',
        relationMove: 'attune',
        turnMode: 'answer',
        responseMode: 'dialogue-answer',
        recommendedAct: 'answer',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        openingDirective: 'raw conflict',
        openingClaim: 'raw conflict',
        supportingReality: [],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'raw conflict',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 3,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.2,
        narrative: [],
        updatedAt: 60_000,
      } as any,
      runtimeSurface: buildAlicizationDigitalLifeRuntimeSurface(runtimeBackedState),
    })

    expect(ledger).toEqual(expect.objectContaining({
      specificityBudget: 'grounded-artifacts',
      shouldLabelHypothesis: false,
    }))
    expect(ledger?.allowedSpecificCues).toContain('AppArbitorController.java')
  })
})
