import { describe, expect, it } from 'vitest'

import { buildCommitmentLedger } from './commitment-ledger'

const baseContext = {
  localTime: { hour: 14, minute: 20, isLateNight: false },
  system: {
    cpuUsage: 12,
    battery: { percent: 82, charging: true },
    memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
    idleSeconds: 18,
    inputActivity: 'idle' as const,
    fullscreenLikely: false,
    foregroundWindow: {
      appName: 'Cursor',
      processName: 'Cursor',
      title: 'runtime.ts - diff',
      pid: 7,
    },
    degradedSignals: [],
  },
  workload: {
    kind: 'coding' as const,
    confidence: 0.88,
    source: 'foreground-window-heuristic' as const,
    matchedLabels: ['cursor'],
  },
  content: {
    kind: 'diff' as const,
    confidence: 0.84,
    source: 'foreground-window-heuristic' as const,
    matchedLabels: ['diff'],
    summary: 'runtime.ts - diff',
  },
  relationship: {
    hostAttitude: '礼貌而克制，保持观察',
    boredom: 42,
    loneliness: 28,
    fatigue: 22,
    minutesSinceLastUserTurn: 6,
    reminderBacklog: 0,
    lateNightActiveMinutes: 0,
    recentProactiveOutcomes: [],
  },
}

describe('buildCommitmentLedger', () => {
  it('keeps holding a concrete problem instead of flattening it into one tick', () => {
    const ledger = buildCommitmentLedger({
      now: 20_000,
      context: baseContext,
      worldModel: {
        activeThread: {
          id: 'thread-1',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts diff',
          summary: 'The host is reviewing a runtime diff with a concrete knot.',
          confidence: 0.88,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      },
      beliefLedger: {
        focusBeliefId: 'belief-1',
        beliefs: [{
          id: 'belief-1',
          scope: 'scene',
          source: 'percept',
          status: 'held',
          statement: 'The diff still hides a real failing locus.',
          confidence: 0.84,
          salience: 0.8,
          evidence: ['diff'],
          entityIds: [],
          formedAt: 0,
          lastUpdatedAt: 20_000,
          expiresAt: 100_000,
        }],
        unresolvedContradictions: [],
        updatedAt: 20_000,
      },
      beliefRevision: {
        dominantBeliefId: 'belief-1',
        stability: 'stable',
        revisionPressure: 0.22,
        groundingNeed: 0.24,
        contradictionPressure: 0.16,
        hostCorrectionWeight: 0.18,
        narrative: [],
        updatedAt: 20_000,
      },
      hypothesisGraph: {
        activeHypothesisId: 'problem-locus::runtime',
        focusHypothesisIds: ['problem-locus::runtime'],
        driftPressure: 0.22,
        hypotheses: [{
          id: 'problem-locus::runtime',
          kind: 'problem-locus',
          status: 'active',
          summary: 'The real knot is narrow enough to keep holding onto.',
          confidence: 0.84,
          salience: 0.86,
          evidence: ['diff'],
          counterEvidence: [],
          formedAt: 0,
          lastUpdatedAt: 20_000,
          expiresAt: 100_000,
        }],
        narrative: [],
        updatedAt: 20_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::thread-1',
        threads: [{
          id: 'runtime::thread-1',
          sourceThreadId: 'thread-1',
          sourceHypothesisId: 'problem-locus::runtime',
          need: 'guidance',
          status: 'foreground',
          summary: 'Point toward the real knot in the diff.',
          salience: 0.82,
          continuity: 0.74,
          whyHeld: 'The diff should not be abandoned before the knot is localized.',
          returnWhen: ['problem-locus-sharpens'],
          suggestedPresence: 'attentive',
          lastActivatedAt: 0,
          lastUpdatedAt: 20_000,
          expiresAt: 120_000,
        }],
        driftPressure: 0.18,
        narrative: [],
        updatedAt: 20_000,
      },
      previous: null,
    })

    expect(ledger.governingCommitmentId).toBeTruthy()
    expect(ledger.commitments.some(commitment => commitment.kind === 'hold-problem')).toBe(true)
    expect(ledger.carryPressure).toBeGreaterThan(0.3)
  })

  it('keeps a follow-through obligation cooling instead of forgetting it instantly', () => {
    const ledger = buildCommitmentLedger({
      now: 40_000,
      context: baseContext,
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 5_000,
          attentionAgeMs: 5_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 40_000,
      },
      threadRuntime: {
        foregroundThreadId: null,
        threads: [],
        driftPressure: 0.12,
        narrative: [],
        updatedAt: 40_000,
      },
      previousPrivateThought: {
        stance: 'accompany',
        confidence: 0.74,
        rationaleTags: [],
        thoughtText: 'I still want to stay with that thread a little longer.',
        shouldSpeak: false,
        suggestedStyle: 'silent-observe',
        embodiedPresence: 'glance',
        expiresAt: 50_000,
        afterglowFromScenario: 'coding',
        emotionalTension: 'focused-flow',
        commitmentId: 'commitment::follow-through::runtime-thread',
      },
      previous: {
        governingCommitmentId: 'commitment::follow-through::runtime-thread',
        commitments: [{
          id: 'commitment::follow-through::runtime-thread',
          kind: 'follow-through',
          status: 'active',
          title: 'Follow Through',
          summary: 'This thread is not finished just because it slipped out of the foreground.',
          source: 'runtime-thread',
          priority: 0.72,
          confidence: 0.68,
          createdAt: 0,
          lastRenewedAt: 20_000,
          patienceUntil: 50_000,
          expiresAt: 100_000,
        }],
        carryPressure: 0.52,
        narrative: [],
        updatedAt: 20_000,
      },
    })

    expect(ledger.commitments.some(commitment => commitment.kind === 'follow-through')).toBe(true)
    expect(ledger.commitments[0]?.status === 'active' || ledger.commitments[0]?.status === 'cooling').toBe(true)
  })

  it('does not force a live observed diff back into recheck mode when the knot is already concrete', () => {
    const ledger = buildCommitmentLedger({
      now: 60_000,
      context: baseContext,
      worldModel: {
        activeThread: {
          id: 'thread-2',
          kind: 'change-review',
          status: 'active',
          source: 'observed-scene',
          title: 'runtime.ts diff',
          summary: 'The host is actively checking a concrete diff.',
          confidence: 0.74,
          significance: 0.76,
          unresolved: true,
          beganAt: 10_000,
          lastUpdatedAt: 60_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: ['当前只拿到了窗口级线索，还没有稳定内容级 grounding。'],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 30_000,
          attentionAgeMs: 30_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 60_000,
      },
      beliefLedger: {
        focusBeliefId: 'belief-observed',
        beliefs: [{
          id: 'belief-observed',
          scope: 'scene',
          source: 'percept',
          status: 'held',
          statement: 'The current diff still hides a concrete knot.',
          confidence: 0.7,
          salience: 0.76,
          evidence: ['diff-visible'],
          entityIds: [],
          formedAt: 0,
          lastUpdatedAt: 60_000,
          expiresAt: 120_000,
        }],
        unresolvedContradictions: [],
        updatedAt: 60_000,
      },
      beliefRevision: {
        dominantBeliefId: 'belief-observed',
        stability: 'fluid',
        revisionPressure: 0.36,
        groundingNeed: 0.48,
        contradictionPressure: 0.18,
        hostCorrectionWeight: 0.22,
        narrative: [],
        updatedAt: 60_000,
      },
      hypothesisGraph: {
        activeHypothesisId: 'problem-locus::observed',
        focusHypothesisIds: ['problem-locus::observed'],
        driftPressure: 0.2,
        hypotheses: [{
          id: 'problem-locus::observed',
          kind: 'problem-locus',
          status: 'active',
          summary: 'The observed diff already localizes to a real knot.',
          confidence: 0.74,
          salience: 0.8,
          evidence: ['content:diff'],
          counterEvidence: [],
          formedAt: 0,
          lastUpdatedAt: 60_000,
          expiresAt: 120_000,
        }],
        narrative: [],
        updatedAt: 60_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::thread-2',
        threads: [{
          id: 'runtime::thread-2',
          sourceThreadId: 'thread-2',
          sourceHypothesisId: 'problem-locus::observed',
          need: 'guidance',
          status: 'foreground',
          summary: 'Point toward the concrete knot already visible in the diff.',
          salience: 0.8,
          continuity: 0.7,
          whyHeld: 'The live diff is concrete enough to keep holding without collapsing into recheck.',
          returnWhen: ['problem-locus-sharpens'],
          suggestedPresence: 'attentive',
          lastActivatedAt: 10_000,
          lastUpdatedAt: 60_000,
          expiresAt: 120_000,
        }],
        driftPressure: 0.18,
        narrative: [],
        updatedAt: 60_000,
      },
      previous: null,
    })

    expect(ledger.governingCommitmentId).toContain('hold-problem')
    expect(ledger.commitments.some(commitment => commitment.kind === 'recheck-scene')).toBe(false)
  })
})
