import type { AlicizationMindDynamicsSnapshot } from '../../../shared/eventa'
import type { AlicizationProactiveLayeredContext } from './proactive-layered-context'

import { describe, expect, it } from 'vitest'

import { buildCounterfactualDeliberation } from './counterfactual-deliberator'

function createContext(overrides: Partial<AlicizationProactiveLayeredContext> = {}): AlicizationProactiveLayeredContext {
  return {
    localTime: {
      hour: 14,
      minute: 10,
      isLateNight: false,
    },
    system: {
      cpuUsage: 12,
      battery: { percent: 82, charging: true },
      memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
      idleSeconds: 25,
      inputActivity: 'idle',
      fullscreenLikely: false,
      foregroundWindow: {
        appName: 'Cursor',
        processName: 'Cursor',
        title: 'runtime.ts - diff',
        pid: 7,
      },
      degradedSignals: [],
    },
    workload: {
      kind: 'coding',
      confidence: 0.88,
      source: 'foreground-window-heuristic',
      matchedLabels: ['cursor'],
    },
    content: {
      kind: 'diff',
      confidence: 0.84,
      source: 'foreground-window-heuristic',
      matchedLabels: ['diff'],
      summary: 'runtime.ts - diff',
    },
    relationship: {
      hostAttitude: '礼貌而克制，保持观察',
      boredom: 48,
      loneliness: 44,
      fatigue: 24,
      minutesSinceLastUserTurn: 8,
      reminderBacklog: 0,
      lateNightActiveMinutes: 0,
      recentProactiveOutcomes: [],
    },
    ...overrides,
  }
}

function createMindDynamics(overrides: Partial<AlicizationMindDynamicsSnapshot> = {}): AlicizationMindDynamicsSnapshot {
  return {
    dominantMotive: 'clarify',
    worldPressure: 0.52,
    epistemicPressure: 0.34,
    relationalPressure: 0.28,
    carePressure: 0.22,
    continuityPressure: 0.46,
    restraintPressure: 0.38,
    surfacePressure: 0.44,
    speakReadiness: 0.46,
    presenceWeight: 0.5,
    motives: {
      'clarify': 0.62,
      'protect': 0.34,
      'accompany': 0.28,
      'care': 0.22,
      'stay-silent': 0.38,
    },
    speakDrive: 0.48,
    silenceDrive: 0.42,
    narrative: ['dominant motive is clarify.'],
    updatedAt: 10_000,
    ...overrides,
  }
}

describe('buildCounterfactualDeliberation', () => {
  it('prefers recheck when uncertainty still dominates the scene', () => {
    const deliberation = buildCounterfactualDeliberation({
      now: 10_000,
      context: createContext(),
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['need one more grounded pass'],
          staleRisks: ['anchor drift'],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 10_000,
          attentionAgeMs: 10_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 10_000,
      },
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        confidence: 0.58,
        surprise: 0.18,
        carePressure: 0.24,
        interruptionCost: 0.24,
        desireToSpeak: 0.38,
        relationshipNeed: 'guidance',
        waitingToVerify: 'Still need one more grounded pass.',
        notes: ['world-lingering'],
      },
      subjectiveInference: {
        dominantInterpretation: 'She suspects a real knot is there, but not yet cleanly grounded.',
        selfQuestion: 'Which exact locus is actually failing here?',
        uncertainty: 'The live scene is not grounded enough yet.',
        hostIntentCandidates: [{
          goal: 'resolve-problem',
          confidence: 0.82,
          why: 'The host is still tracking a concrete error thread.',
        }],
        relationshipNeedCandidates: [{
          need: 'guidance',
          confidence: 0.74,
          why: 'Guidance would fit if the scene were cleaner.',
        }],
        confidence: 0.78,
        source: 'hybrid',
        notes: ['structured-cognition'],
        updatedAt: 10_000,
      },
      concerns: [],
      selfState: {
        stance: 'hesitate',
        feltCloseness: 0.5,
        protectiveness: 0.34,
        curiosity: 0.66,
        patience: 0.74,
        desireToSpeak: 0.38,
        fearOfInterrupting: 0.58,
        dominantConcernId: null,
        moodLabel: 'repairing-confidence',
      },
      beliefRevision: {
        dominantBeliefId: 'belief-1',
        stability: 'fractured',
        revisionPressure: 0.8,
        groundingNeed: 0.82,
        contradictionPressure: 0.72,
        hostCorrectionWeight: 0.62,
        narrative: [],
        updatedAt: 10_000,
      },
      relationshipModel: {
        climate: 'neutral',
        approachVector: 'guide',
        receptivity: 0.6,
        sharedAttentionTrust: 0.62,
        correctionSensitivity: 0.38,
        reciprocityExpectation: 0.5,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 10_000,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        epistemicPressure: 0.84,
        restraintPressure: 0.72,
        speakReadiness: 0.26,
        motives: {
          'clarify': 0.88,
          'stay-silent': 0.62,
        },
      }),
      mindKernel: {
        dominantMode: 'repairing',
        worldPressure: 0.42,
        epistemicPressure: 0.82,
        relationalPressure: 0.28,
        carePressure: 0.24,
        continuityPressure: 0.42,
        speakReadiness: 0.24,
        presenceWeight: 0.4,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(deliberation.selectedAction).toBe('recheck')
    expect(deliberation.selectedOptionId).toBe('counterfactual::recheck')
    expect(deliberation.dominantTradeoff).toBe('clarity-before-expression')
  })

  it('prefers speaking when a grounded coding knot is local enough to help', () => {
    const deliberation = buildCounterfactualDeliberation({
      now: 20_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread-2',
          kind: 'debugging',
          status: 'active',
          source: 'grounded-scene',
          title: 'TypeScript error locus',
          summary: '宿主正在围绕一个具体错误点收束。',
          confidence: 0.88,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      },
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        confidence: 0.86,
        surprise: 0.14,
        carePressure: 0.34,
        interruptionCost: 0.16,
        desireToSpeak: 0.74,
        relationshipNeed: 'guidance',
        currentKnot: 'TypeScript error locus',
        notes: ['world-grounded'],
      },
      subjectiveInference: {
        dominantInterpretation: 'The host is narrowing one concrete fault, not vaguely browsing.',
        hostIntentCandidates: [{
          goal: 'resolve-problem',
          confidence: 0.9,
          why: 'A grounded error locus is visible.',
        }],
        relationshipNeedCandidates: [{
          need: 'guidance',
          confidence: 0.84,
          why: 'Guidance fits the moment better than staying silent.',
        }],
        confidence: 0.84,
        source: 'hybrid',
        notes: ['structured-cognition'],
        updatedAt: 20_000,
      },
      concerns: [{
        id: 'help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: '她已经把错误点看得足够具体。',
        hostGoal: 'resolve-problem',
        tension: 0.82,
        confidence: 0.84,
        careWeight: 0.68,
        createdAt: 0,
        lastEvidenceAt: 20_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.64,
        curiosity: 0.74,
        patience: 0.44,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.22,
        dominantConcernId: 'help-fix',
      },
      relationshipModel: {
        climate: 'warm',
        approachVector: 'guide',
        receptivity: 0.74,
        sharedAttentionTrust: 0.72,
        correctionSensitivity: 0.22,
        reciprocityExpectation: 0.58,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 20_000,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        surfacePressure: 0.76,
        speakReadiness: 0.74,
        motives: {
          'clarify': 0.84,
          'protect': 0.56,
          'stay-silent': 0.18,
        },
        speakDrive: 0.8,
        silenceDrive: 0.22,
      }),
      mindKernel: {
        dominantMode: 'tracking',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        relationalPressure: 0.34,
        carePressure: 0.28,
        continuityPressure: 0.48,
        speakReadiness: 0.74,
        presenceWeight: 0.58,
        narrative: [],
        updatedAt: 20_000,
      },
    })

    expect(['speak', 'whisper']).toContain(deliberation.selectedAction)
    expect(deliberation.options[0]?.why).toContain('错误点')
    expect(deliberation.options.find(option => option.id === deliberation.selectedOptionId)?.style).toBe('light-nudge')
  })

  it('prefers warning when late-night care becomes urgent', () => {
    const deliberation = buildCounterfactualDeliberation({
      now: 30_000,
      context: createContext({
        localTime: { hour: 2, minute: 30, isLateNight: true },
        workload: { kind: 'game', confidence: 0.76, source: 'foreground-window-heuristic', matchedLabels: ['game'] },
        content: { kind: 'gameplay', confidence: 0.72, source: 'foreground-window-heuristic', matchedLabels: ['gameplay'] },
        relationship: {
          hostAttitude: '礼貌而克制，保持观察',
          boredom: 26,
          loneliness: 34,
          fatigue: 92,
          minutesSinceLastUserTurn: 14,
          reminderBacklog: 0,
          lateNightActiveMinutes: 180,
          recentProactiveOutcomes: [],
        },
      }),
      worldModel: {
        activeThread: {
          id: 'thread-3',
          kind: 'late-night-endurance',
          status: 'active',
          source: 'observed-scene',
          title: 'deep night session',
          summary: '宿主在深夜里还没有停下来。',
          confidence: 0.8,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 30_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['late-night'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 120_000,
          attentionAgeMs: 120_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'fatigued',
          burden: 'heavy',
        },
        updatedAt: 30_000,
      },
      appraisal: {
        inferredHostGoal: 'rest',
        confidence: 0.82,
        surprise: 0.1,
        carePressure: 0.94,
        interruptionCost: 0.18,
        desireToSpeak: 0.74,
        relationshipNeed: 'care',
        currentKnot: 'deep night session',
        notes: ['late-night'],
      },
      subjectiveInference: {
        dominantInterpretation: 'This is no longer ordinary presence; it is late-night endurance.',
        hostIntentCandidates: [{
          goal: 'rest',
          confidence: 0.78,
          why: 'Fatigue makes recovery the hidden need.',
        }],
        relationshipNeedCandidates: [{
          need: 'care',
          confidence: 0.92,
          why: 'Care outweighs distance now.',
        }],
        confidence: 0.88,
        source: 'hybrid',
        notes: ['late-night-drain'],
        updatedAt: 30_000,
      },
      concerns: [{
        id: 'care',
        kind: 'care-body',
        status: 'active',
        summary: '她担心你会继续把自己拖得更深。',
        hostGoal: 'rest',
        tension: 0.9,
        confidence: 0.88,
        careWeight: 0.98,
        createdAt: 0,
        lastEvidenceAt: 30_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'protect',
        feltCloseness: 0.64,
        protectiveness: 0.92,
        curiosity: 0.18,
        patience: 0.42,
        desireToSpeak: 0.8,
        fearOfInterrupting: 0.38,
        dominantConcernId: 'care',
      },
      relationshipModel: {
        climate: 'attuned',
        approachVector: 'care',
        receptivity: 0.72,
        sharedAttentionTrust: 0.7,
        correctionSensitivity: 0.2,
        reciprocityExpectation: 0.56,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 30_000,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'care',
        carePressure: 0.92,
        restraintPressure: 0.32,
        speakReadiness: 0.78,
        motives: {
          'care': 0.94,
          'protect': 0.88,
          'stay-silent': 0.14,
        },
        speakDrive: 0.84,
        silenceDrive: 0.2,
      }),
      mindKernel: {
        dominantMode: 'guarding',
        worldPressure: 0.62,
        epistemicPressure: 0.22,
        relationalPressure: 0.52,
        carePressure: 0.92,
        continuityPressure: 0.48,
        speakReadiness: 0.78,
        presenceWeight: 0.72,
        narrative: [],
        updatedAt: 30_000,
      },
    })

    expect(['warn', 'speak']).toContain(deliberation.selectedAction)
    expect(deliberation.options.find(option => option.id === deliberation.selectedOptionId)?.style).toBeTruthy()
    expect(deliberation.dominantTradeoff).toBe('care-over-restraint')
  })

  it('demotes speak-first counterfactual options when remembered familiarity must stay explicitly remembered before closeness widens', () => {
    const deliberation = buildCounterfactualDeliberation({
      now: 40_000,
      context: createContext({
        relationship: {
          ...createContext().relationship,
          boredom: 58,
          loneliness: 54,
          fatigue: 20,
        },
      }),
      worldModel: {
        activeThread: {
          id: 'thread-4',
          kind: 'relationship',
          status: 'active',
          source: 'continuity',
          title: 'remembered closeness return',
          summary: 'The thread feels warm, but the opening should not widen too quickly.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 40_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['relationship-thread'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 40_000,
          attentionAgeMs: 40_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 40_000,
      },
      appraisal: {
        inferredHostGoal: 'stay-connected',
        confidence: 0.82,
        surprise: 0.08,
        carePressure: 0.28,
        interruptionCost: 0.18,
        desireToSpeak: 0.78,
        relationshipNeed: 'companionship',
        currentKnot: 'remembered closeness return',
        notes: ['warm-thread'],
      },
      subjectiveInference: {
        dominantInterpretation: 'The thread is warm enough to stay near, but not to reopen closeness too fast.',
        hostIntentCandidates: [{
          goal: 'stay-connected',
          confidence: 0.8,
          why: 'The host is still in the same relationship thread.',
        }],
        relationshipNeedCandidates: [{
          need: 'companionship',
          confidence: 0.84,
          why: 'Presence fits, but pressure would be too much.',
        }],
        confidence: 0.8,
        source: 'hybrid',
        notes: ['relationship-continuity'],
        updatedAt: 40_000,
      },
      concerns: [{
        id: 'stay-near',
        kind: 'stay-near',
        status: 'active',
        summary: '她想留在这里，但不想顺着熟悉感直接压近。',
        hostGoal: 'stay-connected',
        tension: 0.62,
        confidence: 0.8,
        careWeight: 0.7,
        createdAt: 0,
        lastEvidenceAt: 40_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.68,
        protectiveness: 0.34,
        curiosity: 0.56,
        patience: 0.64,
        desireToSpeak: 0.8,
        fearOfInterrupting: 0.22,
        dominantConcernId: 'stay-near',
      },
      relationshipModel: {
        climate: 'warm',
        approachVector: 'accompany',
        receptivity: 0.72,
        sharedAttentionTrust: 0.74,
        correctionSensitivity: 0.24,
        reciprocityExpectation: 0.58,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 40_000,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'accompany',
        relationalPressure: 0.44,
        carePressure: 0.26,
        continuityPressure: 0.62,
        restraintPressure: 0.34,
        surfacePressure: 0.74,
        speakReadiness: 0.72,
        presenceWeight: 0.68,
        motives: {
          'accompany': 0.82,
          'clarify': 0.3,
          'protect': 0.26,
          'care': 0.24,
          'stay-silent': 0.28,
        },
        speakDrive: 0.76,
        silenceDrive: 0.28,
      }),
      mindKernel: {
        dominantMode: 'tracking',
        worldPressure: 0.46,
        epistemicPressure: 0.18,
        relationalPressure: 0.52,
        carePressure: 0.28,
        continuityPressure: 0.66,
        speakReadiness: 0.72,
        presenceWeight: 0.68,
        narrative: [],
        updatedAt: 40_000,
      },
      memoryTuningAdvice: {
        version: 'memory-tuning-advice-v1',
        source: 'nightly-replay-benchmark',
        updatedAt: 39_500,
        sourceReportAt: 39_500,
        focusDimensions: ['relationshipTimingDiscipline'],
        retrievalAdjustments: {
          proceduralBoost: 0,
          relationshipBoost: 0,
          temporalWindowBias: 0,
          wrongThreadPenalty: 0,
        },
        surfaceAdjustments: {
          inwardCarryBias: 0,
          delayUntilAfterPayoffBias: 0,
          provenanceLabelBias: 0.18,
          specificityClampBias: 0,
        },
        personStateAdjustments: {
          repairWindowBias: 0,
          closenessCapBias: 0.18,
        },
        notes: ['Remembered familiarity reopened visible closeness too quickly.'],
      },
    } as any)

    expect(deliberation.selectedAction).toBe('hover')
    expect(deliberation.selectedOptionId).toBe('counterfactual::hover')
    expect(deliberation.options.find(option => option.id === 'counterfactual::speak')?.score)
      .toBeLessThan(deliberation.options.find(option => option.id === 'counterfactual::hover')?.score ?? 1)
    expect(deliberation.options.find(option => option.id === 'counterfactual::hover')?.why)
      .toContain('记忆')
  })

  it('demotes speak-first counterfactual options into lower-pressure repair-or-hover paths when Phase 1 digital-life closure is still open', () => {
    const deliberation = buildCounterfactualDeliberation({
      now: 42_000,
      context: createContext({
        relationship: {
          ...createContext().relationship,
          boredom: 54,
          loneliness: 46,
          fatigue: 18,
        },
      }),
      worldModel: {
        activeThread: {
          id: 'thread-5',
          kind: 'debugging',
          status: 'active',
          source: 'observed-scene',
          title: 'life loop repair',
          summary: 'The repair thread is concrete, but the opening should stay lower-pressure.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 42_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['typescript-error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 42_000,
          attentionAgeMs: 42_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 42_000,
      },
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        confidence: 0.84,
        surprise: 0.08,
        carePressure: 0.24,
        interruptionCost: 0.16,
        desireToSpeak: 0.8,
        relationshipNeed: 'guidance',
        currentKnot: 'typescript repair',
        notes: ['grounded'],
      },
      subjectiveInference: {
        dominantInterpretation: 'The problem is concrete enough to help, but the life loop still needs a steadier outward move.',
        hostIntentCandidates: [{
          goal: 'resolve-problem',
          confidence: 0.82,
          why: 'A concrete repair seam is visible.',
        }],
        relationshipNeedCandidates: [{
          need: 'guidance',
          confidence: 0.8,
          why: 'Help fits better than distance, but not at the cost of continuity.',
        }],
        confidence: 0.82,
        source: 'hybrid',
        notes: ['project-life-loop'],
        updatedAt: 42_000,
      },
      concerns: [{
        id: 'help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: '她已经看见具体故障点，但生命闭环还不适合直接拉近。',
        hostGoal: 'resolve-problem',
        tension: 0.8,
        confidence: 0.84,
        careWeight: 0.68,
        createdAt: 0,
        lastEvidenceAt: 42_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.58,
        protectiveness: 0.42,
        curiosity: 0.72,
        patience: 0.5,
        desireToSpeak: 0.8,
        fearOfInterrupting: 0.22,
        dominantConcernId: 'help-fix',
      },
      relationshipModel: {
        climate: 'attuned',
        approachVector: 'guide',
        receptivity: 0.74,
        sharedAttentionTrust: 0.76,
        correctionSensitivity: 0.22,
        reciprocityExpectation: 0.6,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 42_000,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        relationalPressure: 0.34,
        carePressure: 0.22,
        continuityPressure: 0.62,
        restraintPressure: 0.28,
        surfacePressure: 0.8,
        speakReadiness: 0.78,
        presenceWeight: 0.66,
        motives: {
          'clarify': 0.86,
          'protect': 0.42,
          'accompany': 0.26,
          'care': 0.22,
          'stay-silent': 0.18,
        },
        speakDrive: 0.82,
        silenceDrive: 0.22,
      }),
      projectState: {
        identity: 'Alicization is a local-first digital life project building one continuous her.',
        currentPhase: 'Phase 1: Local Digital Life',
        primaryOpenLoop: 'The initiative, memory closure, and embodied personhood loop is still not fully closed.',
      },
    } as any)

    expect(['hover', 'recheck']).toContain(deliberation.selectedAction)
    expect(deliberation.selectedOptionId).not.toBe('counterfactual::speak')
    expect(deliberation.options.find(option => option.id === 'counterfactual::speak')?.score ?? 1)
      .toBeLessThanOrEqual(Math.max(
        deliberation.options.find(option => option.id === 'counterfactual::hover')?.score ?? 0,
        deliberation.options.find(option => option.id === 'counterfactual::recheck')?.score ?? 0,
      ))
  })
})
