import { describe, expect, it } from 'vitest'

import { buildDesireMemory } from './desire-memory'

function createContext(overrides: Record<string, any> = {}) {
  return {
    localTime: { hour: 14, minute: 30, isLateNight: false },
    system: {
      cpuUsage: 16,
      battery: { percent: 76, charging: true },
      memory: { usagePercent: 34, freeMB: 4096, totalMB: 8192 },
      idleSeconds: 18,
      inputActivity: 'active' as const,
      fullscreenLikely: false,
      foregroundWindow: {
        appName: 'Cursor',
        processName: 'Cursor',
        title: 'runtime.ts - diff',
        pid: 7,
      },
      degradedSignals: [],
    },
    workload: { kind: 'coding' as const, confidence: 0.88, source: 'foreground-window-heuristic' as const, matchedLabels: ['cursor'] },
    content: { kind: 'diff' as const, confidence: 0.9, source: 'foreground-window-heuristic' as const, matchedLabels: ['diff'], summary: 'runtime.ts - diff' },
    relationship: {
      hostAttitude: '礼貌而克制，保持观察',
      boredom: 50,
      loneliness: 48,
      fatigue: 20,
      minutesSinceLastUserTurn: 5,
      reminderBacklog: 0,
      lateNightActiveMinutes: 0,
      recentProactiveOutcomes: [],
    },
    ...overrides,
  }
}

describe('buildDesireMemory', () => {
  it('stores a withheld recheck desire when the mind holds back instead of speaking', () => {
    const desireMemory = buildDesireMemory({
      now: 20_000,
      context: createContext(),
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['need one more grounded pass'],
          staleRisks: [],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      },
      entityWorld: {
        focusEntityId: 'task::diff',
        activeEntityIds: ['task::diff'],
        entities: [],
        relations: [],
        openLoops: ['need one more grounded pass'],
        updatedAt: 20_000,
      },
      goalStack: {
        leadingHostGoalId: 'host',
        leadingAlicizationGoalId: 'alice',
        hostGoals: [],
        alicizationGoals: [{
          id: 'alice',
          owner: 'alicization',
          kind: 'clarify-scene',
          status: 'blocked',
          label: 're-ground the diff before outward reply',
          confidence: 0.72,
          urgency: 0.66,
          desireWeight: 0.58,
          blockers: ['need one more grounded pass'],
          entityIds: ['task::diff'],
          createdAt: 0,
          lastUpdatedAt: 20_000,
        }],
        unresolvedSummary: 'need one more grounded pass',
        updatedAt: 20_000,
      },
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.42,
        relationshipTrust: 0.46,
        guardingTendency: 0.5,
        misreadBurden: 0.34,
        carryOverDesire: 0.48,
        narrative: [],
        updatedAt: 20_000,
      },
      appraisal: {
        inferredHostGoal: 'inspect-change',
        currentKnot: 'runtime.ts - diff',
        waitingToVerify: 'need one more grounded pass',
        relationshipNeed: 'guidance',
        confidence: 0.56,
        surprise: 0.12,
        carePressure: 0.34,
        interruptionCost: 0.44,
        desireToSpeak: 0.42,
        notes: [],
      },
      initiative: {
        selectedAction: 'recheck',
        confidence: 0.72,
        motives: { clarify: 0.7 },
        why: 'need one more grounded pass',
        shouldSurface: true,
        shouldSpeak: false,
      },
      previous: null,
      recentTransition: null,
    })

    expect(desireMemory.activeDesires[0]?.status).toBe('withheld')
    expect(desireMemory.activeDesires[0]?.kind).toBe('recheck')
    expect(desireMemory.withheldCount).toBe(1)
  })

  it('re-surfaces an old withheld desire when afterglow opens the seam again', () => {
    const desireMemory = buildDesireMemory({
      now: 40_000,
      context: createContext({
        system: {
          ...createContext().system,
          inputActivity: 'idle' as const,
        },
      }),
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 5_000,
          attentionAgeMs: 5_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 40_000,
      },
      entityWorld: {
        focusEntityId: 'task::diff',
        activeEntityIds: ['task::diff'],
        entities: [],
        relations: [],
        openLoops: [],
        updatedAt: 40_000,
      },
      goalStack: {
        leadingHostGoalId: null,
        leadingAlicizationGoalId: null,
        hostGoals: [],
        alicizationGoals: [],
        unresolvedSummary: undefined,
        updatedAt: 40_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.62,
        relationshipTrust: 0.58,
        guardingTendency: 0.34,
        misreadBurden: 0.18,
        carryOverDesire: 0.52,
        narrative: [],
        updatedAt: 40_000,
      },
      appraisal: {
        inferredHostGoal: 'browse',
        confidence: 0.5,
        surprise: 0.08,
        carePressure: 0.18,
        interruptionCost: 0.16,
        desireToSpeak: 0.34,
        notes: [],
      },
      initiative: {
        selectedAction: 'hover',
        confidence: 0.6,
        motives: { accompany: 0.5 },
        why: 'stay nearby a little longer',
        shouldSurface: true,
        shouldSpeak: false,
      },
      previous: {
        activeDesires: [{
          id: 'desire::stay-near::old',
          kind: 'stay-near',
          status: 'withheld',
          reason: 'the shared tension just loosened; this is the seam to say it softly',
          strength: 0.78,
          goalId: 'old-goal',
          entityId: 'task::diff',
          reopenWhen: ['afterglow-window', 'host-open'],
          createdAt: 10_000,
          lastFeltAt: 12_000,
          lastSurfacedAt: null,
          expiresAt: 80_000,
        }],
        resurfacingDesireId: null,
        withheldCount: 1,
        updatedAt: 12_000,
      },
      recentTransition: {
        fromWatchMode: 'symbiotic-vision',
        toWatchMode: 'mnemonic-passive',
        fromScenario: 'coding',
        durationMs: 25 * 60_000,
        reason: 'afterglow',
        occurredAt: 35_000,
      },
    })

    expect(desireMemory.resurfacingDesireId).toBe('desire::stay-near::old')
    expect(desireMemory.activeDesires.some(desire => desire.id === 'desire::stay-near::old')).toBe(true)
  })

  it('stores a withheld repair desire when action ecology decides to repair before outward reply', () => {
    const desireMemory = buildDesireMemory({
      now: 55_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::debug',
          kind: 'debugging',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts diff drift',
          summary: 'The live diff and remembered continuity do not line up yet.',
          confidence: 0.74,
          significance: 0.78,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 55_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['which hunk actually changed?'],
          staleRisks: ['memory drift'],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 55_000,
          attentionAgeMs: 55_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 55_000,
      },
      entityWorld: {
        focusEntityId: 'task::runtime-diff',
        activeEntityIds: ['task::runtime-diff'],
        entities: [],
        relations: [],
        openLoops: ['which hunk actually changed?'],
        updatedAt: 55_000,
      },
      goalStack: {
        leadingHostGoalId: 'host',
        leadingAlicizationGoalId: 'alice',
        hostGoals: [],
        alicizationGoals: [{
          id: 'alice',
          owner: 'alicization',
          kind: 'clarify-scene',
          status: 'blocked',
          label: 'repair the scene before outward reply',
          confidence: 0.72,
          urgency: 0.64,
          desireWeight: 0.6,
          blockers: ['memory drift'],
          entityIds: ['task::runtime-diff'],
          createdAt: 0,
          lastUpdatedAt: 55_000,
        }],
        unresolvedSummary: 'memory drift',
        updatedAt: 55_000,
      },
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.42,
        relationshipTrust: 0.5,
        guardingTendency: 0.46,
        misreadBurden: 0.4,
        carryOverDesire: 0.44,
        narrative: [],
        updatedAt: 55_000,
      },
      appraisal: {
        inferredHostGoal: 'inspect-change',
        currentKnot: 'runtime.ts diff drift',
        waitingToVerify: 'which hunk actually changed?',
        relationshipNeed: 'guidance',
        confidence: 0.52,
        surprise: 0.16,
        carePressure: 0.28,
        interruptionCost: 0.46,
        desireToSpeak: 0.4,
        notes: ['repair-first'],
      },
      initiative: {
        selectedAction: 'recheck',
        selectedThreadId: 'repair-thread',
        confidence: 0.74,
        motives: { clarify: 0.72 },
        why: 'The first move is to repair the drift.',
        shouldSurface: true,
        shouldSpeak: false,
      },
      deliberationState: {
        primaryThreadId: 'repair-thread',
        dominantNeed: 'repair',
        readiness: 0.42,
        threads: [{
          id: 'repair-thread',
          kind: 'repair-misread',
          status: 'holding',
          summary: 'Repair the drift between continuity and the live diff.',
          desiredOutcome: 'reground the scene',
          focusBeliefId: 'belief-1',
          focusInquiryId: 'inquiry-1',
          concernId: null,
          surfacePressure: 0.22,
          silencePressure: 0.66,
          embodiedPresence: 'hesitant',
          startedAt: 0,
          lastUpdatedAt: 55_000,
          expiresAt: 120_000,
        }],
        narrative: ['repair-before-claim'],
        updatedAt: 55_000,
      },
      actionEcology: {
        mode: 'repair-before-speaking',
        selectedThreadId: 'repair-thread',
        readiness: 0.38,
        surfacePressure: 0.24,
        silencePressure: 0.72,
        suggestedStyle: 'silent-observe',
        embodiedPresence: 'hesitant',
        shouldSurface: true,
        shouldSpeak: false,
        why: 'She still needs a cleaner grounding pass before treating the moment as speakable.',
        updatedAt: 55_000,
      },
      previous: null,
      recentTransition: null,
    })

    expect(desireMemory.activeDesires[0]?.kind).toBe('recheck')
    expect(desireMemory.activeDesires[0]?.status).toBe('withheld')
    expect(desireMemory.activeDesires[0]?.reason).toContain('cleaner grounding pass')
    expect(desireMemory.activeDesires[0]?.reopenWhen).toContain('repair-cleared')
  })
})
