import { describe, expect, it } from 'vitest'

import { buildDialogueActKernel, buildDialogueActKernelSystemBlock, normalizeDialogueActKernel } from './dialogue-act-kernel'
import { buildAlicizationDigitalLifeRuntimeSurface } from './digital-life-kernel'
import { createDefaultVisualPresenceState } from './visual-episodic-memory'

describe('dialogue-act-kernel', () => {
  it('collapses answer planning and reply motive into one authoritative kernel', () => {
    const kernel = buildDialogueActKernel({
      now: 1,
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'VS Code diff with a removed null guard',
        source: 'screen-semantic-summary',
        confidence: 0.93,
        target: {
          appName: 'Visual Studio Code',
          processName: 'Code',
          title: 'review.diff - Project Alice',
        },
        beganAt: 1,
        lastSeenAt: 1,
      },
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        currentKnot: 'The diff removed a null guard before dereferencing the value.',
        relationshipNeed: 'guidance',
        confidence: 0.84,
        surprise: 0.2,
        carePressure: 0.34,
        interruptionCost: 0.21,
        desireToSpeak: 0.71,
        notes: [],
      },
      discourseState: {
        currentTurnSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        currentTurnSummary: 'The host wants to know what is wrong with the current diff.',
        currentQuestion: 'What is wrong with this diff?',
        owedAction: 'guide-task',
        relationMove: 'guide',
        continuityMode: 'task-first',
        confidence: 0.82,
        narrative: [],
        updatedAt: 1,
      },
      conversationState: {
        jointThread: 'Explain the current diff before suggesting changes.',
        hostMove: 'What is wrong with this diff?',
        activeProject: 'VS Code diff',
        unansweredQuestion: 'What is wrong with this diff?',
        activeCommitments: ['Pay off the active diff first.'],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: ['VS Code diff'],
        shouldHoldThread: true,
        confidence: 0.85,
        narrative: [],
        updatedAt: 1,
      },
      dialogueWorldThread: {
        activeThread: 'The active diff still needs a grounded explanation.',
        currentQuestion: 'What is wrong with this diff?',
        openLoops: ['diff explanation'],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'steady',
        memoryMode: 'task-thread',
        recallKeys: ['VS Code diff'],
        lastUserMove: 'What is wrong with this diff?',
        lastOutcome: 'pending',
        confidence: 0.83,
        narrative: [],
        updatedAt: 1,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        speechObligation: 'guide-task',
        relationMove: 'guide',
        turnMode: 'guide-current-knot',
        responseMode: 'guide-current-knot',
        recommendedAct: 'guide',
        evidenceMode: 'live-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'backgrounded',
        relationshipPosture: 'warm',
        openingDirective: 'Open from the failing branch immediately.',
        openingClaim: 'The removed null guard is the active bug in this diff.',
        supportingReality: ['The dereference now happens without the guard.'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Point to the exact branch and restore the guard.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: ['Lead with the failing branch.'],
        mustNotDo: ['Do not drift into generic advice.'],
        confidence: 0.86,
        narrative: [],
        updatedAt: 1,
      },
      replyDeliberation: {
        selectedMotive: 'guide',
        speakingFrom: 'task-thread',
        memoryMode: 'task-thread',
        openingBeat: 'Pay off the current diff before anything else.',
        whyThisReplyNow: 'The failing branch is already visible, so the answer should start there.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: ['Pay off the current diff before anything else.'],
        mustAvoid: ['Do not reuse stale browser residue.'],
        confidence: 0.88,
        narrative: [],
        updatedAt: 1,
      },
      answerPlanner: {
        act: 'guide',
        evidenceMode: 'live-grounded',
        confidence: 0.9,
        governingFocus: 'Localize the failing branch in the current diff.',
        openingMove: 'State the failing branch first.',
        answerIntent: 'Explain the removed guard before proposing edits.',
        relationshipPosture: 'warm',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: false,
        mustDo: ['Move from failing branch to exact fix.'],
        mustNotDo: ['Do not broaden into a checklist.'],
        narrative: [],
        updatedAt: 1,
      },
      privateThought: {
        stance: 'nudge',
        confidence: 0.77,
        rationaleTags: ['diff'],
        thoughtText: 'stay with the branch that actually broke',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 10,
        emotionalTension: 'tense-debug',
      },
      worldModel: {
        activeThread: {
          id: 'debug-thread',
          kind: 'debugging',
          status: 'active',
          source: 'grounded-scene',
          title: 'Diff regression',
          summary: 'A current code diff likely removed a required guard.',
          confidence: 0.86,
          significance: 0.8,
          unresolved: true,
          beganAt: 1,
          lastUpdatedAt: 1,
        },
        lingeringThreads: [],
        focusTarget: {
          appName: 'Visual Studio Code',
          processName: 'Code',
          title: 'review.diff - Project Alice',
        },
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['The guard is gone in the active branch.'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 10_000,
          attentionAgeMs: 10_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 1,
      },
    })

    expect(kernel).not.toBeNull()
    expect(kernel?.speechAct).toBe('guide')
    expect(kernel?.turnMode).toBe('guide-current-knot')
    expect(kernel?.hostGoal).toBe('resolve-problem')
    expect(kernel?.relationNeed).toBe('guidance')
    expect(kernel?.selectedEvidence[0]?.summary).toContain('removed null guard')
    expect(kernel?.mustSay).toContain('The failing branch is already visible, so the answer should start there.')
    expect(kernel?.mustAvoid).toContain('Do not broaden into a checklist.')
  })

  it('normalizes and renders persisted kernel snapshots', () => {
    const kernel = normalizeDialogueActKernel({
      subject: 'task-knot',
      hostGoal: 'resolve-problem',
      relationNeed: 'guidance',
      activeProject: 'VS Code diff',
      truthMode: 'live-grounded',
      speechAct: 'guide',
      turnMode: 'guide-current-knot',
      screenReferenceMode: 'helpful',
      speakingFrom: 'task-thread',
      selectedEvidence: [{
        kind: 'scene',
        source: 'current-scene',
        summary: 'VS Code diff with missing guard',
        confidence: 0.9,
      }],
      openingClaim: 'The missing guard is the current bug.',
      openingMove: 'State the missing guard before anything else.',
      whyNow: 'The host is asking about the active diff.',
      mustSay: ['Answer the current diff directly.'],
      mustAvoid: ['Do not answer from stale residue.'],
      sourceTrace: ['speech-act:guide'],
      confidence: 0.9,
      updatedAt: 1,
    })

    const block = buildDialogueActKernelSystemBlock(kernel)
    expect(kernel?.subject).toBe('task-knot')
    expect(block).toContain('[ALICIZATION_DIALOGUE_ACT_KERNEL]')
    expect(block).toContain('speech_act=guide')
    expect(block).toContain('provider_instruction_status=withheld; reason=non_structured_source_text; visibility=internal-structured')
    expect(block).not.toContain('Do not answer from stale residue.')
  })

  it('withholds non-structured fixed template signals from the provider-facing kernel system block', () => {
    const kernel = normalizeDialogueActKernel({
      subject: 'general',
      hostGoal: 'chat',
      relationNeed: 'companionship',
      activeProject: null,
      truthMode: 'dialogue-grounded',
      speechAct: 'answer',
      turnMode: 'answer',
      screenReferenceMode: 'avoid',
      speakingFrom: 'dialogue-bond',
      selectedEvidence: [],
      openingClaim: 'Continue the current answer.',
      openingMove: '继续回答',
      whyNow: 'host asked',
      mustSay: [
        'Keep this on one continuous her line instead of restarting.',
        'continuity_constraint=anti_restart; timing=before_widening',
      ],
      mustAvoid: [
        'Do not rewrite the still-live line as a fresh opening.',
      ],
      sourceTrace: [],
      confidence: 0.7,
      updatedAt: 123,
    })

    const block = buildDialogueActKernelSystemBlock(kernel)

    expect(block).toContain('required_signals=')
    expect(block).toContain('provider_instruction_status=withheld; reason=non_structured_source_text; visibility=internal-structured')
    expect(block).toContain('continuity_constraint=anti_restart; timing=before_widening')
    expect(block).not.toContain('one continuous her')
    expect(block).not.toContain('Do not rewrite the still-live line')
    expect(block).not.toContain('same-her closure seam')
  })

  it('does not turn dialogue-first host turns into fake project evidence', () => {
    const kernel = buildDialogueActKernel({
      now: 2,
      discourseState: {
        currentTurnSubject: 'host-state',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'The host sounds tired and wants company.',
        currentQuestion: null,
        owedAction: 'care-host',
        relationMove: 'care',
        continuityMode: 'dialogue-first',
        confidence: 0.8,
        narrative: [],
        updatedAt: 2,
      },
      conversationState: {
        jointThread: '这题好难，你可以帮帮我吗',
        hostMove: '这题好难，你可以帮帮我吗',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'care',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['late-night'],
        shouldHoldThread: false,
        confidence: 0.58,
        narrative: [],
        updatedAt: 2,
      },
      answerCompiler: {
        answerSubject: 'host-state',
        screenReferenceMode: 'avoid',
        speechObligation: 'care-host',
        relationMove: 'care',
        turnMode: 'care',
        responseMode: 'care-with-boundary',
        recommendedAct: 'care',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'gentle-care',
        personaKernelMode: 'full',
        relationshipPosture: 'tender',
        openingDirective: 'Open with care that answers the current state directly.',
        openingClaim: 'The host sounds overwhelmed and needs a steadier landing.',
        supportingReality: ['The host is surfacing a hard moment directly.'],
        uncertaintyBoundary: null,
        careVector: 'Stay near the tiredness without repeating it back.',
        nextMove: 'Offer calm help without parroting the host.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: ['Stay with the host condition.'],
        mustNotDo: ['Do not echo the host word-for-word.'],
        confidence: 0.84,
        narrative: [],
        updatedAt: 2,
      },
      replyDeliberation: {
        selectedMotive: 'care',
        speakingFrom: 'dialogue-bond',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Answer the host condition directly.',
        whyThisReplyNow: 'The host just surfaced a hard moment in the dialogue.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: ['Stay near the host condition.'],
        mustAvoid: ['Do not drift into screen narration.'],
        confidence: 0.78,
        narrative: [],
        updatedAt: 2,
      },
      privateThought: {
        stance: 'care',
        confidence: 0.82,
        rationaleTags: ['care'],
        thoughtText: 'stay with the host condition, not the old screen carry',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'concerned',
        expiresAt: 10,
        emotionalTension: 'late-night-drain',
      },
      currentScene: {
        workloadKind: 'browser',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'Entire screen',
        source: 'foreground-window-heuristic',
        confidence: 0.74,
        target: {
          appName: 'Alicization',
          processName: 'Codex',
          title: 'Chat Overlay',
        },
        beganAt: 1,
        lastSeenAt: 2,
      },
      worldModel: {
        activeThread: {
          id: 'thread::old-screen',
          kind: 'browsing',
          status: 'lingering',
          source: 'continuity',
          title: 'Entire screen',
          summary: 'A generic old screen carry is still hanging around.',
          confidence: 0.5,
          significance: 0.32,
          unresolved: false,
          beganAt: 1,
          lastUpdatedAt: 2,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 5_000,
          attentionAgeMs: 5_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 2,
      },
    })

    expect(kernel?.activeProject).toBeNull()
    expect(kernel?.selectedEvidence.some(item => item.kind === 'project')).toBe(false)
    expect(kernel?.openingClaim).toBe('The host sounds overwhelmed and needs a steadier landing.')
  })

  it('does not let desktop carry become the first evidence for self turns', () => {
    const kernel = buildDialogueActKernel({
      now: 3,
      currentScene: {
        workloadKind: 'unknown',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'macOS desktop screenshot with wallpaper and dock',
        source: 'screen-semantic-summary',
        confidence: 0.74,
        target: {
          appName: 'Finder',
          processName: 'Finder',
          title: 'Entire screen',
        },
        beganAt: 1,
        lastSeenAt: 3,
      },
      discourseState: {
        currentTurnSubject: 'alicization-self',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'The host is asking Alicization directly about herself.',
        currentQuestion: '你是笨蛋吗',
        owedAction: 'answer-self',
        relationMove: 'self-disclose',
        continuityMode: 'dialogue-first',
        confidence: 0.76,
        narrative: [],
        updatedAt: 3,
      },
      conversationState: {
        jointThread: 'The host is asking Alicization directly about herself.',
        hostMove: '你是笨蛋吗',
        activeProject: null,
        unansweredQuestion: '你是笨蛋吗',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'self-disclose',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你是笨蛋吗'],
        shouldHoldThread: true,
        confidence: 0.75,
        narrative: [],
        updatedAt: 3,
      },
      dialogueWorldThread: {
        activeThread: 'The host is asking Alicization directly about herself.',
        currentQuestion: '你是笨蛋吗',
        openLoops: ['你是笨蛋吗'],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'warming',
        memoryMode: 'dialogue-carry',
        recallKeys: ['你是笨蛋吗'],
        lastUserMove: '你是笨蛋吗',
        lastAssistantMove: null,
        lastOutcome: 'pending',
        pendingValidation: null,
        confidence: 0.7,
        narrative: [],
        updatedAt: 3,
      },
      answerCompiler: {
        answerSubject: 'alicization-self',
        screenReferenceMode: 'avoid',
        speechObligation: 'answer-self',
        relationMove: 'self-disclose',
        turnMode: 'answer',
        responseMode: 'answer-naturally',
        recommendedAct: 'answer',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        openingDirective: 'Answer from Alicization directly.',
        openingClaim: 'The host is asking Alicization directly about herself.',
        supportingReality: ['The host is asking Alicization directly about herself.'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Answer directly from Alicization.',
        suppressAssociativeRecall: false,
        labelCarryAsMemory: false,
        maxSentences: 3,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.78,
        narrative: [],
        updatedAt: 3,
      },
      replyDeliberation: {
        selectedMotive: 'attune',
        speakingFrom: 'self-continuity',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Answer the host directly.',
        whyThisReplyNow: '你是笨蛋吗',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.72,
        narrative: [],
        updatedAt: 3,
      },
      answerPlanner: {
        act: 'answer',
        evidenceMode: 'dialogue-grounded',
        confidence: 0.76,
        governingFocus: 'Answer the host directly from Alicization.',
        openingMove: 'Answer directly.',
        answerIntent: 'Answer from Alicization.',
        relationshipPosture: 'warm',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: false,
        mustDo: [],
        mustNotDo: [],
        narrative: [],
        updatedAt: 3,
      },
      privateThought: {
        stance: 'observe',
        confidence: 0.7,
        rationaleTags: [],
        thoughtText: 'The host is testing Alicization directly.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'hesitant',
        expiresAt: 30,
        emotionalTension: 'restless-switching',
      },
    })

    expect(kernel?.selectedEvidence[0]?.summary).toBe('你是笨蛋吗')
    expect(kernel?.selectedEvidence.some(item => item.kind === 'scene')).toBe(false)
  })

  it('clamps repair directives when the turn is dialogue-first', () => {
    const kernel = buildDialogueActKernel({
      now: 4,
      discourseState: {
        currentTurnSubject: 'host-state',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'The host needs reassurance in dialogue.',
        currentQuestion: '你会不会烦我',
        owedAction: 'care-host',
        relationMove: 'care',
        continuityMode: 'dialogue-first',
        confidence: 0.8,
        narrative: [],
        updatedAt: 4,
      },
      conversationState: {
        jointThread: '你会不会烦我',
        hostMove: '你会不会烦我',
        activeProject: null,
        unansweredQuestion: '你会不会烦我',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'care',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你会不会烦我'],
        shouldHoldThread: true,
        confidence: 0.74,
        narrative: [],
        updatedAt: 4,
      },
      answerCompiler: {
        answerSubject: 'host-state',
        screenReferenceMode: 'avoid',
        speechObligation: 'repair-truth',
        relationMove: 'repair',
        turnMode: 'screen-repair',
        responseMode: 'care-with-boundary',
        recommendedAct: 'ask-reground',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'gentle-care',
        personaKernelMode: 'full',
        relationshipPosture: 'tender',
        openingDirective: 'Stay with the host and reassure directly.',
        openingClaim: 'The host is asking for reassurance right now.',
        supportingReality: ['The host asked directly in dialogue.'],
        uncertaintyBoundary: null,
        careVector: 'Keep the response near reassurance, not grounding.',
        nextMove: 'Reassure first, no screen repair prompt.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 3,
        mustDo: ['Answer the host condition directly.'],
        mustNotDo: ['Do not ask for regrounding in this turn.'],
        confidence: 0.83,
        narrative: [],
        updatedAt: 4,
      },
      replyDeliberation: {
        selectedMotive: 'repair',
        speakingFrom: 'dialogue-bond',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Answer the host condition directly.',
        whyThisReplyNow: 'This is a dialogue-first reassurance turn.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: ['Keep the response in dialogue.'],
        mustAvoid: ['Do not request new grounding.'],
        confidence: 0.81,
        narrative: [],
        updatedAt: 4,
      },
      answerPlanner: {
        act: 'ask-reground',
        evidenceMode: 'dialogue-grounded',
        confidence: 0.8,
        governingFocus: 'Stabilize the host in dialogue.',
        openingMove: 'Start with reassurance.',
        answerIntent: 'Reassure the host without scene repair.',
        relationshipPosture: 'tender',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: false,
        mustDo: ['Keep reassurance primary.'],
        mustNotDo: ['Do not switch to screen repair mode.'],
        narrative: [],
        updatedAt: 4,
      },
      privateThought: {
        stance: 'care',
        confidence: 0.8,
        rationaleTags: ['reassurance'],
        thoughtText: 'Dialogue-first turn; do not ask for screen reground.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'concerned',
        expiresAt: 20,
        emotionalTension: 'late-night-drain',
      },
    })

    expect(kernel).not.toBeNull()
    expect(kernel?.speechAct).toBe('care')
    expect(kernel?.turnMode).toBe('care')
    expect(kernel?.sourceTrace).toContain('kernel-invariant:dialogue-first-repair-clamped')
  })

  it('prefers runtimeSurface over conflicting raw inputs', () => {
    const runtimeBackedState = createDefaultVisualPresenceState(5)
    runtimeBackedState.currentScene = {
      workloadKind: 'coding',
      contentKind: 'diff',
      scenario: 'coding',
      summary: 'Runtime diff with the missing guard still visible.',
      source: 'screen-semantic-summary',
      confidence: 0.92,
      target: {
        appName: 'Visual Studio Code',
        processName: 'Code',
        title: 'runtime.diff - Project Alice',
      },
      beganAt: 1,
      lastSeenAt: 5,
    }
    runtimeBackedState.appraisal = {
      inferredHostGoal: 'resolve-problem',
      currentKnot: 'The runtime branch still dereferences before guarding.',
      relationshipNeed: 'guidance',
      confidence: 0.88,
      surprise: 0.2,
      carePressure: 0.3,
      interruptionCost: 0.2,
      desireToSpeak: 0.76,
      notes: [],
    }
    runtimeBackedState.discourseState = {
      currentTurnSubject: 'task-knot',
      screenReferenceMode: 'helpful',
      currentTurnSummary: 'Stay with the runtime diff.',
      currentQuestion: 'Which runtime branch is failing?',
      owedAction: 'guide-task',
      relationMove: 'guide',
      continuityMode: 'task-first',
      confidence: 0.84,
      narrative: [],
      updatedAt: 5,
    } as any
    runtimeBackedState.conversationState = {
      jointThread: 'Explain the runtime diff first.',
      hostMove: 'Which runtime branch is failing?',
      activeProject: 'Runtime diff',
      unansweredQuestion: 'Which runtime branch is failing?',
      owedRepair: null,
      activeCommitments: ['Stay on the runtime diff.'],
      relationFrame: 'guide',
      continuityPolicy: 'stay-on-thread',
      memoryMode: 'task-thread',
      memoryQueryHints: ['Runtime diff'],
      shouldHoldThread: true,
      confidence: 0.87,
      narrative: [],
      updatedAt: 5,
    } as any
    runtimeBackedState.dialogueWorldThread = {
      activeThread: 'Explain the runtime diff first.',
      currentQuestion: 'Which runtime branch is failing?',
      openLoops: ['Which runtime branch is failing?'],
      recentlyResolvedLoops: [],
      carriedFacts: ['Runtime broken guard'],
      relationDrift: 'steady',
      memoryMode: 'task-thread',
      recallKeys: ['Runtime diff'],
      lastUserMove: 'Which runtime branch is failing?',
      lastAssistantMove: null,
      lastOutcome: 'pending',
      pendingValidation: null,
      confidence: 0.83,
      narrative: [],
      updatedAt: 5,
    }
    runtimeBackedState.answerCompiler = {
      answerSubject: 'task-knot',
      screenReferenceMode: 'helpful',
      recommendedAct: 'guide',
      turnMode: 'guide-current-knot',
      evidenceMode: 'live-grounded',
      openingClaim: 'The runtime broken guard is still the live issue.',
      openingDirective: 'Name the broken guard first.',
      nextMove: 'Point to the runtime branch first.',
      mustNotDo: ['Do not drift into raw conflict.'],
      confidence: 0.86,
    } as any
    runtimeBackedState.replyDeliberation = {
      selectedMotive: 'guide',
      speakingFrom: 'task-thread',
      openingBeat: 'Pay off the runtime branch first.',
      whyThisReplyNow: 'The runtime diff is still visible.',
      mustAvoid: ['Do not reuse raw conflict.'],
      confidence: 0.85,
      updatedAt: 5,
    } as any
    runtimeBackedState.answerPlanner = {
      act: 'guide',
      evidenceMode: 'live-grounded',
      confidence: 0.9,
      governingFocus: 'Localize the runtime branch first.',
      openingMove: 'Name the runtime branch first.',
      answerIntent: 'Explain the runtime guard break before edits.',
      relationshipPosture: 'warm',
      shouldAskForGrounding: false,
      shouldAcknowledgeRepair: false,
      mustDo: ['Stay with the runtime branch.'],
      mustNotDo: ['Do not switch to raw conflict.'],
      narrative: [],
      updatedAt: 5,
    }
    runtimeBackedState.privateThought = {
      stance: 'nudge',
      confidence: 0.78,
      rationaleTags: ['runtime'],
      thoughtText: 'Stay on the runtime diff seam.',
      shouldSpeak: true,
      suggestedStyle: 'light-nudge',
      embodiedPresence: 'attentive',
      expiresAt: 50,
      emotionalTension: 'tense-debug',
    } as any
    runtimeBackedState.worldModel = {
      activeThread: {
        id: 'thread::runtime',
        kind: 'debugging',
        status: 'active',
        source: 'grounded-scene',
        title: 'Runtime diff',
        summary: 'A runtime diff still shows the missing guard.',
        confidence: 0.88,
        significance: 0.84,
        unresolved: true,
        beganAt: 1,
        lastUpdatedAt: 5,
        target: null,
      },
      lingeringThreads: [],
      focusTarget: {
        appName: 'Visual Studio Code',
        processName: 'Code',
        title: 'runtime.diff - Project Alice',
      },
      epistemicState: {
        certainty: 'grounded',
        freshness: 'live',
        seenNow: [],
        inferredNow: [],
        openQuestions: [],
        staleRisks: [],
      },
      continuity: {
        label: 'staying-with-thread',
        sceneAgeMs: 5_000,
        attentionAgeMs: 5_000,
        sameSceneAsBefore: true,
        sameAttentionAsBefore: true,
        afterglowOpen: false,
      },
      hostState: {
        availability: 'focused',
        burden: 'moderate',
      },
      updatedAt: 5,
    }

    const kernel = buildDialogueActKernel({
      now: 5,
      currentScene: {
        workloadKind: 'unknown',
        contentKind: 'unknown',
        scenario: 'general',
        summary: 'raw conflict',
        source: 'screen-semantic-summary',
        confidence: 0.2,
        target: {
          appName: 'Finder',
          processName: 'Finder',
          title: 'raw conflict',
        },
        beganAt: 1,
        lastSeenAt: 5,
      },
      discourseState: {
        currentTurnSubject: 'relationship',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'raw conflict',
        currentQuestion: 'raw conflict',
        owedAction: 'care-host',
        relationMove: 'care',
        continuityMode: 'dialogue-first',
        confidence: 0.2,
        narrative: [],
        updatedAt: 5,
      },
      conversationState: {
        jointThread: 'raw conflict',
        hostMove: 'raw conflict',
        activeProject: 'raw conflict',
        unansweredQuestion: 'raw conflict',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'care',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['raw conflict'],
        shouldHoldThread: false,
        confidence: 0.2,
        narrative: [],
        updatedAt: 5,
      },
      runtimeSurface: buildAlicizationDigitalLifeRuntimeSurface(runtimeBackedState),
    })

    expect(kernel?.subject).toBe('task-knot')
    expect(kernel?.screenReferenceMode).toBe('helpful')
    expect(kernel?.activeProject).toBe('Runtime diff')
    expect(kernel?.openingClaim?.toLowerCase()).toContain('runtime diff')
    expect(kernel?.selectedEvidence[0]?.summary).toContain('Runtime diff')
  })
})
