import { describe, expect, it } from 'vitest'

import {
  buildDialogueWorldThread,
  buildDialogueWorldThreadSystemBlock,
} from './dialogue-world-thread'

describe('buildDialogueWorldThread', () => {
  it('carries the live coding seam across turns instead of flattening it into generic memory', () => {
    const state = buildDialogueWorldThread({
      now: 20_000,
      conversationState: {
        jointThread: 'We are still inside the risky ProjectAtlas diff.',
        hostMove: 'Tell me what is wrong with the current diff.',
        activeProject: 'ProjectAtlas diff',
        unansweredQuestion: 'What is wrong with this diff?',
        owedRepair: null,
        activeCommitments: ['Explain the risky seam before moving on.'],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: ['ProjectAtlas diff', 'What is wrong with this diff?'],
        shouldHoldThread: true,
        confidence: 0.82,
        narrative: [],
        updatedAt: 20_000,
      },
      replyDeliberation: {
        selectedMotive: 'guide',
        speakingFrom: 'task-thread',
        memoryMode: 'task-thread',
        openingBeat: 'Pay off the current knot first.',
        whyThisReplyNow: 'The current diff is still unresolved.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.84,
        narrative: [],
        updatedAt: 20_000,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        speechObligation: 'guide-task',
        relationMove: 'guide',
        turnMode: 'guide-current-knot',
        responseMode: 'guide-current-knot',
        recommendedAct: 'guide',
        evidenceMode: 'coarse-held',
        openingStyle: 'direct-answer',
        personaKernelMode: 'backgrounded',
        relationshipPosture: 'warm',
        openingDirective: 'Open from the current knot first.',
        openingClaim: 'The risky seam is still inside the current diff.',
        supportingReality: ['ProjectAtlas diff'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Point to the risky hunk first.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.84,
        narrative: [],
        updatedAt: 20_000,
      },
      privateThought: {
        stance: 'observe',
        confidence: 0.66,
        rationaleTags: ['diff'],
        thoughtText: 'Stay with the current diff seam.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 50_000,
        afterglowFromScenario: null,
        emotionalTension: 'tense-debug',
      },
      worldModel: {
        activeThread: {
          id: 'thread::diff',
          kind: 'change-review',
          status: 'active',
          source: 'continuity',
          title: 'ProjectAtlas diff',
          summary: 'A risky diff still feels unresolved.',
          confidence: 0.86,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      },
    })

    expect(state).toEqual(expect.objectContaining({
      activeThread: 'We are still inside the risky ProjectAtlas diff.',
      memoryMode: 'task-thread',
      relationDrift: 'steady',
      lastOutcome: 'none',
    }))
    expect(state?.openLoops).toContain('What is wrong with this diff?')
    expect(state?.recallKeys.join(' | ')).toContain('reply_motive:guide')
    expect(buildDialogueWorldThreadSystemBlock(state)).toContain('[ALICIZATION_DIALOGUE_WORLD_THREAD]')
  })

  it('drops stale screen loops and facts when the turn pivots back to dialogue-first', () => {
    const state = buildDialogueWorldThread({
      now: 40_000,
      conversationState: {
        jointThread: '你真可爱',
        hostMove: '你真可爱',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'attune',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你真可爱'],
        shouldHoldThread: false,
        confidence: 0.72,
        narrative: [],
        updatedAt: 40_000,
      },
      replyDeliberation: {
        selectedMotive: 'attune',
        speakingFrom: 'dialogue-bond',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Answer the host\'s question about Alicization directly.',
        whyThisReplyNow: '你真可爱',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.78,
        narrative: [],
        updatedAt: 40_000,
      },
      answerCompiler: {
        answerSubject: 'relationship',
        screenReferenceMode: 'avoid',
        speechObligation: 'answer-relationship',
        relationMove: 'attune',
        turnMode: 'accompany',
        responseMode: 'answer-naturally',
        recommendedAct: 'answer',
        evidenceMode: 'continuity-carry',
        openingStyle: 'light-accompaniment',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        openingDirective: 'Answer the host directly.',
        openingClaim: '你真可爱',
        supportingReality: ['Java interview questions and answers webpage'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Stay with the compliment.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 2,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.7,
        narrative: [],
        updatedAt: 40_000,
      },
      previous: {
        activeThread: 'What is wrong with this diff?',
        currentQuestion: 'What is wrong with this diff?',
        openLoops: ['What is wrong with this diff?'],
        recentlyResolvedLoops: [],
        carriedFacts: ['Java interview questions and answers webpage'],
        relationDrift: 'steady',
        memoryMode: 'task-thread',
        recallKeys: ['Java interview questions and answers webpage', 'What is wrong with this diff?'],
        lastUserMove: 'Tell me what is wrong with this diff.',
        lastAssistantMove: null,
        lastOutcome: 'none',
        pendingValidation: null,
        confidence: 0.8,
        narrative: [],
        updatedAt: 30_000,
      },
    })

    expect(state?.activeThread).toBe('你真可爱')
    expect(state?.openLoops).toEqual([])
    expect(state?.recentlyResolvedLoops).toEqual([])
    expect(state?.carriedFacts).toEqual([])
    expect(state?.recallKeys.join(' | ')).not.toContain('Java interview questions')
    expect(state?.recallKeys.join(' | ')).not.toContain('What is wrong with this diff?')
  })

  it('does not drag the previous repair shell into a fresh Alicization-side question', () => {
    const state = buildDialogueWorldThread({
      now: 60_000,
      conversationState: {
        jointThread: '你困了吗',
        hostMove: '你困了吗',
        activeProject: null,
        unansweredQuestion: '你困了吗',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'self-disclose',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你困了吗'],
        shouldHoldThread: true,
        confidence: 0.74,
        narrative: [],
        updatedAt: 60_000,
      },
      answerCompiler: {
        answerSubject: 'alicization-self',
        screenReferenceMode: 'avoid',
        speechObligation: 'answer-self',
        relationMove: 'self-disclose',
        turnMode: 'answer',
        responseMode: 'answer-naturally',
        recommendedAct: 'answer',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        openingDirective: 'Answer the host question directly.',
        openingClaim: '你困了吗',
        supportingReality: [],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Answer the host question directly.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 2,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.74,
        narrative: [],
        updatedAt: 60_000,
      },
      previous: {
        activeThread: 'The host is asking Alicization to repair the previous answer and speak more plainly.',
        currentQuestion: '说人话',
        openLoops: ['说人话'],
        recentlyResolvedLoops: [],
        carriedFacts: ['The host is asking Alicization to repair the previous answer and speak more plainly.'],
        relationDrift: 'repairing',
        memoryMode: 'dialogue-carry',
        recallKeys: ['The host is asking Alicization to repair the previous answer and speak more plainly.'],
        lastUserMove: '你说人话呗',
        lastAssistantMove: '我刚才那句真正的意思是……',
        lastOutcome: 'missed',
        pendingValidation: null,
        confidence: 0.78,
        narrative: [],
        updatedAt: 50_000,
      },
    })

    expect(state?.activeThread).toBe('你困了吗')
    expect(state?.currentQuestion).toBe('你困了吗')
    expect(state?.carriedFacts).toEqual([])
    expect(state?.recallKeys.join(' | ')).not.toContain('repair the previous answer')
  })
})
