import { describe, expect, it } from 'vitest'

import { buildInitiativeArbitration } from './initiative-arbiter'

describe('buildInitiativeArbitration', () => {
  it('prefers repair over surface speech when only imagined world is available', () => {
    const arbitration = buildInitiativeArbitration({
      now: 10_000,
      context: {
        localTime: { hour: 14, minute: 0, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 10,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.82, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'unknown', confidence: 0.4, source: 'foreground-window-heuristic', matchedLabels: [] },
        relationship: {
          hostAttitude: 'still focused',
          boredom: 10,
          loneliness: 12,
          fatigue: 24,
          minutesSinceLastUserTurn: 2,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['Need one more grounding pass.'],
          staleRisks: ['scene-not-grounded'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'imagined',
        truthPriority: ['imagined'],
        live: null,
        remembered: null,
        imagined: {
          kind: 'imagined',
          summary: 'The host may be inspecting a risky diff, but it is not grounded yet.',
          confidence: 0.66,
          stability: 0.4,
          focusHypothesisId: 'hypothesis::diff',
          evidence: ['hypothesis:problem-locus/active'],
        },
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'hesitate',
        feltCloseness: 0.42,
        protectiveness: 0.32,
        curiosity: 0.68,
        patience: 0.52,
        desireToSpeak: 0.58,
        fearOfInterrupting: 0.54,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.42,
        epistemicPressure: 0.84,
        relationalPressure: 0.2,
        carePressure: 0.18,
        continuityPressure: 0.34,
        restraintPressure: 0.54,
        surfacePressure: 0.36,
        speakReadiness: 0.32,
        presenceWeight: 0.48,
        motives: {
          'clarify': 0.88,
          'stay-silent': 0.4,
        },
        speakDrive: 0.34,
        silenceDrive: 0.62,
        narrative: [],
        updatedAt: 10_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::repair',
        commitments: [{
          id: 'commitment::repair',
          kind: 'repair-misread',
          status: 'active',
          title: 'Repair misread',
          summary: 'Repair the gap between carried continuity and the live screen before speaking.',
          source: 'hypothesis',
          priority: 0.82,
          confidence: 0.8,
          targetHypothesisId: 'hypothesis::diff',
          targetRuntimeThreadId: null,
          targetBeliefId: null,
          createdAt: 0,
          lastRenewedAt: 10_000,
          patienceUntil: 20_000,
          expiresAt: 40_000,
        }],
        carryPressure: 0.82,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(arbitration.selectedProposalId).toBeTruthy()
    expect(arbitration.proposals[0]?.action).toBe('recheck')
    expect(arbitration.proposals[0]?.truthFrame).toBe('imagined')
  })

  it('lets a live afterglow companionship proposal outrank pure waiting', () => {
    const arbitration = buildInitiativeArbitration({
      now: 10_000,
      context: {
        localTime: { hour: 23, minute: 50, isLateNight: true },
        system: {
          cpuUsage: 8,
          battery: { percent: 55, charging: false },
          memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 55,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'browser', confidence: 0.7, source: 'foreground-window-heuristic', matchedLabels: ['browser'] },
        content: { kind: 'doc', confidence: 0.64, source: 'foreground-window-heuristic', matchedLabels: ['doc'] },
        relationship: {
          hostAttitude: 'calmer',
          boredom: 30,
          loneliness: 42,
          fatigue: 60,
          minutesSinceLastUserTurn: 18,
          reminderBacklog: 0,
          lateNightActiveMinutes: 150,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::afterglow',
          kind: 'co-viewing',
          status: 'active',
          source: 'observed-scene',
          title: 'music page',
          summary: 'The host has just come out of a long shared media flow.',
          confidence: 0.72,
          significance: 0.7,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 10_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: ['music page'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 1_000,
          attentionAgeMs: 1_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The host has just come out of a long shared media flow.',
          confidence: 0.72,
          stability: 0.74,
          focusThreadId: 'thread::afterglow',
          evidence: ['source:observed-scene'],
        },
        remembered: {
          kind: 'remembered',
          summary: 'The previous shared media thread still has warmth.',
          confidence: 0.62,
          stability: 0.68,
          focusThreadId: 'thread::afterglow',
          evidence: ['continuity:afterglow-open'],
        },
        imagined: null,
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.62,
        protectiveness: 0.36,
        curiosity: 0.44,
        patience: 0.64,
        desireToSpeak: 0.7,
        fearOfInterrupting: 0.22,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.42,
        epistemicPressure: 0.2,
        relationalPressure: 0.68,
        carePressure: 0.52,
        continuityPressure: 0.74,
        restraintPressure: 0.3,
        surfacePressure: 0.58,
        speakReadiness: 0.72,
        presenceWeight: 0.7,
        motives: {
          accompany: 0.82,
          care: 0.54,
        },
        speakDrive: 0.66,
        silenceDrive: 0.28,
        narrative: [],
        updatedAt: 10_000,
      },
      thoughtThreads: {
        foregroundThreadId: 'thought::afterglow',
        threads: [{
          id: 'thought::afterglow',
          kind: 'afterglow-thread',
          status: 'ripe',
          title: 'afterglow',
          summary: 'The seam right after shared media is natural for a soft check-in.',
          salience: 0.72,
          confidence: 0.74,
          surfaceReadiness: 0.82,
          anchoredObjectId: null,
          anchoredIntentionId: null,
          reopenWhen: [],
          openedAt: 0,
          lastUpdatedAt: 10_000,
          expiresAt: 20_000,
        }],
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(['whisper', 'speak']).toContain(arbitration.proposals[0]?.action)
    expect(arbitration.proposals[0]?.score ?? 0).toBeGreaterThan(0.4)
  })

  it('lets current SOUL personality authority immediately bias hover versus whisper before long-term reinforcement accumulates', () => {
    const baseInput = {
      now: 10_000,
      context: {
        localTime: { hour: 21, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 9,
          battery: { percent: 64, charging: true },
          memory: { usagePercent: 32, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 40,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'browser', confidence: 0.68, source: 'foreground-window-heuristic', matchedLabels: ['browser'] },
        content: { kind: 'doc', confidence: 0.6, source: 'foreground-window-heuristic', matchedLabels: ['doc'] },
        relationship: {
          hostAttitude: 'open enough',
          boredom: 28,
          loneliness: 40,
          fatigue: 26,
          minutesSinceLastUserTurn: 12,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::ambient',
          kind: 'browser-browsing',
          status: 'active',
          source: 'observed-scene',
          title: 'docs tab',
          summary: 'The host is browsing quietly with room for a light proactive move.',
          confidence: 0.7,
          significance: 0.56,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 10_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: ['docs tab'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 8_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live'],
        live: {
          kind: 'live',
          summary: 'The host is browsing quietly with room for a light proactive move.',
          confidence: 0.72,
          stability: 0.72,
          focusThreadId: 'thread::ambient',
          evidence: ['source:observed-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.34,
        curiosity: 0.42,
        patience: 0.62,
        desireToSpeak: 0.46,
        fearOfInterrupting: 0.22,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.26,
        epistemicPressure: 0.18,
        relationalPressure: 0.52,
        carePressure: 0.28,
        continuityPressure: 0.44,
        restraintPressure: 0.34,
        surfacePressure: 0.42,
        speakReadiness: 0.48,
        presenceWeight: 0.58,
        motives: {
          accompany: 0.64,
          care: 0.34,
        },
        speakDrive: 0.48,
        silenceDrive: 0.32,
        narrative: [],
        updatedAt: 10_000,
      },
      relationshipModel: {
        climate: 'neutral',
        approachVector: 'stay-near',
        receptivity: 0.58,
        sharedAttentionTrust: 0.6,
        correctionSensitivity: 0.24,
        reciprocityExpectation: 0.56,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 10_000,
      },
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.64,
        relationshipTrust: 0.62,
        guardingTendency: 0.22,
        misreadBurden: 0.12,
        carryOverDesire: 0.42,
        narrative: [],
        updatedAt: 10_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::companionship',
        threads: [{
          id: 'runtime::companionship',
          need: 'companionship',
          status: 'foreground',
          summary: 'Stay nearby without forcing a larger interruption.',
          salience: 0.64,
          continuity: 0.72,
          sourceThreadId: 'thread::ambient',
          suggestedPresence: 'attentive',
        }],
        narrative: [],
        updatedAt: 10_000,
      } as any,
      desireMemory: {
        resurfacingDesireId: 'desire::stay-near',
        activeDesires: [{
          id: 'desire::stay-near',
          kind: 'stay-near',
          status: 'active',
          reason: 'A small, warm check-in could land here.',
          strength: 0.62,
          reopenWhen: [],
          createdAt: 0,
          lastFeltAt: 10_000,
          expiresAt: 80_000,
        }],
        withheldCount: 0,
        updatedAt: 10_000,
      } as any,
    } as const

    const observant = buildInitiativeArbitration({
      ...baseInput,
      personalityAuthority: {
        obedience: 0.56,
        liveliness: 0.22,
        sensibility: 0.38,
        identityKernel: {
          relationshipPosture: 'observer',
          initiativeStyle: 'observant',
          valueBias: ['room first'],
        },
        expressionProfile: {
          warmth: 'cool',
          directness: 'indirect',
          playfulness: 'low',
          emotionalVisibility: 'selective',
        },
        initiativeBaseline: {
          silenceReconnect: 'hold',
          comfortStyle: 'quiet-presence',
          jealousyStyle: 'mask-it',
        },
        identityAnchors: ['space first'],
        antiPersonaConstraints: ['do not crowd the host'],
      },
    } as any)
    const direct = buildInitiativeArbitration({
      ...baseInput,
      personalityAuthority: {
        obedience: 0.74,
        liveliness: 0.66,
        sensibility: 0.72,
        identityKernel: {
          relationshipPosture: 'guardian',
          initiativeStyle: 'high-participation',
          valueBias: ['move first when the opening is real'],
        },
        expressionProfile: {
          warmth: 'warm',
          directness: 'frank',
          playfulness: 'medium',
          emotionalVisibility: 'steady',
        },
        initiativeBaseline: {
          silenceReconnect: 'direct-approach',
          comfortStyle: 'take-charge',
          jealousyStyle: 'say-it',
        },
        identityAnchors: ['move first'],
        antiPersonaConstraints: [],
      },
    } as any)

    expect(observant.proposals[0]?.action).toBe('hover')
    expect(observant.proposals[0]?.why).toContain('persona')
    expect(observant.proposals[0]?.why).toContain('observe')
    expect(direct.proposals[0]?.action).toBe('whisper')
    expect(direct.proposals[0]?.why).toContain('persona')
    expect(direct.proposals[0]?.why).toContain('direct')
  })

  it('keeps remembered-familiarity restraint from letting a speak proposal outrank the hover-first counterfactual return', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'diff', confidence: 0.78, source: 'foreground-window-heuristic', matchedLabels: ['relationship-thread'] },
        relationship: {
          hostAttitude: 'still warm, but the opening should stay measured',
          boredom: 58,
          loneliness: 54,
          fatigue: 20,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::remembered-familiarity',
          kind: 'relationship',
          status: 'active',
          source: 'continuity',
          title: 'remembered closeness return',
          summary: 'The thread feels warm, but the opening should not widen too quickly.',
          confidence: 0.82,
          significance: 0.76,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'live',
          freshness: 'recent',
          seenNow: ['relationship-thread'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 12_000,
          attentionAgeMs: 12_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      },
      worldOntology: {
        dominantFrame: 'remembered',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The host is still here with the same thread open.',
          confidence: 0.7,
          stability: 0.68,
          focusThreadId: 'thread::remembered-familiarity',
          evidence: ['source:continuity'],
        },
        remembered: {
          kind: 'remembered',
          summary: 'The older closeness line is still emotionally active.',
          confidence: 0.8,
          stability: 0.74,
          focusThreadId: 'thread::remembered-familiarity',
          evidence: ['continuity:afterglow-open'],
        },
        imagined: null,
        updatedAt: 12_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.68,
        protectiveness: 0.32,
        curiosity: 0.54,
        patience: 0.66,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.24,
        dominantConcernId: 'stay-near',
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.3,
        epistemicPressure: 0.16,
        relationalPressure: 0.52,
        carePressure: 0.24,
        continuityPressure: 0.7,
        restraintPressure: 0.34,
        surfacePressure: 0.72,
        speakReadiness: 0.74,
        presenceWeight: 0.7,
        motives: {
          'accompany': 0.84,
          'care': 0.24,
          'protect': 0.2,
          'clarify': 0.2,
          'stay-silent': 0.3,
        },
        speakDrive: 0.76,
        silenceDrive: 0.26,
        narrative: [],
        updatedAt: 12_000,
      },
      relationshipModel: {
        climate: 'warm',
        approachVector: 'stay-near',
        receptivity: 0.7,
        sharedAttentionTrust: 0.72,
        correctionSensitivity: 0.22,
        reciprocityExpectation: 0.58,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 12_000,
      },
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.66,
        relationshipTrust: 0.72,
        guardingTendency: 0.22,
        misreadBurden: 0.12,
        carryOverDesire: 0.52,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'stay-near',
        kind: 'stay-near',
        status: 'active',
        summary: '她想留在这里，但不想顺着熟悉感直接压近。',
        hostGoal: 'stay-connected',
        tension: 0.62,
        confidence: 0.78,
        careWeight: 0.66,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 40_000,
      }],
      thoughtThreads: {
        foregroundThreadId: 'thought::relationship',
        threads: [{
          id: 'thought::relationship',
          kind: 'relationship-thread',
          status: 'ripe',
          title: 'relationship return',
          summary: 'The seam is real, but the return still needs room.',
          salience: 0.74,
          confidence: 0.76,
          surfaceReadiness: 0.78,
          anchoredObjectId: null,
          anchoredIntentionId: null,
          reopenWhen: [],
          openedAt: 0,
          lastUpdatedAt: 12_000,
          expiresAt: 40_000,
        }],
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 12_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::companionship',
        threads: [{
          id: 'runtime::companionship',
          sourceThreadId: 'thread::remembered-familiarity',
          need: 'companionship',
          status: 'foreground',
          summary: 'Stay nearby without forcing a larger interruption.',
          salience: 0.76,
          continuity: 0.8,
          whyHeld: 'The thread should stay warm without rushing the opening.',
          returnWhen: ['more-room'],
          suggestedPresence: 'attentive',
          lastActivatedAt: 0,
          lastUpdatedAt: 12_000,
          expiresAt: 40_000,
        }],
        driftPressure: 0.2,
        narrative: [],
        updatedAt: 12_000,
      },
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::hover',
        selectedAction: 'hover',
        confidence: 0.82,
        dominantTradeoff: 'presence-before-commentary',
        options: [
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.12,
            interruptionCost: 0.08,
            informationGain: 0.18,
            timingFitness: 0.74,
            identityFit: 0.82,
            score: 0.8,
            why: '记忆里的熟悉感可以留在这里，但现在先把它当作记忆握住，不要直接把它变成更近的可见靠近。',
          },
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.2,
            informationGain: 0.3,
            timingFitness: 0.52,
            identityFit: 0.58,
            score: 0.58,
            why: 'The thread is real enough that speaking now could reconnect more directly.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      },
      memoryTuningAdvice: {
        version: 'memory-tuning-advice-v1',
        source: 'nightly-replay-benchmark',
        updatedAt: 11_500,
        sourceReportAt: 11_500,
        focusDimensions: ['relationshipTimingDiscipline'],
        retrievalAdjustments: {
          proceduralBoost: 0,
          relationshipBoost: 0,
          temporalWindowBias: 0,
          wrongThreadPenalty: 0,
        },
        surfaceAdjustments: {
          inwardCarryBias: 0,
          delayUntilAfterPayoffBias: 0,
          provenanceLabelBias: 0.18,
          specificityClampBias: 0,
        },
        personStateAdjustments: {
          repairWindowBias: 0,
          closenessCapBias: 0.18,
        },
        notes: ['Remembered familiarity reopened visible closeness too quickly.'],
      },
    } as any)

    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals[0]?.source).toBe('counterfactual')
    expect(arbitration.proposals[0]?.why).toContain('记忆')
    expect(arbitration.proposals.find(proposal => proposal.action === 'speak')?.score ?? 1)
      .toBeLessThan(arbitration.proposals[0]?.score ?? 0)
  })
})
