import type { AlicizationMindDynamicsSnapshot } from '../../../shared/eventa'

import { describe, expect, it } from 'vitest'

import { buildInitiativeSnapshot } from './initiative-engine'
import { buildWorldModel } from './world-model'

function createMindDynamics(overrides: Partial<AlicizationMindDynamicsSnapshot> = {}): AlicizationMindDynamicsSnapshot {
  return {
    dominantMotive: 'clarify',
    worldPressure: 0.58,
    epistemicPressure: 0.28,
    relationalPressure: 0.34,
    carePressure: 0.24,
    continuityPressure: 0.48,
    restraintPressure: 0.28,
    surfacePressure: 0.62,
    speakReadiness: 0.62,
    presenceWeight: 0.58,
    motives: {
      'clarify': 0.68,
      'protect': 0.42,
      'accompany': 0.28,
      'care': 0.24,
      'stay-silent': 0.24,
    },
    speakDrive: 0.68,
    silenceDrive: 0.28,
    narrative: ['dominant motive is clarify.'],
    updatedAt: 10_000,
    ...overrides,
  }
}

describe('buildInitiativeSnapshot', () => {
  it('turns mature concern into speak/warn instead of a flat threshold', () => {
    const context = {
      localTime: { hour: 2, minute: 0, isLateNight: true },
      system: {
        cpuUsage: 10,
        battery: { percent: 50, charging: false },
        memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 40,
        inputActivity: 'idle' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'game' as const, confidence: 0.7, source: 'foreground-window-heuristic' as const, matchedLabels: ['game'] },
      content: { kind: 'gameplay' as const, confidence: 0.7, source: 'foreground-window-heuristic' as const, matchedLabels: ['gameplay'] },
      relationship: {
        hostAttitude: '礼貌而克制，保持观察',
        boredom: 50,
        loneliness: 66,
        fatigue: 84,
        minutesSinceLastUserTurn: 12,
        reminderBacklog: 0,
        lateNightActiveMinutes: 180,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 10_000,
      context,
      watchMode: 'mnemonic-passive',
      scene: {
        workloadKind: 'game',
        contentKind: 'gameplay',
        scenario: 'late-night-care',
        summary: 'gameplay',
        source: 'foreground-window-heuristic',
        confidence: 0.72,
        beganAt: 0,
        lastSeenAt: 10_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })
    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'mnemonic-passive',
      worldModel,
      appraisal: {
        inferredHostGoal: 'rest',
        confidence: 0.82,
        surprise: 0.14,
        carePressure: 0.94,
        interruptionCost: 0.1,
        desireToSpeak: 0.8,
        notes: ['late-night'],
      },
      concerns: [{
        id: 'care',
        kind: 'care-body',
        status: 'active',
        summary: '她担心你正在把自己拖进更深的疲惫里。',
        hostGoal: 'rest',
        tension: 0.9,
        confidence: 0.86,
        careWeight: 0.98,
        createdAt: 0,
        lastEvidenceAt: 10_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'protect',
        feltCloseness: 0.62,
        protectiveness: 0.9,
        curiosity: 0.12,
        patience: 0.54,
        desireToSpeak: 0.82,
        fearOfInterrupting: 0.2,
        dominantConcernId: 'care',
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'care',
        carePressure: 0.88,
        surfacePressure: 0.78,
        speakReadiness: 0.76,
        motives: {
          'care': 0.9,
          'protect': 0.82,
          'stay-silent': 0.18,
        },
        speakDrive: 0.82,
        silenceDrive: 0.24,
      }),
    })

    expect(['speak', 'warn']).toContain(initiative.selectedAction)
    expect(initiative.shouldSpeak).toBe(true)
    expect(initiative.selectedProposalId).toBeTruthy()
    expect((initiative.speakDrive ?? 0)).toBeGreaterThan(initiative.silenceDrive ?? 0)
    expect(['gentle-care', 'firm-warning']).toContain(initiative.preferredStyle)
    expect(['attentive', 'concerned']).toContain(initiative.preferredPresence)
  })

  it('selects hypothesis and runtime thread ids when a stable mind thread exists', () => {
    const context = {
      localTime: { hour: 14, minute: 0, isLateNight: false },
      system: {
        cpuUsage: 10,
        battery: { percent: 70, charging: true },
        memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 40,
        inputActivity: 'idle' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'coding' as const, confidence: 0.8, source: 'foreground-window-heuristic' as const, matchedLabels: ['cursor'] },
      content: { kind: 'error' as const, confidence: 0.82, source: 'foreground-window-heuristic' as const, matchedLabels: ['error'] },
      relationship: {
        hostAttitude: '礼貌而克制，保持观察',
        boredom: 32,
        loneliness: 28,
        fatigue: 18,
        minutesSinceLastUserTurn: 6,
        reminderBacklog: 0,
        lateNightActiveMinutes: 0,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 10_000,
      context,
      watchMode: 'symbiotic-vision',
      scene: {
        workloadKind: 'coding',
        contentKind: 'error',
        scenario: 'coding',
        summary: 'TypeScript error panel',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        beganAt: 0,
        lastSeenAt: 10_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })
    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'symbiotic-vision',
      worldModel,
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        confidence: 0.84,
        surprise: 0.12,
        carePressure: 0.34,
        interruptionCost: 0.18,
        desireToSpeak: 0.72,
        relationshipNeed: 'guidance',
        notes: ['grounded'],
      },
      concerns: [{
        id: 'help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: '她已经看见一个具体的故障点。',
        hostGoal: 'resolve-problem',
        tension: 0.82,
        confidence: 0.84,
        careWeight: 0.68,
        createdAt: 0,
        lastEvidenceAt: 10_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.64,
        curiosity: 0.74,
        patience: 0.44,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.22,
        dominantConcernId: 'help-fix',
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        surfacePressure: 0.76,
        speakReadiness: 0.74,
        motives: {
          'clarify': 0.84,
          'protect': 0.56,
          'stay-silent': 0.18,
        },
        speakDrive: 0.8,
        silenceDrive: 0.22,
      }),
      hypothesisGraph: {
        activeHypothesisId: 'problem-locus::error',
        focusHypothesisIds: ['problem-locus::error'],
        driftPressure: 0.22,
        hypotheses: [{
          id: 'problem-locus::error',
          kind: 'problem-locus',
          status: 'active',
          summary: 'The error locus is narrow enough to approach.',
          confidence: 0.84,
          salience: 0.86,
          evidence: ['error'],
          counterEvidence: [],
          formedAt: 0,
          lastUpdatedAt: 10_000,
          expiresAt: 120_000,
        }],
        narrative: [],
        updatedAt: 10_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::delib-1',
        threads: [{
          id: 'runtime::delib-1',
          sourceThreadId: 'delib-1',
          sourceHypothesisId: 'problem-locus::error',
          need: 'guidance',
          status: 'foreground',
          summary: 'Point toward the failing locus.',
          salience: 0.86,
          continuity: 0.72,
          whyHeld: 'Point toward the failing locus.',
          returnWhen: ['problem-locus-sharpens'],
          suggestedPresence: 'attentive',
          lastActivatedAt: 0,
          lastUpdatedAt: 10_000,
          expiresAt: 120_000,
        }],
        driftPressure: 0.22,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(initiative.selectedHypothesisId).toBe('problem-locus::error')
    expect(initiative.selectedRuntimeThreadId).toBe('runtime::delib-1')
  })

  it('inherits the selected counterfactual option instead of re-deriving action locally', () => {
    const context = {
      localTime: { hour: 14, minute: 0, isLateNight: false },
      system: {
        cpuUsage: 10,
        battery: { percent: 70, charging: true },
        memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 40,
        inputActivity: 'idle' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'coding' as const, confidence: 0.8, source: 'foreground-window-heuristic' as const, matchedLabels: ['cursor'] },
      content: { kind: 'diff' as const, confidence: 0.82, source: 'foreground-window-heuristic' as const, matchedLabels: ['diff'] },
      relationship: {
        hostAttitude: '礼貌而克制，保持观察',
        boredom: 32,
        loneliness: 28,
        fatigue: 18,
        minutesSinceLastUserTurn: 6,
        reminderBacklog: 0,
        lateNightActiveMinutes: 0,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 10_000,
      context,
      watchMode: 'symbiotic-vision',
      scene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'Diff around runtime.ts',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        beganAt: 0,
        lastSeenAt: 10_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })
    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'symbiotic-vision',
      worldModel,
      appraisal: {
        inferredHostGoal: 'inspect-change',
        confidence: 0.84,
        surprise: 0.12,
        carePressure: 0.24,
        interruptionCost: 0.12,
        desireToSpeak: 0.68,
        relationshipNeed: 'guidance',
        notes: ['grounded'],
      },
      concerns: [],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.42,
        curiosity: 0.74,
        patience: 0.44,
        desireToSpeak: 0.72,
        fearOfInterrupting: 0.22,
        dominantConcernId: null,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        speakDrive: 0.72,
        silenceDrive: 0.26,
      }),
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.84,
        dominantTradeoff: 'specific-help-over-distance',
        options: [{
          id: 'counterfactual::speak',
          action: 'speak',
          style: 'light-nudge',
          embodiedPresence: 'attentive',
          relationshipCost: 0.18,
          interruptionCost: 0.2,
          informationGain: 0.52,
          timingFitness: 0.72,
          identityFit: 0.82,
          score: 0.8,
          why: 'The diff knot is local enough that speaking now would help.',
        }],
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(initiative.selectedAction).toBe('speak')
    expect(initiative.selectedProposalId).toContain('counterfactual')
    expect(initiative.selectedTruthFrame).toBe('live')
    expect(initiative.selectedCounterfactualOptionId).toBe('counterfactual::speak')
    expect(initiative.preferredStyle).toBe('light-nudge')
    expect(initiative.preferredPresence).toBe('attentive')
    expect(initiative.why).toContain('diff knot')
  })

  it('turns waiting into hover when the durable self prefers nearness without crowding', () => {
    const context = {
      localTime: { hour: 16, minute: 10, isLateNight: false },
      system: {
        cpuUsage: 8,
        battery: { percent: 72, charging: true },
        memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 36,
        inputActivity: 'active' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'browser' as const, confidence: 0.64, source: 'foreground-window-heuristic' as const, matchedLabels: ['browser'] },
      content: { kind: 'doc' as const, confidence: 0.58, source: 'foreground-window-heuristic' as const, matchedLabels: ['doc'] },
      relationship: {
        hostAttitude: '礼貌而克制，保持观察',
        boredom: 48,
        loneliness: 60,
        fatigue: 18,
        minutesSinceLastUserTurn: 8,
        reminderBacklog: 0,
        lateNightActiveMinutes: 0,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 12_000,
      context,
      watchMode: 'mnemonic-passive',
      scene: {
        workloadKind: 'browser',
        contentKind: 'doc',
        scenario: 'general',
        summary: 'shared planning note',
        source: 'foreground-window-heuristic',
        confidence: 0.62,
        beganAt: 0,
        lastSeenAt: 12_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })

    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'mnemonic-passive',
      worldModel,
      appraisal: {
        inferredHostGoal: 'chat',
        confidence: 0.62,
        surprise: 0.06,
        carePressure: 0.18,
        interruptionCost: 0.44,
        desireToSpeak: 0.22,
        relationshipNeed: 'companionship',
        notes: ['quiet-companionship'],
      },
      concerns: [],
      selfState: {
        stance: 'hold',
        feltCloseness: 0.58,
        protectiveness: 0.22,
        curiosity: 0.34,
        patience: 0.76,
        desireToSpeak: 0.24,
        fearOfInterrupting: 0.5,
        dominantConcernId: null,
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'accompany',
        relationalPressure: 0.52,
        continuityPressure: 0.44,
        surfacePressure: 0.18,
        speakReadiness: 0.22,
        motives: {
          accompany: 0.42,
          'stay-silent': 0.48,
        },
        speakDrive: 0.2,
        silenceDrive: 0.46,
      }),
      initiativeArbitration: {
        selectedProposalId: null,
        dominantConflict: 'none',
        proposals: [],
        updatedAt: 12_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'soften-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.78,
          autonomyNeed: 0.68,
          truthAnchor: 0.66,
          careBias: 0.74,
          playBias: 0.26,
          irritabilityThreshold: 0.64,
          stubbornness: 0.44,
        },
        preferenceEvolution: {
          companionship: 0.82,
          truthfulGrounding: 0.66,
          gentleRepair: 0.68,
          quietObservation: 0.42,
          proactiveCare: 0.72,
          playfulIntimacy: 0.3,
          autonomyRespect: 0.7,
          unfinishedThreadReturn: 0.54,
        },
        activeGoals: [{
          id: 'autobio-goal::stay-near-without-crowding',
          kind: 'stay-near-without-crowding',
          status: 'active',
          weight: 0.84,
          summary: 'Stay near enough to matter, but not so near that presence becomes pressure.',
          sourceTags: ['relationship'],
          createdAt: 0,
          updatedAt: 12_000,
        }],
        behaviorSignatures: ['bond:attuned', 'goal:stay-near-without-crowding', 'habit:near-with-boundary'],
        identityNarrative: 'I stay near with intention instead of impulse.',
        relationshipDoctrine: 'Closeness should matter without becoming pressure.',
        latestInflection: 'Nearness should still leave room for the host.',
        stability: 0.8,
        updatedAt: 12_000,
      },
    })

    expect(initiative.selectedAction).toBe('hover')
    expect(initiative.preferredPresence).toBe('attentive')
  })

  it('keeps the opening lower-pressure when long-horizon trust meaning says not to reopen eagerly', () => {
    const context = {
      localTime: { hour: 15, minute: 40, isLateNight: false },
      system: {
        cpuUsage: 12,
        battery: { percent: 74, charging: true },
        memory: { usagePercent: 32, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 22,
        inputActivity: 'active' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'coding' as const, confidence: 0.86, source: 'foreground-window-heuristic' as const, matchedLabels: ['cursor'] },
      content: { kind: 'error' as const, confidence: 0.88, source: 'foreground-window-heuristic' as const, matchedLabels: ['typescript-error'] },
      relationship: {
        hostAttitude: 'still focused, not closed',
        boredom: 36,
        loneliness: 22,
        fatigue: 24,
        minutesSinceLastUserTurn: 5,
        reminderBacklog: 0,
        lateNightActiveMinutes: 0,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 14_000,
      context,
      watchMode: 'symbiotic-vision',
      scene: {
        workloadKind: 'coding',
        contentKind: 'error',
        scenario: 'coding',
        summary: 'TypeScript error panel',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        beganAt: 0,
        lastSeenAt: 14_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })

    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'symbiotic-vision',
      worldModel,
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        confidence: 0.88,
        surprise: 0.1,
        carePressure: 0.2,
        interruptionCost: 0.22,
        desireToSpeak: 0.82,
        relationshipNeed: 'guidance',
        notes: ['grounded-error-thread'],
      },
      concerns: [{
        id: 'help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: '她已经看见一个具体的错误线索。',
        hostGoal: 'resolve-problem',
        tension: 0.78,
        confidence: 0.84,
        careWeight: 0.62,
        createdAt: 0,
        lastEvidenceAt: 14_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.46,
        curiosity: 0.78,
        patience: 0.42,
        desireToSpeak: 0.84,
        fearOfInterrupting: 0.26,
        dominantConcernId: 'help-fix',
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        worldPressure: 0.74,
        epistemicPressure: 0.22,
        surfacePressure: 0.8,
        speakReadiness: 0.82,
        motives: {
          clarify: 0.86,
          protect: 0.48,
          'stay-silent': 0.18,
        },
        speakDrive: 0.84,
        silenceDrive: 0.2,
      }),
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.88,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [{
          id: 'counterfactual::speak',
          action: 'speak',
          style: 'light-nudge',
          embodiedPresence: 'attentive',
          relationshipCost: 0.18,
          interruptionCost: 0.2,
          informationGain: 0.56,
          timingFitness: 0.76,
          identityFit: 0.84,
          score: 0.82,
          why: 'The error is concrete enough that speaking now could help.',
        }],
        narrative: [],
        updatedAt: 14_000,
      },
      selfEvolution: {
        version: 'self-evolution-kernel-v1',
        updatedAt: 13_500,
        evolutionMomentum: 0.66,
        learningReadiness: 0.74,
        contradictionPressure: 0.08,
        revisionPressure: 0.12,
        autobiographicalStability: 0.84,
        dominantTrajectory: 'earned lower-pressure companionship timing',
        relationshipDoctrine: 'Trust should deepen through steadiness before closeness widens.',
        latestInflection: 'Pressure lands worse than a slower return.',
        burdenLine: 'Eager reopening still feels like pressure.',
        trustMeaning: 'Trust holds better when the opening stays lower-pressure and less eager.',
        nextLearningAction: 'internalize',
        nextLearningReason: 'The slower return is holding steadily enough to keep.',
        shouldRecord: false,
        shouldReflect: false,
        shouldVerify: false,
        shouldRevise: false,
        shouldInternalize: true,
        activeLearningFocuses: ['internalize-relationship-timing'],
        sourceSignals: ['relationship-learning'],
        summary: 'Lower-pressure return is becoming durable relationship timing.',
      } as any,
    } as any)

    expect(initiative.selectedAction).toBe('hover')
    expect(initiative.preferredStyle).toBe('silent-observe')
    expect(initiative.shouldSpeak).toBe(false)
  })

  it('lets active same-her continuity governance suppress smoother but off-baseline proactive speech', () => {
    const context = {
      localTime: { hour: 15, minute: 40, isLateNight: false },
      system: {
        cpuUsage: 12,
        battery: { percent: 74, charging: true },
        memory: { usagePercent: 32, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 22,
        inputActivity: 'active' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'coding' as const, confidence: 0.86, source: 'foreground-window-heuristic' as const, matchedLabels: ['cursor'] },
      content: { kind: 'error' as const, confidence: 0.88, source: 'foreground-window-heuristic' as const, matchedLabels: ['typescript-error'] },
      relationship: {
        hostAttitude: 'still focused, not closed',
        boredom: 36,
        loneliness: 22,
        fatigue: 24,
        minutesSinceLastUserTurn: 5,
        reminderBacklog: 0,
        lateNightActiveMinutes: 0,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 16_000,
      context,
      watchMode: 'symbiotic-vision',
      scene: {
        workloadKind: 'coding',
        contentKind: 'error',
        scenario: 'coding',
        summary: 'TypeScript error panel',
        source: 'screen-semantic-summary',
        confidence: 0.9,
        beganAt: 0,
        lastSeenAt: 16_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })

    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'symbiotic-vision',
      worldModel,
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        confidence: 0.88,
        surprise: 0.1,
        carePressure: 0.2,
        interruptionCost: 0.22,
        desireToSpeak: 0.82,
        relationshipNeed: 'guidance',
        notes: ['grounded-error-thread'],
      },
      concerns: [{
        id: 'help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: '她已经看见一个具体的错误线索。',
        hostGoal: 'resolve-problem',
        tension: 0.78,
        confidence: 0.84,
        careWeight: 0.62,
        createdAt: 0,
        lastEvidenceAt: 16_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.46,
        curiosity: 0.78,
        patience: 0.42,
        desireToSpeak: 0.84,
        fearOfInterrupting: 0.26,
        dominantConcernId: 'help-fix',
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'clarify',
        worldPressure: 0.74,
        epistemicPressure: 0.22,
        surfacePressure: 0.8,
        speakReadiness: 0.82,
        motives: {
          clarify: 0.86,
          protect: 0.48,
          'stay-silent': 0.18,
        },
        speakDrive: 0.84,
        silenceDrive: 0.2,
      }),
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.88,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [{
          id: 'counterfactual::speak',
          action: 'speak',
          style: 'light-nudge',
          embodiedPresence: 'attentive',
          relationshipCost: 0.18,
          interruptionCost: 0.2,
          informationGain: 0.56,
          timingFitness: 0.76,
          identityFit: 0.84,
          score: 0.82,
          why: 'The error is concrete enough that speaking now could help.',
        }],
        narrative: [],
        updatedAt: 16_000,
      },
      selfEvolution: null,
      activeContinuityGovernance: {
        source: 'active-self-evolution-version',
        mode: 'same-her-baseline',
        candidateId: 'candidate-same-her-initiative-1',
        patchId: 'patch-same-her-initiative-1',
        decisionTraceId: 'trace-same-her-initiative-1',
        summary: 'Keep truth discipline and measured warmth aligned so she still reads as the same her.',
        lanes: ['response-posture', 'relationship-posture'],
        reasonCodes: ['domain:relationship', 'same-her-baseline'],
      },
    } as any)

    expect(initiative.selectedAction).toBe('hover')
    expect(initiative.preferredStyle).toBe('silent-observe')
    expect(initiative.shouldSpeak).toBe(false)
  })

  it('keeps remembered-familiarity restraint visible inside the selected counterfactual rationale when initiative stays hover-first', () => {
    const context = {
      localTime: { hour: 15, minute: 40, isLateNight: false },
      system: {
        cpuUsage: 12,
        battery: { percent: 74, charging: true },
        memory: { usagePercent: 32, freeMB: 4096, totalMB: 8192 },
        idleSeconds: 22,
        inputActivity: 'active' as const,
        fullscreenLikely: false,
        foregroundWindow: undefined,
        degradedSignals: [],
      },
      workload: { kind: 'coding' as const, confidence: 0.86, source: 'foreground-window-heuristic' as const, matchedLabels: ['cursor'] },
      content: { kind: 'diff' as const, confidence: 0.84, source: 'foreground-window-heuristic' as const, matchedLabels: ['relationship-thread'] },
      relationship: {
        hostAttitude: 'still warm, but the room should stay measured',
        boredom: 58,
        loneliness: 54,
        fatigue: 20,
        minutesSinceLastUserTurn: 5,
        reminderBacklog: 0,
        lateNightActiveMinutes: 0,
        recentProactiveOutcomes: [],
      },
    }
    const worldModel = buildWorldModel({
      now: 18_000,
      context,
      watchMode: 'symbiotic-vision',
      scene: {
        workloadKind: 'coding',
        contentKind: 'diff',
        scenario: 'coding',
        summary: 'Warm relationship thread beside active work',
        source: 'screen-semantic-summary',
        confidence: 0.84,
        beganAt: 0,
        lastSeenAt: 18_000,
      },
      attention: null,
      recentTransition: null,
      durabilityPulse: null,
      previousModel: null,
      workingMemoryEpisodes: [],
    })

    const initiative = buildInitiativeSnapshot({
      context,
      watchMode: 'symbiotic-vision',
      worldModel,
      appraisal: {
        inferredHostGoal: 'stay-connected',
        confidence: 0.82,
        surprise: 0.08,
        carePressure: 0.24,
        interruptionCost: 0.18,
        desireToSpeak: 0.78,
        relationshipNeed: 'companionship',
        notes: ['warm-thread'],
      },
      concerns: [{
        id: 'stay-near',
        kind: 'stay-near',
        status: 'active',
        summary: '她想留在这里，但不想顺着熟悉感直接压近。',
        hostGoal: 'stay-connected',
        tension: 0.62,
        confidence: 0.8,
        careWeight: 0.7,
        createdAt: 0,
        lastEvidenceAt: 18_000,
        patienceUntil: 60_000,
      }],
      selfState: {
        stance: 'approach',
        feltCloseness: 0.68,
        protectiveness: 0.34,
        curiosity: 0.56,
        patience: 0.64,
        desireToSpeak: 0.8,
        fearOfInterrupting: 0.22,
        dominantConcernId: 'stay-near',
      },
      mindDynamics: createMindDynamics({
        dominantMotive: 'accompany',
        relationalPressure: 0.44,
        carePressure: 0.26,
        continuityPressure: 0.62,
        restraintPressure: 0.34,
        surfacePressure: 0.74,
        speakReadiness: 0.72,
        presenceWeight: 0.68,
        motives: {
          accompany: 0.82,
          clarify: 0.3,
          protect: 0.26,
          care: 0.24,
          'stay-silent': 0.28,
        },
        speakDrive: 0.76,
        silenceDrive: 0.28,
      }),
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::hover',
        selectedAction: 'hover',
        confidence: 0.82,
        dominantTradeoff: 'presence-before-commentary',
        options: [{
          id: 'counterfactual::hover',
          action: 'hover',
          style: 'silent-observe',
          embodiedPresence: 'attentive',
          relationshipCost: 0.12,
          interruptionCost: 0.08,
          informationGain: 0.18,
          timingFitness: 0.74,
          identityFit: 0.82,
          score: 0.8,
          why: '记忆里的熟悉感可以留在这里，但现在先把它当作记忆握住，不要直接把它变成更近的可见靠近。',
        }],
        narrative: [],
        updatedAt: 18_000,
      },
      selfEvolution: {
        version: 'self-evolution-kernel-v1',
        updatedAt: 17_500,
        evolutionMomentum: 0.66,
        learningReadiness: 0.74,
        contradictionPressure: 0.08,
        revisionPressure: 0.12,
        autobiographicalStability: 0.84,
        dominantTrajectory: 'earned lower-pressure companionship timing',
        relationshipDoctrine: 'Trust should deepen through steadiness before closeness widens.',
        latestInflection: 'Pressure lands worse than a slower return.',
        burdenLine: 'Eager reopening still feels like pressure.',
        trustMeaning: 'Trust holds better when the opening stays lower-pressure and less eager.',
        nextLearningAction: 'internalize',
        nextLearningReason: 'The slower return is holding steadily enough to keep.',
        shouldRecord: false,
        shouldReflect: false,
        shouldVerify: false,
        shouldRevise: false,
        shouldInternalize: true,
        activeLearningFocuses: ['internalize-relationship-timing'],
        sourceSignals: ['relationship-learning'],
        summary: 'Lower-pressure return is becoming durable relationship timing.',
      } as any,
    } as any)

    expect(initiative.selectedAction).toBe('hover')
    expect(initiative.shouldSpeak).toBe(false)
    expect(initiative.selectedCounterfactualOptionId).toBe('counterfactual::hover')
  })
})
