import { describe, expect, it } from 'vitest'

import { buildInitiativeArbitration } from './initiative-arbiter'

describe('buildInitiativeArbitration', () => {
  it('prefers repair over surface speech when only imagined world is available', () => {
    const arbitration = buildInitiativeArbitration({
      now: 10_000,
      context: {
        localTime: { hour: 14, minute: 0, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 10,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.82, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'unknown', confidence: 0.4, source: 'foreground-window-heuristic', matchedLabels: [] },
        relationship: {
          hostAttitude: 'still focused',
          boredom: 10,
          loneliness: 12,
          fatigue: 24,
          minutesSinceLastUserTurn: 2,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['Need one more grounding pass.'],
          staleRisks: ['scene-not-grounded'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'imagined',
        truthPriority: ['imagined'],
        live: null,
        remembered: null,
        imagined: {
          kind: 'imagined',
          summary: 'The host may be inspecting a risky diff, but it is not grounded yet.',
          confidence: 0.66,
          stability: 0.4,
          focusHypothesisId: 'hypothesis::diff',
          evidence: ['hypothesis:problem-locus/active'],
        },
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'hesitate',
        feltCloseness: 0.42,
        protectiveness: 0.32,
        curiosity: 0.68,
        patience: 0.52,
        desireToSpeak: 0.58,
        fearOfInterrupting: 0.54,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.42,
        epistemicPressure: 0.84,
        relationalPressure: 0.2,
        carePressure: 0.18,
        continuityPressure: 0.34,
        restraintPressure: 0.54,
        surfacePressure: 0.36,
        speakReadiness: 0.32,
        presenceWeight: 0.48,
        motives: {
          'clarify': 0.88,
          'stay-silent': 0.4,
        },
        speakDrive: 0.34,
        silenceDrive: 0.62,
        narrative: [],
        updatedAt: 10_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::repair',
        commitments: [{
          id: 'commitment::repair',
          kind: 'repair-misread',
          status: 'active',
          title: 'Repair misread',
          summary: 'Repair the gap between carried continuity and the live screen before speaking.',
          source: 'hypothesis',
          priority: 0.82,
          confidence: 0.8,
          targetHypothesisId: 'hypothesis::diff',
          targetRuntimeThreadId: null,
          targetBeliefId: null,
          createdAt: 0,
          lastRenewedAt: 10_000,
          patienceUntil: 20_000,
          expiresAt: 40_000,
        }],
        carryPressure: 0.82,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(arbitration.selectedProposalId).toBeTruthy()
    expect(arbitration.proposals[0]?.action).toBe('recheck')
    expect(arbitration.proposals[0]?.truthFrame).toBe('imagined')
  })

  it('lets a live afterglow companionship proposal outrank pure waiting', () => {
    const arbitration = buildInitiativeArbitration({
      now: 10_000,
      context: {
        localTime: { hour: 23, minute: 50, isLateNight: true },
        system: {
          cpuUsage: 8,
          battery: { percent: 55, charging: false },
          memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 55,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'browser', confidence: 0.7, source: 'foreground-window-heuristic', matchedLabels: ['browser'] },
        content: { kind: 'doc', confidence: 0.64, source: 'foreground-window-heuristic', matchedLabels: ['doc'] },
        relationship: {
          hostAttitude: 'calmer',
          boredom: 30,
          loneliness: 42,
          fatigue: 60,
          minutesSinceLastUserTurn: 18,
          reminderBacklog: 0,
          lateNightActiveMinutes: 150,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::afterglow',
          kind: 'co-viewing',
          status: 'active',
          source: 'observed-scene',
          title: 'music page',
          summary: 'The host has just come out of a long shared media flow.',
          confidence: 0.72,
          significance: 0.7,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 10_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: ['music page'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 1_000,
          attentionAgeMs: 1_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The host has just come out of a long shared media flow.',
          confidence: 0.72,
          stability: 0.74,
          focusThreadId: 'thread::afterglow',
          evidence: ['source:observed-scene'],
        },
        remembered: {
          kind: 'remembered',
          summary: 'The previous shared media thread still has warmth.',
          confidence: 0.62,
          stability: 0.68,
          focusThreadId: 'thread::afterglow',
          evidence: ['continuity:afterglow-open'],
        },
        imagined: null,
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.62,
        protectiveness: 0.36,
        curiosity: 0.44,
        patience: 0.64,
        desireToSpeak: 0.7,
        fearOfInterrupting: 0.22,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.42,
        epistemicPressure: 0.2,
        relationalPressure: 0.68,
        carePressure: 0.52,
        continuityPressure: 0.74,
        restraintPressure: 0.3,
        surfacePressure: 0.58,
        speakReadiness: 0.72,
        presenceWeight: 0.7,
        motives: {
          accompany: 0.82,
          care: 0.54,
        },
        speakDrive: 0.66,
        silenceDrive: 0.28,
        narrative: [],
        updatedAt: 10_000,
      },
      thoughtThreads: {
        foregroundThreadId: 'thought::afterglow',
        threads: [{
          id: 'thought::afterglow',
          kind: 'afterglow-thread',
          status: 'ripe',
          title: 'afterglow',
          summary: 'The seam right after shared media is natural for a soft check-in.',
          salience: 0.72,
          confidence: 0.74,
          surfaceReadiness: 0.82,
          anchoredObjectId: null,
          anchoredIntentionId: null,
          reopenWhen: [],
          openedAt: 0,
          lastUpdatedAt: 10_000,
          expiresAt: 20_000,
        }],
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(['whisper', 'speak']).toContain(arbitration.proposals[0]?.action)
    expect(arbitration.proposals[0]?.score ?? 0).toBeGreaterThan(0.4)
  })
})
