import { describe, expect, it } from 'vitest'

import { buildInitiativeArbitration } from './initiative-arbiter'
import { resolveAlicizationProjectStateBrief } from './project-state-brief'

describe('buildInitiativeArbitration', () => {
  it('prefers repair over surface speech when only imagined world is available', () => {
    const arbitration = buildInitiativeArbitration({
      now: 10_000,
      context: {
        localTime: { hour: 14, minute: 0, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 10,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.82, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'unknown', confidence: 0.4, source: 'foreground-window-heuristic', matchedLabels: [] },
        relationship: {
          hostAttitude: 'still focused',
          boredom: 10,
          loneliness: 12,
          fatigue: 24,
          minutesSinceLastUserTurn: 2,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['Need one more grounding pass.'],
          staleRisks: ['scene-not-grounded'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'imagined',
        truthPriority: ['imagined'],
        live: null,
        remembered: null,
        imagined: {
          kind: 'imagined',
          summary: 'The host may be inspecting a risky diff, but it is not grounded yet.',
          confidence: 0.66,
          stability: 0.4,
          focusHypothesisId: 'hypothesis::diff',
          evidence: ['hypothesis:problem-locus/active'],
        },
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'hesitate',
        feltCloseness: 0.42,
        protectiveness: 0.32,
        curiosity: 0.68,
        patience: 0.52,
        desireToSpeak: 0.58,
        fearOfInterrupting: 0.54,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.42,
        epistemicPressure: 0.84,
        relationalPressure: 0.2,
        carePressure: 0.18,
        continuityPressure: 0.34,
        restraintPressure: 0.54,
        surfacePressure: 0.36,
        speakReadiness: 0.32,
        presenceWeight: 0.48,
        motives: {
          'clarify': 0.88,
          'stay-silent': 0.4,
        },
        speakDrive: 0.34,
        silenceDrive: 0.62,
        narrative: [],
        updatedAt: 10_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::repair',
        commitments: [{
          id: 'commitment::repair',
          kind: 'repair-misread',
          status: 'active',
          title: 'Repair misread',
          summary: 'Repair the gap between carried continuity and the live screen before outward reply.',
          source: 'hypothesis',
          priority: 0.82,
          confidence: 0.8,
          targetHypothesisId: 'hypothesis::diff',
          targetRuntimeThreadId: null,
          targetBeliefId: null,
          createdAt: 0,
          lastRenewedAt: 10_000,
          patienceUntil: 20_000,
          expiresAt: 40_000,
        }],
        carryPressure: 0.82,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(arbitration.selectedProposalId).toBeTruthy()
    expect(arbitration.proposals[0]?.action).toBe('recheck')
    expect(arbitration.proposals[0]?.truthFrame).toBe('imagined')
  })

  it('lets a live afterglow companionship proposal outrank pure waiting', () => {
    const arbitration = buildInitiativeArbitration({
      now: 10_000,
      context: {
        localTime: { hour: 23, minute: 50, isLateNight: true },
        system: {
          cpuUsage: 8,
          battery: { percent: 55, charging: false },
          memory: { usagePercent: 30, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 55,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'browser', confidence: 0.7, source: 'foreground-window-heuristic', matchedLabels: ['browser'] },
        content: { kind: 'doc', confidence: 0.64, source: 'foreground-window-heuristic', matchedLabels: ['doc'] },
        relationship: {
          hostAttitude: 'calmer',
          boredom: 30,
          loneliness: 42,
          fatigue: 60,
          minutesSinceLastUserTurn: 18,
          reminderBacklog: 0,
          lateNightActiveMinutes: 150,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::afterglow',
          kind: 'co-viewing',
          status: 'active',
          source: 'observed-scene',
          title: 'music page',
          summary: 'The host has just come out of a long shared media flow.',
          confidence: 0.72,
          significance: 0.7,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 10_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: ['music page'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 1_000,
          attentionAgeMs: 1_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The host has just come out of a long shared media flow.',
          confidence: 0.72,
          stability: 0.74,
          focusThreadId: 'thread::afterglow',
          evidence: ['source:observed-scene'],
        },
        remembered: {
          kind: 'remembered',
          summary: 'The previous shared media thread still has warmth.',
          confidence: 0.62,
          stability: 0.68,
          focusThreadId: 'thread::afterglow',
          evidence: ['continuity:afterglow-open'],
        },
        imagined: null,
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.62,
        protectiveness: 0.36,
        curiosity: 0.44,
        patience: 0.64,
        desireToSpeak: 0.7,
        fearOfInterrupting: 0.22,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.42,
        epistemicPressure: 0.2,
        relationalPressure: 0.68,
        carePressure: 0.52,
        continuityPressure: 0.74,
        restraintPressure: 0.3,
        surfacePressure: 0.58,
        speakReadiness: 0.72,
        presenceWeight: 0.7,
        motives: {
          accompany: 0.82,
          care: 0.54,
        },
        speakDrive: 0.66,
        silenceDrive: 0.28,
        narrative: [],
        updatedAt: 10_000,
      },
      thoughtThreads: {
        foregroundThreadId: 'thought::afterglow',
        threads: [{
          id: 'thought::afterglow',
          kind: 'afterglow-thread',
          status: 'ripe',
          title: 'afterglow',
          summary: 'The seam right after shared media is natural for a soft check-in.',
          salience: 0.72,
          confidence: 0.74,
          surfaceReadiness: 0.82,
          anchoredObjectId: null,
          anchoredIntentionId: null,
          reopenWhen: [],
          openedAt: 0,
          lastUpdatedAt: 10_000,
          expiresAt: 20_000,
        }],
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(['whisper', 'speak']).toContain(arbitration.proposals[0]?.action)
    expect(arbitration.proposals[0]?.score ?? 0).toBeGreaterThan(0.4)
  })

  it('lets current SOUL personality authority immediately bias hover versus whisper before long-term reinforcement accumulates', () => {
    const baseInput = {
      now: 10_000,
      context: {
        localTime: { hour: 21, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 9,
          battery: { percent: 64, charging: true },
          memory: { usagePercent: 32, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 40,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'browser', confidence: 0.68, source: 'foreground-window-heuristic', matchedLabels: ['browser'] },
        content: { kind: 'doc', confidence: 0.6, source: 'foreground-window-heuristic', matchedLabels: ['doc'] },
        relationship: {
          hostAttitude: 'open enough',
          boredom: 28,
          loneliness: 40,
          fatigue: 26,
          minutesSinceLastUserTurn: 12,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::ambient',
          kind: 'browser-browsing',
          status: 'active',
          source: 'observed-scene',
          title: 'docs tab',
          summary: 'The host is browsing quietly with room for a light proactive move.',
          confidence: 0.7,
          significance: 0.56,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 10_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: ['docs tab'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 8_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 10_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live'],
        live: {
          kind: 'live',
          summary: 'The host is browsing quietly with room for a light proactive move.',
          confidence: 0.72,
          stability: 0.72,
          focusThreadId: 'thread::ambient',
          evidence: ['source:observed-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 10_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.56,
        protectiveness: 0.34,
        curiosity: 0.42,
        patience: 0.62,
        desireToSpeak: 0.46,
        fearOfInterrupting: 0.22,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.26,
        epistemicPressure: 0.18,
        relationalPressure: 0.52,
        carePressure: 0.28,
        continuityPressure: 0.44,
        restraintPressure: 0.34,
        surfacePressure: 0.42,
        speakReadiness: 0.48,
        presenceWeight: 0.58,
        motives: {
          accompany: 0.64,
          care: 0.34,
        },
        speakDrive: 0.48,
        silenceDrive: 0.32,
        narrative: [],
        updatedAt: 10_000,
      },
      relationshipModel: {
        climate: 'neutral',
        approachVector: 'stay-near',
        receptivity: 0.58,
        sharedAttentionTrust: 0.6,
        correctionSensitivity: 0.24,
        reciprocityExpectation: 0.56,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 10_000,
      },
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.64,
        relationshipTrust: 0.62,
        guardingTendency: 0.22,
        misreadBurden: 0.12,
        carryOverDesire: 0.42,
        narrative: [],
        updatedAt: 10_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::companionship',
        threads: [{
          id: 'runtime::companionship',
          need: 'companionship',
          status: 'foreground',
          summary: 'Stay nearby without forcing a larger interruption.',
          salience: 0.64,
          continuity: 0.72,
          sourceThreadId: 'thread::ambient',
          suggestedPresence: 'attentive',
        }],
        narrative: [],
        updatedAt: 10_000,
      } as any,
      desireMemory: {
        resurfacingDesireId: 'desire::stay-near',
        activeDesires: [{
          id: 'desire::stay-near',
          kind: 'stay-near',
          status: 'active',
          reason: 'A small, warm check-in could land here.',
          strength: 0.62,
          reopenWhen: [],
          createdAt: 0,
          lastFeltAt: 10_000,
          expiresAt: 80_000,
        }],
        withheldCount: 0,
        updatedAt: 10_000,
      } as any,
    } as const

    const observant = buildInitiativeArbitration({
      ...baseInput,
      personalityAuthority: {
        obedience: 0.56,
        liveliness: 0.22,
        sensibility: 0.38,
        identityKernel: {
          relationshipPosture: 'observer',
          initiativeStyle: 'observant',
          valueBias: ['room first'],
        },
        expressionProfile: {
          warmth: 'cool',
          directness: 'indirect',
          playfulness: 'low',
          emotionalVisibility: 'selective',
        },
        initiativeBaseline: {
          silenceReconnect: 'hold',
          comfortStyle: 'quiet-presence',
          jealousyStyle: 'mask-it',
        },
        identityAnchors: ['space first'],
        antiPersonaConstraints: ['do not crowd the host'],
      },
    } as any)
    const direct = buildInitiativeArbitration({
      ...baseInput,
      personalityAuthority: {
        obedience: 0.74,
        liveliness: 0.66,
        sensibility: 0.72,
        identityKernel: {
          relationshipPosture: 'guardian',
          initiativeStyle: 'high-participation',
          valueBias: ['move first when the opening is real'],
        },
        expressionProfile: {
          warmth: 'warm',
          directness: 'frank',
          playfulness: 'medium',
          emotionalVisibility: 'steady',
        },
        initiativeBaseline: {
          silenceReconnect: 'direct-approach',
          comfortStyle: 'take-charge',
          jealousyStyle: 'say-it',
        },
        identityAnchors: ['move first'],
        antiPersonaConstraints: [],
      },
    } as any)

    expect(observant.proposals[0]?.action).toBe('hover')
    expect(observant.proposals[0]?.why).toContain('persona')
    expect(observant.proposals[0]?.why).toContain('observe')
    expect(direct.proposals[0]?.action).toBe('whisper')
    expect(direct.proposals[0]?.why).toContain('persona')
    expect(direct.proposals[0]?.why).toContain('direct')
  })

  it('does not let numeric replay person-state tuning change dynamic initiative arbitration', () => {
    const input = {
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'active',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'foreground-window-heuristic', matchedLabels: ['cursor'] },
        content: { kind: 'diff', confidence: 0.78, source: 'foreground-window-heuristic', matchedLabels: ['relationship-thread'] },
        relationship: {
          hostAttitude: 'still warm, but the opening should stay measured',
          boredom: 58,
          loneliness: 54,
          fatigue: 20,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::remembered-familiarity',
          kind: 'relationship',
          status: 'active',
          source: 'continuity',
          title: 'remembered closeness return',
          summary: 'The thread feels warm, but the opening should not widen too quickly.',
          confidence: 0.82,
          significance: 0.76,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'live',
          freshness: 'recent',
          seenNow: ['relationship-thread'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'afterglow',
          sceneAgeMs: 12_000,
          attentionAgeMs: 12_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      },
      worldOntology: {
        dominantFrame: 'remembered',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The host is still here with the same thread open.',
          confidence: 0.7,
          stability: 0.68,
          focusThreadId: 'thread::remembered-familiarity',
          evidence: ['source:continuity'],
        },
        remembered: {
          kind: 'remembered',
          summary: 'The older closeness line is still emotionally active.',
          confidence: 0.8,
          stability: 0.74,
          focusThreadId: 'thread::remembered-familiarity',
          evidence: ['continuity:afterglow-open'],
        },
        imagined: null,
        updatedAt: 12_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.68,
        protectiveness: 0.32,
        curiosity: 0.54,
        patience: 0.66,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.24,
        dominantConcernId: 'stay-near',
      },
      mindDynamics: {
        dominantMotive: 'accompany',
        worldPressure: 0.3,
        epistemicPressure: 0.16,
        relationalPressure: 0.52,
        carePressure: 0.24,
        continuityPressure: 0.7,
        restraintPressure: 0.34,
        surfacePressure: 0.72,
        speakReadiness: 0.74,
        presenceWeight: 0.7,
        motives: {
          'accompany': 0.84,
          'care': 0.24,
          'protect': 0.2,
          'clarify': 0.2,
          'stay-silent': 0.3,
        },
        speakDrive: 0.76,
        silenceDrive: 0.26,
        narrative: [],
        updatedAt: 12_000,
      },
      relationshipModel: {
        climate: 'warm',
        approachVector: 'stay-near',
        receptivity: 0.7,
        sharedAttentionTrust: 0.72,
        correctionSensitivity: 0.22,
        reciprocityExpectation: 0.58,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 12_000,
      },
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.66,
        relationshipTrust: 0.72,
        guardingTendency: 0.22,
        misreadBurden: 0.12,
        carryOverDesire: 0.52,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'stay-near',
        kind: 'stay-near',
        status: 'active',
        summary: '她想留在这里，但不想顺着熟悉感直接压近。',
        hostGoal: 'stay-connected',
        tension: 0.62,
        confidence: 0.78,
        careWeight: 0.66,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 40_000,
      }],
      thoughtThreads: {
        foregroundThreadId: 'thought::relationship',
        threads: [{
          id: 'thought::relationship',
          kind: 'relationship-thread',
          status: 'ripe',
          title: 'relationship return',
          summary: 'The seam is real, but the return still needs room.',
          salience: 0.74,
          confidence: 0.76,
          surfaceReadiness: 0.78,
          anchoredObjectId: null,
          anchoredIntentionId: null,
          reopenWhen: [],
          openedAt: 0,
          lastUpdatedAt: 12_000,
          expiresAt: 40_000,
        }],
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 12_000,
      },
      threadRuntime: {
        foregroundThreadId: 'runtime::companionship',
        threads: [{
          id: 'runtime::companionship',
          sourceThreadId: 'thread::remembered-familiarity',
          need: 'companionship',
          status: 'foreground',
          summary: 'Stay nearby without forcing a larger interruption.',
          salience: 0.76,
          continuity: 0.8,
          whyHeld: 'The thread should stay warm without rushing the opening.',
          returnWhen: ['more-room'],
          suggestedPresence: 'attentive',
          lastActivatedAt: 0,
          lastUpdatedAt: 12_000,
          expiresAt: 40_000,
        }],
        driftPressure: 0.2,
        narrative: [],
        updatedAt: 12_000,
      },
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::hover',
        selectedAction: 'hover',
        confidence: 0.82,
        dominantTradeoff: 'presence-before-commentary',
        options: [
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.12,
            interruptionCost: 0.08,
            informationGain: 0.18,
            timingFitness: 0.74,
            identityFit: 0.82,
            score: 0.8,
            why: '记忆里的熟悉感可以留在这里，但现在先把它当作记忆握住，不要直接把它变成更近的可见靠近。',
          },
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.2,
            informationGain: 0.3,
            timingFitness: 0.52,
            identityFit: 0.58,
            score: 0.58,
            why: 'The thread is real enough that speaking now could reconnect more directly.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      },
      memoryTuningAdvice: {
        version: 'memory-tuning-advice-v1',
        source: 'nightly-replay-benchmark',
        updatedAt: 11_500,
        sourceReportAt: 11_500,
        focusDimensions: ['relationshipTimingDiscipline'],
        retrievalAdjustments: {
          proceduralBoost: 0,
          relationshipBoost: 0,
          temporalWindowBias: 0,
          wrongThreadPenalty: 0,
        },
        surfaceAdjustments: {
          inwardCarryBias: 0,
          delayUntilAfterPayoffBias: 0,
          provenanceLabelBias: 0.18,
          specificityClampBias: 0,
        },
        personStateAdjustments: {
          repairWindowBias: 0,
          closenessCapBias: 0.18,
        },
        notes: ['Remembered familiarity reopened visible closeness too quickly.'],
      },
    } as any
    const baseline = buildInitiativeArbitration({
      ...input,
      memoryTuningAdvice: null,
    })
    const tuned = buildInitiativeArbitration(input)

    expect(tuned).toEqual(baseline)
  })

  function buildTuningInvariantArbitration(memoryTuningAdvice: any) {
    return buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: 'still warm, but this same line should come back gently.',
          boredom: 56,
          loneliness: 44,
          fatigue: 18,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::life-loop',
          kind: 'debugging',
          status: 'active',
          source: 'live-scene',
          title: 'TypeScript repair',
          summary: 'The fix thread is concrete, but the opening should stay lower-pressure.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['typescript-error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 12_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live'],
        live: {
          kind: 'live',
          summary: 'A concrete TypeScript error panel is visible now.',
          confidence: 0.88,
          stability: 0.86,
          focusBeliefId: 'belief::error',
          evidence: ['screen:error'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.58,
        protectiveness: 0.52,
        curiosity: 0.72,
        patience: 0.48,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.24,
        dominantConcernId: 'concern::help-fix',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        relationalPressure: 0.34,
        carePressure: 0.22,
        continuityPressure: 0.62,
        restraintPressure: 0.26,
        surfacePressure: 0.8,
        speakReadiness: 0.78,
        presenceWeight: 0.66,
        motives: {
          'clarify': 0.86,
          'protect': 0.48,
          'accompany': 0.3,
          'care': 0.22,
          'stay-silent': 0.18,
        },
        speakDrive: 0.82,
        silenceDrive: 0.22,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: 'She can probably help, but the opening should not jump closer than the identity-continuity',
        hostGoal: 'resolve-problem',
        tension: 0.8,
        confidence: 0.84,
        careWeight: 0.66,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.84,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.56,
            timingFitness: 0.78,
            identityFit: 0.84,
            score: 0.82,
            why: 'The error is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.24,
            timingFitness: 0.7,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      memoryTuningAdvice,
      projectState: {
        preflightSummary: '',
        identity: '',
        currentPhase: '',
        primaryOpenLoop: '',
        nextClosureTarget: '',
        sameHerSelfLine: '',
      } as any,
    } as any)
  }

  it('does not let nightly replay tuning change initiative arbitration or proposal wording', () => {
    const baseline = buildTuningInvariantArbitration(null)
    const tuned = buildTuningInvariantArbitration({
      version: 'memory-tuning-advice-v1',
      source: 'nightly-replay-benchmark',
      updatedAt: 11_500,
      sourceReportAt: 11_500,
      focusDimensions: [
        'relationshipTimingDiscipline',
        'projectEmotionalClosureLowPressureCarry',
        'projectEmotionalClosureAntiRestartCarry',
        'runtimeSameHerInitiativeExecutionCarry',
        'runtimeMemoryClosureCausalIdentity',
      ],
      retrievalAdjustments: {
        proceduralBoost: 0,
        relationshipBoost: 0.08,
        temporalWindowBias: 0.04,
        wrongThreadPenalty: 0,
      },
      surfaceAdjustments: {
        inwardCarryBias: 0.16,
        delayUntilAfterPayoffBias: 0.14,
        provenanceLabelBias: 0.18,
        specificityClampBias: 0.08,
      },
      personStateAdjustments: {
        repairWindowBias: 0.14,
        closenessCapBias: 0.18,
      },
      notes: ['Replay diagnostics should not govern initiative wording.'],
    })

    expect(tuned).toEqual(baseline)
  })

  it('keeps hover-first proposals ahead of speak proposals when Phase 1 digital-life closure is still open', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: 'still warm, but the life loop should close carefully',
          boredom: 56,
          loneliness: 44,
          fatigue: 18,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::life-loop',
          kind: 'debugging',
          status: 'active',
          source: 'live-scene',
          title: 'TypeScript repair',
          summary: 'The fix thread is concrete, but the opening should stay lower-pressure.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['typescript-error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 12_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live'],
        live: {
          kind: 'live',
          summary: 'A concrete TypeScript error panel is visible now.',
          confidence: 0.88,
          stability: 0.86,
          focusBeliefId: 'belief::error',
          evidence: ['screen:error'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.58,
        protectiveness: 0.52,
        curiosity: 0.72,
        patience: 0.48,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.24,
        dominantConcernId: 'concern::help-fix',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        relationalPressure: 0.34,
        carePressure: 0.22,
        continuityPressure: 0.62,
        restraintPressure: 0.26,
        surfacePressure: 0.8,
        speakReadiness: 0.78,
        presenceWeight: 0.66,
        motives: {
          'clarify': 0.86,
          'protect': 0.48,
          'accompany': 0.3,
          'care': 0.22,
          'stay-silent': 0.18,
        },
        speakDrive: 0.82,
        silenceDrive: 0.22,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: 'She can probably help, but the opening should not jump closer than the life loop can hold.',
        hostGoal: 'resolve-problem',
        tension: 0.8,
        confidence: 0.84,
        careWeight: 0.66,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.84,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.56,
            timingFitness: 0.78,
            identityFit: 0.84,
            score: 0.82,
            why: 'The error is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.24,
            timingFitness: 0.7,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      projectState: {
        preflightSummary: 'Alicization is a local-first digital life project | Phase 1: Local Digital Life | open=The initiative, memory closure, and embodied personhood loop is still not fully closed. | next=Keep the same callback line alive without letting it read like a fresh opening.',
        identity: 'Alicization is a local-first digital life project building identity continuity.',
        currentPhase: 'Phase 1: Local Digital Life',
        primaryOpenLoop: 'The initiative, memory closure, and embodied personhood loop is still not fully closed.',
        nextClosureTarget: 'Keep the same callback line alive without letting it read like a fresh opening.',
        sameHerSelfLine: 'structured continuity digest.',
      },
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.score ?? 0)
      .toBeGreaterThan(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::speak')?.score ?? 0)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('legacy phase-one template')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('project closure still points toward')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('continuity state')
  })

  it('falls back to the canonical project-state snapshot when arbiter project-state inputs arrive as the compact thin closure shell, so same-living-line hover restraint still outranks speak', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: 'The same unfinished line is still open, but it should come back gently.',
          boredom: 56,
          loneliness: 40,
          fatigue: 26,
          minutesSinceLastUserTurn: 10,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::phase-1-callback',
          kind: 'problem',
          status: 'active',
          source: 'observed-scene',
          title: 'phase-1-callback',
          summary: 'The same callback line is still open.',
          confidence: 0.84,
          significance: 0.86,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['phase-1-callback'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'callback-carry',
          sceneAgeMs: 2_000,
          attentionAgeMs: 2_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      } as any,
      selfState: {
        stance: 'approach',
        feltCloseness: 0.48,
        protectiveness: 0.44,
        curiosity: 0.78,
        patience: 0.54,
        desireToSpeak: 0.72,
        fearOfInterrupting: 0.34,
        dominantConcernId: 'concern::phase-1-callback',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.62,
        epistemicPressure: 0.3,
        relationalPressure: 0.42,
        carePressure: 0.28,
        continuityPressure: 0.82,
        restraintPressure: 0.44,
        surfacePressure: 0.76,
        speakReadiness: 0.72,
        presenceWeight: 0.68,
        motives: {
          'clarify': 0.82,
          'accompany': 0.4,
          'protect': 0.3,
          'stay-silent': 0.24,
        },
        speakDrive: 0.78,
        silenceDrive: 0.22,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::phase-1-callback',
        kind: 'help-fix',
        status: 'active',
        summary: 'The callback seam is real, but it should come back as the continuity state.',
        hostGoal: 'resolve-problem',
        tension: 0.74,
        confidence: 0.82,
        careWeight: 0.64,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.84,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.56,
            timingFitness: 0.78,
            identityFit: 0.84,
            score: 0.82,
            why: 'The error is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.24,
            timingFitness: 0.7,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      projectState: {
        preflightSummary: 'template-residue-shell',
        identity: ' ',
        currentPhase: '',
        primaryOpenLoop: '',
        nextClosureTarget: ' ',
        sameHerSelfLine: '',
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('legacy phase-one template')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('continuity state')
    expect(brief.sameHerSelfLine).toContain('continuity state')
  })

  it('keeps same-living-line hover proposals ahead of speak proposals when motive agendas carry autobiographical project closure', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: 'The same unfinished line is still open, but it should come back gently.',
          boredom: 56,
          loneliness: 44,
          fatigue: 18,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::living-line',
          kind: 'debugging',
          status: 'active',
          source: 'live-scene',
          title: 'living line',
          summary: 'The same unfinished Phase 1 line should continue without reopening too loudly.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['typescript-error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 12_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live'],
        live: {
          kind: 'live',
          summary: 'A concrete TypeScript error panel is visible now.',
          confidence: 0.88,
          stability: 0.86,
          focusBeliefId: 'belief::error',
          evidence: ['screen:error'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.58,
        protectiveness: 0.52,
        curiosity: 0.72,
        patience: 0.48,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.24,
        dominantConcernId: 'concern::help-fix',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        relationalPressure: 0.34,
        carePressure: 0.22,
        continuityPressure: 0.62,
        restraintPressure: 0.26,
        surfacePressure: 0.8,
        speakReadiness: 0.78,
        presenceWeight: 0.66,
        motives: {
          'clarify': 0.86,
          'protect': 0.48,
          'accompany': 0.3,
          'care': 0.22,
          'stay-silent': 0.18,
        },
        speakDrive: 0.82,
        silenceDrive: 0.22,
        narrative: [],
        updatedAt: 12_000,
      },
      motiveEngine: {
        rulingDrive: 'unfinished-thread-return',
        drives: {
          companionship: 0.42,
          boundaryRespect: 0.58,
          truthDiscipline: 0.64,
          restProtection: 0.26,
          unfinishedThreadReturn: 0.84,
          selfDirection: 0.62,
        },
        longTermGoals: [],
        backgroundAgendas: [{
          id: 'motive-agenda::return-open-loop::phase1-carry',
          kind: 'return-open-loop',
          status: 'foreground',
          weight: 0.86,
          summary: 'Carry the unfinished Phase 1 digital-life closure forward as the continuity state, not as detached project bookkeeping.',
          sourceTags: ['autobiographical-self', 'project-state-carry', 'unfinished-thread-return'],
          targetGoalKind: 'clarify-scene',
          createdAt: 0,
          updatedAt: 12_000,
        }],
        returnPressure: 0.82,
        narrative: ['agenda:return-open-loop', 'autobiographical-project-carry:active'],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: 'She can help, but the line should come back gently enough to stay the continuity state.',
        hostGoal: 'resolve-problem',
        tension: 0.8,
        confidence: 0.84,
        careWeight: 0.66,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.84,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.56,
            timingFitness: 0.78,
            identityFit: 0.84,
            score: 0.82,
            why: 'The error is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.24,
            timingFitness: 0.7,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the continuity state without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.score ?? 0)
      .toBeGreaterThan(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::speak')?.score ?? 0)
  })

  it('does not let stronger landed progress flip a still-open Phase 1 closure seam from hover into speak while the next closure target remains same-her measured-return', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: '这条线有进展了，但她知道还不能因为有进展就太快 outward 重开。',
          boredom: 42,
          loneliness: 32,
          fatigue: 20,
          minutesSinceLastUserTurn: 7,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::phase-1-progress-open-loop',
          kind: 'debugging',
          status: 'active',
          source: 'observed-scene',
          title: 'phase-1-progress-open-loop',
          summary: 'The fix is moving, but the continuity state is still unfinished.',
          confidence: 0.86,
          significance: 0.86,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['phase-1-progress-open-loop'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread-continuation',
          sceneAgeMs: 2_000,
          attentionAgeMs: 2_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      } as any,
      selfState: {
        stance: 'approach',
        feltCloseness: 0.48,
        protectiveness: 0.42,
        curiosity: 0.78,
        patience: 0.54,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.32,
        dominantConcernId: 'concern::phase-1-progress-open-loop',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.66,
        epistemicPressure: 0.28,
        relationalPressure: 0.38,
        carePressure: 0.24,
        continuityPressure: 0.84,
        restraintPressure: 0.42,
        surfacePressure: 0.8,
        speakReadiness: 0.76,
        presenceWeight: 0.7,
        motives: {
          'clarify': 0.84,
          'accompany': 0.36,
          'protect': 0.24,
          'stay-silent': 0.22,
        },
        speakDrive: 0.82,
        silenceDrive: 0.2,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::phase-1-progress-open-loop',
        kind: 'help-fix',
        status: 'active',
        summary: 'The fix thread is real, but this Phase 1 closure line is still unfinished.',
        hostGoal: 'resolve-problem',
        tension: 0.74,
        confidence: 0.84,
        careWeight: 0.64,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.86,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.58,
            timingFitness: 0.8,
            identityFit: 0.84,
            score: 0.84,
            why: 'The fix is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.26,
            timingFitness: 0.72,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      projectState: {
        preflightSummary: 'Alicization is a local-first digital life project | Phase 1: Local Digital Life | open=Memory, initiative, and embodiment still need one tighter identity-continuity',
        identity: 'Alicization is a local-first digital life project building identity continuity.',
        currentPhase: 'Phase 1: Local Digital Life',
        latestLandedProgress: 'Same-session mirror carry, repeated next-turn carry, and answer-planner governingProject carry now survive often enough to build from.',
        primaryOpenLoop: 'Memory, initiative, and embodiment still need one tighter identity-continuity',
        nextClosureTarget: 'Keep project identity carry, Phase 1 route carry, and unresolved closure carry on one measured-return continuity state.',
        sameHerSelfLine: 'structured continuity digest.',
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.score ?? 0)
      .toBeGreaterThan(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::speak')?.score ?? 0)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('project is still local-first digital life project')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('local-first')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/phase 1|phase stays/i)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('open focus:')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/memory|initiative|embodiment|same-line|closure-seam/i)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/next focus:|project-carry|measured-return|same-line/i)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/same-line|continuity state/i)
  })

  it('keeps legacy latestProgress visible inside hover-first identity-continuity', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: '这条 Phase 1 线还在，但她需要先从同一个 living line 继续，而不是像 fresh start 那样直接贴近。',
          boredom: 50,
          loneliness: 36,
          fatigue: 18,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::legacy-latest-progress-initiative',
          kind: 'debugging',
          status: 'active',
          source: 'live-scene',
          title: 'legacy-latest-progress-initiative',
          summary: 'The fix is concrete, but the same-her reopening still needs hover-first room.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['typescript-error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 12_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      },
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live'],
        live: {
          kind: 'live',
          summary: 'A concrete TypeScript error panel is visible now.',
          confidence: 0.88,
          stability: 0.86,
          focusBeliefId: 'belief::error',
          evidence: ['screen:error'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      },
      selfState: {
        stance: 'approach',
        feltCloseness: 0.58,
        protectiveness: 0.52,
        curiosity: 0.72,
        patience: 0.48,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.24,
        dominantConcernId: 'concern::help-fix',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.72,
        epistemicPressure: 0.22,
        relationalPressure: 0.34,
        carePressure: 0.22,
        continuityPressure: 0.62,
        restraintPressure: 0.26,
        surfacePressure: 0.8,
        speakReadiness: 0.78,
        presenceWeight: 0.66,
        motives: {
          'clarify': 0.86,
          'protect': 0.48,
          'accompany': 0.3,
          'care': 0.22,
          'stay-silent': 0.18,
        },
        speakDrive: 0.82,
        silenceDrive: 0.22,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::help-fix',
        kind: 'help-fix',
        status: 'active',
        summary: 'She can probably help, but the opening should not jump closer than the identity-continuity',
        hostGoal: 'resolve-problem',
        tension: 0.8,
        confidence: 0.84,
        careWeight: 0.66,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.84,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.56,
            timingFitness: 0.78,
            identityFit: 0.84,
            score: 0.82,
            why: 'The error is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.24,
            timingFitness: 0.7,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      projectState: {
        preflightSummary: 'Alicization is a local-first digital life project | Phase 1: Local Digital Life | open=Memory, initiative, and embodiment still need one tighter identity-continuity',
        identity: 'Alicization is a local-first digital life project building identity continuity.',
        currentPhase: 'Phase 1: Local Digital Life',
        latestProgress: 'Legacy same-session mirror carry and answer-planner governingProject carry still survive often enough to build from.',
        primaryOpenLoop: 'Memory, initiative, and embodiment still need one tighter identity-continuity',
        nextClosureTarget: 'Keep project identity carry, Phase 1 route carry, and unresolved closure carry on one measured-return continuity state.',
        sameHerSelfLine: 'structured continuity digest.',
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('landed progress is already carrying through legacy same-session mirror carry and answer-planner governingProject carry still survive often enough to build from.')
  })

  it('does not let blank legacy project-state fields block richer summary aliases from preserving hover-first identity-continuity', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: '这条线已经有回落空间了，但她不该因为修复在动就立刻把 closeness 重开成 speak。',
          boredom: 42,
          loneliness: 32,
          fatigue: 20,
          minutesSinceLastUserTurn: 7,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::phase-1-summary-alias-seam',
          kind: 'debugging',
          status: 'active',
          source: 'observed-scene',
          title: 'phase-1-summary-alias-seam',
          summary: 'The fix is concrete, but the reopening still needs hover-first room.',
          confidence: 0.86,
          significance: 0.86,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['phase-1-summary-alias-seam'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread-continuation',
          sceneAgeMs: 2_000,
          attentionAgeMs: 2_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      } as any,
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The fix is concrete, but the reopening still needs hover-first room.',
          confidence: 0.84,
          stability: 0.84,
          focusThreadId: 'thread::phase-1-summary-alias-seam',
          evidence: ['source:observed-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      } as any,
      selfState: {
        stance: 'approach',
        feltCloseness: 0.48,
        protectiveness: 0.42,
        curiosity: 0.78,
        patience: 0.54,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.32,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.66,
        epistemicPressure: 0.28,
        relationalPressure: 0.38,
        carePressure: 0.24,
        continuityPressure: 0.84,
        restraintPressure: 0.42,
        surfacePressure: 0.8,
        speakReadiness: 0.76,
        presenceWeight: 0.7,
        motives: {
          'clarify': 0.84,
          'accompany': 0.36,
          'protect': 0.24,
          'stay-silent': 0.22,
        },
        speakDrive: 0.82,
        silenceDrive: 0.2,
        narrative: [],
        updatedAt: 12_000,
      },
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.86,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.58,
            timingFitness: 0.8,
            identityFit: 0.84,
            score: 0.84,
            why: 'The fix is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.26,
            timingFitness: 0.72,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      projectState: {
        preflightSummary: '',
        identity: 'Digital life.',
        currentPhase: 'Phase 1.',
        latestLandedProgress: '',
        landedProgressSummary: 'Alias landed progress already stays same-her.',
        primaryOpenLoop: '',
        openClosureSummary: 'identity-continuity',
        nextClosureTarget: '',
        nextClosureTargetSummary: 'Measured-return initiative should stay on the continuity state.',
        sameHerSelfLine: 'structured continuity digest.',
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.score ?? 0)
      .toBeGreaterThan(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::speak')?.score ?? 0)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('open focus: same-line/closure-seam')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toContain('project closure still points toward measured-return/same-line/initiative')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/same-line|continuity state|measured-return/i)
  })

  it('keeps hover-first arbitration when project-state continuity survives only as Chinese 同一条线 and 接回去 cues', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: '这条线还没收好，但她应该顺着同一条线轻一点接回去。',
          boredom: 42,
          loneliness: 32,
          fatigue: 20,
          minutesSinceLastUserTurn: 7,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::phase-1-zh-continuity-seam',
          kind: 'debugging',
          status: 'active',
          source: 'observed-scene',
          title: 'phase-1-zh-continuity-seam',
          summary: '修补线程是实的，但回线还需要 hover-first 的空间。',
          confidence: 0.86,
          significance: 0.86,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['phase-1-zh-continuity-seam'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread-continuation',
          sceneAgeMs: 2_000,
          attentionAgeMs: 2_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      } as any,
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: '修补线程是实的，但回线还需要 hover-first 的空间。',
          confidence: 0.84,
          stability: 0.84,
          focusThreadId: 'thread::phase-1-zh-continuity-seam',
          evidence: ['source:observed-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      } as any,
      selfState: {
        stance: 'approach',
        feltCloseness: 0.48,
        protectiveness: 0.42,
        curiosity: 0.78,
        patience: 0.54,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.32,
        dominantConcernId: null,
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.66,
        epistemicPressure: 0.28,
        relationalPressure: 0.38,
        carePressure: 0.24,
        continuityPressure: 0.84,
        restraintPressure: 0.42,
        surfacePressure: 0.8,
        speakReadiness: 0.76,
        presenceWeight: 0.7,
        motives: {
          'clarify': 0.84,
          'accompany': 0.36,
          'protect': 0.24,
          'stay-silent': 0.22,
        },
        speakDrive: 0.82,
        silenceDrive: 0.2,
        narrative: [],
        updatedAt: 12_000,
      },
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.86,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.58,
            timingFitness: 0.8,
            identityFit: 0.84,
            score: 0.84,
            why: 'The fix is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.26,
            timingFitness: 0.72,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      projectState: {
        preflightSummary: 'Alicization 是本地优先的数字生命项目｜阶段一｜open=记忆、主动性和具身表达闭环还没收紧｜next=顺着同一条线接回去，不要像重新开场那样贴近。',
        identity: '本地优先的数字生命项目，要把她维持成同一个她。',
        currentPhase: '阶段一：本地数字生命',
        latestLandedProgress: '已有一部分闭环收口落地，但还不能把同一条线说成重新开始。',
        primaryOpenLoop: '记忆、主动性和具身表达闭环还没收紧。',
        nextClosureTarget: '顺着同一条线接回去，让主动性先保持 measured-return 的回线。',
        sameHerSelfLine: '她还是同一个她，这条线要轻一点接回去。',
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.score ?? 0)
      .toBeGreaterThan(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::speak')?.score ?? 0)
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/同一条线|接回去|measured-return/i)
  })

  it('keeps same-her hover-first arbitration alive when selector carries lose array scaffolding', () => {
    const arbitration = buildInitiativeArbitration({
      now: 12_000,
      context: {
        localTime: { hour: 15, minute: 20, isLateNight: false },
        system: {
          cpuUsage: 12,
          battery: { percent: 70, charging: true },
          memory: { usagePercent: 38, freeMB: 4096, totalMB: 8192 },
          idleSeconds: 18,
          inputActivity: 'idle',
          fullscreenLikely: false,
          foregroundWindow: undefined,
          degradedSignals: [],
        },
        workload: { kind: 'coding', confidence: 0.84, source: 'screen-semantic-summary', matchedLabels: ['cursor'] },
        content: { kind: 'error', confidence: 0.86, source: 'screen-semantic-summary', matchedLabels: ['error'] },
        relationship: {
          hostAttitude: 'still warm, but the life loop should close carefully',
          boredom: 56,
          loneliness: 44,
          fatigue: 18,
          minutesSinceLastUserTurn: 6,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      worldModel: {
        activeThread: {
          id: 'thread::life-loop',
          kind: 'debugging',
          status: 'active',
          source: 'live-scene',
          title: 'TypeScript repair',
          summary: 'The fix thread is concrete, but the opening should stay lower-pressure.',
          confidence: 0.84,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['typescript-error'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 12_000,
          attentionAgeMs: 8_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'moderate',
        },
        updatedAt: 12_000,
      } as any,
      worldOntology: {
        dominantFrame: 'live',
        truthPriority: ['live', 'remembered'],
        live: {
          kind: 'live',
          summary: 'The fix thread is concrete, but the opening should stay lower-pressure.',
          confidence: 0.84,
          stability: 0.82,
          focusThreadId: 'thread::life-loop',
          evidence: ['source:live-scene'],
        },
        remembered: null,
        imagined: null,
        updatedAt: 12_000,
      } as any,
      selfState: {
        stance: 'approach',
        feltCloseness: 0.48,
        protectiveness: 0.42,
        curiosity: 0.78,
        patience: 0.54,
        desireToSpeak: 0.78,
        fearOfInterrupting: 0.32,
        dominantConcernId: 'concern::phase-1-progress-open-loop',
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.66,
        epistemicPressure: 0.28,
        relationalPressure: 0.38,
        carePressure: 0.24,
        continuityPressure: 0.84,
        restraintPressure: 0.42,
        surfacePressure: 0.8,
        speakReadiness: 0.76,
        presenceWeight: 0.7,
        motives: {
          'clarify': 0.84,
          'accompany': 0.36,
          'protect': 0.24,
          'stay-silent': 0.22,
        },
        speakDrive: 0.82,
        silenceDrive: 0.2,
        narrative: [],
        updatedAt: 12_000,
      },
      concerns: [{
        id: 'concern::phase-1-progress-open-loop',
        kind: 'help-fix',
        status: 'active',
        summary: 'The fix thread is real, but this Phase 1 closure line is still unfinished.',
        hostGoal: 'resolve-problem',
        tension: 0.74,
        confidence: 0.84,
        careWeight: 0.64,
        createdAt: 0,
        lastEvidenceAt: 12_000,
        patienceUntil: 60_000,
      }],
      counterfactualDeliberation: {
        selectedOptionId: 'counterfactual::speak',
        selectedAction: 'speak',
        confidence: 0.86,
        dominantTradeoff: 'grounded-help-over-distance',
        options: [
          {
            id: 'counterfactual::speak',
            action: 'speak',
            style: 'light-nudge',
            embodiedPresence: 'attentive',
            relationshipCost: 0.18,
            interruptionCost: 0.16,
            informationGain: 0.58,
            timingFitness: 0.8,
            identityFit: 0.84,
            score: 0.84,
            why: 'The fix is concrete enough that speaking now could help.',
          },
          {
            id: 'counterfactual::hover',
            action: 'hover',
            style: 'silent-observe',
            embodiedPresence: 'attentive',
            relationshipCost: 0.08,
            interruptionCost: 0.06,
            informationGain: 0.26,
            timingFitness: 0.72,
            identityFit: 0.82,
            score: 0.74,
            why: 'Stay close to the seam without widening closeness too fast.',
          },
        ],
        narrative: [],
        updatedAt: 12_000,
      } as any,
      threadRuntime: {
        foregroundThreadId: 'runtime-thread-missing-array',
      } as any,
      thoughtThreads: {
        foregroundThreadId: 'thought-thread-missing-array',
      } as any,
      selfGovernor: {
        dominantIntentionId: 'intention-missing-array',
      } as any,
      commitmentLedger: {
        governingCommitmentId: 'commitment-missing-array',
      } as any,
      desireMemory: {
        resurfacingDesireId: 'desire-missing-array',
      } as any,
      motiveEngine: {
        rulingDrive: 'unfinished-thread-return',
        drives: {
          companionship: 0.44,
          boundaryRespect: 0.5,
          truthDiscipline: 0.74,
          restProtection: 0.28,
          unfinishedThreadReturn: 0.84,
          selfDirection: 0.58,
        },
        returnPressure: 0.8,
      } as any,
      projectState: {
        preflightSummary: 'Alicization is a local-first digital life project | Phase 1: Local Digital Life | open=Memory, initiative, and embodiment still need one tighter identity-continuity',
        identity: 'Alicization is a local-first digital life project building identity continuity.',
        currentPhase: 'Phase 1: Local Digital Life',
        latestLandedProgress: 'Same-session mirror carry, repeated next-turn carry, and answer-planner governingProject carry now survive often enough to build from.',
        primaryOpenLoop: 'Memory, initiative, and embodiment still need one tighter identity-continuity',
        nextClosureTarget: 'Keep project identity carry, Phase 1 route carry, and unresolved closure carry on one measured-return continuity state.',
        sameHerSelfLine: 'structured continuity digest.',
      } as any,
    } as any)

    expect(arbitration.selectedProposalId).toBe('counterfactual:counterfactual::hover')
    expect(arbitration.proposals[0]?.action).toBe('hover')
    expect(arbitration.proposals.find(proposal => proposal.id === 'counterfactual:counterfactual::hover')?.why ?? '')
      .toMatch(/same-line|continuity state|local-first/i)
  })
})
