import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

describe('main-chat-timeout-fallback regression', () => {
  it('keeps timeout fallback anchored on the shared project-state brief while preserving richer lived project awareness only when runtime carries an explicit structured summary', () => {
    const source = readFileSync(new URL('./main-chat-timeout-fallback.ts', import.meta.url), 'utf8')

    expect(source).toContain('resolveAlicizationProjectStateBrief')
    expect(source).toContain('const projectStateBrief = resolveAlicizationProjectStateBrief()')
    expect(source).toContain('preDialogueSendIdentity?: AlicizationChatStartPayload[\'preDialogueSendIdentity\'] | null')
    expect(source).toContain('const payloadPreflightSummary')
    expect(source).toContain('const payloadPreDialogueAwarenessLine')
    expect(source).toContain('const payloadCompanionBriefingLine')
    expect(source).toContain('const canonicalPreDialogueAwarenessLine')
    expect(source).toContain('const explicitRuntimeCompanionHeadlineLine')
    expect(source).toContain('const preflightSummary')
    expect(source).toContain('?? payloadPreflightSummary')
    expect(source).toContain('explicitRuntimeCompanionHeadlineLine && explicitRuntimeCompanionHeadlineLine !== canonicalPreDialogueAwarenessLine')
    expect(source).toContain('preDialogueAwarenessLine: payloadPreDialogueAwarenessLine ?? canonicalPreDialogueAwarenessLine')
    expect(source).toContain('companionBriefingLine: payloadCompanionBriefingLine ?? payloadPreDialogueAwarenessLine ?? canonicalPreDialogueAwarenessLine')
    expect(source).toContain('identity: projectStateBrief.identity')
    expect(source).toContain('currentPhase: input.runtimeDigest?.projectState?.currentPhase ?? projectStateBrief.currentPhase')
    expect(source).toContain('const latestLandedProgress')
    expect(source).toContain('input.runtimeDigest?.projectState?.latestLandedProgress')
    expect(source).toContain('?? input.runtimeDigest?.projectState?.latestProgress')
    expect(source).toContain('?? input.runtimeDigest?.projectState?.memoryClosureSummary')
    expect(source).toContain('normalizeTimeoutFallbackProjectText(projectStateBrief.continuityProgressSummary)')
    expect(source).toContain('const sameHerDriftRisk')
    expect(source).toContain('input.runtimeDigest?.projectState?.sameHerDriftRisk')
    expect(source).toContain('projectStateBrief.sameHerDriftRisk')
    expect(source).toContain('resolveTimeoutFallbackPreferredEmbodimentClosureSummary')
    expect(source).toContain('buildTimeoutFallbackProjectStateAuditContinuitySummary')
    expect(source).toContain('const projectStateAudit')
    expect(source).toContain('const explicitOrPayloadCompanionBriefingLine')
    expect(source).toContain('const richerRuntimeProjectAwarenessSummary = preferTimeoutFallbackProjectAwarenessSummary({')
    expect(source).toContain('summaryCandidate: input.runtimeDigest?.projectState?.preDialogueAwarenessSummary')
    expect(source).toContain('preDialogueAwarenessSummary: richerRuntimeProjectAwarenessSummary ?? preDialogueAwarenessLine')
    expect(source).toContain('continuitySummary: buildTimeoutFallbackProjectStateAuditContinuitySummary({')
    expect(source).toContain('projectStateAudit,')
    expect(source).toContain('latestLandedProgress,')
    expect(source).toContain('const primaryOpenLoop')
    expect(source).toContain('const nextClosureTarget = preferTimeoutFallbackProjectNextClosureTarget(')
    expect(source).toContain('primaryOpenLoop,')
    expect(source).toContain('nextClosureTarget,')
    expect(source).toContain('sameHerDriftRisk,')
  })
})
