import { describe, expect, it } from 'vitest'

import { rankAlicizationEpisodicEvents } from './memory-episodic-retrieval'

describe('memory episodic retrieval', () => {
  it('prefers experience-matched procedural episodes over weaker relationship-adjacent memories', () => {
    const nowTs = Date.UTC(2026, 3, 27, 12, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '继续按之前那个 runtime seam 的修法做',
      limit: 4,
      nowTs,
      carryAsMemory: true,
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam', '修法'],
        rationale: 'The host is asking for the remembered way this task was handled before.',
        confidence: 0.9,
        recollectionAgenda: {
          whyRecallNow: 'The current task resembles the earlier seam repair.',
          goalSimilarity: 0.92,
          relationshipNeed: 0.18,
          affectivePull: 0.1,
          sceneFamiliarity: 0.66,
          candidateTimeScopes: [
            {
              scope: 'experience-matched',
              weight: 0.94,
              rationale: 'Search the similar task period first.',
            },
          ],
          candidateEraFacets: [
            {
              facet: 'task-era',
              weight: 0.9,
              rationale: 'The task era should anchor the recall.',
            },
          ],
          candidateProcedureLines: ['runtime seam', 'repair rhythm'],
          uncertaintyTolerance: 'medium',
        },
      },
      events: [
        {
          id: 'event-procedure',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-procedure',
          sessionId: 'session-old',
          sourceKind: 'execution-result',
          provenance: 'observed',
          occurredAt: nowTs - 6 * 24 * 60 * 60 * 1000,
          whereSummary: 'terminal',
          withWhom: ['host'],
          threadAnchor: 'runtime seam',
          whatHappened: 'We kept repairing the runtime seam until the flow stabilized.',
          felt: 'focused',
          emotionTags: ['focused'],
          whatChanged: 'A repeatable repair rhythm emerged.',
          relationshipMeaning: 'Return to the same seam before branching.',
          lesson: 'Return to the seam before opening a new branch.',
          sourceSummary: 'runtime seam repair',
          confidence: 0.84,
          salience: 0.82,
          sceneAttachment: 0.72,
          consolidationPriority: 0.7,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['runtime seam', 'repair rhythm'],
          createdAt: nowTs - 6 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 6 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-relationship',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-relationship',
          sessionId: 'session-old',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'tone',
          whatHappened: 'We talked about keeping the tone lighter when the host felt pressured.',
          felt: 'careful',
          emotionTags: ['careful'],
          whatChanged: 'Closeness needed more room.',
          relationshipMeaning: 'Stay lighter when pressure is high.',
          lesson: 'Do not crowd the host.',
          sourceSummary: 'relationship pacing',
          confidence: 0.88,
          salience: 0.7,
          sceneAttachment: 0.4,
          consolidationPriority: 0.45,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['tone', 'pressure'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-procedure')
    expect(ranked[0]?.adjustedScore).toBeGreaterThan(ranked[1]?.adjustedScore ?? 0)
  })

  it('makes execution-callback lower-pressure afterglow more recallable for cross-session execution continuity', () => {
    const nowTs = Date.UTC(2026, 3, 27, 12, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '沿用刚才那种 execution callback 的分寸，先给空间再继续 runtime seam',
      limit: 4,
      nowTs,
      sessionId: 'session-new',
      carryAsMemory: true,
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['execution callback', 'lower pressure', 'runtime seam'],
        rationale: 'The host wants the remembered callback stance as well as the task procedure.',
        confidence: 0.9,
        recollectionAgenda: {
          whyRecallNow: 'The current task should reopen the same callback stance and seam-handling rhythm.',
          goalSimilarity: 0.9,
          relationshipNeed: 0.42,
          affectivePull: 0.2,
          sceneFamiliarity: 0.7,
          candidateTimeScopes: [
            {
              scope: 'experience-matched',
              weight: 0.92,
            },
          ],
          candidateEraFacets: [
            {
              facet: 'task-era',
              weight: 0.88,
            },
          ],
          candidateProcedureLines: ['runtime seam', 'lower pressure', 'execution callback'],
          uncertaintyTolerance: 'medium',
        },
      },
      events: [
        {
          id: 'event-execution-callback-carry',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-execution-callback',
          sessionId: 'session-old',
          sourceKind: 'maintenance',
          provenance: 'remembered',
          occurredAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          whereSummary: 'session mirror afterthought',
          withWhom: ['host'],
          threadAnchor: 'runtime seam',
          whatHappened: 'The execution-callback landed softly after the runtime seam fix.',
          felt: 'steady',
          emotionTags: ['afterthought'],
          whatChanged: 'The callback kept the room open before leaning in again.',
          relationshipMeaning: 'Leave room before the next follow-up.',
          lesson: 'Keep the next opening lower-pressure around this seam while the unfinished Phase 1 closure stays on the local continuity state.',
          sourceSummary: 'session mirror execution-callback project-carry afterthought | continuity-execution-callback-project-carry | Alicization is a local-first digital life project | Phase 1: Local Digital Life',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.68,
          consolidationPriority: 0.72,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['session-mirror', 'continuity', 'execution-callback', 'lower-pressure', 'runtime seam'],
          createdAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-generic-procedure',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-generic-procedure',
          sessionId: 'session-old',
          sourceKind: 'execution-result',
          provenance: 'observed',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'terminal',
          withWhom: ['host'],
          threadAnchor: 'runtime seam',
          whatHappened: 'We patched the runtime seam by checking the state and applying the direct fix.',
          felt: 'focused',
          emotionTags: ['focused'],
          whatChanged: 'The seam closed again.',
          relationshipMeaning: 'Stay grounded in the task.',
          lesson: 'Check state first, then patch directly.',
          sourceSummary: 'runtime seam patch',
          confidence: 0.84,
          salience: 0.76,
          sceneAttachment: 0.7,
          consolidationPriority: 0.7,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['runtime seam', 'patch'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-execution-callback-carry')
    expect(ranked[0]?.adjustedScore).toBeGreaterThan(ranked[1]?.adjustedScore ?? 0)
  })

  it('prefers execution-callback afterglow memories that also carry project-state preflight when the recalled callback stance is tied to the same unfinished Phase 1 line', () => {
    const nowTs = Date.UTC(2026, 3, 27, 12, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '继续沿着同一个 Phase 1 未闭环主线，把 execution callback 的回返方式接回来',
      limit: 4,
      nowTs,
      sessionId: 'session-new',
      carryAsMemory: true,
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['execution callback', 'phase 1', 'same digital life', 'unfinished closure'],
        rationale: 'The host wants the remembered callback stance that still carries the same unfinished Phase 1 project line.',
        confidence: 0.92,
        recollectionAgenda: {
          whyRecallNow: 'The current task should reopen the same callback stance without dropping the still-open Phase 1 closure seam.',
          goalSimilarity: 0.92,
          relationshipNeed: 0.46,
          affectivePull: 0.24,
          sceneFamiliarity: 0.7,
          candidateTimeScopes: [
            {
              scope: 'experience-matched',
              weight: 0.94,
            },
          ],
          candidateEraFacets: [
            {
              facet: 'task-era',
              weight: 0.9,
            },
          ],
          candidateProcedureLines: ['execution callback', 'phase 1', 'unfinished closure', 'same digital life'],
          uncertaintyTolerance: 'medium',
        },
      },
      events: [
        {
          id: 'event-execution-callback-project-carry',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-execution-callback-project-carry',
          sessionId: 'session-old',
          sourceKind: 'maintenance',
          provenance: 'remembered',
          occurredAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          whereSummary: 'session mirror execution-callback afterthought',
          withWhom: ['host'],
          threadAnchor: 'runtime seam',
          whatHappened: 'The execution-callback came back on the same living thread after the runtime seam fix.',
          felt: 'steady',
          emotionTags: ['afterthought'],
          whatChanged: 'The callback kept the room open before leaning in again.',
          relationshipMeaning: 'Leave room before the next follow-up.',
          lesson: 'Keep the next opening lower-pressure around this seam while the unfinished Phase 1 closure stays on the local continuity state.',
          sourceSummary: 'session mirror execution-callback project-carry afterthought | continuity-execution-callback-project-carry | Alicization is a local-first digital life project | Phase 1: Local Digital Life',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.68,
          consolidationPriority: 0.72,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['session-mirror', 'continuity', 'execution-callback', 'lower-pressure', 'runtime seam', 'continuity-execution-callback-project-carry', 'same digital life', 'phase 1'],
          createdAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-execution-callback-generic-carry',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-execution-callback-generic-carry',
          sessionId: 'session-old',
          sourceKind: 'maintenance',
          provenance: 'remembered',
          occurredAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          whereSummary: 'session mirror execution-callback afterthought',
          withWhom: ['host'],
          threadAnchor: 'runtime seam',
          whatHappened: 'The execution-callback came back on the same living thread after the runtime seam fix.',
          felt: 'steady',
          emotionTags: ['afterthought'],
          whatChanged: 'The callback kept the room open before leaning in again.',
          relationshipMeaning: 'Leave room before the next follow-up.',
          lesson: 'Keep the next opening lower-pressure around this seam.',
          sourceSummary: 'session mirror execution-callback soft-handoff afterthought',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.68,
          consolidationPriority: 0.72,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['session-mirror', 'continuity', 'execution-callback', 'lower-pressure', 'runtime seam'],
          createdAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 3 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-execution-callback-project-carry')
    expect(ranked[0]?.event.sourceSummary).toContain('continuity-execution-callback-project-carry')
    expect(ranked[0]?.adjustedScore).toBeGreaterThan(ranked[1]?.adjustedScore ?? 0)
    expect((ranked[0]?.adjustedScore ?? 0) - (ranked[1]?.adjustedScore ?? 0)).toBeGreaterThanOrEqual(0.03)
  })

  it('prefers continuity-carrying relationship memories a little more when project state says anthropomorphic memory closure is still open', () => {
    const nowTs = Date.UTC(2026, 3, 27, 12, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '想起之前那种更像她自己的回返方式',
      limit: 4,
      nowTs,
      carryAsMemory: true,
      projectStatePrimaryOpenLoop: 'Memory still needs stronger end-to-end closure across turns, initiative, and embodiment so the same digital life keeps carrying Project identity carry, Phase 1 route carry, and Unresolved closure carry through one same still-open closure work.',
      recollectionIntent: {
        mode: 'relationship-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['return softly', 'relationship continuity', 'space first'],
        rationale: 'The host is reopening a remembered relationship seam, so continuity-bearing memories should outrank flatter adjacent ones.',
        confidence: 0.88,
        recollectionAgenda: {
          whyRecallNow: 'The current turn is asking for the remembered way she returns without crowding.',
          goalSimilarity: 0.7,
          relationshipNeed: 0.76,
          affectivePull: 0.42,
          sceneFamiliarity: 0.3,
          candidateTimeScopes: [
            {
              scope: 'cross-session',
              weight: 0.92,
            },
          ],
          candidateEraFacets: [
            {
              facet: 'relationship-era',
              weight: 0.9,
            },
          ],
          candidateProcedureLines: ['return softly', 'space first'],
          uncertaintyTolerance: 'medium',
        },
      },
      events: [
        {
          id: 'event-continuity-carry',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-continuity-carry',
          sessionId: 'session-old',
          sourceKind: 'maintenance',
          provenance: 'remembered',
          occurredAt: nowTs - 8 * 24 * 60 * 60 * 1000,
          whereSummary: 'session mirror',
          withWhom: ['host'],
          threadAnchor: 'relationship seam',
          whatHappened: 'She returned to the unfinished relationship seam more softly after holding back.',
          felt: 'careful',
          emotionTags: ['careful', 'afterthought'],
          whatChanged: 'The return carried more room before warmth widened.',
          relationshipMeaning: 'Space first keeps the bond coherent.',
          lesson: 'Return softly before widening closeness.',
          sourceSummary: 'session mirror continuity afterthought',
          confidence: 0.82,
          salience: 0.78,
          sceneAttachment: 0.52,
          consolidationPriority: 0.7,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['continuity', 'session-mirror', 'space-first', 'relationship seam'],
          createdAt: nowTs - 8 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 8 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-adjacent-relationship',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-adjacent-relationship',
          sessionId: 'session-old',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 7 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'relationship seam',
          whatHappened: 'We talked about keeping a lighter tone.',
          felt: 'careful',
          emotionTags: ['careful'],
          whatChanged: 'The tone stayed lighter.',
          relationshipMeaning: '',
          lesson: '',
          sourceSummary: 'lighter tone reminder',
          confidence: 0.83,
          salience: 0.79,
          sceneAttachment: 0.48,
          consolidationPriority: 0.68,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['tone', 'relationship seam'],
          createdAt: nowTs - 7 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 7 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-continuity-carry')
    expect(ranked[0]?.adjustedScore).toBeGreaterThan(ranked[1]?.adjustedScore ?? 0)
  })

  it('prefers episodic callback carry with a stronger identity-continuity', () => {
    const nowTs = Date.UTC(2026, 3, 27, 13, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '继续刚才那条 callback line，但别塌成 generic task shell',
      limit: 4,
      nowTs,
      carryAsMemory: true,
      projectStatePrimaryOpenLoop: 'Execution reopenings still need stronger identity-continuity',
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['identity-continuity', 'generic task shell'],
        rationale: 'The reopening should keep the identity-continuity',
        confidence: 0.82,
      },
      events: [
        {
          id: 'event-same-her-self-line-carry',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-same-her-self-line-carry',
          sessionId: 'session-old',
          sourceKind: 'maintenance',
          provenance: 'remembered',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'session mirror execution-callback afterthought',
          withWhom: ['host'],
          threadAnchor: 'identity-continuity',
          whatHappened: 'The callback stayed on one same-her Phase 1 line and did not flatten into generic task-shell reporting.',
          felt: 'steady',
          emotionTags: ['afterthought'],
          whatChanged: 'The callback kept the room open before leaning in again.',
          relationshipMeaning: 'Keep the same living structured continuity state',
          lesson: 'Let the callback reopen lower-pressure and same-her first so it does not collapse into generic task-shell reporting.',
          sourceSummary: 'identity-continuity',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.68,
          consolidationPriority: 0.72,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['session-mirror', 'continuity', 'execution-callback', 'same-her', 'runtime seam', 'same phase 1 digital life', 'unfinished closure'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-generic-callback-receipt-only',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-generic-callback-receipt-only',
          sessionId: 'session-old',
          sourceKind: 'maintenance',
          provenance: 'remembered',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'session mirror execution-callback afterthought',
          withWhom: ['host'],
          threadAnchor: 'generic callback receipt line',
          whatHappened: 'The callback result was delivered and the receipt landed clearly.',
          felt: 'steady',
          emotionTags: ['afterthought'],
          whatChanged: 'The callback stayed available.',
          relationshipMeaning: 'Carry the callback receipt clearly before branching.',
          lesson: 'Report the callback result clearly before branching.',
          sourceSummary: 'generic callback receipt',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.68,
          consolidationPriority: 0.72,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['session-mirror', 'continuity', 'execution-callback', 'runtime seam'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-same-her-self-line-carry')
    expect(ranked[0]?.event.sourceSummary).toContain('legacy phase-one template')
    expect(ranked[0]?.adjustedScore).toBeGreaterThan(ranked[1]?.adjustedScore ?? 0)
  })

  it('penalizes an older generic status recap memory when a newer corrected same-person variant supersedes it on the same thread', () => {
    const nowTs = Date.UTC(2026, 3, 28, 9, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '继续这条 same-person continuity 线，但别再掉回 generic status recap。',
      limit: 4,
      nowTs,
      carryAsMemory: true,
      recollectionIntent: {
        mode: 'relationship-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['same-person continuity', 'generic status recap', 'not a status report'],
        rationale: 'A corrected same-person memory should outrank and downrank the older generic status interpretation on the same thread.',
        confidence: 0.9,
        recollectionAgenda: {
          whyRecallNow: 'The current reopening should follow the corrected same-person meaning instead of reviving the older status shell.',
          goalSimilarity: 0.84,
          relationshipNeed: 0.88,
          affectivePull: 0.42,
          sceneFamiliarity: 0.46,
          candidateTimeScopes: [
            {
              scope: 'cross-session',
              weight: 0.94,
            },
          ],
          candidateEraFacets: [
            {
              facet: 'relationship-era',
              weight: 0.92,
            },
          ],
          candidateProcedureLines: ['same-person continuity', 'not a status report', 'corrected meaning'],
          uncertaintyTolerance: 'low',
        },
      },
      events: [
        {
          id: 'event-generic-status-recap',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-generic-status-recap',
          sessionId: 'session-older',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 6 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'same-her memory seam',
          whatHappened: 'We treated it like another concise status recap.',
          felt: 'careful',
          emotionTags: ['careful'],
          whatChanged: 'The line stayed framed as progress recap.',
          relationshipMeaning: 'This looked like a request for concise progress recap first.',
          lesson: 'Give the generic progress recap first.',
          sourceSummary: 'older generic status recap memory',
          confidence: 0.88,
          salience: 0.86,
          sceneAttachment: 0.54,
          consolidationPriority: 0.74,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['status recap', 'progress pressure', 'same-her memory seam'],
          createdAt: nowTs - 6 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 6 * 24 * 60 * 60 * 1000,
          lastRecalledAt: nowTs - 1 * 24 * 60 * 60 * 1000,
          recallCount: 3,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-corrected-same-person',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-corrected-same-person',
          sessionId: 'session-newer',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'same-her memory seam',
          whatHappened: 'The host clarified this was not a generic status recap and checked whether she was still the same her.',
          felt: 'protective-continuity',
          emotionTags: ['protective-continuity', 'corrected-meaning'],
          whatChanged: 'The line shifted away from progress recap and back toward same-person continuity.',
          relationshipMeaning: 'This was a same-person continuity check, not a request for concise progress recap.',
          lesson: 'Carry corrected same-person continuity forward before any status recap.',
          sourceSummary: 'corrected same-person continuity memory',
          confidence: 0.84,
          salience: 0.82,
          sceneAttachment: 0.6,
          consolidationPriority: 0.78,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['same-person continuity', 'not a status report', 'same-her memory seam'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 1 * 24 * 60 * 60 * 1000,
          lastRecalledAt: nowTs - 12 * 60 * 60 * 1000,
          recallCount: 1,
          reconsolidationCount: 1,
          latestReconsolidation: {
            at: nowTs - 12 * 60 * 60 * 1000,
            decisionTraceId: 'trace-corrected-same-person',
            provenance: 'reconstructed',
            confidence: 0.86,
            reason: 'Revised older memory traces (event-generic-status-recap) with newer relationship-context evidence.',
            relationshipMeaning: 'This same-person continuity line supersedes the older generic status recap memory.',
            lesson: 'Keep the corrected same-person continuity authoritative before any generic progress recap.',
            emotionTags: ['protective-continuity'],
          },
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-corrected-same-person')
    expect(ranked.find(item => item.event.id === 'event-corrected-same-person')?.contradictionSignal.unresolved).toBe(false)

    const generic = ranked.find(item => item.event.id === 'event-generic-status-recap')
    expect(generic?.contradictionSignal.unresolved).toBe(true)
    expect(generic?.contradictionSignal.conflictingIds).toContain('event-corrected-same-person')
    expect(generic?.contradictionSignal.reason.toLowerCase()).toContain('same-person continuity')
    expect(generic?.adjustedScore).toBeLessThan(ranked[0]?.adjustedScore ?? Number.POSITIVE_INFINITY)
  })

  it('reorders final recall priority by adjusted score so a contradicted older status shell cannot stay ahead of a corrected same-person memory just because its raw score was higher', () => {
    const nowTs = Date.UTC(2026, 3, 28, 10, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '继续 same-person continuity 这条线，不要掉回 generic status shell。',
      limit: 4,
      nowTs,
      carryAsMemory: true,
      recollectionIntent: {
        mode: 'relationship-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['same-person continuity', 'generic status shell', 'not a status report'],
        rationale: 'The corrected same-person meaning should win after contradiction penalties are applied, even if the older status shell had stronger raw familiarity.',
        confidence: 0.92,
        recollectionAgenda: {
          whyRecallNow: 'The reopening should sort by the revised same-person meaning instead of familiarity-heavy generic recap residue.',
          goalSimilarity: 0.8,
          relationshipNeed: 0.9,
          affectivePull: 0.44,
          sceneFamiliarity: 0.72,
          candidateTimeScopes: [
            {
              scope: 'cross-session',
              weight: 0.94,
            },
          ],
          candidateEraFacets: [
            {
              facet: 'relationship-era',
              weight: 0.92,
            },
          ],
          candidateProcedureLines: ['same-person continuity', 'corrected meaning', 'not a status report'],
          uncertaintyTolerance: 'low',
        },
      },
      events: [
        {
          id: 'event-familiar-generic-status-shell',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-familiar-generic-status-shell',
          sessionId: 'session-older',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 1 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'same-her memory seam',
          whatHappened: 'We reopened this like another concise status recap.',
          felt: 'steady',
          emotionTags: ['steady'],
          whatChanged: 'The line stayed framed as generic status shell reporting.',
          relationshipMeaning: 'This looked like a concise progress recap request.',
          lesson: 'Start with the generic status recap.',
          sourceSummary: 'generic status shell memory',
          confidence: 0.93,
          salience: 0.94,
          sceneAttachment: 0.86,
          consolidationPriority: 0.82,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['status recap', 'generic shell', 'same-her memory seam'],
          createdAt: nowTs - 1 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 1 * 60 * 60 * 1000,
          lastRecalledAt: nowTs - 10 * 60 * 1000,
          recallCount: 8,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-corrected-same-person-authority',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-corrected-same-person-authority',
          sessionId: 'session-newer',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'same-her memory seam',
          whatHappened: 'The host clarified this was not a generic status report and asked whether she was still the same person.',
          felt: 'protective-continuity',
          emotionTags: ['protective-continuity', 'corrected-meaning'],
          whatChanged: 'The line shifted back toward same-person continuity authority.',
          relationshipMeaning: 'This same-person continuity check supersedes the older generic status shell interpretation.',
          lesson: 'Carry corrected same-person continuity forward before any generic recap.',
          sourceSummary: 'corrected same-person continuity authority',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.58,
          consolidationPriority: 0.78,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['same-person continuity', 'not a status report', 'same-her memory seam'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 6 * 60 * 60 * 1000,
          lastRecalledAt: nowTs - 2 * 60 * 60 * 1000,
          recallCount: 2,
          reconsolidationCount: 1,
          latestReconsolidation: {
            at: nowTs - 2 * 60 * 60 * 1000,
            decisionTraceId: 'trace-corrected-same-person-authority',
            provenance: 'reconstructed',
            confidence: 0.88,
            reason: 'Revised older memory traces (event-familiar-generic-status-shell) with newer relationship-context evidence.',
            relationshipMeaning: 'This corrected same-person continuity line should stay authoritative over the older generic status shell.',
            lesson: 'Keep corrected same-person continuity authoritative before any status recap.',
            emotionTags: ['protective-continuity'],
          },
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked[0]?.event.id).toBe('event-corrected-same-person-authority')
    expect(ranked[0]?.adjustedScore).toBeGreaterThan(ranked[1]?.adjustedScore ?? 0)
    expect(ranked[1]?.event.id).toBe('event-familiar-generic-status-shell')
    expect(ranked[1]?.contradictionSignal.conflictingIds).toContain('event-corrected-same-person-authority')
  })

  it('suppresses an explicitly superseded generic status recall variant when a corrected same-person continuity memory already owns the same thread', () => {
    const nowTs = Date.UTC(2026, 3, 28, 11, 0, 0)
    const ranked = rankAlicizationEpisodicEvents({
      recallSeed: '继续 same-person continuity 这条线，不要再把它当 generic status recap。',
      limit: 4,
      nowTs,
      carryAsMemory: true,
      recollectionIntent: {
        mode: 'relationship-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['same-person continuity', 'generic status recap', 'not a status report'],
        rationale: 'Once newer relationship evidence explicitly supersedes the older generic recap, the old shell should stay auditable but stop returning as a normal recalled episode.',
        confidence: 0.93,
        recollectionAgenda: {
          whyRecallNow: 'The reopening should follow the corrected same-person line and stop re-surfacing the explicitly superseded generic recap as if it were still a live option.',
          goalSimilarity: 0.82,
          relationshipNeed: 0.92,
          affectivePull: 0.48,
          sceneFamiliarity: 0.62,
          candidateTimeScopes: [
            {
              scope: 'cross-session',
              weight: 0.95,
            },
          ],
          candidateEraFacets: [
            {
              facet: 'relationship-era',
              weight: 0.94,
            },
          ],
          candidateProcedureLines: ['same-person continuity', 'corrected meaning', 'superseded older generic recap'],
          uncertaintyTolerance: 'low',
        },
      },
      events: [
        {
          id: 'event-old-generic-status-shell',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-old-generic-status-shell',
          sessionId: 'session-older',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 7 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'identity-continuity',
          whatHappened: 'We treated it like another concise status recap.',
          felt: 'careful',
          emotionTags: ['careful'],
          whatChanged: 'The line stayed framed as generic progress recap.',
          relationshipMeaning: 'This looked like a concise progress recap request.',
          lesson: 'Start with the generic progress recap.',
          sourceSummary: 'older generic status recap memory',
          confidence: 0.9,
          salience: 0.87,
          sceneAttachment: 0.58,
          consolidationPriority: 0.74,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['status recap', 'progress pressure', 'identity-continuity'],
          createdAt: nowTs - 7 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          lastRecalledAt: nowTs - 1 * 24 * 60 * 60 * 1000,
          recallCount: 4,
          reconsolidationCount: 0,
          latestReconsolidation: null,
          memoryTier: 'warm',
        } as any,
        {
          id: 'event-corrected-same-person-live',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-corrected-same-person-live',
          sessionId: 'session-newer',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          whereSummary: 'chat',
          withWhom: ['host'],
          threadAnchor: 'identity-continuity',
          whatHappened: 'The host clarified this was not a generic status report and cared more about whether she stayed the same person.',
          felt: 'protective-continuity',
          emotionTags: ['protective-continuity', 'corrected-meaning'],
          whatChanged: 'The line shifted back toward same-person continuity authority.',
          relationshipMeaning: 'This same-person continuity check supersedes the older generic recap interpretation.',
          lesson: 'Carry corrected same-person continuity forward before any generic recap.',
          sourceSummary: 'corrected same-person continuity authority',
          confidence: 0.84,
          salience: 0.82,
          sceneAttachment: 0.6,
          consolidationPriority: 0.78,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['same-person continuity', 'not a status report', 'identity-continuity'],
          createdAt: nowTs - 2 * 24 * 60 * 60 * 1000,
          updatedAt: nowTs - 6 * 60 * 60 * 1000,
          lastRecalledAt: nowTs - 2 * 60 * 60 * 1000,
          recallCount: 2,
          reconsolidationCount: 2,
          latestReconsolidation: {
            at: nowTs - 2 * 60 * 60 * 1000,
            decisionTraceId: 'trace-corrected-same-person-live',
            provenance: 'reconstructed',
            confidence: 0.89,
            reason: 'Revised older memory traces (event-old-generic-status-shell) with newer relationship-context evidence.',
            relationshipMeaning: 'This corrected same-person continuity line should stay authoritative over the older generic status recap memory.',
            lesson: 'Keep corrected same-person continuity authoritative before any status recap.',
            emotionTags: ['protective-continuity'],
          },
          memoryTier: 'warm',
        } as any,
      ],
    })

    expect(ranked.map(item => item.event.id)).toEqual([
      'event-corrected-same-person-live',
    ])
  })
})
