import { describe, expect, it } from 'vitest'

import {
  blendAlicizationMemoryTelemetryLatency,
  createAlicizationMemoryRetrievalTelemetryRuntime,
  defaultAlicizationMemoryRetrievalTelemetry,
  normalizeAlicizationMemoryRetrievalTelemetry,
} from './memory-retrieval-telemetry'

describe('memory retrieval telemetry', () => {
  it('normalizes malformed telemetry payloads into a safe snapshot', () => {
    expect(normalizeAlicizationMemoryRetrievalTelemetry({
      semanticLatencyMs: '12',
      semanticSampleCount: '3',
      graphLatencyMs: '19',
      graphSampleCount: '2',
      candidateGenerationLatencyMs: '11',
      candidateGenerationSampleCount: '4',
      plannerLatencyMs: '13',
      plannerSampleCount: '5',
      speechPlanLatencyMs: '17',
      speechPlanSampleCount: '6',
      cacheHitCount: '7',
      cacheMissCount: '3',
      prewarmHitCount: '4',
      prewarmMissCount: '2',
      budgetLatencySamples: {
        'realtime-reply': [200, 100, 300],
      },
      recallHitRate: '0.8',
      recallMissRate: '0.2',
      recallAt1: '1.5',
      recallAt3: '0.75',
      precisionAt3: '0.5',
      wrongThreadRate: '0.1',
      wrongThreadSuppression: '0.9',
      suppressionHitRate: '0.6',
      wrongThreadPreventedCount: '3',
      falsePositiveSuppressionRate: '0.2',
      staleSelfModelVetoRate: '0.25',
      relationshipEraConfusionRate: '0.5',
      reconstructionErrorRate: '0.25',
      stableCoreOnlyRate: '0.75',
      memorySurfaceViolationRate: '0.15',
      templateLeakageFailCount: '4',
      claimAccuracy: '0.67',
      replyAuthorityAccuracy: '0.99',
      latencyBudgetPass: true,
      lastUpdatedAt: '123',
    })).toEqual({
      semanticLatencyMs: 12,
      semanticSampleCount: 3,
      graphLatencyMs: 19,
      graphSampleCount: 2,
      candidateGenerationLatencyMs: 11,
      candidateGenerationSampleCount: 4,
      plannerLatencyMs: 13,
      plannerSampleCount: 5,
      speechPlanLatencyMs: 17,
      speechPlanSampleCount: 6,
      cacheHitCount: 7,
      cacheMissCount: 3,
      prewarmHitCount: 4,
      prewarmMissCount: 2,
      budgetClassCounts: {
        'realtime-reply': 0,
        'deep-recall-reply': 0,
        'proactive-generation': 0,
        'nightly-benchmark': 0,
        'diagnosis-replay': 0,
      },
      budgetLatencyTelemetry: {
        'realtime-reply': {
          sampleCount: 3,
          p50LatencyMs: 200,
          p95LatencyMs: 300,
          maxLatencyMs: 300,
          gateStatus: 'pass',
          targetP95Ms: 900,
        },
        'deep-recall-reply': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 2200 },
        'proactive-generation': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 750 },
        'nightly-benchmark': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 5000 },
        'diagnosis-replay': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 3600 },
      },
      budgetLatencySamples: {
        'realtime-reply': [200, 100, 300],
        'deep-recall-reply': [],
        'proactive-generation': [],
        'nightly-benchmark': [],
        'diagnosis-replay': [],
      },
      organicStageTelemetry: {
        'search-prelude': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'candidate-generation': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'candidate-ranking': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'recollection-planning': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'surface-planning': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'self-evolution-integration': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'prompt-blocks': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
      },
      organicStageBudgetCounts: {
        'search-prelude': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'candidate-generation': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'candidate-ranking': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'recollection-planning': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'surface-planning': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'self-evolution-integration': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'prompt-blocks': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
      },
      hotKeyStats: [],
      recallHitRate: 0.8,
      recallMissRate: 0.2,
      recallAt1: 1,
      recallAt3: 0.75,
      precisionAt3: 0.5,
      wrongThreadRate: 0.1,
      wrongThreadSuppression: 0.9,
      suppressionHitRate: 0.6,
      wrongThreadPreventedCount: 3,
      falsePositiveSuppressionRate: 0.2,
      staleSelfModelVetoRate: 0.25,
      relationshipEraConfusionRate: 0.5,
      reconstructionErrorRate: 0.25,
      stableCoreOnlyRate: 0.75,
      memorySurfaceViolationRate: 0.15,
      templateLeakageFailCount: 4,
      claimAccuracy: 0.67,
      replyAuthorityAccuracy: 0.99,
      latencyBudgetPass: true,
      mindParticipation: 0,
      memoryParticipation: 0,
      personalityParticipation: 0,
      relationshipParticipation: 0,
      continuityParticipation: 0,
      learningTaskCompletionCount: 0,
      learningTaskCompletionRate: 0,
      learningTaskFailureCount: 0,
      learningTaskFailureRate: 0,
      learningTaskBlockedCount: 0,
      learningTaskReopenedCount: 0,
      learningTaskReopenRecoveryRate: 0,
      learningTaskDowngradedCount: 0,
      learningTaskCancelledCount: 0,
      learningRelationshipReviseCount: 0,
      learningSelfModelReviseCount: 0,
      learningWorldModelValidationCount: 0,
      learningWorldModelFalseInternalizationCount: 0,
      misinternalizationRate: 0,
      sampleCount: 0,
      learningPolicyStrictnessBias: 0,
      learningPolicyWrongThreadSuppressionBias: 0,
      learningPolicyProvenanceLabelBias: 0,
      learningPolicyReasonCodes: [],
      selfRevisionPatchCount: 0,
      selfRevisionMemoryPolicyBias: 0,
      selfRevisionRelationshipPostureBias: 0,
      selfRevisionResponsePostureBias: 0,
      selfRevisionProactivePolicyBias: 0,
      selfRevisionValidationBias: 0,
      selfRevisionReasonCodes: [],
      selfEvolutionVersionCandidateCount: 0,
      selfEvolutionActiveCandidateCount: 0,
      selfEvolutionShadowCandidateCount: 0,
      selfEvolutionRejectedCandidateCount: 0,
      selfEvolutionRolledBackCandidateCount: 0,
      selfEvolutionReplayRequiredCount: 0,
      selfEvolutionReplayPassedCount: 0,
      selfEvolutionReasonCodes: [],
      relationshipCadenceRegressionRate: 0,
      selfModelStaleBeliefRate: 0,
      lastUpdatedAt: 123,
    })
    expect(defaultAlicizationMemoryRetrievalTelemetry()).toEqual({
      semanticLatencyMs: null,
      semanticSampleCount: 0,
      graphLatencyMs: null,
      graphSampleCount: 0,
      candidateGenerationLatencyMs: null,
      candidateGenerationSampleCount: 0,
      plannerLatencyMs: null,
      plannerSampleCount: 0,
      speechPlanLatencyMs: null,
      speechPlanSampleCount: 0,
      cacheHitCount: 0,
      cacheMissCount: 0,
      prewarmHitCount: 0,
      prewarmMissCount: 0,
      budgetClassCounts: {},
      budgetLatencyTelemetry: {},
      budgetLatencySamples: {},
      organicStageTelemetry: {},
      organicStageBudgetCounts: {},
      hotKeyStats: [],
      recallHitRate: 0,
      recallMissRate: 0,
      recallAt1: 0,
      recallAt3: 0,
      precisionAt3: 0,
      wrongThreadRate: 0,
      wrongThreadSuppression: 0,
      suppressionHitRate: 0,
      wrongThreadPreventedCount: 0,
      falsePositiveSuppressionRate: 0,
      staleSelfModelVetoRate: 0,
      relationshipEraConfusionRate: 0,
      reconstructionErrorRate: 0,
      stableCoreOnlyRate: 0,
      memorySurfaceViolationRate: 0,
      templateLeakageFailCount: 0,
      claimAccuracy: 0,
      replyAuthorityAccuracy: 0,
      latencyBudgetPass: null,
      mindParticipation: 0,
      memoryParticipation: 0,
      personalityParticipation: 0,
      relationshipParticipation: 0,
      continuityParticipation: 0,
      learningTaskCompletionCount: 0,
      learningTaskCompletionRate: 0,
      learningTaskFailureCount: 0,
      learningTaskFailureRate: 0,
      learningTaskBlockedCount: 0,
      learningTaskReopenedCount: 0,
      learningTaskReopenRecoveryRate: 0,
      learningTaskDowngradedCount: 0,
      learningTaskCancelledCount: 0,
      learningRelationshipReviseCount: 0,
      learningSelfModelReviseCount: 0,
      learningWorldModelValidationCount: 0,
      learningWorldModelFalseInternalizationCount: 0,
      misinternalizationRate: 0,
      sampleCount: 0,
      learningPolicyStrictnessBias: 0,
      learningPolicyWrongThreadSuppressionBias: 0,
      learningPolicyProvenanceLabelBias: 0,
      learningPolicyReasonCodes: [],
      selfRevisionPatchCount: 0,
      selfRevisionMemoryPolicyBias: 0,
      selfRevisionRelationshipPostureBias: 0,
      selfRevisionResponsePostureBias: 0,
      selfRevisionProactivePolicyBias: 0,
      selfRevisionValidationBias: 0,
      selfRevisionReasonCodes: [],
      selfEvolutionVersionCandidateCount: 0,
      selfEvolutionActiveCandidateCount: 0,
      selfEvolutionShadowCandidateCount: 0,
      selfEvolutionRejectedCandidateCount: 0,
      selfEvolutionRolledBackCandidateCount: 0,
      selfEvolutionReplayRequiredCount: 0,
      selfEvolutionReplayPassedCount: 0,
      selfEvolutionReasonCodes: [],
      relationshipCadenceRegressionRate: 0,
      selfModelStaleBeliefRate: 0,
      lastUpdatedAt: null,
    })
  })

  it('blends retrieval latency and applies override through runtime meta storage', async () => {
    const meta = new Map<string, string>()
    const runtime = createAlicizationMemoryRetrievalTelemetryRuntime({
      now: () => 100,
      key: 'telemetry',
      getMetaValue: async key => meta.get(key),
      upsertMeta: async (key, value) => {
        meta.set(key, value)
      },
      enqueueWrite: async task => await task(),
    })

    expect(blendAlicizationMemoryTelemetryLatency(10, 2, 16)).toBeCloseTo(12)

    await runtime.recordSemanticLatency(12)
    await runtime.recordSemanticLatency(18)
    await runtime.recordGraphLatency(20)
    await runtime.recordCandidateGenerationLatency(11)
    await runtime.recordPlannerLatency(13)
    await runtime.recordSpeechPlanLatency(17)
    await runtime.recordOrganicStageLatency({
      stage: 'candidate-ranking',
      latencyMs: 19,
    })
    await runtime.recordOrganicStageBudget({
      stage: 'candidate-ranking',
      budgetClass: 'deep-recall-reply',
    })
    await runtime.recordLearningExecution({
      status: 'completed',
      domain: 'relationship',
    })
    await runtime.recordLearningExecution({
      status: 'completed',
      domain: 'world-model',
      internalizedAsValidatedOnly: true,
      policyFeedback: {
        strictnessBias: 0.3,
        wrongThreadSuppressionBias: 0.22,
        provenanceLabelBias: 0.4,
        reasonCodes: ['state:verification', 'result:completed', 'domain:world-model'],
      },
      selfEvolutionVersionCandidate: {
        status: 'shadow',
        validation: {
          replayRequired: true,
          replayPassed: null,
          rollbackSupported: true,
          activationBlockedReasons: ['self-evolution:shadow-replay-required'],
        },
      },
    })
    await runtime.recordLearningExecution({
      status: 'failed',
    })
    await runtime.recordCacheAccess(true)
    await runtime.recordCacheAccess(false)
    await runtime.recordPrewarmAccess(true)
    await runtime.applyHealthOverride({
      semanticLatencyMs: 15,
      graphLatencyMs: 22,
      candidateGenerationLatencyMs: 14,
      plannerLatencyMs: 16,
      speechPlanLatencyMs: 18,
      cacheHitRatio: 0.5,
      prewarmHitRatio: 1,
      recallHitRate: 0.8,
      recallMissRate: 0.2,
      recallAt1: 1,
      recallAt3: 0.8,
      precisionAt3: 0.67,
      wrongThreadRate: 0.1,
      wrongThreadSuppression: 0.9,
      suppressionHitRate: 0.6,
      wrongThreadPreventedCount: 3,
      falsePositiveSuppressionRate: 0.2,
      staleSelfModelVetoRate: 0.25,
      relationshipEraConfusionRate: 0.5,
      reconstructionErrorRate: 0.25,
      stableCoreOnlyRate: 0.75,
      memorySurfaceViolationRate: 0.15,
      templateLeakageFailCount: 3,
      claimAccuracy: 0.88,
      replyAuthorityAccuracy: 1,
      latencyBudgetPass: true,
    })

    expect(await runtime.getTelemetry()).toEqual({
      semanticLatencyMs: 15,
      semanticSampleCount: 2,
      graphLatencyMs: 22,
      graphSampleCount: 1,
      candidateGenerationLatencyMs: 14,
      candidateGenerationSampleCount: 1,
      plannerLatencyMs: 16,
      plannerSampleCount: 1,
      speechPlanLatencyMs: 18,
      speechPlanSampleCount: 1,
      cacheHitCount: 1,
      cacheMissCount: 1,
      prewarmHitCount: 1,
      prewarmMissCount: 0,
      budgetClassCounts: {
        'realtime-reply': 0,
        'deep-recall-reply': 0,
        'proactive-generation': 0,
        'nightly-benchmark': 0,
        'diagnosis-replay': 0,
      },
      budgetLatencyTelemetry: {
        'realtime-reply': { sampleCount: 1, p50LatencyMs: 19, p95LatencyMs: 19, maxLatencyMs: 19, gateStatus: 'pass', targetP95Ms: 900 },
        'deep-recall-reply': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 2200 },
        'proactive-generation': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 750 },
        'nightly-benchmark': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 5000 },
        'diagnosis-replay': { sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null, maxLatencyMs: null, gateStatus: 'unknown', targetP95Ms: 3600 },
      },
      budgetLatencySamples: {
        'realtime-reply': [19],
        'deep-recall-reply': [],
        'proactive-generation': [],
        'nightly-benchmark': [],
        'diagnosis-replay': [],
      },
      organicStageTelemetry: {
        'search-prelude': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'candidate-generation': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'candidate-ranking': { latencyMs: 19, sampleCount: 1, p50LatencyMs: 19, p95LatencyMs: 19 },
        'recollection-planning': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'surface-planning': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'self-evolution-integration': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
        'prompt-blocks': { latencyMs: null, sampleCount: 0, p50LatencyMs: null, p95LatencyMs: null },
      },
      organicStageBudgetCounts: {
        'search-prelude': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'candidate-generation': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'candidate-ranking': { 'realtime-reply': 0, 'deep-recall-reply': 1, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'recollection-planning': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'surface-planning': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'self-evolution-integration': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
        'prompt-blocks': { 'realtime-reply': 0, 'deep-recall-reply': 0, 'proactive-generation': 0, 'nightly-benchmark': 0, 'diagnosis-replay': 0 },
      },
      hotKeyStats: [],
      recallHitRate: 0.8,
      recallMissRate: 0.2,
      recallAt1: 1,
      recallAt3: 0.8,
      precisionAt3: 0.67,
      wrongThreadRate: 0.1,
      wrongThreadSuppression: 0.9,
      suppressionHitRate: 0.6,
      wrongThreadPreventedCount: 3,
      falsePositiveSuppressionRate: 0.2,
      staleSelfModelVetoRate: 0.25,
      relationshipEraConfusionRate: 0.5,
      reconstructionErrorRate: 0.25,
      stableCoreOnlyRate: 0.75,
      memorySurfaceViolationRate: 0.15,
      templateLeakageFailCount: 3,
      claimAccuracy: 0.88,
      replyAuthorityAccuracy: 1,
      latencyBudgetPass: true,
      mindParticipation: 0,
      memoryParticipation: 0,
      personalityParticipation: 0,
      relationshipParticipation: 0,
      continuityParticipation: 0,
      learningTaskCompletionCount: 2,
      learningTaskCompletionRate: 0.67,
      learningTaskFailureCount: 1,
      learningTaskFailureRate: 0.33,
      learningTaskBlockedCount: 0,
      learningTaskReopenedCount: 0,
      learningTaskReopenRecoveryRate: 0,
      learningTaskDowngradedCount: 0,
      learningTaskCancelledCount: 0,
      learningRelationshipReviseCount: 1,
      learningSelfModelReviseCount: 0,
      learningWorldModelValidationCount: 1,
      learningWorldModelFalseInternalizationCount: 0,
      misinternalizationRate: 0,
      sampleCount: 0,
      learningPolicyStrictnessBias: 0.3,
      learningPolicyWrongThreadSuppressionBias: 0.22,
      learningPolicyProvenanceLabelBias: 0.4,
      learningPolicyReasonCodes: ['state:verification', 'result:completed', 'domain:world-model'],
      selfRevisionPatchCount: 0,
      selfRevisionMemoryPolicyBias: 0,
      selfRevisionRelationshipPostureBias: 0,
      selfRevisionResponsePostureBias: 0,
      selfRevisionProactivePolicyBias: 0,
      selfRevisionValidationBias: 0,
      selfRevisionReasonCodes: [],
      selfEvolutionVersionCandidateCount: 1,
      selfEvolutionActiveCandidateCount: 0,
      selfEvolutionShadowCandidateCount: 1,
      selfEvolutionRejectedCandidateCount: 0,
      selfEvolutionRolledBackCandidateCount: 0,
      selfEvolutionReplayRequiredCount: 1,
      selfEvolutionReplayPassedCount: 0,
      selfEvolutionReasonCodes: [
        'self-evolution:status:shadow',
        'self-evolution:replay-required',
        'self-evolution:rollback-supported',
        'self-evolution:shadow-replay-required',
      ],
      relationshipCadenceRegressionRate: 0,
      selfModelStaleBeliefRate: 0,
      lastUpdatedAt: 100,
    })
  })
})
