import { describe, expect, it } from 'vitest'

import {
  buildMemoryConsolidationRecords,
  searchMemoryConsolidationRecords,
} from './memory-consolidation'

describe('memory consolidation', () => {
  it('builds autobiographical era summaries from multiple episodic events', () => {
    const records = buildMemoryConsolidationRecords({
      now: Date.UTC(2026, 3, 20, 12, 0, 0),
      events: [
        {
          id: 'event-relationship-1',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-relationship-1',
          sessionId: 'session-relationship-1',
          sourceKind: 'dialogue-feedback',
          provenance: 'remembered',
          occurredAt: Date.UTC(2026, 3, 18, 8, 0, 0),
          whereSummary: 'focused work boundary',
          withWhom: ['host'],
          threadAnchor: 'focused work boundary',
          whatHappened: 'The host needed more room before closeness during focused work.',
          felt: 'careful',
          emotionTags: ['boundary'],
          whatChanged: 'burden dropped once the reply backed off.',
          relationshipMeaning: 'Back off first, then reopen with a lighter touch.',
          lesson: 'Focused windows need more room before closeness.',
          sourceSummary: 'relationship repair period',
          confidence: 0.84,
          salience: 0.82,
          sceneAttachment: 0.34,
          consolidationPriority: 0.76,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['focused-work', 'lighter-touch'],
          createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
          updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
        },
        {
          id: 'event-relationship-2',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-relationship-2',
          sessionId: 'session-relationship-2',
          sourceKind: 'reply',
          provenance: 'observed',
          occurredAt: Date.UTC(2026, 3, 19, 8, 0, 0),
          whereSummary: 'bond repair seam',
          withWhom: ['host'],
          threadAnchor: 'bond repair seam',
          whatHappened: 'The answer landed better once Alicization gave more room before leaning closer.',
          felt: 'relieved',
          emotionTags: ['repair'],
          whatChanged: 'trust rose once the reply stopped pressing in.',
          relationshipMeaning: 'Space before closeness keeps the bond steadier here.',
          lesson: 'Repair should land before warmth expands.',
          sourceSummary: 'reply repair period',
          confidence: 0.82,
          salience: 0.8,
          sceneAttachment: 0.3,
          consolidationPriority: 0.74,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['bond-repair', 'lighter-touch'],
          createdAt: Date.UTC(2026, 3, 19, 8, 30, 0),
          updatedAt: Date.UTC(2026, 3, 19, 8, 30, 0),
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
        },
        {
          id: 'event-task-1',
          cardId: 'default',
          decisionTraceId: null,
          turnId: 'turn-task-1',
          sessionId: 'session-task-1',
          sourceKind: 'execution-result',
          provenance: 'observed',
          occurredAt: Date.UTC(2026, 3, 19, 10, 0, 0),
          whereSummary: 'runtime continuity thread',
          withWhom: ['host'],
          threadAnchor: 'runtime continuity',
          whatHappened: 'We kept returning to the runtime seam until the flow stabilized.',
          felt: 'focused',
          emotionTags: ['focused'],
          whatChanged: 'trust up 0.04',
          relationshipMeaning: 'Carry the same runtime seam before branching.',
          lesson: 'Return to the same seam before branching.',
          sourceSummary: 'runtime continuity repair',
          confidence: 0.86,
          salience: 0.84,
          sceneAttachment: 0.32,
          consolidationPriority: 0.74,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['runtime-seam'],
          createdAt: Date.UTC(2026, 3, 19, 10, 30, 0),
          updatedAt: Date.UTC(2026, 3, 19, 10, 30, 0),
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
        },
        {
        id: 'event-task-2',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-task-2',
        sessionId: 'session-task-2',
        sourceKind: 'execution-result',
        provenance: 'remembered',
        occurredAt: Date.UTC(2026, 3, 19, 12, 0, 0),
          whereSummary: 'runtime continuity thread',
          withWhom: ['host'],
          threadAnchor: 'runtime continuity',
          whatHappened: 'The safest way through the runtime seam was still patch then verify.',
          felt: 'steady',
          emotionTags: ['focused'],
          whatChanged: 'the task line stayed coherent.',
          relationshipMeaning: 'Stay on the same seam before branching.',
          lesson: 'Patch and verify before branching.',
          sourceSummary: 'runtime continuity procedure',
          confidence: 0.84,
          salience: 0.82,
          sceneAttachment: 0.3,
          consolidationPriority: 0.72,
          relationshipShift: null,
          derivedFrom: [],
          tags: ['runtime-seam', 'procedure-learning'],
          createdAt: Date.UTC(2026, 3, 19, 12, 30, 0),
          updatedAt: Date.UTC(2026, 3, 19, 12, 30, 0),
          lastRecalledAt: null,
          recallCount: 0,
          reconsolidationCount: 0,
          latestReconsolidation: null,
        },
      ],
    })

    expect(records).toEqual(expect.arrayContaining([
      expect.objectContaining({
        kind: 'autobiographical',
        facet: 'relationship-era',
        summary: expect.stringContaining('relationship era'),
        cues: expect.arrayContaining(['Back off first, then reopen with a lighter touch.']),
      }),
      expect.objectContaining({
        kind: 'autobiographical',
        facet: 'task-era',
        summary: expect.stringContaining('task era'),
        cues: expect.arrayContaining(['runtime continuity']),
      }),
      expect.objectContaining({
        kind: 'autobiographical',
        facet: 'phase',
      }),
    ]))
  })

  it('prefers autobiographical era records that match recollection intent', () => {
    const rows = searchMemoryConsolidationRecords({
      query: '为什么你这次会这样回应我',
      records: [
        {
          id: 'autobio:relationship-era:2026-W16',
          kind: 'autobiographical',
          facet: 'relationship-era',
          periodKey: '2026-W16',
          periodStartedAt: Date.UTC(2026, 3, 14, 0, 0, 0),
          periodEndedAt: Date.UTC(2026, 3, 20, 0, 0, 0),
          summary: 'During 2026-W16, the dominant relationship era centered on giving more room before closeness.',
          lesson: 'Focused windows need more room before closeness.',
          cues: ['focused work', 'lighter touch'],
          confidence: 0.86,
          dominantProvenance: 'remembered',
          derivedEventIds: ['episode-relationship-1', 'episode-relationship-2'],
          updatedAt: Date.UTC(2026, 3, 20, 12, 0, 0),
        },
        {
          id: 'autobio:task-era:2026-W16',
          kind: 'autobiographical',
          facet: 'task-era',
          periodKey: '2026-W16',
          periodStartedAt: Date.UTC(2026, 3, 14, 0, 0, 0),
          periodEndedAt: Date.UTC(2026, 3, 20, 0, 0, 0),
          summary: 'During 2026-W16, the dominant task era centered on returning to the same runtime seam before branching.',
          lesson: 'Patch and verify before branching.',
          cues: ['runtime continuity', 'procedure-learning'],
          confidence: 0.84,
          dominantProvenance: 'remembered',
          derivedEventIds: ['episode-task-1', 'episode-task-2'],
          updatedAt: Date.UTC(2026, 3, 20, 12, 0, 0),
        },
      ],
      recollectionIntent: {
        mode: 'relationship-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['focused work', 'lighter touch'],
        rationale: 'Long-range relationship history should start from the right era.',
        confidence: 0.82,
      },
    })

    expect(rows[0]?.facet).toBe('relationship-era')
  })

  it('uses semantic and graph cues to surface the right task-era even when the recall wording changes', () => {
    const rows = searchMemoryConsolidationRecords({
      query: '继续把那条断掉的线接回去',
      records: [
        {
          id: 'autobio:task-era:runtime',
          kind: 'autobiographical',
          facet: 'task-era',
          periodKey: 'runtime-seam',
          periodStartedAt: Date.UTC(2026, 3, 18, 8, 0, 0),
          periodEndedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
          summary: 'That task era kept turning back to the runtime seam until it stabilized.',
          lesson: 'Return to the same seam before branching.',
          cues: ['runtime seam', 'repair rhythm'],
          confidence: 0.78,
          dominantProvenance: 'remembered',
          derivedEventIds: ['episode-seam', 'episode-handoff'],
          updatedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
          memoryTier: 'warm',
        },
        {
          id: 'autobio:phase:other',
          kind: 'autobiographical',
          facet: 'phase',
          periodKey: 'other-phase',
          periodStartedAt: Date.UTC(2026, 3, 17, 8, 0, 0),
          periodEndedAt: Date.UTC(2026, 3, 17, 10, 0, 0),
          summary: 'That phase was mostly about a general dashboard cleanup.',
          lesson: 'Keep the UI tidy.',
          cues: ['dashboard', 'cleanup'],
          confidence: 0.8,
          dominantProvenance: 'remembered',
          derivedEventIds: ['episode-other'],
          updatedAt: Date.UTC(2026, 3, 17, 10, 0, 0),
          memoryTier: 'warm',
        },
      ],
      recollectionIntent: {
        mode: 'experience-pattern',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['return before branching', 'runtime seam'],
        rationale: 'The host is asking to reconnect the same task line.',
        confidence: 0.82,
      },
    })

    expect(rows[0]?.id).toBe('autobio:task-era:runtime')
  })
})
