import { describe, expect, it } from 'vitest'

import { buildMindKernel } from './mind-kernel'

describe('buildMindKernel', () => {
  it('stays in repairing mode when the carried obligation is still regrounding', () => {
    const kernel = buildMindKernel({
      now: 30_000,
      worldModel: {
        activeThread: {
          id: 'thread-1',
          kind: 'debugging',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts error',
          summary: 'The host is still debugging.',
          confidence: 0.74,
          significance: 0.72,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 30_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['which scene is current?'],
          staleRisks: ['continuity drift'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 2_000,
          attentionAgeMs: 2_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 30_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::repair-misread::runtime',
        commitments: [{
          id: 'commitment::repair-misread::runtime',
          kind: 'repair-misread',
          status: 'active',
          title: 'Repair Misread',
          summary: 'A drift between remembered continuity and the live world is unresolved.',
          source: 'hypothesis',
          priority: 0.8,
          confidence: 0.74,
          createdAt: 0,
          lastRenewedAt: 30_000,
          patienceUntil: 60_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.62,
        narrative: [],
        updatedAt: 30_000,
      },
      inquiryPlanner: {
        activePlanId: 'inquiry-plan::reground-scene::runtime',
        plans: [{
          id: 'inquiry-plan::reground-scene::runtime',
          kind: 'reground-scene',
          status: 'tracking',
          priority: 'high',
          question: 'What is actually in front of the host right now?',
          askForGrounding: true,
          suggestedProbeMs: 8_000,
          evidenceWanted: ['fresh-scene'],
          createdAt: 0,
          lastUpdatedAt: 30_000,
          expiresAt: 120_000,
        }],
        epistemicPressure: 0.76,
        groundingUrgency: 0.74,
        narrative: [],
        updatedAt: 30_000,
      },
      mindDynamics: {
        dominantMotive: 'clarify',
        worldPressure: 0.62,
        epistemicPressure: 0.78,
        relationalPressure: 0.28,
        carePressure: 0.24,
        continuityPressure: 0.58,
        restraintPressure: 0.64,
        surfacePressure: 0.34,
        speakReadiness: 0.28,
        presenceWeight: 0.42,
        motives: {
          'clarify': 0.82,
          'stay-silent': 0.68,
        },
        speakDrive: 0.32,
        silenceDrive: 0.74,
        narrative: ['dominant motive is clarify.'],
        updatedAt: 30_000,
      },
      beliefRevision: {
        dominantBeliefId: null,
        stability: 'fractured',
        revisionPressure: 0.74,
        groundingNeed: 0.72,
        contradictionPressure: 0.68,
        hostCorrectionWeight: 0.4,
        narrative: [],
        updatedAt: 30_000,
      },
      selfState: {
        stance: 'hesitate',
        feltCloseness: 0.52,
        protectiveness: 0.3,
        curiosity: 0.7,
        patience: 0.78,
        desireToSpeak: 0.34,
        fearOfInterrupting: 0.62,
        dominantConcernId: null,
        moodLabel: 'repairing-confidence',
      },
    })

    expect(kernel.dominantMode).toBe('repairing')
    expect(kernel.epistemicPressure).toBeGreaterThan(0.6)
  })

  it('switches into guarding mode when care pressure overtakes everything else', () => {
    const kernel = buildMindKernel({
      now: 30_000,
      worldModel: {
        activeThread: {
          id: 'thread-2',
          kind: 'late-night-endurance',
          status: 'active',
          source: 'continuity',
          title: 'late-night session',
          summary: 'The host is still pushing through late-night fatigue.',
          confidence: 0.82,
          significance: 0.72,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 30_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 30_000,
          attentionAgeMs: 30_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'fatigued',
          burden: 'heavy',
        },
        updatedAt: 30_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::care-host::late-night',
        commitments: [{
          id: 'commitment::care-host::late-night',
          kind: 'care-host',
          status: 'active',
          title: 'Care Host',
          summary: 'The host may need care more than commentary right now.',
          source: 'continuity',
          priority: 0.82,
          confidence: 0.76,
          createdAt: 0,
          lastRenewedAt: 30_000,
          patienceUntil: 60_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.68,
        narrative: [],
        updatedAt: 30_000,
      },
      inquiryPlanner: {
        activePlanId: 'inquiry-plan::verify-care::late-night',
        plans: [{
          id: 'inquiry-plan::verify-care::late-night',
          kind: 'verify-care',
          status: 'tracking',
          priority: 'high',
          question: 'Does the host need a care nudge right now?',
          askForGrounding: false,
          suggestedProbeMs: 18_000,
          evidenceWanted: ['fatigue-trend'],
          createdAt: 0,
          lastUpdatedAt: 30_000,
          expiresAt: 120_000,
        }],
        epistemicPressure: 0.44,
        groundingUrgency: 0.18,
        narrative: [],
        updatedAt: 30_000,
      },
      mindDynamics: {
        dominantMotive: 'care',
        worldPressure: 0.54,
        epistemicPressure: 0.32,
        relationalPressure: 0.44,
        carePressure: 0.86,
        continuityPressure: 0.62,
        restraintPressure: 0.28,
        surfacePressure: 0.72,
        speakReadiness: 0.58,
        presenceWeight: 0.68,
        motives: {
          care: 0.88,
          protect: 0.76,
        },
        speakDrive: 0.74,
        silenceDrive: 0.32,
        narrative: ['dominant motive is care.'],
        updatedAt: 30_000,
      },
      selfState: {
        stance: 'protect',
        feltCloseness: 0.62,
        protectiveness: 0.84,
        curiosity: 0.34,
        patience: 0.58,
        desireToSpeak: 0.64,
        fearOfInterrupting: 0.28,
        dominantConcernId: null,
        moodLabel: 'protective-tension',
      },
    })

    expect(kernel.dominantMode).toBe('guarding')
    expect(kernel.carePressure).toBeGreaterThan(0.7)
    expect(kernel.speakReadiness).toBeGreaterThan(0.3)
  })
})
