import { describe, expect, it } from 'vitest'

import { createAlicizationContinuityMind } from './continuity-mind'
import { buildCurrentConsciousFrame } from './current-conscious-frame'
import { stabilizeMindStateInvariants } from './mind-state-invariants'
import { buildPrivateThoughtLoop } from './private-thought-loop'

describe('stabilizeMindStateInvariants', () => {
  it('synthesizes living world, governor, and thought thread when live world exists but slices collapse', () => {
    const stabilized = stabilizeMindStateInvariants({
      now: 120_000,
      watchMode: 'symbiotic-vision',
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'error',
        scenario: 'coding',
        summary: 'TypeScript error in runtime.ts',
        source: 'screen-semantic-summary',
        confidence: 0.94,
        target: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'runtime.ts - TypeScript error',
          pid: 7,
        },
        beganAt: 60_000,
        lastSeenAt: 120_000,
      },
      worldModel: {
        activeThread: {
          id: 'debugging::runtime.ts',
          kind: 'debugging',
          status: 'active',
          source: 'grounded-scene',
          title: 'TypeScript error in runtime.ts',
          summary: 'The host is pinned on a TypeScript error in runtime.ts.',
          confidence: 0.92,
          significance: 0.74,
          unresolved: true,
          beganAt: 60_000,
          lastUpdatedAt: 120_000,
          target: {
            appName: 'Cursor',
            processName: 'Cursor',
            title: 'runtime.ts - TypeScript error',
            pid: 7,
          },
        },
        lingeringThreads: [],
        focusTarget: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'runtime.ts - TypeScript error',
          pid: 7,
        },
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['scene:TypeScript error in runtime.ts'],
          inferredNow: ['thread:debugging'],
          openQuestions: ['What exactly is failing in the current error?'],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 60_000,
          attentionAgeMs: 60_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 120_000,
      },
      livingWorldState: null,
      relationshipModel: null,
      selfGovernor: null,
      thoughtThreads: null,
      privateThought: null,
    })

    expect(stabilized.livingWorldState?.focusObjectId).toBeTruthy()
    expect(stabilized.livingWorldState?.objects.length).toBeGreaterThan(0)
    expect(stabilized.selfGovernor?.dominantDrive).toBeTruthy()
    expect(stabilized.selfGovernor?.activeIntentions.length).toBeGreaterThan(0)
    expect(stabilized.thoughtThreads?.foregroundThreadId).toBeTruthy()
    expect(stabilized.thoughtThreads?.threads.length).toBeGreaterThan(0)
  })

  it('keeps empty slices empty when no live world anchor exists', () => {
    const stabilized = stabilizeMindStateInvariants({
      now: 1_000,
      watchMode: 'mnemonic-passive',
      currentScene: null,
      worldModel: null,
      livingWorldState: null,
      relationshipModel: null,
      selfGovernor: null,
      thoughtThreads: null,
      privateThought: null,
    })

    expect(stabilized.livingWorldState).toBeNull()
    expect(stabilized.selfGovernor).toBeNull()
    expect(stabilized.thoughtThreads).toBeNull()
  })
})

describe('continuity mind', () => {
  it('maintains a subjective present during prolonged silence', () => {
    const mind = createAlicizationContinuityMind()
    const state = mind.reduce({
      quietLineMs: 240000,
      bodyState: 'accompanying',
      latestThreadSummary: 'host sustained focus on coding task',
      relationshipPressure: 0.38,
      latestUserTurnAt: 1000,
      now: 241000,
    })

    expect(state.subjectiveNowSummary).toContain('focus')
    expect(state.privateThoughtMode).toBe('quiet-companionship')
    expect(state.shouldForceSpeech).toBe(false)
  })

  it('treats accompanying stance as continuity companionship', () => {
    const mind = createAlicizationContinuityMind()
    const state = mind.reduce({
      quietLineMs: 180000,
      bodyState: 'accompanying',
      latestThreadSummary: 'host staying with a coding thread',
      relationshipPressure: 0.4,
      latestUserTurnAt: null,
      now: 180000,
    })

    expect(state.privateThoughtMode).toBe('quiet-companionship')
    expect(state.subjectiveNowSummary).toContain('coding thread')
  })

  it('blocks quiet companionship when the latest user turn is still recent', () => {
    const mind = createAlicizationContinuityMind()
    const state = mind.reduce({
      quietLineMs: 240000,
      bodyState: 'accompanying',
      latestThreadSummary: 'host sustained focus on coding task',
      relationshipPressure: 0.38,
      latestUserTurnAt: 210000,
      now: 241000,
    })

    expect(state.privateThoughtMode).toBe('ambient-watch')
    expect(state.subjectiveNowSummary).toContain('focus')
  })

  it('does not treat reducer refresh timestamps as user-turn timing', () => {
    const mind = createAlicizationContinuityMind()
    const state = mind.reduce({
      quietLineMs: 240000,
      bodyState: 'accompanying',
      latestThreadSummary: 'host sustained focus on coding task',
      relationshipPressure: 0.38,
      latestUserTurnAt: null,
      now: 241000,
    })

    expect(state.privateThoughtMode).toBe('quiet-companionship')
    expect(state.subjectiveNowSummary).toContain('focus')
  })

  it('does not fabricate quiet companionship from future thought expiry alone', () => {
    const thought = buildPrivateThoughtLoop({
      now: 180000,
      context: {
        localTime: {
          hour: 15,
          minute: 0,
          isLateNight: false,
        },
        system: {
          cpuUsage: 0.2,
          battery: {
            percent: 90,
            charging: true,
          },
          memory: {
            usagePercent: 32,
            freeMB: 4096,
            totalMB: 8192,
          },
          idleSeconds: 0,
          inputActivity: 'active',
          fullscreenLikely: false,
          degradedSignals: [],
        },
        workload: {
          kind: 'coding',
          confidence: 0.9,
          source: 'screen-semantic-summary',
          matchedLabels: ['cursor'],
        },
        content: {
          kind: 'doc',
          confidence: 0.7,
          source: 'screen-semantic-summary',
          matchedLabels: ['doc'],
          summary: 'notes',
        },
        relationship: {
          hostAttitude: 'focused',
          boredom: 15,
          loneliness: 18,
          fatigue: 12,
          minutesSinceLastUserTurn: 0,
          reminderBacklog: 0,
          lateNightActiveMinutes: 0,
          recentProactiveOutcomes: [],
        },
      },
      watchMode: 'symbiotic-vision',
      currentScene: {
        workloadKind: 'coding',
        contentKind: 'doc',
        scenario: 'coding',
        summary: 'host staying with docs',
        source: 'screen-semantic-summary',
        confidence: 0.92,
        target: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'notes.md',
          pid: 7,
        },
        beganAt: 179500,
        lastSeenAt: 180000,
      },
      attention: null,
      recentTransition: null,
      worldModel: {
        activeThread: {
          id: 'thread-1',
          kind: 'deep-focus',
          status: 'active',
          source: 'grounded-scene',
          title: 'Notes review',
          summary: 'host staying with docs',
          confidence: 0.86,
          significance: 0.62,
          unresolved: false,
          beganAt: 179500,
          lastUpdatedAt: 180000,
        },
        lingeringThreads: [],
        focusTarget: {
          appName: 'Cursor',
          processName: 'Cursor',
          title: 'notes.md',
          pid: 7,
        },
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['scene:host staying with docs'],
          inferredNow: ['thread:deep-focus'],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 500,
          attentionAgeMs: 500,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'light',
        },
        updatedAt: 180000,
      },
      relationshipModel: {
        climate: 'neutral',
        approachVector: 'stay-near',
        receptivity: 0.5,
        sharedAttentionTrust: 0.55,
        correctionSensitivity: 0.3,
        reciprocityExpectation: 0.48,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 180000,
      },
      mindKernel: {
        dominantMode: 'accompanying',
        governingHypothesisId: null,
        governingRuntimeThreadId: null,
        governingCommitmentId: null,
        governingInquiryPlanId: null,
        governingIntentionId: null,
        dominantDrive: 'withhold',
        worldPressure: 0.3,
        epistemicPressure: 0.1,
        relationalPressure: 0.45,
        carePressure: 0.2,
        continuityPressure: 0.6,
        speakReadiness: 0.2,
        presenceWeight: 0.8,
        narrative: [],
        updatedAt: 180000,
      },
      initiative: {
        selectedAction: 'hover',
        selectedProposalId: null,
        selectedTruthFrame: null,
        selectedCounterfactualOptionId: null,
        selectedConcernId: null,
        selectedBeliefId: null,
        selectedInquiryId: null,
        selectedCommitmentId: null,
        selectedInquiryPlanId: null,
        selectedHypothesisId: null,
        selectedThreadId: null,
        selectedRuntimeThreadId: null,
        selectedThoughtThreadId: null,
        selectedGovernorIntentionId: null,
        actionEcologyMode: 'quiet-accompany',
        confidence: 0.7,
        motives: {},
        speakDrive: 0.2,
        silenceDrive: 0.8,
        preferredStyle: 'silent-observe',
        preferredPresence: 'attentive',
        why: 'Stay nearby without interrupting.',
        shouldSurface: false,
        shouldSpeak: false,
      },
      previousPrivateThought: null,
    })

    expect(thought.thoughtText).not.toContain('Still quietly accompanying')
    expect(thought.rationaleTags).not.toContain('continuity-mind:quiet-companionship')
  })

  it('does not let conscious-frame companionship silently force defer without a true user-turn signal', () => {
    const frame = buildCurrentConsciousFrame({
      now: 241000,
      discourseState: {
        currentTurnSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        currentTurnSummary: 'host is still inside the coding thread',
        currentQuestion: 'what should happen next?',
        primaryTurnAnchor: 'coding thread',
        primaryTurnAnchorSource: 'thread',
        owedAction: 'guide-task',
        relationMove: 'guide',
        continuityMode: 'task-first',
        unresolvedCarry: null,
        ruptureRepair: null,
        confidence: 0.86,
        narrative: [],
        updatedAt: 241000,
      },
      conversationState: {
        jointThread: 'host is still inside the coding thread',
        hostMove: 'kept working through the task',
        primaryTurnAnchor: 'coding thread',
        primaryTurnAnchorSource: 'thread',
        activeProject: 'Task 4',
        unansweredQuestion: 'what should happen next?',
        owedRepair: null,
        activeCommitments: ['continue the task'],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: [],
        shouldHoldThread: true,
        carryEligible: true,
        carryReason: 'same live task',
        confidence: 0.88,
        narrative: [],
        updatedAt: 241000,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        speechObligation: 'guide-task',
        relationMove: 'guide',
        turnMode: 'guide-current-knot',
        responseMode: 'answer-naturally',
        replyRealizationMode: null,
        expectedVisibleReplyAuthority: 'llm-mind',
        recommendedAct: 'guide',
        evidenceMode: 'live-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        activeClosenessContext: 'focused-work',
        activeClosenessRung: 'nearby-soft',
        openingDirective: 'stay with the task',
        openingClaim: 'the host is still inside the same coding thread',
        supportingReality: ['coding thread remains active'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'continue the task',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 3,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.9,
        narrative: [],
        updatedAt: 241000,
      },
      privateThought: {
        stance: 'accompany',
        confidence: 0.72,
        rationaleTags: ['continuity-ready'],
        thoughtText: 'I can stay near this moment without pressing into it.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 331000,
        afterglowFromScenario: null,
        emotionalTension: 'soft-covision',
        selectedConcernId: null,
        focusBeliefId: null,
        focusInquiryId: null,
        commitmentId: null,
        inquiryPlanId: null,
        hypothesisId: null,
        deliberationThreadId: null,
        runtimeThreadId: null,
        mindNeed: null,
        relationshipVector: 'stay-near',
        counterfactualOptionId: null,
        leadingGoalId: null,
        desireId: null,
        governorDrive: null,
        governorIntentionId: null,
        selectedThoughtThreadId: null,
        livingWorldObjectId: null,
      },
      initiative: {
        selectedAction: 'speak',
        selectedProposalId: null,
        selectedTruthFrame: null,
        selectedCounterfactualOptionId: null,
        selectedConcernId: null,
        selectedBeliefId: null,
        selectedInquiryId: null,
        selectedCommitmentId: null,
        selectedInquiryPlanId: null,
        selectedHypothesisId: null,
        selectedThreadId: null,
        selectedRuntimeThreadId: null,
        selectedThoughtThreadId: null,
        selectedGovernorIntentionId: null,
        actionEcologyMode: null,
        confidence: 0.7,
        motives: {},
        speakDrive: 0.8,
        silenceDrive: 0.2,
        preferredStyle: 'light-nudge',
        preferredPresence: 'attentive',
        why: 'continue helping on the live task',
        shouldSurface: true,
        shouldSpeak: true,
      },
      runtimeSurface: {
        version: 'digital-life-runtime-surface-v1',
        perception: {
          watchMode: 'symbiotic-vision',
          currentScene: {
            workloadKind: 'coding',
            contentKind: 'doc',
            scenario: 'coding',
            summary: 'host sustained focus on coding task',
            source: 'screen-semantic-summary',
            confidence: 0.94,
            target: {
              appName: 'Cursor',
              processName: 'Cursor',
              title: 'task-4.md',
              pid: 7,
            },
            beganAt: 1000,
            lastSeenAt: 241000,
          },
          attention: null,
          captureState: {
            permission: 'granted',
            lastGroundedAt: 241000,
          },
          durabilityPulse: null,
          recentTransition: null,
          nextSuggestedProbeMs: 15000,
          updatedAt: 241000,
        },
        world: {
          worldModel: {
            activeThread: {
              id: 'thread-1',
              kind: 'deep-focus',
              status: 'active',
              source: 'grounded-scene',
              title: 'Task 4',
              summary: 'host sustained focus on coding task',
              confidence: 0.92,
              significance: 0.7,
              unresolved: true,
              beganAt: 1000,
              lastUpdatedAt: 241000,
            },
            lingeringThreads: [],
            focusTarget: {
              appName: 'Cursor',
              processName: 'Cursor',
              title: 'task-4.md',
              pid: 7,
            },
            epistemicState: {
              certainty: 'grounded',
              freshness: 'live',
              seenNow: ['scene:host sustained focus on coding task'],
              inferredNow: ['thread:deep-focus'],
              openQuestions: [],
              staleRisks: [],
            },
            continuity: {
              label: 'staying-with-thread',
              sceneAgeMs: 240000,
              attentionAgeMs: 240000,
              sameSceneAsBefore: true,
              sameAttentionAsBefore: true,
              afterglowOpen: false,
            },
            hostState: {
              availability: 'focused',
              burden: 'moderate',
            },
            updatedAt: 241000,
          },
          worldOntology: null,
          entityWorld: null,
          livingWorldState: null,
          relationshipModel: {
            climate: 'neutral',
            approachVector: 'stay-near',
            receptivity: 0.45,
            sharedAttentionTrust: 0.46,
            correctionSensitivity: 0.3,
            reciprocityExpectation: 0.42,
            activeBoundaries: [],
            narrative: [],
            updatedAt: 241000,
          },
        },
        cognition: {
          mindTurnFrame: null,
          subjectiveInference: null,
          appraisal: null,
          beliefLedger: null,
          beliefRevision: null,
          hypothesisGraph: null,
          mindDynamics: null,
          mindKernel: {
            dominantMode: 'accompanying',
            governingHypothesisId: null,
            governingRuntimeThreadId: null,
            governingCommitmentId: null,
            governingInquiryPlanId: null,
            governingIntentionId: null,
            dominantDrive: 'withhold',
            worldPressure: 0.3,
            epistemicPressure: 0.1,
            relationalPressure: 0.45,
            carePressure: 0.2,
            continuityPressure: 0.8,
            speakReadiness: 0.2,
            presenceWeight: 0.8,
            narrative: [],
            updatedAt: 241000,
          },
          privateThought: {
            stance: 'accompany',
            confidence: 0.72,
            rationaleTags: ['continuity-ready'],
            thoughtText: 'I can stay near this moment without pressing into it.',
            shouldSpeak: true,
            suggestedStyle: 'light-nudge',
            embodiedPresence: 'attentive',
            expiresAt: 331000,
            afterglowFromScenario: null,
            emotionalTension: 'soft-covision',
            selectedConcernId: null,
            focusBeliefId: null,
            focusInquiryId: null,
            commitmentId: null,
            inquiryPlanId: null,
            hypothesisId: null,
            deliberationThreadId: null,
            runtimeThreadId: null,
            mindNeed: null,
            relationshipVector: 'stay-near',
            counterfactualOptionId: null,
            leadingGoalId: null,
            desireId: null,
            governorDrive: null,
            governorIntentionId: null,
            selectedThoughtThreadId: null,
            livingWorldObjectId: null,
          },
        },
        memory: {
          workingMemoryEpisodes: [],
          goalStack: null,
          concerns: [],
          concernContinuity: null,
          longHorizonMemory: null,
          selfContinuity: null,
          autobiographicalSelf: null,
          threadRuntime: null,
          commitmentLedger: null,
          inquiryPlanner: null,
          repairLedger: null,
          intentionStream: null,
          reflectionLedger: null,
          executiveCycle: null,
          thoughtThreads: null,
          desireMemory: null,
          recallGovernor: null,
        },
        dialogue: {
          discourseState: {
            currentTurnSubject: 'task-knot',
            screenReferenceMode: 'helpful',
            currentTurnSummary: 'host is still inside the coding thread',
            currentQuestion: 'what should happen next?',
            primaryTurnAnchor: 'coding thread',
            primaryTurnAnchorSource: 'thread',
            owedAction: 'guide-task',
            relationMove: 'guide',
            continuityMode: 'task-first',
            unresolvedCarry: null,
            ruptureRepair: null,
            confidence: 0.86,
            narrative: [],
            updatedAt: 241000,
          },
          dialogueEncounter: null,
          mindSynthesis: null,
          conversationState: {
            jointThread: 'host is still inside the coding thread',
            hostMove: 'kept working through the task',
            primaryTurnAnchor: 'coding thread',
            primaryTurnAnchorSource: 'thread',
            activeProject: 'Task 4',
            unansweredQuestion: 'what should happen next?',
            owedRepair: null,
            activeCommitments: ['continue the task'],
            relationFrame: 'guide',
            continuityPolicy: 'stay-on-thread',
            memoryMode: 'task-thread',
            memoryQueryHints: [],
            shouldHoldThread: true,
            carryEligible: true,
            carryReason: 'same live task',
            confidence: 0.88,
            narrative: [],
            updatedAt: 241000,
          },
          dialogueWorldThread: null,
          dialogueActKernel: null,
          answerCompiler: null,
          currentConsciousFrame: null,
          claimEvidenceLedger: null,
          replyDeliberation: null,
          answerPlanner: null,
        },
        agency: {
          selfState: null,
          selfGovernor: null,
          inquiryLoop: null,
          deliberationState: null,
          counterfactualDeliberation: null,
          actionEcology: null,
          initiativeArbitration: null,
          initiative: null,
          autonomy: null,
        },
      },
    })

    expect(frame?.centerOfGravity).toBe('guide')
  })
})
