import { describe, expect, it } from 'vitest'

import { buildMindContinuityFragment, buildMindContinuityRecallSeed } from './mind-continuity'

describe('mind continuity', () => {
  it('writes a searchable fragment when the inner line materially changes', () => {
    const fragment = buildMindContinuityFragment({
      previousState: {
        watchMode: 'mnemonic-passive',
        currentScene: null,
        attention: null,
        workingMemoryEpisodes: [],
        privateThought: null,
        captureState: {
          permission: 'unknown',
          lastGroundedAt: null,
        },
        durabilityPulse: null,
        recentTransition: null,
        nextSuggestedProbeMs: 10_000,
        updatedAt: 0,
      },
      nextState: {
        watchMode: 'symbiotic-vision',
        currentScene: {
          workloadKind: 'coding',
          contentKind: 'error',
          scenario: 'coding',
          summary: 'runtime.ts proactive policy error',
          source: 'screen-semantic-summary',
          confidence: 0.92,
          beganAt: 0,
          lastSeenAt: 10_000,
        },
        attention: null,
        workingMemoryEpisodes: [],
        beliefRevision: {
          dominantBeliefId: 'belief-1',
          stability: 'fractured',
          revisionPressure: 0.76,
          groundingNeed: 0.72,
          contradictionPressure: 0.64,
          hostCorrectionWeight: 0.52,
          narrative: [],
          updatedAt: 10_000,
        },
        deliberationState: {
          primaryThreadId: 'thread-1',
          dominantNeed: 'repair',
          readiness: 0.42,
          threads: [{
            id: 'thread-1',
            kind: 'repair-misread',
            status: 'holding',
            summary: 'Repair the drift before speaking.',
            desiredOutcome: 'reground the live error',
            focusBeliefId: 'belief-1',
            focusInquiryId: null,
            concernId: null,
            surfacePressure: 0.22,
            silencePressure: 0.68,
            embodiedPresence: 'hesitant',
            startedAt: 0,
            lastUpdatedAt: 10_000,
            expiresAt: 120_000,
          }],
          narrative: [],
          updatedAt: 10_000,
        },
        commitmentLedger: {
          governingCommitmentId: 'commitment::repair-misread::thread-1',
          commitments: [{
            id: 'commitment::repair-misread::thread-1',
            kind: 'repair-misread',
            status: 'active',
            title: 'Repair Misread',
            summary: 'A drift between remembered continuity and the live world is unresolved.',
            source: 'hypothesis',
            priority: 0.8,
            confidence: 0.72,
            createdAt: 0,
            lastRenewedAt: 10_000,
            patienceUntil: 40_000,
            expiresAt: 120_000,
          }],
          carryPressure: 0.6,
          narrative: [],
          updatedAt: 10_000,
        },
        inquiryPlanner: {
          activePlanId: 'inquiry-plan::reground-scene::thread-1',
          plans: [{
            id: 'inquiry-plan::reground-scene::thread-1',
            kind: 'reground-scene',
            status: 'tracking',
            priority: 'high',
            question: 'What is actually on screen now?',
            askForGrounding: true,
            suggestedProbeMs: 8_000,
            evidenceWanted: ['fresh-scene'],
            createdAt: 0,
            lastUpdatedAt: 10_000,
            expiresAt: 120_000,
          }],
          epistemicPressure: 0.74,
          groundingUrgency: 0.7,
          narrative: [],
          updatedAt: 10_000,
        },
        concernContinuity: {
          governingEntryId: 'concern-continuity::help-fix::runtime-error::thread-1',
          entries: [{
            id: 'concern-continuity::help-fix::runtime-error::thread-1',
            sourceConcernId: 'concern-1',
            kind: 'help-fix',
            status: 'active',
            summary: 'She is still carrying the runtime error knot.',
            anchor: 'runtime error',
            targetThreadId: 'thread-1',
            continuityWeight: 0.8,
            freshnessBias: 0.76,
            repairAffinity: 0.64,
            confidence: 0.78,
            createdAt: 0,
            lastUpdatedAt: 10_000,
            expiresAt: 120_000,
          }],
          carryPressure: 0.8,
          unresolvedCount: 1,
          narrative: [],
          updatedAt: 10_000,
        },
        repairLedger: {
          governingRepairId: 'repair-ledger::reground-scene::runtime-error',
          entries: [{
            id: 'repair-ledger::reground-scene::runtime-error',
            kind: 'reground-scene',
            status: 'open',
            summary: 'The live error still needs a cleaner grounding pass.',
            rationale: 'certainty is not fully live yet',
            urgency: 0.78,
            confidence: 0.72,
            createdAt: 0,
            lastUpdatedAt: 10_000,
            expiresAt: 120_000,
          }],
          repairPressure: 0.78,
          truthRisk: 0.72,
          shouldConstrainPresentTense: true,
          narrative: [],
          updatedAt: 10_000,
        },
        mindKernel: {
          dominantMode: 'repairing',
          governingCommitmentId: 'commitment::repair-misread::thread-1',
          governingInquiryPlanId: 'inquiry-plan::reground-scene::thread-1',
          worldPressure: 0.62,
          epistemicPressure: 0.78,
          relationalPressure: 0.24,
          carePressure: 0.16,
          continuityPressure: 0.54,
          speakReadiness: 0.22,
          presenceWeight: 0.48,
          narrative: ['repairing is governing the current inner line.'],
          updatedAt: 10_000,
        },
        actionEcology: {
          mode: 'repair-before-speaking',
          selectedThreadId: 'thread-1',
          readiness: 0.38,
          surfacePressure: 0.24,
          silencePressure: 0.72,
          suggestedStyle: 'silent-observe',
          embodiedPresence: 'hesitant',
          shouldSurface: true,
          shouldSpeak: false,
          why: 'She still needs a cleaner grounding pass before speaking.',
          updatedAt: 10_000,
        },
        answerPlanner: {
          act: 'ask-reground',
          evidenceMode: 'repair-first',
          confidence: 0.8,
          governingFocus: 'The live error still needs a cleaner grounding pass.',
          openingMove: 'Open by admitting the live view is not grounded enough yet.',
          answerIntent: 'Keep truth ahead of fluency by regrounding before you commit.',
          relationshipPosture: 'restrained',
          shouldAskForGrounding: true,
          shouldAcknowledgeRepair: true,
          selectedConcernEntryId: 'concern-continuity::help-fix::runtime-error::thread-1',
          selectedRepairId: 'repair-ledger::reground-scene::runtime-error',
          mustDo: [],
          mustNotDo: [],
          narrative: [],
          updatedAt: 10_000,
        },
        privateThought: {
          stance: 'uncertain',
          confidence: 0.58,
          rationaleTags: [],
          thoughtText: 'I should repair the drift before claiming anything.',
          shouldSpeak: false,
          suggestedStyle: 'silent-observe',
          embodiedPresence: 'hesitant',
          expiresAt: 40_000,
          afterglowFromScenario: null,
          emotionalTension: 'tense-debug',
        },
        captureState: {
          permission: 'granted',
          lastGroundedAt: 10_000,
        },
        durabilityPulse: null,
        recentTransition: null,
        nextSuggestedProbeMs: 10_000,
        updatedAt: 10_000,
      },
    })

    expect(fragment).toContain('belief_stability:fractured')
    expect(fragment).toContain('mind_need:repair')
    expect(fragment).toContain('commitment:repair-misread')
    expect(fragment).toContain('inquiry_plan:reground-scene')
    expect(fragment).toContain('concern_continuity:help-fix/active')
    expect(fragment).toContain('repair_ledger:reground-scene/open')
    expect(fragment).toContain('answer_act:ask-reground')
    expect(fragment).toContain('mind_kernel:repairing')
    expect(fragment).toContain('action_ecology:repair-before-speaking')
    expect(fragment).toContain('emotional_tension:tense-debug')
  })

  it('stays silent when the inner signature has not changed', () => {
    const nextState = {
      watchMode: 'mnemonic-passive' as const,
      currentScene: null,
      attention: null,
      workingMemoryEpisodes: [],
      beliefRevision: {
        dominantBeliefId: null,
        stability: 'stable' as const,
        revisionPressure: 0.2,
        groundingNeed: 0.18,
        contradictionPressure: 0.08,
        hostCorrectionWeight: 0.16,
        narrative: [],
        updatedAt: 20_000,
      },
      deliberationState: {
        primaryThreadId: 'thread-2',
        dominantNeed: 'companionship' as const,
        readiness: 0.52,
        threads: [{
          id: 'thread-2',
          kind: 'stay-near' as const,
          status: 'holding' as const,
          summary: 'Stay near quietly.',
          desiredOutcome: 'keep continuity alive',
          focusBeliefId: null,
          focusInquiryId: null,
          concernId: null,
          surfacePressure: 0.32,
          silencePressure: 0.28,
          embodiedPresence: 'glance' as const,
          startedAt: 0,
          lastUpdatedAt: 20_000,
          expiresAt: 120_000,
        }],
        narrative: [],
        updatedAt: 20_000,
      },
      actionEcology: {
        mode: 'quiet-accompany' as const,
        selectedThreadId: 'thread-2',
        readiness: 0.52,
        surfacePressure: 0.34,
        silencePressure: 0.3,
        suggestedStyle: 'silent-observe' as const,
        embodiedPresence: 'glance' as const,
        shouldSurface: true,
        shouldSpeak: false,
        why: 'Presence matters here more than commentary.',
        updatedAt: 20_000,
      },
      privateThought: {
        stance: 'accompany' as const,
        confidence: 0.62,
        rationaleTags: [],
        thoughtText: 'I can stay nearby quietly.',
        shouldSpeak: false,
        suggestedStyle: 'silent-observe' as const,
        embodiedPresence: 'glance' as const,
        expiresAt: 50_000,
        afterglowFromScenario: null,
        emotionalTension: 'soft-covision' as const,
      },
      captureState: {
        permission: 'granted' as const,
        lastGroundedAt: 20_000,
      },
      durabilityPulse: null,
      recentTransition: null,
      nextSuggestedProbeMs: 10_000,
      updatedAt: 20_000,
    }

    expect(buildMindContinuityFragment({
      previousState: nextState,
      nextState,
    })).toBe('')
  })

  it('builds a recall seed from the current inner line', () => {
    const seed = buildMindContinuityRecallSeed({
      watchMode: 'symbiotic-vision',
      currentScene: null,
      attention: null,
      workingMemoryEpisodes: [],
      beliefRevision: {
        dominantBeliefId: null,
        stability: 'stable',
        revisionPressure: 0.22,
        groundingNeed: 0.18,
        contradictionPressure: 0.1,
        hostCorrectionWeight: 0.16,
        narrative: [],
        updatedAt: 30_000,
      },
      deliberationState: {
        primaryThreadId: 'thread-3',
        dominantNeed: 'guidance',
        readiness: 0.74,
        threads: [{
          id: 'thread-3',
          kind: 'localize-problem',
          status: 'ripe',
          summary: 'Locate the exact locus of the knot.',
          desiredOutcome: 'point at the real line',
          focusBeliefId: null,
          focusInquiryId: null,
          concernId: null,
          surfacePressure: 0.72,
          silencePressure: 0.22,
          embodiedPresence: 'attentive',
          startedAt: 0,
          lastUpdatedAt: 30_000,
          expiresAt: 120_000,
        }],
        narrative: [],
        updatedAt: 30_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::hold-problem::thread-3',
        commitments: [{
          id: 'commitment::hold-problem::thread-3',
          kind: 'hold-problem',
          status: 'active',
          title: 'Hold Problem',
          summary: 'The concrete knot should stay alive across ticks.',
          source: 'runtime-thread',
          priority: 0.78,
          confidence: 0.72,
          createdAt: 0,
          lastRenewedAt: 30_000,
          patienceUntil: 60_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.58,
        narrative: [],
        updatedAt: 30_000,
      },
      inquiryPlanner: {
        activePlanId: 'inquiry-plan::localize-problem::thread-3',
        plans: [{
          id: 'inquiry-plan::localize-problem::thread-3',
          kind: 'localize-problem',
          status: 'tracking',
          priority: 'high',
          question: 'Which line is the real knot?',
          askForGrounding: false,
          suggestedProbeMs: 12_000,
          evidenceWanted: ['error-locus'],
          createdAt: 0,
          lastUpdatedAt: 30_000,
          expiresAt: 120_000,
        }],
        epistemicPressure: 0.54,
        groundingUrgency: 0.18,
        narrative: [],
        updatedAt: 30_000,
      },
      mindKernel: {
        dominantMode: 'tracking',
        governingCommitmentId: 'commitment::hold-problem::thread-3',
        governingInquiryPlanId: 'inquiry-plan::localize-problem::thread-3',
        worldPressure: 0.66,
        epistemicPressure: 0.42,
        relationalPressure: 0.28,
        carePressure: 0.18,
        continuityPressure: 0.56,
        speakReadiness: 0.58,
        presenceWeight: 0.54,
        narrative: ['tracking is governing the current inner line.'],
        updatedAt: 30_000,
      },
      actionEcology: {
        mode: 'surface-nudge',
        selectedThreadId: 'thread-3',
        readiness: 0.76,
        surfacePressure: 0.74,
        silencePressure: 0.24,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        shouldSurface: true,
        shouldSpeak: true,
        why: 'The knot is local enough for a nudge.',
        updatedAt: 30_000,
      },
      privateThought: {
        stance: 'nudge',
        confidence: 0.8,
        rationaleTags: [],
        thoughtText: 'I can point closer to the real knot now.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 60_000,
        afterglowFromScenario: null,
        emotionalTension: 'focused-flow',
      },
      captureState: {
        permission: 'granted',
        lastGroundedAt: 30_000,
      },
      durabilityPulse: null,
      recentTransition: null,
      nextSuggestedProbeMs: 10_000,
      updatedAt: 30_000,
    })

    expect(seed).toContain('Locate the exact locus of the knot.')
    expect(seed).toContain('mind_need:guidance')
    expect(seed).toContain('commitment:hold-problem')
    expect(seed).toContain('inquiry_plan:localize-problem')
    expect(seed).toContain('mind_kernel:tracking')
    expect(seed).toContain('action_ecology:surface-nudge')
  })
})
