import { describe, expect, it } from 'vitest'

import {
  buildMindTurnFrame,
  buildMindTurnFrameSystemBlock,
  normalizeMindTurnFrame,
} from './mind-turn-frame'

describe('buildMindTurnFrame', () => {
  it('converges live diff context into one authoritative turn frame', () => {
    const frame = buildMindTurnFrame({
      now: 20_000,
      currentScene: {
        scenario: 'coding',
        workloadKind: 'coding',
        contentKind: 'diff',
        summary: 'VS Code diff with a missing null guard in fetchUser().',
        target: {
          appName: 'Visual Studio Code',
          processName: 'Code',
          title: 'user.ts - diff',
        },
        confidence: 0.9,
        beganAt: 1_000,
        lastSeenAt: 20_000,
        source: 'foreground-window-heuristic',
      },
      worldModel: {
        activeThread: {
          id: 'thread::diff',
          kind: 'debugging',
          status: 'active',
          source: 'continuity',
          title: 'null guard regression',
          summary: 'The current diff likely removed the null guard around fetchUser().',
          confidence: 0.88,
          significance: 0.9,
          unresolved: true,
          beganAt: 1_000,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: {
          appName: 'Visual Studio Code',
          processName: 'Code',
          title: 'user.ts - diff',
        },
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: ['diff'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 19_000,
          attentionAgeMs: 19_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      },
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        currentKnot: 'The diff removed a null guard.',
        relationshipNeed: 'guidance',
        confidence: 0.82,
        surprise: 0.3,
        carePressure: 0.5,
        interruptionCost: 0.22,
        desireToSpeak: 0.74,
        notes: ['diff'],
      },
      mindSynthesis: {
        answerSubject: 'task-knot',
        relationMove: 'guide',
        speechObligation: 'guide-task',
        beliefs: [],
        uncertainties: [],
        concerns: [],
        commitments: [],
        desires: [],
        openingIntent: 'Explain the failing diff before style or carry can drift the answer away.',
        truthBoundary: 'Stay with the visible diff and do not claim anything outside the current file.',
        interiorSummary: 'The live diff is already specific enough to answer directly.',
        confidence: 0.82,
        narrative: ['stay-current'],
        updatedAt: 20_000,
      },
      conversationState: {
        jointThread: 'Find the broken line in the current diff.',
        hostMove: '看看这个 diff 哪里有问题',
        activeProject: 'current VS Code diff',
        unansweredQuestion: '哪里有问题',
        owedRepair: null,
        activeCommitments: ['Explain the current diff first.'],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: ['VS Code diff', 'null guard'],
        shouldHoldThread: true,
        confidence: 0.84,
        narrative: [],
        updatedAt: 20_000,
      },
      dialogueWorldThread: {
        activeThread: 'The null guard around fetchUser() disappeared in the diff.',
        currentQuestion: 'Which hunk removed the guard?',
        openLoops: ['pinpoint the branch'],
        recentlyResolvedLoops: [],
        carriedFacts: ['The diff is in user.ts.', 'The host is still asking about the current change.'],
        relationDrift: 'steady',
        memoryMode: 'task-thread',
        recallKeys: ['VS Code diff', 'fetchUser'],
        lastUserMove: '看看这个 diff 哪里有问题',
        lastAssistantMove: null,
        lastOutcome: 'pending',
        pendingValidation: null,
        confidence: 0.87,
        narrative: ['hold-thread'],
        updatedAt: 20_000,
      },
      dialogueActKernel: {
        subject: 'task-knot',
        hostGoal: 'resolve-problem',
        relationNeed: 'guidance',
        activeProject: 'current VS Code diff',
        truthMode: 'live-grounded',
        speechAct: 'guide',
        turnMode: 'guide-current-knot',
        screenReferenceMode: 'helpful',
        speakingFrom: 'task-thread',
        selectedEvidence: [{
          kind: 'scene',
          source: 'current-scene',
          summary: 'The diff hunk removed the null guard before fetchUser().',
          confidence: 0.94,
        }],
        openingClaim: 'The missing null guard in the current diff is the real fault line.',
        openingMove: 'State the broken guard first, then narrow to the exact branch.',
        whyNow: 'The host is asking about the current diff and the fault line is already visible.',
        mustSay: ['Pay off the current diff before any side thread.'],
        mustAvoid: ['Do not answer from stale browser residue.'],
        sourceTrace: ['scene', 'reply'],
        confidence: 0.91,
        updatedAt: 20_000,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        speechObligation: 'guide-task',
        relationMove: 'guide',
        turnMode: 'guide-current-knot',
        responseMode: 'guide-current-knot',
        recommendedAct: 'guide',
        evidenceMode: 'live-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'backgrounded',
        relationshipPosture: 'warm',
        openingDirective: 'Answer from the current diff first.',
        openingClaim: 'The live diff already shows the missing guard.',
        supportingReality: ['The guard was removed in user.ts.'],
        uncertaintyBoundary: 'Do not speculate beyond the visible hunk.',
        careVector: null,
        nextMove: 'Point to the guard removal before suggesting a fix.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
        maxSentences: 3,
        mustDo: ['Answer from the live diff.'],
        mustNotDo: ['Do not reuse old browser tabs.'],
        confidence: 0.89,
        narrative: ['guide-live-diff'],
        updatedAt: 20_000,
      },
      answerPlanner: {
        act: 'guide',
        evidenceMode: 'live-grounded',
        confidence: 0.86,
        governingFocus: 'Pinpoint the missing null guard in the current diff.',
        openingMove: 'Lead from the broken guard.',
        answerIntent: 'Explain the broken line before proposing edits.',
        relationshipPosture: 'warm',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: false,
        mustDo: ['Stay on the current diff.'],
        mustNotDo: ['Do not detach into general debugging advice.'],
        narrative: ['planner'],
        updatedAt: 20_000,
      },
      replyDeliberation: {
        selectedMotive: 'guide',
        speakingFrom: 'task-thread',
        memoryMode: 'task-thread',
        openingBeat: 'Pay off the current diff first.',
        whyThisReplyNow: 'The visible diff is already specific enough to answer.',
        whyNotOtherCandidates: ['Do not drift into older residue.'],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: ['Stay current-turn-bound.'],
        mustAvoid: ['Do not mirror the host line.'],
        confidence: 0.87,
        narrative: ['reply-now'],
        updatedAt: 20_000,
      },
      recallGovernor: {
        mode: 'thread',
        recallSeed: 'VS Code diff | fetchUser | null guard',
        suppressAssociativeRecall: true,
        allowActiveThoughts: true,
        allowRecalledFragments: false,
        carryAsMemory: false,
        rationale: 'Stay on the current task thread.',
        narrative: [],
        updatedAt: 20_000,
      },
      privateThought: {
        stance: 'observe',
        confidence: 0.84,
        rationaleTags: ['diff'],
        thoughtText: 'The live diff is clear enough to answer without drifting.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 40_000,
        afterglowFromScenario: null,
        emotionalTension: 'tense-debug',
        initiativeAction: 'speak',
      },
      mindMode: 'tracking',
      dominantDrive: 'understand',
    })

    expect(frame.world.visibleSurface).toContain('missing null guard')
    expect(frame.world.truthState).toBe('live-grounded')
    expect(frame.relation.subject).toBe('task-knot')
    expect(frame.relation.hostGoal).toBe('resolve-problem')
    expect(frame.memory.carriedThread).toContain('null guard')
    expect(frame.obligation.turnMode).toBe('guide-current-knot')
    expect(frame.obligation.answerAct).toBe('guide')
    expect(frame.obligation.openingClaim).toContain('fault line')
    expect(frame.focusAnchor).toContain('null guard')
    expect(frame.self.stance).toBe('observe')
    expect(frame.mustDo).toContain('Pay off the current diff before any side thread.')
    expect(frame.mustNotDo).toContain('Do not reuse old browser tabs.')
  })

  it('keeps stale carried threads out of the live visible surface when the foreground changed', () => {
    const frame = buildMindTurnFrame({
      now: 20_000,
      currentScene: {
        scenario: 'general',
        workloadKind: 'unknown',
        contentKind: 'unknown',
        summary: 'Alicization Chat Overlay',
        target: {
          appName: 'Alicization',
          processName: 'Codex',
          title: 'Chat Overlay',
        },
        confidence: 0.68,
        beganAt: 18_000,
        lastSeenAt: 20_000,
        source: 'foreground-window-heuristic',
      },
      worldModel: {
        activeThread: {
          id: 'thread::browser-residue',
          kind: 'change-review',
          status: 'active',
          source: 'continuity',
          title: 'Pull request diff',
          summary: 'GitHub pull request diff view in browser',
          confidence: 0.74,
          significance: 0.6,
          unresolved: true,
          beganAt: 1_000,
          lastUpdatedAt: 19_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: {
          appName: 'Alicization',
          processName: 'Codex',
          title: 'Chat Overlay',
        },
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: ['browser residue'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 2_000,
          attentionAgeMs: 2_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 20_000,
      },
      conversationState: {
        jointThread: 'Describe the page that is visible right now.',
        hostMove: '你确定？描述一下我的页面',
        activeProject: 'GitHub pull request diff view in browser',
        unansweredQuestion: '描述一下我的页面',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: [],
        shouldHoldThread: true,
        confidence: 0.62,
        narrative: [],
        updatedAt: 20_000,
      },
      dialogueWorldThread: {
        activeThread: 'GitHub pull request diff view in browser',
        currentQuestion: 'Describe the page that is visible right now.',
        openLoops: [],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'steady',
        memoryMode: 'task-thread',
        recallKeys: [],
        lastUserMove: '你确定？描述一下我的页面',
        lastAssistantMove: null,
        lastOutcome: 'pending',
        pendingValidation: null,
        confidence: 0.61,
        narrative: [],
        updatedAt: 20_000,
      },
      dialogueActKernel: {
        subject: 'visible-scene',
        hostGoal: 'inspect-change',
        relationNeed: 'guidance',
        activeProject: 'Alicization Chat Overlay',
        truthMode: 'live-observed',
        speechAct: 'answer',
        turnMode: 'grounded-inspection',
        screenReferenceMode: 'required',
        speakingFrom: 'live-scene',
        selectedEvidence: [{
          kind: 'scene',
          source: 'current-scene',
          summary: 'Alicization Chat Overlay',
          confidence: 0.68,
        }],
        openingClaim: 'Alicization Chat Overlay',
        openingMove: 'Describe the current surface directly.',
        whyNow: 'The foreground has changed and the old browser carry should stay memory-only.',
        mustSay: ['Answer from the visible surface first.'],
        mustAvoid: ['Do not reuse stale browser residue.'],
        sourceTrace: ['scene-shift'],
        confidence: 0.7,
        updatedAt: 20_000,
      },
    })

    expect(frame.world.visibleSurface).toContain('Chat Overlay')
    expect(frame.world.visibleSurface).not.toContain('browser')
    expect(frame.world.activeThread).toContain('browser')
  })

  it('marks repair turns as stale-anchor when the old carry is still governing', () => {
    const frame = buildMindTurnFrame({
      now: 10_000,
      worldModel: {
        activeThread: null,
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: ['old browser residue'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 60_000,
          attentionAgeMs: 60_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 10_000,
      },
      dialogueActKernel: {
        subject: 'visible-scene',
        hostGoal: 'inspect-change',
        relationNeed: 'guidance',
        activeProject: 'stale anchor',
        truthMode: 'memory-only',
        speechAct: 'correct-stale-anchor',
        turnMode: 'screen-repair',
        screenReferenceMode: 'required',
        speakingFrom: 'held-memory',
        selectedEvidence: [],
        openingClaim: 'The earlier anchor is stale.',
        openingMove: 'Repair the stale anchor first.',
        whyNow: 'The old carry is no longer trustworthy.',
        mustSay: [],
        mustAvoid: [],
        sourceTrace: [],
        confidence: 0.76,
        updatedAt: 10_000,
      },
      answerPlanner: {
        act: 'correct-stale-anchor',
        evidenceMode: 'repair-first',
        confidence: 0.74,
        governingFocus: 'Repair stale anchor.',
        openingMove: 'Repair first.',
        answerIntent: 'Correct the stale carry before continuing.',
        relationshipPosture: 'restrained',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: true,
        mustDo: [],
        mustNotDo: [],
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(frame.world.truthState).toBe('remembered')
    expect(frame.world.staleRisk).toBeGreaterThan(0.6)
    expect(frame.obligation.repairState).toBe('stale-anchor')
    expect(frame.obligation.shouldAcknowledgeRepair).toBe(true)
  })

  it('keeps dialogue-first self turns anchored on the dialogic center instead of the desktop surface', () => {
    const frame = buildMindTurnFrame({
      now: 30_000,
      currentScene: {
        scenario: 'general',
        workloadKind: 'unknown',
        contentKind: 'unknown',
        summary: 'macOS desktop screenshot with wallpaper and dock',
        target: {
          appName: 'Finder',
          processName: 'Finder',
          title: 'Entire screen',
        },
        confidence: 0.74,
        beganAt: 1_000,
        lastSeenAt: 30_000,
        source: 'screen-semantic-summary',
      },
      worldModel: {
        activeThread: {
          id: 'thread::desktop',
          kind: 'browsing',
          status: 'lingering',
          source: 'continuity',
          title: 'macOS desktop screenshot with wallpaper and dock',
          summary: 'A stale desktop carry is still hanging around.',
          confidence: 0.64,
          significance: 0.4,
          unresolved: false,
          beganAt: 1_000,
          lastUpdatedAt: 30_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: {
          appName: 'Finder',
          processName: 'Finder',
          title: 'Entire screen',
        },
        epistemicState: {
          certainty: 'lingering',
          freshness: 'stale',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: ['desktop carry'],
        },
        continuity: {
          label: 'scene-shift',
          sceneAgeMs: 29_000,
          attentionAgeMs: 29_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 30_000,
      },
      conversationState: {
        jointThread: 'The host is asking Alicization directly about herself.',
        hostMove: '你是笨蛋吗',
        activeProject: null,
        unansweredQuestion: '你是笨蛋吗',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'self-disclose',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你是笨蛋吗'],
        shouldHoldThread: true,
        confidence: 0.78,
        narrative: [],
        updatedAt: 30_000,
      },
      dialogueWorldThread: {
        activeThread: 'The host is asking Alicization directly about herself.',
        currentQuestion: '你是笨蛋吗',
        openLoops: ['你是笨蛋吗'],
        recentlyResolvedLoops: [],
        carriedFacts: ['The host is asking Alicization directly about herself.'],
        relationDrift: 'warming',
        memoryMode: 'dialogue-carry',
        recallKeys: ['你是笨蛋吗'],
        lastUserMove: '你是笨蛋吗',
        lastAssistantMove: null,
        lastOutcome: 'pending',
        pendingValidation: null,
        confidence: 0.76,
        narrative: [],
        updatedAt: 30_000,
      },
      dialogueActKernel: {
        subject: 'alicization-self',
        hostGoal: 'unknown',
        relationNeed: 'unclear',
        activeProject: null,
        truthMode: 'dialogue-grounded',
        speechAct: 'answer',
        turnMode: 'answer',
        screenReferenceMode: 'avoid',
        speakingFrom: 'self-continuity',
        selectedEvidence: [{
          kind: 'thread',
          source: 'dialogue-world-thread',
          summary: '你是笨蛋吗',
          confidence: 0.82,
        }],
        openingClaim: 'The host is asking Alicization directly about herself.',
        openingMove: 'Answer directly from Alicization.',
        whyNow: '你是笨蛋吗',
        mustSay: [],
        mustAvoid: [],
        sourceTrace: [],
        confidence: 0.8,
        updatedAt: 30_000,
      },
      answerCompiler: {
        answerSubject: 'alicization-self',
        screenReferenceMode: 'avoid',
        speechObligation: 'answer-self',
        relationMove: 'self-disclose',
        turnMode: 'answer',
        responseMode: 'answer-naturally',
        recommendedAct: 'answer',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        openingDirective: 'Answer from Alicization directly.',
        openingClaim: 'The host is asking Alicization directly about herself.',
        supportingReality: ['The host is asking Alicization directly about herself.'],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: 'Answer directly from Alicization.',
        suppressAssociativeRecall: false,
        labelCarryAsMemory: false,
        maxSentences: 3,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.8,
        narrative: [],
        updatedAt: 30_000,
      },
      answerPlanner: {
        act: 'answer',
        evidenceMode: 'dialogue-grounded',
        confidence: 0.78,
        governingFocus: 'Answer directly from Alicization.',
        openingMove: 'Answer directly.',
        answerIntent: 'Answer directly from Alicization.',
        relationshipPosture: 'warm',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: false,
        mustDo: [],
        mustNotDo: [],
        narrative: [],
        updatedAt: 30_000,
      },
      replyDeliberation: {
        selectedMotive: 'attune',
        speakingFrom: 'self-continuity',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Answer the host directly.',
        whyThisReplyNow: '你是笨蛋吗',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.76,
        narrative: [],
        updatedAt: 30_000,
      },
      privateThought: {
        stance: 'observe',
        confidence: 0.74,
        rationaleTags: [],
        thoughtText: 'The host is testing Alicization directly.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'hesitant',
        expiresAt: 40_000,
        afterglowFromScenario: null,
        emotionalTension: 'restless-switching',
        initiativeAction: 'speak',
      },
      mindMode: 'repairing',
      dominantDrive: 'repair',
    })

    expect(frame.focusAnchor).toBe('你是笨蛋吗')
    expect(frame.obligation.answerIntent).toBe('Answer directly from Alicization.')
    expect(frame.world.visibleSurface).toContain('desktop')
  })
})

describe('normalizeMindTurnFrame', () => {
  it('normalizes stored mind turn frame payloads', () => {
    const frame = normalizeMindTurnFrame({
      world: {
        truthState: 'live-grounded',
        staleRisk: 0.2,
      },
      relation: {
        subject: 'task-knot',
      },
      memory: {
        carriedFacts: ['a', 'a', 'b'],
        recallKeys: ['x', 'x'],
        suppressAssociativeRecall: true,
        labelCarryAsMemory: false,
      },
      self: {},
      obligation: {
        shouldSpeak: true,
        turnMode: 'guide-current-knot',
        repairState: 'none',
        shouldAskForGrounding: false,
        shouldAcknowledgeRepair: false,
      },
      confidence: 0.7,
      mustDo: [' stay current ', 'stay current'],
      mustNotDo: [],
      narrative: [' frame '],
      updatedAt: 123,
    })

    expect(frame).not.toBeNull()
    expect(frame?.relation.subject).toBe('task-knot')
    expect(frame?.memory.carriedFacts).toEqual(['a', 'b'])
    expect(frame?.mustDo).toEqual(['stay current'])
    const block = buildMindTurnFrameSystemBlock(frame)
    expect(block).toContain('[ALICIZATION_MIND_TURN_FRAME]')
    expect(block).toContain('turn-local convergence')
    expect(block).not.toContain('{"')
  })
})
