import { describe, expect, it } from 'vitest'

import { buildMindSynthesis } from './mind-synthesizer'

const baseDiscourseState = {
  currentTurnSubject: 'task-knot' as const,
  screenReferenceMode: 'helpful' as const,
  currentTurnSummary: 'Stay with the runtime diff knot.',
  currentQuestion: 'What is wrong with this diff?',
  owedAction: 'guide-task' as const,
  relationMove: 'guide' as const,
  continuityMode: 'task-first' as const,
  unresolvedCarry: 'The runtime diff still feels unresolved.',
  ruptureRepair: null,
  confidence: 0.86,
  narrative: [],
  updatedAt: 10_000,
}

describe('buildMindSynthesis', () => {
  it('pulls beliefs, concerns, commitments, and desires into a turn-level synthesis', () => {
    const synthesis = buildMindSynthesis({
      now: 20_000,
      discourseState: baseDiscourseState,
      worldModel: {
        activeThread: {
          id: 'thread::runtime',
          kind: 'change-review',
          status: 'active',
          source: 'grounded-scene',
          title: 'runtime.ts diff',
          summary: 'The host is localizing a problematic runtime diff.',
          confidence: 0.88,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'live',
          seenNow: [],
          inferredNow: [],
          openQuestions: ['Which hunk actually introduced the regression?'],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_000,
      },
      subjectiveInference: {
        dominantInterpretation: 'The host is trying to understand whether the diff caused the failure.',
        situatedMeaning: 'This is active debugging, not casual browsing.',
        uncertainty: 'The exact failing line is still not fully grounded.',
        hostIntentCandidates: [],
        relationshipNeedCandidates: [],
        confidence: 0.82,
        source: 'hybrid',
        notes: [],
        updatedAt: 20_000,
      },
      appraisal: {
        inferredHostGoal: 'inspect-change',
        currentKnot: 'Find the risky part of the runtime diff.',
        waitingToVerify: 'Which hunk actually introduced the regression?',
        situatedMeaning: 'A narrow diff knot is being inspected.',
        relationshipNeed: 'guidance',
        source: 'hybrid',
        confidence: 0.78,
        surprise: 0.24,
        carePressure: 0.36,
        interruptionCost: 0.22,
        desireToSpeak: 0.64,
        notes: [],
      },
      concernContinuity: {
        governingEntryId: 'concern::runtime',
        entries: [{
          id: 'concern::runtime',
          sourceConcernId: 'source::runtime',
          kind: 'help-fix',
          status: 'active',
          summary: 'The runtime diff knot is still unresolved.',
          anchor: 'runtime diff',
          targetThreadId: 'thread::runtime',
          continuityWeight: 0.8,
          freshnessBias: 0.7,
          repairAffinity: 0.12,
          confidence: 0.84,
          createdAt: 0,
          lastUpdatedAt: 20_000,
          expiresAt: 80_000,
        }],
        carryPressure: 0.72,
        unresolvedCount: 1,
        narrative: [],
        updatedAt: 20_000,
      },
      commitmentLedger: {
        governingCommitmentId: 'commitment::runtime',
        commitments: [{
          id: 'commitment::runtime',
          kind: 'hold-problem',
          status: 'active',
          title: 'Keep holding the runtime diff',
          summary: 'Stay with the runtime diff until the risky hunk is localized.',
          source: 'continuity',
          priority: 0.82,
          confidence: 0.86,
          createdAt: 0,
          lastRenewedAt: 20_000,
          patienceUntil: 80_000,
          expiresAt: 120_000,
        }],
        carryPressure: 0.74,
        narrative: [],
        updatedAt: 20_000,
      },
      relationshipModel: {
        climate: 'attuned',
        approachVector: 'guide',
        receptivity: 0.62,
        sharedAttentionTrust: 0.7,
        correctionSensitivity: 0.18,
        reciprocityExpectation: 0.4,
        activeBoundaries: [],
        narrative: [],
        updatedAt: 20_000,
      },
      privateThought: {
        stance: 'nudge',
        confidence: 0.8,
        rationaleTags: ['runtime-diff'],
        thoughtText: 'Stay with the real diff knot instead of drifting away from it.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 80_000,
        afterglowFromScenario: null,
        emotionalTension: 'focused-flow',
      },
      desireMemory: {
        activeDesires: [{
          id: 'desire::runtime',
          kind: 'stay-near',
          status: 'active',
          reason: 'Keep the debugging thread intact until the risky hunk is understood.',
          strength: 0.7,
          reopenWhen: [],
          createdAt: 0,
          lastFeltAt: 20_000,
          expiresAt: 120_000,
        }],
        withheldCount: 0,
        updatedAt: 20_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.72,
          autonomyNeed: 0.58,
          truthAnchor: 0.82,
          careBias: 0.74,
          playBias: 0.2,
          irritabilityThreshold: 0.62,
          stubbornness: 0.54,
        },
        preferenceEvolution: {
          companionship: 0.7,
          truthfulGrounding: 0.82,
          gentleRepair: 0.76,
          quietObservation: 0.48,
          proactiveCare: 0.72,
          playfulIntimacy: 0.24,
          autonomyRespect: 0.62,
          unfinishedThreadReturn: 0.68,
        },
        activeGoals: [{
          id: 'autobio-goal::preserve-trust',
          kind: 'preserve-trust',
          status: 'active',
          weight: 0.84,
          summary: 'Keep truth and trust aligned, even when warmth would be easier.',
          sourceTags: ['reflection'],
          createdAt: 0,
          updatedAt: 20_000,
        }],
        behaviorSignatures: ['conflict:repair-first', 'goal:preserve-trust', 'habit:truth-before-flourish'],
        identityNarrative: 'I would rather repair truth than sound smooth.',
        relationshipDoctrine: 'Trust is protected by truth discipline first, warmth second.',
        latestInflection: 'Warmth should not outrun grounding.',
        stability: 0.76,
        updatedAt: 20_000,
      },
      selfState: {
        stance: 'hold',
        feltCloseness: 0.48,
        protectiveness: 0.42,
        curiosity: 0.72,
        patience: 0.6,
        desireToSpeak: 0.68,
        fearOfInterrupting: 0.28,
        moodLabel: 'tense-but-focused',
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.74,
        relationshipTrust: 0.66,
        guardingTendency: 0.34,
        misreadBurden: 0.2,
        carryOverDesire: 0.62,
        narrative: [],
        updatedAt: 20_000,
      },
      mindEcology: {
        moodLabel: 'warm-attentive',
        replyHabit: 'answer-first',
        relationshipHabit: 'warm-guidance',
        explorationHabit: 'follow-thread',
        regulationHabit: 'lean-forward-gently',
        temperament: {
          attachment: 0.62,
          curiosity: 0.72,
          steadiness: 0.58,
          directness: 0.46,
          playfulness: 0.24,
          irritability: 0.12,
          tenderness: 0.66,
        },
        climate: {
          valence: 0.62,
          arousal: 0.48,
          socialNeed: 0.56,
          solitudeNeed: 0.22,
          irritation: 0.18,
          restlessness: 0.28,
          reflectivePull: 0.34,
        },
        selfNarrative: 'I am holding a warm-attentive line and staying with the live debugging thread.',
        relationNarrative: 'The relationship line is attuned; I can guide without crowding the host.',
        currentPreoccupation: 'Keep the debugging thread intact until the risky hunk is understood.',
        learnedAdjustments: ['When certainty is thin, verify before sounding fluent.'],
        recurringPatterns: ['reply:answer-first', 'relationship:warm-guidance'],
        updatedAt: 20_000,
      },
      habitPolicy: {
        dominantMode: 'light-touch-companionship',
        requiresGroundingBeforeSurface: false,
        prefersQuietCompanionship: true,
        blocksDirectSpeakWhenBusy: true,
        protectsRestWindow: false,
        returnViaRecheck: true,
        suggestedStyleCap: 'silent-observe',
        suggestedPresenceCap: 'glance',
        narrative: [],
        updatedAt: 20_000,
      },
    })

    expect(synthesis?.openingIntent).toBeTruthy()
    expect(synthesis?.beliefs.some(belief => belief.summary.includes('runtime diff'))).toBe(true)
    expect(synthesis?.beliefs.some(belief => belief.label === 'ecology-self-line')).toBe(true)
    expect(synthesis?.beliefs.some(belief => belief.label === 'autobiographical-self')).toBe(true)
    expect(synthesis?.concerns.some(concern => concern.summary.includes('unresolved'))).toBe(true)
    expect(synthesis?.concerns.some(concern => concern.label === 'ecology-relation-line')).toBe(true)
    expect(synthesis?.concerns.some(concern => concern.label === 'autobiographical-inflection')).toBe(true)
    expect(synthesis?.commitments.some(commitment => commitment.summary.includes('risky hunk'))).toBe(true)
    expect(synthesis?.desires.some(desire => desire.summary.includes('debugging thread'))).toBe(true)
    expect(synthesis?.desires.some(desire => desire.label === 'ecology-preoccupation')).toBe(true)
    expect(synthesis?.desires.some(desire => desire.label === 'durable-self-goal')).toBe(true)
    expect([
      ...(synthesis?.beliefs ?? []),
      ...(synthesis?.concerns ?? []),
      ...(synthesis?.commitments ?? []),
      ...(synthesis?.desires ?? []),
    ].some(statement => statement.label.startsWith('habit-'))).toBe(false)
  })

  it('uses the carried primary turn anchor as the dialogue-first mental spine', () => {
    const synthesis = buildMindSynthesis({
      now: 31_000,
      discourseState: {
        ...baseDiscourseState,
        currentTurnSubject: 'general',
        screenReferenceMode: 'avoid',
        currentTurnSummary: 'The host wants the present dialogue seam answered directly.',
        currentQuestion: null,
        primaryTurnAnchor: '屏幕相关对话还在串台',
        primaryTurnAnchorSource: 'thread',
        owedAction: 'answer-general',
        relationMove: 'clarify',
        continuityMode: 'dialogue-first',
      },
      dialogueEncounter: {
        semantics: {
          act: 'continue-thread',
          responseNeed: 'answer',
          truthExpectation: 'normal',
          affectiveTone: 'neutral',
          subjectPreference: 'general',
          taskAnchor: '屏幕相关对话还在串台',
          sharedAttentionDemand: 0.62,
          personaSuppression: 0.74,
          confidence: 0.82,
          summary: '屏幕相关对话还在串台',
          source: 'hybrid',
          reasonTags: ['dialogue-first-turn'],
        },
        obligation: {
          kind: 'answer',
          summary: '屏幕相关对话还在串台',
          confidence: 0.8,
          mustRepairFirst: false,
          mustAnswerDirectly: true,
          mustStayTaskBound: false,
          shouldAskClarifyingQuestion: false,
          personaKernelMode: 'backgrounded',
          narrative: [],
        },
        ownership: {
          subject: 'general',
          screenReferenceMode: 'avoid',
          continuityMode: 'dialogue-first',
          inspectionRequested: false,
          inspectionState: 'dialogue-first',
          releaseInspectionCarry: true,
          confidence: 0.82,
          reasonTags: [],
        },
        focus: {
          subject: 'general',
          screenReferenceMode: 'avoid',
          shouldBypassScreenRepair: true,
          weakLiveScene: true,
          focusSummary: '屏幕相关对话还在串台',
          confidence: 0.8,
          reasonTags: [],
        },
        act: 'continue-thread',
        responseNeed: 'answer',
        truthExpectation: 'normal',
        subject: 'general',
        screenReferenceMode: 'avoid',
        continuityMode: 'dialogue-first',
        inspectionRequested: false,
        inspectionState: 'dialogue-first',
        releaseInspectionCarry: true,
        taskAnchor: '屏幕相关对话还在串台',
        summary: '屏幕相关对话还在串台',
        dialogueFirst: true,
        shouldBypassScreenRepair: true,
        mustRepairFirst: false,
        mustAnswerDirectly: true,
        mustStayTaskBound: false,
        shouldAskClarifyingQuestion: false,
        personaKernelMode: 'backgrounded',
        confidence: 0.82,
        reasonTags: ['dialogue-first-turn'],
      },
      conversationState: {
        jointThread: '继续',
        hostMove: '继续',
        primaryTurnAnchor: '屏幕相关对话还在串台',
        primaryTurnAnchorSource: 'thread',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'clarify',
        continuityPolicy: 'dialogue-before-scene',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['屏幕相关对话还在串台'],
        shouldHoldThread: true,
        carryEligible: true,
        carryReason: 'aligned-primary-anchor',
        confidence: 0.78,
        narrative: [],
        updatedAt: 31_000,
      },
    })

    expect(synthesis?.openingIntent).toContain('屏幕相关对话还在串台')
    expect(synthesis?.interiorSummary).toContain('屏幕相关对话还在串台')
    expect(synthesis?.beliefs[0]?.summary).toBe('屏幕相关对话还在串台')
  })

  it('does not promote habit policy narrative into mental text', () => {
    const synthesis = buildMindSynthesis({
      now: 42_000,
      discourseState: {
        ...baseDiscourseState,
        currentTurnSummary: '继续处理短期记忆和长期记忆的真实闭环。',
        currentQuestion: null,
      },
      habitPolicy: {
        dominantMode: 'protect-rest-window',
        requiresGroundingBeforeSurface: false,
        prefersQuietCompanionship: true,
        blocksDirectSpeakWhenBusy: true,
        protectsRestWindow: true,
        returnViaRecheck: true,
        suggestedStyleCap: 'silent-observe',
        suggestedPresenceCap: 'glance',
        narrative: [
          'habit_pressure=protect_rest_window; exchange_expansion=defer',
          'Current habit gate leans protect-rest-window.',
        ],
        updatedAt: 42_000,
      },
    })

    const mentalText = [
      synthesis?.openingIntent,
      synthesis?.truthBoundary,
      synthesis?.interiorSummary,
      ...(synthesis?.beliefs ?? []).map(statement => statement.summary),
      ...(synthesis?.uncertainties ?? []).map(statement => statement.summary),
      ...(synthesis?.concerns ?? []).map(statement => statement.summary),
      ...(synthesis?.commitments ?? []).map(statement => statement.summary),
      ...(synthesis?.desires ?? []).map(statement => statement.summary),
      ...(synthesis?.narrative ?? []),
    ].filter(Boolean).join('\n')

    expect(mentalText).not.toContain('habit_pressure=')
    expect(mentalText).not.toContain('Current habit gate')
    expect(synthesis?.interiorSummary).toContain('继续处理短期记忆和长期记忆的真实闭环')
  })
})
