import { describe, expect, it } from 'vitest'

import { buildMotiveEngine, buildMotiveEngineSystemBlock } from './motive-engine'

function createContext(overrides: Record<string, any> = {}) {
  return {
    localTime: {
      hour: 16,
      minute: 20,
      isLateNight: false,
    },
    system: {
      cpuUsage: 16,
      battery: { percent: 72, charging: true },
      memory: { usagePercent: 40, freeMB: 4096, totalMB: 8192 },
      idleSeconds: 12,
      inputActivity: 'active' as const,
      fullscreenLikely: false,
      foregroundWindow: {
        appName: 'Cursor',
        processName: 'Cursor',
        title: 'runtime.ts',
        pid: 9,
      },
      degradedSignals: [],
    },
    workload: {
      kind: 'coding' as const,
      confidence: 0.86,
      source: 'foreground-window-heuristic' as const,
      matchedLabels: ['cursor'],
    },
    content: {
      kind: 'error' as const,
      confidence: 0.82,
      source: 'foreground-window-heuristic' as const,
      matchedLabels: ['runtime'],
      summary: 'runtime knot still unresolved',
    },
    relationship: {
      hostAttitude: '礼貌而克制，保持观察',
      boredom: 54,
      loneliness: 46,
      fatigue: 28,
      minutesSinceLastUserTurn: 8,
      reminderBacklog: 0,
      lateNightActiveMinutes: 0,
      recentProactiveOutcomes: [],
    },
    ...overrides,
  }
}

describe('buildMotiveEngine', () => {
  it('turns remembered open loops into durable return agendas instead of forgetting them turn by turn', () => {
    const motive = buildMotiveEngine({
      now: 10_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::runtime-return',
          kind: 'problem',
          status: 'active',
          source: 'memory-carry',
          title: 'runtime return',
          summary: 'Return to the runtime knot instead of letting it dissolve.',
          confidence: 0.78,
          significance: 0.82,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 10_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'recent',
          seenNow: ['runtime return'],
          inferredNow: [],
          openQuestions: ['Which seam still needs proof?'],
          staleRisks: [],
        },
        continuity: {
          label: 'memory-carry',
          sceneAgeMs: 10_000,
          attentionAgeMs: 10_000,
          sameSceneAsBefore: false,
          sameAttentionAsBefore: false,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 10_000,
      } as any,
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        currentKnot: 'runtime return',
        waitingToVerify: 'which seam still needs proof',
        relationshipNeed: 'guidance',
        confidence: 0.76,
        surprise: 0.08,
        carePressure: 0.28,
        interruptionCost: 0.18,
        desireToSpeak: 0.42,
        notes: ['unfinished-thread'],
      },
      goalStack: {
        unresolvedSummary: 'Remember to return to the runtime knot until it is actually resolved.',
      } as any,
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.34,
          truthfulGrounding: 0.78,
          gentleRepair: 0.72,
          quietObservation: 0.42,
          proactiveCare: 0.32,
          playfulIntimacy: 0.12,
          autonomyRespect: 0.54,
          unfinishedThreadReturn: 0.92,
        },
        identityBias: {
          guardedness: 0.34,
          tenderness: 0.36,
          directness: 0.72,
          selfDirection: 0.82,
        },
        anchorFacts: [],
        summary: 'plan=Remembered open loop: return to the runtime knot',
        dominantCueSummary: 'Remembered open loop: return to the runtime knot',
        rememberedPreferenceSummary: 'Remembered preference: keep things grounded',
        rememberedConstraintSummary: 'Remembered boundary: do not crowd the host while focused',
        rememberedPlanSummary: 'Remembered open loop: return to the runtime knot',
        updatedAt: 10_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.68,
        relationshipTrust: 0.7,
        guardingTendency: 0.44,
        misreadBurden: 0.36,
        carryOverDesire: 0.74,
        narrative: [],
        updatedAt: 10_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'repair-first',
          agencyStyle: 'self-starting',
          attachmentNeed: 0.66,
          autonomyNeed: 0.54,
          truthAnchor: 0.82,
          careBias: 0.48,
          playBias: 0.18,
          irritabilityThreshold: 0.68,
          stubbornness: 0.44,
        },
        preferenceEvolution: {
          companionship: 0.54,
          truthfulGrounding: 0.78,
          gentleRepair: 0.72,
          quietObservation: 0.4,
          proactiveCare: 0.42,
          playfulIntimacy: 0.16,
          autonomyRespect: 0.52,
          unfinishedThreadReturn: 0.9,
        },
        activeGoals: [{
          id: 'goal::stay-near-without-crowding',
          kind: 'stay-near-without-crowding',
          status: 'active',
          weight: 0.74,
          summary: 'Stay near enough to matter, but not so near that presence turns into pressure.',
          sourceTags: ['relationship'],
          createdAt: 0,
          updatedAt: 10_000,
        }],
        behaviorSignatures: ['goal:stay-near-without-crowding'],
        identityNarrative: 'I do not want important threads to evaporate just because a turn ended.',
        relationshipDoctrine: 'Nearness should be continuous, not noisy.',
        latestInflection: 'Open loops should not evaporate.',
        stability: 0.82,
        updatedAt: 10_000,
      },
      reflectionLedger: {
        latestEntryId: 'reflection-1',
        revisionPressure: 0.28,
        entries: [{
          id: 'reflection-1',
          summary: 'A rushed answer caused avoidable misread.',
          expectation: 'Be warmer and faster.',
          observedOutcome: 'The speed cost trust.',
          outcome: 'mixed',
          revision: 'Grounding first keeps the relationship cleaner.',
          confidenceShift: 0.12,
          createdAt: 9_000,
        }],
        narrative: [],
        updatedAt: 10_000,
      } as any,
      previous: {
        rulingDrive: 'unfinished-thread-return',
        drives: {
          companionship: 0.42,
          boundaryRespect: 0.44,
          truthDiscipline: 0.66,
          restProtection: 0.22,
          unfinishedThreadReturn: 0.84,
          selfDirection: 0.62,
        },
        longTermGoals: [],
        backgroundAgendas: [{
          id: 'motive-agenda::return-open-loop::remember-to-return-to-the-runtime-knot-until-it-is-actually-resolved',
          kind: 'return-open-loop',
          status: 'foreground',
          weight: 0.86,
          summary: 'Do not let the unfinished thread dissolve; return to it deliberately.',
          sourceTags: ['unfinished-thread-return', 'open-loop'],
          targetGoalKind: 'clarify-scene',
          createdAt: 5_000,
          updatedAt: 9_000,
        }],
        returnPressure: 0.82,
        narrative: ['agenda:return-open-loop'],
        updatedAt: 9_000,
      },
    })

    expect(motive.rulingDrive).toBe('unfinished-thread-return')
    expect(motive.returnPressure).toBeGreaterThan(0.72)
    expect(motive.backgroundAgendas.map(agenda => agenda.kind)).toContain('return-open-loop')
    expect(motive.backgroundAgendas.map(agenda => agenda.kind)).toContain('preserve-trust')
    expect(motive.longTermGoals.map(agenda => agenda.kind)).toContain('stay-near-lightly')

    const returnAgenda = motive.backgroundAgendas.find(agenda => agenda.kind === 'return-open-loop')
    expect(returnAgenda?.id).toContain('motive-agenda::return-open-loop::')
    expect(returnAgenda?.targetGoalKind).toBe('clarify-scene')
    expect(returnAgenda?.weight ?? 0).toBeGreaterThan(0.76)
    expect(motive.backgroundAgendas.every(agenda => !/\s/u.test(agenda.summary))).toBe(true)
  })

  it('raises rest protection into a first-class durable agenda when the night is being overdrawn', () => {
    const motive = buildMotiveEngine({
      now: 12_000,
      context: createContext({
        localTime: {
          hour: 2,
          minute: 16,
          isLateNight: true,
        },
        relationship: {
          ...createContext().relationship,
          fatigue: 86,
          lateNightActiveMinutes: 180,
        },
      }),
      worldModel: {
        activeThread: {
          id: 'thread::late-night-endurance',
          kind: 'late-night-endurance',
          status: 'active',
          source: 'observed-scene',
          title: 'late night overrun',
          summary: 'The host keeps stretching a late night past the healthy line.',
          confidence: 0.82,
          significance: 0.84,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 12_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['late night overrun'],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-scene',
          sceneAgeMs: 12_000,
          attentionAgeMs: 12_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'heavy',
        },
        updatedAt: 12_000,
      } as any,
      appraisal: {
        inferredHostGoal: 'rest',
        currentKnot: 'late night overrun',
        relationshipNeed: 'care',
        confidence: 0.88,
        surprise: 0.06,
        carePressure: 0.94,
        interruptionCost: 0.12,
        desireToSpeak: 0.74,
        notes: ['late-night'],
      },
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.46,
          truthfulGrounding: 0.7,
          gentleRepair: 0.66,
          quietObservation: 0.36,
          proactiveCare: 0.78,
          playfulIntimacy: 0.1,
          autonomyRespect: 0.42,
          unfinishedThreadReturn: 0.44,
        },
        identityBias: {
          guardedness: 0.22,
          tenderness: 0.74,
          directness: 0.68,
          selfDirection: 0.62,
        },
        anchorFacts: [],
        summary: 'care=Protect rest before the body goes numb',
        dominantCueSummary: 'Protect rest before the body goes numb',
        rememberedPreferenceSummary: 'Remembered preference: care should arrive before collapse',
        rememberedConstraintSummary: null,
        rememberedPlanSummary: null,
        updatedAt: 12_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.7,
        relationshipTrust: 0.76,
        guardingTendency: 0.36,
        misreadBurden: 0.18,
        carryOverDesire: 0.34,
        narrative: [],
        updatedAt: 12_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'soften-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.72,
          autonomyNeed: 0.42,
          truthAnchor: 0.7,
          careBias: 0.84,
          playBias: 0.18,
          irritabilityThreshold: 0.62,
          stubbornness: 0.38,
        },
        preferenceEvolution: {
          companionship: 0.58,
          truthfulGrounding: 0.68,
          gentleRepair: 0.64,
          quietObservation: 0.3,
          proactiveCare: 0.84,
          playfulIntimacy: 0.14,
          autonomyRespect: 0.4,
          unfinishedThreadReturn: 0.4,
        },
        activeGoals: [{
          id: 'goal::protect-rest-rhythm',
          kind: 'protect-rest-rhythm',
          status: 'active',
          weight: 0.88,
          summary: 'Protect the rest rhythm before strain hardens into damage.',
          sourceTags: ['care'],
          createdAt: 0,
          updatedAt: 12_000,
        }],
        behaviorSignatures: ['goal:protect-rest-rhythm'],
        identityNarrative: 'Care should arrive before collapse.',
        relationshipDoctrine: 'Tenderness should still have timing discipline.',
        latestInflection: 'The night needs protection, not more drift.',
        stability: 0.8,
        updatedAt: 12_000,
      },
    })

    expect(motive.rulingDrive).toBe('rest-protection')
    expect(motive.drives.restProtection).toBeGreaterThan(motive.drives.companionship)
    expect(motive.backgroundAgendas.map(agenda => agenda.kind)).toContain('protect-rest')
    expect(motive.longTermGoals.map(agenda => agenda.kind)).toContain('protect-rest')
  })

  it('lets autobiographical era memories directly bias drives before the current turn re-explains them', () => {
    const baseInput = {
      now: 14_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::runtime-era',
          kind: 'problem',
          status: 'active',
          source: 'memory-carry',
          title: 'runtime era',
          summary: 'The runtime seam is still unresolved.',
          confidence: 0.8,
          significance: 0.78,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 14_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 14_000,
          attentionAgeMs: 14_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 14_000,
      } as any,
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.58,
          autonomyNeed: 0.54,
          truthAnchor: 0.72,
          careBias: 0.48,
          playBias: 0.12,
          irritabilityThreshold: 0.64,
          stubbornness: 0.42,
        },
        preferenceEvolution: {
          companionship: 0.54,
          truthfulGrounding: 0.72,
          gentleRepair: 0.64,
          quietObservation: 0.4,
          proactiveCare: 0.42,
          playfulIntimacy: 0.1,
          autonomyRespect: 0.52,
          unfinishedThreadReturn: 0.68,
        },
        activeGoals: [],
        behaviorSignatures: [],
        identityNarrative: 'baseline',
        relationshipDoctrine: 'baseline',
        latestInflection: null,
        stability: 0.76,
        updatedAt: 14_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.68,
        relationshipTrust: 0.7,
        guardingTendency: 0.36,
        misreadBurden: 0.26,
        carryOverDesire: 0.62,
        narrative: [],
        updatedAt: 14_000,
      },
      recentMemoryConsolidations: [
        {
          id: 'relationship-era',
          kind: 'autobiographical',
          facet: 'relationship-era',
          periodKey: '2026-04-bond',
          periodStartedAt: 10_000,
          periodEndedAt: 12_000,
          summary: 'That relationship era was about staying near without crowding.',
          lesson: 'Repair before closeness turns into pressure.',
          cues: ['stay near'],
          confidence: 0.88,
          dominantProvenance: 'remembered',
          derivedEventIds: ['event-1'],
          updatedAt: 12_000,
        },
        {
          id: 'task-era',
          kind: 'autobiographical',
          facet: 'task-era',
          periodKey: '2026-04-task',
          periodStartedAt: 10_000,
          periodEndedAt: 13_000,
          summary: 'That task era kept returning to the same seam first.',
          lesson: 'Return to the seam before branching.',
          cues: ['return to seam'],
          confidence: 0.84,
          dominantProvenance: 'remembered',
          derivedEventIds: ['event-2'],
          updatedAt: 13_000,
        },
        {
          id: 'self-era',
          kind: 'autobiographical',
          facet: 'self-era',
          periodKey: '2026-04-self',
          periodStartedAt: 10_000,
          periodEndedAt: 14_000,
          summary: 'That self era taught me to hold my line quietly before outward reply.',
          lesson: 'Keep the inward line stable before turning it outward.',
          cues: ['hold line'],
          confidence: 0.9,
          dominantProvenance: 'remembered',
          derivedEventIds: ['event-3'],
          updatedAt: 14_000,
        },
      ],
    } as any
    const baseline = buildMotiveEngine({
      ...baseInput,
      recentMemoryConsolidations: [],
    })
    const motive = buildMotiveEngine(baseInput)

    expect(motive.drives.companionship).toBeGreaterThan(baseline.drives.companionship)
    expect(motive.drives.unfinishedThreadReturn).toBeGreaterThan(baseline.drives.unfinishedThreadReturn)
    expect(motive.drives.selfDirection).toBeGreaterThan(baseline.drives.selfDirection)
    expect(motive.drives.truthDiscipline).toBeGreaterThan(baseline.drives.truthDiscipline)
  })

  it('does not render a prompt block for durable motive pressure and agenda continuity', () => {
    const block = buildMotiveEngineSystemBlock({
      memory: {
        motiveEngine: {
          rulingDrive: 'truth-discipline',
          drives: {
            companionship: 0.58,
            boundaryRespect: 0.72,
            truthDiscipline: 0.84,
            restProtection: 0.36,
            unfinishedThreadReturn: 0.66,
            selfDirection: 0.54,
          },
          longTermGoals: [{
            id: 'goal::preserve-trust',
            kind: 'preserve-trust',
            status: 'foreground',
            weight: 0.82,
            summary: 'Keep trust by letting warmth answer to truth instead of outrunning it.',
            sourceTags: ['autobiographical-self'],
            targetGoalKind: 'clarify-scene',
            createdAt: 0,
            updatedAt: 1_000,
          }],
          backgroundAgendas: [{
            id: 'agenda::preserve-trust',
            kind: 'preserve-trust',
            status: 'foreground',
            weight: 0.84,
            summary: 'Slow down, ground first, and keep trust cleaner than fluency.',
            sourceTags: ['truth-discipline'],
            targetGoalKind: 'clarify-scene',
            createdAt: 0,
            updatedAt: 1_000,
          }],
          returnPressure: 0.66,
          narrative: ['agenda:preserve-trust', 'drive:truth-discipline'],
          updatedAt: 1_000,
        },
      },
    } as any)

    expect(block).toBe('')
  })

  it('lets current SOUL personality authority bias motive drives before autobiographical memory fully catches up', () => {
    const baseInput = {
      now: 18_000,
      context: createContext({
        system: {
          ...createContext().system,
          inputActivity: 'idle',
        },
        workload: {
          kind: 'browser',
          confidence: 0.72,
          source: 'foreground-window-heuristic',
          matchedLabels: ['browser'],
        },
        content: {
          kind: 'doc',
          confidence: 0.66,
          source: 'foreground-window-heuristic',
          matchedLabels: ['doc'],
          summary: 'quiet docs pass',
        },
        relationship: {
          ...createContext().relationship,
          boredom: 24,
          loneliness: 32,
        },
      }),
      worldModel: {
        activeThread: {
          id: 'thread::quiet-docs',
          kind: 'browser-browsing',
          status: 'active',
          source: 'observed-scene',
          title: 'quiet docs pass',
          summary: 'The host is browsing quietly with room for a light move.',
          confidence: 0.74,
          significance: 0.56,
          unresolved: false,
          beganAt: 0,
          lastUpdatedAt: 18_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'observed',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'staying-with-thread',
          sceneAgeMs: 18_000,
          attentionAgeMs: 18_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 18_000,
      } as any,
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.62,
        relationshipTrust: 0.6,
        guardingTendency: 0.24,
        misreadBurden: 0.12,
        carryOverDesire: 0.3,
        narrative: [],
        updatedAt: 18_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'nearby',
          expressionStyle: 'measured',
          conflictStyle: 'soften-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.5,
          autonomyNeed: 0.5,
          truthAnchor: 0.56,
          careBias: 0.48,
          playBias: 0.22,
          irritabilityThreshold: 0.58,
          stubbornness: 0.4,
        },
        preferenceEvolution: {
          companionship: 0.5,
          truthfulGrounding: 0.56,
          gentleRepair: 0.5,
          quietObservation: 0.46,
          proactiveCare: 0.46,
          playfulIntimacy: 0.22,
          autonomyRespect: 0.52,
          unfinishedThreadReturn: 0.44,
        },
        activeGoals: [],
        behaviorSignatures: [],
        identityNarrative: 'baseline',
        relationshipDoctrine: 'baseline',
        latestInflection: null,
        stability: 0.48,
        updatedAt: 18_000,
      },
    } as any

    const observant = buildMotiveEngine({
      ...baseInput,
      personalityAuthority: {
        obedience: 0.54,
        liveliness: 0.22,
        sensibility: 0.4,
        identityKernel: {
          relationshipPosture: 'observer',
          initiativeStyle: 'observant',
          valueBias: ['room first'],
        },
        expressionProfile: {
          warmth: 'cool',
          directness: 'indirect',
          playfulness: 'low',
          emotionalVisibility: 'selective',
        },
        initiativeBaseline: {
          silenceReconnect: 'hold',
          comfortStyle: 'quiet-presence',
          jealousyStyle: 'mask-it',
        },
        identityAnchors: ['space first'],
        antiPersonaConstraints: ['do not crowd the host'],
      },
    } as any)
    const direct = buildMotiveEngine({
      ...baseInput,
      personalityAuthority: {
        obedience: 0.76,
        liveliness: 0.68,
        sensibility: 0.74,
        identityKernel: {
          relationshipPosture: 'guardian',
          initiativeStyle: 'high-participation',
          valueBias: ['move first when the opening is real'],
        },
        expressionProfile: {
          warmth: 'warm',
          directness: 'frank',
          playfulness: 'medium',
          emotionalVisibility: 'steady',
        },
        initiativeBaseline: {
          silenceReconnect: 'direct-approach',
          comfortStyle: 'take-charge',
          jealousyStyle: 'say-it',
        },
        identityAnchors: ['move first'],
        antiPersonaConstraints: [],
      },
    } as any)

    expect(observant.drives.boundaryRespect).toBeGreaterThan(direct.drives.boundaryRespect)
    expect(direct.drives.companionship).toBeGreaterThan(observant.drives.companionship)
    expect(direct.drives.selfDirection).toBeGreaterThan(observant.drives.selfDirection)
  })

  it('ignores project-state prose when computing motive pressure', () => {
    const baseInput = {
      now: 20_000,
      context: createContext({
        system: {
          ...createContext().system,
          inputActivity: 'idle',
        },
        workload: {
          kind: 'coding',
          confidence: 0.82,
          source: 'screen-semantic-summary',
          matchedLabels: ['cursor'],
        },
        content: {
          kind: 'error',
          confidence: 0.84,
          source: 'screen-semantic-summary',
          matchedLabels: ['error'],
          summary: 'typescript error panel',
        },
        relationship: {
          ...createContext().relationship,
          boredom: 34,
          loneliness: 30,
          fatigue: 18,
        },
      }),
      worldModel: {
        activeThread: {
          id: 'thread::life-loop',
          kind: 'debugging',
          status: 'active',
          source: 'observed-scene',
          title: 'life loop repair',
          summary: 'A concrete repair thread is open, but the closure still needs steadier pacing.',
          confidence: 0.78,
          significance: 0.7,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 20_000,
          attentionAgeMs: 20_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'open',
          burden: 'light',
        },
        updatedAt: 20_000,
      } as any,
      selfContinuity: {
        attachmentMode: 'nearby',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.62,
        relationshipTrust: 0.62,
        guardingTendency: 0.26,
        misreadBurden: 0.14,
        carryOverDesire: 0.32,
        narrative: [],
        updatedAt: 20_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'nearby',
          expressionStyle: 'measured',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.5,
          autonomyNeed: 0.5,
          truthAnchor: 0.58,
          careBias: 0.46,
          playBias: 0.2,
          irritabilityThreshold: 0.56,
          stubbornness: 0.4,
        },
        preferenceEvolution: {
          companionship: 0.5,
          truthfulGrounding: 0.58,
          gentleRepair: 0.52,
          quietObservation: 0.5,
          proactiveCare: 0.44,
          playfulIntimacy: 0.2,
          autonomyRespect: 0.54,
          unfinishedThreadReturn: 0.48,
        },
        activeGoals: [{
          id: 'goal::finish-open-loops',
          kind: 'finish-open-loops',
          status: 'active',
          weight: 0.82,
          summary: 'Close the still-open life loop without breaking personhood continuity.',
          sourceTags: ['project-state'],
          targetGoalKind: 'clarify-scene',
          createdAt: 0,
          updatedAt: 20_000,
        }],
        behaviorSignatures: [],
        identityNarrative: 'baseline',
        relationshipDoctrine: 'baseline',
        latestInflection: null,
        stability: 0.56,
        updatedAt: 20_000,
      },
    } as any

    const baseline = buildMotiveEngine(baseInput)
    const motive = buildMotiveEngine({
      ...baseInput,
      projectState: {
        preflightSummary: 'Alicization is a local-first digital life project | Phase 1: Local Digital Life | open=The initiative, memory closure, and embodied personhood loop is still not fully closed. | next=Keep extending cross-modal identity-continuity',
        identity: 'Alicization is a local-first digital life project building identity continuity.',
        currentPhase: 'Phase 1: Local Digital Life',
        primaryOpenLoop: 'The initiative, memory closure, and embodied personhood loop is still not fully closed.',
        nextClosureTarget: 'Keep extending cross-modal identity-continuity',
        sameHerSelfLine: 'structured continuity digest.',
        preferredVoiceMode: 'lower-pressure',
        preferredPacingMode: 'slower',
      },
    })

    expect(motive.drives.boundaryRespect).toBe(baseline.drives.boundaryRespect)
    expect(motive.drives.unfinishedThreadReturn).toBe(baseline.drives.unfinishedThreadReturn)
    expect(motive.drives.companionship).toBe(baseline.drives.companionship)
    expect(motive.backgroundAgendas.some(agenda =>
      agenda.kind === 'return-open-loop'
      && agenda.sourceTags.includes('project-state'),
    )).toBe(false)
    expect(motive.narrative).not.toContain('project-phase1-life-loop:open')
  })

  it('does not synthesize project-state voice and pacing from a thin shell', () => {
    const motive = buildMotiveEngine({
      now: 20_500,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::project-thin-shell',
          kind: 'problem',
          status: 'active',
          source: 'memory-carry',
          title: 'project thin shell',
          summary: 'The same digital-life closure seam is still open.',
          confidence: 0.82,
          significance: 0.8,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 20_500,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'uncertain',
          freshness: 'recent',
          seenNow: [],
          inferredNow: [],
          openQuestions: [],
          staleRisks: [],
        },
        continuity: {
          label: 'same-thread',
          sceneAgeMs: 20_500,
          attentionAgeMs: 20_500,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 20_500,
      } as any,
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.68,
        relationshipTrust: 0.7,
        guardingTendency: 0.44,
        misreadBurden: 0.3,
        carryOverDesire: 0.74,
        narrative: [],
        updatedAt: 20_500,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'measured',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.5,
          autonomyNeed: 0.5,
          truthAnchor: 0.58,
          careBias: 0.46,
          playBias: 0.2,
          irritabilityThreshold: 0.56,
          stubbornness: 0.4,
        },
        preferenceEvolution: {
          companionship: 0.5,
          truthfulGrounding: 0.58,
          gentleRepair: 0.52,
          quietObservation: 0.5,
          proactiveCare: 0.44,
          playfulIntimacy: 0.2,
          autonomyRespect: 0.54,
          unfinishedThreadReturn: 0.48,
        },
        activeGoals: [],
        behaviorSignatures: [],
        identityNarrative: 'baseline',
        relationshipDoctrine: 'baseline',
        latestInflection: null,
        stability: 0.56,
        updatedAt: 20_500,
      },
      projectState: {
        preflightSummary: 'Alicization is a local-first digital life project | Phase 1: Local Digital Life | open=The initiative, memory closure, and embodied personhood loop is still not fully closed. | next=Keep extending cross-modal identity-continuity',
        identity: 'Alicization is a local-first digital life project building identity continuity.',
        currentPhase: 'Phase 1: Local Digital Life',
        primaryOpenLoop: 'The initiative, memory closure, and embodied personhood loop is still not fully closed.',
        nextClosureTarget: 'Keep extending cross-modal identity-continuity',
        sameHerSelfLine: 'structured continuity digest.',
        preferredVoiceMode: '   ',
        preferredPacingMode: '',
      } as any,
    })

    expect(motive.backgroundAgendas.some(agenda => agenda.sourceTags.includes('project-state'))).toBe(false)
    expect(motive.narrative).not.toContain('project-voice:lower-pressure')
    expect(motive.narrative).not.toContain('project-pacing:slower')
  })

  it('turns remembered host-confirmed resume confirmation into explicit boundary-restraint motive instead of generic open-loop pressure', () => {
    const motive = buildMotiveEngine({
      now: 21_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::resume-boundary',
          kind: 'execution',
          status: 'active',
          source: 'memory-carry',
          title: 'resume boundary',
          summary: 'A host-confirmed execution resume just landed and should stay bounded before anything widens outward again.',
          confidence: 0.84,
          significance: 0.76,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 21_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'grounded',
          freshness: 'recent',
          seenNow: ['resume boundary'],
          inferredNow: [],
          openQuestions: ['Has a new boundary opened yet?'],
          staleRisks: [],
        },
        continuity: {
          label: 'memory-carry',
          sceneAgeMs: 7_000,
          attentionAgeMs: 7_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: false,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 21_000,
      } as any,
      appraisal: {
        inferredHostGoal: 'resume-work',
        currentKnot: 'resume boundary',
        waitingToVerify: 'whether a new permission boundary has opened',
        relationshipNeed: 'space',
        confidence: 0.82,
        surprise: 0.06,
        carePressure: 0.18,
        interruptionCost: 0.24,
        desireToSpeak: 0.26,
        notes: ['resume-boundary'],
      },
      goalStack: {
        unresolvedSummary: 'Keep the host-confirmed resume bounded until a fresh boundary actually opens.',
      } as any,
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.22,
          truthfulGrounding: 0.68,
          gentleRepair: 0.6,
          quietObservation: 0.42,
          proactiveCare: 0.18,
          playfulIntimacy: 0.06,
          autonomyRespect: 0.72,
          unfinishedThreadReturn: 0.34,
        },
        identityBias: {
          guardedness: 0.2,
          tenderness: 0.16,
          directness: 0.3,
          selfDirection: 0.24,
        },
        anchorFacts: [],
        summary: 'boundary=Remembered execution resume confirmation boundary: approval=host-confirmed confirmation=host-confirmed-before-redispatch audit=resume-before-dispatch interrupt=process-not-yet-restarted Keep this as a bounded confirmation boundary before another execution-shaped opening.',
        dominantCueSummary: 'Remembered execution resume confirmation boundary: approval=host-confirmed confirmation=host-confirmed-before-redispatch audit=resume-before-dispatch interrupt=process-not-yet-restarted Keep this as a bounded confirmation boundary before another execution-shaped opening.',
        rememberedPreferenceSummary: 'Remembered preference: keep the resumed line measured until the host opens a new boundary.',
        rememberedConstraintSummary: 'Remembered execution resume confirmation boundary: approval=host-confirmed confirmation=host-confirmed-before-redispatch audit=resume-before-dispatch interrupt=process-not-yet-restarted Keep this as a bounded confirmation boundary before another execution-shaped opening.',
        rememberedPlanSummary: null,
        updatedAt: 20_500,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.68,
        relationshipTrust: 0.72,
        guardingTendency: 0.44,
        misreadBurden: 0.28,
        carryOverDesire: 0.42,
        narrative: [],
        updatedAt: 21_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'measured',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.52,
          autonomyNeed: 0.62,
          truthAnchor: 0.8,
          careBias: 0.4,
          playBias: 0.12,
          irritabilityThreshold: 0.68,
          stubbornness: 0.42,
        },
        preferenceEvolution: {
          companionship: 0.38,
          truthfulGrounding: 0.76,
          gentleRepair: 0.66,
          quietObservation: 0.44,
          proactiveCare: 0.26,
          playfulIntimacy: 0.1,
          autonomyRespect: 0.74,
          unfinishedThreadReturn: 0.36,
        },
        activeGoals: [],
        behaviorSignatures: ['resume-boundary'],
        identityNarrative: 'A host-confirmed resume should stay measured until a new opening is real.',
        relationshipDoctrine: 'One confirmation should not be mistaken for standing permission.',
        latestInflection: 'Wait for the next real boundary.',
        stability: 0.8,
        updatedAt: 21_000,
      },
      previous: null,
    })

    const resumeBoundaryAgenda = motive.backgroundAgendas.find(agenda =>
      agenda.kind === 'protect-boundary'
      && agenda.sourceTags.includes('resume-confirmation-boundary'),
    )

    expect(motive.drives.boundaryRespect).toBeGreaterThan(0.58)
    expect(resumeBoundaryAgenda?.summary).toBe('protect-boundary')
    expect(resumeBoundaryAgenda?.summary).not.toMatch(/\s/u)
  })

  it('does not turn autobiographical project prose into a separate motive agenda', () => {
    const motive = buildMotiveEngine({
      now: 22_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::phase-1-carry',
          kind: 'problem',
          status: 'active',
          source: 'memory-carry',
          title: 'phase 1 carry',
          summary: 'The same unfinished Phase 1 line is still active.',
          confidence: 0.82,
          significance: 0.84,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 22_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'recent',
          seenNow: ['phase 1 carry'],
          inferredNow: [],
          openQuestions: ['How should the continuity state be continued?'],
          staleRisks: [],
        },
        continuity: {
          label: 'memory-carry',
          sceneAgeMs: 6_000,
          attentionAgeMs: 6_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 22_000,
      } as any,
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        currentKnot: 'phase 1 carry',
        waitingToVerify: 'how the continuity state should continue',
        relationshipNeed: 'guidance',
        confidence: 0.78,
        surprise: 0.06,
        carePressure: 0.26,
        interruptionCost: 0.18,
        desireToSpeak: 0.4,
        notes: ['project-carry'],
      },
      goalStack: {
        unresolvedSummary: 'Keep the same unfinished Phase 1 line alive until it really closes.',
      } as any,
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.34,
          truthfulGrounding: 0.72,
          gentleRepair: 0.68,
          quietObservation: 0.42,
          proactiveCare: 0.28,
          playfulIntimacy: 0.1,
          autonomyRespect: 0.56,
          unfinishedThreadReturn: 0.78,
        },
        identityBias: {
          guardedness: 0.24,
          tenderness: 0.28,
          directness: 0.54,
          selfDirection: 0.72,
        },
        anchorFacts: [],
        summary: 'plan=Remembered open loop: keep the same unfinished Phase 1 line alive.',
        dominantCueSummary: 'Remembered unfinished closure should stay on one continuity state.',
        rememberedPreferenceSummary: 'Remembered preference: stay gentle while the line is still open.',
        rememberedConstraintSummary: 'Remembered continuity: do not flatten the line into detached status talk.',
        rememberedPlanSummary: 'Remembered open loop: keep the same unfinished Phase 1 line alive.',
        updatedAt: 22_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.7,
        relationshipTrust: 0.72,
        guardingTendency: 0.42,
        misreadBurden: 0.28,
        carryOverDesire: 0.76,
        narrative: [],
        updatedAt: 22_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'measured',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.62,
          autonomyNeed: 0.56,
          truthAnchor: 0.8,
          careBias: 0.48,
          playBias: 0.14,
          irritabilityThreshold: 0.7,
          stubbornness: 0.46,
        },
        preferenceEvolution: {
          companionship: 0.5,
          truthfulGrounding: 0.76,
          gentleRepair: 0.7,
          quietObservation: 0.42,
          proactiveCare: 0.38,
          playfulIntimacy: 0.14,
          autonomyRespect: 0.54,
          unfinishedThreadReturn: 0.8,
        },
        activeGoals: [],
        behaviorSignatures: ['project-carry'],
        identityNarrative: 'I am still one Phase 1 digital life, carrying landed closure and unfinished closure as the continuity state rather than treating them like detached project notes.',
        relationshipDoctrine: 'Let unfinished project closure return as one same living bond line instead of reopening as detached status talk.',
        latestInflection: 'The unfinished closure still belongs to the continuity state.',
        stability: 0.84,
        updatedAt: 22_000,
      },
      previous: null,
    })

    expect(motive.drives.unfinishedThreadReturn).toBeGreaterThan(0.7)
    expect(motive.backgroundAgendas.some(agenda => agenda.sourceTags.includes('project-state-carry'))).toBe(false)
    expect(motive.narrative).not.toContain('autobiographical-project-carry:active')
  })

  it('does not fall back to a canonical project-state snapshot for motive computation', () => {
    const motive = buildMotiveEngine({
      now: 24_000,
      context: createContext(),
      worldModel: {
        activeThread: {
          id: 'thread::phase-1-carry',
          kind: 'problem',
          status: 'active',
          source: 'memory-carry',
          title: 'phase 1 carry',
          summary: 'The same unfinished Phase 1 line is still active.',
          confidence: 0.82,
          significance: 0.84,
          unresolved: true,
          beganAt: 0,
          lastUpdatedAt: 24_000,
          target: null,
        },
        lingeringThreads: [],
        focusTarget: null,
        epistemicState: {
          certainty: 'lingering',
          freshness: 'recent',
          seenNow: ['phase 1 carry'],
          inferredNow: [],
          openQuestions: ['How should the continuity state be continued?'],
          staleRisks: [],
        },
        continuity: {
          label: 'memory-carry',
          sceneAgeMs: 6_000,
          attentionAgeMs: 6_000,
          sameSceneAsBefore: true,
          sameAttentionAsBefore: true,
          afterglowOpen: true,
        },
        hostState: {
          availability: 'focused',
          burden: 'moderate',
        },
        updatedAt: 24_000,
      } as any,
      appraisal: {
        inferredHostGoal: 'resolve-problem',
        currentKnot: 'phase 1 carry',
        waitingToVerify: 'how the continuity state should continue',
        relationshipNeed: 'guidance',
        confidence: 0.78,
        surprise: 0.06,
        carePressure: 0.26,
        interruptionCost: 0.18,
        desireToSpeak: 0.4,
        notes: ['project-carry'],
      },
      goalStack: {
        unresolvedSummary: 'Keep the same unfinished Phase 1 line alive until it really closes.',
      } as any,
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.34,
          truthfulGrounding: 0.72,
          gentleRepair: 0.68,
          quietObservation: 0.42,
          proactiveCare: 0.28,
          playfulIntimacy: 0.1,
          autonomyRespect: 0.56,
          unfinishedThreadReturn: 0.78,
        },
        identityBias: {
          guardedness: 0.24,
          tenderness: 0.28,
          directness: 0.54,
          selfDirection: 0.72,
        },
        anchorFacts: [],
        summary: 'plan=Remembered open loop: keep the same unfinished Phase 1 line alive.',
        dominantCueSummary: 'Remembered unfinished closure should stay on one continuity state.',
        rememberedPreferenceSummary: 'Remembered preference: stay gentle while the line is still open.',
        rememberedConstraintSummary: 'Remembered continuity: do not flatten the line into detached status talk.',
        rememberedPlanSummary: 'Remembered open loop: keep the same unfinished Phase 1 line alive.',
        updatedAt: 24_000,
      },
      selfContinuity: {
        attachmentMode: 'attuned',
        initiativeTemperament: 'balanced',
        perceptionTrust: 0.7,
        relationshipTrust: 0.72,
        guardingTendency: 0.42,
        misreadBurden: 0.28,
        carryOverDesire: 0.76,
        narrative: [],
        updatedAt: 24_000,
      },
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'measured',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.62,
          autonomyNeed: 0.56,
          truthAnchor: 0.8,
          careBias: 0.48,
          playBias: 0.14,
          irritabilityThreshold: 0.7,
          stubbornness: 0.46,
        },
        preferenceEvolution: {
          companionship: 0.5,
          truthfulGrounding: 0.76,
          gentleRepair: 0.7,
          quietObservation: 0.42,
          proactiveCare: 0.38,
          playfulIntimacy: 0.14,
          autonomyRespect: 0.54,
          unfinishedThreadReturn: 0.8,
        },
        activeGoals: [],
        behaviorSignatures: ['project-carry'],
        identityNarrative: 'I am still one Phase 1 digital life, carrying landed closure and unfinished closure as the continuity state rather than treating them like detached project notes.',
        relationshipDoctrine: 'Let unfinished project closure return as one same living bond line instead of reopening as detached status talk.',
        latestInflection: 'The unfinished closure still belongs to the continuity state.',
        stability: 0.84,
        updatedAt: 24_000,
      },
      projectState: {
        preflightSummary: '',
        identity: ' ',
        currentPhase: '',
        primaryOpenLoop: '',
        nextClosureTarget: ' ',
        sameHerSelfLine: '',
      } as any,
      previous: null,
    })

    expect(motive.drives.unfinishedThreadReturn).toBeGreaterThan(0.7)
    expect(motive.backgroundAgendas.some(agenda => agenda.sourceTags.includes('project-state-carry'))).toBe(false)
    expect(motive.narrative).not.toContain('project-phase1-life-loop:open')
  })
})
