import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

import {
  resolveAlicizationProjectStateBrief,
  resolveAlicizationProjectStateCoverage,
} from './project-state-brief'

function normalizeProjectStateSyncText(text: string) {
  return text.replaceAll('`', '').replace(/\s+/g, ' ')
}

function collectProjectStateAuditCoverageIds(doc: string) {
  return [...doc.matchAll(/^- `([^`]+)` (?:responsibility|proof):/gm)]
    .map(([, id]) => id)
    .filter((id, index, list) => list.indexOf(id) === index)
    .sort()
}

function collectProjectStateAuditEntries(doc: string) {
  const entries = new Map<string, { responsibility?: string, proof?: string }>()

  for (const [, id, kind, text] of doc.matchAll(/^- `([^`]+)` (responsibility|proof): (.*)$/gm)) {
    const current = entries.get(id) ?? {}
    if (kind === 'responsibility')
      current.responsibility = text
    else
      current.proof = text
    entries.set(id, current)
  }

  return entries
}

function collectProjectStateAuditEntryCounts(doc: string) {
  const counts = new Map<string, { responsibility: number, proof: number }>()

  for (const [, id, kind] of doc.matchAll(/^- `([^`]+)` (responsibility|proof): (.*)$/gm)) {
    const current = counts.get(id) ?? { responsibility: 0, proof: 0 }
    if (kind === 'responsibility')
      current.responsibility += 1
    else
      current.proof += 1
    counts.set(id, current)
  }

  return counts
}

function findProjectStateAuditRouteRow(doc: string, label: string) {
  return doc.split('\n').find(line => line.startsWith(`| ${label} |`)) ?? ''
}

describe('project-state docs sync', () => {
  it('keeps docs/project-state.md directly anchored to the canonical repo brief identity, phase, open loop, and same-her line', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(normalizedDoc).toContain(brief.identity)
    expect(normalizedDoc).toContain(brief.currentPhase)
    expect(normalizedDoc).toContain(brief.primaryOpenLoop)
    expect(normalizedDoc).toContain(brief.proactiveSameHerGap)
    expect(normalizedDoc).toContain(brief.sameHerSelfLine)
  })

  it('keeps docs/project-state.md directly anchored to the canonical preflight self-awareness summary', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.preflightSummary).toBeTruthy()
    expect(normalizedDoc).toContain(normalizeProjectStateSyncText(brief.preflightSummary ?? ''))
  })

  it('keeps docs/project-state.md directly anchored to the canonical pre-dialogue awareness line', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.preDialogueAwarenessLine).toBeTruthy()
    expect(normalizedDoc).toContain(brief.preDialogueAwarenessLine ?? '')
  })

  it('keeps docs/project-state.md directly anchored to the canonical latest landed progress summary', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.latestProgress).toBeTruthy()
    expect(normalizedDoc).toContain(normalizeProjectStateSyncText(brief.latestProgress))
    expect(brief.latestProgress).toContain('proactive policy')
    expect(brief.latestProgress).toContain('presence-only resident carry')
    expect(brief.latestProgress).toContain('bounded redispatch confirmation')
    expect(brief.latestProgress).toContain('permanent execution permission')
    expect(brief.latestProgress).toContain('Broader provider-consumer candidates')
    expect(brief.latestProgress).toContain('real invokeGenerateText / generateText / invokeStreamText / streamText sinks')
    expect(brief.latestProgress).toContain('broader autonomous-dialogue candidates')
    expect(brief.latestProgress).toContain('broader execution-dispatch candidates')
    expect(brief.latestProgress).toContain('broader execution-preflight candidates')
    expect(brief.latestProgress).toContain('semantics classification')
    expect(brief.latestProgress).toContain('answer planning')
    expect(brief.latestProgress).toContain('response charter shaping')
    expect(brief.latestProgress).toContain('Broader execution follow-up continuity candidates')
    expect(brief.latestProgress).toContain('execution-follow-up-entrypoint-candidate-audit.test.ts')
    expect(brief.latestProgress).toContain('Broader recovery reentry candidates')
    expect(brief.latestProgress).toContain('recovery-reentry-entrypoint-candidate-audit.test.ts')
    expect(brief.latestProgress).toContain('future provider-facing generation families still need explicit registration')
    expect(brief.latestProgress).toContain('future runtime-owned dialogue families still need explicit registration')
    expect(brief.latestProgress).toContain('future main-process chat-start entry shapes still need explicit classification')
    expect(brief.latestProgress).toContain('future renderer/store dialogue-entry shapes still need explicit classification')
    expect(brief.latestProgress).toContain('future reopen-time route shapes still need explicit classification')
    expect(brief.latestProgress).toContain('future execution dispatch families still need explicit owner registration')
    expect(brief.latestProgress).toContain('future execution-preflight families still need explicit classification')
    expect(brief.latestProgress).toContain('future execution follow-up families still need explicit registration')
    expect(brief.latestProgress).toContain('future recovery reentry families still need explicit classification')
    expect(brief.latestProgress).toContain('runtime execution bridge and subconscious deferred bridge dispatch owners')
    expect(brief.latestProgress).toContain('runtime-owned direct dispatch bridge')
    expect(brief.latestProgress).toContain('blocked-dispatch safety-gate briefing seams')
    expect(brief.latestProgress).toContain('single repo-level entrypoint governance registry')
    expect(brief.latestProgress).toContain('shared root final-gate candidate-audit registry')
    expect(brief.latestProgress).toContain('shared top-level completeness guard family registry')
    expect(brief.latestProgress).toContain('renderer/store dialogue-entry candidates')
    expect(brief.latestProgress).toContain('main-process chat-start candidates')
    expect(brief.latestProgress).toContain('reopen-time return-side rebuild candidates')
    expect(brief.latestProgress).toContain('provider-facing generation entry candidates')
    expect(brief.latestProgress).toContain('project-state answer surfaces')
    expect(brief.latestProgress).toContain('host-visible normalization seams')
    expect(brief.latestProgress).toContain('guarded turn persistence')
    expect(brief.latestProgress).toContain('execution-preflight context-repair candidates')
    expect(brief.latestProgress).toContain('direct execution-dispatch bridge candidates')
    expect(brief.latestProgress).toContain('recovery reentry')
    expect(brief.latestProgress).toContain('execution follow-up continuity')
    expect(brief.latestProgress).toContain('candidate families derive from one shared registry')
    expect(brief.latestProgress).toContain('future entrypoint families are harder to hide between neighboring audits')
    expect(brief.latestProgress).toContain('wholly new route families still are not automatically proven')
    expect(brief.latestProgress).toContain('runtime-owned autonomous-dialogue family markers')
    expect(brief.latestProgress).toContain('one shared source of truth')
    expect(brief.latestProgress).toContain('recovery-reentry plus execution-follow-up continuity seams')
    expect(brief.latestProgress).toContain('same explicit governance map')
    expect(brief.latestProgress).toContain('direct main-chat-stream callers')
    expect(brief.latestProgress).toContain('real startMainChatStream sinks')
    expect(brief.latestProgress).toContain('merge-readiness / closure-readiness follow-ups')
    expect(brief.latestProgress).toContain('completion-timing / language-drift follow-ups')
    expect(brief.latestProgress).toContain('can merge to main')
    expect(brief.latestProgress).toContain('how far the goal has landed')
    expect(brief.latestProgress).toContain('when it is expected to close')
    expect(brief.latestProgress).toContain('drifted into English')
    expect(brief.latestProgress).toContain('already verified evidence')
    expect(brief.latestProgress).toContain('unproven or still open')
    expect(brief.latestProgress).toContain('misreporting full closure')
    expect(brief.latestProgress).toContain('living-self host-facing system block')
    expect(brief.latestProgress).toContain('canonical project preflight self-awareness line')
    expect(brief.latestProgress).toContain('natural reply shaping')
    expect(brief.latestProgress).toContain('visible-reply facade project-state resolution')
    expect(brief.latestProgress).toContain('reply-surface planning')
    expect(brief.latestProgress).toContain('same shared project-state seam as living-self and fallback paths')
    expect(brief.latestProgress).toContain('ordinary dialogue system blocks')
    expect(brief.latestProgress).toContain('unified Phase 1 closure dashboard')
    expect(brief.latestProgress).toContain('runtime snapshot/digest')
    expect(brief.latestProgress).toContain('project-state spine')
    expect(brief.latestProgress).toContain('voice / face / motion / lipsync summaries')
    expect(brief.latestProgress).toContain('canonical embodimentScript')
    expect(brief.latestProgress).toContain('Dream, reminder, proactive, and reforge one-shot gateway prompts')
    expect(brief.latestProgress).toContain('screen-semantic summary generation')
    expect(brief.latestProgress).toContain('execution callback carry')
    expect(brief.latestProgress).toContain('execution-result delivery learning')
    expect(brief.latestProgress).toContain('long-horizon same-her memory')
    expect(brief.latestProgress).toContain('Current conscious frame shaping')
    expect(brief.latestProgress).toContain('still-open closure pressure')
    expect(brief.latestProgress).toContain('thin runtime project shell')
    expect(brief.latestProgress).toContain('richer same-her callback continuity')
    expect(brief.latestProgress).toContain('Primary open-loop continuity pressure')
    expect(brief.latestProgress).toContain('retrieval ranking')
    expect(brief.latestProgress).toContain('autobiographical writeback')
    expect(brief.latestProgress).toContain('durable self-carry layer')
    expect(brief.latestProgress).toContain('beyond local prompt shaping')
    expect(brief.latestProgress).toContain('unified person-state summary')
    expect(brief.latestProgress).toContain('self-evolution candidate continuity reasons')
    expect(normalizedDoc).toContain('proactive policy')
    expect(normalizedDoc).toContain('presence-only resident carry')
    expect(normalizedDoc).toContain('bounded redispatch confirmation')
    expect(normalizedDoc).toContain('permanent execution permission')
    expect(normalizedDoc).toContain('Broader provider-consumer candidates')
    expect(normalizedDoc).toContain('real invokeGenerateText / generateText / invokeStreamText / streamText sinks')
    expect(normalizedDoc).toContain('broader autonomous-dialogue candidates')
    expect(normalizedDoc).toContain('broader execution-dispatch candidates')
    expect(normalizedDoc).toContain('broader execution-preflight candidates')
    expect(normalizedDoc).toContain('semantics classification')
    expect(normalizedDoc).toContain('answer planning')
    expect(normalizedDoc).toContain('response charter shaping')
    expect(normalizedDoc).toContain('Broader execution follow-up continuity candidates')
    expect(normalizedDoc).toContain('execution-follow-up-entrypoint-candidate-audit.test.ts')
    expect(normalizedDoc).toContain('Broader recovery reentry candidates')
    expect(normalizedDoc).toContain('recovery-reentry-entrypoint-candidate-audit.test.ts')
    expect(normalizedDoc).toContain('future provider-facing generation families still need explicit registration')
    expect(normalizedDoc).toContain('future runtime-owned dialogue families still need explicit registration')
    expect(normalizedDoc).toContain('future main-process chat-start entry shapes still need explicit classification')
    expect(normalizedDoc).toContain('future renderer/store dialogue-entry shapes still need explicit classification')
    expect(normalizedDoc).toContain('future reopen-time route shapes still need explicit classification')
    expect(normalizedDoc).toContain('future execution dispatch families still need explicit owner registration')
    expect(normalizedDoc).toContain('future execution-preflight families still need explicit classification')
    expect(normalizedDoc).toContain('future execution follow-up families still need explicit registration')
    expect(normalizedDoc).toContain('future recovery reentry families still need explicit classification')
    expect(normalizedDoc).not.toContain('can hide between')
    expect(normalizedDoc).not.toContain('neighboring governance registries during parallel desktop development')
    expect(normalizedDoc).not.toContain('neighboring same-her route-authority audits during parallel desktop development')
    expect(normalizedDoc).toContain('runtime execution bridge and subconscious deferred bridge dispatch owners')
    expect(normalizedDoc).toContain('runtime-owned direct dispatch bridge')
    expect(normalizedDoc).toContain('blocked-dispatch safety-gate briefing seams')
    expect(normalizedDoc).toContain('single repo-level entrypoint governance registry')
    expect(normalizedDoc).toContain('shared root final-gate candidate-audit registry')
    expect(normalizedDoc).toContain('shared top-level completeness guard family registry')
    expect(normalizedDoc).toContain('renderer/store dialogue-entry candidates')
    expect(normalizedDoc).toContain('main-process chat-start candidates')
    expect(normalizedDoc).toContain('reopen-time return-side rebuild candidates')
    expect(normalizedDoc).toContain('provider-facing generation entry candidates')
    expect(normalizedDoc).toContain('project-state answer surfaces')
    expect(normalizedDoc).toContain('host-visible normalization seams')
    expect(normalizedDoc).toContain('guarded turn persistence')
    expect(normalizedDoc).toContain('execution-preflight context-repair candidates')
    expect(normalizedDoc).toContain('direct execution-dispatch bridge candidates')
    expect(normalizedDoc).toContain('recovery reentry')
    expect(normalizedDoc).toContain('execution follow-up continuity')
    expect(normalizedDoc).toContain('candidate families derive from one shared registry')
    expect(normalizedDoc).toContain('future entrypoint families are harder to hide between neighboring audits')
    expect(normalizedDoc).toContain('wholly new route families still are not automatically proven')
    expect(normalizedDoc).toContain('runtime-owned autonomous-dialogue family markers')
    expect(normalizedDoc).toContain('one shared source of truth')
    expect(normalizedDoc).toContain('recovery-reentry plus execution-follow-up continuity seams')
    expect(normalizedDoc).toContain('same explicit governance map')
    expect(normalizedDoc).toContain('direct main-chat-stream callers')
    expect(normalizedDoc).toContain('real startMainChatStream sinks')
    expect(normalizedDoc).toContain('merge-readiness / closure-readiness follow-ups')
    expect(normalizedDoc).toContain('completion-timing / language-drift follow-ups')
    expect(normalizedDoc).toContain('can merge to main')
    expect(normalizedDoc).toContain('how far the goal has landed')
    expect(normalizedDoc).toContain('when it is expected to close')
    expect(normalizedDoc).toContain('drifted into English')
    expect(normalizedDoc).toContain('already verified evidence')
    expect(normalizedDoc).toContain('unproven or still open')
    expect(normalizedDoc).toContain('misreporting full closure')
    expect(normalizedDoc).toContain('living-self host-facing system block')
    expect(normalizedDoc).toContain('canonical project preflight self-awareness line')
    expect(normalizedDoc).toContain('natural reply shaping')
    expect(normalizedDoc).toContain('visible-reply facade project-state resolution')
    expect(normalizedDoc).toContain('reply-surface planning')
    expect(normalizedDoc).toContain('same shared project-state seam as living-self and fallback paths')
    expect(normalizedDoc).toContain('ordinary dialogue system blocks')
    expect(normalizedDoc).toContain('unified Phase 1 closure dashboard')
    expect(normalizedDoc).toContain('runtime snapshot/digest')
    expect(normalizedDoc).toContain('project-state spine')
    expect(normalizedDoc).toContain('voice / face / motion / lipsync summaries')
    expect(normalizedDoc).toContain('canonical embodimentScript')
    expect(normalizedDoc).toContain('Dream, reminder, proactive, and reforge one-shot gateway prompts')
    expect(normalizedDoc).toContain('screen-semantic summary generation')
    expect(normalizedDoc).toContain('execution callback carry')
    expect(normalizedDoc).toContain('execution-result delivery learning')
    expect(normalizedDoc).toContain('long-horizon same-her memory')
    expect(normalizedDoc).toContain('Current conscious frame shaping')
    expect(normalizedDoc).toContain('still-open closure pressure')
    expect(normalizedDoc).toContain('thin runtime project shell')
    expect(normalizedDoc).toContain('richer same-her callback continuity')
    expect(normalizedDoc).toContain('Primary open-loop continuity pressure')
    expect(normalizedDoc).toContain('retrieval ranking')
    expect(normalizedDoc).toContain('autobiographical writeback')
    expect(normalizedDoc).toContain('durable self-carry layer')
    expect(normalizedDoc).toContain('beyond local prompt shaping')
    expect(normalizedDoc).toContain('unified person-state summary')
    expect(normalizedDoc).toContain('self-evolution candidate continuity reasons')
  })

  it('keeps docs/project-state.md directly anchored to the canonical closed foundations list', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.closedFoundations.length).toBeGreaterThan(2)

    for (const item of brief.closedFoundations)
      expect(normalizedDoc).toContain(item)
  })

  it('keeps docs/project-state.md directly anchored to the canonical same-her drift risk and emotional closure cue', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.sameHerDriftRisk).toBeTruthy()
    expect(brief.emotionalClosureCue).toBeTruthy()
    expect(normalizedDoc).toContain(brief.sameHerDriftRisk)
    expect(normalizedDoc).toContain(brief.emotionalClosureCue ?? '')
  })

  it('keeps docs/project-state.md directly anchored to the canonical open-loops list', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.openLoops.length).toBeGreaterThan(3)

    for (const item of brief.openLoops)
      expect(normalizedDoc).toContain(item)
  })

  it('keeps docs/project-state.md directly anchored to the canonical next closure target inside the canonical repo brief section', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)

    expect(brief.nextClosureTarget).toBeTruthy()
    expect(normalizedDoc).toContain(`Canonical next closure target: ${brief.nextClosureTarget}`)
  })

  it('keeps docs/project-state.md directly anchored to the canonical continuity progress summary inside the canonical repo brief section', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)
    const expected = normalizeProjectStateSyncText(`Canonical continuity progress summary: ${brief.continuityProgressSummary ?? ''}`)

    expect(brief.continuityProgressSummary).toBeTruthy()
    expect(normalizedDoc).toContain(expected)
  })

  it('keeps docs/project-state.md aligned with the latest continuity progress and next closure target', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/project-state.md', import.meta.url), 'utf8')
    const normalizedDoc = normalizeProjectStateSyncText(doc)
    const secondPassRewriteProgress = brief.memoryAnthropomorphismProgress.find(item =>
      item.includes('second-pass rewrite guidance'),
    ) ?? ''
    const emotionalKernelOwnerProgress = brief.memoryAnthropomorphismProgress.find(item =>
      item.includes('shared emotional owner'),
    ) ?? ''
    const emotionalKernelConvergenceProgress = brief.memoryAnthropomorphismProgress.find(item =>
      item.includes('emotional-memory-initiative-embodiment'),
    ) ?? ''
    expect(doc).toContain('Alicization is a local-first digital life project.')
    expect(doc).toContain('What is this project trying to become?')
    expect(doc).toContain('What has already become real enough to count as closed?')
    expect(doc).toContain('Which loops are still open and should be treated as active development pressure?')
    expect(doc).toContain(brief.continuityProgressSummary ?? brief.memoryAnthropomorphismProgress.at(-1) ?? '')
    expect(doc).toContain('visible reply opening discipline')
    expect(doc).toContain('second-pass rewrite guidance')
    expect(normalizedDoc).toContain(secondPassRewriteProgress)
    expect(doc).toContain('normal governed rewrite requests')
    expect(doc).toContain('critic anti-restart guard')
    expect(normalizedDoc).toContain('start over')
    expect(normalizedDoc).toContain('fresh opening')
    expect(doc).toContain('hover-first proactive restraint under later noisy pressure')
    expect(normalizedDoc).toContain('silent-observe / hover-first posture')
    expect(normalizedDoc).toContain('fresh proactive approach')
    expect(normalizedDoc).toContain('voice, face, and motion summaries aligned on the same measured-return, repair-before-closeness, or rest-protective quiet-companionship line')
    expect(normalizedDoc).toContain('measured-return, repair-before-closeness, or rest-protective quiet-companionship line')
    expect(normalizedDoc).toContain('recollection continuity is now better locked through visible-reply governance')
    expect(normalizedDoc).toContain('callback-afterglow same-her carry now also has one explicit route-level audit')
    expect(normalizedDoc).toContain('the final visible reply itself continues the lower-pressure callback seam')
    expect(normalizedDoc).toContain('one further noisy-detour follow-up can now keep a multi-segment visible reply')
    expect(normalizedDoc).toContain('quieter settle-tail frame after speech now no longer steals the last visible reply lane')
    expect(normalizedDoc).toContain('last-frame diagnostics still preserve the softer tail release')
    expect(doc).toContain('runtime-main-chat-prelude')
    expect(doc).toContain('main-chat-session-runtime')
    expect(doc).toContain('chat-start-awareness-audit.ts')
    expect(doc).toContain('chat-start-awareness-audit.test.ts')
    expect(doc).toContain('chat-entry-awareness-audit.ts')
    expect(doc).toContain('chat-entry-awareness-audit.test.ts')
    expect(doc).toContain('provider-facing contract normalization')
    expect(doc).toContain('preDialogueAwarenessSummary')
    expect(doc).toContain('reply-deliberator')
    expect(doc).toContain('companionHeadlineLine')
    expect(doc).toContain('opening beat')
    expect(doc).toContain('shared project-state resolver')
    expect(doc).toContain('final visible-reply settlement')
    expect(doc).toContain('host-visible project-state audit')
    expect(doc).toContain(brief.nextClosureTarget)
    expect(normalizedDoc).toContain('long-run same-her continuity')
    expect(normalizedDoc).toContain('emotional-memory-initiative-embodiment')
    expect(normalizedDoc).toContain('affective residue')
    expect(normalizedDoc).toContain('voice / face / motion / lipsync')
    expect(doc).toContain('Runtime-owned proactive initiative now also has one explicit compact same-her closure loop')
    expect(normalizedDoc).toContain('motive seed')
    expect(normalizedDoc).toContain('next-session feedback carry')
    expect(normalizedDoc).toContain('post-answer dream carry')
    expect(normalizedDoc).toContain('next project-state answer carry')
    expect(normalizedDoc).toContain('noisy-desktop detour persistence')
    expect(normalizedDoc).toContain('dream-to-long-horizon self-carry bridge')
    expect(normalizedDoc).toContain('long-horizon self-carry boundary')
    expect(normalizedDoc).toContain('next conscious frame')
    expect(normalizedDoc).toContain('final reply planning')
    expect(doc).toContain('proactive-feedback-next-project-state-answer-audit.test.ts')
    expect(doc).toContain('proactive-feedback-post-answer-dream-carry-audit.test.ts')
    expect(doc).toContain('proactive-feedback-dream-long-horizon-bridge-audit.test.ts')
    expect(doc).toContain('proactive-feedback-long-horizon-conscious-frame-bridge-audit.test.ts')
    expect(doc).toContain('noisy-desktop-autonomous-dialogue-persistence-audit.test.ts')
    expect(doc).toContain('proactive-same-her-bridge-audit.test.ts')
    expect(normalizedDoc).toContain('colder closure line explicit at the repo-truth level too')
    expect(doc).toContain('autonomous-dialogue-closure-loop-audit.test.ts')
    expect(normalizedDoc).toContain('proactive same-her bridge')
    expect(normalizedDoc).toContain('proactive anthropomorphic host-visible bridge')
    expect(normalizedDoc).toContain('hover-first policy restraint')
    expect(normalizedDoc).toContain('visible quiet hold')
    expect(normalizedDoc).toContain('active-self rejoin seam')
    expect(normalizedDoc).toContain('visible proactive hold')
    expect(normalizedDoc).toContain('subconscious carry')
    expect(normalizedDoc).toContain('quiet-companionship host-visible lane summaries')
    expect(normalizedDoc).toContain('same-living-self host-visible inward carry')
    expect(normalizedDoc).toContain('more anthropomorphic same living host-visible line')
    expect(normalizedDoc).toContain('longer noisy desktop runs')
    expect(emotionalKernelOwnerProgress).toContain('shared emotional owner')
    expect(emotionalKernelOwnerProgress).toContain('emotional-kernel-v1')
    expect(emotionalKernelOwnerProgress).toContain('one common inner state')
    expect(emotionalKernelConvergenceProgress).toContain('emotional-memory-initiative-embodiment')
    expect(emotionalKernelConvergenceProgress).toContain('voice / face / motion / lipsync')
    expect(normalizedDoc).toContain(emotionalKernelOwnerProgress)
    expect(normalizedDoc).toContain(emotionalKernelConvergenceProgress)
    expect(doc).toContain('cross-surface dialogue-entry candidates')
    expect(doc).toContain('project-awareness-cross-surface-entrypoint-audit.test.ts')
    expect(normalizedDoc).toContain('pre-dialogue transport and chat-entry discovery union')
    expect(doc).toContain('entrypoint-governance-registry-audit.test.ts')
    expect(normalizedDoc).toContain('pre-dialogue transport')
    expect(normalizedDoc).toContain('mirrored into chat-entry governance')
    expect(normalizedDoc).toContain('Broader project-state answer-governance candidates')
    expect(normalizedDoc).toContain('broader runtime dialogue-normalization candidates')
    expect(normalizedDoc).toContain('broader guarded turn persistence candidates')
    expect(normalizedDoc).toContain('project-status answer surfaces')
    expect(normalizedDoc).toContain('host-visible normalization seams')
    expect(normalizedDoc).toContain('future project-status answer surfaces')
    expect(normalizedDoc).toContain('future host-visible normalization seams')
    expect(normalizedDoc).toContain('future guarded persistence families still need explicit classification')
    expect(normalizedDoc).toContain('Broader provider-consumer candidates')
    expect(normalizedDoc).toContain('broader autonomous-dialogue candidates')
    expect(normalizedDoc).toContain('broader execution-dispatch candidates')
    expect(normalizedDoc).toContain('broader execution-preflight candidates')
    expect(normalizedDoc).toContain('Broader execution follow-up continuity candidates')
    expect(normalizedDoc).toContain('execution-follow-up-entrypoint-candidate-audit.test.ts')
    expect(normalizedDoc).toContain('Broader recovery reentry candidates')
    expect(normalizedDoc).toContain('recovery-reentry-entrypoint-candidate-audit.test.ts')
    expect(normalizedDoc).toContain('future provider-facing generation families still need explicit registration')
    expect(normalizedDoc).toContain('future runtime-owned dialogue families still need explicit registration')
    expect(normalizedDoc).toContain('future execution dispatch families still need explicit owner registration')
    expect(normalizedDoc).toContain('future execution-preflight families still need explicit classification')
    expect(normalizedDoc).toContain('future execution follow-up families still need explicit registration')
    expect(normalizedDoc).toContain('future recovery reentry families still need explicit classification')
    expect(normalizedDoc).toContain('runtime execution bridge and subconscious deferred bridge dispatch owners')
    expect(normalizedDoc).toContain('runtime-owned direct dispatch bridge')
    expect(normalizedDoc).toContain('blocked-dispatch safety-gate briefing seams')
  })

  it('keeps docs/project-state-audit.md aligned with conscious-frame project-state awareness coverage and free of stale coverage ids', () => {
    const coverage = resolveAlicizationProjectStateCoverage()
    const doc = readFileSync(new URL('../../../../../../docs/project-state-audit.md', import.meta.url), 'utf8')
    const coverageIds = coverage.map(item => item.id).sort()
    const docEntries = collectProjectStateAuditEntries(doc)
    const docEntryCounts = collectProjectStateAuditEntryCounts(doc)
    const proactiveFeedbackRouteRow = findProjectStateAuditRouteRow(
      doc,
      'Proactive feedback settlement / next chat continuity / dream carry',
    )
    const unknownFutureEntrypointsRouteRow = findProjectStateAuditRouteRow(
      doc,
      'Unknown future dialogue entrypoints',
    )

    expect(coverage.length).toBeGreaterThan(20)
    expect(collectProjectStateAuditCoverageIds(doc)).toEqual(coverageIds)

    for (const item of coverage) {
      expect(item.responsibility).toBeTruthy()
      expect(item.proof).toBeTruthy()
      expect(docEntryCounts.get(item.id)).toEqual({
        responsibility: 1,
        proof: 1,
      })
      expect(docEntries.get(item.id)).toEqual({
        responsibility: item.responsibility,
        proof: item.proof,
      })
    }

    expect(doc).toContain('provider-wrapper-authority')
    expect(doc).toContain('provider-dispatch-owner')
    expect(doc).toContain('typed-gateway-consumer')
    expect(doc).toContain('mirrored into chat-entry governance')
    expect(doc).toContain('broader cross-surface dialogue-entry candidates')
    expect(doc).toContain('project-awareness-cross-surface-entrypoint-audit.test.ts')
    expect(doc).toContain('pre-dialogue-transport-entrypoint-audit.ts')
    expect(doc).toContain('chat-start-entrypoint-candidate-audit.test.ts')
    expect(doc).toContain('autonomous-dialogue-entrypoint-candidate-audit.test.ts')
    expect(doc).toContain('shared route-authority registry')
    expect(doc).toContain('explicit allowed overlaps')
    expect(doc).toContain('shared same-her project-state answer contract')
    expect(doc).toContain('single repo-level entrypoint governance registry')
    expect(doc).toContain('shared root final-gate candidate-audit registry')
    expect(doc).toContain('shared top-level completeness guard family registry')
    expect(doc).toContain('renderer/store dialogue-entry candidates')
    expect(doc).toContain('main-process chat-start candidates')
    expect(doc).toContain('reopen-time return-side rebuild candidates')
    expect(doc).toContain('provider-facing generation entry candidates')
    expect(doc).toContain('project-state answer surfaces')
    expect(doc).toContain('host-visible normalization seams')
    expect(doc).toContain('guarded turn persistence')
    expect(doc).toContain('execution-preflight context-repair candidates')
    expect(doc).toContain('direct execution-dispatch bridge candidates')
    expect(doc).toContain('recovery reentry')
    expect(doc).toContain('execution follow-up continuity')
    expect(doc).toContain('candidate families derive from one shared registry')
    expect(doc).toContain('future entrypoint families are harder to hide between neighboring audits')
    expect(unknownFutureEntrypointsRouteRow).toContain('single repo-level entrypoint governance registry')
    expect(unknownFutureEntrypointsRouteRow).toContain('shared root final-gate candidate-audit registry')
    expect(unknownFutureEntrypointsRouteRow).toContain('shared top-level completeness guard family registry')
    expect(unknownFutureEntrypointsRouteRow).toContain('renderer/store dialogue-entry candidates')
    expect(unknownFutureEntrypointsRouteRow).toContain('main-process chat-start candidates')
    expect(unknownFutureEntrypointsRouteRow).toContain('reopen-time return-side rebuild candidates')
    expect(unknownFutureEntrypointsRouteRow).toContain('provider-facing generation entry candidates')
    expect(unknownFutureEntrypointsRouteRow).toContain('project-state answer surfaces')
    expect(unknownFutureEntrypointsRouteRow).toContain('host-visible normalization seams')
    expect(unknownFutureEntrypointsRouteRow).toContain('guarded turn persistence')
    expect(unknownFutureEntrypointsRouteRow).toContain('execution-preflight context-repair candidates')
    expect(unknownFutureEntrypointsRouteRow).toContain('direct execution-dispatch bridge candidates')
    expect(unknownFutureEntrypointsRouteRow).toContain('recovery reentry')
    expect(unknownFutureEntrypointsRouteRow).toContain('execution follow-up continuity')
    expect(unknownFutureEntrypointsRouteRow).toContain('candidate families derive from one shared registry')
    expect(unknownFutureEntrypointsRouteRow).toContain('future entrypoint families are harder to hide between neighboring audits')
    expect(unknownFutureEntrypointsRouteRow).toContain('wholly new route families still are not automatically proven')
    expect(proactiveFeedbackRouteRow).toContain('next project-state answer carry')
    expect(proactiveFeedbackRouteRow).toContain('post-answer detour persistence')
    expect(proactiveFeedbackRouteRow).toContain('post-answer dream carry')
    expect(proactiveFeedbackRouteRow).toContain('proactive-feedback-next-project-state-answer-audit.test.ts')
    expect(proactiveFeedbackRouteRow).toContain('proactive-feedback-post-answer-detour-persistence-audit.test.ts')
    expect(proactiveFeedbackRouteRow).toContain('proactive-feedback-post-answer-dream-carry-audit.test.ts')
    expect(doc).toContain('next project-state answer carry now also ties settled proactive feedback continuity block')
    expect(doc).toContain('post-answer detour persistence now also ties settled proactive feedback continuity block')
    expect(doc).toContain('post-answer dream carry now also ties settled proactive feedback continuity block')
    expect(doc).toContain('proactive-feedback-next-project-state-answer-audit.test.ts')
    expect(doc).toContain('proactive-feedback-post-answer-detour-persistence-audit.test.ts')
    expect(doc).toContain('proactive-feedback-post-answer-dream-carry-audit.test.ts')
    expect(doc).toContain('project-status answers cannot silently drop identity, landed progress, open closure, next closure target, or same-her continuity')
    expect(doc).toContain('runtime-owned direct dispatch bridge')
    expect(doc).toContain('projectStateSameHerSelfLineDrift')
    expect(doc).toContain('same-her self line degrades into generic guidance')
    expect(doc).toContain('desktop renderer App.vue structured-clone handoff is now explicit as one desktop-root bridge across pre-dialogue transport, renderer chat-entry governance, and return-side project-awareness rebuild')
    expect(doc).toContain('desktop send-time and reopen-time same-her carry')
    expect(doc).not.toContain('can hide between')
    expect(doc).not.toContain('neighboring governance registries during parallel desktop development')
    expect(doc).not.toContain('neighboring same-her route-authority audits during parallel desktop development')
  })

  it('keeps repo-level hardening coverage anchored to at least one cold audit test instead of drifting back to hot-spec-only proof lists', () => {
    const coverage = resolveAlicizationProjectStateCoverage()
    const hardeningItems = coverage.filter(item => item.id.endsWith('-hardening'))

    expect(hardeningItems.length).toBeGreaterThan(10)

    for (const item of hardeningItems)
      expect(item.proof).toMatch(/audit\.test\.ts/)
  })

  it('keeps docs/pre-dialogue-project-awareness-matrix.md aligned with deeper start/runtime awareness boundaries', () => {
    const brief = resolveAlicizationProjectStateBrief()
    const doc = readFileSync(new URL('../../../../../../docs/pre-dialogue-project-awareness-matrix.md', import.meta.url), 'utf8')

    expect(doc).toContain(brief.identity)
    expect(doc).toContain(brief.currentPhase)
    expect(doc).toContain('runtime-main-chat-prelude.ts')
    expect(doc).toContain('runtime-main-chat-prelude-project-awareness-regression.test.ts')
    expect(doc).toContain('runtime-main-chat-prelude-project-state-system-block-regression.test.ts')
    expect(doc).toContain('main-chat-session-runtime-project-awareness-regression.test.ts')
    expect(doc).toContain('provider-facing contract normalization')
    expect(doc).toContain('project-state-provider-consumer-audit.ts')
    expect(doc).toContain('provider-consumer-entrypoint-candidate-audit.test.ts')
    expect(doc).toContain('runtime-main-gateway-one-shot.ts')
    expect(doc).toContain('runtime.ts')
    expect(doc).toContain('typed audited')
    expect(doc).toContain('reopen-persistence-project-awareness-audit.test.ts')
    expect(doc).toContain('replay-emission-project-awareness-audit.test.ts')
    expect(doc).toContain('reminder-callback-project-awareness-audit.test.ts')
    expect(doc).toContain('execution-surface-project-awareness-audit.test.ts')
    expect(doc).toContain('active-dialogue-project-awareness-audit.test.ts')
    expect(doc).toContain('memory-active-self-project-awareness-audit.test.ts')
    expect(doc).toContain('host-visible-same-her-continuity-audit.test.ts')
    expect(doc).toContain('chat-entry-route-project-awareness-audit.test.ts')
    expect(doc).toContain('chat-entry-composer-surface-audit.test.ts')
    expect(doc).toContain('chat-entry-main-chat-fallback-dispatch.test.ts')
    expect(doc).toContain('chat-entry-devtools-fallback-dispatch.test.ts')
    expect(doc).toContain('desktop renderer App.vue structured-clone handoff now sits in the pre-dialogue transport, chat-entry governance, and return-side project-awareness rebuild chains')
    expect(doc).toContain('desktop main chat surface fallback sends')
    expect(doc).toContain('transport-only seam')
    expect(doc).toContain('pre-dialogue-transport-entrypoint-audit.ts')
    expect(doc).toContain('shared discovery helper')
    expect(doc).toContain('chat-start-runtime-project-awareness-audit.test.ts')
    expect(doc).toContain('chat-start-result-project-awareness-audit.test.ts')
    expect(doc).toContain('timeout-fallback-project-awareness-audit.test.ts')
    expect(doc).toContain('background-recovery-project-awareness-audit.test.ts')
    expect(doc).toContain('run-lifecycle-project-awareness-audit.test.ts')
    expect(doc).toContain('main-chat-background-rules.test.ts')
    expect(doc).toContain('session-runtime-project-awareness-audit.test.ts')
    expect(doc).toContain('reminder-delivery-project-awareness-audit.test.ts')
    expect(doc).toContain('subconscious-persistence-project-awareness-audit.test.ts')
    expect(doc).toContain('proactive-visible-project-awareness-audit.test.ts')
    expect(doc).toContain('stream-meta-project-awareness-audit.test.ts')
    expect(doc).toContain('embodiment-project-awareness-audit.test.ts')
    expect(doc).toContain('repeated-detour-reunion-persistence-audit.test.ts')
    expect(doc).toContain('long-horizon-project-awareness-audit.test.ts')
    expect(doc).toContain('quick-reply-project-awareness-audit.test.ts')
    expect(doc).toContain('renderer-diagnostics-project-awareness-audit.test.ts')
    expect(doc).toContain('Renderer-side session fallback now also has an explicit route-level reopen proof')
    expect(doc).toContain('Runtime persistence and replay emission now also have an explicit route-level proof')
    expect(doc).toContain('Reminder/execution-callback delivery persistence now also has an explicit route-level proof')
    expect(doc).toContain('Execution-only route surfaces now also have an explicit route-level proof')
    expect(doc).toContain('Compact active-dialogue follow-up replies now also have their own route-level proof')
    expect(doc).toContain('Known renderer/chat entry routes now also have dedicated route-level proof')
    expect(doc).toContain('Thin host-facing composer surfaces now also have dedicated route-level proof')
    expect(doc).toContain('shared text-composer send authority')
    expect(doc).toContain('thin host-facing composer surfaces')
    expect(doc).toContain('future renderer/store dialogue-entry shapes still need explicit classification')
    expect(doc).toContain('web/pocket devtools performance-playground explicit pre-dialogue identity sends')
    expect(doc).toContain('deeper main-process start/runtime seams now also have dedicated route-level proof')
    expect(doc).toContain('Chat-start result settlement now also has dedicated route-level proof')
    expect(doc).toContain('timeout fallback recovery now also has dedicated route-level proof')
    expect(doc).toContain('background recovery now also has dedicated route-level proof')
    expect(doc).toContain('Lifecycle timeout recovery finish/emit now also has dedicated route-level proof')
    expect(doc).toContain('minimal timeout-recovery compaction now also preserves the richer executive answer brief')
    expect(doc).toContain('Session-runtime provider-facing preparation now also has dedicated route-level proof')
    expect(doc).toContain('Host-visible reminder delivery now also has dedicated route-level proof')
    expect(doc).toContain('Subconscious persistence and deferred carry now also have dedicated route-level proof')
    expect(doc).toContain('Proactive visible utterance realization now also has dedicated route-level proof')
    expect(doc).toContain('Stream meta / host-visible meta emission now also has dedicated route-level proof')
    expect(doc).toContain('Embodiment-facing body/voice/face/motion continuity surfaces now also have dedicated route-level proof')
    expect(doc).toContain('Renderer diagnostics now also have dedicated route-level proof')
    expect(doc).toContain('host-corrected same-person continuity as final `sameHerHoldDetail` / `continuityCue` carry')
    expect(doc).toContain('Organic-memory recall and current-conscious-frame shaping now also have an explicit route-level proof')
    expect(doc).toContain('repeated-detour persistence audit showing the same-her route can survive multiple reopenings before later-turn reunion summaries form')
    expect(doc).toContain('noisy-desktop detour persistence')
    expect(doc).toContain('noisy-desktop-autonomous-dialogue-persistence-audit.test.ts')
    expect(doc).toContain('next project-state answer carry')
    expect(doc).toContain('proactive-feedback-next-project-state-answer-audit.test.ts')
    expect(doc).toContain('post-answer dream carry')
    expect(doc).toContain('proactive-feedback-post-answer-dream-carry-audit.test.ts')
    expect(doc).toContain('Durable long-horizon carry and host-facing closure briefing now also have dedicated route-level proof')
    expect(doc).toContain('Front-stage quick-reply closure itself now also has dedicated route-level proof')
    expect(doc).toContain('The earlier desktop execution chain is now also explicitly represented in the proof map')
    expect(doc).toContain('Early desktop execution-chain carry now also has dedicated route-level proof')
    expect(doc).toContain('Execution callback runtime shaping now also has dedicated route-level proof')
    expect(doc).toContain('Execution-result afterglow learning now also has dedicated route-level proof')
    expect(doc).toContain('Execution follow-up obligation now also has dedicated route-level proof')
    expect(doc).toContain('Ledger-backed execution history reopen now also has dedicated route-level proof')
    expect(doc).toContain('Live session-runtime execution follow-up assembly now also has dedicated route-level proof')
    expect(doc).toContain('task-thread dispatch now also explicitly persists identity, landed progress, open closure, same-her drift guard, and pre-dialogue awareness')
    expect(doc).toContain('desktop-execution-chain-project-awareness-audit.test.ts')
    expect(doc).toContain('execution-callback-runtime-project-awareness-audit.test.ts')
    expect(doc).toContain('execution-afterglow-project-awareness-audit.test.ts')
    expect(doc).toContain('execution-follow-up-obligation-project-awareness-audit.test.ts')
    expect(doc).toContain('execution-ledger-follow-up-project-awareness-audit.test.ts')
    expect(doc).toContain('execution-follow-up-session-runtime-project-awareness-audit.test.ts')
    expect(doc).toContain('agent-runtime.test.ts')
    expect(doc).toContain('execution-runtime-context.test.ts')
    expect(doc).toContain('task-thread-dispatcher.test.ts')
    expect(doc).toContain('runtime-execution-feedback.test.ts')
    expect(doc).toContain('route-authority-boundary-registry-audit.test.ts')
    expect(doc).toContain('shared boundary helper')
    expect(doc).toContain('overlap-aware repo-level map')
    expect(doc).toContain('main-chat-background-run.ts')
    expect(doc).toContain('runtime-delivery-reminders.ts')
    expect(doc).toContain('runtime-subconscious-tick.ts')
    expect(doc).toContain('runtime.ts')
    expect(doc).toContain('return-side project-awareness rebuild')
    expect(doc).toContain('packages/stage-ui/src/stores/chat.ts')
    expect(doc).toContain('explicit overlap audits now also tie outbound pre-dialogue identity construction and return-side stream ingest to the same')
    expect(doc).toContain('explicit overlap audits tying host-visible normalization, guarded persistence entry, proactive carry, and runtime continuity fallback to concrete same-her seams now keep')
    expect(doc).toContain('route-level host-visible continuity audit now also tying stream meta to visible proactive hold')
    expect(doc).toContain('Route-level pre-dialogue reasons sync note')
    expect(doc).toContain('shared pre-dialogue awareness/closure structures now also keep explicit `Proactive same-her gap:` carry inside `reasonPreview` / `reasons`')
    expect(doc).toContain('so the still-open anthropomorphic initiative gap is already part of the same before-answer self-brief')
    expect(doc).toContain('broader chat-start candidates')
    expect(doc).toContain('future main-process chat-start entry shapes still need explicit classification')
    expect(doc).toContain('broader autonomous-dialogue candidates')
    expect(doc).toContain('future runtime-owned dialogue families still need explicit registration')
    expect(doc).toContain('execution-dispatch-entrypoint-candidate-audit.test.ts')
    expect(doc).toContain('execution-follow-up-entrypoint-candidate-audit.test.ts')
    expect(doc).toContain('broader provider-consumer candidates')
    expect(doc).toContain('future provider-facing generation families still need explicit registration')
    expect(doc).toContain('broader execution-dispatch candidates')
    expect(doc).toContain('Broader execution follow-up continuity candidates')
    expect(doc).toContain('future execution follow-up families still need explicit registration')
    expect(doc).toContain('Broader recovery reentry candidates')
    expect(doc).toContain('recovery-reentry-entrypoint-candidate-audit.test.ts')
    expect(doc).toContain('future recovery reentry families still need explicit classification')
    expect(doc).toContain('runtime execution bridge and subconscious deferred bridge')
    expect(doc).toContain('runtime-owned direct dispatch bridge')
    expect(doc).toContain('runtime-governance normalization-time project-state audit carry')
    expect(doc).toContain('normalization-time project-state audit carry')
    expect(doc).toContain('keeps next-closure-target carry explicit through rewrite preservation')
    expect(doc).toContain('callback next-closure-target carry')
    expect(doc).toContain('second-pass transport-failure callback next-closure-target carry')
    expect(doc).toContain('final-realization callback next-closure-target carry')
    expect(doc).toContain('final-settlement callback next-closure-target carry')
    expect(doc).toContain('return-side-reopen-through-visible-reply same-her bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('desktop same-her full-cycle bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution desktop full-cycle bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution desktop execution long-run continuity bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution anthropomorphic host-visible bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('proactive anthropomorphic host-visible bridge now also ties proactive same-her outward carry into rest-protective proactive feedback, quiet-companionship host-visible lane summaries, same-living-self host-visible inward carry, and the more anthropomorphic same living host-visible line')
    expect(doc).toContain('proactive remembered emotional carry bridge now also ties proactive anthropomorphic host-visible carry into self-evolution remembered emotional carry, affective-residue room-making carry, and longer emotion-memory-voice-motion convergence')
    expect(doc).toContain('proactive pre-dialogue planning bridge now also ties proactive remembered emotional carry into self-evolution durable self-recognition, current-conscious-frame same-her grounding, current-conscious-frame turn shaping, and answer-planner same-her closure planning')
    expect(doc).toContain('self-evolution remembered emotional carry bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution durable self-recognition bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution pre-dialogue planning bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution long-run follow-through bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution host-visible closure target bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution return-side reentry bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution return-side reentry bridge now also inherits the richer next closure target explicit')
    expect(doc).toContain('self-evolution replay reopen continuity bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution downstream visible reply bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution answer governance bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('self-evolution pre-dialogue reply-planning bridge now also ties self-evolution pre-dialogue planning into self-evolution answer governance, answer planning, response charter shaping, and executive answer briefing')
    expect(doc).toContain('self-evolution reply-planning governance bridge now also keeps callback next-closure-target carry explicit')
    expect(doc).toContain('proactive downstream visible-reply bridge now also ties proactive pre-dialogue reply-planning into self-evolution downstream visible reply, answer-compiler supporting reality, reply-deliberator outward planning, final visible-reply gating, and visible-reply realization')
    expect(doc).toContain('proactive replay reopen continuity bridge now also ties proactive downstream visible-reply carry into guarded turn persistence, replay emission, and reopen persistence')
    expect(doc).toContain('same-living-self return-side observability bridge now also keeps the richer next closure target explicit')
    expect(doc).toContain('stressed recovery same-her bridge now ties one-shot provider fallback, timeout fallback, background recovery, and lifecycle finish onto one same-her project-awareness line')
    expect(doc).toContain('self-evolution baseline lifecycle chain now also keeps restrained callback-line cadence carry explicit')
    expect(doc).toContain('self-evolution governance chain now also keeps restrained callback-line cadence carry explicit')
    expect(doc).toContain('future execution dispatch families still need explicit owner registration')
    expect(doc).not.toContain('can hide between')
    expect(doc).not.toContain('neighboring governance registries during parallel desktop development')
    expect(doc).not.toContain('neighboring same-her route-authority audits during parallel desktop development')
    expect(doc).toContain('Stable long-term personhood, natural recall, restrained helpful initiative, reliable execution policy, and unified dialogue/voice/motion still need more sustained proof in use.')
    expect(doc).toContain(brief.nextClosureTarget)
  })
})
