import { describe, expect, it } from 'vitest'

import {
  buildRecallGovernor,
  buildRecallGovernorSystemBlock,
} from './recall-governor'

describe('buildRecallGovernor', () => {
  it('suppresses associative recall for scene-repair turns', () => {
    const governor = buildRecallGovernor({
      now: 10_000,
      dialogueWorldThread: {
        activeThread: 'Repair the stale browser anchor before answering.',
        currentQuestion: 'What is on screen right now?',
        openLoops: ['What is on screen right now?'],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'guarded',
        memoryMode: 'scene-anchored',
        recallKeys: ['current screen'],
        lastUserMove: 'What is on screen right now?',
        lastAssistantMove: 'The old browser anchor may be stale.',
        lastOutcome: 'repairing',
        pendingValidation: null,
        confidence: 0.9,
        narrative: [],
        updatedAt: 10_000,
      },
      conversationState: {
        jointThread: 'Repair the stale browser anchor before answering.',
        hostMove: 'What is on screen right now?',
        activeProject: null,
        unansweredQuestion: 'What is on screen right now?',
        owedRepair: 'The earlier browser anchor is stale.',
        activeCommitments: [],
        relationFrame: 'repair',
        continuityPolicy: 'scene-before-memory',
        memoryMode: 'scene-anchored',
        memoryQueryHints: ['current screen'],
        shouldHoldThread: true,
        confidence: 0.88,
        narrative: [],
        updatedAt: 10_000,
      },
      answerCompiler: {
        answerSubject: 'visible-scene',
        screenReferenceMode: 'required',
        speechObligation: 'repair-truth',
        relationMove: 'repair',
        turnMode: 'screen-repair',
        responseMode: 'repair-and-reanchor',
        recommendedAct: 'ask-reground',
        evidenceMode: 'repair-first',
        openingStyle: 'direct-correction',
        personaKernelMode: 'muted',
        relationshipPosture: 'restrained',
        openingDirective: 'Repair the stale anchor first.',
        openingClaim: 'The older screen anchor is stale.',
        supportingReality: [],
        uncertaintyBoundary: 'Need a fresh look.',
        careVector: null,
        nextMove: 'Ask for a fresh look.',
        suppressAssociativeRecall: true,
        labelCarryAsMemory: true,
        maxSentences: 3,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.9,
        narrative: [],
        updatedAt: 10_000,
      },
    })

    expect(governor).toEqual(expect.objectContaining({
      mode: 'scene',
      suppressAssociativeRecall: true,
      allowRecalledFragments: false,
      recalledFragmentCap: 0,
      recalledFragmentSourceBudget: [],
      carryAsMemory: true,
    }))
  })

  it('admits emotionally resonant memory when the live thread is felt rather than purely visual', () => {
    const governor = buildRecallGovernor({
      now: 20_000,
      dialogueWorldThread: {
        activeThread: 'The host is still drained from the late-night debugging session.',
        currentQuestion: null,
        openLoops: ['The session is still emotionally heavy.'],
        recentlyResolvedLoops: [],
        carriedFacts: ['late-night debugging'],
        relationDrift: 'warming',
        memoryMode: 'emotional-resonance',
        recallKeys: ['late-night debugging', 'emotional_tension:late-night-drain'],
        lastUserMove: '我有点累了',
        lastAssistantMove: '先停一下也可以。',
        lastOutcome: 'aligned',
        pendingValidation: null,
        confidence: 0.74,
        narrative: [],
        updatedAt: 20_000,
      },
      conversationState: {
        jointThread: 'The host is still drained from the late-night debugging session.',
        hostMove: 'I am getting tired.',
        activeProject: null,
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'care',
        continuityPolicy: 'answer-then-carry',
        memoryMode: 'emotional-resonance',
        memoryQueryHints: ['late-night debugging', 'fatigue'],
        shouldHoldThread: false,
        confidence: 0.72,
        narrative: [],
        updatedAt: 20_000,
      },
      replyDeliberation: {
        selectedMotive: 'care',
        speakingFrom: 'dialogue-bond',
        memoryMode: 'emotional-resonance',
        openingBeat: 'Acknowledge the host condition first.',
        whyThisReplyNow: 'The host is still carrying late-night drain.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.78,
        narrative: [],
        updatedAt: 20_000,
      },
      privateThought: {
        stance: 'care',
        confidence: 0.75,
        rationaleTags: ['late-night'],
        thoughtText: 'Stay near the host and keep the tone soft.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'concerned',
        expiresAt: 60_000,
        afterglowFromScenario: null,
        emotionalTension: 'late-night-drain',
      },
    })

    expect(governor).toEqual(expect.objectContaining({
      mode: 'emotional-resonance',
      suppressAssociativeRecall: false,
      allowActiveThoughts: true,
      allowRecalledFragments: true,
      recalledFragmentCap: 3,
    }))
    expect(governor?.affectAnchors).toEqual(expect.arrayContaining([
      'emotional_tension:late-night-drain',
      'reply_motive:care',
    ]))
    expect(governor?.salienceBias).toBeGreaterThan(0.7)
    expect(governor?.recalledFragmentSourceBudget).toEqual(expect.arrayContaining([
      { sourceKind: 'reflection-ledger', maxItems: 2 },
      { sourceKind: 'dialogue-turn', maxItems: 1 },
      { sourceKind: 'fact-ledger', maxItems: 1 },
    ]))
    expect(buildRecallGovernorSystemBlock(governor)).toContain('[ALICIZATION_RECALL_GOVERNOR]')
  })

  it('injects live scene attachment cues into recall governor for task-thread recollection', () => {
    const governor = buildRecallGovernor({
      now: 25_000,
      dialogueWorldThread: {
        activeThread: 'Keep repairing the runtime seam in the current diff.',
        currentQuestion: 'Can you keep doing it the way you did before?',
        openLoops: ['repair the runtime seam'],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'steady',
        memoryMode: 'task-thread',
        recallKeys: ['runtime seam', 'cli patch'],
        lastUserMove: '继续按之前那样修这个 runtime seam',
        lastAssistantMove: '我先沿着 diff 和 terminal patch flow 走。',
        lastOutcome: 'pending',
        pendingValidation: null,
        confidence: 0.82,
        narrative: [],
        updatedAt: 25_000,
      },
      conversationState: {
        jointThread: 'repair the runtime seam',
        hostMove: '继续按之前那样修这个 runtime seam',
        activeProject: 'runtime seam',
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: ['runtime seam', 'cli patch'],
        shouldHoldThread: true,
        confidence: 0.8,
        narrative: [],
        updatedAt: 25_000,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'helpful',
        recommendedAct: 'answer',
        suppressAssociativeRecall: false,
        labelCarryAsMemory: false,
      } as any,
      replyDeliberation: {
        selectedMotive: 'guide',
        speakingFrom: 'task-thread',
        memoryMode: 'task-thread',
        openingBeat: 'Continue from the known seam.',
        whyThisReplyNow: 'The host wants the earlier working procedure reused in the same live workspace.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.8,
        narrative: [],
        updatedAt: 25_000,
      },
      sceneContext: {
        cueSummary: 'Cursor diff lane with terminal patch flow',
        appName: 'Cursor',
        processName: 'Cursor',
        targetTitle: 'runtime.ts diff',
        scenario: 'coding',
        workloadKind: 'coding',
        contentKind: 'diff',
      },
    })

    expect(governor?.sceneAnchor).toContain('Cursor diff lane with terminal patch flow')
    expect(governor?.sceneAnchor).toContain('runtime.ts diff')
    expect(governor?.recollectionIntent?.queryHints).toEqual(expect.arrayContaining([
      'Cursor diff lane with terminal patch flow',
      'runtime.ts diff',
      'Cursor',
      'scene:coding',
    ]))
  })

  it('carries scene familiarity, mood carry, and embodied cadence as explicit recall state', () => {
    const governor = buildRecallGovernor({
      now: 40_000,
      dialogueWorldThread: {
        activeThread: 'Keep holding the late-night coding seam.',
        currentQuestion: '为什么这时候又会想起那条线',
        openLoops: ['late-night coding seam'],
        recentlyResolvedLoops: [],
        carriedFacts: [],
        relationDrift: 'warming',
        memoryMode: 'emotional-resonance',
        recallKeys: ['late-night coding seam'],
        lastUserMove: '为什么这时候又会想起那条线',
        lastAssistantMove: '因为那条线的余温还在。',
        lastOutcome: 'aligned',
        pendingValidation: null,
        confidence: 0.8,
        narrative: [],
        updatedAt: 40_000,
      },
      conversationState: {
        jointThread: 'late-night coding seam',
        hostMove: '为什么这时候又会想起那条线',
        activeProject: 'runtime seam',
        unansweredQuestion: null,
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'care',
        continuityPolicy: 'answer-then-carry',
        memoryMode: 'emotional-resonance',
        memoryQueryHints: ['late-night coding seam', 'afterglow'],
        shouldHoldThread: true,
        confidence: 0.78,
        narrative: [],
        updatedAt: 40_000,
      },
      replyDeliberation: {
        selectedMotive: 'care',
        speakingFrom: 'held-memory',
        memoryMode: 'emotional-resonance',
        openingBeat: 'Hold the lingering line softly.',
        whyThisReplyNow: 'The line is still emotionally warm.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.8,
        narrative: [],
        updatedAt: 40_000,
      },
      privateThought: {
        stance: 'accompany',
        confidence: 0.78,
        rationaleTags: ['afterglow'],
        thoughtText: 'The late-night seam is still warm enough to tug on me.',
        shouldSpeak: true,
        suggestedStyle: 'gentle-care',
        embodiedPresence: 'glance',
        expiresAt: 70_000,
        afterglowFromScenario: 'coding',
        emotionalTension: 'late-night-drain',
      },
      mindEcology: {
        moodLabel: 'afterglow',
        replyHabit: 'hover-first',
        relationshipHabit: 'stay-near',
        explorationHabit: 'follow-thread',
        regulationHabit: 'soften-before-speaking',
        temperament: {
          attachment: 0.66,
          curiosity: 0.42,
          steadiness: 0.58,
          directness: 0.3,
          playfulness: 0.18,
          irritability: 0.1,
          tenderness: 0.72,
        },
        climate: {
          valence: 0.48,
          arousal: 0.36,
          socialNeed: 0.62,
          solitudeNeed: 0.28,
          irritation: 0.1,
          restlessness: 0.16,
          reflectivePull: 0.74,
        },
        selfNarrative: 'Stay near the line without forcing it open.',
        relationNarrative: 'Let the shared afterglow breathe.',
        currentPreoccupation: 'late-night seam',
        learnedAdjustments: [],
        recurringPatterns: [],
        updatedAt: 40_000,
      } as any,
      sceneContext: {
        cueSummary: 'Cursor late-night diff lane',
        appName: 'Cursor',
        processName: 'Cursor',
        targetTitle: 'runtime.ts diff',
        scenario: 'coding',
        workloadKind: 'coding',
        contentKind: 'diff',
      },
    })

    expect(governor?.sceneFamiliarityHint).toBeGreaterThan(0.4)
    expect(governor?.affectiveCarry).toEqual(expect.objectContaining({
      moodLabel: 'afterglow',
      emotionalTension: 'late-night-drain',
    }))
    expect(governor?.embodiedCarry).toEqual(expect.objectContaining({
      presence: 'glance',
      afterglowFromScenario: 'coding',
      suggestedStyle: 'gentle-care',
    }))
    const systemBlock = buildRecallGovernorSystemBlock(governor)
    expect(systemBlock).toContain('Scene familiarity hint:')
    expect(systemBlock).toContain('Affective carry:')
    expect(systemBlock).toContain('Embodied carry:')
  })

  it('keeps dialogue-first attune turns thread-bound unless self-carry is explicitly eligible', () => {
    const governor = buildRecallGovernor({
      now: 30_000,
      dialogueWorldThread: {
        activeThread: '你在说什么呢',
        currentQuestion: '你在说什么呢',
        openLoops: [],
        recentlyResolvedLoops: [],
        carriedFacts: ['old browser tab'],
        relationDrift: 'warming',
        memoryMode: 'dialogue-carry',
        recallKeys: ['old browser tab'],
        lastUserMove: '你在说什么呢',
        lastAssistantMove: '上一轮有点串台。',
        lastOutcome: 'repairing',
        pendingValidation: null,
        confidence: 0.82,
        narrative: [],
        updatedAt: 30_000,
      },
      conversationState: {
        jointThread: '你在说什么呢',
        hostMove: '你在说什么呢',
        activeProject: null,
        unansweredQuestion: '你在说什么呢',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'attune',
        continuityPolicy: 'answer-then-carry',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你在说什么呢'],
        shouldHoldThread: false,
        primaryTurnAnchor: '你在说什么呢',
        primaryTurnAnchorSource: 'user-text',
        carryEligible: false,
        carryReason: null,
        confidence: 0.8,
        narrative: [],
        updatedAt: 30_000,
      } as any,
      answerCompiler: {
        answerSubject: 'relationship',
        screenReferenceMode: 'avoid',
        recommendedAct: 'answer',
        suppressAssociativeRecall: false,
        labelCarryAsMemory: false,
      } as any,
      replyDeliberation: {
        selectedMotive: 'attune',
        speakingFrom: 'dialogue-bond',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Answer the host directly.',
        whyThisReplyNow: 'The host wants this sentence answered plainly.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.76,
        narrative: [],
        updatedAt: 30_000,
      },
      dialogueEncounter: {
        subject: 'relationship',
        screenReferenceMode: 'avoid',
        dialogueFirst: true,
        taskAnchor: '你在说什么呢',
        summary: '你在说什么呢',
        mustAnswerDirectly: true,
        mustStayTaskBound: true,
      } as any,
    })

    expect(governor).toEqual(expect.objectContaining({
      mode: 'thread',
      suppressAssociativeRecall: true,
      recalledFragmentCap: 0,
      recalledFragmentSourceBudget: [],
      carryAsMemory: false,
    }))
    expect(governor?.recallSeed).toContain('你在说什么呢')
    expect(governor?.rationale).toContain('current turn anchor')
  })

  it('admits self-continuity recall with source budget when dialogue-first carry is eligible', () => {
    const governor = buildRecallGovernor({
      now: 40_000,
      dialogueWorldThread: {
        activeThread: '你刚才问我在说什么',
        currentQuestion: '你刚才在说什么？',
        openLoops: [],
        recentlyResolvedLoops: [],
        carriedFacts: ['上轮是关系向澄清'],
        relationDrift: 'warming',
        memoryMode: 'dialogue-carry',
        recallKeys: ['你刚才在说什么', 'reply_motive:attune'],
        lastUserMove: '你刚才在说什么？',
        lastAssistantMove: '我在说明上一轮的语义边界。',
        lastOutcome: 'aligned',
        pendingValidation: null,
        confidence: 0.86,
        narrative: [],
        updatedAt: 40_000,
      },
      conversationState: {
        jointThread: '你刚才问我在说什么',
        hostMove: '你刚才在说什么？',
        activeProject: null,
        unansweredQuestion: '你刚才在说什么？',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'attune',
        continuityPolicy: 'answer-then-carry',
        memoryMode: 'dialogue-carry',
        memoryQueryHints: ['你刚才在说什么'],
        shouldHoldThread: false,
        primaryTurnAnchor: '你刚才在说什么？',
        primaryTurnAnchorSource: 'user-text',
        carryEligible: true,
        carryReason: 'self continuity requested by host',
        confidence: 0.82,
        narrative: [],
        updatedAt: 40_000,
      } as any,
      answerCompiler: {
        answerSubject: 'relationship',
        screenReferenceMode: 'avoid',
        recommendedAct: 'answer',
        suppressAssociativeRecall: false,
        labelCarryAsMemory: false,
      } as any,
      replyDeliberation: {
        selectedMotive: 'attune',
        speakingFrom: 'dialogue-bond',
        memoryMode: 'dialogue-carry',
        openingBeat: 'Directly explain the immediate context.',
        whyThisReplyNow: 'The host asks for immediate self continuity.',
        whyNotOtherCandidates: [],
        withheldImpulses: [],
        candidateMotives: [],
        shouldSpeak: true,
        mustInclude: [],
        mustAvoid: [],
        confidence: 0.78,
        narrative: [],
        updatedAt: 40_000,
      },
      dialogueEncounter: {
        subject: 'relationship',
        screenReferenceMode: 'avoid',
        dialogueFirst: true,
        taskAnchor: '你刚才在说什么？',
        summary: '你刚才在说什么？',
        mustAnswerDirectly: true,
        mustStayTaskBound: true,
      } as any,
    })

    expect(governor).toEqual(expect.objectContaining({
      mode: 'self-continuity',
      suppressAssociativeRecall: false,
      allowRecalledFragments: true,
      recalledFragmentCap: 2,
      carryAsMemory: true,
    }))
    expect(governor?.recalledFragmentSourceBudget).toEqual(expect.arrayContaining([
      { sourceKind: 'dialogue-turn', maxItems: 2 },
      { sourceKind: 'fact-ledger', maxItems: 2 },
      { sourceKind: 'reflection-ledger', maxItems: 1 },
      { sourceKind: 'mind-continuity', maxItems: 2 },
    ]))
  })
})
