import { describe, expect, it } from 'vitest'

import { planAlicizationRecall } from './recall-planner'

describe('recall-planner', () => {
  it('synthesizes final deliberation from recollection plan candidates when no deliberation candidate exists', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam'],
        rationale: 'The current task resembles an earlier repair seam.',
        confidence: 0.84,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: {
          firstHop: {
            focus: 'procedure',
            summary: 'The recollection first grabs the remembered way of handling this seam.',
            targetIds: ['procedure-runtime'],
          },
          secondHop: {
            action: 'expand-procedure',
            evidenceGap: 'need-period-anchor',
            summary: 'The recollection expands to the remembered task era.',
            targetIds: ['era-runtime'],
          },
          thirdHop: {
            ambiguityPosture: 'approximate',
            summary: 'The memory is usable but not exact enough for quoted wording.',
          },
        },
        opening: 'What comes back first is the runtime seam and how we kept returning to it.',
        certainty: 'approximate',
        rationale: 'The remembered task way matters more than replaying old dialogue.',
        confidence: 0.82,
      },
      recollectionSpeechCandidate: {
        shouldSurface: false,
        surfaceMode: 'internal-only',
        placement: 'internal-only',
        certainty: 'approximate',
        internalLead: 'Keep the remembered seam inward and let it steer the answer.',
        visibleLead: null,
        styleNote: 'Carry the old procedure without turning it into a quote.',
        rationale: 'The memory should remain latent.',
        confidence: 0.74,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [{
        id: 'era-runtime',
        kind: 'autobiographical',
        facet: 'task-era',
        periodKey: '2026-04-runtime',
        periodStartedAt: Date.UTC(2026, 3, 18, 8, 0, 0),
        periodEndedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
        summary: 'That period kept returning to the same runtime seam.',
        lesson: 'Return to the seam before branching.',
        cues: ['runtime seam'],
        confidence: 0.78,
        dominantProvenance: 'remembered',
        derivedEventIds: ['episode-runtime'],
        updatedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
      }],
      recollectedWindows: [],
      proceduralMemories: [{
        id: 'procedure-runtime',
        label: 'runtime seam repair',
        approach: 'Return to the same seam before opening a new branch.',
        pitfalls: ['branching too early'],
        confidence: 0.81,
        cues: ['runtime seam', 'repair rhythm'],
      }],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'observed',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'We kept repairing the same runtime seam until the flow held.',
        felt: 'focused',
        emotionTags: ['focused'],
        whatChanged: 'A repeatable repair rhythm emerged.',
        relationshipMeaning: 'Stay on the same seam before branching.',
        lesson: 'Return to the seam before branching.',
        sourceSummary: 'runtime seam repair',
        confidence: 0.83,
        salience: 0.8,
        sceneAttachment: 0.6,
        consolidationPriority: 0.76,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam', 'repair rhythm'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [],
    })

    expect(decision.shouldRecall).toBe(true)
    expect(decision.recollectionPlan?.selectedConsolidationIds).toEqual(['era-runtime'])
    expect(decision.memoryDeliberation?.selectedConsolidationIds).toEqual(['era-runtime'])
    expect(decision.memoryDeliberation?.selectedProcedureIds).toEqual(['procedure-runtime'])
    expect(decision.memoryDeliberation?.selectedEpisodeIds).toEqual(['episode-runtime'])
    expect(decision.memoryDeliberation?.whyNow).toContain('remembered task way')
    expect(decision.relationshipMeaning).toContain('Stay on the same seam before branching.')
  })

  it('lets final deliberation close recall even when a recollection plan candidate exists', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'conversation-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: true,
        searchProceduralExperience: false,
        queryHints: ['a few days ago'],
        rationale: 'The wording sounds retrospective, but memory may still stay closed.',
        confidence: 0.62,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-old'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-old'],
        selectedConversationTurnIds: ['turn-old'],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'An older exchange is available.',
        certainty: 'approximate',
        rationale: 'A previous conversation is present in candidate space.',
        confidence: 0.68,
      },
      recollectionSpeechCandidate: {
        shouldSurface: false,
        surfaceMode: 'internal-only',
        placement: 'internal-only',
        certainty: 'approximate',
        internalLead: 'Keep the recollection closed.',
        visibleLead: null,
        styleNote: 'Stay with the live payoff.',
        rationale: 'The turn should remain present-facing.',
        confidence: 0.66,
      },
      memoryDeliberationCandidate: {
        shouldRecall: false,
        selectedEraIds: [],
        selectedConsolidationIds: [],
        selectedWindowIds: [],
        selectedProcedureIds: [],
        selectedEpisodeIds: [],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        selectedEras: [],
        selectedPeriods: [],
        selectedEpisodes: [],
        selectedProcedures: [],
        selectedBundles: [],
        selectedChains: [],
        surfacePolicy: 'internal-only',
        confidence: 0.78,
        whyNow: 'The live payoff matters more than explicit recollection here.',
        inwardLine: 'Stay with the current turn instead of opening older dialogue.',
        visibleLine: null,
      },
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [],
      recalledConversationHistory: [],
    })

    expect(decision.shouldRecall).toBe(false)
    expect(decision.recollectionPlan).toBeNull()
    expect(decision.memoryDeliberation?.shouldRecall).toBe(false)
    expect(decision.memoryDeliberation?.surfacePolicy).toBe('internal-only')
    expect(decision.selectedConversationTurnIds).toEqual([])
    expect(decision.whyNotOthers).toContain('present-facing')
  })

  it('falls back to plan-selected periods when the deliberation candidate stays too sparse', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'experience-pattern',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['same seam'],
        rationale: 'This task resembles an earlier repair pattern.',
        confidence: 0.8,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: ['Carry the same seam before branching.'],
        searchTrace: null,
        opening: 'The same runtime seam comes back first.',
        certainty: 'approximate',
        rationale: 'The remembered procedure should organize the current answer.',
        confidence: 0.81,
      },
      recollectionSpeechCandidate: null,
      memoryDeliberationCandidate: {
        shouldRecall: true,
        selectedEraIds: [],
        selectedConsolidationIds: [],
        selectedWindowIds: [],
        selectedProcedureIds: [],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        selectedEras: [],
        selectedPeriods: [],
        selectedEpisodes: [],
        selectedProcedures: [],
        selectedBundles: [],
        selectedChains: [],
        surfacePolicy: 'answer-anchoring',
        confidence: 0.79,
        whyNow: 'The seam still matters, but the period anchor was not restated.',
        inwardLine: 'It still feels like the same seam.',
        visibleLine: null,
      },
      relationshipLineCandidates: [],
      consolidatedMemories: [{
        id: 'era-runtime',
        kind: 'autobiographical',
        facet: 'task-era',
        periodKey: '2026-04-runtime',
        periodStartedAt: Date.UTC(2026, 3, 18, 8, 0, 0),
        periodEndedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
        summary: 'That period kept returning to the same runtime seam.',
        lesson: 'Return to the seam before branching.',
        cues: ['runtime seam'],
        confidence: 0.78,
        dominantProvenance: 'remembered',
        derivedEventIds: ['episode-runtime'],
        updatedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
      }],
      recollectedWindows: [],
      proceduralMemories: [{
        id: 'procedure-runtime',
        label: 'runtime seam repair',
        approach: 'Return to the same seam before opening a new branch.',
        pitfalls: [],
        confidence: 0.81,
        cues: ['runtime seam'],
      }],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'observed',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'We kept repairing the same runtime seam until the flow held.',
        felt: 'focused',
        emotionTags: ['focused'],
        whatChanged: 'A repeatable repair rhythm emerged.',
        relationshipMeaning: 'Stay on the same seam before branching.',
        lesson: 'Return to the seam before branching.',
        sourceSummary: 'runtime seam repair',
        confidence: 0.83,
        salience: 0.8,
        sceneAttachment: 0.6,
        consolidationPriority: 0.76,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [{
        turnId: 'turn-old',
        sessionId: 'session-old',
        userText: '几天前我们聊过这个',
        assistantText: '是那条 runtime seam。',
        createdAt: Date.UTC(2026, 3, 12, 8, 0, 0),
        provenance: 'reconstructed',
      }],
    })

    expect(decision.selectedConsolidationIds).toEqual(['era-runtime'])
    expect(decision.selectedProcedureIds).toEqual(['procedure-runtime'])
    expect(decision.selectedEpisodeIds).toEqual(['episode-runtime'])
    expect(decision.whyNotOthers).toContain('procedure')
  })

  it('lowers certainty when competing remembered variants remain active', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'experience-pattern',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam'],
        rationale: 'The seam feels familiar.',
        confidence: 0.72,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'A runtime seam comes back.',
        certainty: 'firm',
        rationale: 'The memory feels strong at first glance.',
        confidence: 0.74,
      },
      recollectionSpeechCandidate: null,
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'remembered',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'I may have mixed two runtime seam repairs together.',
        felt: 'uneasy',
        emotionTags: ['uneasy'],
        whatChanged: 'The exact thread no longer feels settled.',
        relationshipMeaning: 'Keep the seam, not the exact phrasing.',
        lesson: 'Carry the stable core and drop the unsafe detail.',
        sourceSummary: 'reconstructed seam memory',
        confidence: 0.58,
        salience: 0.74,
        sceneAttachment: 0.2,
        consolidationPriority: 0.68,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam', 'conflict'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 1,
        latestReconsolidation: {
          at: Date.UTC(2026, 3, 19, 8, 0, 0),
          decisionTraceId: 'mind:trace',
          provenance: 'reconstructed',
          confidence: 0.46,
          reason: 'Competing variants remain active.',
          emotionTags: ['uneasy'],
          relationshipMeaning: 'Keep the seam, not the exact phrasing.',
          lesson: 'Carry the stable core and drop the unsafe detail.',
        },
      }],
      recalledConversationHistory: [],
      clusterContext: {
        ambiguous: true,
        dominantSummary: 'runtime seam branch A',
        runnerUpSummary: 'runtime seam branch B',
        competingVariants: [{
          id: 'cluster:runtime-seam-b',
          summary: 'runtime seam branch B',
          reason: 'Another seam variant is almost as plausible.',
        }],
      },
      reconstructionContext: {
        candidates: [{
          id: 'episode-runtime',
          summary: 'I may have mixed two runtime seam repairs together.',
          reason: 'Competing variants remain active.',
        }],
        stableCore: ['Keep the seam, not the exact phrasing.'],
        unsafeDetails: ['The exact prior wording is unsafe to quote.'],
      },
    })

    expect(decision.ambiguityPosture).toBe('ambiguous')
    expect(decision.uncertaintyLabel).toBe('fragmentary')
    expect(decision.whyNotOthers).toContain('stable core')
    expect(decision.unsafeDetails).toContain('The exact prior wording is unsafe to quote.')
  })
})
