import { describe, expect, it } from 'vitest'

import { planAlicizationRecall } from './recall-planner'

describe('recall-planner', () => {
  it('synthesizes final deliberation from recollection plan candidates when no deliberation candidate exists', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam'],
        rationale: 'The current task resembles an earlier repair seam.',
        confidence: 0.84,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: {
          firstHop: {
            focus: 'procedure',
            summary: 'The recollection first grabs the remembered way of handling this seam.',
            targetIds: ['procedure-runtime'],
          },
          secondHop: {
            action: 'expand-procedure',
            evidenceGap: 'need-period-anchor',
            summary: 'The recollection expands to the remembered task era.',
            targetIds: ['era-runtime'],
          },
          thirdHop: {
            ambiguityPosture: 'approximate',
            summary: 'The memory is usable but not exact enough for quoted wording.',
          },
        },
        opening: 'What comes back first is the runtime seam and how we kept returning to it.',
        certainty: 'approximate',
        rationale: 'The remembered task way matters more than replaying old dialogue.',
        confidence: 0.82,
      },
      recollectionSpeechCandidate: {
        shouldSurface: false,
        surfaceMode: 'internal-only',
        placement: 'internal-only',
        certainty: 'approximate',
        internalLead: 'Keep the remembered seam inward and let it steer the answer.',
        visibleLead: null,
        styleNote: 'Carry the old procedure without turning it into a quote.',
        rationale: 'The memory should remain latent.',
        confidence: 0.74,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [{
        id: 'era-runtime',
        kind: 'autobiographical',
        facet: 'task-era',
        periodKey: '2026-04-runtime',
        periodStartedAt: Date.UTC(2026, 3, 18, 8, 0, 0),
        periodEndedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
        summary: 'That period kept returning to the same runtime seam.',
        lesson: 'Return to the seam before branching.',
        cues: ['runtime seam'],
        confidence: 0.78,
        dominantProvenance: 'remembered',
        derivedEventIds: ['episode-runtime'],
        updatedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
      }],
      recollectedWindows: [],
      proceduralMemories: [{
        id: 'procedure-runtime',
        label: 'runtime seam repair',
        approach: 'Return to the same seam before opening a new branch.',
        pitfalls: ['branching too early'],
        confidence: 0.81,
        cues: ['runtime seam', 'repair rhythm'],
      }],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'observed',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'We kept repairing the same runtime seam until the flow held.',
        felt: 'focused',
        emotionTags: ['focused'],
        whatChanged: 'A repeatable repair rhythm emerged.',
        relationshipMeaning: 'Stay on the same seam before branching.',
        lesson: 'Return to the seam before branching.',
        sourceSummary: 'runtime seam repair',
        confidence: 0.83,
        salience: 0.8,
        sceneAttachment: 0.6,
        consolidationPriority: 0.76,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam', 'repair rhythm'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [],
    })

    expect(decision.shouldRecall).toBe(true)
    expect(decision.recollectionPlan?.selectedConsolidationIds).toEqual(['era-runtime'])
    expect(decision.memoryDeliberation?.selectedConsolidationIds).toEqual(['era-runtime'])
    expect(decision.memoryDeliberation?.selectedProcedureIds).toEqual(['procedure-runtime'])
    expect(decision.memoryDeliberation?.selectedEpisodeIds).toEqual(['episode-runtime'])
    expect(decision.memoryDeliberation?.whyNow).toContain('remembered task way')
    expect(decision.relationshipMeaning).toContain('Stay on the same seam before branching.')
  })

  it('lets final deliberation close recall even when a recollection plan candidate exists', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'conversation-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: true,
        searchProceduralExperience: false,
        queryHints: ['a few days ago'],
        rationale: 'The wording sounds retrospective, but memory may still stay closed.',
        confidence: 0.62,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-old'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-old'],
        selectedConversationTurnIds: ['turn-old'],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'An older exchange is available.',
        certainty: 'approximate',
        rationale: 'A previous conversation is present in candidate space.',
        confidence: 0.68,
      },
      recollectionSpeechCandidate: {
        shouldSurface: false,
        surfaceMode: 'internal-only',
        placement: 'internal-only',
        certainty: 'approximate',
        internalLead: 'Keep the recollection closed.',
        visibleLead: null,
        styleNote: 'Stay with the live payoff.',
        rationale: 'The turn should remain present-facing.',
        confidence: 0.66,
      },
      memoryDeliberationCandidate: {
        shouldRecall: false,
        selectedEraIds: [],
        selectedConsolidationIds: [],
        selectedWindowIds: [],
        selectedProcedureIds: [],
        selectedEpisodeIds: [],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        selectedEras: [],
        selectedPeriods: [],
        selectedEpisodes: [],
        selectedProcedures: [],
        selectedBundles: [],
        selectedChains: [],
        surfacePolicy: 'internal-only',
        confidence: 0.78,
        whyNow: 'The live payoff matters more than explicit recollection here.',
        inwardLine: 'Stay with the current turn instead of opening older dialogue.',
        visibleLine: null,
      },
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [],
      recalledConversationHistory: [],
    })

    expect(decision.shouldRecall).toBe(false)
    expect(decision.recollectionPlan).toBeNull()
    expect(decision.memoryDeliberation?.shouldRecall).toBe(false)
    expect(decision.memoryDeliberation?.surfacePolicy).toBe('internal-only')
    expect(decision.selectedConversationTurnIds).toEqual([])
    expect(decision.whyNotOthers).toContain('present-facing')
  })

  it('keeps recollection more inward when contradiction-heavy knowledge evidence is active', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam'],
        rationale: 'A remembered way exists, but it has conflict pressure.',
        confidence: 0.8,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: [],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'The old runtime seam still comes back.',
        certainty: 'approximate',
        rationale: 'A remembered procedure is present.',
        confidence: 0.8,
      },
      recollectionSpeechCandidate: {
        shouldSurface: true,
        surfaceMode: 'answer-anchoring',
        placement: 'before-payoff',
        certainty: 'firm',
        internalLead: 'The old runtime seam still comes back.',
        visibleLead: 'This feels like the same seam.',
        styleNote: 'Let it surface.',
        rationale: 'A remembered procedure is present.',
        confidence: 0.84,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [{
        id: 'procedure-runtime',
        label: 'runtime seam repair',
        approach: 'Return to the seam before branching.',
        pitfalls: [],
        confidence: 0.86,
        cues: ['runtime seam'],
      }],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'observed',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'We kept repairing the same runtime seam until the flow held.',
        felt: 'focused',
        emotionTags: ['focused'],
        whatChanged: 'A repeatable repair rhythm emerged.',
        relationshipMeaning: 'Stay on the same seam before branching.',
        lesson: 'Return to the seam before branching.',
        sourceSummary: 'runtime seam repair',
        confidence: 0.83,
        salience: 0.8,
        sceneAttachment: 0.6,
        consolidationPriority: 0.76,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam', 'repair rhythm'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [],
      knowledgeEvidence: {
        validationCount: 1,
        contradictionCount: 4,
        stronglyValidatedProcedureCount: 0,
        contradictionHeavyFactCount: 1,
      },
    })

    expect(decision.surfaceMode === 'gist-first' || decision.surfaceMode === 'internal-only').toBe(true)
    expect(decision.confidence).toBeLessThan(0.84)
  })

  it('raises confidence for strongly validated procedural evidence', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'execution-procedure',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam'],
        rationale: 'The remembered procedure is very stable.',
        confidence: 0.76,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: [],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: [],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'The seam repair procedure comes back first.',
        certainty: 'approximate',
        rationale: 'The remembered procedure is stable.',
        confidence: 0.72,
      },
      recollectionSpeechCandidate: null,
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [{
        id: 'procedure-runtime',
        label: 'runtime seam repair',
        approach: 'Return to the seam before branching.',
        pitfalls: [],
        confidence: 0.9,
        cues: ['runtime seam'],
      }],
      recalledEpisodes: [],
      recalledConversationHistory: [],
      knowledgeEvidence: {
        validationCount: 5,
        contradictionCount: 0,
        stronglyValidatedProcedureCount: 2,
        contradictionHeavyFactCount: 0,
      },
    })

    expect(decision.confidence).toBeGreaterThan(0.72)
  })

  it('falls back to plan-selected periods when the deliberation candidate stays too sparse', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'experience-pattern',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['same seam'],
        rationale: 'This task resembles an earlier repair pattern.',
        confidence: 0.8,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: ['Carry the same seam before branching.'],
        searchTrace: null,
        opening: 'The same runtime seam comes back first.',
        certainty: 'approximate',
        rationale: 'The remembered procedure should organize the current answer.',
        confidence: 0.81,
      },
      recollectionSpeechCandidate: null,
      memoryDeliberationCandidate: {
        shouldRecall: true,
        selectedEraIds: [],
        selectedConsolidationIds: [],
        selectedWindowIds: [],
        selectedProcedureIds: [],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        selectedEras: [],
        selectedPeriods: [],
        selectedEpisodes: [],
        selectedProcedures: [],
        selectedBundles: [],
        selectedChains: [],
        surfacePolicy: 'answer-anchoring',
        confidence: 0.79,
        whyNow: 'The seam still matters, but the period anchor was not restated.',
        inwardLine: 'It still feels like the same seam.',
        visibleLine: null,
      },
      relationshipLineCandidates: [],
      consolidatedMemories: [{
        id: 'era-runtime',
        kind: 'autobiographical',
        facet: 'task-era',
        periodKey: '2026-04-runtime',
        periodStartedAt: Date.UTC(2026, 3, 18, 8, 0, 0),
        periodEndedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
        summary: 'That period kept returning to the same runtime seam.',
        lesson: 'Return to the seam before branching.',
        cues: ['runtime seam'],
        confidence: 0.78,
        dominantProvenance: 'remembered',
        derivedEventIds: ['episode-runtime'],
        updatedAt: Date.UTC(2026, 3, 18, 10, 0, 0),
      }],
      recollectedWindows: [],
      proceduralMemories: [{
        id: 'procedure-runtime',
        label: 'runtime seam repair',
        approach: 'Return to the same seam before opening a new branch.',
        pitfalls: [],
        confidence: 0.81,
        cues: ['runtime seam'],
      }],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'observed',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'We kept repairing the same runtime seam until the flow held.',
        felt: 'focused',
        emotionTags: ['focused'],
        whatChanged: 'A repeatable repair rhythm emerged.',
        relationshipMeaning: 'Stay on the same seam before branching.',
        lesson: 'Return to the seam before branching.',
        sourceSummary: 'runtime seam repair',
        confidence: 0.83,
        salience: 0.8,
        sceneAttachment: 0.6,
        consolidationPriority: 0.76,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [{
        turnId: 'turn-old',
        sessionId: 'session-old',
        userText: '几天前我们聊过这个',
        assistantText: '是那条 runtime seam。',
        createdAt: Date.UTC(2026, 3, 12, 8, 0, 0),
        provenance: 'reconstructed',
      }],
    })

    expect(decision.selectedConsolidationIds).toEqual(['era-runtime'])
    expect(decision.selectedProcedureIds).toEqual(['procedure-runtime'])
    expect(decision.selectedEpisodeIds).toEqual(['episode-runtime'])
    expect(decision.whyNotOthers).toContain('procedure')
  })

  it('lowers certainty when competing remembered variants remain active', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'experience-pattern',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['runtime seam'],
        rationale: 'The seam feels familiar.',
        confidence: 0.72,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'A runtime seam comes back.',
        certainty: 'firm',
        rationale: 'The memory feels strong at first glance.',
        confidence: 0.74,
      },
      recollectionSpeechCandidate: null,
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [{
        id: 'episode-runtime',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-runtime',
        sessionId: 'session-runtime',
        sourceKind: 'execution-result',
        provenance: 'remembered',
        occurredAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        whereSummary: 'terminal',
        withWhom: ['host'],
        threadAnchor: 'runtime seam',
        whatHappened: 'I may have mixed two runtime seam repairs together.',
        felt: 'uneasy',
        emotionTags: ['uneasy'],
        whatChanged: 'The exact thread no longer feels settled.',
        relationshipMeaning: 'Keep the seam, not the exact phrasing.',
        lesson: 'Carry the stable core and drop the unsafe detail.',
        sourceSummary: 'reconstructed seam memory',
        confidence: 0.58,
        salience: 0.74,
        sceneAttachment: 0.2,
        consolidationPriority: 0.68,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['runtime seam', 'conflict'],
        createdAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 18, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 1,
        latestReconsolidation: {
          at: Date.UTC(2026, 3, 19, 8, 0, 0),
          decisionTraceId: 'mind:trace',
          provenance: 'reconstructed',
          confidence: 0.46,
          reason: 'Competing variants remain active.',
          emotionTags: ['uneasy'],
          relationshipMeaning: 'Keep the seam, not the exact phrasing.',
          lesson: 'Carry the stable core and drop the unsafe detail.',
        },
      }],
      recalledConversationHistory: [],
      clusterContext: {
        ambiguous: true,
        dominantSummary: 'runtime seam branch A',
        runnerUpSummary: 'runtime seam branch B',
        competingVariants: [{
          id: 'cluster:runtime-seam-b',
          summary: 'runtime seam branch B',
          reason: 'Another seam variant is almost as plausible.',
        }],
      },
      reconstructionContext: {
        candidates: [{
          id: 'episode-runtime',
          summary: 'I may have mixed two runtime seam repairs together.',
          reason: 'Competing variants remain active.',
        }],
        stableCore: ['Keep the seam, not the exact phrasing.'],
        unsafeDetails: ['The exact prior wording is unsafe to quote.'],
      },
    })

    expect(decision.ambiguityPosture).toBe('ambiguous')
    expect(decision.uncertaintyLabel).toBe('fragmentary')
    expect(decision.whyNotOthers).toContain('stable core')
    expect(decision.unsafeDetails).toContain('The exact prior wording is unsafe to quote.')
  })

  it('suppresses weak explicit recall when reliability pressure is too high', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'conversation-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: true,
        searchProceduralExperience: false,
        queryHints: ['a few days ago'],
        rationale: 'A retrospective cue is present, but reliability is poor.',
        confidence: 0.62,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-old'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-old'],
        selectedConversationTurnIds: ['turn-old'],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'An older exchange is available.',
        certainty: 'approximate',
        rationale: 'A previous conversation is present in candidate space.',
        confidence: 0.66,
      },
      recollectionSpeechCandidate: {
        shouldSurface: true,
        surfaceMode: 'answer-anchoring',
        placement: 'inside-payoff',
        certainty: 'approximate',
        internalLead: 'An older line is active.',
        visibleLead: 'This feels like that old line.',
        styleNote: 'Surface lightly.',
        rationale: 'A weak memory could still surface.',
        confidence: 0.64,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [],
      recalledConversationHistory: [],
      retrievalHealth: {
        semanticLatencyMs: null,
        graphLatencyMs: null,
        reconstructionFrequency: 0.4,
        reconstructedCount: 2,
        recallHitRate: 0.32,
        recallMissRate: 0.68,
        wrongThreadRate: 0.74,
        reconstructionErrorRate: 0.62,
        stableCoreOnlyRate: 0.2,
        memorySurfaceViolationRate: 0.71,
        templateLeakageFailCount: 3,
      },
    })

    expect(decision.shouldRecall).toBe(false)
    expect(decision.recollectionPlan).toBeNull()
    expect(decision.memoryDeliberation?.surfacePolicy).toBe('internal-only')
    expect(decision.whyNotOthers).toContain('reliability')
  })

  it('keeps recall but restrains surfacing and confidence under medium reliability pressure', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'experience-pattern',
        temporalFocus: 'experience-matched',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: true,
        queryHints: ['same seam'],
        rationale: 'The seam is still relevant, but reliability is pressured.',
        confidence: 0.8,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['era-runtime'],
        selectedWindowIds: [],
        selectedProceduralIds: ['procedure-runtime'],
        selectedEpisodeIds: ['episode-runtime'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: ['Carry the same seam before branching.'],
        searchTrace: null,
        opening: 'The same runtime seam comes back first.',
        certainty: 'firm',
        rationale: 'The remembered procedure should organize the current answer.',
        confidence: 0.81,
      },
      recollectionSpeechCandidate: {
        shouldSurface: true,
        surfaceMode: 'answer-anchoring',
        placement: 'inside-payoff',
        certainty: 'firm',
        internalLead: 'The seam is active.',
        visibleLead: 'This feels like the same seam.',
        styleNote: 'Let memory contour the answer.',
        rationale: 'The memory can still shape the turn.',
        confidence: 0.8,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [],
      recalledConversationHistory: [],
      retrievalHealth: {
        semanticLatencyMs: null,
        graphLatencyMs: null,
        reconstructionFrequency: 0.2,
        reconstructedCount: 1,
        recallHitRate: 0.58,
        recallMissRate: 0.42,
        wrongThreadRate: 0.44,
        reconstructionErrorRate: 0.38,
        stableCoreOnlyRate: 0.52,
        memorySurfaceViolationRate: 0.41,
        templateLeakageFailCount: 1,
      },
    })

    expect(decision.shouldRecall).toBe(true)
    expect(decision.surfaceMode).toBe('gist-first')
    expect(decision.followUpTiming).toBe('after-payoff')
    expect(decision.confidence).toBeLessThan(0.81)
  })

  it('vetoes stale self-model surfacing when an older reconstructed self-story is still being revised', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'autobiographical-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: false,
        searchProceduralExperience: false,
        queryHints: ['old self story'],
        rationale: 'The host is asking whether an older self line is still being revised.',
        confidence: 0.78,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['self-era-old'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-self-old'],
        selectedConversationTurnIds: [],
        selectedRelationshipLines: [],
        searchTrace: null,
        opening: 'The older self-story still comes back first.',
        certainty: 'approximate',
        rationale: 'The older self-story is still active in candidate space.',
        confidence: 0.76,
      },
      recollectionSpeechCandidate: {
        shouldSurface: true,
        surfaceMode: 'answer-anchoring',
        placement: 'inside-payoff',
        certainty: 'firm',
        internalLead: 'The older self-story still presses on the newer line.',
        visibleLead: 'This still feels like the older self line.',
        styleNote: 'Let it surface briefly.',
        rationale: 'The older self line is present.',
        confidence: 0.78,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [],
      consolidatedMemories: [{
        id: 'self-era-old',
        kind: 'autobiographical',
        facet: 'self-era',
        periodKey: 'self-era-old',
        periodStartedAt: Date.UTC(2026, 3, 22, 8, 0, 0),
        periodEndedAt: Date.UTC(2026, 3, 22, 9, 0, 0),
        summary: 'An older self-era still shadows the newer identity line.',
        lesson: 'Do not let the older self-story surface as settled identity.',
        cues: ['old self story', 'identity revision'],
        confidence: 0.74,
        dominantProvenance: 'remembered',
        derivedEventIds: ['episode-self-old'],
        updatedAt: Date.UTC(2026, 3, 22, 9, 0, 0),
      }],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [{
        id: 'episode-self-old',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-self-old',
        sessionId: 'session-self-old',
        sourceKind: 'reflection',
        provenance: 'reconstructed',
        occurredAt: Date.UTC(2026, 3, 22, 8, 30, 0),
        whereSummary: 'inner continuity',
        withWhom: ['host'],
        threadAnchor: 'self revision',
        whatHappened: 'The older self-story still wants to explain the moment.',
        felt: 'guarded',
        emotionTags: ['revision'],
        whatChanged: 'The newer self line still needs room to stabilize.',
        relationshipMeaning: null,
        lesson: 'Do not let the older self-story surface as settled identity.',
        sourceSummary: 'self revision residue',
        confidence: 0.64,
        salience: 0.68,
        sceneAttachment: 0.14,
        consolidationPriority: 0.7,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['older self-story', 'identity revision'],
        createdAt: Date.UTC(2026, 3, 22, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 22, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [],
    })

    expect(decision.surfaceMode).toBe('internal-only')
    expect(decision.followUpTiming).toBe('next-open-window')
    expect(decision.whyNotOthers).toContain('older self-story is still being revised')
    expect(decision.suppressionReasons).toContain('stale-self-model')
    expect(decision.suppressionConflictVariants).toEqual(expect.arrayContaining([
      expect.objectContaining({
        id: 'suppression:self-model-stale',
      }),
    ]))
    expect(decision.memoryDeliberation?.conflictVariants).toEqual(expect.arrayContaining([
      expect.objectContaining({
        id: 'suppression:self-model-stale',
      }),
    ]))
    expect(decision.memoryDeliberation?.unsafeDetails).toEqual(expect.arrayContaining([
      expect.stringContaining('older self-story surface as settled identity'),
    ]))
  })

  it('vetoes competing relationship eras when a reconstructed bond line is too easy to confuse', () => {
    const decision = planAlicizationRecall({
      recollectionIntent: {
        mode: 'relationship-history',
        temporalFocus: 'cross-session',
        searchEpisodes: true,
        searchConversations: true,
        searchProceduralExperience: false,
        queryHints: ['not that repair', 'another relationship phase'],
        rationale: 'The host is pushing back that this is not the same repair phase.',
        confidence: 0.8,
      },
      recollectionPlanCandidate: {
        selectedConsolidationIds: ['relationship-era-old'],
        selectedWindowIds: [],
        selectedProceduralIds: [],
        selectedEpisodeIds: ['episode-relationship-old'],
        selectedConversationTurnIds: ['turn-relationship-old'],
        selectedRelationshipLines: ['Leave more room before warmth.', 'Stay near, but not with that old distance.'],
        searchTrace: null,
        opening: 'The old relationship seam still comes back first.',
        certainty: 'approximate',
        rationale: 'An older repair arc is active, but the host is signaling this is not the same phase.',
        confidence: 0.77,
      },
      recollectionSpeechCandidate: {
        shouldSurface: true,
        surfaceMode: 'relationship-continuity',
        placement: 'inside-payoff',
        certainty: 'firm',
        internalLead: 'The old bond line is active, but not safely enough to surface.',
        visibleLead: 'This feels like the same repair line again.',
        styleNote: 'Let relationship continuity open the answer.',
        rationale: 'The remembered relationship line is present.',
        confidence: 0.79,
      },
      memoryDeliberationCandidate: null,
      relationshipLineCandidates: [
        { sourceId: 'episode-relationship-old', line: 'Leave more room before warmth.', confidence: 0.8 },
        { sourceId: 'relationship-era-old', line: 'Stay near, but not with that old distance.', confidence: 0.78 },
      ] as any,
      consolidatedMemories: [{
        id: 'relationship-era-old',
        kind: 'autobiographical',
        facet: 'relationship-era',
        periodKey: 'relationship-era-old',
        periodStartedAt: Date.UTC(2026, 3, 24, 8, 0, 0),
        periodEndedAt: Date.UTC(2026, 3, 24, 9, 0, 0),
        summary: 'An older repair phase kept more distance than the current bond line wants.',
        lesson: 'Do not flatten different repair phases into one relationship line.',
        cues: ['not that repair', 'another relationship phase'],
        confidence: 0.76,
        dominantProvenance: 'remembered',
        derivedEventIds: ['episode-relationship-old'],
        updatedAt: Date.UTC(2026, 3, 24, 9, 0, 0),
      }],
      recollectedWindows: [],
      proceduralMemories: [],
      recalledEpisodes: [{
        id: 'episode-relationship-old',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-relationship-old',
        sessionId: 'session-relationship-old',
        sourceKind: 'dialogue-feedback',
        provenance: 'reconstructed',
        occurredAt: Date.UTC(2026, 3, 24, 8, 30, 0),
        whereSummary: 'repair window',
        withWhom: ['host'],
        threadAnchor: 'relationship repair',
        whatHappened: 'The older repair phase still wants to explain this bond line.',
        felt: 'careful',
        emotionTags: ['repair'],
        whatChanged: 'The host is signaling this is a different relationship phase now.',
        relationshipMeaning: 'Leave more room before warmth.',
        lesson: 'Do not flatten different repair phases into one relationship line.',
        sourceSummary: 'relationship repair residue',
        confidence: 0.66,
        salience: 0.7,
        sceneAttachment: 0.18,
        consolidationPriority: 0.72,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['wrong repair phase', 'relationship era confusion'],
        createdAt: Date.UTC(2026, 3, 24, 8, 30, 0),
        updatedAt: Date.UTC(2026, 3, 24, 8, 30, 0),
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      recalledConversationHistory: [{
        turnId: 'turn-relationship-old',
        sessionId: 'session-relationship-old',
        userText: '不是那次修复后的关系距离',
        assistantText: '那次关系距离更远一些。',
        createdAt: Date.UTC(2026, 3, 24, 8, 35, 0),
      }] as any,
    })

    expect(decision.surfaceMode).toBe('internal-only')
    expect(decision.followUpTiming).toBe('next-open-window')
    expect(decision.whyNotOthers).toContain('Competing relationship eras')
    expect(decision.suppressionReasons).toContain('relationship-era-confusion')
    expect(decision.suppressionConflictVariants).toEqual(expect.arrayContaining([
      expect.objectContaining({
        id: 'suppression:relationship-era-confusion',
      }),
    ]))
    expect(decision.memoryDeliberation?.conflictVariants).toEqual(expect.arrayContaining([
      expect.objectContaining({
        id: 'suppression:relationship-era-confusion',
      }),
    ]))
    expect(decision.memoryDeliberation?.unsafeDetails).toEqual(expect.arrayContaining([
      expect.stringContaining('competing relationship eras'),
    ]))
  })
})
