import { describe, expect, it } from 'vitest'

import { buildReplyDeliberation } from './reply-deliberator'

describe('buildReplyDeliberation typed project state boundary', () => {
  it('does not synthesize project prose from cadence and embodiment fields', () => {
    const state = buildReplyDeliberation({
      now: 60,
      discourseState: {
        currentTurnSubject: 'task-knot',
        screenReferenceMode: 'avoid',
        currentTurnSummary: '',
        currentQuestion: '记忆召回为什么慢？',
        primaryTurnAnchor: '记忆召回延迟',
        primaryTurnAnchorSource: 'question',
        owedAction: 'guide-task',
        relationMove: 'guide',
        continuityMode: 'dialogue-first',
        confidence: 0.8,
        narrative: [],
        updatedAt: 50,
      },
      conversationState: {
        jointThread: '记忆召回延迟',
        hostMove: '记忆召回为什么慢？',
        primaryTurnAnchor: '记忆召回延迟',
        primaryTurnAnchorSource: 'question',
        activeProject: null,
        unansweredQuestion: '记忆召回为什么慢？',
        owedRepair: null,
        activeCommitments: [],
        relationFrame: 'guide',
        continuityPolicy: 'stay-on-thread',
        memoryMode: 'task-thread',
        memoryQueryHints: [],
        shouldHoldThread: true,
        confidence: 0.8,
        narrative: [],
        updatedAt: 50,
      },
      mindSynthesis: {
        answerSubject: 'task-knot',
        relationMove: 'guide',
        speechObligation: 'guide-task',
        beliefs: [],
        uncertainties: [],
        concerns: [],
        commitments: [],
        desires: [],
        openingIntent: '',
        truthBoundary: '',
        interiorSummary: '',
        confidence: 0.8,
        narrative: [],
        updatedAt: 50,
      },
      answerCompiler: {
        answerSubject: 'task-knot',
        screenReferenceMode: 'avoid',
        speechObligation: 'guide-task',
        relationMove: 'guide',
        turnMode: 'guide-current-knot',
        responseMode: 'guide-current-knot',
        recommendedAct: 'guide',
        evidenceMode: 'dialogue-grounded',
        openingStyle: 'direct-answer',
        personaKernelMode: 'full',
        relationshipPosture: 'warm',
        openingDirective: '',
        openingClaim: '',
        supportingReality: [],
        uncertaintyBoundary: null,
        careVector: null,
        nextMove: '核对本轮召回耗时。',
        labelCarryAsMemory: false,
        maxSentences: 4,
        mustDo: [],
        mustNotDo: [],
        confidence: 0.8,
        narrative: [],
        updatedAt: 50,
      },
      currentConsciousFrame: {
        subject: 'task-knot',
        centerOfGravity: 'guide',
        truthDiscipline: 'dialogue-first',
        consciousNeed: '记忆召回为什么慢？',
        consciousTension: '',
        speakingIntention: '核对本轮召回耗时。',
        focusAnchor: '记忆召回延迟',
        withheldImpulse: null,
        shouldWithholdSpecificity: false,
        shouldSelfRevise: false,
        confidence: 0.8,
        reasonTags: [
          'subject:task-knot',
          'center:guide',
          'discipline:dialogue-first',
          'continuity-arc:same-thread-continuation',
        ],
        continuityPreferredTiming: 'next-open-window',
        continuityCadence: 'measured-return',
        projectState: {
          continuityArcStage: 'same-thread-continuation',
          continuityPreferredTiming: 'next-open-window',
          continuityCadence: 'measured-return',
          preferredBlinkCadence: 'quiet',
          preferredGazeMode: 'soften',
          preferredPauseMode: 'longer',
          preferredLipsyncMode: 'restrained',
          preferredVoiceMode: 'lower-pressure',
          preferredPacingMode: 'slower',
        },
        updatedAt: 60,
      },
    })

    const trace = JSON.stringify(state)

    expect(trace).not.toMatch(
      /Phase 1|Memory, dialogue, and embodiment still need|Extend embodiment-scale validation|Proactive continuity is partial|Project-status summary|visible_reply_anchor=project_identity/iu,
    )
  })
})
