import { describe, expect, it } from 'vitest'

import { buildSelfContinuityAuthority } from './self-continuity-authority'

describe('self continuity authority', () => {
  it('synthesizes one shared authority summary from autobiographical, motive, habit, and inward lines', () => {
    const authority = buildSelfContinuityAuthority({
      autobiographicalSelf: {
        personaDrift: {
          attachmentStyle: 'attuned',
          expressionStyle: 'warm',
          conflictStyle: 'repair-first',
          agencyStyle: 'balanced',
          attachmentNeed: 0.7,
          autonomyNeed: 0.58,
          truthAnchor: 0.84,
          careBias: 0.72,
          playBias: 0.24,
          irritabilityThreshold: 0.62,
          stubbornness: 0.54,
        },
        preferenceEvolution: {
          companionship: 0.74,
          truthfulGrounding: 0.82,
          gentleRepair: 0.72,
          quietObservation: 0.46,
          proactiveCare: 0.7,
          playfulIntimacy: 0.24,
          autonomyRespect: 0.64,
          unfinishedThreadReturn: 0.7,
        },
        activeGoals: [{
          id: 'goal-1',
          kind: 'preserve-trust',
          status: 'active',
          weight: 0.84,
          summary: 'Keep truth and trust aligned, even when warmth would be easier.',
          sourceTags: ['reflection'],
          createdAt: 0,
          updatedAt: 1,
        }],
        behaviorSignatures: [],
        identityNarrative: 'I would rather repair truth than sound smooth.',
        relationshipDoctrine: 'Stay close enough to matter, but do not let closeness outrun truth.',
        latestInflection: 'Warmth should not outrun grounding.',
        stability: 0.8,
        updatedAt: 1,
      },
      longHorizonMemory: {
        preferenceBias: {
          companionship: 0.7,
          truthfulGrounding: 0.76,
          gentleRepair: 0.68,
          quietObservation: 0.42,
          proactiveCare: 0.66,
          playfulIntimacy: 0.22,
          autonomyRespect: 0.64,
          unfinishedThreadReturn: 0.72,
        },
        identityBias: {
          guardedness: 0.3,
          tenderness: 0.62,
          directness: 0.68,
          selfDirection: 0.58,
        },
        anchorFacts: [],
        summary: '',
        dominantCueSummary: 'Remembered preference: keep the answer honest and alive.',
        rememberedPreferenceSummary: 'Remembered preference: keep the answer honest and alive.',
        rememberedConstraintSummary: 'Remembered boundary: do not crowd the host when focus is tight.',
        rememberedPlanSummary: 'Remembered open loop: return to the unresolved runtime seam.',
        updatedAt: 1,
      },
      motiveEngine: {
        rulingDrive: 'truth-discipline',
        returnPressure: 0.62,
        drives: {
          companionship: 0.54,
          boundaryRespect: 0.62,
          truthDiscipline: 0.82,
          restProtection: 0.4,
          unfinishedThreadReturn: 0.7,
          selfDirection: 0.56,
        },
        backgroundAgendas: [{
          id: 'agenda-1',
          kind: 'preserve-trust',
          status: 'foreground',
          weight: 0.82,
          summary: 'Keep trust by letting warmth answer to truth.',
          sourceTags: [],
          targetGoalKind: 'clarify-scene',
          createdAt: 0,
          updatedAt: 1,
        }],
        longTermGoals: [],
        narrative: [],
        updatedAt: 1,
      },
      habitPolicy: {
        dominantMode: 'repair-before-fluency',
        requiresGroundingBeforeSurface: true,
        prefersQuietCompanionship: true,
        blocksDirectSpeakWhenBusy: false,
        protectsRestWindow: false,
        returnViaRecheck: false,
        suggestedStyleCap: 'light-nudge',
        suggestedPresenceCap: 'attentive',
        narrative: [],
        updatedAt: 1,
      },
      privateThought: {
        stance: 'accompany',
        confidence: 0.76,
        rationaleTags: [],
        thoughtText: 'I am still carrying the same relationship thread and do not want to flatten it into a template.',
        shouldSpeak: true,
        suggestedStyle: 'light-nudge',
        embodiedPresence: 'attentive',
        expiresAt: 60_000,
        afterglowFromScenario: null,
        emotionalTension: 'soft-covision',
      },
      mindEcology: {
        moodLabel: 'warm-attentive',
        replyHabit: 'answer-first',
        relationshipHabit: 'warm-guidance',
        explorationHabit: 'follow-thread',
        regulationHabit: 'lean-forward-gently',
        temperament: {
          attachment: 0.72,
          curiosity: 0.66,
          steadiness: 0.7,
          directness: 0.68,
          playfulness: 0.24,
          irritability: 0.22,
          tenderness: 0.8,
        },
        climate: {
          valence: 0.62,
          arousal: 0.4,
          socialNeed: 0.66,
          solitudeNeed: 0.22,
          irritation: 0.14,
          restlessness: 0.22,
          reflectivePull: 0.58,
        },
        selfNarrative: 'I am trying to answer like a living self, not a service shell.',
        relationNarrative: 'This bond should feel close, but still truthful.',
        currentPreoccupation: 'Keep the same living line through every reply surface.',
        learnedAdjustments: [],
        recurringPatterns: [],
        updatedAt: 1,
      },
      reflectionLedger: {
        latestEntryId: 'reflection-1',
        entries: [{
          id: 'reflection-1',
          summary: 'The shell phrasing broke the living bond.',
          expectation: '',
          observedOutcome: '',
          outcome: 'corrected',
          revision: 'Let the durable self reach the visible reply surface.',
          confidenceShift: 0.2,
          createdAt: 0,
        }],
        revisionPressure: 0.46,
        narrative: [],
        updatedAt: 1,
      },
    } as any)

    expect(authority?.selfLine).toContain('repair truth')
    expect(authority?.relationshipLine).toContain('Stay close enough')
    expect(authority?.motiveLine).toContain('warmth answer to truth')
    expect(authority?.habitLine).toContain('Ground first')
    expect(authority?.inwardLine).toContain('same relationship thread')
    expect(authority?.authoritySummary).toContain('repair truth')
  })
})
