import { describe, expect, it } from 'vitest'

import {
  formatSpeechAuthorityFilterValue,
  formatSpeechAuthorityValue,
  formatSpeechCueMetadataValue,
  formatSpeechDisplayText,
  formatSpeechDriverExecutionSummary,
  formatSpeechObservabilityLabel,
  formatSpeechObservabilitySectionLabel,
} from './performance-visualizer-speech-display'

describe('performance visualizer speech display', () => {
  it('maps speech embodiment headings and fixed field labels into Chinese-first display text', () => {
    expect(formatSpeechDisplayText('speech-embodiment')).toBe('语音显形')
    expect(formatSpeechDisplayText('phase')).toBe('阶段')
    expect(formatSpeechDisplayText('playback-phase')).toBe('播放阶段')
    expect(formatSpeechDisplayText('speech-energy')).toBe('语音能量')
    expect(formatSpeechDisplayText('prosody-intensity')).toBe('韵律强度')
    expect(formatSpeechDisplayText('emphasis-level')).toBe('强调等级')
    expect(formatSpeechDisplayText('cadence-pulse')).toBe('节拍脉冲')
    expect(formatSpeechDisplayText('viseme-intensity')).toBe('口型强度')
    expect(formatSpeechDisplayText('articulation-voice-language')).toBe('咬字语音语言')
    expect(formatSpeechDisplayText('articulation-consonant-precision')).toBe('咬字辅音精度')
    expect(formatSpeechDisplayText('articulation-closure-bias')).toBe('咬字收口偏置')
    expect(formatSpeechDisplayText('cue-micro-prosody-weight')).toBe('片段微表情韵律权重')
    expect(formatSpeechDisplayText('cue-micro-mouth-weight')).toBe('片段微表情口部权重')
    expect(formatSpeechDisplayText('cue-micro-head-weight')).toBe('片段微表情头部权重')
    expect(formatSpeechDisplayText('cue-micro-facial-hold-ms')).toBe('片段微表情表情保持毫秒')
    expect(formatSpeechDisplayText('cue-micro-action-hold-ms')).toBe('片段微表情动作保持毫秒')
    expect(formatSpeechDisplayText('cue-micro-emotion-hold-ms')).toBe('片段微表情情绪保持毫秒')
    expect(formatSpeechDisplayText('speech-observability-summary')).toBe('语音可观测性摘要')
    expect(formatSpeechDisplayText('articulation-observability')).toBe('咬字可观测性')
    expect(formatSpeechDisplayText('cue-micro-expression')).toBe('片段微表情')
    expect(formatSpeechDisplayText('viseme-hints')).toBe('口型提示')
    expect(formatSpeechDisplayText('speech-authority-segments')).toBe('语音权威片段')
    expect(formatSpeechDisplayText('speech-authority-hotspots')).toBe('语音权威热点')
    expect(formatSpeechDisplayText('top-hotspots')).toBe('热点优先')
    expect(formatSpeechDisplayText('playback-cue-authority')).toBe('播放片段权威')
    expect(formatSpeechDisplayText('recent-driving-trace-record')).toBe('最近驱动轨迹记录')
    expect(formatSpeechDisplayText('recent-driving-trace')).toBe('最近驱动轨迹')
    expect(formatSpeechDisplayText('recent-driving-trace-details')).toBe('最近驱动轨迹细节')
    expect(formatSpeechDisplayText('live2d-authority-comparison')).toBe('Live2D 权威对比')
    expect(formatSpeechDisplayText('vrm-authority-comparison')).toBe('VRM 权威对比')
    expect(formatSpeechDisplayText('authority-summary')).toBe('权威摘要')
    expect(formatSpeechDisplayText('active')).toBe('活跃')
    expect(formatSpeechDisplayText('voice')).toBe('语音')
    expect(formatSpeechDisplayText('lip-closure')).toBe('闭口')
    expect(formatSpeechDisplayText('lip-round')).toBe('圆唇')
    expect(formatSpeechDisplayText('lip-spread')).toBe('展唇')
    expect(formatSpeechDisplayText('jaw-open')).toBe('张口')
    expect(formatSpeechDisplayText('openness')).toBe('开口度')
    expect(formatSpeechDisplayText('top-visemes')).toBe('主要口型')
    expect(formatSpeechDisplayText('cue-id')).toBe('片段 ID')
    expect(formatSpeechDisplayText('cue-text')).toBe('片段文本')
    expect(formatSpeechDisplayText('cue')).toBe('片段')
    expect(formatSpeechDisplayText('drift')).toBe('漂移')
    expect(formatSpeechDisplayText('aligned')).toBe('对齐')
    expect(formatSpeechDisplayText('severity')).toBe('严重度')
    expect(formatSpeechDisplayText('lanes')).toBe('通道')
    expect(formatSpeechDisplayText('surfaces')).toBe('表面')
    expect(formatSpeechDisplayText('all-lanes')).toBe('全通道')
    expect(formatSpeechDisplayText('evidence')).toBe('证据')
    expect(formatSpeechDisplayText('renderer')).toBe('渲染')
    expect(formatSpeechDisplayText('settle')).toBe('稳定段')
    expect(formatSpeechDisplayText('source')).toBe('来源')
    expect(formatSpeechDisplayText('confidence')).toBe('置信度')
    expect(formatSpeechDisplayText('planned')).toBe('规划')
    expect(formatSpeechDisplayText('consumed')).toBe('消费')
    expect(formatSpeechDisplayText('surface')).toBe('表面')
    expect(formatSpeechDisplayText('lane')).toBe('通道')
    expect(formatSpeechDisplayText('live2d-release')).toBe('Live2D 表情回收')
    expect(formatSpeechDisplayText('live2d-follow')).toBe('Live2D 动作跟随')
    expect(formatSpeechDisplayText('vrm-action-fade')).toBe('VRM 动作淡出')
    expect(formatSpeechDisplayText('vrm-expression-blend')).toBe('VRM 表情混合')
    expect(formatSpeechDisplayText('speech')).toBe('语音')
    expect(formatSpeechDisplayText('consumed-expression-name')).toBe('消费表情名')
    expect(formatSpeechDisplayText('expression-aligned')).toBe('表情对齐')
    expect(formatSpeechDisplayText('planned-face-cue')).toBe('规划表情线索')
    expect(formatSpeechDisplayText('consumed-face-cue')).toBe('消费表情线索')
    expect(formatSpeechDisplayText('face-source')).toBe('表情来源')
    expect(formatSpeechDisplayText('face-segment-aligned')).toBe('表情片段对齐')
    expect(formatSpeechDisplayText('planned-motion-aliases')).toBe('规划动作别名')
    expect(formatSpeechDisplayText('consumed-motion-aliases')).toBe('消费动作别名')
    expect(formatSpeechDisplayText('consumed-motion-group')).toBe('消费动作组')
    expect(formatSpeechDisplayText('motion-aligned')).toBe('动作对齐')
    expect(formatSpeechDisplayText('planned-motion-cue')).toBe('规划动作线索')
    expect(formatSpeechDisplayText('consumed-motion-cue')).toBe('消费动作线索')
    expect(formatSpeechDisplayText('motion-source')).toBe('动作来源')
    expect(formatSpeechDisplayText('motion-segment-aligned')).toBe('动作片段对齐')
    expect(formatSpeechDisplayText('consumed-lipsync-cue')).toBe('消费口型线索')
    expect(formatSpeechDisplayText('lipsync-source')).toBe('口型来源')
    expect(formatSpeechDisplayText('lipsync-segment-aligned')).toBe('口型片段对齐')
    expect(formatSpeechDisplayText('consumed-voice-summary')).toBe('消费语音摘要')
    expect(formatSpeechDisplayText('voice-source')).toBe('语音来源')
    expect(formatSpeechDisplayText('voice-segment-aligned')).toBe('语音片段对齐')
    expect(formatSpeechDisplayText('planned-live2d-facial-release-ms')).toBe('规划 Live2D 表情回收毫秒')
    expect(formatSpeechDisplayText('consumed-live2d-facial-release-ms')).toBe('消费 Live2D 表情回收毫秒')
    expect(formatSpeechDisplayText('facial-release-aligned')).toBe('表情回收对齐')
    expect(formatSpeechDisplayText('planned-live2d-motion-follow-through-ms')).toBe('规划 Live2D 动作跟随毫秒')
    expect(formatSpeechDisplayText('consumed-live2d-motion-follow-through-ms')).toBe('消费 Live2D 动作跟随毫秒')
    expect(formatSpeechDisplayText('motion-follow-through-aligned')).toBe('动作跟随对齐')
    expect(formatSpeechDisplayText('consumed-expression-aliases')).toBe('消费表情别名')
    expect(formatSpeechDisplayText('planned-action-cue')).toBe('规划动作线索')
    expect(formatSpeechDisplayText('consumed-action-cue')).toBe('消费动作线索')
    expect(formatSpeechDisplayText('planned-vrm-action-fade-ms')).toBe('规划 VRM 动作淡出毫秒')
    expect(formatSpeechDisplayText('consumed-vrm-action-fade-ms')).toBe('消费 VRM 动作淡出毫秒')
    expect(formatSpeechDisplayText('vrm-action-fade-aligned')).toBe('VRM 动作淡出对齐')
    expect(formatSpeechDisplayText('planned-vrm-expression-blend-ms')).toBe('规划 VRM 表情混合毫秒')
    expect(formatSpeechDisplayText('consumed-vrm-expression-blend-ms')).toBe('消费 VRM 表情混合毫秒')
    expect(formatSpeechDisplayText('vrm-expression-blend-aligned')).toBe('VRM 表情混合对齐')
    expect(formatSpeechDisplayText('persona-style')).toBe('人格风格')
    expect(formatSpeechDisplayText('timing')).toBe('时序')
    expect(formatSpeechDisplayText('summary')).toBe('摘要')
    expect(formatSpeechDisplayText('unknown-speech-key')).toBe('unknown-speech-key')
  })

  it('maps speech observability sections and row labels into Chinese-first display text', () => {
    expect(formatSpeechObservabilitySectionLabel('articulation')).toBe('咬字')
    expect(formatSpeechObservabilitySectionLabel('authority')).toBe('权威')
    expect(formatSpeechObservabilitySectionLabel('cue')).toBe('片段')
    expect(formatSpeechObservabilitySectionLabel('viseme')).toBe('口型')

    expect(formatSpeechObservabilityLabel('voice')).toBe('语音')
    expect(formatSpeechObservabilityLabel('visemes')).toBe('口型')
    expect(formatSpeechObservabilityLabel('authority-match')).toBe('权威命中')
    expect(formatSpeechObservabilityLabel('authority-mismatch')).toBe('权威漂移')
    expect(formatSpeechObservabilityLabel('persona-style')).toBe('人格风格')
    expect(formatSpeechObservabilityLabel('timing')).toBe('时序')
    expect(formatSpeechObservabilityLabel('renderer-live2d')).toBe('显形 Live2D')
    expect(formatSpeechObservabilityLabel('renderer-vrm')).toBe('显形 VRM')
    expect(formatSpeechObservabilityLabel('segment-zh-1')).toBe('segment-zh-1')
  })

  it('maps authority surfaces, lanes, drift statuses, and source-style values into Chinese-first display values', () => {
    expect(formatSpeechAuthorityValue('surface', 'live2d')).toBe('Live2D')
    expect(formatSpeechAuthorityValue('surface', 'vrm')).toBe('VRM')
    expect(formatSpeechAuthorityValue('lane', 'expression')).toBe('表情')
    expect(formatSpeechAuthorityValue('lane', 'motion')).toBe('动作')
    expect(formatSpeechAuthorityValue('lane', 'action')).toBe('动作')
    expect(formatSpeechAuthorityValue('lane', 'lipsync')).toBe('口型')
    expect(formatSpeechAuthorityValue('lane', 'voice')).toBe('语音')
    expect(formatSpeechAuthorityValue('lane', 'settle')).toBe('稳定段')
    expect(formatSpeechAuthorityValue('drift', 'partial-drift')).toBe('部分漂移')
    expect(formatSpeechAuthorityValue('drift', 'hard-drift')).toBe('严重漂移')
    expect(formatSpeechAuthorityValue('drift', 'all-aligned')).toBe('全部对齐')
    expect(formatSpeechAuthorityValue('drift', 'unknown')).toBe('未知')
    expect(formatSpeechAuthorityValue('source', 'prosody-authority')).toBe('韵律权威')
    expect(formatSpeechAuthorityValue('source', 'timeline-projection')).toBe('时间线投影')
    expect(formatSpeechAuthorityValue('source', 'seeded-face')).toBe('播种表情')
    expect(formatSpeechAuthorityValue('source', 'n/a')).toBe('n/a')
    expect(formatSpeechAuthorityValue('renderer-target', 'live2d')).toBe('Live2D')
    expect(formatSpeechAuthorityValue('renderer-target', 'vrm')).toBe('VRM')
    expect(formatSpeechAuthorityValue('unknown-kind', 'prosody-authority')).toBe('prosody-authority')
    expect(formatSpeechAuthorityValue('source', 'unknown-source')).toBe('unknown-source')
  })

  it('maps cue timing and driver metadata values into Chinese-first display values', () => {
    expect(formatSpeechCueMetadataValue('action-window', 'segment-start')).toBe('片段起始')
    expect(formatSpeechCueMetadataValue('action-window', 'cadence-peak')).toBe('节拍峰值')
    expect(formatSpeechCueMetadataValue('interrupt-mode', 'soft-interrupt')).toBe('软打断')
    expect(formatSpeechCueMetadataValue('interrupt-mode', 'hard-interrupt')).toBe('硬打断')
    expect(formatSpeechCueMetadataValue('interrupt-mode', 'continue')).toBe('继续')
    expect(formatSpeechCueMetadataValue('settle-mode', 'hold')).toBe('保持')
    expect(formatSpeechCueMetadataValue('settle-mode', 'release')).toBe('释放')
    expect(formatSpeechCueMetadataValue('settle-mode', 'linger')).toBe('停留')
    expect(formatSpeechCueMetadataValue('attention-mode', 'observe-first')).toBe('先观察')
    expect(formatSpeechCueMetadataValue('playback-phase', 'playing')).toBe('播放中')
    expect(formatSpeechCueMetadataValue('source', 'prosody-authority')).toBe('韵律权威')
    expect(formatSpeechCueMetadataValue('source', 'timeline-projection')).toBe('时间线投影')
    expect(formatSpeechCueMetadataValue('unknown-kind', 'playing')).toBe('playing')
    expect(formatSpeechCueMetadataValue('playback-phase', 'unknown-phase')).toBe('unknown-phase')
  })

  it('formats structured driver execution summaries into Chinese-first human-readable text while preserving unstructured upstream text', () => {
    expect(
      formatSpeechDriverExecutionSummary(
        'face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing',
      ),
    ).toBe(
      '表情 attentive/focused @0.61，保持 320ms，前置 soften，后置 hold-soft，来源 韵律权威，置信 0.83 | 动作 observe_focus，模式 先观察，待机 breathing-idle @0.48，保持 240ms，来源 时间线投影，置信 0.79 | 口型 energy-phoneme-hybrid，阶段 播放中',
    )

    expect(formatSpeechDriverExecutionSummary('face=上游驱动执行')).toBe('face=上游驱动执行')
    expect(formatSpeechDriverExecutionSummary('上游驱动执行')).toBe('上游驱动执行')
    expect(formatSpeechDriverExecutionSummary('lipsync=energy-phoneme-hybrid phase=playing')).toBe('口型 energy-phoneme-hybrid，阶段 播放中')
    expect(
      formatSpeechDriverExecutionSummary(
        'motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79',
      ),
    ).toBe('动作 observe_focus，模式 先观察，待机 breathing-idle @0.48，保持 240ms，来源 时间线投影，置信 0.79')
    expect(
      formatSpeechDriverExecutionSummary(
        'face=focused src=prosody-authority | lipsync=energy-phoneme-hybrid phase=playing',
      ),
    ).toBe('表情 focused，来源 韵律权威 | 口型 energy-phoneme-hybrid，阶段 播放中')
  })

  it('maps authority toolbar labels and filter values into Chinese-first display text', () => {
    expect(formatSpeechDisplayText('tracing-enabled')).toBe('Stage Three Runtime 跟踪已开启')
    expect(formatSpeechDisplayText('tracing-disabled')).toBe('Stage Three Runtime 跟踪已关闭')
    expect(formatSpeechDisplayText('stop-tracing')).toBe('停止跟踪')
    expect(formatSpeechDisplayText('start-tracing')).toBe('开始跟踪')
    expect(formatSpeechDisplayText('refresh-self-evolution-inspector')).toBe('刷新自演化检查器')
    expect(formatSpeechDisplayText('refreshing-self-evolution')).toBe('正在刷新自演化…')
    expect(formatSpeechDisplayText('refresh-self-evolution')).toBe('刷新自演化')
    expect(formatSpeechDisplayText('show-only-drift-rows')).toBe('仅显示漂移行')
    expect(formatSpeechDisplayText('only-drift-rows')).toBe('仅漂移行')
    expect(formatSpeechDisplayText('all-rows')).toBe('全部行')
    expect(formatSpeechDisplayText('cycle-authority-surface-filter')).toBe('切换权威表面筛选')
    expect(formatSpeechDisplayText('cycle-authority-lane-filter')).toBe('切换权威通道筛选')
    expect(formatSpeechDisplayText('cycle-authority-drift-filter')).toBe('切换权威漂移筛选')
    expect(formatSpeechDisplayText('cycle-authority-speech-evidence-filter')).toBe('切换语音证据筛选')
    expect(formatSpeechDisplayText('cycle-settle-authority-filter')).toBe('切换稳定段权威筛选')
    expect(formatSpeechDisplayText('cycle-authority-mismatch-filter')).toBe('切换权威漂移类型筛选')
    expect(formatSpeechDisplayText('cycle-renderer-drift-filter')).toBe('切换显形漂移筛选')
    expect(formatSpeechDisplayText('search-cue-text')).toBe('搜索片段文本')
    expect(formatSpeechDisplayText('window-lifecycle')).toBe('窗口生命周期')
    expect(formatSpeechDisplayText('visible')).toBe('可见')
    expect(formatSpeechDisplayText('minimized')).toBe('最小化')
    expect(formatSpeechDisplayText('focused')).toBe('聚焦')
    expect(formatSpeechDisplayText('reason')).toBe('原因')
    expect(formatSpeechDisplayText('updated-at')).toBe('更新时间')
    expect(formatSpeechDisplayText('stage-paused')).toBe('舞台暂停')
    expect(formatSpeechDisplayText('three-render')).toBe('Three 渲染')
    expect(formatSpeechDisplayText('render-count')).toBe('渲染次数')
    expect(formatSpeechDisplayText('draw-calls')).toBe('绘制调用')
    expect(formatSpeechDisplayText('triangles')).toBe('三角面')
    expect(formatSpeechDisplayText('points')).toBe('点')
    expect(formatSpeechDisplayText('lines')).toBe('线')
    expect(formatSpeechDisplayText('textures')).toBe('纹理')
    expect(formatSpeechDisplayText('geometries')).toBe('几何体')
    expect(formatSpeechDisplayText('last-timestamp-ms')).toBe('最近时间戳毫秒')
    expect(formatSpeechDisplayText('vrm-update-frame')).toBe('VRM 更新帧')
    expect(formatSpeechDisplayText('continuity-frame-summary')).toBe('同一生命线帧摘要')
    expect(formatSpeechDisplayText('continuity-frame-aligned')).toBe('同一生命线帧对齐')
    expect(formatSpeechDisplayText('continuity-frame-mismatch-drivers')).toBe('同一生命线漂移驱动')
    expect(formatSpeechDisplayText('continuity-execution-summary')).toBe('同一生命线执行摘要')
    expect(formatSpeechDisplayText('continuity-execution-aligned')).toBe('同一生命线执行对齐')
    expect(formatSpeechDisplayText('continuity-execution-mismatch-drivers')).toBe('同一生命线执行漂移驱动')
    expect(formatSpeechDisplayText('last-consumed-expression-aliases')).toBe('最近消费表情别名')
    expect(formatSpeechDisplayText('last-consumed-motion-aliases')).toBe('最近消费动作别名')
    expect(formatSpeechDisplayText('last-consumed-vrm-action-fade-ms')).toBe('最近消费 VRM 动作淡出毫秒')
    expect(formatSpeechDisplayText('last-consumed-vrm-expression-blend-ms')).toBe('最近消费 VRM 表情混合毫秒')
    expect(formatSpeechDisplayText('frame-count')).toBe('帧数')
    expect(formatSpeechDisplayText('total-ms')).toBe('总毫秒')
    expect(formatSpeechDisplayText('delta-ms')).toBe('帧间毫秒')
    expect(formatSpeechDisplayText('animation-mixer-ms')).toBe('动画混合器毫秒')
    expect(formatSpeechDisplayText('humanoid-ms')).toBe('Humanoid 毫秒')
    expect(formatSpeechDisplayText('look-at-ms')).toBe('注视毫秒')
    expect(formatSpeechDisplayText('blink-and-saccade-ms')).toBe('眨眼与扫视毫秒')
    expect(formatSpeechDisplayText('emote-ms')).toBe('情绪动作毫秒')
    expect(formatSpeechDisplayText('lip-sync-ms')).toBe('唇形同步毫秒')
    expect(formatSpeechDisplayText('expression-ms')).toBe('表情毫秒')
    expect(formatSpeechDisplayText('spring-bone-ms')).toBe('Spring Bone 毫秒')
    expect(formatSpeechDisplayText('vrm-frame-hook-ms')).toBe('VRM 帧钩子毫秒')
    expect(formatSpeechDisplayText('fade-on-hover-hit-test')).toBe('悬停淡出命中测试')
    expect(formatSpeechDisplayText('read-count')).toBe('读取次数')
    expect(formatSpeechDisplayText('last-duration-ms')).toBe('最近耗时毫秒')
    expect(formatSpeechDisplayText('total-duration-ms')).toBe('累计耗时毫秒')
    expect(formatSpeechDisplayText('last-read-width')).toBe('最近读取宽度')
    expect(formatSpeechDisplayText('last-read-height')).toBe('最近读取高度')
    expect(formatSpeechDisplayText('vrm-lifecycle')).toBe('VRM 生命周期')
    expect(formatSpeechDisplayText('last-model-src')).toBe('最近模型来源')
    expect(formatSpeechDisplayText('last-reason')).toBe('最近原因')
    expect(formatSpeechDisplayText('last-load-start-at')).toBe('最近加载开始时间')
    expect(formatSpeechDisplayText('last-load-end-at')).toBe('最近加载结束时间')
    expect(formatSpeechDisplayText('last-load-duration-ms')).toBe('最近加载耗时毫秒')
    expect(formatSpeechDisplayText('last-dispose-start-at')).toBe('最近释放开始时间')
    expect(formatSpeechDisplayText('last-dispose-end-at')).toBe('最近释放结束时间')
    expect(formatSpeechDisplayText('last-dispose-duration-ms')).toBe('最近释放耗时毫秒')
    expect(formatSpeechDisplayText('last-error-message')).toBe('最近错误信息')
    expect(formatSpeechDisplayText('renderer-resource-snapshots')).toBe('渲染器 / 资源快照')
    expect(formatSpeechDisplayText('after-load')).toBe('加载后')
    expect(formatSpeechDisplayText('before-dispose')).toBe('释放前')
    expect(formatSpeechDisplayText('after-dispose')).toBe('释放后')
    expect(formatSpeechDisplayText('ts')).toBe('时间戳')
    expect(formatSpeechDisplayText('calls')).toBe('调用')
    expect(formatSpeechDisplayText('mesh-count')).toBe('网格数量')
    expect(formatSpeechDisplayText('material-count')).toBe('材质数量')
    expect(formatSpeechDisplayText('history-entries')).toBe('历史条目')

    expect(formatSpeechAuthorityFilterValue('surface', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('surface', 'live2d')).toBe('Live2D')
    expect(formatSpeechAuthorityFilterValue('surface', 'vrm')).toBe('VRM')
    expect(formatSpeechAuthorityFilterValue('lane', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('lane', 'expression')).toBe('表情')
    expect(formatSpeechAuthorityFilterValue('lane', 'motion')).toBe('动作')
    expect(formatSpeechAuthorityFilterValue('lane', 'face')).toBe('表情')
    expect(formatSpeechAuthorityFilterValue('lane', 'action')).toBe('动作')
    expect(formatSpeechAuthorityFilterValue('lane', 'lipsync')).toBe('口型')
    expect(formatSpeechAuthorityFilterValue('lane', 'settle')).toBe('稳定段')
    expect(formatSpeechAuthorityFilterValue('drift', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('drift', 'hard-drift')).toBe('严重漂移')
    expect(formatSpeechAuthorityFilterValue('drift', 'partial-drift')).toBe('部分漂移')
    expect(formatSpeechAuthorityFilterValue('drift', 'unknown')).toBe('未知')
    expect(formatSpeechAuthorityFilterValue('drift', 'all-aligned')).toBe('全部对齐')
    expect(formatSpeechAuthorityFilterValue('speech-evidence', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('speech-evidence', 'speech')).toBe('语音')
    expect(formatSpeechAuthorityFilterValue('speech-evidence', 'prosody')).toBe('韵律')
    expect(formatSpeechAuthorityFilterValue('speech-evidence', 'viseme')).toBe('口型')
    expect(formatSpeechAuthorityFilterValue('speech-evidence', 'micro-expression')).toBe('微表情')
    expect(formatSpeechAuthorityFilterValue('speech-evidence', 'authority-match')).toBe('权威命中')
    expect(formatSpeechAuthorityFilterValue('settle-authority', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('settle-authority', 'authority-bound')).toBe('权威绑定')
    expect(formatSpeechAuthorityFilterValue('settle-authority', 'fallback-derived')).toBe('回退派生')
    expect(formatSpeechAuthorityFilterValue('authority-mismatch', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('authority-mismatch', 'face-mismatch')).toBe('表情漂移')
    expect(formatSpeechAuthorityFilterValue('authority-mismatch', 'motion-mismatch')).toBe('动作漂移')
    expect(formatSpeechAuthorityFilterValue('authority-mismatch', 'lipsync-mismatch')).toBe('口型漂移')
    expect(formatSpeechAuthorityFilterValue('authority-mismatch', 'voice-mismatch')).toBe('语音漂移')
    expect(formatSpeechAuthorityFilterValue('renderer-drift', 'all')).toBe('全部')
    expect(formatSpeechAuthorityFilterValue('renderer-drift', 'present')).toBe('存在漂移')
    expect(formatSpeechAuthorityFilterValue('renderer-drift', 'pending-or-runtime-only')).toBe('待执行或仅运行时')
    expect(formatSpeechAuthorityFilterValue('renderer-drift', 'none')).toBe('无')
    expect(formatSpeechAuthorityFilterValue('unknown-filter', 'authority-bound')).toBe('authority-bound')
  })
})
