import { describe, expect, it } from 'vitest'

import { filterAuthorityTableRows } from './performance-visualizer-authority-table'

describe('performance visualizer authority table filter', () => {
  it('filters compact authority table rows by surface, lane, and drift status', () => {
    const rows = [
      {
        cueId: 'segment-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'expression',
        planned: 'CalmInspect',
        consumed: 'RecoverSoft',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'target=live2d | drivers=face | sources=prosody-authority | matches=face:yes motion:no lipsync:no',
        authorityMatchSummary: 'face:yes motion:no lipsync:no',
        authorityTrustSummary: '韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-1',
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / n/a | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: 'n/a',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'authority-bound | segment=segment-1 | target=live2d | drivers=face | sources=prosody-authority',
      },
      {
        cueId: 'segment-2',
        cueText: '请继续说。',
        driftStatus: 'all-aligned',
        aligned: true,
        surface: 'vrm',
        lane: 'action',
        planned: 'observe_focus',
        consumed: 'observe_focus',
        source: 'timeline-projection',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        authorityTrustSummary: null,
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.24 | mouth=0.16 | head=0.19 | visemePeak=0.31 | provenance=fallback-derived | source=timeline-projection | segment=segment-2',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'soft-gaze / observe_focus',
        cueIdentityPresent: true,
        cueProsodyPresent: false,
        faceCue: 'soft-gaze',
        actionCue: 'observe_focus',
        weightSummary: 'n/a',
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=240 action=220 emotion=300 | cadence-peak | soft-interrupt | hold',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
      },
      {
        cueId: 'segment-3',
        cueText: '这里有口型漂移。',
        driftStatus: 'hard-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.91',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        authorityTrustSummary: null,
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.48 | mouth=0.42 | head=0.18 | visemePeak=0.66 | provenance=fallback-derived | source=prosody-authority | segment=segment-legacy',
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'n/a / n/a | prosody=0.48 mouth=0.42 head=0.18',
        cueIdentityPresent: false,
        cueProsodyPresent: true,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.48 mouth=0.42 head=0.18',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
        settleAuthoritySummary: 'fallback-derived | segment=segment-3',
      },
      {
        cueId: 'segment-4',
        cueText: '无语音元数据。',
        driftStatus: 'unknown',
        aligned: null,
        surface: 'vrm',
        lane: 'expression',
        planned: 'CalmInspect',
        consumed: 'CalmInspect',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        authorityTrustSummary: null,
        prosodyAuthoritySummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
      },
      {
        cueId: 'segment-5',
        cueText: '只有结构化闭环阶段还保留着。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'I',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        authorityTrustSummary: null,
        prosodyAuthoritySummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        embodimentClosureStage: 'audible-body-carry',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      surface: 'live2d',
    }).map(row => row.cueId)).toEqual(['segment-1', 'segment-3', 'segment-5'])

    expect(filterAuthorityTableRows(rows, {
      lane: 'lipsync',
    }).map(row => row.cueId)).toEqual(['segment-3', 'segment-5'])

    expect(filterAuthorityTableRows(rows, {
      driftStatus: 'hard-drift',
    }).map(row => row.cueId)).toEqual(['segment-3'])

    expect(filterAuthorityTableRows(rows, {
      cueTextQuery: '口型',
    }).map(row => row.cueId)).toEqual(['segment-3'])

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'speech',
    }).map(row => row.cueId)).toEqual(['segment-1', 'segment-2', 'segment-3', 'segment-5'])

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'prosody',
    }).map(row => row.cueId)).toEqual(['segment-1', 'segment-2', 'segment-3', 'segment-5'])

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'viseme',
    }).map(row => row.cueId)).toEqual(['segment-1', 'segment-3'])

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'micro-expression',
    }).map(row => row.cueId)).toEqual(['segment-1', 'segment-2'])

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'authority-match',
    }).map(row => row.cueId)).toEqual(['segment-1'])

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'authority-trust',
    }).map(row => row.cueId)).toEqual(['segment-1'])

    expect(filterAuthorityTableRows(rows, {
      settleAuthority: 'authority-bound',
    }).map(row => row.cueId)).toEqual(['segment-1'])

    expect(filterAuthorityTableRows(rows, {
      settleAuthority: 'fallback-derived',
    }).map(row => row.cueId)).toEqual(['segment-3'])
  })

  it('filters authority table rows by renderer drift presence', () => {
    const rows = [
      {
        cueId: 'segment-pending',
        cueText: 'resident prediction still pending.',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'expression',
        planned: 'Soft Gaze',
        consumed: 'n/a',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
        rendererDriftSummary: 'resident Soft Gaze is waiting for renderer application',
        speechSummaryLines: ['renderer-drift: resident Soft Gaze is waiting for renderer application'],
      },
      {
        cueId: 'segment-runtime-only',
        cueText: 'runtime surfaced before resident prediction.',
        driftStatus: 'hard-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'expression',
        planned: 'n/a',
        consumed: 'Focus Inspect',
        source: 'prosody-authority',
        confidence: '0.94',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
        rendererDriftSummary: 'runtime expression surfaced Focus Inspect before resident prediction | face focused@prosody-authority',
        speechSummaryLines: ['renderer-drift: runtime expression surfaced Focus Inspect before resident prediction | face focused@prosody-authority'],
      },
      {
        cueId: 'segment-none',
        cueText: 'no renderer drift here.',
        driftStatus: 'all-aligned',
        aligned: true,
        surface: 'vrm',
        lane: 'action',
        planned: 'observe_focus',
        consumed: 'observe_focus',
        source: 'timeline-projection',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
        rendererDriftSummary: null,
        speechSummaryLines: [],
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      rendererDrift: 'present',
    }).map(row => row.cueId)).toEqual(['segment-pending', 'segment-runtime-only'])

    expect(filterAuthorityTableRows(rows, {
      rendererDrift: 'pending-or-runtime-only',
    }).map(row => row.cueId)).toEqual(['segment-pending', 'segment-runtime-only'])

    expect(filterAuthorityTableRows(rows, {
      rendererDrift: 'none',
    }).map(row => row.cueId)).toEqual(['segment-none'])
  })

  it('filters authority-bound driver mismatch rows without treating fallback-derived rows as authority mismatch', () => {
    const rows = [
      {
        cueId: 'segment-face-mismatch',
        cueText: '表情 authority 漂移。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'face',
        planned: 'focused',
        consumed: 'soft',
        source: 'prosody-authority',
        confidence: '0.88',
        settle: 'n/a',
        authorityBindingSummary: 'target=live2d | drivers=motion, lipsync | sources=prosody-authority | matches=face:no motion:yes lipsync:yes',
        authorityMatchSummary: 'face:no motion:yes lipsync:yes',
        voiceSummary: 'zh-CN | closure=0.71 | precision=0.82',
        topVisemeSummary: 'n/a',
        cueSummary: 'focused / n/a | prosody=0.31 mouth=0.18 head=0.27',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.31 mouth=0.18 head=0.27',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'authority-bound | segment=segment-face-mismatch | target=live2d | drivers=motion, lipsync | sources=prosody-authority',
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['motion', 'lipsync'],
      },
      {
        cueId: 'segment-motion-mismatch',
        cueText: '动作 authority 漂移。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'action',
        planned: 'observe_focus',
        consumed: 'idle_breathing',
        source: 'timeline-projection',
        confidence: '0.79',
        settle: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=face, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:no lipsync:yes',
        authorityMatchSummary: 'face:yes motion:no lipsync:yes',
        voiceSummary: 'zh-CN | closure=0.74 | precision=0.81',
        topVisemeSummary: 'n/a',
        cueSummary: 'soft-gaze / observe_focus | prosody=0.28 mouth=0.17 head=0.33',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'soft-gaze',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.28 mouth=0.17 head=0.33',
        personaStyleSummary: 'observe-first',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'authority-bound | segment=segment-motion-mismatch | target=vrm | drivers=face, lipsync | sources=prosody-authority, timeline-projection',
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'lipsync'],
      },
      {
        cueId: 'segment-lipsync-mismatch',
        cueText: '口型 authority 漂移。',
        driftStatus: 'hard-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.91',
        settle: 'n/a',
        authorityBindingSummary: 'target=live2d | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        voiceSummary: 'zh-CN | closure=0.83 | precision=0.89',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'n/a / n/a | prosody=0.48 mouth=0.42 head=0.18',
        cueIdentityPresent: false,
        cueProsodyPresent: true,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.48 mouth=0.42 head=0.18',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
        settleAuthoritySummary: 'authority-bound | segment=segment-lipsync-mismatch | target=live2d | drivers=face, motion | sources=prosody-authority, timeline-projection',
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion'],
      },
      {
        cueId: 'segment-voice-mismatch',
        cueText: '语音 authority 漂移。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'voice',
        planned: 'steady-line',
        consumed: 'steady-line',
        source: 'voice-segment',
        confidence: '0.86',
        settle: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, voice-segment | matches=face:yes motion:yes lipsync:yes voice:no',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes voice:no',
        voiceSummary: 'segment=segment-stale-voice-line | zh-CN | closure=0.77 | precision=0.84',
        topVisemeSummary: 'n/a',
        cueSummary: 'soft-gaze / observe_focus | prosody=0.26 mouth=0.19 head=0.22',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'soft-gaze',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.26 mouth=0.19 head=0.22',
        personaStyleSummary: 'observe-first',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'authority-bound | segment=segment-voice-mismatch | target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, voice-segment | lane=face+motion+lipsync-only',
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion', 'lipsync'],
      },
      {
        cueId: 'segment-fallback',
        cueText: 'fallback 不能算 authority mismatch。',
        driftStatus: 'hard-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.67',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        voiceSummary: 'zh-CN | closure=0.63 | precision=0.72',
        topVisemeSummary: 'A:0.52',
        cueSummary: 'n/a / n/a | prosody=0.41 mouth=0.36 head=0.12',
        cueIdentityPresent: false,
        cueProsodyPresent: true,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.41 mouth=0.36 head=0.12',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.21@0.73',
        settleAuthoritySummary: 'fallback-derived | segment=segment-fallback',
        authoritySegmentMatched: false,
        authorityMatchedDrivers: [],
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      authorityMatch: 'face-mismatch',
    } as any).map(row => row.cueId)).toEqual(['segment-face-mismatch'])

    expect(filterAuthorityTableRows(rows, {
      authorityMatch: 'motion-mismatch',
    } as any).map(row => row.cueId)).toEqual(['segment-motion-mismatch'])

    expect(filterAuthorityTableRows(rows, {
      authorityMatch: 'lipsync-mismatch',
    } as any).map(row => row.cueId)).toEqual(['segment-lipsync-mismatch'])

    expect(filterAuthorityTableRows(rows, {
      authorityMatch: 'voice-mismatch',
    } as any).map(row => row.cueId)).toEqual(['segment-voice-mismatch'])
  })

  it('keeps micro-expression filtering backward compatible when only legacy cue fields are present', () => {
    const rows = [
      {
        cueId: 'segment-legacy-cue',
        cueText: '这里只有旧字段。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'action',
        planned: 'observe_focus',
        consumed: 'observe_focus',
        source: 'timeline-projection',
        confidence: '0.79',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        faceCue: 'soft-gaze',
        actionCue: 'observe_focus',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
      },
      {
        cueId: 'segment-legacy-prosody-only',
        cueText: '这里只有旧的权重字段。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.88',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        voiceSummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.44 mouth=0.31 head=0.12',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'micro-expression',
    }).map(row => row.cueId)).toEqual(['segment-legacy-cue'])
  })

  it('filters authority table rows by explicit authority trust presence', () => {
    const rows = [
      {
        cueId: 'segment-trusted',
        cueText: '已经重新绑定到当前片段。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'I',
        source: 'prosody-authority',
        confidence: '0.93',
        settle: 'n/a',
        authorityBindingSummary: 'target=live2d | drivers=face, lipsync | sources=prosody-authority | matches=face:yes motion:no lipsync:yes',
        authorityMatchSummary: 'face:yes motion:no lipsync:yes',
        authorityTrustSummary: '韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemeSummary: 'I:0.71, closed:0.38',
        cueSummary: 'focused / n/a | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.35@0.94',
        settleAuthoritySummary: 'authority-bound | segment=segment-trusted | target=live2d | drivers=face, lipsync | sources=prosody-authority',
        speechSummaryLines: ['authority-trust: 韵律权威链已重新绑定到当前片段，可直接进入长期基线。'],
      },
      {
        cueId: 'segment-untrusted',
        cueText: '还没有绑定回来。',
        driftStatus: 'hard-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.78',
        settle: 'n/a',
        authorityBindingSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        authorityTrustSummary: null,
        voiceSummary: 'zh-CN | closure=0.61 | precision=0.72',
        topVisemeSummary: 'A:0.52',
        cueSummary: 'n/a / n/a | prosody=0.41 mouth=0.36 head=0.12',
        cueIdentityPresent: false,
        cueProsodyPresent: true,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.41 mouth=0.36 head=0.12',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'A:0.21@0.73',
        settleAuthoritySummary: 'fallback-derived | segment=segment-untrusted',
        speechSummaryLines: [],
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      authorityTrust: 'present',
    }).map(row => row.cueId)).toEqual(['segment-trusted'])

    expect(filterAuthorityTableRows(rows, {
      authorityTrust: 'none',
    }).map(row => row.cueId)).toEqual(['segment-untrusted'])
  })
  it('treats same-body-line trust as present authority trust in table filters', () => {
    const rows = [
      {
        cueId: 'segment-same-body-filter-1',
        cueText: '三驱动已经一起回体。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'action',
        planned: 'observe_focus',
        consumed: 'observe_focus',
        source: 'timeline-projection',
        confidence: '0.88',
        settle: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:yes',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        authorityTrustSummary: 'VRM 表情、动作、口型已经一起回到当前片段主链，可按同一身体线继续观察。',
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-same-body-filter-1',
        topVisemeSummary: 'I:0.71, closed:0.38',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.35@0.94',
        settleAuthoritySummary: 'authority-bound | segment=segment-same-body-filter-1 | target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection',
        speechSummaryLines: ['authority-trust: VRM 表情、动作、口型已经一起回到当前片段主链，可按同一身体线继续观察。'],
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'authority-trust',
    }).map(row => row.cueId)).toEqual(['segment-same-body-filter-1'])

    expect(filterAuthorityTableRows(rows, {
      authorityTrust: 'present',
    }).map(row => row.cueId)).toEqual(['segment-same-body-filter-1'])
  })

  it('treats thin affective settle-reason trust as present authority trust in table filters even before a row explicitly stores authorityTrustSummary', () => {
    const rows = [
      {
        cueId: 'segment-thin-affective-filter-1',
        cueText: '先把余温留在外面。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'settle',
        planned: 'settle',
        consumed: 'settle',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:yes',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        authorityTrustSummary: null,
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-thin-affective-filter-1',
        topVisemeSummary: 'I:0.71, closed:0.38',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.35@0.94',
        settleAuthoritySummary: 'authority-bound | segment=segment-thin-affective-filter-1 | target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | reason=余韵还在，先留白，别立刻把温度放大',
        speechSummaryLines: [],
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'authority-trust',
    }).map(row => row.cueId)).toEqual(['segment-thin-affective-filter-1'])

    expect(filterAuthorityTableRows(rows, {
      authorityTrust: 'present',
    }).map(row => row.cueId)).toEqual(['segment-thin-affective-filter-1'])
  })

  it('treats audible body-carried same-her continuity as present authority trust in table filters even when only settle authority still exposes it', () => {
    const rows = [
      {
        cueId: 'segment-audible-body-filter-1',
        cueText: '先别把这条身体和声音还在的线拆掉。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.91',
        settle: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=body, lipsync | sources=prosody-authority, voice-segment | matches=body:yes face:no motion:no lipsync:yes | lane=body+lipsync+voice-only | pending-rejoin=face+motion',
        authorityMatchSummary: 'body:yes face:no motion:no lipsync:yes',
        authorityTrustSummary: null,
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-audible-body-filter-1 | source=prosody-authority',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-audible-body-filter-1',
        topVisemeSummary: 'I:0.71, closed:0.38',
        cueSummary: 'n/a / n/a | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: false,
        cueProsodyPresent: true,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'body=measured-return seg=segment-audible-body-filter-1 | lipsync=energy-phoneme-hybrid phase=playing seg=segment-audible-body-filter-1 | closure=audible-body-carry',
        embodimentClosureStage: 'audible-body-carry',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'I:0.35@0.94',
        settleAuthoritySummary: 'authority-bound | segment=segment-audible-body-filter-1 | target=vrm | drivers=body, lipsync | sources=prosody-authority, voice-segment | lane=body+lipsync+voice-only | pending-rejoin=face+motion',
        speechSummaryLines: [],
      },
    ] as any

    expect(filterAuthorityTableRows(rows, {
      speechEvidence: 'authority-trust',
    }).map(row => row.cueId)).toEqual(['segment-audible-body-filter-1'])

    expect(filterAuthorityTableRows(rows, {
      authorityTrust: 'present',
    }).map(row => row.cueId)).toEqual(['segment-audible-body-filter-1'])

    expect(filterAuthorityTableRows(rows, {
      authorityTrust: 'none',
    }).map(row => row.cueId)).toEqual([])
  })
})
