import { describe, expect, it } from 'vitest'

import { buildSelfEvolutionRendererAuthorityProjection } from './performance-visualizer-self-evolution-renderer-authority'

describe('performance visualizer self evolution renderer authority projection', () => {
  it('connects embodiment output projection to concrete renderer authority evidence', () => {
    const projection = buildSelfEvolutionRendererAuthorityProjection({
      embodimentOutputProjection: {
        status: 'grounded',
        projectedBodyState: 'settled',
        projectedContinuityMode: 'ambient-covision',
        projectedFacialCue: 'focused',
        projectedActionCue: 'observe_focus',
        projectedBaseEmotion: 'tired',
        projectedDelivery: 'gentle',
        residentSignature: 'resident|protective-watch|focused|observe_focus',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        driverSummary: {
          rendererTarget: 'vrm',
          face: {
            cue: 'focused',
            source: 'prosody-authority',
            confidence: 0.94,
            segmentId: 'segment-vrm-1',
          },
          motion: {
            cue: 'observe_focus',
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-vrm-1',
          },
          lipsync: {
            cue: 'I',
            source: 'prosody-authority',
            confidence: 0.91,
            segmentId: 'segment-vrm-1',
            mode: 'energy-phoneme-hybrid',
          },
        },
        playbackTelemetry: {
          rendererTarget: 'vrm',
          prosodyAuthority: {
            segmentId: 'segment-vrm-1',
            provenance: 'authority-bound',
            source: 'prosody-authority',
            mode: 'energy-phoneme-hybrid',
            cueProsodyWeight: 0.35,
            cueMouthWeight: 0.35,
            cueHeadWeight: 0.32,
            visemePeakWeight: 0.75,
            summary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-vrm-1',
          },
          driverAuthority: {
            segmentId: 'segment-vrm-1',
            rendererTarget: 'vrm',
            matchedDrivers: ['face', 'motion', 'lipsync'],
            sources: ['prosody-authority', 'timeline-projection'],
            faceSegmentMatched: true,
            motionSegmentMatched: true,
            lipsyncSegmentMatched: true,
          },
          cue: {
            id: 'segment-vrm-1',
            facialCue: 'focused',
            actionCue: 'observe_focus',
            rendererHints: {
              preferredExpressionAliases: ['CalmInspect'],
              preferredMotionAliases: ['ObserveSoft'],
            },
            rendererSettle: {
              vrmActionFadeMs: 280,
              vrmExpressionBlendMs: 360,
              live2dFacialReleaseMs: null,
              live2dMotionFollowThroughMs: null,
            },
          },
          actualDurationMs: 220,
          plannedDurationMs: 220,
          driftMs: 0,
          settleMs: 220,
          stopReason: null,
          drivers: {
            face: {
              emotion: 'thinking',
              facialCue: 'focused',
              intensity: 0.52,
              holdMs: 320,
              source: 'prosody-authority',
              confidence: 0.94,
              preUtteranceCue: 'steady-inhale',
              postUtteranceCue: 'soft-release',
              segmentId: 'segment-vrm-1',
            },
            lipsync: {
              mode: 'energy-phoneme-hybrid',
              playbackPhase: 'playing',
              segmentId: 'segment-vrm-1',
              visemeHints: [],
            },
            motion: {
              idleBase: 'idle_settle',
              attentionMode: 'attentive',
              actionCue: 'observe_focus',
              intensity: 0.34,
              holdMs: 240,
              source: 'timeline-projection',
              confidence: 0.88,
              segmentId: 'segment-vrm-1',
            },
          },
        },
      } as any,
      vrmAuthorityView: {
        cueId: 'segment-vrm-1',
        plannedExpressionAliases: ['CalmInspect'],
        consumedExpressionAliases: ['CalmInspect'],
        expressionAligned: true,
        plannedMotionAliases: ['ObserveSoft'],
        consumedMotionAliases: ['ObserveSoft'],
        motionAligned: true,
        plannedFaceCue: 'focused',
        consumedFaceCue: 'focused',
        faceSource: 'prosody-authority',
        faceSegmentAligned: true,
        plannedActionCue: 'observe_focus',
        consumedActionCue: 'observe_focus',
        motionSource: 'timeline-projection',
        motionSegmentAligned: true,
        consumedLipsyncCue: 'I',
        lipsyncSource: 'prosody-authority',
        lipsyncConfidence: 0.91,
        lipsyncSegmentAligned: true,
        plannedVrmActionFadeMs: 280,
        consumedVrmActionFadeMs: 280,
        vrmActionFadeAligned: true,
        plannedVrmExpressionBlendMs: 360,
        consumedVrmExpressionBlendMs: 360,
        vrmExpressionBlendAligned: true,
      },
      live2dAuthorityView: null,
      playbackCueAuthorityView: {
        cueId: 'segment-vrm-1',
        authoritySegmentId: 'segment-vrm-1',
        authorityRendererTarget: 'vrm',
        authorityMatchedDrivers: ['face', 'motion', 'lipsync'],
        authoritySources: ['prosody-authority', 'timeline-projection'],
        faceSegmentMatched: true,
        motionSegmentMatched: true,
        lipsyncSegmentMatched: true,
        authorityBindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:yes',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        settleAuthoritySummary: 'segment=segment-vrm-1 | target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection',
        preferredExpressionAliases: ['CalmInspect'],
        preferredMotionAliases: ['ObserveSoft'],
        live2dFacialReleaseMs: null,
        live2dMotionFollowThroughMs: null,
        vrmActionFadeMs: 280,
        vrmExpressionBlendMs: 360,
      },
    })

    expect(projection).toEqual({
      status: 'grounded',
      rendererTarget: 'vrm',
      runtimeProfile: 'protective-watch',
      runtimeBodyState: 'settled',
      runtimeContinuityMode: 'ambient-covision',
      runtimeResidentEmotion: 'tired',
      runtimeResidentDelivery: 'gentle',
      runtimeResidentFacialCue: 'focused',
      runtimeResidentActionCue: 'observe_focus',
      playbackCueFacialCue: 'focused',
      playbackCueActionCue: 'observe_focus',
      driverFaceCue: 'focused',
      driverActionCue: 'observe_focus',
      authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
      authorityMismatchSummary: null,
      authorityMismatchDisplay: null,
      prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-vrm-1',
      matchedSignals: [
        'renderer-target:vrm',
        'runtime-body:settled',
        'runtime-continuity:ambient-covision',
        'runtime-emotion:tired',
        'runtime-delivery:gentle',
        'runtime-facialCue:focused',
        'runtime-actionCue:observe_focus',
        'playback-facialCue:focused',
        'playback-actionCue:observe_focus',
        'driver-faceCue:focused',
        'driver-actionCue:observe_focus',
        'authority-face:yes',
        'authority-motion:yes',
        'authority-lipsync:yes',
      ],
      missingSignals: [],
      driftingSignals: [],
      reasons: [
        'Runtime dynamics still publish focused/observe_focus with tired/gentle output, so the renderer runtime is carrying the same embodiment projection rather than inventing a separate shell state.',
        'Playback cue and driver execution both still consume focused and observe_focus, so the visible face and action are the same ones projected by the resident line.',
        'Resident projection is still carrying one continuous manifestation line into renderer authority, so the visible embodiment remains downstream of persona-guided private thought rather than a detached renderer-only posture.',
        'Authority matching remains face:yes motion:yes lipsync:yes on vrm, which shows the bound renderer segment is the one the desktop runtime actually executed.',
        'Prosody authority still anchors energy-phoneme-hybrid on segment-vrm-1, so the mouth-driving chain remains attributable to one authoritative speech segment instead of a renderer-local guess.',
      ],
    })
  })

  it('surfaces explicit renderer drift cause when resident prediction and actual renderer output diverge', () => {
    const projection = buildSelfEvolutionRendererAuthorityProjection({
      embodimentOutputProjection: {
        status: 'grounded',
        projectedBodyState: 'settled',
        projectedContinuityMode: 'ambient-covision',
        projectedFacialCue: 'focused',
        projectedActionCue: 'observe_focus',
        projectedBaseEmotion: 'tired',
        projectedDelivery: 'gentle',
        residentSignature: 'resident|protective-watch|focused|observe_focus',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        rendererAlignment: {
          live2d: {
            predicted: 'Soft Gaze',
            actual: 'Focus Inspect',
            reason: 'preferred',
            status: 'drifted',
            driftKind: 'alias-resolution-drift',
            driverCue: 'focused',
            driverSource: 'prosody-authority',
          },
          vrm: null,
        },
        driverSummary: {
          rendererTarget: 'live2d',
          face: {
            cue: 'focused',
            source: 'prosody-authority',
            confidence: 0.94,
            segmentId: 'segment-live2d-1',
          },
          motion: {
            cue: 'observe_focus',
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-live2d-1',
          },
          lipsync: null,
        },
        playbackTelemetry: {
          rendererTarget: 'live2d',
          prosodyAuthority: {
            segmentId: 'segment-live2d-1',
            provenance: 'authority-bound',
            source: 'prosody-authority',
            mode: 'energy-phoneme-hybrid',
            cueProsodyWeight: 0.35,
            cueMouthWeight: 0.35,
            cueHeadWeight: 0.32,
            visemePeakWeight: 0.75,
            summary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-live2d-1',
          },
          driverAuthority: {
            segmentId: 'segment-live2d-1',
            rendererTarget: 'live2d',
            matchedDrivers: ['face', 'motion'],
            sources: ['prosody-authority', 'timeline-projection'],
            faceSegmentMatched: true,
            motionSegmentMatched: true,
            lipsyncSegmentMatched: false,
          },
          cue: {
            id: 'segment-live2d-1',
            facialCue: 'focused',
            actionCue: 'observe_focus',
            rendererHints: null,
            rendererSettle: null,
          },
          actualDurationMs: 220,
          plannedDurationMs: 220,
          driftMs: 0,
          settleMs: 220,
          stopReason: null,
          drivers: {
            face: {
              emotion: 'thinking',
              facialCue: 'focused',
              intensity: 0.52,
              holdMs: 320,
              source: 'prosody-authority',
              confidence: 0.94,
              preUtteranceCue: 'steady-inhale',
              postUtteranceCue: 'soft-release',
              segmentId: 'segment-live2d-1',
            },
            lipsync: null,
            motion: {
              idleBase: 'idle_settle',
              attentionMode: 'attentive',
              actionCue: 'observe_focus',
              intensity: 0.34,
              holdMs: 240,
              source: 'timeline-projection',
              confidence: 0.88,
              segmentId: 'segment-live2d-1',
            },
          },
        },
      } as any,
      live2dAuthorityView: {
        cueId: 'segment-live2d-1',
        plannedExpressionAliases: ['Soft Gaze'],
        consumedExpressionName: 'Focus Inspect',
        expressionAligned: false,
        plannedMotionAliases: ['ObserveSoft'],
        consumedMotionGroup: 'ObserveSoft',
        motionAligned: true,
        plannedFaceCue: 'focused',
        consumedFaceCue: 'focused',
        faceSource: 'prosody-authority',
        faceSegmentAligned: true,
        plannedMotionCue: 'observe_focus',
        consumedMotionCue: 'observe_focus',
        motionSource: 'timeline-projection',
        motionSegmentAligned: true,
        consumedLipsyncCue: null,
        lipsyncSource: null,
        lipsyncConfidence: null,
        lipsyncSegmentAligned: null,
        plannedLive2dFacialReleaseMs: 320,
        consumedLive2dFacialReleaseMs: 320,
        facialReleaseAligned: true,
        plannedLive2dMotionFollowThroughMs: 440,
        consumedLive2dMotionFollowThroughMs: 440,
        motionFollowThroughAligned: true,
      },
      vrmAuthorityView: null,
      playbackCueAuthorityView: {
        cueId: 'segment-live2d-1',
        authoritySegmentId: 'segment-live2d-1',
        authorityRendererTarget: 'live2d',
        authorityMatchedDrivers: ['face', 'motion'],
        authoritySources: ['prosody-authority', 'timeline-projection'],
        faceSegmentMatched: true,
        motionSegmentMatched: true,
        lipsyncSegmentMatched: false,
        authorityBindingSummary: 'target=live2d | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        settleAuthoritySummary: 'segment=segment-live2d-1 | target=live2d | drivers=face, motion | sources=prosody-authority, timeline-projection',
        preferredExpressionAliases: ['Soft Gaze'],
        preferredMotionAliases: ['ObserveSoft'],
        live2dFacialReleaseMs: 320,
        live2dMotionFollowThroughMs: 440,
        vrmActionFadeMs: null,
        vrmExpressionBlendMs: null,
      },
    })

    expect(projection?.driftingSignals).toContain('renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority')
    expect(projection?.reasons).toContain('Resident projection is still carrying one continuous manifestation line into renderer authority, so the visible embodiment remains downstream of persona-guided private thought rather than a detached renderer-only posture.')
    expect(projection?.reasons).toContain('Renderer drift still shows resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority, so the visible face is diverging after mind-to-render projection rather than before it.')
    expect(projection?.reasons).toContain('Prosody authority still anchors energy-phoneme-hybrid on segment-live2d-1, so the mouth-driving chain remains attributable to one authoritative speech segment instead of a renderer-local guess.')
  })

  it('prefers snapshot-native renderer drift summary over locally recomputed renderer alignment text', () => {
    const projection = buildSelfEvolutionRendererAuthorityProjection({
      embodimentOutputProjection: {
        status: 'grounded',
        projectedBodyState: 'settled',
        projectedContinuityMode: 'ambient-covision',
        projectedFacialCue: 'focused',
        projectedActionCue: 'observe_focus',
        projectedBaseEmotion: 'tired',
        projectedDelivery: 'gentle',
        residentSignature: 'resident|protective-watch|focused|observe_focus',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        rendererAlignment: {
          live2d: {
            predicted: 'Soft Gaze',
            actual: 'Focus Inspect',
            reason: 'preferred',
            status: 'drifted',
            driftKind: 'alias-resolution-drift',
            driverCue: 'focused',
            driverSource: 'prosody-authority',
          },
          vrm: null,
        },
        rendererDriftSummary: {
          live2d: '上游 Live2D 显形归因',
          vrm: null,
          primary: '上游 Live2D 显形归因',
        },
        driverSummary: {
          rendererTarget: 'live2d',
          face: {
            cue: 'focused',
            source: 'prosody-authority',
            confidence: 0.94,
            segmentId: 'segment-live2d-1',
          },
          motion: {
            cue: 'observe_focus',
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-live2d-1',
          },
          lipsync: null,
        },
        playbackTelemetry: {
          rendererTarget: 'live2d',
          driverAuthority: {
            segmentId: 'segment-live2d-1',
            rendererTarget: 'live2d',
            matchedDrivers: ['face', 'motion'],
            sources: ['prosody-authority', 'timeline-projection'],
            faceSegmentMatched: true,
            motionSegmentMatched: true,
            lipsyncSegmentMatched: false,
          },
          cue: {
            id: 'segment-live2d-1',
            facialCue: 'focused',
            actionCue: 'observe_focus',
          },
          actualDurationMs: 220,
          plannedDurationMs: 220,
          driftMs: 0,
          settleMs: 220,
          stopReason: null,
          drivers: {
            face: {
              emotion: 'thinking',
              facialCue: 'focused',
              intensity: 0.52,
              holdMs: 320,
              source: 'prosody-authority',
              confidence: 0.94,
              preUtteranceCue: 'steady-inhale',
              postUtteranceCue: 'soft-release',
              segmentId: 'segment-live2d-1',
            },
            lipsync: null,
            motion: {
              idleBase: 'idle_settle',
              attentionMode: 'attentive',
              actionCue: 'observe_focus',
              intensity: 0.34,
              holdMs: 240,
              source: 'timeline-projection',
              confidence: 0.88,
              segmentId: 'segment-live2d-1',
            },
          },
        },
      } as any,
      live2dAuthorityView: null,
      vrmAuthorityView: null,
      playbackCueAuthorityView: {
        cueId: 'segment-live2d-1',
        authoritySegmentId: 'segment-live2d-1',
        authorityRendererTarget: 'live2d',
        authorityMatchedDrivers: ['face', 'motion'],
        authoritySources: ['prosody-authority', 'timeline-projection'],
        faceSegmentMatched: true,
        motionSegmentMatched: true,
        lipsyncSegmentMatched: false,
        authorityBindingSummary: 'target=live2d | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        settleAuthoritySummary: 'segment=segment-live2d-1 | target=live2d | drivers=face, motion | sources=prosody-authority, timeline-projection',
        preferredExpressionAliases: ['Soft Gaze'],
        preferredMotionAliases: ['ObserveSoft'],
        live2dFacialReleaseMs: 320,
        live2dMotionFollowThroughMs: 440,
        vrmActionFadeMs: null,
        vrmExpressionBlendMs: null,
      },
    })

    expect(projection?.driftingSignals).toContain('renderer-drift:上游 Live2D 显形归因')
    expect(projection?.reasons).toContain('Renderer drift still shows 上游 Live2D 显形归因, so the visible face is diverging after mind-to-render projection rather than before it.')
  })

  it('surfaces explicit lipsync authority drift when the bound segment stops matching', () => {
    const projection = buildSelfEvolutionRendererAuthorityProjection({
      embodimentOutputProjection: {
        status: 'grounded',
        projectedBodyState: 'settled',
        projectedContinuityMode: 'ambient-covision',
        projectedFacialCue: 'focused',
        projectedActionCue: 'observe_focus',
        projectedBaseEmotion: 'tired',
        projectedDelivery: 'gentle',
        residentSignature: 'resident|protective-watch|focused|observe_focus',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        driverSummary: {
          rendererTarget: 'vrm',
          face: {
            cue: 'focused',
            source: 'prosody-authority',
            confidence: 0.94,
            segmentId: 'segment-vrm-1',
          },
          motion: {
            cue: 'observe_focus',
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-vrm-1',
          },
          lipsync: {
            cue: 'I',
            source: 'prosody-authority',
            confidence: 0.91,
            segmentId: 'segment-vrm-2',
            mode: 'energy-phoneme-hybrid',
          },
        },
        playbackTelemetry: {
          rendererTarget: 'vrm',
          driverAuthority: {
            segmentId: 'segment-vrm-1',
            rendererTarget: 'vrm',
            matchedDrivers: ['face', 'motion'],
            sources: ['prosody-authority', 'timeline-projection'],
            faceSegmentMatched: true,
            motionSegmentMatched: true,
            lipsyncSegmentMatched: false,
          },
          cue: {
            id: 'segment-vrm-1',
            facialCue: 'focused',
            actionCue: 'observe_focus',
          },
          actualDurationMs: 220,
          plannedDurationMs: 220,
          driftMs: 0,
          settleMs: 220,
          stopReason: null,
          drivers: {
            face: {
              emotion: 'thinking',
              facialCue: 'focused',
              intensity: 0.52,
              holdMs: 320,
              source: 'prosody-authority',
              confidence: 0.94,
              preUtteranceCue: 'steady-inhale',
              postUtteranceCue: 'soft-release',
              segmentId: 'segment-vrm-1',
            },
            lipsync: {
              mode: 'energy-phoneme-hybrid',
              playbackPhase: 'playing',
              segmentId: 'segment-vrm-2',
              visemeHints: [],
            },
            motion: {
              idleBase: 'idle_settle',
              attentionMode: 'attentive',
              actionCue: 'observe_focus',
              intensity: 0.34,
              holdMs: 240,
              source: 'timeline-projection',
              confidence: 0.88,
              segmentId: 'segment-vrm-1',
            },
          },
        },
      } as any,
      vrmAuthorityView: {
        cueId: 'segment-vrm-1',
        plannedExpressionAliases: ['CalmInspect'],
        consumedExpressionAliases: ['CalmInspect'],
        expressionAligned: true,
        plannedMotionAliases: ['ObserveSoft'],
        consumedMotionAliases: ['ObserveSoft'],
        motionAligned: true,
        plannedFaceCue: 'focused',
        consumedFaceCue: 'focused',
        faceSource: 'prosody-authority',
        faceSegmentAligned: true,
        plannedActionCue: 'observe_focus',
        consumedActionCue: 'observe_focus',
        motionSource: 'timeline-projection',
        motionSegmentAligned: true,
        consumedLipsyncCue: 'I',
        lipsyncSource: 'prosody-authority',
        lipsyncConfidence: 0.91,
        lipsyncSegmentAligned: false,
        plannedVrmActionFadeMs: null,
        consumedVrmActionFadeMs: null,
        vrmActionFadeAligned: null,
        plannedVrmExpressionBlendMs: null,
        consumedVrmExpressionBlendMs: null,
        vrmExpressionBlendAligned: null,
      },
      live2dAuthorityView: null,
      playbackCueAuthorityView: {
        cueId: 'segment-vrm-1',
        authoritySegmentId: 'segment-vrm-1',
        authorityRendererTarget: 'vrm',
        authorityMatchedDrivers: ['face', 'motion'],
        authoritySources: ['prosody-authority', 'timeline-projection'],
        faceSegmentMatched: true,
        motionSegmentMatched: true,
        lipsyncSegmentMatched: false,
        authorityBindingSummary: 'target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        settleAuthoritySummary: 'segment=segment-vrm-1 | target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection',
        preferredExpressionAliases: [],
        preferredMotionAliases: [],
        live2dFacialReleaseMs: null,
        live2dMotionFollowThroughMs: null,
        vrmActionFadeMs: null,
        vrmExpressionBlendMs: null,
      },
    })

    expect(projection?.matchedSignals).toContain('authority-face:yes')
    expect(projection?.matchedSignals).toContain('authority-motion:yes')
    expect(projection?.driftingSignals).toContain('authority-lipsync:no')
    expect(projection?.driftingSignals).toContain('authority-mismatch:口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。')
    expect(projection?.authorityMatchSummary).toBe('face:yes motion:yes lipsync:no')
    expect(projection?.authorityMismatchSummary).toBe('lipsync-mismatch')
    expect(projection?.authorityMismatchDisplay).toBe('口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。')
    expect(projection?.reasons).toContain('口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。')
  })

  it('prefers speech embodiment authority summaries even when playback cue authority view is absent', () => {
    const projection = buildSelfEvolutionRendererAuthorityProjection({
      embodimentOutputProjection: {
        status: 'grounded',
        projectedBodyState: 'settled',
        projectedContinuityMode: 'ambient-covision',
        projectedFacialCue: 'focused',
        projectedActionCue: 'observe_focus',
        projectedBaseEmotion: 'tired',
        projectedDelivery: 'gentle',
        residentSignature: 'resident|protective-watch|focused|observe_focus',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: null,
            personaOpeningGuidance: null,
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: [],
            focusBeliefId: null,
            focusInquiryId: null,
            commitmentId: null,
            runtimeThreadId: null,
            governorDrive: null,
            governorIntentionId: null,
            selectedThoughtThreadId: null,
          },
        },
        authoritySummary: {
          cueId: 'segment-summary-only',
          segmentId: 'segment-summary-only',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion'],
          matchedSources: ['prosody-authority', 'timeline-projection'],
          bindingSummary: '上游 authority 绑定',
          matchSummary: '上游 authority 命中',
          authorityMismatchSummary: 'lipsync-mismatch',
          authorityMismatchReasonSummary: '上游 authority reason：当前口型落点已经偏离绑定片段。',
          authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但口型落点已经和绑定片段分叉；当前表面策略是 procedural-carry。',
          settleSummary: '上游 authority settle',
        },
        driverExecutionSummary: 'motion=上游驱动执行',
        playbackTelemetry: {
          rendererTarget: 'vrm',
          driverAuthority: {
            segmentId: 'segment-summary-only',
            rendererTarget: 'vrm',
            matchedDrivers: ['face', 'motion'],
            sources: ['prosody-authority', 'timeline-projection'],
            faceSegmentMatched: true,
            motionSegmentMatched: true,
            lipsyncSegmentMatched: false,
          },
          cue: {
            id: 'segment-summary-only',
            facialCue: 'focused',
            actionCue: 'observe_focus',
          },
          actualDurationMs: 220,
          plannedDurationMs: 220,
          driftMs: 0,
          settleMs: 220,
          stopReason: null,
          drivers: {
            face: null,
            motion: {
              idleBase: 'idle_settle',
              attentionMode: 'attentive',
              actionCue: 'observe_focus',
              intensity: 0.34,
              holdMs: 240,
              source: 'timeline-projection',
              confidence: 0.88,
              segmentId: 'segment-summary-only',
            },
            lipsync: null,
          },
        },
        driverSummary: {
          rendererTarget: 'vrm',
          face: null,
          motion: {
            cue: 'observe_focus',
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-summary-only',
          },
          lipsync: null,
        },
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:summary:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
      } as any,
      vrmAuthorityView: null,
      live2dAuthorityView: null,
      playbackCueAuthorityView: null,
    })

    expect(projection?.authorityMatchSummary).toBe('上游 authority 命中')
    expect(projection?.authorityMismatchSummary).toBe('lipsync-mismatch')
    expect(projection?.authorityMismatchDisplay).toBe('上游 authority 展示：当前仍在同一主线程里，但口型落点已经和绑定片段分叉；当前表面策略是 procedural-carry。')
    expect(projection?.driftingSignals).toContain('authority-mismatch:上游 authority 展示：当前仍在同一主线程里，但口型落点已经和绑定片段分叉；当前表面策略是 procedural-carry。')
    expect(projection?.reasons).toContain('Authority matching remains 上游 authority 命中 on vrm, which shows the bound renderer segment is the one the desktop runtime actually executed.')
    expect(projection?.reasons).toContain('上游 authority 展示：当前仍在同一主线程里，但口型落点已经和绑定片段分叉；当前表面策略是 procedural-carry。')
  })

  it('does not reuse another cue authority summary when playback cue authority view already scopes the current cue', () => {
    const projection = buildSelfEvolutionRendererAuthorityProjection({
      embodimentOutputProjection: {
        status: 'grounded',
        projectedBodyState: 'settled',
        projectedContinuityMode: 'ambient-covision',
        projectedFacialCue: 'focused',
        projectedActionCue: 'observe_focus',
        projectedBaseEmotion: 'tired',
        projectedDelivery: 'gentle',
        residentSignature: 'resident|protective-watch|focused|observe_focus',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: null,
            personaOpeningGuidance: null,
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: [],
            focusBeliefId: null,
            focusInquiryId: null,
            commitmentId: null,
            runtimeThreadId: null,
            governorDrive: null,
            governorIntentionId: null,
            selectedThoughtThreadId: null,
          },
        },
        authoritySummary: {
          cueId: 'segment-other-authority',
          segmentId: 'segment-other-authority',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion'],
          matchedSources: ['prosody-authority', 'timeline-projection'],
          matchSummary: '上游 authority 命中',
          authorityMismatchSummary: 'lipsync-mismatch',
          authorityMismatchReasonSummary: '上游 authority reason：当前口型落点已经偏离绑定片段。',
          authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但口型落点已经和绑定片段分叉；当前表面策略是 procedural-carry。',
        },
        playbackTelemetry: {
          rendererTarget: 'vrm',
          driverAuthority: {
            segmentId: 'segment-other-authority',
            rendererTarget: 'vrm',
            matchedDrivers: ['face', 'motion'],
            sources: ['prosody-authority', 'timeline-projection'],
            faceSegmentMatched: true,
            motionSegmentMatched: true,
            lipsyncSegmentMatched: false,
          },
          cue: {
            id: 'segment-current-playback',
            facialCue: 'focused',
            actionCue: 'observe_focus',
          },
          drivers: {
            face: {
              emotion: 'thinking',
              facialCue: 'focused',
              intensity: 0.52,
              holdMs: 320,
              source: 'prosody-authority',
              confidence: 0.94,
              preUtteranceCue: 'steady-inhale',
              postUtteranceCue: 'soft-release',
              segmentId: 'segment-current-playback',
            },
            motion: {
              idleBase: 'idle_settle',
              attentionMode: 'attentive',
              actionCue: 'observe_focus',
              intensity: 0.34,
              holdMs: 240,
              source: 'timeline-projection',
              confidence: 0.88,
              segmentId: 'segment-current-playback',
            },
            lipsync: {
              mode: 'energy-phoneme-hybrid',
              playbackPhase: 'playing',
              segmentId: 'segment-current-playback',
              visemeHints: [],
            },
          },
        },
        driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:summary:scoped-1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
      } as any,
      vrmAuthorityView: null,
      live2dAuthorityView: null,
      playbackCueAuthorityView: {
        cueId: 'segment-current-playback',
        authoritySegmentId: 'segment-other-authority',
        authorityRendererTarget: 'vrm',
        authorityMatchedDrivers: ['face', 'motion'],
        authoritySources: ['prosody-authority', 'timeline-projection'],
        faceSegmentMatched: true,
        motionSegmentMatched: true,
        lipsyncSegmentMatched: false,
        authorityBindingSummary: null,
        authorityMatchSummary: null,
        settleAuthoritySummary: null,
        preferredExpressionAliases: [],
        preferredMotionAliases: [],
        live2dFacialReleaseMs: null,
        live2dMotionFollowThroughMs: null,
        vrmActionFadeMs: null,
        vrmExpressionBlendMs: null,
      },
    })

    expect(projection?.authorityMatchSummary).toBeNull()
    expect(projection?.authorityMismatchSummary).toBe('lipsync-mismatch')
    expect(projection?.authorityMismatchDisplay).toBe('口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。')
    expect(projection?.driftingSignals).toContain('authority-mismatch:口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。')
    expect(projection?.reasons).not.toContain('Authority matching remains 上游 authority 命中 on vrm, which shows the bound renderer segment is the one the desktop runtime actually executed.')
  })
})
