import { describe, expect, it } from 'vitest'

import { buildSpeechAuthoritySegmentRows } from './performance-visualizer-speech-authority'
import { buildAuthorityTableRows } from './performance-visualizer-authority-table'

describe('performance visualizer authority table rows', () => {
  it('flattens compact authority display rows into table-ready cells', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-live2d-1',
        cueText: '继续看这里。',
        surfaces: 'live2d',
        lanes: 'expression, lipsync, settle',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'live2d',
            lane: 'expression',
            planned: 'CalmInspect',
            consumed: 'RecoverSoft',
            source: 'n/a',
            confidence: 'n/a',
            aligned: false,
            settleLines: [],
          },
          {
            surface: 'live2d',
            lane: 'settle',
            planned: 'settle',
            consumed: 'settle',
            source: 'n/a',
            confidence: 'n/a',
            settle: {
              live2dFacialReleaseMs: {
                planned: 320,
                consumed: 300,
              },
              live2dMotionFollowThroughMs: {
                planned: 440,
                consumed: 420,
              },
            },
            aligned: false,
            settleLines: [
              'live2dFacialReleaseMs: 320 -> 300',
              'live2dMotionFollowThroughMs: 440 -> 420',
            ],
          },
        ],
      },
    ] as any)

    expect((rows[0] as any).speechSummaryLines).toEqual([])

    expect(rows).toEqual([
      {
        cueId: 'segment-live2d-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'expression',
        planned: 'CalmInspect',
        consumed: 'RecoverSoft',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'n/a',
        settleLive2dFacialReleaseMs: 'n/a',
        settleLive2dMotionFollowThroughMs: 'n/a',
        settleVrmActionFadeMs: 'n/a',
        settleVrmExpressionBlendMs: 'n/a',
        authorityBindingSummary: 'n/a',
        voiceSummary: 'n/a',
        prosodyAuthoritySummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
        authorityTrustSummary: null,
        rendererDriftSummary: null,
        authoritySegmentMatched: null,
        authorityMatchedDrivers: [],
        authorityMatchedSources: [],
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        speechSummaryLines: [],
      },
      {
        cueId: 'segment-live2d-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'settle',
        planned: 'settle',
        consumed: 'settle',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'live2dFacialReleaseMs: 320 -> 300 | live2dMotionFollowThroughMs: 440 -> 420',
        settleLive2dFacialReleaseMs: '320 -> 300',
        settleLive2dMotionFollowThroughMs: '440 -> 420',
        settleVrmActionFadeMs: 'n/a',
        settleVrmExpressionBlendMs: 'n/a',
        authorityBindingSummary: 'n/a',
        voiceSummary: 'n/a',
        prosodyAuthoritySummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        authorityMatchSummary: 'n/a',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'n/a',
        authorityTrustSummary: null,
        rendererDriftSummary: null,
        authoritySegmentMatched: null,
        authorityMatchedDrivers: [],
        authorityMatchedSources: [],
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        speechSummaryLines: [],
      },
    ])
  })

  it('threads structured speech observability into each authority table row for the same cue', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-zh-1',
        cueText: '继续看这里。',
        surfaces: 'live2d, vrm',
        lanes: 'expression, lipsync, settle',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'live2d',
            lane: 'lipsync',
            planned: 'I',
            consumed: 'A',
            source: 'prosody-authority',
            confidence: '0.91',
            aligned: false,
            settleLines: [],
          },
        ],
      },
    ] as any, {
      'segment-zh-1': {
        cueId: 'segment-zh-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        speechEvidence: {
          voiceSummary: '上游语音韵律',
          prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
          authorityMatchSummary: '上游 authority 命中',
          topVisemeSummary: '上游主口型',
          cueSummary: '上游微表情线索',
          cueIdentityPresent: true,
          cueProsodyPresent: true,
          personaStyleSummary: '上游人设风格',
          timingSummary: '上游时序节奏',
          driverExecutionSummary: '上游驱动执行',
          visemeHintsSummary: '上游口型提示',
        },
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityBindingSummary: 'target=vrm | drivers=face, lipsync | sources=prosody-authority | matches=face:yes motion:no lipsync:yes',
        authorityMismatchSummary: 'motion-mismatch',
        authorityMismatchReasonSummary: '动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型。',
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing',
        authorityMatchSummary: 'face:yes motion:no lipsync:yes',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=none | execution=none | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
        settleAuthoritySummary: null,
        rendererDriftSummary: 'resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      },
    })

    expect((rows[0] as any).speechSummaryLines).toEqual([
      'authority: 目标 VRM，驱动 表情、口型，来源 prosody-authority，命中 表情命中 / 动作未命中 / 口型命中',
      'authority-match: 表情命中 / 动作未命中 / 口型命中',
      'authority-trust: 韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
      'authority-mismatch: 动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型。',
      'renderer-drift: resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      'voice: 上游语音韵律',
      'prosody-authority: 模式 energy-phoneme-hybrid，韵律 0.35，口部 0.35，头部 0.32，峰值口型 0.75，权威绑定，来源 韵律权威，片段 segment-zh-1',
      'visemes: 上游主口型',
      'cue: 上游微表情线索',
      'persona-style: 上游人设风格',
      'timing: 上游时序节奏',
      'driver-execution: 上游驱动执行',
      'trace-embodiment: 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 表情、口型，实际执行 表情+动作+口型，场景 深夜疲劳照看，姿态 先观察后表达，来源链 fatigue -> care -> grounded-recall',
      'viseme-hints: 上游口型提示',
    ])

    expect(rows).toEqual([
      {
        cueId: 'segment-zh-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'live2d',
        lane: 'lipsync',
        planned: 'I',
        consumed: 'A',
        source: 'prosody-authority',
        confidence: '0.91',
        settle: 'n/a',
        settleLive2dFacialReleaseMs: 'n/a',
        settleLive2dMotionFollowThroughMs: 'n/a',
        settleVrmActionFadeMs: 'n/a',
        settleVrmExpressionBlendMs: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=face, lipsync | sources=prosody-authority | matches=face:yes motion:no lipsync:yes',
        voiceSummary: '上游语音韵律',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
        topVisemeSummary: '上游主口型',
        cueSummary: '上游微表情线索',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        personaStyleSummary: '上游人设风格',
        timingSummary: '上游时序节奏',
        driverExecutionSummary: '上游驱动执行',
        authorityMatchSummary: 'face:yes motion:no lipsync:yes',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=face, lipsync | execution=face+motion+lipsync | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall',
        visemeHintsSummary: '上游口型提示',
        settleAuthoritySummary: 'n/a',
        authorityTrustSummary: '韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityMismatchSummary: 'motion-mismatch',
        authorityMismatchReasonSummary: '动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型。',
        authorityMismatchDisplay: '动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型。',
        rendererDriftSummary: 'resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        speechSummaryLines: [
          'authority: 目标 VRM，驱动 表情、口型，来源 prosody-authority，命中 表情命中 / 动作未命中 / 口型命中',
          'authority-match: 表情命中 / 动作未命中 / 口型命中',
          'authority-trust: 韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
          'authority-mismatch: 动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型。',
          'renderer-drift: resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
          'voice: 上游语音韵律',
          'prosody-authority: 模式 energy-phoneme-hybrid，韵律 0.35，口部 0.35，头部 0.32，峰值口型 0.75，权威绑定，来源 韵律权威，片段 segment-zh-1',
          'visemes: 上游主口型',
          'cue: 上游微表情线索',
          'persona-style: 上游人设风格',
          'timing: 上游时序节奏',
          'driver-execution: 上游驱动执行',
          'trace-embodiment: 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 表情、口型，实际执行 表情+动作+口型，场景 深夜疲劳照看，姿态 先观察后表达，来源链 fatigue -> care -> grounded-recall',
          'viseme-hints: 上游口型提示',
        ],
      },
    ])
  })

  it('reuses speech-row prosody authority summary when authority trust must be derived locally', () => {
    const speechRows = buildSpeechAuthoritySegmentRows([
      {
        cueId: 'segment-driver-table-native',
        cueText: '继续跟上。',
        surfaces: ['vrm'],
        lanes: ['lipsync'],
        aligned: true,
        driftStatus: 'all-aligned',
        entries: [],
      },
    ] as any, {
      articulation: null,
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        prosodyAuthoritySummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        visemeHintsSummary: null,
      },
      authorityBinding: {
        segmentId: 'segment-driver-table-native',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        faceSegmentMatched: false,
        motionSegmentMatched: false,
        lipsyncSegmentMatched: true,
      },
      authoritySummary: null,
      authorityMismatchSummary: null,
      authorityMismatchReasonSummary: null,
      authorityMismatchDisplay: null,
      cueMicro: null,
      cueMicroSummary: null,
      driverExecution: null,
      visemeHints: [],
      visemeHintsSummary: null,
      driverExecutionSummary: null,
      playbackTelemetry: {
        driverAuthority: {
          segmentId: 'segment-driver-table-native',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
          prosodyAuthority: {
            segmentId: 'segment-driver-table-native',
            provenance: 'authority-bound',
            source: 'prosody-authority',
            mode: 'energy-phoneme-hybrid',
            cueProsodyWeight: 0.35,
            cueMouthWeight: 0.35,
            cueHeadWeight: 0.32,
            visemePeakWeight: 0.75,
          },
        },
        prosodyAuthority: null,
      },
      rendererAlignmentSummary: {
        live2d: null,
        vrm: null,
      },
    } as any)
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-driver-table-native',
        cueText: '继续跟上。',
        surfaces: 'vrm',
        lanes: 'lipsync',
        driftStatus: 'all-aligned',
        aligned: true,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'lipsync',
            planned: 'I',
            consumed: 'I',
            source: 'prosody-authority',
            confidence: '0.94',
            aligned: true,
            settleLines: [],
          },
        ],
      },
    ] as any, {
      'segment-driver-table-native': speechRows[0],
    } as any)

    expect(rows[0]?.prosodyAuthoritySummary).toBe(
      'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-driver-table-native',
    )
    expect(rows[0]?.authorityTrustSummary).toBe('韵律权威链已重新绑定到当前片段，可直接进入长期基线。')
  })

  it('adds settle authority labeling to settle rows without changing non-settle rows', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-settle-1',
        cueText: '这里是 settle authority.',
        surfaces: 'vrm',
        lanes: 'settle',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'settle',
            planned: 'settle',
            consumed: 'settle',
            source: 'n/a',
            confidence: 'n/a',
            aligned: false,
            settle: {
              vrmActionFadeMs: {
                planned: 280,
                consumed: 320,
              },
            },
            settleLines: [
              'vrmActionFadeMs: 280 -> 320',
            ],
          },
        ],
      },
    ] as any, {
      'segment-settle-1': {
        cueId: 'segment-settle-1',
        cueText: '这里是 settle authority.',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion'],
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityBindingSummary: 'target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMismatchSummary: 'lipsync-mismatch',
        authorityMismatchReasonSummary: '口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是无执行。',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        voiceSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: null,
        visemeHintsSummary: null,
        settleAuthoritySummary: 'authority-bound | segment=segment-settle-1 | target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
      },
    } as any)

    expect(rows).toEqual([
      {
        cueId: 'segment-settle-1',
        cueText: '这里是 settle authority.',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'settle',
        planned: 'settle',
        consumed: 'settle',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'vrmActionFadeMs: 280 -> 320',
        settleLive2dFacialReleaseMs: 'n/a',
        settleLive2dMotionFollowThroughMs: 'n/a',
        settleVrmActionFadeMs: '280 -> 320',
        settleVrmExpressionBlendMs: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        voiceSummary: 'n/a',
        prosodyAuthoritySummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        traceEmbodimentSummary: 'n/a',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'authority-bound | segment=segment-settle-1 | target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityTrustSummary: null,
        rendererDriftSummary: null,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion'],
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityMismatchSummary: 'lipsync-mismatch',
        authorityMismatchReasonSummary: '口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是无执行。',
        authorityMismatchDisplay: '口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是无执行。',
        speechSummaryLines: [
          'authority: 目标 VRM，驱动 表情、动作，来源 prosody-authority, timeline-projection，命中 表情命中 / 动作命中 / 口型未命中',
          'authority-match: 表情命中 / 动作命中 / 口型未命中',
          'authority-mismatch: 口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是无执行。',
          'settle-authority: authority-bound，片段 segment-settle-1，目标 VRM，驱动 表情、动作，来源 prosody-authority, timeline-projection',
        ],
      },
    ])
  })

  it('prefers structured authority sources over parsing them back out of summary text', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-structured-source',
        cueText: '只看结构化 source threading。',
        surfaces: 'vrm',
        lanes: 'lipsync',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'lipsync',
            planned: 'I',
            consumed: 'A',
            source: 'prosody-authority',
            confidence: '0.91',
            aligned: false,
            settleLines: [],
          },
        ],
      },
    ] as any, {
      'segment-structured-source': {
        cueId: 'segment-structured-source',
        cueText: '只看结构化 source threading。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'lipsync'],
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityBindingSummary: 'target=vrm | drivers=face, lipsync | matches=face:yes motion:no lipsync:yes',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMatchSummary: 'face:yes motion:no lipsync:yes',
        voiceSummary: null,
        topVisemeSummary: null,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: null,
        visemeHintsSummary: null,
        settleAuthoritySummary: null,
      },
    } as any)

    expect(rows).toEqual([
      expect.objectContaining({
        cueId: 'segment-structured-source',
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityMismatchSummary: 'motion-mismatch',
        authorityMismatchReasonSummary: '动作 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是无执行。',
        speechSummaryLines: [
          'authority: 目标 VRM，驱动 表情、口型，命中 表情命中 / 动作未命中 / 口型命中',
          'authority-match: 表情命中 / 动作未命中 / 口型命中',
        'authority-mismatch: 动作 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是无执行。',
        ],
      }),
    ])
  })

  it('keeps technical mismatch labels out of user-facing summary lines when a Chinese authority reason is available', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-human-readable-mismatch',
        cueText: '优先自然语言 authority explainability。',
        surfaces: 'vrm',
        lanes: 'lipsync',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'lipsync',
            planned: 'I',
            consumed: 'A',
            source: 'prosody-authority',
            confidence: '0.91',
            aligned: false,
            settleLines: [],
          },
        ],
      },
    ] as any, {
      'segment-human-readable-mismatch': {
        cueId: 'segment-human-readable-mismatch',
        cueText: '优先自然语言 authority explainability。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion'],
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityBindingSummary: 'target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMismatchSummary: 'lipsync-mismatch',
        authorityMismatchReasonSummary: '口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        voiceSummary: null,
        topVisemeSummary: null,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: null,
        visemeHintsSummary: null,
        settleAuthoritySummary: null,
      },
    } as any)

    expect(rows[0]?.authorityMismatchSummary).toBe('lipsync-mismatch')
    expect(rows[0]?.authorityMismatchReasonSummary).toBe('口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。')
    expect(rows[0]?.speechSummaryLines).toEqual([
      'authority: 目标 VRM，驱动 表情、动作，来源 prosody-authority, timeline-projection，命中 表情命中 / 动作命中 / 口型未命中',
      'authority-match: 表情命中 / 动作命中 / 口型未命中',
      'authority-mismatch: 口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。',
    ])
  })

  it('prefers upstream authority mismatch display text over locally rebuilt reason text', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-display-first',
        cueText: '优先使用上游 authority 展示文案。',
        surfaces: 'vrm',
        lanes: 'lipsync',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'lipsync',
            planned: 'I',
            consumed: 'A',
            source: 'prosody-authority',
            confidence: '0.91',
            aligned: false,
            settleLines: [],
          },
        ],
      },
    ] as any, {
      'segment-display-first': {
        cueId: 'segment-display-first',
        cueText: '优先使用上游 authority 展示文案。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion'],
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityBindingSummary: 'target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMismatchSummary: 'lipsync-mismatch',
        authorityMismatchReasonSummary: '口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。',
        authorityMismatchDisplay: '上游 authority 展示：口型落点和绑定来源已分叉，但仍处于同一条中文主链解释中。',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        voiceSummary: null,
        topVisemeSummary: null,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: null,
        visemeHintsSummary: null,
        settleAuthoritySummary: null,
      },
    } as any)

    expect(rows[0]?.speechSummaryLines).toEqual([
      'authority: 目标 VRM，驱动 表情、动作，来源 prosody-authority, timeline-projection，命中 表情命中 / 动作命中 / 口型未命中',
      'authority-match: 表情命中 / 动作命中 / 口型未命中',
      'authority-mismatch: 上游 authority 展示：口型落点和绑定来源已分叉，但仍处于同一条中文主链解释中。',
    ])
  })

  it('enriches sparse generated trace embodiment summaries in authority table rows with bound authority and execution context', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-trace-enriched',
        cueText: '这里需要把轨迹落点补全到 authority table。',
        surfaces: 'vrm',
        lanes: 'lipsync',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'lipsync',
            planned: 'I',
            consumed: 'A',
            source: 'prosody-authority',
            confidence: '0.91',
            aligned: false,
            settleLines: [],
          },
        ],
      },
    ] as any, {
      'segment-trace-enriched': {
        cueId: 'segment-trace-enriched',
        cueText: '这里需要把轨迹落点补全到 authority table。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['face', 'motion'],
        authorityMatchedSources: ['prosody-authority', 'timeline-projection'],
        authorityBindingSummary: 'target=vrm | drivers=face, motion | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:no',
        authorityMismatchSummary: 'lipsync-mismatch',
        authorityMismatchReasonSummary: '口型 authority 漂移，当前绑定来源是 prosody-authority、timeline-projection，实际执行落点是表情、动作。',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        voiceSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: 'face=attentive/focused@0.61 hold=320 src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first hold=240 src=timeline-projection conf=0.79',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall',
        visemeHintsSummary: null,
        settleAuthoritySummary: null,
      },
    } as any)

    expect(rows[0]?.traceEmbodimentSummary).toBe('turn=care | closure=grounded-recall | surface=procedural-carry | authority=face, motion | execution=face+motion | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall')
    expect(rows[0]?.speechSummaryLines).toContain('trace-embodiment: 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 表情、动作，实际执行 表情+动作，场景 深夜疲劳照看，姿态 先观察后表达，来源链 fatigue -> care -> grounded-recall')
  })

  it('does not rehydrate another cue authority summary after speech rows already scoped it away', () => {
    const rows = buildAuthorityTableRows([
      {
        cueId: 'segment-current-authority',
        cueText: '当前 authority cue。',
        surfaces: 'vrm',
        lanes: 'settle',
        driftStatus: 'partial-drift',
        aligned: false,
        detailRows: [
          {
            surface: 'vrm',
            lane: 'settle',
            planned: 'settle',
            consumed: 'settle',
            source: 'n/a',
            confidence: 'n/a',
            aligned: false,
            settle: {
              vrmActionFadeMs: {
                planned: 280,
                consumed: 320,
              },
            },
            settleLines: [
              'vrmActionFadeMs: 280 -> 320',
            ],
          },
        ],
      },
    ] as any, {
      'segment-current-authority': {
        cueId: 'segment-current-authority',
        cueText: '当前 authority cue。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityBindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        authorityMatchSummary: 'face:no motion:no lipsync:yes',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
        authorityMismatchDisplay: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
        speechEvidence: {
          voiceSummary: null,
          authorityMatchSummary: 'face:no motion:no lipsync:yes',
          topVisemeSummary: null,
          cueSummary: null,
          cueIdentityPresent: false,
          cueProsodyPresent: false,
          personaStyleSummary: null,
          timingSummary: null,
          driverExecutionSummary: null,
          visemeHintsSummary: null,
        },
        voiceSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=none',
        visemeHintsSummary: null,
        settleAuthoritySummary: 'authority-bound | segment=segment-current-authority | target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
    } as any)

    expect(rows).toEqual([
      {
        cueId: 'segment-current-authority',
        cueText: '当前 authority cue。',
        driftStatus: 'partial-drift',
        aligned: false,
        surface: 'vrm',
        lane: 'settle',
        planned: 'settle',
        consumed: 'settle',
        source: 'n/a',
        confidence: 'n/a',
        settle: 'vrmActionFadeMs: 280 -> 320',
        settleLive2dFacialReleaseMs: 'n/a',
        settleLive2dMotionFollowThroughMs: 'n/a',
        settleVrmActionFadeMs: '280 -> 320',
        settleVrmExpressionBlendMs: 'n/a',
        authorityBindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        authorityMatchSummary: 'face:no motion:no lipsync:yes',
        voiceSummary: 'n/a',
        prosodyAuthoritySummary: 'n/a',
        topVisemeSummary: 'n/a',
        cueSummary: 'n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: 'n/a',
        actionCue: 'n/a',
        weightSummary: 'n/a',
        personaStyleSummary: 'n/a',
        timingSummary: 'n/a',
        driverExecutionSummary: 'n/a',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=none',
        visemeHintsSummary: 'n/a',
        settleAuthoritySummary: 'authority-bound | segment=segment-current-authority | target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        authorityTrustSummary: null,
        rendererDriftSummary: null,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
        authorityMismatchDisplay: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
        speechSummaryLines: [
          'authority: 目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
          'authority-match: 表情未命中 / 动作未命中 / 口型命中',
          'authority-mismatch: 表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
          'trace-embodiment: 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 口型，实际执行 无',
          'settle-authority: authority-bound，片段 segment-current-authority，目标 VRM，驱动 口型，来源 prosody-authority',
        ],
      },
    ])
  })
})
