import { describe, expect, it } from 'vitest'

import { buildSpeechObservabilityRows } from './performance-visualizer-speech-observability-rows'
import { buildSpeechObservabilityView } from './performance-visualizer-speech-observability'

describe('performance visualizer speech observability rows', () => {
  it('condenses articulation, cue micro, and viseme hints into scannable summary rows', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0.18,
          O: 0.08,
          U: 0.12,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-zh-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-zh-1',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-zh-1',
            visemeHints: [
              { segmentId: 'segment-zh-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-zh-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
            ],
          },
        },
      },
    })

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'articulation',
        label: 'voice',
        value: '中文韵律，收口 0.84，咬字 0.90，权威绑定，片段 segment-zh-1，来源 韵律权威',
        technicalValue: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-zh-1 | source=prosody-authority',
      },
      {
        section: 'articulation',
        label: 'visemes',
        value: 'A 0.66，闭口 0.41，E 0.24',
        technicalValue: 'A:0.66, closed:0.41, E:0.24',
      },
      {
        section: 'authority',
        label: 'segment-zh-1',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
      {
        section: 'cue',
        label: 'segment-zh-1',
        value: 'focused / observe_focus，韵律 0.36，口部 0.28，头部 0.32，权威绑定，片段 segment-zh-1',
        technicalValue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=authority-bound segment=segment-zh-1',
      },
      {
        section: 'cue',
        label: 'persona-style',
        value: 'observe-first，韵律 -0.07，节拍 -0.06，口部 -0.04，头部 +0.08，权威绑定，片段 segment-zh-1',
        technicalValue: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08 provenance=authority-bound segment=segment-zh-1',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '表情 320ms，动作 240ms，情绪 360ms，片段起始，软打断，保持',
        technicalValue: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '口型 energy-phoneme-hybrid，阶段 播放中',
        technicalValue: 'lipsync=energy-phoneme-hybrid phase=playing',
      },
      {
        section: 'viseme',
        label: 'segment-zh-1',
        value: 'I 权重 0.35（置信 0.94，来源 韵律权威，片段 segment-zh-1），闭口 权重 0.75（置信 0.89，来源 韵律权威，片段 segment-zh-1）',
        technicalValue: 'I:0.35@0.94 src=prosody-authority segment=segment-zh-1 | closed:0.75@0.89 src=prosody-authority segment=segment-zh-1',
      },
    ])
  })

  it('adds renderer drift cause rows when alignment summaries are present', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: {
          predicted: 'Soft Gaze',
          actual: 'Focus Inspect',
          reason: 'preferred',
          status: 'drifted',
          driftKind: 'alias-resolution-drift',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: null,
      },
      rendererDriftSummary: {
        live2d: '上游 Live2D 显形归因',
        vrm: null,
        primary: '上游 Live2D 显形归因',
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: null,
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'renderer-live2d',
        value: '上游 Live2D 显形归因',
      },
    ])
  })

  it('surfaces authority trust when runtime prosody authority rebinds to the current segment', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: {
        cueId: 'segment-zh-1',
        segmentId: 'segment-zh-1',
        rendererTarget: 'vrm',
        bindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        matchSummary: 'face:no motion:no lipsync:yes',
        settleSummary: null,
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        prosodyAuthority: {
          mode: 'energy-phoneme-hybrid',
          cueProsodyWeight: 0.35,
          cueMouthWeight: 0.35,
          cueHeadWeight: 0.32,
          visemePeakWeight: 0.75,
          provenance: 'authority-bound',
          source: 'prosody-authority',
          segmentId: 'segment-zh-1',
        },
        driverAuthority: {
          segmentId: 'segment-zh-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: null,
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'articulation',
        label: 'prosody-authority',
        value: '模式 energy-phoneme-hybrid，韵律 0.35，口部 0.35，头部 0.32，峰值口型 0.75，权威绑定，来源 韵律权威，片段 segment-zh-1',
        technicalValue: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
      },
      {
        section: 'authority',
        label: 'segment-zh-1',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-trust',
        value: '韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行。',
      },
    ])
  })

  it('prefers upstream authority trust text over locally deriving it in observability rows', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-upstream-trust',
        authorityMatchSummary: 'face:no motion:no lipsync:yes',
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        visemeHintsSummary: null,
      },
      authoritySummary: {
        cueId: 'segment-upstream-trust',
        segmentId: 'segment-upstream-trust',
        rendererTarget: 'vrm',
        bindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        matchSummary: 'face:no motion:no lipsync:yes',
        settleSummary: null,
        authorityTrustSummary: '上游 authority trust：已经回到当前片段主链。',
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-upstream-trust',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: null,
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'articulation',
        label: 'prosody-authority',
        value: '模式 energy-phoneme-hybrid，韵律 0.35，口部 0.35，头部 0.32，峰值口型 0.75，权威绑定，来源 韵律权威，片段 segment-upstream-trust',
        technicalValue: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-upstream-trust',
      },
      {
        section: 'authority',
        label: 'segment-upstream-trust',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-trust',
        value: '上游 authority trust：已经回到当前片段主链。',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行。',
      },
    ])
  })

  it('omits empty articulation rows when only voice summary survives', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: '上游 evidence voice',
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        visemeHintsSummary: null,
      },
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: null,
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'articulation',
        label: 'voice',
        value: '上游 evidence voice',
      },
    ])
  })

  it('keeps driver execution rows visible even when cue summary snapshots are missing', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: 'motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79',
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-driver-only',
          rendererTarget: 'vrm',
          matchedDrivers: ['motion'],
          sources: ['timeline-projection'],
          faceSegmentMatched: false,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: false,
        },
        cue: null,
        drivers: {
          face: null,
          motion: {
            idleBase: 'breathing-idle',
            attentionMode: 'observe-first',
            actionCue: 'observe_focus',
            intensity: 0.48,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.79,
            segmentId: 'segment-driver-only',
          },
          lipsync: null,
        },
      },
    })

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-driver-only',
        value: '目标 VRM，驱动 动作，来源 timeline-projection，命中 表情未命中 / 动作命中 / 口型未命中',
        technicalValue: 'target=vrm | drivers=motion | sources=timeline-projection | matches=face:no motion:yes lipsync:no',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作命中 / 口型未命中',
        technicalValue: 'face:no motion:yes lipsync:no',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、口型 authority 漂移，当前绑定来源是 timeline-projection，实际执行落点是动作。',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '动作 observe_focus，模式 先观察，待机 breathing-idle @0.48，保持 240ms，来源 时间线投影，置信 0.79',
        technicalValue: 'motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79',
      },
    ])
  })

  it('keeps upstream cue summary rows visible even when local cue telemetry is missing', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: '上游 evidence cue',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: '上游 evidence persona',
        timingSummary: '上游 evidence timing',
        driverExecutionSummary: '上游 evidence execution',
        visemeHintsSummary: null,
      },
      authoritySummary: {
        cueId: 'segment-evidence-only',
        segmentId: 'segment-evidence-only',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: '上游驱动执行',
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-evidence-only',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: null,
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-evidence-only',
        value: '上游 authority 绑定',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '上游 authority 命中',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行。',
      },
      {
        section: 'cue',
        label: 'segment-evidence-only',
        value: '上游 evidence cue',
      },
      {
        section: 'cue',
        label: 'persona-style',
        value: '上游 evidence persona',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '上游 evidence timing',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '上游 evidence execution',
      },
    ])
  })

  it('uses authority binding segment id for viseme summary rows when only summary text survives', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        visemeHintsSummary: '上游 evidence viseme hints',
      },
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: '上游口型提示',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-viseme-evidence-only',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-viseme-evidence-only',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-viseme-evidence-only',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
      {
        section: 'viseme',
        label: 'segment-viseme-evidence-only',
        value: '上游 evidence viseme hints',
      },
    ])
  })

  it('uses lipsync driver segment id for viseme summary rows when authority binding is absent', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        visemeHintsSummary: '上游 evidence viseme hints',
      },
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: '上游口型提示',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: null,
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-lipsync-only',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'viseme',
        label: 'segment-lipsync-only',
        value: '上游 evidence viseme hints',
      },
    ])
  })

  it('uses lipsync driver segment id for cue summary rows when authority binding is absent', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: '上游 evidence cue',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: '上游 evidence persona',
        timingSummary: '上游 evidence timing',
        driverExecutionSummary: null,
        visemeHintsSummary: null,
      },
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: null,
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-cue-lipsync-only',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'cue',
        label: 'segment-cue-lipsync-only',
        value: '上游 evidence cue',
      },
      {
        section: 'cue',
        label: 'persona-style',
        value: '上游 evidence persona',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '上游 evidence timing',
      },
    ])
  })

  it('prefers snapshot-native summary rows when upstream summaries are present', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: {
        voice: '上游语音摘要',
        topVisemes: '上游主口型',
      },
      authoritySummary: {
        cueId: 'segment-summary-rows',
        segmentId: 'segment-summary-rows',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: {
        cueId: 'segment-summary-rows',
        cueText: '继续看这里。',
        cue: '上游微表情线索',
        personaStyle: '上游人设风格',
        timing: '上游时序节奏',
      },
      driverSummary: null,
      driverExecutionSummary: 'motion=上游驱动执行',
      live2dExecution: null,
      visemeHintsSummary: '上游口型提示',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-summary-rows',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-summary-rows',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'raw persona style',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: {
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
            segmentId: 'segment-summary-rows',
          },
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-summary-rows',
            visemeHints: [
              { segmentId: 'segment-summary-rows', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
            ],
          },
        },
      },
    })

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'articulation',
        label: 'voice',
        value: '上游语音摘要',
      },
      {
        section: 'articulation',
        label: 'visemes',
        value: '上游主口型',
      },
      {
        section: 'authority',
        label: 'segment-summary-rows',
        value: '上游 authority 绑定',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '上游 authority 命中',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是动作。',
      },
      {
        section: 'cue',
        label: 'segment-summary-rows',
        value: '上游微表情线索',
      },
      {
        section: 'cue',
        label: 'persona-style',
        value: '上游人设风格',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '上游时序节奏',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '动作 上游驱动执行',
        technicalValue: 'motion=上游驱动执行',
      },
      {
        section: 'viseme',
        label: 'segment-summary-rows',
        value: '上游口型提示',
      },
    ])
  })

  it('prefers an upstream authority mismatch display over locally recomputing a weaker mismatch line', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:rest:1',
        activeThreadId: 'runtime-thread-rest-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: [],
      },
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-display-first',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-display-first',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: null,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: {
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
            segmentId: 'segment-display-first',
          },
          motion: {
            idleBase: 'breathing-idle',
            attentionMode: 'observe-first',
            actionCue: 'observe_focus',
            intensity: 0.48,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.79,
            segmentId: 'segment-display-first',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-display-first',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-display-first',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。',
      },
      {
        section: 'cue',
        label: 'segment-display-first',
        value: 'focused / observe_focus，韵律 0.36，口部 0.28，头部 0.32，权威绑定，片段 segment-display-first',
        technicalValue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=authority-bound segment=segment-display-first',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '表情 320ms，动作 240ms，情绪 360ms，片段起始，软打断，保持',
        technicalValue: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '表情 attentive/focused @0.61，保持 320ms，前置 soften，后置 hold-soft，来源 韵律权威，置信 0.83 | 动作 observe_focus，模式 先观察，待机 breathing-idle @0.48，保持 240ms，来源 时间线投影，置信 0.79 | 口型 energy-phoneme-hybrid，阶段 播放中',
        technicalValue: 'face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing',
      },
    ])
  })

  it('keeps cue and viseme row labels scoped to the current playback cue when authority summary points at a different segment', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: {
        voice: '上游语音摘要',
        topVisemes: '上游主口型',
      },
      authoritySummary: {
        cueId: 'segment-authority-summary',
        segmentId: 'segment-authority-summary',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: {
        cueId: 'segment-current-playback',
        cueText: '这里才是当前播放片段。',
        cue: '当前 cue 微表情线索',
        personaStyle: '当前 cue 人设风格',
        timing: '当前 cue 时序节奏',
      },
      driverSummary: null,
      driverExecutionSummary: 'motion=上游驱动执行',
      live2dExecution: null,
      visemeHintsSummary: '当前 cue 口型提示',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-authority-summary',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'raw persona style',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-current-playback',
            visemeHints: [
              { segmentId: 'segment-current-playback', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
            ],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'articulation',
        label: 'voice',
        value: '上游语音摘要',
      },
      {
        section: 'articulation',
        label: 'visemes',
        value: '上游主口型',
      },
      {
        section: 'authority',
        label: 'segment-authority-summary',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是动作。',
      },
      {
        section: 'cue',
        label: 'segment-current-playback',
        value: '当前 cue 微表情线索',
      },
      {
        section: 'cue',
        label: 'persona-style',
        value: '当前 cue 人设风格',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '当前 cue 时序节奏',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '动作 上游驱动执行',
        technicalValue: 'motion=上游驱动执行',
      },
      {
        section: 'viseme',
        label: 'segment-current-playback',
        value: '当前 cue 口型提示',
      },
    ])
  })

  it('falls back to authority binding segment id when cue telemetry lacks its own cue id', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-cue-fallback',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: '',
          text: '这里继续看当前片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: null,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-cue-fallback',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-cue-fallback',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
      {
        section: 'cue',
        label: 'segment-cue-fallback',
        value: 'focused / observe_focus，韵律 0.36，口部 0.28，头部 0.32，权威绑定，片段 segment-cue-fallback',
        technicalValue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=authority-bound segment=segment-cue-fallback',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '表情 320ms，动作 240ms，情绪 360ms，片段起始，软打断，保持',
        technicalValue: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '口型 energy-phoneme-hybrid，阶段 播放中',
        technicalValue: 'lipsync=energy-phoneme-hybrid phase=playing',
      },
    ])
  })

  it('omits empty timing rows when cue identity survives without timing detail', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: {
        cueId: 'segment-cue-only',
        segmentId: 'segment-cue-only',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        settleSummary: null,
      },
      cueMicroSummary: {
        cueId: 'segment-cue-only',
        cueText: '这里只保留 cue 身份。',
        cue: '当前 cue 微表情线索',
        personaStyle: null,
        timing: null,
      },
      driverSummary: null,
      driverExecutionSummary: 'lipsync=energy-phoneme-hybrid phase=playing',
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-cue-only',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-cue-only',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-cue-only',
        value: '上游 authority 绑定',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '上游 authority 命中',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
      {
        section: 'cue',
        label: 'segment-cue-only',
        value: '当前 cue 微表情线索',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '口型 energy-phoneme-hybrid，阶段 播放中',
        technicalValue: 'lipsync=energy-phoneme-hybrid phase=playing',
      },
    ])
  })

  it('omits placeholder-only cue rows when only settle timing survives', () => {
    const view = buildSpeechObservabilityView({
      phase: 'settle',
      playbackPhase: 'settle',
      speechEnergy: 0.18,
      prosodyIntensity: 0.12,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 240,
        plannedDurationMs: 240,
        driftMs: 0,
        settleMs: 240,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-settle-only',
          rendererTarget: 'vrm',
          matchedDrivers: [],
          sources: [],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: false,
        },
        cue: {
          id: 'segment-settle-only',
          text: '这里只剩 settle。',
          prosodyWeight: null,
          mouthWeight: null,
          headWeight: null,
          personaStyleSummary: null,
          facialHoldMs: null,
          actionHoldMs: null,
          emotionHoldMs: null,
          facialCue: null,
          actionCue: null,
          actionWindow: null,
          interruptMode: null,
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: null,
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-settle-only',
        value: '目标 VRM，驱动 无，来源 无，命中 表情未命中 / 动作未命中 / 口型未命中',
        technicalValue: 'target=vrm | drivers=n/a | sources=n/a | matches=face:no motion:no lipsync:no',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型未命中',
        technicalValue: 'face:no motion:no lipsync:no',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作、口型 authority 漂移，当前绑定来源是 无来源，实际执行落点是无执行。',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '表情 n/a，动作 n/a，情绪 n/a，n/a，n/a，保持',
        technicalValue: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold',
      },
    ])
  })

  it('omits fallback cue rows when upstream cue summary is placeholder-only', () => {
    const view = buildSpeechObservabilityView({
      phase: 'settle',
      playbackPhase: 'settle',
      speechEnergy: 0.18,
      prosodyIntensity: 0.12,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: 'n/a / n/a | prosody=n/a mouth=n/a head=n/a',
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold',
        driverExecutionSummary: null,
        visemeHintsSummary: null,
      },
      authoritySummary: {
        cueId: 'segment-fallback-placeholder',
        segmentId: 'segment-fallback-placeholder',
        rendererTarget: 'vrm',
        matchedDrivers: [],
        matchedSources: [],
        bindingSummary: 'target=vrm | drivers=n/a | sources=n/a | matches=face:no motion:no lipsync:no',
        matchSummary: 'face:no motion:no lipsync:no',
        settleSummary: null,
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 240,
        plannedDurationMs: 240,
        driftMs: 0,
        settleMs: 240,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-fallback-placeholder',
          rendererTarget: 'vrm',
          matchedDrivers: [],
          sources: [],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: false,
        },
        cue: null,
        drivers: null,
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-fallback-placeholder',
        value: '目标 VRM，驱动 无，来源 无，命中 表情未命中 / 动作未命中 / 口型未命中',
        technicalValue: 'target=vrm | drivers=n/a | sources=n/a | matches=face:no motion:no lipsync:no',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型未命中',
        technicalValue: 'face:no motion:no lipsync:no',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作、口型 authority 漂移，当前绑定来源是 无来源，实际执行落点是无执行。',
      },
      {
        section: 'cue',
        label: 'timing',
        value: '表情 n/a，动作 n/a，情绪 n/a，n/a，n/a，保持',
        technicalValue: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold',
      },
    ])
  })

  it('omits placeholder-only viseme rows when lipsync telemetry carries no usable hint payload', () => {
    const view = buildSpeechObservabilityView({
      phase: 'settle',
      playbackPhase: 'settle',
      speechEnergy: 0.18,
      prosodyIntensity: 0.12,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: {
        cueId: 'segment-viseme-placeholder',
        segmentId: 'segment-viseme-placeholder',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        matchSummary: 'face:no motion:no lipsync:yes',
        settleSummary: null,
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: 'lipsync=energy-phoneme-hybrid phase=settle',
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 240,
        plannedDurationMs: 240,
        driftMs: 0,
        settleMs: 240,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-viseme-placeholder',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'settle',
            segmentId: 'segment-viseme-placeholder',
            visemeHints: [
              {
                segmentId: 'segment-viseme-placeholder',
                viseme: null,
                weight: null,
                source: null,
                confidence: null,
              },
            ],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-viseme-placeholder',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
      {
        section: 'cue',
        label: 'driver-execution',
        value: '口型 energy-phoneme-hybrid，阶段 settle',
        technicalValue: 'lipsync=energy-phoneme-hybrid phase=settle',
      },
    ])
  })

  it('omits placeholder-only driver execution rows when upstream execution summary is an empty shell', () => {
    const view = buildSpeechObservabilityView({
      phase: 'settle',
      playbackPhase: 'settle',
      speechEnergy: 0.18,
      prosodyIntensity: 0.12,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: 'lipsync=n/a phase=n/a',
        visemeHintsSummary: null,
      },
      authoritySummary: {
        cueId: 'segment-driver-placeholder',
        segmentId: 'segment-driver-placeholder',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        matchSummary: 'face:no motion:no lipsync:yes',
        settleSummary: null,
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: 'lipsync=n/a phase=n/a',
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 240,
        plannedDurationMs: 240,
        driftMs: 0,
        settleMs: 240,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-driver-placeholder',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'settle',
            segmentId: 'segment-driver-placeholder',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-driver-placeholder',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
    ])
  })

  it('omits placeholder-only persona-style rows when upstream persona summary is an empty shell', () => {
    const view = buildSpeechObservabilityView({
      phase: 'settle',
      playbackPhase: 'settle',
      speechEnergy: 0.18,
      prosodyIntensity: 0.12,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: {
        voiceSummary: null,
        authorityMatchSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        personaStyleSummary: 'n/a | prosody=n/a beat=n/a mouth=n/a head=n/a',
        timingSummary: null,
        driverExecutionSummary: null,
        visemeHintsSummary: null,
      },
      authoritySummary: {
        cueId: 'segment-persona-placeholder',
        segmentId: 'segment-persona-placeholder',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        matchSummary: 'face:no motion:no lipsync:yes',
        settleSummary: null,
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 240,
        plannedDurationMs: 240,
        driftMs: 0,
        settleMs: 240,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-persona-placeholder',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'settle',
            segmentId: 'segment-persona-placeholder',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(buildSpeechObservabilityRows(view)).toEqual([
      {
        section: 'authority',
        label: 'segment-persona-placeholder',
        value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-match',
        value: '表情未命中 / 动作未命中 / 口型命中',
        technicalValue: 'face:no motion:no lipsync:yes',
      },
      {
        section: 'authority',
        label: 'authority-mismatch',
        value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型。',
      },
    ])
  })
})
