import { describe, expect, it } from 'vitest'

import {
  buildSelfEvolutionDiagnosticSummaryEntries,
  buildSelfEvolutionDiagnosticSummaryLines,
} from './performance-visualizer-self-evolution-diagnostic-summary'

describe('performance visualizer self evolution diagnostic summary', () => {
  it('builds concise continuity-first summary entries for grounded self-evolution evidence', () => {
    const entries = buildSelfEvolutionDiagnosticSummaryEntries({
      proactiveDecisionConsumptionSummary: {
        status: 'grounded',
        decisionMode: 'birth-anchored-restraint',
        dominantDrift: null,
        lines: [
          'decision-consumption: birth observe-first restraint became persona hover and runtime hold',
          'manifestation-consumption: silent-observe | attentive',
          'counterfactual-consumption: selected=hover | tradeoff=presence-before-commentary',
          'rejected-alternative: speak stayed rejected because Current persona bias is observe-first, so speak breaks the preferred restraint posture.',
          'trust-meaning: trust deepens through steadiness before closeness',
        ],
      },
      identityDriftGovernanceSummary: {
        status: 'grounded',
        governanceMode: 'bounded-growth',
        dominantDrift: null,
        lines: [
          'governance: bounded growth is preserving identity',
          'identity-boundary: trust can deepen without violating observe-first room',
          'identity-anchors: host-steadiness | observe-first room',
          'trust-meaning: trust deepens through steadiness before closeness',
          'autobiographical-stability: 0.92 | trajectory=presence restraint',
        ],
      } as any,
      personaBiasProvenance: {
        status: 'grounded',
        relationshipPosture: 'observer',
        initiativeStyle: 'observant',
        silenceReconnect: 'hold',
        comfortStyle: 'quiet-presence',
        preferredProactiveStyle: 'silent-observe',
        openingGuidance: 'Open by observing first and keep the approach lighter.',
        manifestationCadenceSummary: 'persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveActionChain: {
        status: 'grounded',
        personaPreferredAction: 'hover',
        runtimeSelectedAction: 'hold',
        runtimeShouldSpeak: false,
        openingGuidance: 'Open by observing first and keep the approach lighter.',
        openingGuidanceHoldReason: 'opening-guidance:observe-first',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveManifestationChain: {
        status: 'grounded',
        personaPreferredStyle: 'silent-observe',
        personaPreferredPresence: 'attentive',
        counterfactualStyle: 'silent-observe',
        counterfactualPresence: 'attentive',
        actionEcologyStyle: 'silent-observe',
        actionEcologyPresence: 'attentive',
        initiativePreferredStyle: 'silent-observe',
        initiativePreferredPresence: 'attentive',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      privateThoughtGovernanceChain: {
        status: 'grounded',
        privateThoughtStance: 'accompany',
        privateThoughtShouldSpeak: false,
        privateThoughtStyle: 'silent-observe',
        privateThoughtPresence: 'attentive',
        privateThoughtText: '我先不挤进去，只把这条线轻轻挂着。',
        visibleReplyRealizationReason: null,
        visibleReplyBlockedReason: 'opening-guidance:observe-first',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      residentPerformanceProjection: {
        status: 'grounded',
        residentSource: 'main-runtime',
        residentEmbodiedPresence: 'attentive',
        residentStance: 'accompany',
        residentEmotionalTension: 'soft-covision',
        residentBaseEmotion: 'thinking',
        residentDelivery: 'gentle',
        residentEmphasis: 1,
        residentReasonTags: [],
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      rendererAuthorityProjection: {
        status: 'grounded',
        rendererTarget: 'vrm',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        authorityMismatchSummary: null,
        authorityMismatchDisplay: null,
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      runtimeContinuityProjection: {
        status: 'grounded',
        runtimeChannel: 'active-dialogue',
        runtimeSummary: 'runtime alignment held',
        activeThreadId: 'runtime-thread-rest-1',
        activeThreadTitle: 'late-night care',
        runtimeScenario: 'coding',
        runtimeScene: 'coding',
        transitionFromWatchMode: 'symbiotic-vision',
        transitionToWatchMode: 'recovering',
        transitionFromScenario: 'chat',
        transitionReason: 'host fatigue detected during late-night care',
        governorDrive: 'protect',
        governorIntentionId: 'governor-intention-rest-1',
        focusBeliefId: 'belief-rest-1',
        rationaleTags: ['recovering', 'late-night-fatigue'],
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      baselineAnchorAuditSummary: {
        status: 'grounded',
        lines: [
          'anchor: candidate-active is still the adopted default continuity anchor',
          'trace: snapshot=180 | trace=trace-active | owner=显形权威',
          'prosody-authority: 韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
        ],
      },
    })

    expect(entries).toEqual([
      {
        key: 'status',
        label: '闭环状态',
        value: '闭环稳定 | 漂移=无',
        technicalValue: 'grounded | drift=none',
      },
      {
        key: 'persona',
        label: '人格基线',
        value: '观察者 | 善于观察 | 静默观察',
        technicalValue: 'observer | observant | silent-observe',
      },
      { key: 'manifestation-cadence', label: '显形节奏', value: 'persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.' },
      {
        key: 'manifestation-bridge',
        label: '显形链路',
        value: '人格 静默观察/专注 -> 思绪 静默观察/专注 -> 驻留 专注/陪伴',
        technicalValue: 'persona silent-observe/attentive -> thought silent-observe/attentive -> resident attentive/accompany',
      },
      {
        key: 'proactive',
        label: '主动落点',
        value: '保持 | shouldSpeak=false | 开场指引：先观察 | 初始锚定克制',
        technicalValue: 'hold | shouldSpeak=false | opening-guidance:observe-first | birth-anchored-restraint',
      },
      {
        key: 'resident',
        label: '驻留投影',
        value: '专注陪伴 | 思考/温和',
        technicalValue: 'attentive/accompany | thinking/gentle',
      },
      {
        key: 'renderer',
        label: '显形权威',
        value: 'VRM | 表情命中/动作命中/口型命中 | 韵律权威 energy-phoneme-hybrid | 韵律权威',
        technicalValue: 'vrm | face:yes motion:yes lipsync:yes | mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
      },
      {
        key: 'continuity',
        label: '连续线程',
        value: 'runtime-thread-rest-1 | 主动对话 | 编码中 | 有界成长',
        technicalValue: 'runtime-thread-rest-1 | active-dialogue | coding | bounded-growth',
      },
      {
        key: 'adopted-anchor',
        label: '已采纳锚点',
        value: 'candidate-active | snapshot=180 | owner=显形权威 | 韵律权威已回绑',
        technicalValue: 'candidate-active | snapshot=180 | trace=trace-active | owner=显形权威 | prosody-authority: 韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
      },
    ])

    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toEqual([
      'status: 闭环稳定 | 漂移=无',
      'persona: 观察者 | 善于观察 | 静默观察',
      'manifestation-cadence: persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.',
      'manifestation-bridge: 人格 静默观察/专注 -> 思绪 静默观察/专注 -> 驻留 专注/陪伴',
      'proactive: 保持 | shouldSpeak=false | 开场指引：先观察 | 初始锚定克制',
      'resident: 专注陪伴 | 思考/温和',
      'renderer: VRM | 表情命中/动作命中/口型命中 | 韵律权威 energy-phoneme-hybrid | 韵律权威',
      'continuity: runtime-thread-rest-1 | 主动对话 | 编码中 | 有界成长',
      'adopted-anchor: candidate-active | snapshot=180 | owner=显形权威 | 韵律权威已回绑',
    ])
  })

  it('surfaces remembered-familiarity same-her continuity in the top-level diagnostic summary when companionship stays memory-first', () => {
    const entries = buildSelfEvolutionDiagnosticSummaryEntries({
      proactiveDecisionConsumptionSummary: {
        status: 'grounded',
        decisionMode: 'birth-anchored-restraint',
        dominantDrift: null,
        lines: [
          'decision-consumption: birth observe-first restraint became persona hover and runtime hold',
          'memory-familiarity-restraint: remembered familiarity stayed memory-first before visible closeness widened',
        ],
      },
      candidateTrajectorySummary: {
        status: 'grounded',
        trajectoryLabel: 'observe-first',
        dominantDrift: null,
        lines: [
          'remembered-familiarity-trajectory: familiarity is staying memory-first while the same-her room holds',
        ],
      },
      identityDriftGovernanceSummary: {
        status: 'grounded',
        governanceMode: 'bounded-growth',
        dominantDrift: null,
        lines: [
          'remembered-familiarity-governance: familiarity stayed in memory first, so growth did not widen visible closeness past the same-her room',
        ],
      } as any,
      personaBiasProvenance: {
        status: 'grounded',
        relationshipPosture: 'observer',
        initiativeStyle: 'observant',
        silenceReconnect: 'hold',
        comfortStyle: 'quiet-presence',
        preferredProactiveStyle: 'silent-observe',
        openingGuidance: 'Open by observing first and keep the approach lighter.',
        manifestationCadenceSummary: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveActionChain: {
        status: 'grounded',
        personaPreferredAction: 'hover',
        runtimeSelectedAction: 'hold',
        runtimeShouldSpeak: false,
        openingGuidance: 'Open by observing first and keep the approach lighter.',
        openingGuidanceHoldReason: 'opening-guidance:observe-first',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveManifestationChain: {
        status: 'grounded',
        personaPreferredStyle: 'silent-observe',
        personaPreferredPresence: 'attentive',
        counterfactualStyle: 'silent-observe',
        counterfactualPresence: 'attentive',
        actionEcologyStyle: 'silent-observe',
        actionEcologyPresence: 'attentive',
        initiativePreferredStyle: 'silent-observe',
        initiativePreferredPresence: 'attentive',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      privateThoughtGovernanceChain: {
        status: 'grounded',
        privateThoughtStance: 'accompany',
        privateThoughtShouldSpeak: false,
        privateThoughtStyle: 'silent-observe',
        privateThoughtPresence: 'attentive',
        privateThoughtText: '我先不挤进去，只把这条线轻轻挂着。',
        visibleReplyRealizationReason: null,
        visibleReplyBlockedReason: 'opening-guidance:observe-first',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      residentPerformanceProjection: {
        status: 'grounded',
        residentSource: 'main-runtime',
        residentEmbodiedPresence: 'attentive',
        residentStance: 'accompany',
        residentEmotionalTension: 'soft-covision',
        residentBaseEmotion: 'thinking',
        residentDelivery: 'gentle',
        residentEmphasis: 1,
        residentReasonTags: [],
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      rendererAuthorityProjection: {
        status: 'grounded',
        rendererTarget: 'vrm',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        authorityMismatchSummary: null,
        authorityMismatchDisplay: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      runtimeContinuityProjection: {
        status: 'grounded',
        runtimeChannel: 'active-dialogue',
        runtimeSummary: 'runtime alignment held',
        activeThreadId: 'runtime-thread-rest-1',
        activeThreadTitle: 'late-night care',
        runtimeScenario: 'coding',
        runtimeScene: 'coding',
        transitionFromWatchMode: 'symbiotic-vision',
        transitionToWatchMode: 'recovering',
        transitionFromScenario: 'chat',
        transitionReason: 'host fatigue detected during late-night care',
        governorDrive: 'protect',
        governorIntentionId: 'governor-intention-rest-1',
        focusBeliefId: 'belief-rest-1',
        rationaleTags: ['recovering', 'late-night-fatigue'],
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
    })

    expect(entries).toContainEqual({
      key: 'continuity',
      label: '连续线程',
      value: 'runtime-thread-rest-1 | 主动对话 | 编码中 | 有界成长 | 熟悉感记忆先行',
      technicalValue: 'runtime-thread-rest-1 | active-dialogue | coding | bounded-growth | remembered-familiarity-memory-first',
    })

    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toContain(
      'continuity: runtime-thread-rest-1 | 主动对话 | 编码中 | 有界成长 | 熟悉感记忆先行',
    )
  })

  it('prioritizes renderer drift as the dominant self-evolution break when continuity is otherwise intact', () => {
    const entries = buildSelfEvolutionDiagnosticSummaryEntries({
      proactiveDecisionConsumptionSummary: {
        status: 'partial',
        decisionMode: 'restraint-overridden',
        dominantDrift: 'runtime-selected-action:speak',
        lines: [
          'decision-consumption: runtime speak overrode birth observe-first restraint',
          'manifestation-drift: silent-observe -> light-nudge | attentive',
          'counterfactual-consumption: selected=speak | tradeoff=comfort-over-restraint',
          'rejected-identity-fit: hover preserved more identity but lost the final decision',
          'dominant-drift: runtime-selected-action:speak',
          'trust-meaning: trust now means speaking before the room is ready',
        ],
      },
      identityDriftGovernanceSummary: {
        status: 'partial',
        governanceMode: 'boundary-violation',
        dominantDrift: 'runtime-selected-action:speak',
        lines: [
          'governance: growth crossed persona boundary',
          'boundary-violation: runtime speech outran birth restraint',
          'identity-anchors: host-steadiness | observe-first room',
          'anti-persona-constraints: no pushy intimacy | do not force closeness',
          'trust-meaning: trust now means speaking before the room is ready',
          'dominant-drift: runtime-selected-action:speak',
        ],
      } as any,
      personaBiasProvenance: {
        status: 'grounded',
        relationshipPosture: 'observer',
        initiativeStyle: 'observant',
        silenceReconnect: 'hold',
        comfortStyle: 'quiet-presence',
        preferredProactiveStyle: 'silent-observe',
        openingGuidance: null,
        manifestationCadenceSummary: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveActionChain: {
        status: 'grounded',
        personaPreferredAction: 'hover',
        runtimeSelectedAction: 'hold',
        runtimeShouldSpeak: false,
        openingGuidance: null,
        openingGuidanceHoldReason: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveManifestationChain: {
        status: 'partial',
        personaPreferredStyle: 'silent-observe',
        personaPreferredPresence: 'attentive',
        counterfactualStyle: 'light-nudge',
        counterfactualPresence: 'attentive',
        actionEcologyStyle: 'light-nudge',
        actionEcologyPresence: 'attentive',
        initiativePreferredStyle: 'light-nudge',
        initiativePreferredPresence: 'attentive',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: ['initiative-preferred-style:light-nudge'],
        reasons: [],
      },
      privateThoughtGovernanceChain: {
        status: 'partial',
        privateThoughtStance: 'accompany',
        privateThoughtShouldSpeak: false,
        privateThoughtStyle: 'light-nudge',
        privateThoughtPresence: 'attentive',
        privateThoughtText: '要不要我轻一点提醒你一下？',
        visibleReplyRealizationReason: 'proactive-opening-guidance-violation:callback-bounded',
        visibleReplyBlockedReason: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: ['private-thought-style:light-nudge'],
        reasons: [],
      },
      residentPerformanceProjection: {
        status: 'grounded',
        residentSource: 'main-runtime',
        residentEmbodiedPresence: 'attentive',
        residentStance: 'accompany',
        residentEmotionalTension: 'soft-covision',
        residentBaseEmotion: 'thinking',
        residentDelivery: 'gentle',
        residentEmphasis: 1,
        residentReasonTags: [],
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      rendererAuthorityProjection: {
        status: 'partial',
        rendererTarget: 'live2d',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        authorityMismatchSummary: 'lipsync mismatch',
        authorityMismatchDisplay: '口型 authority 漂移，当前绑定来源仍然正确，但落点已经不同步。',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-live2d-1',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [
          'renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        ],
        reasons: [
          'Renderer drift still shows resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority, so the visible face is diverging after mind-to-render projection rather than before it.',
        ],
      },
      runtimeContinuityProjection: {
        status: 'partial',
        runtimeChannel: 'active-dialogue',
        runtimeSummary: 'runtime alignment held',
        activeThreadId: 'runtime-thread-rest-1',
        activeThreadTitle: 'late-night care',
        runtimeScenario: 'coding',
        runtimeScene: 'coding',
        transitionFromWatchMode: null,
        transitionToWatchMode: null,
        transitionFromScenario: null,
        transitionReason: null,
        governorDrive: 'protect',
        governorIntentionId: 'governor-intention-rest-1',
        focusBeliefId: 'belief-rest-1',
        rationaleTags: ['recovering'],
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [
          'renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        ],
        reasons: [
          'Renderer continuity still carries resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority, so the life thread can explain the visible divergence as a post-projection renderer event instead of a broken resident mind state.',
        ],
      },
    })

    expect(entries).toEqual([
      {
        key: 'status',
        label: '闭环状态',
        value: '部分闭环 | 漂移=显形',
        technicalValue: 'partial | drift=renderer',
      },
      {
        key: 'persona',
        label: '人格基线',
        value: '观察者 | 善于观察 | 静默观察',
        technicalValue: 'observer | observant | silent-observe',
      },
      {
        key: 'manifestation-bridge',
        label: '显形链路',
        value: '人格 静默观察/专注 -> 思绪 轻提醒/专注 -> 驻留 专注/陪伴',
        technicalValue: 'persona silent-observe/attentive -> thought light-nudge/attentive -> resident attentive/accompany',
      },
      { key: 'drift-start', label: '起漂层', value: 'persona | initiative-preferred-style:light-nudge' },
      {
        key: 'repair-owner',
        label: '修复归属',
        value: 'persona | 自我演化',
        technicalValue: 'persona | evolution',
      },
      {
        key: 'first-check',
        label: '首查点',
        value: 'persona | 自我演化内核 -> 主动学习策略 -> 显形/行动生态/人格偏置',
        technicalValue: 'persona | self-evolution kernel -> active learning strategy -> manifestation/action-ecology/persona-bias',
      },
      {
        key: 'repair-path',
        label: '修复路径',
        value: '人格漂移 initiative-preferred-style:light-nudge -> 思绪轨迹 proactive-opening-guidance-violation:callback-bounded -> 连续性锚点 governor-intention-rest-1',
        technicalValue: 'persona drift initiative-preferred-style:light-nudge -> thought trace proactive-opening-guidance-violation:callback-bounded -> continuity anchor governor-intention-rest-1',
      },
      {
        key: 'proactive',
        label: '主动落点',
        value: '保持 | shouldSpeak=false | 克制被覆盖',
        technicalValue: 'hold | shouldSpeak=false | restraint-overridden',
      },
      {
        key: 'resident',
        label: '驻留投影',
        value: '专注陪伴 | 思考/温和',
        technicalValue: 'attentive/accompany | thinking/gentle',
      },
      {
        key: 'renderer',
        label: '显形权威',
        value: 'Live2D | 表情命中/动作命中/口型未命中 | 韵律权威 energy-phoneme-hybrid | 韵律权威',
        technicalValue: 'live2d | face:yes motion:yes lipsync:no | mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-live2d-1',
      },
      {
        key: 'continuity',
        label: '连续线程',
        value: 'runtime-thread-rest-1 | 主动对话 | 编码中 | 边界越线',
        technicalValue: 'runtime-thread-rest-1 | active-dialogue | coding | boundary-violation',
      },
      {
        key: 'dominant-drift',
        label: '主漂移',
        value: '显形漂移：resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        technicalValue: 'renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      },
    ])

    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toEqual([
      'status: 部分闭环 | 漂移=显形',
      'persona: 观察者 | 善于观察 | 静默观察',
      'manifestation-bridge: 人格 静默观察/专注 -> 思绪 轻提醒/专注 -> 驻留 专注/陪伴',
      'drift-start: persona | initiative-preferred-style:light-nudge',
      'repair-owner: persona | 自我演化',
      'first-check: persona | 自我演化内核 -> 主动学习策略 -> 显形/行动生态/人格偏置',
      'repair-path: 人格漂移 initiative-preferred-style:light-nudge -> 思绪轨迹 proactive-opening-guidance-violation:callback-bounded -> 连续性锚点 governor-intention-rest-1',
      'proactive: 保持 | shouldSpeak=false | 克制被覆盖',
      'resident: 专注陪伴 | 思考/温和',
      'renderer: Live2D | 表情命中/动作命中/口型未命中 | 韵律权威 energy-phoneme-hybrid | 韵律权威',
      'continuity: runtime-thread-rest-1 | 主动对话 | 编码中 | 边界越线',
      'dominant-drift: 显形漂移：resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
    ])
  })

  it('labels renderer as the drift start when upstream manifestation layers stay grounded', () => {
    const entries = buildSelfEvolutionDiagnosticSummaryEntries({
      personaBiasProvenance: {
        status: 'grounded',
        relationshipPosture: 'observer',
        initiativeStyle: 'observant',
        silenceReconnect: 'hold',
        comfortStyle: 'quiet-presence',
        preferredProactiveStyle: 'silent-observe',
        openingGuidance: null,
        manifestationCadenceSummary: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveActionChain: {
        status: 'grounded',
        personaPreferredAction: 'hover',
        runtimeSelectedAction: 'hold',
        runtimeShouldSpeak: false,
        openingGuidance: null,
        openingGuidanceHoldReason: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      proactiveManifestationChain: {
        status: 'grounded',
        personaPreferredStyle: 'silent-observe',
        personaPreferredPresence: 'attentive',
        counterfactualStyle: 'silent-observe',
        counterfactualPresence: 'attentive',
        actionEcologyStyle: 'silent-observe',
        actionEcologyPresence: 'attentive',
        initiativePreferredStyle: 'silent-observe',
        initiativePreferredPresence: 'attentive',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      privateThoughtGovernanceChain: {
        status: 'grounded',
        privateThoughtStance: 'accompany',
        privateThoughtShouldSpeak: false,
        privateThoughtStyle: 'silent-observe',
        privateThoughtPresence: 'attentive',
        privateThoughtText: '我先不挤进去，只把这条线轻轻挂着。',
        visibleReplyRealizationReason: null,
        visibleReplyBlockedReason: null,
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      residentPerformanceProjection: {
        status: 'grounded',
        residentSource: 'main-runtime',
        residentEmbodiedPresence: 'attentive',
        residentStance: 'accompany',
        residentEmotionalTension: 'soft-covision',
        residentBaseEmotion: 'thinking',
        residentDelivery: 'gentle',
        residentEmphasis: 1,
        residentReasonTags: [],
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      rendererAuthorityProjection: {
        status: 'partial',
        rendererTarget: 'live2d',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'thinking',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        authorityMismatchSummary: 'lipsync mismatch',
        authorityMismatchDisplay: '口型 authority 漂移，当前绑定来源仍然正确，但落点已经不同步。',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: ['renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority'],
        reasons: [],
      },
      runtimeContinuityProjection: {
        status: 'partial',
        runtimeChannel: 'active-dialogue',
        runtimeSummary: 'runtime alignment held',
        activeThreadId: 'runtime-thread-rest-1',
        activeThreadTitle: 'late-night care',
        runtimeScenario: 'coding',
        runtimeScene: 'coding',
        transitionFromWatchMode: null,
        transitionToWatchMode: null,
        transitionFromScenario: null,
        transitionReason: null,
        governorDrive: 'protect',
        governorIntentionId: 'governor-intention-rest-1',
        focusBeliefId: 'belief-rest-1',
        rationaleTags: ['recovering'],
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry',
        traceEmbodimentDisplaySummary: '关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达）',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: ['renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority'],
        reasons: [],
      },
    })

    expect(entries).toEqual(expect.arrayContaining([
      {
        key: 'status',
        label: '闭环状态',
        value: '部分闭环 | 漂移=显形',
        technicalValue: 'partial | drift=renderer',
      },
      {
        key: 'manifestation-bridge',
        label: '显形链路',
        value: '人格 静默观察/专注 -> 思绪 静默观察/专注 -> 驻留 专注/陪伴',
        technicalValue: 'persona silent-observe/attentive -> thought silent-observe/attentive -> resident attentive/accompany',
      },
      {
        key: 'drift-start',
        label: '起漂层',
        value: 'renderer | 显形漂移：resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        technicalValue: 'renderer | renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      },
      {
        key: 'repair-owner',
        label: '修复归属',
        value: 'renderer | 显形权威',
        technicalValue: 'renderer | renderer authority',
      },
      {
        key: 'first-check',
        label: '首查点',
        value: 'renderer | 显形权威绑定 -> 回放片段 -> 驱动执行',
        technicalValue: 'renderer | renderer authority binding -> playback cues -> driver execution',
      },
      {
        key: 'repair-path',
        label: '修复路径',
        value: '显形漂移 renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority -> 权威轨迹 口型 authority 漂移，当前绑定来源仍然正确，但落点已经不同步。 -> 连续性锚点 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达）',
        technicalValue: 'renderer drift renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority -> authority trace 口型 authority 漂移，当前绑定来源仍然正确，但落点已经不同步。 -> continuity anchor 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达）',
      },
      {
        key: 'renderer',
        label: '显形权威',
        value: 'Live2D | 表情命中/动作命中/口型未命中',
        technicalValue: 'live2d | face:yes motion:yes lipsync:no',
      },
      {
        key: 'dominant-drift',
        label: '主漂移',
        value: '显形漂移：resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        technicalValue: 'renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      },
    ]))

    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toContain(
      'drift-start: renderer | 显形漂移：resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
    )
    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toContain(
      'repair-owner: renderer | 显形权威',
    )
    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toContain(
      'first-check: renderer | 显形权威绑定 -> 回放片段 -> 驱动执行',
    )
    expect(buildSelfEvolutionDiagnosticSummaryLines(entries)).toContain(
      'repair-path: 显形漂移 renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority -> 权威轨迹 口型 authority 漂移，当前绑定来源仍然正确，但落点已经不同步。 -> 连续性锚点 关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达）',
    )
  })
})
