import { describe, expect, it } from 'vitest'

import {
  buildSpeechObservabilityView,
  formatAuthorityBindingSummary,
  formatAuthorityMatchSummary,
} from './performance-visualizer-speech-observability'

describe('performance visualizer speech observability', () => {
  it('surfaces chinese-first articulation, viseme hints, and cue micro-expression detail', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0.18,
          O: 0.08,
          U: 0.12,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-zh-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-zh-1',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08 provenance=authority-bound segment=segment-zh-1',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        prosodyAuthority: {
          segmentId: 'segment-zh-1',
          provenance: 'authority-bound',
          source: 'prosody-authority',
          mode: 'energy-phoneme-hybrid',
          cueProsodyWeight: 0.35,
          cueMouthWeight: 0.35,
          cueHeadWeight: 0.32,
          visemePeakWeight: 0.75,
        },
        drivers: {
          face: {
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
            segmentId: 'segment-zh-1',
          },
          motion: {
            idleBase: 'breathing-idle',
            attentionMode: 'observe-first',
            actionCue: 'observe_focus',
            intensity: 0.48,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.79,
            segmentId: 'segment-zh-1',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-zh-1',
            visemeHints: [
              { segmentId: 'segment-zh-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-zh-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
            ],
          },
        },
      },
    })

    expect(view.articulation?.voiceLanguage).toBe('zh-CN')
    expect(view.authorityBinding).toEqual({
      segmentId: 'segment-zh-1',
      rendererTarget: 'vrm',
      matchedDrivers: ['lipsync'],
      matchedSources: ['prosody-authority'],
      faceSegmentMatched: false,
      motionSegmentMatched: false,
      lipsyncSegmentMatched: true,
    })
    expect(view.articulation?.topVisemes).toEqual([
      { viseme: 'A', weight: 0.66 },
      { viseme: 'closed', weight: 0.41 },
      { viseme: 'E', weight: 0.24 },
    ])
    expect(view.articulationSummary).toEqual({
      voice: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-zh-1 | source=prosody-authority',
      topVisemes: 'A:0.66, closed:0.41, E:0.24',
    })
    expect(view.cueMicro).toEqual({
      cueId: 'segment-zh-1',
      cueText: '继续看这里。',
      prosodyWeight: 0.36,
      mouthWeight: 0.28,
      headWeight: 0.32,
      facialHoldMs: 320,
      actionHoldMs: 240,
      emotionHoldMs: 360,
      facialCue: 'focused',
      actionCue: 'observe_focus',
      actionWindow: 'segment-start',
      interruptMode: 'soft-interrupt',
      settleMode: 'hold',
      personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08 provenance=authority-bound segment=segment-zh-1',
    })
    expect(view.cueMicroSummary).toEqual({
      cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=authority-bound segment=segment-zh-1',
      personaStyle: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08 provenance=authority-bound segment=segment-zh-1',
      timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
    })
    expect(view.speechEvidence?.prosodyAuthoritySummary).toBe(
      'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
    )
    expect(view.driverExecution).toEqual({
      face: {
        segmentId: 'segment-zh-1',
        emotion: 'attentive',
        facialCue: 'focused',
        intensity: 0.61,
        holdMs: 320,
        source: 'prosody-authority',
        confidence: 0.83,
        preUtteranceCue: 'soften',
        postUtteranceCue: 'hold-soft',
      },
      motion: {
        segmentId: 'segment-zh-1',
        idleBase: 'breathing-idle',
        attentionMode: 'observe-first',
        actionCue: 'observe_focus',
        intensity: 0.48,
        holdMs: 240,
        source: 'timeline-projection',
        confidence: 0.79,
      },
      lipsync: {
        segmentId: 'segment-zh-1',
        mode: 'energy-phoneme-hybrid',
        playbackPhase: 'playing',
      },
    })
    expect(view.visemeHints).toEqual([
      { segmentId: 'segment-zh-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
      { segmentId: 'segment-zh-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
    ])
    expect(view.visemeHintsSummary).toBe('I:0.35@0.94 src=prosody-authority segment=segment-zh-1 | closed:0.75@0.89 src=prosody-authority segment=segment-zh-1')
    expect(formatAuthorityMatchSummary(view.authorityBinding)).toBe('face:no motion:no lipsync:yes')
    expect(formatAuthorityBindingSummary(view.authorityBinding)).toBe('target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes')
    expect(view.driverExecutionSummary).toBe('face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing')
    expect(view.rendererAlignmentSummary).toEqual({
      live2d: null,
      vrm: null,
    })
  })

  it('deduplicates seeded authority sources inside speech observability authority binding', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-dedupe-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          sources: ['prosody-authority', 'timeline-projection', 'prosody-authority'],
          faceSegmentMatched: true,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: null,
      },
    } as any)

    expect(view.authorityBinding).toEqual({
      segmentId: 'segment-dedupe-1',
      rendererTarget: 'vrm',
      matchedDrivers: ['face', 'motion', 'lipsync'],
      matchedSources: ['prosody-authority', 'timeline-projection'],
      faceSegmentMatched: true,
      motionSegmentMatched: true,
      lipsyncSegmentMatched: true,
    })
    expect(formatAuthorityBindingSummary(view.authorityBinding)).toBe('target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:yes')
  })

  it('prefers snapshot-native summaries over locally recomputed speech summary strings', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0,
          O: 0,
          U: 0,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: {
        voice: '上游语音摘要',
        topVisemes: '上游主口型',
      },
      speechEvidence: {
        voiceSummary: '上游 evidence voice',
        authorityMatchSummary: '上游 evidence match',
        topVisemeSummary: '上游 evidence visemes',
        cueSummary: '上游 evidence cue',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: '上游 evidence persona',
        timingSummary: '上游 evidence timing',
        driverExecutionSummary: '上游 evidence execution',
        visemeHintsSummary: '上游 evidence hints',
      },
      authoritySummary: {
        cueId: 'segment-summary-1',
        segmentId: 'segment-summary-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段。',
        authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: {
        cueId: 'segment-summary-1',
        cueText: '继续看这里。',
        cue: '上游微表情线索',
        personaStyle: '上游人设风格',
        timing: '上游时序节奏',
      },
      driverSummary: null,
      driverExecutionSummary: '上游驱动执行',
      live2dExecution: null,
      visemeHintsSummary: '上游口型提示',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-summary-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-summary-1',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'raw persona style',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        prosodyAuthority: {
          segmentId: 'segment-zh-1',
          provenance: 'authority-bound',
          source: 'prosody-authority',
          mode: 'energy-phoneme-hybrid',
          cueProsodyWeight: 0.35,
          cueMouthWeight: 0.35,
          cueHeadWeight: 0.32,
          visemePeakWeight: 0.75,
        },
        drivers: {
          face: {
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
            segmentId: 'segment-summary-1',
          },
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-summary-1',
            visemeHints: [
              { segmentId: 'segment-summary-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
            ],
          },
        },
      },
    })

    expect(view.articulationSummary).toEqual({
      voice: '上游 evidence voice',
      topVisemes: '上游 evidence visemes',
    })
    expect(view.authoritySummary).toEqual({
      cueId: 'segment-summary-1',
      segmentId: 'segment-summary-1',
      bindingSummary: '上游 authority 绑定',
      matchSummary: '上游 authority 命中',
      authorityMismatchSummary: 'face-mismatch, motion-mismatch',
      authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段。',
      authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。',
      settleSummary: '上游 authority settle',
    })
    expect(view.cueMicroSummary).toEqual({
      cue: '上游 evidence cue',
      personaStyle: '上游 evidence persona',
      timing: '上游 evidence timing',
    })
    expect(view.visemeHintsSummary).toBe('上游 evidence hints')
    expect(view.driverExecutionSummary).toBe('上游 evidence execution')
  })

  it('surfaces an authority mismatch display that preserves final surface policy when runtime telemetry can explain it', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:rest:1',
        activeThreadId: 'runtime-thread-rest-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: [],
      },
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-display-first',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-display-first',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: null,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: {
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
            segmentId: 'segment-display-first',
          },
          motion: {
            idleBase: 'breathing-idle',
            attentionMode: 'observe-first',
            actionCue: 'observe_focus',
            intensity: 0.48,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.79,
            segmentId: 'segment-display-first',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-display-first',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect((view as any).authorityMismatchSummary).toBe('face-mismatch, motion-mismatch')
    expect((view as any).authorityMismatchReasonSummary).toBe('表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。')
    expect((view as any).authorityMismatchDisplay).toBe('表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。')
  })

  it('summarizes renderer alignment drift as a readable cause line', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: {
          predicted: 'Soft Gaze',
          actual: 'Focus Inspect',
          reason: 'preferred',
          status: 'drifted',
          driftKind: 'alias-resolution-drift',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: null,
          reason: 'preferred',
          status: 'predicted-only',
          driftKind: 'resident-not-yet-applied',
          driverCue: null,
          driverSource: null,
        },
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: null,
    } as any)

    expect(view.rendererAlignmentSummary).toEqual({
      live2d: 'resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      vrm: 'resident calm is waiting for renderer application',
    })
  })

  it('prefers snapshot-native renderer drift summaries over locally formatted alignment text', () => {
    const view = buildSpeechObservabilityView({
      rendererAlignment: {
        live2d: {
          predicted: 'Soft Gaze',
          actual: 'Focus Inspect',
          reason: 'preferred',
          status: 'drifted',
          driftKind: 'alias-resolution-drift',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: null,
          reason: 'preferred',
          status: 'predicted-only',
          driftKind: 'resident-not-yet-applied',
          driverCue: null,
          driverSource: null,
        },
      },
      rendererDriftSummary: {
        live2d: '上游 Live2D 显形归因',
        vrm: '上游 VRM 显形归因',
        primary: '上游 Live2D 显形归因',
      },
    } as any)

    expect(view.rendererAlignmentSummary).toEqual({
      live2d: '上游 Live2D 显形归因',
      vrm: '上游 VRM 显形归因',
    })
  })

  it('falls back to current playback cue summaries when upstream speech evidence only retains global fields after cue scoping', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: {
        voice: '上游语音摘要',
        topVisemes: '上游主口型',
      },
      speechEvidence: {
        voiceSummary: '上游 evidence voice',
        authorityMatchSummary: null,
        topVisemeSummary: '上游 evidence visemes',
        cueSummary: null,
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: '上游 evidence execution',
        visemeHintsSummary: '上游 evidence hints',
      },
      authoritySummary: {
        cueId: 'segment-authority-summary',
        segmentId: 'segment-authority-summary',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '别的 cue authority 命中',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段。',
        authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: {
        cueId: 'segment-current-playback',
        cueText: '这里才是当前播放片段。',
        cue: '当前 cue 微表情线索',
        personaStyle: '当前 cue 人设风格',
        timing: '当前 cue 时序节奏',
      },
      driverSummary: null,
      driverExecutionSummary: '当前 cue 驱动执行',
      live2dExecution: null,
      visemeHintsSummary: '当前 cue 口型提示',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-authority-summary',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'raw persona style',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: {
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
            segmentId: 'segment-current-playback',
          },
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-current-playback',
            visemeHints: [
              { segmentId: 'segment-current-playback', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
            ],
          },
        },
      },
    } as any)

    expect(view.articulationSummary).toEqual({
      voice: '上游 evidence voice',
      topVisemes: '上游 evidence visemes',
    })
    expect(view.cueMicroSummary).toEqual({
      cue: '当前 cue 微表情线索',
      personaStyle: '当前 cue 人设风格',
      timing: '当前 cue 时序节奏',
    })
    expect(view.driverExecutionSummary).toBe('上游 evidence execution')
    expect(view.visemeHintsSummary).toBe('上游 evidence hints')
  })

  it('does not reuse authority summary text when it belongs to another cue than the current playback segment', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:observability:scoped-1',
        activeThreadId: 'runtime-thread-observability-scoped-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: [],
      },
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      speechEvidence: null,
      authoritySummary: {
        cueId: 'segment-other-authority-summary',
        segmentId: 'segment-other-authority-summary',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段。',
        authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-current-playback',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: null,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-current-playback',
            visemeHints: [
              { segmentId: 'segment-current-playback', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
            ],
          },
        },
      },
    } as any)

    expect(view.authoritySummary).toEqual({
      cueId: 'segment-other-authority-summary',
      segmentId: 'segment-other-authority-summary',
      bindingSummary: null,
      matchSummary: null,
      authorityMismatchSummary: null,
      authorityMismatchReasonSummary: null,
      authorityMismatchDisplay: null,
      settleSummary: null,
    })
    expect((view as any).authorityMismatchSummary).toBe('face-mismatch, motion-mismatch')
    expect((view as any).authorityMismatchReasonSummary).toBe('表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型；当前表面策略是 procedural-carry。')
    expect((view as any).authorityMismatchDisplay).toBe('表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是口型；当前表面策略是 procedural-carry。')
  })

  it('filters viseme hints to the current playback segment so chinese cue observability stays segment-coherent', () => {
    const view = buildSpeechObservabilityView({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: null,
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-current-playback',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: null,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: null,
          rendererSettle: null,
        },
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-current-playback',
            visemeHints: [
              { segmentId: 'segment-other-playback', viseme: 'A', weight: 0.52, source: 'prosody-authority', confidence: 0.87 },
              { segmentId: 'segment-current-playback', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-current-playback', viseme: 'closed', weight: 0.62, source: 'prosody-authority', confidence: 0.9 },
            ],
          },
        },
      },
    } as any)

    expect(view.visemeHints).toEqual([
      { segmentId: 'segment-current-playback', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
      { segmentId: 'segment-current-playback', viseme: 'closed', weight: 0.62, source: 'prosody-authority', confidence: 0.9 },
    ])
    expect(view.visemeHintsSummary).toBe('I:0.35@0.94 src=prosody-authority segment=segment-current-playback | closed:0.62@0.90 src=prosody-authority segment=segment-current-playback')
  })
})
