import { describe, expect, it } from 'vitest'

import { buildSpeechAuthoritySegmentRows } from './performance-visualizer-speech-authority'

describe('performance visualizer speech authority', () => {
  it('projects speech observability into structured authority segment rows', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-zh-1',
          cueText: '继续看这里。',
          surfaces: ['live2d', 'vrm'],
          lanes: ['expression', 'lipsync', 'settle'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [
            {
              surface: 'vrm',
              lane: 'settle',
              cueId: 'segment-zh-1',
              planned: 'settle',
              consumed: 'settle',
              source: null,
              aligned: false,
              settle: {
                vrmActionFadeMs: {
                  planned: 280,
                  consumed: 320,
                },
              },
            },
          ],
        },
        {
          cueId: 'segment-other',
          cueText: '别的片段。',
          surfaces: ['vrm'],
          lanes: ['action'],
          aligned: true,
          driftStatus: 'all-aligned',
          entries: [],
        },
      ] as any,
      {
        articulation: {
          active: true,
          voiceLanguage: 'zh-CN',
          closureBias: 0.84,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
          lipClosure: 0.44,
          lipRound: 0.12,
          lipSpread: 0.18,
          jawOpen: 0.28,
          openness: 0.36,
          topVisemes: [
            { viseme: 'A', weight: 0.66 },
            { viseme: 'closed', weight: 0.41 },
            { viseme: 'E', weight: 0.24 },
          ],
        },
        articulationSummary: {
          voice: 'zh-CN | closure=0.84 | precision=0.90',
          topVisemes: 'A:0.66, closed:0.41, E:0.24',
        },
        speechEvidence: {
          voiceSummary: null,
          prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
          authorityMatchSummary: null,
          topVisemeSummary: null,
          cueSummary: null,
          cueIdentityPresent: false,
          cueProsodyPresent: false,
          personaStyleSummary: null,
          timingSummary: null,
          driverExecutionSummary: null,
          visemeHintsSummary: null,
        },
        authorityBinding: {
          segmentId: 'segment-zh-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: null,
        cueMicro: {
          cueId: 'segment-zh-1',
          cueText: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        cueMicroSummary: {
          cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=fallback-derived segment=segment-zh-1',
          personaStyle: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
          timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        },
        driverExecution: {
          face: {
            segmentId: 'segment-zh-1',
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
          },
          motion: {
            segmentId: 'segment-zh-1',
            idleBase: 'breathing-idle',
            attentionMode: 'observe-first',
            actionCue: 'observe_focus',
            intensity: 0.48,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.79,
          },
          lipsync: {
            segmentId: 'segment-zh-1',
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
          },
        },
        driverExecutionSummary: null,
        visemeHints: [
          { segmentId: 'segment-zh-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
          { segmentId: 'segment-zh-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
        ],
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      },
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: ['late-night-fatigue'],
        },
        recentDrivingTraceDetails: [
          {
            kind: 'presence-pulse-dispatched',
            summary: 'protective-watch settled after fatigue pressure rose',
            createdAt: 2_468,
            details: [
              { label: 'scenario', value: 'late-night-fatigue' },
              { label: 'stance', value: 'observe-first' },
            ],
          },
          {
            kind: 'person-state-updated',
            summary: 'source trail applied',
            createdAt: 2_469,
            details: [
              { label: 'sourceTrail', value: 'fatigue, care, grounded-recall' },
            ],
          },
        ],
      },
    )

    expect(rows).toEqual([
      {
        cueId: 'segment-zh-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityBindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        authorityMatchSummary: 'face:no motion:no lipsync:yes',
        authorityTrustSummary: '韵律权威链已重新绑定到当前片段，可直接进入长期基线。',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。',
        authorityMismatchDisplay: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。',
        speechEvidence: {
          voiceSummary: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-zh-1 | source=prosody-authority',
          prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
          authorityMatchSummary: 'face:no motion:no lipsync:yes',
          topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
          cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=fallback-derived segment=segment-zh-1',
          cueIdentityPresent: true,
          cueProsodyPresent: true,
          personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
          timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
          driverExecutionSummary: 'face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing',
          visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
        },
        speechSummaryEntries: [
          { key: 'authority', label: '权威绑定', value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中', technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes' },
          { key: 'authority-match', label: '绑定命中', value: '表情未命中 / 动作未命中 / 口型命中', technicalValue: 'face:no motion:no lipsync:yes' },
          { key: 'authority-trust', label: '权威可信性', value: '韵律权威链已重新绑定到当前片段，可直接进入长期基线。' },
          { key: 'authority-mismatch', label: '权威漂移', value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情、动作、口型；当前表面策略是 procedural-carry。' },
          { key: 'voice', label: '语音韵律', value: '中文韵律，收口 0.84，咬字 0.90，权威绑定，片段 segment-zh-1，来源 韵律权威', technicalValue: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-zh-1 | source=prosody-authority' },
          { key: 'prosody-authority', label: '韵律权威', value: '模式 energy-phoneme-hybrid，韵律 0.35，口部 0.35，头部 0.32，峰值口型 0.75，权威绑定，来源 韵律权威，片段 segment-zh-1', technicalValue: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1' },
          { key: 'visemes', label: '主口型', value: 'A 0.66，闭口 0.41，E 0.24', technicalValue: 'A:0.66, closed:0.41, E:0.24' },
          { key: 'cue', label: '微表情线索', value: 'focused / observe_focus，韵律 0.36，口部 0.28，头部 0.32，回退派生，片段 segment-zh-1', technicalValue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=fallback-derived segment=segment-zh-1' },
          { key: 'persona-style', label: '人设风格', value: 'observe-first，韵律 -0.07，节拍 -0.06，口部 -0.04，头部 +0.08', technicalValue: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08' },
          { key: 'timing', label: '时序节奏', value: '表情 320ms，动作 240ms，情绪 360ms，片段起始，软打断，保持', technicalValue: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold' },
          { key: 'driver-execution', label: '驱动执行', value: '表情 attentive/focused @0.61，保持 320ms，前置 soften，后置 hold-soft，来源 韵律权威，置信 0.83 | 动作 observe_focus，模式 先观察，待机 breathing-idle @0.48，保持 240ms，来源 时间线投影，置信 0.79 | 口型 energy-phoneme-hybrid，阶段 播放中', technicalValue: 'face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing' },
          { key: 'trace-embodiment', label: '轨迹落点', value: '关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 口型，实际执行 表情+动作+口型，场景 深夜疲劳照看，姿态 先观察后表达，来源链 fatigue -> care -> grounded-recall', technicalValue: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=face+motion+lipsync | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall' },
          { key: 'viseme-hints', label: '口型提示', value: 'I 权重 0.35（置信 0.94），闭口 权重 0.75（置信 0.89）', technicalValue: 'I:0.35@0.94 | closed:0.75@0.89' },
          { key: 'settle-authority', label: '稳定段归因', value: 'authority-bound，片段 segment-zh-1，目标 VRM，驱动 口型，来源 prosody-authority', technicalValue: 'authority-bound | segment=segment-zh-1 | target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes' },
        ],
        settleAuthoritySummary: 'authority-bound | segment=segment-zh-1 | target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        rendererDriftSummary: null,
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-zh-1 | source=prosody-authority',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32 provenance=fallback-derived segment=segment-zh-1',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'observe_focus',
        weightSummary: 'prosody=0.36 mouth=0.28 head=0.32',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-zh-1',
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'face=attentive/focused@0.61 hold=320 pre=soften post=hold-soft src=prosody-authority conf=0.83 | motion=observe_focus mode=observe-first idle=breathing-idle@0.48 hold=240 src=timeline-projection conf=0.79 | lipsync=energy-phoneme-hybrid phase=playing',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=face+motion+lipsync | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      },
    ])
  })

  it('prefers driver authority prosody metadata when speech evidence summary is absent', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-driver-prosody-native',
          cueText: '继续跟上。',
          surfaces: ['vrm'],
          lanes: ['lipsync'],
          aligned: true,
          driftStatus: 'all-aligned',
          entries: [],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        speechEvidence: {
          voiceSummary: null,
          prosodyAuthoritySummary: null,
          authorityMatchSummary: null,
          topVisemeSummary: null,
          cueSummary: null,
          cueIdentityPresent: false,
          cueProsodyPresent: false,
          personaStyleSummary: null,
          timingSummary: null,
          driverExecutionSummary: null,
          visemeHintsSummary: null,
        },
        authorityBinding: {
          segmentId: 'segment-driver-prosody-native',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: null,
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        cueMicro: null,
        cueMicroSummary: null,
        driverExecution: null,
        visemeHints: [],
        visemeHintsSummary: null,
        driverExecutionSummary: null,
        playbackTelemetry: {
          driverAuthority: {
            segmentId: 'segment-driver-prosody-native',
            rendererTarget: 'vrm',
            matchedDrivers: ['lipsync'],
            matchedSources: ['prosody-authority'],
            sources: ['prosody-authority'],
            faceSegmentMatched: false,
            motionSegmentMatched: false,
            lipsyncSegmentMatched: true,
            prosodyAuthority: {
              segmentId: 'segment-driver-prosody-native',
              provenance: 'authority-bound',
              source: 'prosody-authority',
              mode: 'energy-phoneme-hybrid',
              cueProsodyWeight: 0.35,
              cueMouthWeight: 0.35,
              cueHeadWeight: 0.32,
              visemePeakWeight: 0.75,
            },
          },
          prosodyAuthority: null,
        },
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      } as any,
    )

    expect(rows[0]?.speechEvidence?.prosodyAuthoritySummary).toBe(
      'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-driver-prosody-native',
    )
    expect(rows[0]?.authorityTrustSummary).toBe('韵律权威链已重新绑定到当前片段，可直接进入长期基线。')
  })

  it('keeps authority-bound rows visible even when cue and viseme evidence is absent', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-authority-only',
          cueText: '仅 authority seed。',
          surfaces: ['vrm'],
          lanes: ['action'],
          aligned: true,
          driftStatus: 'all-aligned',
          entries: [],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        authorityBinding: {
          segmentId: 'segment-authority-only',
          rendererTarget: 'vrm',
          matchedDrivers: ['motion'],
          matchedSources: ['timeline-projection'],
          faceSegmentMatched: false,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: false,
        },
        authoritySummary: null,
        cueMicro: null,
        cueMicroSummary: null,
        driverExecution: null,
        driverExecutionSummary: null,
        visemeHints: [],
        visemeHintsSummary: null,
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      },
      {
        recentDrivingTraceRecord: null,
        recentDrivingTraceDetails: [],
      },
    )

    expect(rows).toEqual([
      {
        cueId: 'segment-authority-only',
        cueText: '仅 authority seed。',
        driftStatus: 'all-aligned',
        aligned: true,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['motion'],
        authorityMatchedSources: ['timeline-projection'],
        authorityBindingSummary: 'target=vrm | drivers=motion | sources=timeline-projection | matches=face:no motion:yes lipsync:no',
        authorityMatchSummary: 'face:no motion:yes lipsync:no',
        authorityTrustSummary: null,
        authorityMismatchSummary: 'face-mismatch, lipsync-mismatch',
        authorityMismatchReasonSummary: '表情、口型 authority 漂移，当前绑定来源是 timeline-projection，实际执行落点是无执行。',
        authorityMismatchDisplay: '表情、口型 authority 漂移，当前绑定来源是 timeline-projection，实际执行落点是无执行。',
        speechEvidence: {
          voiceSummary: null,
          prosodyAuthoritySummary: null,
          authorityMatchSummary: 'face:no motion:yes lipsync:no',
          topVisemeSummary: null,
          cueSummary: null,
          cueIdentityPresent: false,
          cueProsodyPresent: false,
          personaStyleSummary: null,
          timingSummary: null,
          driverExecutionSummary: null,
          visemeHintsSummary: null,
        },
        speechSummaryEntries: [
          { key: 'authority', label: '权威绑定', value: '目标 VRM，驱动 动作，来源 timeline-projection，命中 表情未命中 / 动作命中 / 口型未命中', technicalValue: 'target=vrm | drivers=motion | sources=timeline-projection | matches=face:no motion:yes lipsync:no' },
          { key: 'authority-match', label: '绑定命中', value: '表情未命中 / 动作命中 / 口型未命中', technicalValue: 'face:no motion:yes lipsync:no' },
          { key: 'authority-mismatch', label: '权威漂移', value: '表情、口型 authority 漂移，当前绑定来源是 timeline-projection，实际执行落点是无执行。' },
        ],
        settleAuthoritySummary: null,
        rendererDriftSummary: null,
        voiceSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        prosodyAuthoritySummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: null,
        visemeHintsSummary: null,
      },
    ])
  })

  it('marks settle authority as fallback-derived when the cue has settle drift but no stable authority match', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-settle-fallback',
          cueText: '这里只剩 settle 回退。',
          surfaces: ['vrm'],
          lanes: ['settle'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [
            {
              surface: 'vrm',
              lane: 'settle',
              cueId: 'segment-settle-fallback',
              planned: 'settle',
              consumed: 'settle',
              source: null,
              aligned: false,
              settle: {
                vrmActionFadeMs: {
                  planned: 280,
                  consumed: 340,
                },
              },
            },
          ],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        authorityBinding: {
          segmentId: 'segment-other',
          rendererTarget: 'vrm',
          matchedDrivers: ['face'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: false,
        },
        authoritySummary: null,
        cueMicro: {
          cueId: 'segment-settle-fallback',
          cueText: '这里只剩 settle 回退。',
          prosodyWeight: null,
          mouthWeight: null,
          headWeight: null,
          personaStyleSummary: null,
          facialHoldMs: null,
          actionHoldMs: null,
          emotionHoldMs: null,
          facialCue: null,
          actionCue: null,
          actionWindow: null,
          interruptMode: null,
          settleMode: 'hold',
        },
        cueMicroSummary: {
          cue: 'n/a / n/a | prosody=n/a mouth=n/a head=n/a',
          personaStyle: null,
          timing: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold',
        },
        driverExecution: null,
        driverExecutionSummary: null,
        visemeHints: [],
        visemeHintsSummary: null,
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      },
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:fallback:1',
          activeThreadId: 'runtime-thread-fallback-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
        recentDrivingTraceDetails: [],
      },
    )

    expect(rows).toEqual([
      {
        cueId: 'segment-settle-fallback',
        cueText: '这里只剩 settle 回退。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: false,
        authorityMatchedDrivers: [],
        authorityMatchedSources: [],
        authorityBindingSummary: null,
        authorityMatchSummary: null,
        authorityTrustSummary: null,
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        speechEvidence: {
          voiceSummary: null,
          prosodyAuthoritySummary: null,
          authorityMatchSummary: null,
          topVisemeSummary: null,
          cueSummary: null,
          cueIdentityPresent: false,
          cueProsodyPresent: false,
          personaStyleSummary: null,
          timingSummary: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold',
          driverExecutionSummary: null,
          visemeHintsSummary: null,
        },
        speechSummaryEntries: [
          { key: 'timing', label: '时序节奏', value: '表情 n/a，动作 n/a，情绪 n/a，n/a，n/a，保持', technicalValue: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold' },
          { key: 'trace-embodiment', label: '轨迹落点', value: '关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 无，实际执行 无', technicalValue: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=none | execution=none' },
          { key: 'settle-authority', label: '稳定段归因', value: 'fallback-derived，片段 segment-settle-fallback', technicalValue: 'fallback-derived | segment=segment-settle-fallback' },
        ],
        settleAuthoritySummary: 'fallback-derived | segment=segment-settle-fallback',
        rendererDriftSummary: null,
        voiceSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        prosodyAuthoritySummary: null,
        personaStyleSummary: null,
        timingSummary: 'facial=n/a action=n/a emotion=n/a | n/a | n/a | hold',
        driverExecutionSummary: null,
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=none | execution=none',
        visemeHintsSummary: null,
      },
    ])
  })

  it('prefers snapshot-native authority, cue, driver, and viseme summaries for matched segments', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-summary-1',
          cueText: '继续看这里。',
          surfaces: ['vrm'],
          lanes: ['expression', 'settle'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [
            {
              surface: 'vrm',
              lane: 'settle',
              cueId: 'segment-summary-1',
              planned: 'settle',
              consumed: 'settle',
              source: null,
              aligned: false,
              settle: {
                vrmActionFadeMs: {
                  planned: 280,
                  consumed: 320,
                },
              },
            },
          ],
        },
      ] as any,
      {
        articulation: {
          active: true,
          voiceLanguage: 'zh-CN',
          closureBias: 0.84,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
          lipClosure: 0.44,
          lipRound: 0.12,
          lipSpread: 0.18,
          jawOpen: 0.28,
          openness: 0.36,
          topVisemes: [
            { viseme: 'A', weight: 0.66 },
          ],
        },
        articulationSummary: {
          voice: '上游语音摘要',
          topVisemes: '上游主口型',
        },
        authorityBinding: {
          segmentId: 'segment-summary-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: {
          cueId: 'segment-summary-1',
          segmentId: 'segment-summary-1',
          bindingSummary: '上游 authority 绑定',
          matchSummary: '上游 authority 命中',
          settleSummary: '上游 authority settle',
        },
        cueMicro: {
          cueId: 'segment-summary-1',
          cueText: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'raw persona style',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        cueMicroSummary: {
          cue: '上游微表情线索',
          personaStyle: '上游人设风格',
          timing: '上游时序节奏',
        },
        driverExecution: {
          face: {
            segmentId: 'segment-summary-1',
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
          },
          motion: null,
          lipsync: {
            segmentId: 'segment-summary-1',
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
          },
        },
        driverExecutionSummary: 'face=上游驱动执行',
        visemeHints: [
          { segmentId: 'segment-summary-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
        ],
        visemeHintsSummary: '上游口型提示',
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      } as any,
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
        recentDrivingTraceDetails: [],
      },
    )

    expect(rows).toEqual([
      {
        cueId: 'segment-summary-1',
        cueText: '继续看这里。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityBindingSummary: '上游 authority 绑定',
        authorityMatchSummary: '上游 authority 命中',
        authorityTrustSummary: null,
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情；当前表面策略是 procedural-carry。',
        authorityMismatchDisplay: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情；当前表面策略是 procedural-carry。',
        speechSummaryEntries: [
          { key: 'authority', label: '权威绑定', value: '上游 authority 绑定' },
          { key: 'authority-match', label: '绑定命中', value: '上游 authority 命中' },
          { key: 'authority-mismatch', label: '权威漂移', value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是表情；当前表面策略是 procedural-carry。' },
          { key: 'voice', label: '语音韵律', value: '上游语音摘要' },
          { key: 'visemes', label: '主口型', value: '上游主口型' },
          { key: 'cue', label: '微表情线索', value: '上游微表情线索' },
          { key: 'persona-style', label: '人设风格', value: '上游人设风格' },
          { key: 'timing', label: '时序节奏', value: '上游时序节奏' },
          { key: 'driver-execution', label: '驱动执行', value: 'face=上游驱动执行' },
          { key: 'trace-embodiment', label: '轨迹落点', value: '关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 口型，实际执行 表情', technicalValue: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=face' },
          { key: 'viseme-hints', label: '口型提示', value: '上游口型提示' },
          { key: 'settle-authority', label: '稳定段归因', value: '上游 authority settle' },
        ],
        settleAuthoritySummary: '上游 authority settle',
        rendererDriftSummary: null,
        speechEvidence: {
          voiceSummary: '上游语音摘要',
          prosodyAuthoritySummary: null,
          authorityMatchSummary: '上游 authority 命中',
          topVisemeSummary: '上游主口型',
          cueSummary: '上游微表情线索',
          cueIdentityPresent: true,
          cueProsodyPresent: true,
          personaStyleSummary: '上游人设风格',
          timingSummary: '上游时序节奏',
          driverExecutionSummary: 'face=上游驱动执行',
          visemeHintsSummary: '上游口型提示',
        },
        voiceSummary: '上游语音摘要',
        topVisemeSummary: '上游主口型',
        cueSummary: '上游微表情线索',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        faceCue: 'focused',
        actionCue: 'observe_focus',
        weightSummary: null,
        prosodyAuthoritySummary: null,
        personaStyleSummary: '上游人设风格',
        timingSummary: '上游时序节奏',
        driverExecutionSummary: 'face=上游驱动执行',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=face',
        visemeHintsSummary: '上游口型提示',
      },
    ])
  })

  it('prefers an upstream observability authority mismatch display over locally recomputing the same cue mismatch', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-display-first',
          cueText: '继续看这里。',
          surfaces: ['vrm'],
          lanes: ['lipsync'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        authorityBinding: {
          segmentId: 'segment-display-first',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: null,
        authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。',
        cueMicro: {
          cueId: 'segment-display-first',
          cueText: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: null,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        cueMicroSummary: {
          cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
          personaStyle: null,
          timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        },
        driverExecution: {
          face: {
            segmentId: 'segment-display-first',
            emotion: 'attentive',
            facialCue: 'focused',
            intensity: 0.61,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.83,
            preUtteranceCue: 'soften',
            postUtteranceCue: 'hold-soft',
          },
          motion: {
            segmentId: 'segment-display-first',
            idleBase: 'breathing-idle',
            attentionMode: 'observe-first',
            actionCue: 'observe_focus',
            intensity: 0.48,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.79,
          },
          lipsync: {
            segmentId: 'segment-display-first',
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
          },
        },
        driverExecutionSummary: null,
        visemeHints: [],
        visemeHintsSummary: null,
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      } as any,
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
        recentDrivingTraceDetails: [],
      },
    )

    expect(rows[0]?.authorityMismatchDisplay).toBe('上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。')
    expect(rows[0]?.speechSummaryEntries?.find(entry => entry.key === 'authority-mismatch')).toEqual({
      key: 'authority-mismatch',
      label: '权威漂移',
      value: '上游 authority 展示：当前仍在同一主线程里，但表情与动作、口型落点已分叉；当前表面策略是 procedural-carry。',
    })
  })

  it('does not leak renderer drift summary into non-authority observed segments', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-authority',
          cueText: '权威片段。',
          surfaces: ['vrm'],
          lanes: ['lipsync'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [],
        },
        {
          cueId: 'segment-observed-only',
          cueText: '只是被观测到的片段。',
          surfaces: ['vrm'],
          lanes: ['lipsync'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        authorityBinding: {
          segmentId: 'segment-authority',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: {
          cueId: 'segment-authority',
          segmentId: 'segment-authority',
          bindingSummary: '上游 authority 绑定',
          matchSummary: '上游 authority 命中',
          settleSummary: '上游 authority settle',
        },
        cueMicro: {
          cueId: 'segment-observed-only',
          cueText: '只是被观测到的片段。',
          prosodyWeight: 0.3,
          mouthWeight: 0.2,
          headWeight: 0.1,
          personaStyleSummary: null,
          facialHoldMs: 200,
          actionHoldMs: 180,
          emotionHoldMs: 240,
          facialCue: 'soft-gaze',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        cueMicroSummary: {
          cue: 'soft-gaze / observe_focus | prosody=0.30 mouth=0.20 head=0.10',
          personaStyle: null,
          timing: 'facial=200 action=180 emotion=240 | segment-start | soft-interrupt | hold',
        },
        driverExecution: null,
        driverExecutionSummary: null,
        visemeHints: [],
        visemeHintsSummary: null,
        rendererAlignmentSummary: {
          live2d: '上游 Live2D 显形归因',
          vrm: '上游 VRM 显形归因',
        },
      } as any,
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:authority:1',
          activeThreadId: 'runtime-thread-authority-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
        recentDrivingTraceDetails: [],
      },
    )

    expect(rows).toEqual([
      expect.objectContaining({
        cueId: 'segment-authority',
        authoritySegmentMatched: true,
        rendererDriftSummary: '上游 Live2D 显形归因',
      }),
      expect.objectContaining({
        cueId: 'segment-observed-only',
        authoritySegmentMatched: false,
        rendererDriftSummary: null,
      }),
    ])
  })

  it('does not leak trace embodiment summary into non-authority observed segments', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-authority',
          cueText: '权威片段。',
          surfaces: ['vrm'],
          lanes: ['lipsync'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [],
        },
        {
          cueId: 'segment-observed-only',
          cueText: '只是被观测到的片段。',
          surfaces: ['vrm'],
          lanes: ['lipsync'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        authorityBinding: {
          segmentId: 'segment-authority',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: {
          cueId: 'segment-authority',
          segmentId: 'segment-authority',
          bindingSummary: '上游 authority 绑定',
          matchSummary: '上游 authority 命中',
          settleSummary: '上游 authority settle',
        },
        cueMicro: {
          cueId: 'segment-observed-only',
          cueText: '只是被观测到的片段。',
          prosodyWeight: 0.3,
          mouthWeight: 0.2,
          headWeight: 0.1,
          personaStyleSummary: null,
          facialHoldMs: 200,
          actionHoldMs: 180,
          emotionHoldMs: 240,
          facialCue: 'soft-gaze',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        cueMicroSummary: {
          cue: 'soft-gaze / observe_focus | prosody=0.30 mouth=0.20 head=0.10',
          personaStyle: null,
          timing: 'facial=200 action=180 emotion=240 | segment-start | soft-interrupt | hold',
        },
        driverExecution: null,
        driverExecutionSummary: null,
        visemeHints: [],
        visemeHintsSummary: null,
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      } as any,
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:authority:1',
          activeThreadId: 'runtime-thread-authority-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
        recentDrivingTraceDetails: [
          {
            kind: 'presence-pulse-dispatched',
            summary: 'protective-watch settled after fatigue pressure rose',
            createdAt: 2_468,
            details: [
              { label: 'scenario', value: 'late-night-fatigue' },
              { label: 'stance', value: 'observe-first' },
            ],
          },
        ],
      },
    )

    expect(rows).toEqual([
      expect.objectContaining({
        cueId: 'segment-authority',
        authoritySegmentMatched: true,
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=none | scenario=late-night-fatigue | stance=observe-first',
      }),
      expect.objectContaining({
        cueId: 'segment-observed-only',
        authoritySegmentMatched: false,
        traceEmbodimentSummary: null,
      }),
    ])
  })

  it('does not reuse authority summary binding, match, or settle text when the authority summary belongs to another cue', () => {
    const rows = buildSpeechAuthoritySegmentRows(
      [
        {
          cueId: 'segment-current-authority',
          cueText: '当前 authority cue。',
          surfaces: ['vrm'],
          lanes: ['settle'],
          aligned: false,
          driftStatus: 'partial-drift',
          entries: [
            {
              surface: 'vrm',
              lane: 'settle',
              cueId: 'segment-current-authority',
              planned: 'settle',
              consumed: 'settle',
              source: null,
              aligned: false,
              settle: {
                vrmActionFadeMs: {
                  planned: 280,
                  consumed: 320,
                },
              },
            },
          ],
        },
      ] as any,
      {
        articulation: null,
        articulationSummary: null,
        authorityBinding: {
          segmentId: 'segment-current-authority',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          matchedSources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        authoritySummary: {
          cueId: 'segment-other-authority-summary',
          segmentId: 'segment-other-authority-summary',
          bindingSummary: '上游 authority 绑定',
          matchSummary: '上游 authority 命中',
          settleSummary: '上游 authority settle',
        },
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        cueMicro: null,
        cueMicroSummary: null,
        driverExecution: null,
        driverExecutionSummary: null,
        visemeHints: [],
        visemeHintsSummary: null,
        rendererAlignmentSummary: {
          live2d: null,
          vrm: null,
        },
      } as any,
      {
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:authority:scoped-1',
          activeThreadId: 'runtime-thread-authority-scoped-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: [],
        },
        recentDrivingTraceDetails: [],
      },
    )

    expect(rows).toEqual([
      {
        cueId: 'segment-current-authority',
        cueText: '当前 authority cue。',
        driftStatus: 'partial-drift',
        aligned: false,
        authoritySegmentMatched: true,
        authorityMatchedDrivers: ['lipsync'],
        authorityMatchedSources: ['prosody-authority'],
        authorityBindingSummary: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        authorityMatchSummary: 'face:no motion:no lipsync:yes',
        authorityTrustSummary: null,
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
        authorityMismatchDisplay: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。',
        speechEvidence: {
          voiceSummary: null,
          prosodyAuthoritySummary: null,
          authorityMatchSummary: 'face:no motion:no lipsync:yes',
          topVisemeSummary: null,
          cueSummary: null,
          cueIdentityPresent: false,
          cueProsodyPresent: false,
          personaStyleSummary: null,
          timingSummary: null,
          driverExecutionSummary: null,
          visemeHintsSummary: null,
        },
        speechSummaryEntries: [
          { key: 'authority', label: '权威绑定', value: '目标 VRM，驱动 口型，来源 prosody-authority，命中 表情未命中 / 动作未命中 / 口型命中', technicalValue: 'target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes' },
          { key: 'authority-match', label: '绑定命中', value: '表情未命中 / 动作未命中 / 口型命中', technicalValue: 'face:no motion:no lipsync:yes' },
          { key: 'authority-mismatch', label: '权威漂移', value: '表情、动作 authority 漂移，当前绑定来源是 prosody-authority，实际执行落点是无执行；当前表面策略是 procedural-carry。' },
          { key: 'trace-embodiment', label: '轨迹落点', value: '关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 口型，实际执行 无', technicalValue: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=none' },
          { key: 'settle-authority', label: '稳定段归因', value: 'authority-bound，片段 segment-current-authority，目标 VRM，驱动 口型，来源 prosody-authority', technicalValue: 'authority-bound | segment=segment-current-authority | target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes' },
        ],
        settleAuthoritySummary: 'authority-bound | segment=segment-current-authority | target=vrm | drivers=lipsync | sources=prosody-authority | matches=face:no motion:no lipsync:yes',
        rendererDriftSummary: null,
        voiceSummary: null,
        topVisemeSummary: null,
        cueSummary: null,
        cueIdentityPresent: false,
        cueProsodyPresent: false,
        faceCue: null,
        actionCue: null,
        weightSummary: null,
        prosodyAuthoritySummary: null,
        personaStyleSummary: null,
        timingSummary: null,
        driverExecutionSummary: null,
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=none',
        visemeHintsSummary: null,
      },
    ])
  })
})
