import { describe, expect, it } from 'vitest'

import { buildSelfEvolutionRuntimeContinuityProjection } from './performance-visualizer-self-evolution-runtime-continuity'

describe('performance visualizer self evolution runtime continuity projection', () => {
  it('connects renderer authority evidence to runtime and scene continuity evidence', () => {
    const projection = buildSelfEvolutionRuntimeContinuityProjection({
      rendererAuthorityProjection: {
        status: 'grounded',
        rendererTarget: 'vrm',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: {
              fromWatchMode: 'symbiotic-vision',
              toWatchMode: 'recovering',
              fromScenario: 'chat',
              durationMs: 90_000,
              reason: 'host fatigue detected during late-night care',
              occurredAt: 1_234,
            },
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: ['late-night-fatigue'],
        },
        recentDrivingTraceDetails: [
          {
            kind: 'governance-normalized',
            summary: 'turn=care | truth=live-grounded | repair=none',
            createdAt: 2_430,
            details: [
              { label: 'scenario', value: 'late-night-fatigue' },
              { label: 'stance', value: 'observe-first' },
              { label: 'sourceTrail', value: 'fatigue, care, grounded-recall' },
            ],
          },
        ],
      } as any,
    })

    expect(projection).toEqual({
      status: 'grounded',
      runtimeChannel: 'active-dialogue',
      runtimeSummary: 'runtime alignment held',
      activeThreadId: 'runtime-thread-rest-1',
      activeThreadTitle: 'late-night care',
      runtimeScenario: 'coding',
      runtimeScene: 'coding',
      transitionFromWatchMode: 'symbiotic-vision',
      transitionToWatchMode: 'recovering',
      transitionFromScenario: 'chat',
      transitionReason: 'host fatigue detected during late-night care',
      governorDrive: 'protect',
      governorIntentionId: 'governor-intention-rest-1',
      focusBeliefId: 'belief-rest-1',
      rationaleTags: ['recovering', 'late-night-fatigue'],
      traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=none | execution=none | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall',
      traceEmbodimentDisplaySummary: '关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 无，实际执行 无，场景 深夜疲劳照看，姿态 先观察后表达，来源链 fatigue -> care -> grounded-recall',
      matchedSignals: [
        'runtime-channel:active-dialogue',
        'runtime-thread:runtime-thread-rest-1',
        'runtime-scenario:coding',
        'runtime-scene:coding',
        'transition-from:symbiotic-vision',
        'transition-to:recovering',
        'governor-drive:protect',
        'focus-belief:belief-rest-1',
        'trace-embodiment',
      ],
      missingSignals: [],
      driftingSignals: [],
      reasons: [
        'Runtime continuity still stays on thread runtime-thread-rest-1 with active-dialogue/coding context, so the rendered authority output is attached to an ongoing life situation instead of a detached animation shell.',
        'Recent transition still explains the move from symbiotic-vision to recovering because host fatigue detected during late-night care, which preserves a causal line between the prior scene and the current embodied posture.',
        'Upstream renderer authority is still carrying the same manifestation line, so runtime continuity can explain the current embodiment as one continuous person-state rather than a renderer-local improvisation.',
        'Trace embodiment summary still closes the same care/grounded-recall line, so renderer authority is part of one continuous person-state rather than a fresh isolated output.',
      ],
    })
  })

  it('keeps renderer drift attached to runtime continuity instead of treating it as a pre-runtime identity break', () => {
    const projection = buildSelfEvolutionRuntimeContinuityProjection({
      rendererAuthorityProjection: {
        status: 'partial',
        rendererTarget: 'live2d',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:no',
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.35 | mouth=0.35 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-live2d-1',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [
          'renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
        ],
        reasons: [
          'Renderer drift still shows resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority, so the visible face is diverging after mind-to-render projection rather than before it.',
        ],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: ['late-night-fatigue'],
        },
        recentDrivingTraceDetails: [],
      } as any,
    })

    expect(projection?.driftingSignals).toContain('renderer-drift:resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority')
    expect(projection?.reasons).toContain('Upstream renderer authority is still carrying the same manifestation line, so runtime continuity can explain the current embodiment as one continuous person-state rather than a renderer-local improvisation.')
    expect(projection?.reasons).toContain('Renderer continuity still carries resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority, so the life thread can explain the visible divergence as a post-projection renderer event instead of a broken resident mind state.')
    expect(projection?.reasons).toContain('Prosody authority still anchors energy-phoneme-hybrid on segment-live2d-1, so runtime continuity can attribute the mouth-driving divergence to the same speech segment instead of a detached renderer branch.')
  })

  it('prefers an upstream runtime continuity trace embodiment summary when one is already projected', () => {
    const projection = buildSelfEvolutionRuntimeContinuityProjection({
      rendererAuthorityProjection: {
        status: 'grounded',
        rendererTarget: 'vrm',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: ['late-night-fatigue'],
        },
        recentDrivingTraceDetails: [
          {
            kind: 'governance-normalized',
            summary: 'turn=care | truth=live-grounded | repair=none',
            createdAt: 2_430,
            details: [
              { label: 'scenario', value: 'late-night-fatigue' },
              { label: 'stance', value: 'observe-first' },
              { label: 'sourceTrail', value: 'fatigue, care, grounded-recall' },
            ],
          },
        ],
      } as any,
      traceEmbodimentSummary: '上游轨迹摘要：中文优先 continuity explainability',
    })

    expect(projection?.traceEmbodimentSummary).toBe('上游轨迹摘要：中文优先 continuity explainability')
    expect(projection?.traceEmbodimentDisplaySummary).toBe('上游轨迹摘要：中文优先 continuity explainability')
    expect(projection?.reasons).toContain('Trace embodiment summary still closes the same care/grounded-recall line, so renderer authority is part of one continuous person-state rather than a fresh isolated output.')
  })

  it('enriches a sparse upstream generated trace embodiment summary with local trace detail context', () => {
    const projection = buildSelfEvolutionRuntimeContinuityProjection({
      rendererAuthorityProjection: {
        status: 'grounded',
        rendererTarget: 'vrm',
        runtimeProfile: 'protective-watch',
        runtimeBodyState: 'settled',
        runtimeContinuityMode: 'ambient-covision',
        runtimeResidentEmotion: 'tired',
        runtimeResidentDelivery: 'gentle',
        runtimeResidentFacialCue: 'focused',
        runtimeResidentActionCue: 'observe_focus',
        playbackCueFacialCue: 'focused',
        playbackCueActionCue: 'observe_focus',
        driverFaceCue: 'focused',
        driverActionCue: 'observe_focus',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        matchedSignals: [],
        missingSignals: [],
        driftingSignals: [],
        reasons: [],
      },
      speechEmbodiment: {
        runtimeDynamics: {
          profile: 'protective-watch',
          variationToken: 'presence-pulse|protective-watch',
          residentEmotion: 'tired',
          residentDelivery: 'gentle',
          residentFacialCue: 'focused',
          residentActionCue: 'observe_focus',
          actionIntensity: 0.1,
          breathDrive: 0.2,
          focusDrive: 0.3,
          provenance: {
            watchMode: 'recovering',
            bodyState: 'settled',
            continuityMode: 'ambient-covision',
            thoughtStance: 'care',
            thoughtShouldSpeak: false,
            thoughtTension: 'focused-flow',
            runtimeChannel: 'active-dialogue',
            runtimeSummary: 'runtime alignment held',
            activeThreadId: 'runtime-thread-rest-1',
            activeThreadTitle: 'late-night care',
            preferredPresence: 'gentle-watch',
            selectedAction: 'observe_focus',
            personaBiasSummary: 'protective-watch favored due to late-night care pressure',
            personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
            scene: 'coding',
            scenario: 'coding',
          },
          eventPointers: {
            recentTransition: null,
            rationaleTags: ['recovering', 'late-night-fatigue'],
            focusBeliefId: 'belief-rest-1',
            focusInquiryId: null,
            commitmentId: 'commitment-rest-1',
            runtimeThreadId: 'runtime-thread-rest-1',
            governorDrive: 'protect',
            governorIntentionId: 'governor-intention-rest-1',
            selectedThoughtThreadId: 'thought-thread-rest-1',
          },
        },
        recentDrivingTraceRecord: {
          decisionTraceId: 'mind:rest:1',
          activeThreadId: 'runtime-thread-rest-1',
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: ['late-night-fatigue'],
        },
        recentDrivingTraceDetails: [
          {
            kind: 'governance-normalized',
            summary: 'turn=care | truth=live-grounded | repair=none',
            createdAt: 2_430,
            details: [
              { label: 'scenario', value: 'late-night-fatigue' },
              { label: 'stance', value: 'observe-first' },
              { label: 'sourceTrail', value: 'fatigue, care, grounded-recall' },
            ],
          },
        ],
      } as any,
      traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry',
    })

    expect(projection?.traceEmbodimentSummary).toBe('turn=care | closure=grounded-recall | surface=procedural-carry | authority=none | execution=none | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall')
    expect(projection?.traceEmbodimentDisplaySummary).toBe('关怀回合，收口 grounded-recall（基于记忆回收落稳），表面策略 procedural-carry（沿既有过程延续表达），权威驱动 无，实际执行 无，场景 深夜疲劳照看，姿态 先观察后表达，来源链 fatigue -> care -> grounded-recall')
  })
})
