import { describe, expect, it } from 'vitest'

import {
  buildRecentDrivingEventQueryInput,
  buildRecentDrivingTraceDetailsFromMindTurnEvents,
  buildRecentDrivingTraceEventsFromMindTurnEvents,
  buildRecentDrivingTraceRecordSummaryFromMemoryDecisionTraces,
  mapSpeechEmbodimentDiagnosticsForRenderer,
  resolveRecentDrivingEventFromMindTurnEvents,
} from './index.speech-embodiment-diagnostics'

describe('index speech embodiment diagnostics mapping', () => {
  it('maps stage speech diagnostics snapshot into renderer diagnostics store shape', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0.18,
          O: 0.08,
          U: 0.12,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:trace:vrm-1',
        activeThreadId: 'thread-vrm-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: ['nearby-thread'],
      },
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      traceSummary: {
        decisionTraceId: 'mind:trace:vrm-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        activeThreadId: 'thread-vrm-1',
        suppressionTags: ['nearby-thread'],
        latestEventSummary: null,
        segmentBinding: {
          matched: true,
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          matchedSources: ['seeded-face', 'seeded-motion', 'seeded-lipsync'],
        },
      },
      rendererAlignment: {
        live2d: {
          predicted: 'CalmInspect',
          actual: 'CalmInspect',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: 'calm',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: null,
          driverSource: null,
        },
      },
      rendererDriftSummary: {
        live2d: null,
        vrm: null,
        primary: null,
      },
      articulationSummary: {
        voice: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemes: 'A:0.66, closed:0.41, E:0.24',
      },
      authoritySummary: {
        cueId: 'segment-vrm-1',
        segmentId: 'segment-vrm-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['face', 'motion', 'lipsync'],
        matchedSources: ['seeded-face', 'seeded-motion', 'seeded-lipsync'],
        bindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=seeded-face, seeded-motion, seeded-lipsync | matches=face:yes motion:yes lipsync:yes',
        matchSummary: 'face:yes motion:yes lipsync:yes',
        authorityTrustSummary: null,
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.36 | mouth=0.28 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-vrm-1',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        settleSummary: 'authority-bound | segment=segment-vrm-1 | target=vrm | drivers=face, motion, lipsync | sources=seeded-face, seeded-motion, seeded-lipsync',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=face, motion, lipsync | execution=face+motion+lipsync',
      },
      speechEvidence: {
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-vrm-1 | source=prosody-authority',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      },
      cueMicroSummary: {
        cueId: 'segment-vrm-1',
        cueText: null,
        cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        personaStyle: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      driverSummary: {
        rendererTarget: 'vrm',
        face: {
          cue: 'focused',
          source: 'prosody-authority',
          confidence: 0.94,
          segmentId: 'segment-vrm-1',
        },
        motion: null,
        lipsync: null,
      },
      driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
      live2dExecution: {
        activeExpression: {
          name: 'CalmInspect',
          reason: 'preferred',
          score: 11.4,
          segmentId: 'segment-vrm-1',
        },
        activeMotion: {
          group: 'ObserveSoft',
          index: 1,
        },
        cue: {
          emotion: 'thinking',
          facialCue: 'focus',
          preferredExpressionAliases: ['CalmInspect'],
          live2dFacialReleaseMs: 320,
          live2dMotionFollowThroughMs: 440,
        },
      },
      visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-vrm-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          sources: ['seeded-face', 'seeded-motion', 'seeded-lipsync'],
          faceSegmentMatched: true,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: true,
          prosodyAuthority: {
            segmentId: 'segment-vrm-1',
            provenance: 'authority-bound',
            source: 'prosody-authority',
            mode: 'energy-phoneme-hybrid',
            cueProsodyWeight: 0.36,
            cueMouthWeight: 0.28,
            cueHeadWeight: 0.32,
            visemePeakWeight: 0.75,
          },
        },
        cue: {
          id: 'segment-vrm-1',
          text: null,
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: {
            preferredExpressionAliases: ['CalmInspect'],
            preferredMotionAliases: ['ObserveSoft'],
          },
          rendererSettle: {
            live2dFacialReleaseMs: 320,
            live2dMotionFollowThroughMs: 440,
            vrmActionFadeMs: 280,
            vrmExpressionBlendMs: 360,
          },
        },
        drivers: {
          face: {
            emotion: 'thinking',
            facialCue: 'focused',
            intensity: 0.52,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.94,
            preUtteranceCue: 'steady-inhale',
            postUtteranceCue: 'soft-release',
            segmentId: 'segment-vrm-1',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-vrm-1',
            visemeHints: [
              { segmentId: 'segment-vrm-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-vrm-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
            ],
          },
          motion: {
            idleBase: 'idle_settle',
            attentionMode: 'attentive',
            actionCue: 'observe_focus',
            intensity: 0.34,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-vrm-1',
          },
        },
      },
    } as any)

    expect(mapped).toEqual({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0.18,
          O: 0.08,
          U: 0.12,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:trace:vrm-1',
        activeThreadId: 'thread-vrm-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: ['nearby-thread'],
      },
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      traceSummary: {
        decisionTraceId: 'mind:trace:vrm-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        activeThreadId: 'thread-vrm-1',
        suppressionTags: ['nearby-thread'],
        latestEventSummary: null,
        segmentBinding: {
          matched: true,
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          matchedSources: ['seeded-face', 'seeded-motion', 'seeded-lipsync'],
        },
      },
      rendererAlignment: {
        live2d: {
          predicted: 'CalmInspect',
          actual: 'CalmInspect',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: 'calm',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: null,
          driverSource: null,
        },
      },
      rendererDriftSummary: null,
      articulationSummary: {
        voice: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemes: 'A:0.66, closed:0.41, E:0.24',
      },
      authoritySummary: {
        cueId: 'segment-vrm-1',
        segmentId: 'segment-vrm-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['face', 'motion', 'lipsync'],
        matchedSources: ['seeded-face', 'seeded-motion', 'seeded-lipsync'],
        bindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=seeded-face, seeded-motion, seeded-lipsync | matches=face:yes motion:yes lipsync:yes',
        matchSummary: 'face:yes motion:yes lipsync:yes',
        authorityTrustSummary: null,
        prosodyAuthoritySummary: 'mode=energy-phoneme-hybrid | prosody=0.36 | mouth=0.28 | head=0.32 | visemePeak=0.75 | provenance=authority-bound | source=prosody-authority | segment=segment-vrm-1',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        settleSummary: 'authority-bound | segment=segment-vrm-1 | target=vrm | drivers=face, motion, lipsync | sources=seeded-face, seeded-motion, seeded-lipsync',
        traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=face, motion, lipsync | execution=face+motion+lipsync',
      },
      speechEvidence: {
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90 | provenance=authority-bound | segment=segment-vrm-1 | source=prosody-authority',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      },
      cueMicroSummary: {
        cueId: 'segment-vrm-1',
        cueText: null,
        cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        personaStyle: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      driverSummary: {
        rendererTarget: 'vrm',
        face: {
          cue: 'focused',
          source: 'prosody-authority',
          confidence: 0.94,
          segmentId: 'segment-vrm-1',
        },
        motion: null,
        lipsync: null,
      },
      live2dExecution: {
        activeExpression: {
          name: 'CalmInspect',
          reason: 'preferred',
          score: 11.4,
          segmentId: 'segment-vrm-1',
        },
        activeMotion: {
          group: 'ObserveSoft',
          index: 1,
        },
        cue: {
          emotion: 'thinking',
          facialCue: 'focus',
          preferredExpressionAliases: ['CalmInspect'],
          live2dFacialReleaseMs: 320,
          live2dMotionFollowThroughMs: 440,
        },
      },
      driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
      visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-vrm-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          sources: ['seeded-face', 'seeded-motion', 'seeded-lipsync'],
          faceSegmentMatched: true,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: true,
          prosodyAuthority: {
            segmentId: 'segment-vrm-1',
            provenance: 'authority-bound',
            source: 'prosody-authority',
            mode: 'energy-phoneme-hybrid',
            cueProsodyWeight: 0.36,
            cueMouthWeight: 0.28,
            cueHeadWeight: 0.32,
            visemePeakWeight: 0.75,
          },
        },
        cue: {
          id: 'segment-vrm-1',
          text: null,
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: {
            preferredExpressionAliases: ['CalmInspect'],
            preferredMotionAliases: ['ObserveSoft'],
          },
          rendererSettle: {
            live2dFacialReleaseMs: 320,
            live2dMotionFollowThroughMs: 440,
            vrmActionFadeMs: 280,
            vrmExpressionBlendMs: 360,
          },
        },
        drivers: {
          face: {
            emotion: 'thinking',
            facialCue: 'focused',
            intensity: 0.52,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.94,
            preUtteranceCue: 'steady-inhale',
            postUtteranceCue: 'soft-release',
            segmentId: 'segment-vrm-1',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-vrm-1',
            visemeHints: [
              { segmentId: 'segment-vrm-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-vrm-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
            ],
          },
          motion: {
            idleBase: 'idle_settle',
            attentionMode: 'attentive',
            actionCue: 'observe_focus',
            intensity: 0.34,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-vrm-1',
          },
        },
      },
    })
  })

  it('enriches upstream authority mismatch explainability with final surface policy when renderer trace context has stronger authority evidence', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:trace:display-policy-1',
        activeThreadId: 'thread-display-policy-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: [],
      },
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      articulationSummary: null,
      authoritySummary: {
        cueId: 'segment-display-policy-1',
        segmentId: 'segment-display-policy-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段。',
        authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作落点已经和绑定片段分叉。',
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: null,
      driverSummary: null,
      driverExecutionSummary: 'lipsync=energy-phoneme-hybrid phase=playing',
      live2dExecution: null,
      visemeHintsSummary: null,
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-display-policy-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: null,
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-display-policy-1',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(mapped.authoritySummary).toEqual({
      cueId: 'segment-display-policy-1',
      segmentId: 'segment-display-policy-1',
      rendererTarget: 'vrm',
      matchedDrivers: ['lipsync'],
      matchedSources: ['prosody-authority'],
      prosodyAuthoritySummary: null,
      bindingSummary: '上游 authority 绑定',
      matchSummary: '上游 authority 命中',
      authorityTrustSummary: null,
      authorityMismatchSummary: 'face-mismatch, motion-mismatch',
      authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段；当前表面策略是 procedural-carry。',
      authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作落点已经和绑定片段分叉；当前表面策略是 procedural-carry。',
      settleSummary: '上游 authority settle',
      traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=lipsync',
    })
  })

  it('builds snapshot-native trace embodiment summary on authority summary when trace and execution context are available', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:trace:summary-native-1',
        activeThreadId: 'thread-summary-native-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: [],
      },
      recentDrivingTraceDetails: [
        {
          kind: 'presence-pulse-dispatched',
          summary: 'protective-watch settled after fatigue pressure rose',
          createdAt: 1234,
          details: [
            { label: 'scenario', value: 'late-night-fatigue' },
            { label: 'stance', value: 'observe-first' },
          ],
        },
        {
          kind: 'person-state-updated',
          summary: 'fatigue, care, grounded-recall',
          createdAt: 1235,
          details: [
            { label: 'sourceTrail', value: 'fatigue, care, grounded-recall' },
          ],
        },
      ],
      authoritySummary: {
        cueId: 'segment-summary-native-1',
        segmentId: 'segment-summary-native-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        settleSummary: '上游 authority settle',
      },
      driverExecutionSummary: 'lipsync=energy-phoneme-hybrid phase=playing',
    } as any)

    expect(mapped.authoritySummary).toEqual({
      cueId: 'segment-summary-native-1',
      segmentId: 'segment-summary-native-1',
      rendererTarget: 'vrm',
      matchedDrivers: ['lipsync'],
      matchedSources: ['prosody-authority'],
      prosodyAuthoritySummary: null,
      bindingSummary: '上游 authority 绑定',
      matchSummary: '上游 authority 命中',
      authorityTrustSummary: null,
      authorityMismatchSummary: null,
      authorityMismatchReasonSummary: null,
      authorityMismatchDisplay: null,
      settleSummary: '上游 authority settle',
      traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=lipsync | scenario=late-night-fatigue | stance=observe-first | sourceTrail=fatigue, care, grounded-recall',
    })
  })

  it('builds fallback trace summary with the current playback cue id instead of an unrelated authority summary cue id', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      recentDrivingEvent: {
        kind: 'person-state-updated',
        decisionTraceId: 'mind:trace:cue-scope-1',
        summary: 'protective-watch settled after fatigue pressure rose',
        createdAt: 2468,
      },
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:trace:cue-scope-1',
        activeThreadId: 'runtime-thread-cue-scope-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: ['late-night-fatigue'],
      },
      recentDrivingTraceEvents: [
        {
          kind: 'person-state-updated',
          summary: 'protective-watch settled after fatigue pressure rose',
          createdAt: 2468,
        },
      ],
      recentDrivingTraceDetails: [],
      traceSummary: null,
      authoritySummary: {
        cueId: 'segment-authority-summary',
        segmentId: 'segment-authority-summary',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        settleSummary: '上游 authority settle',
        traceEmbodimentSummary: '上游 authority 轨迹落点摘要',
      },
      driverSummary: {
        rendererTarget: 'vrm',
        face: null,
        motion: null,
        lipsync: {
          cue: 'I',
          source: 'prosody-authority',
          confidence: 0.91,
          segmentId: 'segment-current-playback',
          mode: 'energy-phoneme-hybrid',
        },
      },
      playbackTelemetry: {
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-authority-summary',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        drivers: {
          face: null,
          motion: null,
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-current-playback',
            visemeHints: [],
          },
        },
      },
    } as any)

    expect(mapped.traceSummary).toEqual({
      cueId: 'segment-current-playback',
      decisionTraceId: 'mind:trace:cue-scope-1',
      turnMode: 'care',
      truthState: 'live-grounded',
      repairState: 'none',
      finalSurfacePolicy: 'procedural-carry',
      closureState: 'grounded-recall',
      activeThreadId: 'runtime-thread-cue-scope-1',
      suppressionTags: ['late-night-fatigue'],
      latestEventSummary: 'protective-watch settled after fatigue pressure rose',
      segmentBinding: {
        matched: false,
        rendererTarget: 'vrm',
        matchedDrivers: [],
        matchedSources: [],
      },
    })
  })

  it('builds snapshot-native speech evidence when renderer speech diagnostics carry chinese-first evidence summaries', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      articulationSummary: {
        voice: '上游语音摘要',
        topVisemes: '上游主口型',
      },
      authoritySummary: {
        cueId: 'segment-summary-native-1',
        segmentId: 'segment-summary-native-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: {
        cueId: 'segment-summary-native-1',
        cueText: '继续看这里。',
        cue: '上游微表情线索',
        personaStyle: '上游人设风格',
        timing: '上游时序节奏',
      },
      driverExecutionSummary: '上游驱动执行',
      visemeHintsSummary: '上游口型提示',
      playbackTelemetry: {
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-summary-native-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-summary-native-1',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        drivers: null,
      },
    } as any)

    expect(mapped.speechEvidence).toEqual({
      voiceSummary: '上游语音摘要',
      authorityMatchSummary: '上游 authority 命中',
      topVisemeSummary: '上游主口型',
      cueSummary: '上游微表情线索',
      cueIdentityPresent: true,
      cueProsodyPresent: true,
      personaStyleSummary: '上游人设风格',
      timingSummary: '上游时序节奏',
      driverExecutionSummary: '上游驱动执行',
      visemeHintsSummary: '上游口型提示',
    })
  })

  it('does not reuse authority and cue speech evidence fields when they belong to a different cue than the current playback segment', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      articulationSummary: {
        voice: '上游语音摘要',
        topVisemes: '上游主口型',
      },
      authoritySummary: {
        cueId: 'segment-authority-summary',
        segmentId: 'segment-authority-summary',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '别的 cue authority 命中',
        authorityMismatchSummary: null,
        authorityMismatchReasonSummary: null,
        authorityMismatchDisplay: null,
        settleSummary: '上游 authority settle',
      },
      cueMicroSummary: {
        cueId: 'segment-other-cue',
        cueText: '别的 cue。',
        cue: '别的 cue 微表情线索',
        personaStyle: '别的 cue 人设风格',
        timing: '别的 cue 时序节奏',
      },
      driverExecutionSummary: '上游驱动执行',
      visemeHintsSummary: '上游口型提示',
      playbackTelemetry: {
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-authority-summary',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        drivers: null,
      },
    } as any)

    expect(mapped.speechEvidence).toEqual({
      voiceSummary: '上游语音摘要',
      authorityMatchSummary: null,
      topVisemeSummary: '上游主口型',
      cueSummary: null,
      cueIdentityPresent: true,
      cueProsodyPresent: true,
      personaStyleSummary: null,
      timingSummary: null,
      driverExecutionSummary: '上游驱动执行',
      visemeHintsSummary: '上游口型提示',
    })
  })

  it('does not retain authority summary text when it belongs to a different cue than the current playback segment', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'playing',
      playbackPhase: 'playing',
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:diagnostics:scoped-1',
        activeThreadId: 'runtime-thread-diagnostics-scoped-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: [],
      },
      recentDrivingTraceDetails: [],
      authoritySummary: {
        cueId: 'segment-authority-summary',
        segmentId: 'segment-authority-summary',
        rendererTarget: 'vrm',
        matchedDrivers: ['lipsync'],
        matchedSources: ['prosody-authority'],
        bindingSummary: '上游 authority 绑定',
        matchSummary: '上游 authority 命中',
        authorityMismatchSummary: 'face-mismatch, motion-mismatch',
        authorityMismatchReasonSummary: '上游 authority reason：表情与动作已经偏离绑定片段。',
        authorityMismatchDisplay: '上游 authority 展示：当前仍在同一主线程里，但表情与动作落点已经和绑定片段分叉。',
        settleSummary: '上游 authority settle',
      },
      driverExecutionSummary: null,
      playbackTelemetry: {
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-current-playback',
          rendererTarget: 'vrm',
          matchedDrivers: ['lipsync'],
          sources: ['prosody-authority'],
          faceSegmentMatched: false,
          motionSegmentMatched: false,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-current-playback',
          text: '这里才是当前播放片段。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
        },
        drivers: null,
      },
    } as any)

    expect(mapped.authoritySummary).toEqual({
      cueId: 'segment-authority-summary',
      segmentId: 'segment-authority-summary',
      rendererTarget: 'vrm',
      matchedDrivers: ['lipsync'],
      matchedSources: ['prosody-authority'],
      prosodyAuthoritySummary: null,
      bindingSummary: null,
      matchSummary: null,
      authorityTrustSummary: null,
      authorityMismatchSummary: null,
      authorityMismatchReasonSummary: null,
      authorityMismatchDisplay: null,
      settleSummary: null,
      traceEmbodimentSummary: 'turn=care | closure=grounded-recall | surface=procedural-carry | authority=lipsync | execution=none',
    })
  })

  it('builds snapshot-native renderer drift summaries when renderer alignment explains visible divergence', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      rendererAlignment: {
        live2d: {
          predicted: 'Soft Gaze',
          actual: 'Focus Inspect',
          reason: 'preferred',
          status: 'drifted',
          driftKind: 'alias-resolution-drift',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: null,
          reason: 'preferred',
          status: 'predicted-only',
          driftKind: 'resident-not-yet-applied',
          driverCue: null,
          driverSource: null,
        },
      },
    } as any)

    expect(mapped.rendererDriftSummary).toEqual({
      live2d: 'resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
      vrm: 'resident calm is waiting for renderer application',
      primary: 'resident Soft Gaze -> actual Focus Inspect | cue focused@prosody-authority',
    })
  })

  it('maps resident runtime explanation for quiet accompaniment into renderer diagnostics shape', () => {
    const mapped = mapSpeechEmbodimentDiagnosticsForRenderer({
      phase: 'idle',
      playbackPhase: 'idle',
      speechEnergy: 0,
      prosodyIntensity: 0,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      runtimeDynamics: {
        profile: 'quiet-accompaniment',
        variationToken: 'presence-pulse|quiet-accompaniment',
        residentEmotion: 'thinking',
        residentDelivery: 'gentle',
        residentFacialCue: 'focus',
        residentActionCue: 'steady_focus',
        actionIntensity: 0.1,
        breathDrive: 0.2,
        focusDrive: 0.2,
        provenance: {
          watchMode: 'symbiotic-vision',
          bodyState: 'accompanying',
          continuityMode: 'quiet-accompaniment',
          thoughtStance: 'accompany',
          thoughtShouldSpeak: false,
          thoughtTension: 'focused-flow',
          runtimeChannel: null,
          runtimeSummary: null,
          scene: 'coding',
          scenario: 'coding',
          personaBiasSummary: 'persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.',
          personaOpeningGuidance: 'Open by observing first and keep the approach lighter.',
        },
        eventPointers: {
          recentTransition: {
            fromWatchMode: 'invited-inspection',
            toWatchMode: 'symbiotic-vision',
            fromScenario: 'coding',
            durationMs: 180_000,
            reason: 'settled into quiet accompaniment',
            occurredAt: 1_234,
          },
          rationaleTags: ['scene:diff', 'companionship'],
          focusBeliefId: 'belief-focus-1',
          focusInquiryId: 'inquiry-focus-1',
          commitmentId: 'commitment-focus-1',
          runtimeThreadId: 'runtime-thread-1',
          governorDrive: 'stabilize',
          governorIntentionId: 'governor-intention-1',
          selectedThoughtThreadId: 'thought-thread-1',
        },
      },
      recentDrivingEvent: {
        kind: 'presence-pulse-dispatched',
        decisionTraceId: 'mind:quiet:1',
        summary: 'quiet accompaniment line held after focus stabilized',
        createdAt: 3_210,
      },
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:quiet:1',
        activeThreadId: 'thread-quiet-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: ['companionship'],
      },
      recentDrivingTraceEvents: [
        {
          kind: 'governance-normalized',
          summary: 'turn=care | truth=live-grounded | repair=none',
          createdAt: 3_000,
        },
        {
          kind: 'presence-pulse-dispatched',
          summary: 'quiet accompaniment line held after focus stabilized',
          createdAt: 3_210,
        },
      ],
      recentDrivingTraceDetails: [],
      driverSummary: null,
      live2dExecution: null,
      playbackTelemetry: null,
    } as any)

    expect(mapped.runtimeDynamics).toEqual({
      profile: 'quiet-accompaniment',
      variationToken: 'presence-pulse|quiet-accompaniment',
      residentEmotion: 'thinking',
      residentDelivery: 'gentle',
      residentFacialCue: 'focus',
      residentActionCue: 'steady_focus',
      actionIntensity: 0.1,
      breathDrive: 0.2,
      focusDrive: 0.2,
      provenance: {
        watchMode: 'symbiotic-vision',
        bodyState: 'accompanying',
        continuityMode: 'quiet-accompaniment',
        thoughtStance: 'accompany',
        thoughtShouldSpeak: false,
        thoughtTension: 'focused-flow',
        runtimeChannel: null,
        runtimeSummary: null,
        scene: 'coding',
        scenario: 'coding',
        personaBiasSummary: 'persona prefers observe-first room, so visible return cadence should stay slower until the opening softens.',
        personaOpeningGuidance: 'Open by observing first and keep the approach lighter.',
      },
      eventPointers: {
        recentTransition: {
          fromWatchMode: 'invited-inspection',
          toWatchMode: 'symbiotic-vision',
          fromScenario: 'coding',
          durationMs: 180_000,
          reason: 'settled into quiet accompaniment',
          occurredAt: 1_234,
        },
        rationaleTags: ['scene:diff', 'companionship'],
        focusBeliefId: 'belief-focus-1',
        focusInquiryId: 'inquiry-focus-1',
        commitmentId: 'commitment-focus-1',
        runtimeThreadId: 'runtime-thread-1',
        governorDrive: 'stabilize',
        governorIntentionId: 'governor-intention-1',
        selectedThoughtThreadId: 'thought-thread-1',
      },
    })
    expect(mapped.recentDrivingEvent).toEqual({
      kind: 'presence-pulse-dispatched',
      decisionTraceId: 'mind:quiet:1',
      summary: 'quiet accompaniment line held after focus stabilized',
      createdAt: 3_210,
    })
    expect(mapped.recentDrivingTraceRecord).toEqual({
      decisionTraceId: 'mind:quiet:1',
      activeThreadId: 'thread-quiet-1',
      turnMode: 'care',
      truthState: 'live-grounded',
      repairState: 'none',
      finalSurfacePolicy: 'procedural-carry',
      closureState: 'grounded-recall',
      suppressionTags: ['companionship'],
    })
    expect(mapped.recentDrivingTraceEvents).toEqual([
      {
        kind: 'governance-normalized',
        summary: 'turn=care | truth=live-grounded | repair=none',
        createdAt: 3_000,
      },
      {
        kind: 'presence-pulse-dispatched',
        summary: 'quiet accompaniment line held after focus stabilized',
        createdAt: 3_210,
      },
    ])
  })

  it('falls back to an idle renderer snapshot when stage diagnostics are absent', () => {
    expect(mapSpeechEmbodimentDiagnosticsForRenderer(null)).toEqual({
      phase: 'idle',
      playbackPhase: 'idle',
      speechEnergy: 0,
      prosodyIntensity: 0,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      traceSummary: null,
      driverSummary: null,
      live2dExecution: null,
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      rendererDriftSummary: null,
      articulationSummary: null,
      authoritySummary: null,
      cueMicroSummary: null,
      driverExecutionSummary: null,
      visemeHintsSummary: null,
      playbackTelemetry: null,
    })
  })

  it('prefers presence-pulse-dispatched as the recent driving event when a summarized event exists', () => {
    const selected = resolveRecentDrivingEventFromMindTurnEvents([
      {
        id: 'evt-1',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-1',
        sessionId: 'session-1',
        origin: 'system',
        kind: 'person-state-updated',
        payload: {
          sourceTrail: ['mind-state', 'repair-ledger'],
        },
        createdAt: 100,
      },
      {
        id: 'evt-2',
        decisionTraceId: 'mind:trace:2',
        turnId: 'turn-2',
        sessionId: 'session-2',
        origin: 'system',
        kind: 'presence-pulse-dispatched',
        payload: {
          summary: 'quiet accompaniment line held after focus stabilized',
        },
        createdAt: 200,
      },
    ] as any)

    expect(selected).toEqual({
      kind: 'presence-pulse-dispatched',
      decisionTraceId: 'mind:trace:2',
      summary: 'quiet accompaniment line held after focus stabilized',
      createdAt: 200,
    })
  })

  it('falls back to governance-normalized when higher-priority events lack summaries', () => {
    const selected = resolveRecentDrivingEventFromMindTurnEvents([
      {
        id: 'evt-1',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-1',
        sessionId: 'session-1',
        origin: 'system',
        kind: 'presence-pulse-dispatched',
        payload: {},
        createdAt: 300,
      },
      {
        id: 'evt-2',
        decisionTraceId: 'mind:trace:2',
        turnId: 'turn-2',
        sessionId: 'session-2',
        origin: 'system',
        kind: 'governance-normalized',
        payload: {
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
        },
        createdAt: 250,
      },
    ] as any)

    expect(selected).toEqual({
      kind: 'governance-normalized',
      decisionTraceId: 'mind:trace:2',
      summary: 'turn=care | truth=live-grounded | repair=none',
      createdAt: 250,
    })
  })

  it('prefers activeThreadId from provenance when building recent driving event query input', () => {
    const query = buildRecentDrivingEventQueryInput({
      phase: 'idle',
      playbackPhase: 'idle',
      speechEnergy: 0,
      prosodyIntensity: 0,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      runtimeDynamics: {
        profile: 'protective-watch',
        variationToken: 'presence-pulse|protective-watch',
        residentEmotion: 'tired',
        residentDelivery: 'gentle',
        residentFacialCue: 'soft-gaze',
        residentActionCue: 'comfort_sway',
        actionIntensity: 0.1,
        breathDrive: 0.2,
        focusDrive: 0.3,
        provenance: {
          watchMode: 'recovering',
          bodyState: 'recovering',
          continuityMode: 'protective-watch',
          thoughtStance: 'care',
          thoughtShouldSpeak: false,
          thoughtTension: 'late-night-drain',
          runtimeChannel: 'active-dialogue',
          runtimeSummary: 'runtime alignment held',
          activeThreadId: 'thread-main-1',
          activeThreadTitle: 'night thread',
          preferredPresence: 'attentive',
          selectedAction: 'warn',
          scene: 'chat',
          scenario: 'late-night-care',
        },
        eventPointers: {
          recentTransition: null,
          rationaleTags: ['recovering'],
          focusBeliefId: null,
          focusInquiryId: null,
          commitmentId: 'commitment-rest-1',
          runtimeThreadId: 'runtime-thread-rest-1',
          governorDrive: 'protect',
          governorIntentionId: 'governor-intention-rest-1',
          selectedThoughtThreadId: 'thought-thread-rest-1',
        },
      },
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      driverSummary: null,
      playbackTelemetry: null,
    } as any)

    expect(query).toEqual({
      activeThreadId: 'thread-main-1',
      limit: 12,
    })
  })

  it('builds a filtered local trace event chain from recent mind turn events', () => {
    const events = buildRecentDrivingTraceEventsFromMindTurnEvents([
      {
        id: 'evt-0',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-0',
        sessionId: 'session-0',
        origin: 'system',
        kind: 'dialogue-emitted',
        payload: {
          summary: 'visible reply rendered',
        },
        createdAt: 100,
      },
      {
        id: 'evt-1',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-1',
        sessionId: 'session-1',
        origin: 'system',
        kind: 'governance-normalized',
        payload: {
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
        },
        createdAt: 110,
      },
      {
        id: 'evt-2',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-2',
        sessionId: 'session-2',
        origin: 'system',
        kind: 'presence-pulse-dispatched',
        payload: {
          summary: 'protective watch dispatched',
        },
        createdAt: 120,
      },
      {
        id: 'evt-3',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-3',
        sessionId: 'session-3',
        origin: 'system',
        kind: 'person-state-updated',
        payload: {
          sourceTrail: ['mind-state', 'repair-ledger'],
        },
        createdAt: 130,
      },
      {
        id: 'evt-4',
        decisionTraceId: 'mind:trace:2',
        turnId: 'turn-4',
        sessionId: 'session-4',
        origin: 'system',
        kind: 'presence-pulse-dispatched',
        payload: {
          summary: 'different trace should be excluded',
        },
        createdAt: 140,
      },
    ] as any, 'mind:trace:1')

    expect(events).toEqual([
      {
        kind: 'governance-normalized',
        summary: 'turn=care | truth=live-grounded | repair=none',
        createdAt: 110,
      },
      {
        kind: 'presence-pulse-dispatched',
        summary: 'protective watch dispatched',
        createdAt: 120,
      },
      {
        kind: 'person-state-updated',
        summary: 'mind-state, repair-ledger',
        createdAt: 130,
      },
    ])
  })

  it('builds trace details for the filtered recent driving event chain', () => {
    const details = buildRecentDrivingTraceDetailsFromMindTurnEvents([
      {
        id: 'evt-1',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-1',
        sessionId: 'session-1',
        origin: 'system',
        kind: 'governance-normalized',
        payload: {
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
        },
        createdAt: 110,
      },
      {
        id: 'evt-2',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-2',
        sessionId: 'session-2',
        origin: 'system',
        kind: 'presence-pulse-dispatched',
        payload: {
          summary: 'protective watch dispatched',
          scenario: 'late-night-care',
          stance: 'care',
        },
        createdAt: 120,
      },
      {
        id: 'evt-3',
        decisionTraceId: 'mind:trace:1',
        turnId: 'turn-3',
        sessionId: 'session-3',
        origin: 'system',
        kind: 'person-state-updated',
        payload: {
          sourceTrail: ['mind-state', 'repair-ledger'],
        },
        createdAt: 130,
      },
    ] as any, 'mind:trace:1')

    expect(details).toEqual([
      {
        kind: 'governance-normalized',
        summary: 'turn=care | truth=live-grounded | repair=none',
        createdAt: 110,
        details: [
          { label: 'turnMode', value: 'care' },
          { label: 'truthState', value: 'live-grounded' },
          { label: 'repairState', value: 'none' },
        ],
      },
      {
        kind: 'presence-pulse-dispatched',
        summary: 'protective watch dispatched',
        createdAt: 120,
        details: [
          { label: 'summary', value: 'protective watch dispatched' },
          { label: 'scenario', value: 'late-night-care' },
          { label: 'stance', value: 'care' },
        ],
      },
      {
        kind: 'person-state-updated',
        summary: 'mind-state, repair-ledger',
        createdAt: 130,
        details: [
          { label: 'sourceTrail', value: 'mind-state, repair-ledger' },
        ],
      },
    ])
  })

  it('builds a recent driving trace record summary from memory decision traces', () => {
    const summary = buildRecentDrivingTraceRecordSummaryFromMemoryDecisionTraces([
      {
        decisionTraceId: 'mind:trace:other',
        activeThreadId: 'thread-other',
        governance: {
          turnMode: 'reflect',
          truthState: 'remembered',
          repairState: 'open',
        },
        memoryResolutionLedger: {
          finalSurfacePolicy: 'internal-only',
          closureState: 'inward-only',
          suppressionTags: ['other-thread'],
        },
      },
      {
        decisionTraceId: 'mind:trace:1',
        activeThreadId: 'thread-main',
        governance: {
          turnMode: 'care',
          truthState: 'live-grounded',
          repairState: 'none',
        },
        memoryResolutionLedger: {
          finalSurfacePolicy: 'procedural-carry',
          closureState: 'grounded-recall',
          suppressionTags: ['nearby-thread', 'stable-core'],
        },
      },
    ] as any, 'mind:trace:1')

    expect(summary).toEqual({
      decisionTraceId: 'mind:trace:1',
      activeThreadId: 'thread-main',
      turnMode: 'care',
      truthState: 'live-grounded',
      repairState: 'none',
      finalSurfacePolicy: 'procedural-carry',
      closureState: 'grounded-recall',
      suppressionTags: ['nearby-thread', 'stable-core'],
    })
  })

  it('returns null when no memory decision trace matches the recent driving trace id', () => {
    expect(buildRecentDrivingTraceRecordSummaryFromMemoryDecisionTraces([
      {
        decisionTraceId: 'mind:trace:other',
        activeThreadId: 'thread-other',
      },
    ] as any, 'mind:trace:missing')).toBeNull()
  })
})
