import { createPinia, setActivePinia } from 'pinia'
import { describe, expect, it } from 'vitest'

import {
  applyHitTestTracePayload,
  applySnapshotRecord,
  applyThreeRenderTracePayload,
  applyVrmUpdateTracePayload,
  createDefaultStageHitTestDiagnostics,
  createDefaultStageResourceSnapshotDiagnostics,
  createDefaultStageSpeechEmbodimentDiagnostics,
  createDefaultStageThreeRenderDiagnostics,
  createDefaultStageVrmUpdateDiagnostics,
  pushTraceHistory,
  TRACE_HISTORY_LIMIT,
  useStageThreeRuntimeDiagnosticsStore,
} from './stage-three-runtime-diagnostics'

describe('stage three runtime diagnostics helpers', () => {
  setActivePinia(createPinia())

  it('aggregates three render payloads', () => {
    const next = applyThreeRenderTracePayload(createDefaultStageThreeRenderDiagnostics(), {
      drawCalls: 12,
      geometries: 8,
      lines: 3,
      points: 2,
      textures: 5,
      triangles: 144,
      ts: 10,
    })

    expect(next.renderCount).toBe(1)
    expect(next.drawCalls).toBe(12)
    expect(next.points).toBe(2)
    expect(next.lines).toBe(3)
    expect(next.triangles).toBe(144)
  })

  it('aggregates vrm update and hit-test payloads', () => {
    const vrmUpdate = applyVrmUpdateTracePayload(createDefaultStageVrmUpdateDiagnostics(), {
      activeActionCue: 'observe_focus',
      activeActionCueSource: 'segment',
      activeCuePreferredExpressionAliases: ['CalmInspect'],
      activeCuePreferredMotionAliases: ['ObserveSoft'],
      activeCueVrmActionFadeMs: 220,
      activeCueVrmExpressionBlendMs: 260,
      activeFacialCue: 'focused',
      activeFacialCueSource: 'segment',
      animationMixerMs: 1,
      actionIntensity: 0.44,
      blinkAndSaccadeMs: 2,
      deltaMs: 16.7,
      durationMs: 9.5,
      emoteMs: 3,
      expressionIntensity: 0.62,
      expressionMs: 4,
      facialCueIntensity: 0.58,
      humanoidMs: 5,
      lipSyncMs: 6,
      lookAtMs: 7,
      springBoneMs: 8,
      ts: 20,
      visemeIntensity: 0.4,
      vrmFrameHookMs: 9,
    })

    const hitTest = applyHitTestTracePayload(createDefaultStageHitTestDiagnostics(), {
      durationMs: 4.5,
      radius: 25,
      readHeight: 20,
      readWidth: 30,
      ts: 30,
    })

    expect(vrmUpdate.frameCount).toBe(1)
    expect(vrmUpdate.totalMs).toBe(9.5)
    expect(vrmUpdate.springBoneMs).toBe(8)
    expect(vrmUpdate.lastConsumedExpressionAliases).toEqual(['CalmInspect'])
    expect(vrmUpdate.lastConsumedMotionAliases).toEqual(['ObserveSoft'])
    expect(vrmUpdate.lastConsumedVrmActionFadeMs).toBe(220)
    expect(vrmUpdate.lastConsumedVrmExpressionBlendMs).toBe(260)
    expect(hitTest.readCount).toBe(1)
    expect(hitTest.totalDurationMs).toBe(4.5)
    expect(hitTest.lastReadWidth).toBe(30)
  })

  it('keeps resource snapshot history bounded', () => {
    let history: ReturnType<typeof createDefaultStageResourceSnapshotDiagnostics>['history'] = []
    for (let index = 0; index < TRACE_HISTORY_LIMIT + 4; index += 1) {
      history = pushTraceHistory(history, {
        phase: 'after-load',
        ts: index,
      })
    }

    expect(history).toHaveLength(TRACE_HISTORY_LIMIT)
    expect(history[0]?.ts).toBe(4)

    const snapshots = applySnapshotRecord(createDefaultStageResourceSnapshotDiagnostics(), {
      phase: 'before-dispose',
      ts: 99,
    })

    expect(snapshots.lastBeforeDispose?.ts).toBe(99)
    expect(snapshots.history).toHaveLength(1)
  })

  it('creates an empty speech embodiment diagnostics snapshot for renderer devtools', () => {
    expect(createDefaultStageSpeechEmbodimentDiagnostics()).toEqual({
      phase: 'idle',
      playbackPhase: 'idle',
      speechEnergy: 0,
      prosodyIntensity: 0,
      emphasisLevel: 0,
      cadencePulse: 0,
      visemeIntensity: 0,
      articulation: null,
      runtimeDynamics: null,
      recentDrivingEvent: null,
      recentDrivingTraceRecord: null,
      recentDrivingTraceEvents: [],
      recentDrivingTraceDetails: [],
      traceSummary: null,
      driverSummary: null,
      live2dExecution: null,
      rendererAlignment: {
        live2d: null,
        vrm: null,
      },
      rendererDriftSummary: null,
      articulationSummary: null,
      authoritySummary: null,
      convergence: null,
      speechEvidence: null,
      cueMicroSummary: null,
      driverExecutionSummary: null,
      visemeHintsSummary: null,
      playbackTelemetry: null,
    })
  })

  it('stores speech embodiment diagnostics snapshots for renderer devtools consumption', () => {
    const store = useStageThreeRuntimeDiagnosticsStore()

    store.setSpeechEmbodiment({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0.18,
          O: 0.08,
          U: 0.12,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: {
        profile: 'protective-watch',
        variationToken: 'presence-pulse|protective-watch',
        residentEmotion: 'tired',
        residentDelivery: 'gentle',
        residentFacialCue: 'soft-gaze',
        residentActionCue: 'comfort_sway',
        actionIntensity: 0.1,
        breathDrive: 0.2,
        focusDrive: 0.3,
        provenance: {
          watchMode: 'recovering',
          bodyState: 'settled',
          continuityMode: 'ambient-covision',
          thoughtStance: 'care',
          thoughtShouldSpeak: false,
          thoughtTension: 'focused-flow',
          runtimeChannel: 'active-dialogue',
          runtimeSummary: 'runtime alignment held',
          activeThreadId: 'runtime-thread-rest-1',
          activeThreadTitle: 'late-night care',
          preferredPresence: 'gentle-watch',
          selectedAction: 'comfort_sway',
          personaBiasSummary: 'protective-watch favored due to late-night care pressure',
          personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
          scene: 'coding',
          scenario: 'coding',
        },
        eventPointers: {
          recentTransition: {
            fromWatchMode: 'symbiotic-vision',
            toWatchMode: 'recovering',
            fromScenario: 'chat',
            durationMs: 90_000,
            reason: 'host fatigue detected during late-night care',
            occurredAt: 1_234,
          },
          rationaleTags: ['recovering', 'late-night-fatigue'],
          focusBeliefId: 'belief-rest-1',
          focusInquiryId: null,
          commitmentId: 'commitment-rest-1',
          runtimeThreadId: 'runtime-thread-rest-1',
          governorDrive: 'protect',
          governorIntentionId: 'governor-intention-rest-1',
          selectedThoughtThreadId: 'thought-thread-rest-1',
        },
      },
      recentDrivingEvent: {
        kind: 'person-state-updated',
        decisionTraceId: 'mind:rest:1',
        summary: 'protective-watch settled after fatigue pressure rose',
        createdAt: 2_468,
      },
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:rest:1',
        activeThreadId: 'runtime-thread-rest-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: ['late-night-fatigue'],
      },
      recentDrivingTraceEvents: [
        {
          kind: 'governance-normalized',
          summary: 'turn=care | truth=live-grounded | repair=none',
          createdAt: 2_430,
        },
        {
          kind: 'presence-pulse-dispatched',
          summary: 'protective watch dispatched',
          createdAt: 2_450,
        },
        {
          kind: 'person-state-updated',
          summary: 'protective-watch settled after fatigue pressure rose',
          createdAt: 2_468,
        },
      ],
      recentDrivingTraceDetails: [],
      traceSummary: {
        decisionTraceId: 'mind:rest:1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        activeThreadId: 'runtime-thread-rest-1',
        suppressionTags: ['late-night-fatigue'],
        latestEventSummary: 'protective-watch settled after fatigue pressure rose',
        segmentBinding: {
          matched: true,
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          matchedSources: ['prosody-authority', 'timeline-projection'],
        },
      },
      rendererAlignment: {
        live2d: {
          predicted: 'CalmInspect',
          actual: 'CalmInspect',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: 'calm',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: null,
          driverSource: null,
        },
      },
      rendererDriftSummary: null,
      articulationSummary: {
        voice: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemes: 'A:0.66, closed:0.41, E:0.24',
      },
      authoritySummary: {
        cueId: 'segment-vrm-1',
        segmentId: 'segment-vrm-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['face', 'motion', 'lipsync'],
        matchedSources: ['prosody-authority', 'timeline-projection'],
        bindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:yes',
        matchSummary: 'face:yes motion:yes lipsync:yes',
        settleSummary: 'segment=segment-vrm-1 | target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection',
      },
      speechEvidence: {
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      },
      cueMicroSummary: {
        cueId: 'segment-vrm-1',
        cueText: '继续看这里。',
        cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        personaStyle: null,
        timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      driverSummary: {
        rendererTarget: 'vrm',
        face: {
          cue: 'focused',
          source: 'prosody-authority',
          confidence: 0.94,
          segmentId: 'segment-vrm-1',
        },
        motion: null,
        lipsync: null,
      },
      driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
      live2dExecution: {
        activeExpression: {
          name: 'CalmInspect',
          reason: 'preferred',
          score: 11.4,
          segmentId: 'segment-vrm-1',
        },
        activeMotion: {
          group: 'ObserveSoft',
          index: 1,
        },
        cue: {
          emotion: 'thinking',
          facialCue: 'focus',
          preferredExpressionAliases: ['CalmInspect'],
          live2dFacialReleaseMs: 320,
          live2dMotionFollowThroughMs: 440,
        },
      },
      visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-vrm-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          sources: ['prosody-authority', 'timeline-projection'],
          faceSegmentMatched: true,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-vrm-1',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: {
            preferredExpressionAliases: ['CalmInspect'],
            preferredMotionAliases: ['ObserveSoft'],
          },
          rendererSettle: {
            live2dFacialReleaseMs: 320,
            live2dMotionFollowThroughMs: 440,
            vrmActionFadeMs: 280,
            vrmExpressionBlendMs: 360,
          },
        },
        drivers: {
          face: {
            emotion: 'thinking',
            facialCue: 'focused',
            intensity: 0.52,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.94,
            preUtteranceCue: 'steady-inhale',
            postUtteranceCue: 'soft-release',
            segmentId: 'segment-vrm-1',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-vrm-1',
            visemeHints: [
              { segmentId: 'segment-vrm-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-vrm-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
            ],
          },
          motion: {
            idleBase: 'idle_settle',
            attentionMode: 'attentive',
            actionCue: 'observe_focus',
            intensity: 0.34,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-vrm-1',
          },
        },
      },
    })

    expect(store.speechEmbodiment).toEqual({
      phase: 'playing',
      playbackPhase: 'playing',
      speechEnergy: 0.44,
      prosodyIntensity: 0.52,
      emphasisLevel: 0.38,
      cadencePulse: 0.22,
      visemeIntensity: 0.4,
      articulation: {
        active: true,
        progress: 0.42,
        openness: 0.36,
        jawOpen: 0.28,
        lipClosure: 0.44,
        lipSpread: 0.18,
        lipRound: 0.12,
        visemes: {
          A: 0.66,
          E: 0.24,
          I: 0.18,
          O: 0.08,
          U: 0.12,
          closed: 0.41,
        },
        voice: {
          provider: 'test',
          model: null,
          voiceId: 'crisp-zh',
          voiceName: null,
          language: 'zh-CN',
          gender: null,
          rateMultiplier: 1,
          pitchDelta: 0,
          closureBias: 0.84,
          roundBias: 0.1,
          spreadBias: 0.1,
          jawBias: 0.12,
          consonantPrecision: 0.9,
          vowelLegato: 0.3,
        },
      },
      runtimeDynamics: {
        profile: 'protective-watch',
        variationToken: 'presence-pulse|protective-watch',
        residentEmotion: 'tired',
        residentDelivery: 'gentle',
        residentFacialCue: 'soft-gaze',
        residentActionCue: 'comfort_sway',
        actionIntensity: 0.1,
        breathDrive: 0.2,
        focusDrive: 0.3,
        provenance: {
          watchMode: 'recovering',
          bodyState: 'settled',
          continuityMode: 'ambient-covision',
          thoughtStance: 'care',
          thoughtShouldSpeak: false,
          thoughtTension: 'focused-flow',
          runtimeChannel: 'active-dialogue',
          runtimeSummary: 'runtime alignment held',
          activeThreadId: 'runtime-thread-rest-1',
          activeThreadTitle: 'late-night care',
          preferredPresence: 'gentle-watch',
          selectedAction: 'comfort_sway',
          personaBiasSummary: 'protective-watch favored due to late-night care pressure',
          personaOpeningGuidance: 'Open gently, but keep the opening bounded and real.',
          scene: 'coding',
          scenario: 'coding',
        },
        eventPointers: {
          recentTransition: {
            fromWatchMode: 'symbiotic-vision',
            toWatchMode: 'recovering',
            fromScenario: 'chat',
            durationMs: 90_000,
            reason: 'host fatigue detected during late-night care',
            occurredAt: 1_234,
          },
          rationaleTags: ['recovering', 'late-night-fatigue'],
          focusBeliefId: 'belief-rest-1',
          focusInquiryId: null,
          commitmentId: 'commitment-rest-1',
          runtimeThreadId: 'runtime-thread-rest-1',
          governorDrive: 'protect',
          governorIntentionId: 'governor-intention-rest-1',
          selectedThoughtThreadId: 'thought-thread-rest-1',
        },
      },
      recentDrivingEvent: {
        kind: 'person-state-updated',
        decisionTraceId: 'mind:rest:1',
        summary: 'protective-watch settled after fatigue pressure rose',
        createdAt: 2_468,
      },
      recentDrivingTraceRecord: {
        decisionTraceId: 'mind:rest:1',
        activeThreadId: 'runtime-thread-rest-1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        suppressionTags: ['late-night-fatigue'],
      },
      recentDrivingTraceEvents: [
        {
          kind: 'governance-normalized',
          summary: 'turn=care | truth=live-grounded | repair=none',
          createdAt: 2_430,
        },
        {
          kind: 'presence-pulse-dispatched',
          summary: 'protective watch dispatched',
          createdAt: 2_450,
        },
        {
          kind: 'person-state-updated',
          summary: 'protective-watch settled after fatigue pressure rose',
          createdAt: 2_468,
        },
      ],
      recentDrivingTraceDetails: [],
      traceSummary: {
        decisionTraceId: 'mind:rest:1',
        turnMode: 'care',
        truthState: 'live-grounded',
        repairState: 'none',
        finalSurfacePolicy: 'procedural-carry',
        closureState: 'grounded-recall',
        activeThreadId: 'runtime-thread-rest-1',
        suppressionTags: ['late-night-fatigue'],
        latestEventSummary: 'protective-watch settled after fatigue pressure rose',
        segmentBinding: {
          matched: true,
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          matchedSources: ['prosody-authority', 'timeline-projection'],
        },
      },
      rendererAlignment: {
        live2d: {
          predicted: 'CalmInspect',
          actual: 'CalmInspect',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: 'focused',
          driverSource: 'prosody-authority',
        },
        vrm: {
          predicted: 'calm',
          actual: 'calm',
          reason: 'preferred',
          status: 'aligned',
          driftKind: 'aligned',
          driverCue: null,
          driverSource: null,
        },
      },
      rendererDriftSummary: null,
      articulationSummary: {
        voice: 'zh-CN | closure=0.84 | precision=0.90',
        topVisemes: 'A:0.66, closed:0.41, E:0.24',
      },
      authoritySummary: {
        cueId: 'segment-vrm-1',
        segmentId: 'segment-vrm-1',
        rendererTarget: 'vrm',
        matchedDrivers: ['face', 'motion', 'lipsync'],
        matchedSources: ['prosody-authority', 'timeline-projection'],
        bindingSummary: 'target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection | matches=face:yes motion:yes lipsync:yes',
        matchSummary: 'face:yes motion:yes lipsync:yes',
        settleSummary: 'segment=segment-vrm-1 | target=vrm | drivers=face, motion, lipsync | sources=prosody-authority, timeline-projection',
      },
      speechEvidence: {
        voiceSummary: 'zh-CN | closure=0.84 | precision=0.90',
        authorityMatchSummary: 'face:yes motion:yes lipsync:yes',
        topVisemeSummary: 'A:0.66, closed:0.41, E:0.24',
        cueSummary: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        cueIdentityPresent: true,
        cueProsodyPresent: true,
        personaStyleSummary: 'observe-first | prosody=-0.07 beat=-0.06 mouth=-0.04 head=+0.08',
        timingSummary: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
        driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
        visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      },
      cueMicroSummary: {
        cueId: 'segment-vrm-1',
        cueText: '继续看这里。',
        cue: 'focused / observe_focus | prosody=0.36 mouth=0.28 head=0.32',
        personaStyle: null,
        timing: 'facial=320 action=240 emotion=360 | segment-start | soft-interrupt | hold',
      },
      driverSummary: {
        rendererTarget: 'vrm',
        face: {
          cue: 'focused',
          source: 'prosody-authority',
          confidence: 0.94,
          segmentId: 'segment-vrm-1',
        },
        motion: null,
        lipsync: null,
      },
      live2dExecution: {
        activeExpression: {
          name: 'CalmInspect',
          reason: 'preferred',
          score: 11.4,
          segmentId: 'segment-vrm-1',
        },
        activeMotion: {
          group: 'ObserveSoft',
          index: 1,
        },
        cue: {
          emotion: 'thinking',
          facialCue: 'focus',
          preferredExpressionAliases: ['CalmInspect'],
          live2dFacialReleaseMs: 320,
          live2dMotionFollowThroughMs: 440,
        },
      },
      driverExecutionSummary: 'face=thinking/focused@0.52 hold=320 pre=steady-inhale post=soft-release src=prosody-authority conf=0.94 | motion=observe_focus mode=attentive idle=idle_settle@0.34 hold=240 src=timeline-projection conf=0.88 | lipsync=energy-phoneme-hybrid phase=playing',
      visemeHintsSummary: 'I:0.35@0.94 | closed:0.75@0.89',
      playbackTelemetry: {
        actualDurationMs: 220,
        plannedDurationMs: 220,
        driftMs: 0,
        settleMs: 220,
        stopReason: null,
        rendererTarget: 'vrm',
        driverAuthority: {
          segmentId: 'segment-vrm-1',
          rendererTarget: 'vrm',
          matchedDrivers: ['face', 'motion', 'lipsync'],
          sources: ['prosody-authority', 'timeline-projection'],
          faceSegmentMatched: true,
          motionSegmentMatched: true,
          lipsyncSegmentMatched: true,
        },
        cue: {
          id: 'segment-vrm-1',
          text: '继续看这里。',
          prosodyWeight: 0.36,
          mouthWeight: 0.28,
          headWeight: 0.32,
          facialHoldMs: 320,
          actionHoldMs: 240,
          emotionHoldMs: 360,
          facialCue: 'focused',
          actionCue: 'observe_focus',
          actionWindow: 'segment-start',
          interruptMode: 'soft-interrupt',
          settleMode: 'hold',
          rendererHints: {
            preferredExpressionAliases: ['CalmInspect'],
            preferredMotionAliases: ['ObserveSoft'],
          },
          rendererSettle: {
            live2dFacialReleaseMs: 320,
            live2dMotionFollowThroughMs: 440,
            vrmActionFadeMs: 280,
            vrmExpressionBlendMs: 360,
          },
        },
        drivers: {
          face: {
            emotion: 'thinking',
            facialCue: 'focused',
            intensity: 0.52,
            holdMs: 320,
            source: 'prosody-authority',
            confidence: 0.94,
            preUtteranceCue: 'steady-inhale',
            postUtteranceCue: 'soft-release',
            segmentId: 'segment-vrm-1',
          },
          lipsync: {
            mode: 'energy-phoneme-hybrid',
            playbackPhase: 'playing',
            segmentId: 'segment-vrm-1',
            visemeHints: [
              { segmentId: 'segment-vrm-1', viseme: 'I', weight: 0.35, source: 'prosody-authority', confidence: 0.94 },
              { segmentId: 'segment-vrm-1', viseme: 'closed', weight: 0.75, source: 'prosody-authority', confidence: 0.89 },
            ],
          },
          motion: {
            idleBase: 'idle_settle',
            attentionMode: 'attentive',
            actionCue: 'observe_focus',
            intensity: 0.34,
            holdMs: 240,
            source: 'timeline-projection',
            confidence: 0.88,
            segmentId: 'segment-vrm-1',
          },
        },
      },
    })
  })
})
