import { describe, expect, it } from 'vitest'

import {
  buildAlicizationAffectiveResidueMemory,
  buildAlicizationBrowserAffectiveResidueMemory,
} from './alicization-affective-residue-memory'

describe('alicization-affective-residue-memory', () => {
  it('builds main-runtime affective residue from relationship outcomes and continuity pressure', () => {
    const residue = buildAlicizationAffectiveResidueMemory({
      now: 1_700_000_000_000,
      recentRelationshipOutcomes: [{
        id: 'relationship-outcome-1',
        cardId: 'default',
        decisionTraceId: 'trace-1',
        turnId: 'turn-1',
        sessionId: 'session-1',
        outcomeKind: 'repair',
        closenessDelta: 0.12,
        trustDelta: 0.22,
        burdenDelta: 0.64,
        repairDelta: 0.7,
        misreadDelta: -0.24,
        boundaryDelta: -0.18,
        openLoopDelta: 0.1,
        summary: 'Repair landed, but the host was tired and needed less pressure.',
        sourceSignals: ['repair before closeness', 'host tired'],
        createdAt: 1_700_000_000_000,
      } as any],
      recentMemoryReflections: [{
        id: 'reflection-1',
        cardId: 'default',
        decisionTraceId: 'trace-1',
        turnId: 'turn-1',
        targetScope: 'relationship',
        sourceKind: 'relationship-outcome',
        status: 'confirmed',
        summary: 'Repair should stay low-pressure because burden is active.',
        lesson: 'Protect rest before reopening warmth.',
        sourceSignals: ['burden', 'repair'],
        confidence: 0.86,
        createdAt: 1_700_000_000_000,
        updatedAt: 1_700_000_000_000,
      } as any],
      personStateEvolutionSummary: {
        latestDoctrine: 'Repair before closeness returns.',
        latestBurdenLine: 'The host is easier to crowd right now.',
        latestTrustMeaning: 'Trust rises when pressure stays low.',
        repairShift: 0.74,
        burdenShift: 0.66,
        trustShift: 0.36,
        recentSummaries: ['Repair is still active and warmth must wait.'],
      } as any,
      personalityContinuityState: {
        currentRegime: 'late-night-care',
        repairPosture: 'repair-first',
        energyProfile: 'rest-sensitive',
        autonomyPosture: 'protect-space',
        trustStage: 'warming',
        closenessPosture: 'measured-room',
        rhythmState: {
          cadenceMode: 'cooldown',
          restMode: 'rest-protective',
          moodLabel: 'afterglow',
          memoryResonance: 0.42,
          summary: 'cooldown with rest protection',
          rationale: ['Protect rest before warmth.'],
        },
      },
      hostPersonModel: {
        summary: 'The host trusts low-pressure repair.',
        routines: [],
        sensitivities: [],
        repairTriggers: [],
        trustLadder: {
          stage: 'warming',
          score: 0.72,
          rationale: 'Trust rises when pressure stays low.',
        },
        preferredClosenessByContext: [],
        recurrentBurdens: ['The host is easier to crowd right now.'],
        narrative: [],
        updatedAt: 1_700_000_000_000,
      },
    })

    expect(residue.version).toBe('affective-residue-memory-v1')
    expect(residue.residues.map(item => item.kind)).toEqual(expect.arrayContaining([
      'repair',
      'burden',
      'rest-protective',
      'trust',
    ]))
    expect(residue.relationshipCadence.cadenceMode).toBe('cooldown')
    expect(residue.relationshipCadence.shouldProtectRest).toBe(true)
    expect(residue.relationshipCadence.shouldDelayWarmth).toBe(true)
    expect(residue.summary).not.toMatch(/我会一直在|慢慢来|先抱抱/u)
  })

  it('builds browser fallback affective residue from lightweight episodic carry without browser-only wording shells', () => {
    const residue = buildAlicizationBrowserAffectiveResidueMemory({
      now: 1_700_000_123_456,
      hostPersonModel: {
        summary: 'The host is easier to crowd at night but trust is growing.',
        routines: [],
        sensitivities: [],
        repairTriggers: [],
        trustLadder: {
          stage: 'warming',
          score: 0.7,
          rationale: 'Trust grows when warmth stays measured.',
        },
        preferredClosenessByContext: [],
        recurrentBurdens: ['Late-night pressure crowds the host quickly.'],
        narrative: [],
        updatedAt: 1_700_000_123_456,
      },
      recollectionForeground: {
        mode: 'relationship-history',
        summary: 'Recent continuity still carries a warm repair seam.',
      },
      recentEpisodicEvents: [{
        id: 'event-1',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-1',
        sessionId: 'session-1',
        sourceKind: 'reply',
        provenance: 'observed',
        occurredAt: 1_700_000_100_000,
        whereSummary: 'chat',
        withWhom: ['host'],
        threadAnchor: 'relationship repair',
        whatHappened: 'Late night repair landed and the afterglow stayed warm.',
        felt: 'warm',
        emotionTags: ['warm'],
        whatChanged: 'The seam felt more stable.',
        relationshipMeaning: 'Repair before pressure.',
        lesson: 'Protect rest before widening warmth.',
        sourceSummary: 'late-night repair',
        confidence: 0.84,
        salience: 0.72,
        sceneAttachment: 0.58,
        consolidationPriority: 0.64,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['late night', 'repair'],
        createdAt: 1_700_000_100_000,
        updatedAt: 1_700_000_100_000,
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }, {
        id: 'event-2',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-2',
        sessionId: 'session-1',
        sourceKind: 'reply',
        provenance: 'observed',
        occurredAt: 1_700_000_110_000,
        whereSummary: 'chat',
        withWhom: ['host'],
        threadAnchor: 'relationship repair',
        whatHappened: 'Another late night repair had to stay gentle because the host was tired and needed rest.',
        felt: 'careful',
        emotionTags: ['careful'],
        whatChanged: 'The line stayed low-pressure.',
        relationshipMeaning: 'Keep repair ahead of closeness.',
        lesson: 'Protect rest and do not crowd the host.',
        sourceSummary: 'late-night careful repair',
        confidence: 0.8,
        salience: 0.68,
        sceneAttachment: 0.56,
        consolidationPriority: 0.62,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['late night', 'repair', 'rest'],
        createdAt: 1_700_000_110_000,
        updatedAt: 1_700_000_110_000,
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }, {
        id: 'event-3',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-3',
        sessionId: 'session-1',
        sourceKind: 'reply',
        provenance: 'observed',
        occurredAt: 1_700_000_120_000,
        whereSummary: 'chat',
        withWhom: ['host'],
        threadAnchor: 'relationship repair',
        whatHappened: 'The late night seam held again only because the line protected rest and stayed gentle.',
        felt: 'steady',
        emotionTags: ['steady'],
        whatChanged: 'The repair cadence became more stable.',
        relationshipMeaning: 'Rest protection keeps the warmth from crowding.',
        lesson: 'Late-night warmth must stay low-pressure.',
        sourceSummary: 'rest-protected repair',
        confidence: 0.82,
        salience: 0.7,
        sceneAttachment: 0.57,
        consolidationPriority: 0.63,
        relationshipShift: null,
        derivedFrom: [],
        tags: ['late night', 'repair', 'rest'],
        createdAt: 1_700_000_120_000,
        updatedAt: 1_700_000_120_000,
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
      selfEvolution: {
        version: 'self-evolution-kernel-v1',
        updatedAt: 1_700_000_123_456,
        evolutionMomentum: 0.68,
        learningReadiness: 0.74,
        contradictionPressure: 0,
        revisionPressure: 0.32,
        autobiographicalStability: 0.58,
        dominantTrajectory: 'repair stays active',
        relationshipDoctrine: 'Repair should settle before closeness expands.',
        latestInflection: 'The last seam held because pressure stayed low.',
        burdenLine: 'Protect rest before adding more closeness.',
        trustMeaning: 'Measured warmth is being trusted.',
        nextLearningAction: 'verify',
        nextLearningReason: 'The seam should be checked again before it becomes doctrine.',
        shouldRecord: false,
        shouldReflect: false,
        shouldVerify: true,
        shouldRevise: false,
        shouldInternalize: false,
        activeLearningFocuses: ['relationship repair'],
        sourceSignals: ['late-night repair'],
        summary: 'Repair remains active and needs verification.',
      },
    })

    expect(residue.version).toBe('affective-residue-memory-v1')
    expect(residue.dominantResidueKind).toMatch(/repair|rest-protective|trust/u)
    expect(residue.relationshipCadence.cadenceMode).toBe('cooldown')
    expect(residue.relationshipCadence.shouldProtectRest).toBe(true)
    expect(residue.summary).not.toContain('Browser fallback')
  })

  it('does not derive main-runtime residue from reflection prose alone', () => {
    const residue = buildAlicizationAffectiveResidueMemory({
      now: 1_700_000_222_000,
      recentMemoryReflections: [{
        id: 'reflection-prose-only',
        cardId: 'default',
        decisionTraceId: 'trace-prose-only',
        turnId: 'turn-prose-only',
        sessionId: 'session-prose-only',
        targetScope: 'task',
        sourceKind: 'maintenance',
        status: 'confirmed',
        summary: 'repair trust rest warm closeness burden',
        lesson: 'repair trust rest warm closeness burden',
        supportingFactIds: [],
        supportingOutcomeIds: [],
        confidence: 0.9,
        createdAt: 1_700_000_222_000,
        updatedAt: 1_700_000_222_000,
        confirmedAt: 1_700_000_222_000,
        deniedAt: null,
      }],
    })

    expect(residue.dominantResidueKind).toBeNull()
    expect(residue.residues).toEqual([])
  })

  it('does not derive browser fallback residue from episodic prose alone', () => {
    const residue = buildAlicizationBrowserAffectiveResidueMemory({
      now: 1_700_000_333_000,
      recentEpisodicEvents: [{
        id: 'event-prose-only',
        cardId: 'default',
        decisionTraceId: null,
        turnId: 'turn-prose-only',
        sessionId: 'session-prose-only',
        sourceKind: 'reply',
        provenance: 'observed',
        occurredAt: 1_700_000_333_000,
        whereSummary: 'chat',
        withWhom: ['host'],
        threadAnchor: null,
        whatHappened: 'late night repair stayed warm and protected rest',
        felt: 'warm repair rest',
        emotionTags: [],
        whatChanged: null,
        relationshipMeaning: 'repair warm rest trust',
        lesson: 'repair warm rest trust',
        sourceSummary: null,
        confidence: 0.9,
        salience: 0.8,
        sceneAttachment: 0.2,
        consolidationPriority: 0.2,
        relationshipShift: null,
        derivedFrom: [],
        tags: [],
        createdAt: 1_700_000_333_000,
        updatedAt: 1_700_000_333_000,
        lastRecalledAt: null,
        recallCount: 0,
        reconsolidationCount: 0,
        latestReconsolidation: null,
      }],
    })

    expect(residue.dominantResidueKind).toBeNull()
    expect(residue.residues).toEqual([])
  })
})
