import { describe, expect, it } from 'vitest'

import { deriveAlicizationBrowserMainParitySummary } from './alicization-browser-main-parity'
import { normalizeAlicizationDerivedMindStateBundle } from './alicization-transport-contracts'

describe('alicization-browser-main-parity', () => {
  it('passes when main and browser shared surfaces stay aligned', () => {
    const summary = deriveAlicizationBrowserMainParitySummary({
      mainBundle: {
        version: 'derived-mind-state-bundle-v1',
        source: 'main-runtime',
        producedAt: 1,
        hostPersonModel: {
          summary: 'trusted',
          routines: [],
          sensitivities: [],
          repairTriggers: [],
          trustLadder: {
            stage: 'warming',
            score: 0.7,
            rationale: 'steady warmth',
          },
          preferredClosenessByContext: [],
          recurrentBurdens: [],
          narrative: [],
          updatedAt: 1,
        },
        selfEvolution: {
          version: 'self-evolution-kernel-v1',
          updatedAt: 1,
          evolutionMomentum: 0.7,
          learningReadiness: 0.8,
          contradictionPressure: 0,
          revisionPressure: 0,
          autobiographicalStability: 0.7,
          dominantTrajectory: 'steady line',
          relationshipDoctrine: 'repair first',
          latestInflection: 'stable',
          burdenLine: null,
          trustMeaning: null,
          nextLearningAction: 'reflect',
          nextLearningReason: null,
          shouldRecord: false,
          shouldReflect: true,
          shouldVerify: false,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['repair'],
          sourceSignals: [],
          summary: 'steady line',
        },
        affectiveResidue: {
          version: 'affective-residue-memory-v1',
          updatedAt: 1,
          residues: [],
          dominantResidueKind: 'repair',
          afterglowPressure: 0.1,
          repairPressure: 0.6,
          burdenPressure: 0.1,
          trustPressure: 0.3,
          restProtectivePressure: 0.2,
          relationshipCadence: {
            cadenceMode: 'cooldown',
            distancePosture: 'measured-room',
            companionshipDensity: 0.2,
            repairRecovery: 0.6,
            overreachRisk: 0.2,
            fatigueGuard: 0.2,
            afterglowCarry: 0.1,
            shouldDelayWarmth: true,
            shouldProtectRest: false,
            reasonTags: [],
            summary: 'repair first',
          },
          sourceSignals: [],
          summary: 'repair first',
        },
        learningExecutionState: {
          currentTaskId: null,
          currentStatus: 'scheduled',
          currentAttemptCount: 0,
          currentMaxAttempts: 0,
          currentNextRetryAt: null,
          currentBlockedReason: null,
          currentFailureKind: null,
          nextLearningAction: 'reflect',
          shouldRecord: false,
          shouldReflect: true,
          shouldVerify: false,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['repair'],
          queuedTaskCount: 1,
          runningTaskCount: 0,
          blockedTaskCount: 0,
          recentTaskIds: [],
          lastCompletedTaskId: null,
          lastCompletedAction: null,
          lastCompletedSummary: null,
          lastFailureTaskId: null,
          lastFailureKind: null,
          lastFailureReason: null,
          lastFailureNextRetryAt: null,
          updatedAt: 1,
        },
        recallLatencyPolicy: {
          version: 'recall-latency-policy-v1',
          budgetClass: 'realtime-reply',
          latencyClass: 'balanced',
          recallAction: 'stable-core-only',
          degradeReason: null,
          domainBudgets: [],
          hotPathKey: null,
          shouldUseHotCache: true,
          shouldPrefetch: false,
          shouldAvoidDeepExpansion: true,
          shouldEmitFollowUpAffordance: false,
          confidence: 0.8,
          reasonTags: [],
          summary: 'balanced',
        },
        recollectionPlan: {
          opening: 'runtime seam',
        } as any,
        recollectionSpeechPlan: {
          surfaceMode: 'procedural-carry',
        } as any,
        memoryDeliberation: {
          surfacePolicy: 'procedural-carry',
        },
        dialogueRhythm: {
          relationshipDoctrine: 'repair first',
        },
        summary: 'steady line',
      },
      browserBundle: {
        version: 'derived-mind-state-bundle-v1',
        source: 'browser-fallback',
        producedAt: 2,
        hostPersonModel: {
          summary: 'trusted',
          routines: [],
          sensitivities: [],
          repairTriggers: [],
          trustLadder: {
            stage: 'warming',
            score: 0.7,
            rationale: 'steady warmth',
          },
          preferredClosenessByContext: [],
          recurrentBurdens: [],
          narrative: [],
          updatedAt: 1,
        },
        selfEvolution: {
          version: 'self-evolution-kernel-v1',
          updatedAt: 1,
          evolutionMomentum: 0.7,
          learningReadiness: 0.8,
          contradictionPressure: 0,
          revisionPressure: 0,
          autobiographicalStability: 0.7,
          dominantTrajectory: 'steady line',
          relationshipDoctrine: 'repair first',
          latestInflection: 'stable',
          burdenLine: null,
          trustMeaning: null,
          nextLearningAction: 'reflect',
          nextLearningReason: null,
          shouldRecord: false,
          shouldReflect: true,
          shouldVerify: false,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['repair'],
          sourceSignals: [],
          summary: 'steady line',
        },
        affectiveResidue: {
          version: 'affective-residue-memory-v1',
          updatedAt: 1,
          residues: [],
          dominantResidueKind: 'repair',
          afterglowPressure: 0.1,
          repairPressure: 0.6,
          burdenPressure: 0.1,
          trustPressure: 0.3,
          restProtectivePressure: 0.2,
          relationshipCadence: {
            cadenceMode: 'cooldown',
            distancePosture: 'measured-room',
            companionshipDensity: 0.2,
            repairRecovery: 0.6,
            overreachRisk: 0.2,
            fatigueGuard: 0.2,
            afterglowCarry: 0.1,
            shouldDelayWarmth: true,
            shouldProtectRest: false,
            reasonTags: [],
            summary: 'repair first',
          },
          sourceSignals: [],
          summary: 'repair first',
        },
        learningExecutionState: {
          currentTaskId: null,
          currentStatus: 'scheduled',
          currentAttemptCount: 0,
          currentMaxAttempts: 0,
          currentNextRetryAt: null,
          currentBlockedReason: null,
          currentFailureKind: null,
          nextLearningAction: 'reflect',
          shouldRecord: false,
          shouldReflect: true,
          shouldVerify: false,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['repair'],
          queuedTaskCount: 1,
          runningTaskCount: 0,
          blockedTaskCount: 0,
          recentTaskIds: [],
          lastCompletedTaskId: null,
          lastCompletedAction: null,
          lastCompletedSummary: null,
          lastFailureTaskId: null,
          lastFailureKind: null,
          lastFailureReason: null,
          lastFailureNextRetryAt: null,
          updatedAt: 1,
        },
        recallLatencyPolicy: {
          version: 'recall-latency-policy-v1',
          budgetClass: 'realtime-reply',
          latencyClass: 'balanced',
          recallAction: 'stable-core-only',
          degradeReason: null,
          domainBudgets: [],
          hotPathKey: null,
          shouldUseHotCache: true,
          shouldPrefetch: false,
          shouldAvoidDeepExpansion: true,
          shouldEmitFollowUpAffordance: false,
          confidence: 0.8,
          reasonTags: [],
          summary: 'balanced',
        },
        recollectionPlan: {
          opening: 'runtime seam',
        } as any,
        recollectionSpeechPlan: {
          surfaceMode: 'procedural-carry',
        } as any,
        memoryDeliberation: {
          surfacePolicy: 'procedural-carry',
        },
        dialogueRhythm: {
          relationshipDoctrine: 'repair first',
        },
        summary: 'steady line',
      },
      mainResolutionLedger: {
        version: 'memory-resolution-ledger-v1',
        producedAt: 1,
        dominantClusterId: null,
        dominantClusterSummary: 'runtime seam',
        competingClusterId: null,
        competingClusterSummary: null,
        candidates: [],
        selectedCandidates: [],
        rejectedCandidates: [],
        finalSurfacePolicy: 'procedural-carry',
        shouldStayInward: false,
        shouldDelayUntilAfterPayoff: false,
        stableCoreOnly: true,
        suppressionTags: [],
        closureState: 'grounded-recall',
        surfaceConfidence: 0.88,
        shouldLabelUncertainty: false,
        visibleCarryMode: 'tone-carry',
        conflictPressure: 'none',
        retrievalQuality: 'high',
        finalRationale: null,
      },
      browserResolutionLedger: {
        version: 'memory-resolution-ledger-v1',
        producedAt: 2,
        dominantClusterId: null,
        dominantClusterSummary: 'runtime seam',
        competingClusterId: null,
        competingClusterSummary: null,
        candidates: [],
        selectedCandidates: [],
        rejectedCandidates: [],
        finalSurfacePolicy: 'procedural-carry',
        shouldStayInward: false,
        shouldDelayUntilAfterPayoff: false,
        stableCoreOnly: true,
        suppressionTags: [],
        closureState: 'grounded-recall',
        surfaceConfidence: 0.88,
        shouldLabelUncertainty: false,
        visibleCarryMode: 'tone-carry',
        conflictPressure: 'none',
        retrievalQuality: 'high',
        finalRationale: null,
      },
    })

    expect(summary.passed).toBe(true)
    expect(summary.divergentFieldCount).toBe(0)
  })

  it('reports first divergent layer and field-level diffs', () => {
    const summary = deriveAlicizationBrowserMainParitySummary({
      mainBundle: {
        version: 'derived-mind-state-bundle-v1',
        source: 'main-runtime',
        producedAt: 1,
        learningExecutionState: {
          currentTaskId: null,
          currentStatus: 'running',
          currentAttemptCount: 1,
          currentMaxAttempts: 3,
          currentNextRetryAt: null,
          currentBlockedReason: null,
          currentFailureKind: null,
          nextLearningAction: 'verify',
          shouldRecord: false,
          shouldReflect: false,
          shouldVerify: true,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['world-model'],
          queuedTaskCount: 0,
          runningTaskCount: 1,
          blockedTaskCount: 0,
          recentTaskIds: [],
          lastCompletedTaskId: null,
          lastCompletedAction: null,
          lastCompletedSummary: null,
          lastFailureTaskId: null,
          lastFailureKind: null,
          lastFailureReason: null,
          lastFailureNextRetryAt: null,
          updatedAt: 1,
        },
        summary: 'main',
      },
      browserBundle: {
        version: 'derived-mind-state-bundle-v1',
        source: 'browser-fallback',
        producedAt: 2,
        learningExecutionState: {
          currentTaskId: null,
          currentStatus: 'scheduled',
          currentAttemptCount: 0,
          currentMaxAttempts: 0,
          currentNextRetryAt: null,
          currentBlockedReason: null,
          currentFailureKind: null,
          nextLearningAction: 'reflect',
          shouldRecord: false,
          shouldReflect: true,
          shouldVerify: false,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['relationship'],
          queuedTaskCount: 1,
          runningTaskCount: 0,
          blockedTaskCount: 0,
          recentTaskIds: [],
          lastCompletedTaskId: null,
          lastCompletedAction: null,
          lastCompletedSummary: null,
          lastFailureTaskId: null,
          lastFailureKind: null,
          lastFailureReason: null,
          lastFailureNextRetryAt: null,
          updatedAt: 2,
        },
        summary: 'browser',
      },
    })

    expect(summary.passed).toBe(false)
    expect(summary.firstDivergentLayer).toBe('bundle')
    expect(summary.divergentFields).toEqual(expect.arrayContaining([
      expect.objectContaining({
        field: 'bundle.summary',
        layer: 'bundle',
      }),
      expect.objectContaining({
        field: 'learningExecution.nextLearningAction',
        layer: 'learning-execution',
      }),
    ]))
  })

  it('compares situation candidates and claim evidence graphs deeply', () => {
    const summary = deriveAlicizationBrowserMainParitySummary({
      mainBundle: {
        version: 'derived-mind-state-bundle-v1',
        source: 'main-runtime',
        producedAt: 1,
        learningExecutionState: {
          currentTaskId: 'task-1',
          currentStatus: 'running',
          currentAttemptCount: 1,
          currentMaxAttempts: 3,
          currentNextRetryAt: null,
          currentBlockedReason: null,
          currentFailureKind: null,
          nextLearningAction: 'internalize',
          shouldRecord: false,
          shouldReflect: false,
          shouldVerify: false,
          shouldRevise: false,
          shouldInternalize: true,
          activeLearningFocuses: ['world-model'],
          queuedTaskCount: 0,
          runningTaskCount: 1,
          blockedTaskCount: 0,
          recentTaskIds: ['task-1'],
          lastCompletedTaskId: 'task-0',
          lastCompletedAction: 'verify',
          lastCompletedSummary: 'verified world model',
          lastFailureTaskId: null,
          lastFailureKind: null,
          lastFailureReason: null,
          lastFailureNextRetryAt: null,
          updatedAt: 1,
        },
        claimEvidenceGraphs: [{
          version: 'claim-evidence-graph-v1',
          producedAt: 1,
          claimId: 'claim-1',
          claim: 'screenReferenceMode accepts required and avoid',
          domain: 'world-model',
          supportingEvidence: [],
          contradictingEvidence: [],
          supersededBy: [],
          currentBelief: 'screenReferenceMode accepts required and avoid',
          validationState: 'validated',
          sourceTrust: 0.82,
          lastRevalidatedAt: 1,
          revalidationPolicy: {
            shouldRevalidate: false,
            nextRevalidationAt: null,
            expiredSourceIds: [],
            reasonTags: [],
          },
          internalizationDecision: {
            mayInternalize: false,
            mayValidateOnly: true,
            blockedReasons: [],
          },
        }],
        summary: 'main',
      },
      browserBundle: {
        version: 'derived-mind-state-bundle-v1',
        source: 'browser-fallback',
        producedAt: 2,
        learningExecutionState: {
          currentTaskId: 'task-1',
          currentStatus: 'blocked',
          currentAttemptCount: 1,
          currentMaxAttempts: 3,
          currentNextRetryAt: null,
          currentBlockedReason: 'revalidation-required',
          currentFailureKind: null,
          nextLearningAction: 'verify',
          shouldRecord: false,
          shouldReflect: false,
          shouldVerify: true,
          shouldRevise: false,
          shouldInternalize: false,
          activeLearningFocuses: ['world-model'],
          queuedTaskCount: 1,
          runningTaskCount: 0,
          blockedTaskCount: 1,
          recentTaskIds: ['task-1'],
          lastCompletedTaskId: null,
          lastCompletedAction: null,
          lastCompletedSummary: null,
          lastFailureTaskId: null,
          lastFailureKind: null,
          lastFailureReason: null,
          lastFailureNextRetryAt: null,
          updatedAt: 2,
        },
        claimEvidenceGraphs: [{
          version: 'claim-evidence-graph-v1',
          producedAt: 2,
          claimId: 'claim-1',
          claim: 'screenReferenceMode accepts required and avoid',
          domain: 'world-model',
          supportingEvidence: [],
          contradictingEvidence: [],
          supersededBy: [],
          currentBelief: 'screenReferenceMode accepts required and avoid',
          validationState: 'expired',
          sourceTrust: 0.42,
          lastRevalidatedAt: null,
          revalidationPolicy: {
            shouldRevalidate: true,
            nextRevalidationAt: 9,
            expiredSourceIds: ['fact-1'],
            reasonTags: ['world-model-revalidation-required'],
          },
          internalizationDecision: {
            mayInternalize: false,
            mayValidateOnly: false,
            blockedReasons: ['revalidation-required'],
          },
        }],
        summary: 'browser',
      },
      mainMemorySituationCandidates: {
        version: 'memory-situation-candidates-v1',
        producedAt: 1,
        queryTexts: ['runtime repair'],
        candidates: [{
          candidateId: 'cand-1',
          sourceKinds: ['event-graph'],
          situationKind: 'repair-arc',
          eraKey: null,
          relationshipArcKey: null,
          procedureKey: null,
          selfModelKey: null,
          worldClaimKeys: [],
          selectedEvidenceIds: ['event-1'],
          competingCandidateIds: ['cand-2'],
          suppressionReasons: [],
          confidence: 0.84,
          latencyCost: 0.2,
          status: 'selected',
          statusReason: 'main winner',
          summary: 'repair path',
          evidenceSummary: null,
        }],
        selected: [],
        rejected: [],
        suppressed: [],
        delayed: [],
        unresolved: [],
      },
      browserMemorySituationCandidates: {
        version: 'memory-situation-candidates-v1',
        producedAt: 2,
        queryTexts: ['runtime repair'],
        candidates: [{
          candidateId: 'cand-2',
          sourceKinds: ['fact'],
          situationKind: 'procedure',
          eraKey: null,
          relationshipArcKey: null,
          procedureKey: null,
          selfModelKey: null,
          worldClaimKeys: [],
          selectedEvidenceIds: ['fact-1'],
          competingCandidateIds: ['cand-1'],
          suppressionReasons: [],
          confidence: 0.72,
          latencyCost: 0.12,
          status: 'selected',
          statusReason: 'browser winner',
          summary: 'fact path',
          evidenceSummary: null,
        }],
        selected: [],
        rejected: [],
        suppressed: [],
        delayed: [],
        unresolved: [],
      },
      mainLearningArtifacts: [{
        decisionTraceId: 'trace-main',
        turnId: 'turn-main',
        sessionId: 'session-main',
        taskId: 'learning:world:1',
        artifactId: 'artifact-main',
        claimId: 'claim-1',
        action: 'verify',
        domain: 'world-model',
        resultSummary: 'main verified artifact',
        verificationBasis: ['existing-memory'],
        sourceFactIds: ['fact-1'],
        verifiedArtifact: {
          version: 'verified-learning-artifact-v1',
          artifactId: 'artifact-main',
          taskId: 'learning:world:1',
          action: 'verify',
          domain: 'world-model',
          verifier: {
            kind: 'world-model-verifier',
            mayVerify: true,
            mayInternalize: false,
            mayValidateOnly: true,
            rollbackRequired: false,
            blockedReasons: [],
          },
          status: 'downgraded',
          producedAt: 1,
          claimGraph: {
            version: 'claim-evidence-graph-v1',
            producedAt: 1,
            claimId: 'claim-1',
            claim: 'screenReferenceMode accepts required and avoid',
            domain: 'world-model',
            supportingEvidence: [],
            contradictingEvidence: [],
            supersededBy: [],
            currentBelief: 'screenReferenceMode accepts required and avoid',
            validationState: 'validated',
            sourceTrust: 0.82,
            lastRevalidatedAt: 1,
            revalidationPolicy: {
              shouldRevalidate: false,
              nextRevalidationAt: null,
              expiredSourceIds: [],
              reasonTags: [],
            },
            internalizationDecision: {
              mayInternalize: false,
              mayValidateOnly: true,
              blockedReasons: [],
            },
          },
          verificationBasis: ['existing-memory'],
          supportingFactIds: ['fact-1'],
          contradictionFactIds: [],
          internalizationStage: 'validated-knowledge',
          reason: 'stable enough to validate',
        },
        createdAt: 1,
      }],
      browserLearningArtifacts: [{
        decisionTraceId: 'trace-browser',
        turnId: 'turn-browser',
        sessionId: 'session-browser',
        taskId: 'learning:world:1',
        artifactId: 'artifact-browser',
        claimId: 'claim-1',
        action: 'verify',
        domain: 'world-model',
        resultSummary: 'browser blocked artifact',
        verificationBasis: ['conflict-review'],
        sourceFactIds: ['fact-1'],
        verifiedArtifact: {
          version: 'verified-learning-artifact-v1',
          artifactId: 'artifact-browser',
          taskId: 'learning:world:1',
          action: 'verify',
          domain: 'world-model',
          verifier: {
            kind: 'world-model-verifier',
            mayVerify: false,
            mayInternalize: false,
            mayValidateOnly: false,
            rollbackRequired: false,
            blockedReasons: ['revalidation-required'],
          },
          status: 'blocked',
          producedAt: 2,
          claimGraph: {
            version: 'claim-evidence-graph-v1',
            producedAt: 2,
            claimId: 'claim-1',
            claim: 'screenReferenceMode accepts required and avoid',
            domain: 'world-model',
            supportingEvidence: [],
            contradictingEvidence: [],
            supersededBy: [],
            currentBelief: 'screenReferenceMode accepts required and avoid',
            validationState: 'expired',
            sourceTrust: 0.42,
            lastRevalidatedAt: null,
            revalidationPolicy: {
              shouldRevalidate: true,
              nextRevalidationAt: 9,
              expiredSourceIds: ['fact-1'],
              reasonTags: ['world-model-revalidation-required'],
            },
            internalizationDecision: {
              mayInternalize: false,
              mayValidateOnly: false,
              blockedReasons: ['revalidation-required'],
            },
          },
          verificationBasis: ['conflict-review'],
          supportingFactIds: ['fact-1'],
          contradictionFactIds: [],
          internalizationStage: 'working-understanding',
          reason: 'needs revalidation',
        },
        createdAt: 2,
      }],
      mainTracePointer: {
        decisionTraceId: 'trace-main',
        turnId: 'turn-main',
        sessionId: 'session-main',
      },
      browserTracePointer: {
        decisionTraceId: 'trace-browser',
        turnId: 'turn-browser',
        sessionId: 'session-browser',
      },
    })

    expect(summary.passed).toBe(false)
    expect(summary.divergentLayers).toEqual(expect.arrayContaining([
      'situation-candidates',
      'claim-evidence',
      'learning-causal-chain',
    ]))
    expect(summary.divergentFields).toEqual(expect.arrayContaining([
      expect.objectContaining({
        field: 'situationCandidates.candidate.cand-1.status',
        layer: 'situation-candidates',
      }),
      expect.objectContaining({
        field: 'claimEvidence.claim.claim-1.validationState',
        layer: 'claim-evidence',
      }),
      expect.objectContaining({
        field: 'learningCausalChain.currentStatus',
        layer: 'learning-causal-chain',
      }),
      expect.objectContaining({
        field: 'learningArtifacts.artifactIds',
        layer: 'learning-causal-chain',
      }),
      expect.objectContaining({
        field: 'tracePointer.decisionTraceId',
        layer: 'learning-causal-chain',
      }),
    ]))
  })

  it('normalizes persistent body-kernel state fields without inventing second-mind authority', () => {
    const state = normalizeAlicizationDerivedMindStateBundle({
      source: 'browser-fallback',
      producedAt: 1,
      visualPresenceState: {
        watchMode: 'symbiotic-vision',
        updatedAt: 1,
        currentBodyState: 'idle',
        continuityMode: 'ambient-covision',
        quietLineMs: 120000,
        currentInwardPreoccupation: 'host sustained focus',
      },
    })

    expect(state?.visualPresenceState?.currentBodyState).toBe('idle')
    expect(state?.visualPresenceState?.continuityMode).toBe('ambient-covision')
    expect(state?.visualPresenceState?.currentInwardPreoccupation).toBe('host sustained focus')
  })

  it('keeps top-level bundle metadata strict when visual presence state is present', () => {
    const state = normalizeAlicizationDerivedMindStateBundle({
      visualPresenceState: {
        watchMode: 'symbiotic-vision',
        updatedAt: 1,
        currentBodyState: 'idle',
        continuityMode: 'ambient-covision',
        quietLineMs: 120000,
        currentInwardPreoccupation: 'host sustained focus',
      },
    })

    expect(state).toBeNull()
  })
})
